BEGIN;
LOCK TABLE fixed_asset_disposal_evidence IN SHARE MODE;
DO $$ BEGIN
 IF EXISTS(SELECT 1 FROM audit_event WHERE event_type='FIXED_ASSET_DISPOSAL_REVIEWED' AND metadata->>'lineage_version'='POSTED_DISPOSAL_LINES_V2') THEN
  RAISE EXCEPTION 'Cannot remove full disposal lineage with retained evidence' USING ERRCODE='55006';
 END IF;
END; $$;

CREATE OR REPLACE FUNCTION refs_review_fixed_asset_disposal(p_tenant uuid,p_entity uuid,p_register uuid,p_period uuid,p_source uuid,p_date date,p_accum numeric,p_proceeds numeric,p_reason text,p_idempotency_key text,p_request_hash text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE actor text:=refs_current_actor();asset fixed_asset_register_evidence;source source_document;idem idempotency_receipt;period accounting_period;credit numeric(20,4);je_ids uuid[];jl_ids uuid[];ll_ids uuid[];carrying numeric(20,4);gain_loss numeric(20,4);evidence_hash text;disposal_id uuid:=gen_random_uuid();payload jsonb;result jsonb;
BEGIN
  PERFORM refs_assert_scope(p_tenant,p_entity,'FIXED_ASSET.DISPOSAL.REVIEW');IF actor IS NULL THEN RAISE EXCEPTION 'Authenticated disposal reviewer missing' USING ERRCODE='42501';END IF;
  evidence_hash:=refs_review_fixed_asset_disposal_hash(p_tenant,p_entity,p_register,p_period,p_source,p_date,p_accum,p_proceeds,p_reason);IF p_request_hash IS DISTINCT FROM evidence_hash OR p_accum IS NULL OR p_proceeds IS NULL OR p_accum<0 OR p_proceeds<0 OR length(btrim(COALESCE(p_reason,''))) NOT BETWEEN 8 AND 2000 THEN RAISE EXCEPTION 'Disposal review payload is invalid or non-canonical' USING ERRCODE='22023';END IF;
  INSERT INTO idempotency_receipt(tenant_id,operation_scope,idempotency_key,request_hash,status,actor_id) VALUES(p_tenant,'FIXED_ASSET_DISPOSAL_REVIEW:'||p_entity,p_idempotency_key,p_request_hash,'IN_PROGRESS',actor) ON CONFLICT(tenant_id,operation_scope,idempotency_key) DO NOTHING;SELECT * INTO idem FROM idempotency_receipt WHERE tenant_id=p_tenant AND operation_scope='FIXED_ASSET_DISPOSAL_REVIEW:'||p_entity AND idempotency_key=p_idempotency_key FOR UPDATE;IF idem.request_hash<>p_request_hash OR idem.actor_id IS DISTINCT FROM actor THEN RAISE EXCEPTION 'Disposal review idempotency conflict' USING ERRCODE='23505';END IF;IF idem.status='SUCCEEDED' THEN RETURN idem.response_body||jsonb_build_object('idempotent',true);END IF;
  SELECT * INTO asset FROM fixed_asset_register_evidence WHERE tenant_id=p_tenant AND entity_id=p_entity AND fixed_asset_register_evidence_id=p_register FOR SHARE;IF NOT FOUND OR asset.status<>'ACTIVE' OR asset.reviewed_by=actor OR p_date<asset.placed_in_service_date OR p_accum>asset.cost_basis THEN RAISE EXCEPTION 'Independent disposal review requires active asset evidence, valid dates and a different actor' USING ERRCODE='23514';END IF;
  SELECT * INTO period FROM accounting_period WHERE tenant_id=p_tenant AND entity_id=p_entity AND period_id=p_period AND ledger_code='PRIMARY' FOR SHARE;IF NOT FOUND OR p_date NOT BETWEEN period.starts_on AND period.ends_on THEN RAISE EXCEPTION 'Disposal date must be in the exact primary accounting period' USING ERRCODE='23514';END IF;
  SELECT * INTO source FROM source_document WHERE tenant_id=p_tenant AND entity_id=p_entity AND source_document_id=p_source FOR SHARE;IF NOT FOUND OR source.version<1 OR source.status NOT IN('READY_FOR_DRAFT','DRAFT_CREATED','PENDING_JE_REVIEW','PENDING_JE_APPROVAL','APPROVED','POSTED') THEN RAISE EXCEPTION 'Retained disposal source is missing or unavailable' USING ERRCODE='23514';END IF;
  SELECT sum(l.credit_amount-l.debit_amount)::numeric(20,4),array_agg(DISTINCT l.journal_entry_id ORDER BY l.journal_entry_id),array_agg(DISTINCT l.journal_line_id ORDER BY l.journal_line_id),array_agg(DISTINCT l.ledger_line_id ORDER BY l.ledger_line_id) INTO credit,je_ids,jl_ids,ll_ids FROM ledger_line l JOIN journal_entry j ON j.tenant_id=l.tenant_id AND j.entity_id=l.entity_id AND j.journal_entry_id=l.journal_entry_id AND j.status='POSTED' WHERE l.tenant_id=p_tenant AND l.entity_id=p_entity AND l.account_code=asset.asset_account_code AND l.dimensions->>'fixed_asset_register_evidence_id'=p_register::text AND j.journal_date BETWEEN period.starts_on AND period.ends_on AND l.credit_amount>l.debit_amount;
  IF credit IS NULL OR credit<>asset.cost_basis THEN RAISE EXCEPTION 'Posted asset credit must exactly equal the reviewed disposed cost' USING ERRCODE='23514';END IF;carrying:=asset.cost_basis-p_accum;gain_loss:=p_proceeds-carrying;
  INSERT INTO fixed_asset_disposal_evidence(fixed_asset_disposal_evidence_id,tenant_id,entity_id,fixed_asset_register_evidence_id,accounting_period_id,disposal_source_document_id,disposal_source_payload_hash,disposal_date,currency,disposed_cost,accumulated_depreciation,carrying_value,proceeds,gain_or_loss,posted_asset_credit,journal_entry_ids,journal_line_ids,ledger_line_ids,reviewed_by,review_reason,disposal_evidence_hash,status) VALUES(disposal_id,p_tenant,p_entity,p_register,p_period,p_source,source.payload_hash,p_date,asset.currency,asset.cost_basis,p_accum,carrying,p_proceeds,gain_loss,credit,je_ids,jl_ids,ll_ids,actor,btrim(p_reason),evidence_hash,'REVIEWED');
  payload:=jsonb_build_object('schema_version','FIXED_ASSET_DISPOSAL_EVIDENCE_V1','fixed_asset_disposal_evidence_id',disposal_id,'fixed_asset_register_evidence_id',p_register,'accounting_period_id',p_period,'disposal_source_document_id',p_source,'disposal_source_payload_hash',source.payload_hash,'disposal_date',p_date,'currency',asset.currency,'disposed_cost',to_char(asset.cost_basis,'FM999999999999990.0000'),'accumulated_depreciation',to_char(p_accum,'FM999999999999990.0000'),'carrying_value',to_char(carrying,'FM999999999999990.0000'),'proceeds',to_char(p_proceeds,'FM999999999999990.0000'),'gain_or_loss',to_char(gain_loss,'FM999999999999990.0000'),'posted_asset_credit',to_char(credit,'FM999999999999990.0000'),'journal_entry_ids',je_ids,'journal_line_ids',jl_ids,'ledger_line_ids',ll_ids,'disposal_evidence_hash',evidence_hash,'status','REVIEWED','can_create_draft',false,'can_review',false,'can_approve',false,'can_post',false);
  INSERT INTO audit_event(tenant_id,entity_id,event_type,object_type,object_id,action,actor_id,actor_type,permission_used,request_id,correlation_id,idempotency_key,after_hash,reason,metadata) VALUES(p_tenant,p_entity,'FIXED_ASSET_DISPOSAL_REVIEWED','FIXED_ASSET_DISPOSAL_EVIDENCE',disposal_id,'REVIEW',actor,'USER','FIXED_ASSET.DISPOSAL.REVIEW',p_idempotency_key,p_idempotency_key,p_idempotency_key,evidence_hash,btrim(p_reason),payload);INSERT INTO outbox_event(tenant_id,entity_id,aggregate_type,aggregate_id,event_type,payload,payload_hash) VALUES(p_tenant,p_entity,'FIXED_ASSET_DISPOSAL_EVIDENCE',disposal_id,'FIXED_ASSET_DISPOSAL_REVIEWED',payload,refs_jsonb_hash(payload));result:=payload||jsonb_build_object('idempotent',false);UPDATE idempotency_receipt SET status='SUCCEEDED',response_status=201,response_body=result,completed_at=clock_timestamp() WHERE idempotency_receipt_id=idem.idempotency_receipt_id;RETURN result;
END;$$;

CREATE OR REPLACE FUNCTION refs_review_fixed_asset_impairment(p_tenant uuid,p_entity uuid,p_register uuid,p_period uuid,p_source uuid,p_date date,p_recoverable numeric,p_expense text,p_accumulated text,p_reason text,p_idempotency_key text,p_request_hash text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE actor text:=refs_current_actor();asset fixed_asset_register_evidence;period accounting_period;source source_document;idem idempotency_receipt;carrying numeric(20,4);loss numeric(20,4);je_ids uuid[];jl_ids uuid[];ll_ids uuid[];assessment_id uuid:=gen_random_uuid();evidence_hash text;payload jsonb;result jsonb;
BEGIN
  PERFORM refs_assert_scope(p_tenant,p_entity,'FIXED_ASSET.IMPAIRMENT.REVIEW');IF actor IS NULL THEN RAISE EXCEPTION 'Authenticated impairment reviewer missing' USING ERRCODE='42501';END IF;evidence_hash:=refs_review_fixed_asset_impairment_hash(p_tenant,p_entity,p_register,p_period,p_source,p_date,p_recoverable,p_expense,p_accumulated,p_reason);IF p_request_hash IS DISTINCT FROM evidence_hash OR p_recoverable IS NULL OR p_recoverable<0 OR btrim(COALESCE(p_expense,''))='' OR btrim(COALESCE(p_accumulated,''))='' OR btrim(p_expense)=btrim(p_accumulated) OR length(btrim(COALESCE(p_reason,''))) NOT BETWEEN 8 AND 2000 THEN RAISE EXCEPTION 'Impairment review payload is invalid or non-canonical' USING ERRCODE='22023';END IF;
  INSERT INTO idempotency_receipt(tenant_id,operation_scope,idempotency_key,request_hash,status,actor_id) VALUES(p_tenant,'FIXED_ASSET_IMPAIRMENT_REVIEW:'||p_entity,p_idempotency_key,p_request_hash,'IN_PROGRESS',actor) ON CONFLICT(tenant_id,operation_scope,idempotency_key) DO NOTHING;SELECT * INTO idem FROM idempotency_receipt WHERE tenant_id=p_tenant AND operation_scope='FIXED_ASSET_IMPAIRMENT_REVIEW:'||p_entity AND idempotency_key=p_idempotency_key FOR UPDATE;IF idem.request_hash<>p_request_hash OR idem.actor_id IS DISTINCT FROM actor THEN RAISE EXCEPTION 'Impairment review idempotency conflict' USING ERRCODE='23505';END IF;IF idem.status='SUCCEEDED' THEN RETURN idem.response_body||jsonb_build_object('idempotent',true);END IF;
  SELECT * INTO asset FROM fixed_asset_register_evidence WHERE tenant_id=p_tenant AND entity_id=p_entity AND fixed_asset_register_evidence_id=p_register FOR SHARE;IF NOT FOUND OR asset.status<>'ACTIVE' OR asset.reviewed_by=actor OR p_date<asset.placed_in_service_date THEN RAISE EXCEPTION 'Independent impairment review requires active asset evidence, a valid date and different actor' USING ERRCODE='23514';END IF;SELECT * INTO period FROM accounting_period WHERE tenant_id=p_tenant AND entity_id=p_entity AND period_id=p_period AND ledger_code='PRIMARY' FOR SHARE;IF NOT FOUND OR p_date NOT BETWEEN period.starts_on AND period.ends_on THEN RAISE EXCEPTION 'Assessment date must be in exact primary period' USING ERRCODE='23514';END IF;SELECT * INTO source FROM source_document WHERE tenant_id=p_tenant AND entity_id=p_entity AND source_document_id=p_source FOR SHARE;IF NOT FOUND OR source.version<1 OR source.status NOT IN('READY_FOR_DRAFT','DRAFT_CREATED','PENDING_JE_REVIEW','PENDING_JE_APPROVAL','APPROVED','POSTED') THEN RAISE EXCEPTION 'Retained valuation source is unavailable' USING ERRCODE='23514';END IF;
  PERFORM 1 FROM account_master WHERE tenant_id=p_tenant AND entity_id=p_entity AND account_code=btrim(p_expense) AND active FOR SHARE;IF NOT FOUND THEN RAISE EXCEPTION 'Impairment expense account is missing or inactive' USING ERRCODE='23503';END IF;PERFORM 1 FROM account_master WHERE tenant_id=p_tenant AND entity_id=p_entity AND account_code=btrim(p_accumulated) AND active FOR SHARE;IF NOT FOUND THEN RAISE EXCEPTION 'Accumulated impairment account is missing or inactive' USING ERRCODE='23503';END IF;
  SELECT sum(CASE WHEN l.account_code=asset.asset_account_code THEN l.debit_amount-l.credit_amount WHEN l.account_code IN(asset.accumulated_depreciation_account_code,btrim(p_accumulated)) THEN l.debit_amount-l.credit_amount ELSE 0 END)::numeric(20,4),array_agg(DISTINCT l.journal_entry_id ORDER BY l.journal_entry_id),array_agg(DISTINCT l.journal_line_id ORDER BY l.journal_line_id),array_agg(DISTINCT l.ledger_line_id ORDER BY l.ledger_line_id) INTO carrying,je_ids,jl_ids,ll_ids FROM ledger_line l JOIN journal_entry j ON j.tenant_id=l.tenant_id AND j.entity_id=l.entity_id AND j.journal_entry_id=l.journal_entry_id AND j.status='POSTED' WHERE l.tenant_id=p_tenant AND l.entity_id=p_entity AND l.dimensions->>'fixed_asset_register_evidence_id'=p_register::text AND l.account_code IN(asset.asset_account_code,asset.accumulated_depreciation_account_code,btrim(p_accumulated)) AND j.journal_date<=p_date;
  IF carrying IS NULL OR carrying<0 THEN RAISE EXCEPTION 'Asset-bound Posted carrying value is unavailable or invalid' USING ERRCODE='23514';END IF;loss:=greatest(carrying-p_recoverable,0);
  INSERT INTO fixed_asset_impairment_assessment_evidence(fixed_asset_impairment_assessment_evidence_id,tenant_id,entity_id,fixed_asset_register_evidence_id,accounting_period_id,valuation_source_document_id,valuation_source_payload_hash,assessment_date,currency,posted_carrying_value,recoverable_amount,impairment_loss,impairment_expense_account_code,accumulated_impairment_account_code,journal_entry_ids,journal_line_ids,ledger_line_ids,reviewed_by,review_reason,impairment_assessment_hash,status) VALUES(assessment_id,p_tenant,p_entity,p_register,p_period,p_source,source.payload_hash,p_date,asset.currency,carrying,p_recoverable,loss,btrim(p_expense),btrim(p_accumulated),je_ids,jl_ids,ll_ids,actor,btrim(p_reason),evidence_hash,'INDEPENDENTLY_REVIEWED');
  payload:=jsonb_build_object('schema_version','FIXED_ASSET_IMPAIRMENT_ASSESSMENT_EVIDENCE_V1','impairment_assessment_evidence_id',assessment_id,'fixed_asset_register_evidence_id',p_register,'accounting_period_id',p_period,'valuation_source_document_id',p_source,'valuation_source_payload_hash',source.payload_hash,'assessment_date',p_date,'currency',asset.currency,'posted_carrying_value',to_char(carrying,'FM999999999999990.0000'),'recoverable_amount',to_char(p_recoverable,'FM999999999999990.0000'),'impairment_loss',to_char(loss,'FM999999999999990.0000'),'impairment_expense_account_code',btrim(p_expense),'accumulated_impairment_account_code',btrim(p_accumulated),'journal_entry_ids',je_ids,'journal_line_ids',jl_ids,'ledger_line_ids',ll_ids,'impairment_assessment_hash',evidence_hash,'status','INDEPENDENTLY_REVIEWED','can_create_draft',false,'can_review',false,'can_approve',false,'can_post',false);INSERT INTO audit_event(tenant_id,entity_id,event_type,object_type,object_id,action,actor_id,actor_type,permission_used,request_id,correlation_id,idempotency_key,after_hash,reason,metadata) VALUES(p_tenant,p_entity,'FIXED_ASSET_IMPAIRMENT_REVIEWED','FIXED_ASSET_IMPAIRMENT_ASSESSMENT',assessment_id,'REVIEW',actor,'USER','FIXED_ASSET.IMPAIRMENT.REVIEW',p_idempotency_key,p_idempotency_key,p_idempotency_key,evidence_hash,btrim(p_reason),payload);INSERT INTO outbox_event(tenant_id,entity_id,aggregate_type,aggregate_id,event_type,payload,payload_hash) VALUES(p_tenant,p_entity,'FIXED_ASSET_IMPAIRMENT_ASSESSMENT',assessment_id,'FIXED_ASSET_IMPAIRMENT_REVIEWED',payload,refs_jsonb_hash(payload));result:=payload||jsonb_build_object('idempotent',false);UPDATE idempotency_receipt SET status='SUCCEEDED',response_status=201,response_body=result,completed_at=clock_timestamp() WHERE idempotency_receipt_id=idem.idempotency_receipt_id;RETURN result;
END;$$;

COMMIT;
