BEGIN;

CREATE OR REPLACE FUNCTION refs_create_unit_transfer(
 p_tenant uuid,p_source_entity uuid,p_target_entity uuid,p_source_period uuid,p_target_period uuid,p_date date,p_unit text,
 p_source_document uuid,p_source_line uuid,p_expected_source_version bigint,p_expected_source_hash text,p_expected_source_line_hash text,p_expected_source_attachment_hash text,p_expected_transfer_price numeric,p_source_mapping uuid,p_expected_source_mapping_hash text,
 p_target_mapping uuid,p_expected_target_mapping_hash text,p_source_carrying_accounts text[],p_source_gain_loss_account text,p_target_inventory_account text,
 p_expected_carrying numeric,p_expected_unit_version bigint,p_target_attachments uuid[],p_expected_target_attachment_hash text,p_source_number text,p_target_number text,p_reason text,p_idempotency_key text,p_request_hash text
) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE actor text:=refs_current_actor();idem idempotency_receipt;source_period accounting_period;target_period accounting_period;source_document source_document;source_line source_document_line;
 source_map mapping_snapshot;target_map mapping_snapshot;source_entity_row entity;target_entity_row entity;source_due text;target_due text;source_affiliate text;target_affiliate text;currency char(3);carrying numeric(20,4);price numeric(20,4);margin numeric(20,4);
 attachments uuid[];target_attachments uuid[];attachment_hash text;target_attachment_hash text;cost_line_ids uuid[];cost_basis_hash text;cost_snapshot jsonb;cost_layers jsonb;layer_lines jsonb;dims jsonb;source_lines jsonb;target_lines jsonb;source_result jsonb;target_result jsonb;source_journal uuid;target_journal uuid;
 source_snapshot text;target_snapshot text;pair_id uuid:=gen_random_uuid();unit_control unit_transfer_unit_control;evidence text;payload jsonb;inner_hash text;
BEGIN
 PERFORM refs_assert_scope(p_tenant,p_source_entity,'REAL_ESTATE.UNIT_TRANSFER.CREATE');PERFORM refs_assert_scope(p_tenant,p_target_entity,'REAL_ESTATE.UNIT_TRANSFER.CREATE');
 PERFORM refs_assert_scope(p_tenant,p_source_entity,'GL.JE.CREATE');PERFORM refs_assert_scope(p_tenant,p_target_entity,'GL.JE.CREATE');
 PERFORM refs_assert_scope(p_tenant,p_source_entity,'GL.JE.VIEW');PERFORM refs_assert_scope(p_tenant,p_target_entity,'GL.JE.VIEW');
 IF actor IS NULL OR p_source_entity IS NULL OR p_target_entity IS NULL OR p_source_entity=p_target_entity OR p_date IS NULL OR p_expected_source_version IS NULL OR p_expected_source_version<0
  OR p_expected_source_hash IS NULL OR p_expected_source_hash!~'^sha256:[0-9a-f]{64}$' OR p_expected_source_line_hash IS NULL OR p_expected_source_line_hash!~'^sha256:[0-9a-f]{64}$' OR p_expected_source_attachment_hash IS NULL OR p_expected_source_attachment_hash!~'^sha256:[0-9a-f]{64}$'
  OR p_expected_transfer_price IS NULL OR p_expected_transfer_price<=0 OR p_expected_transfer_price>=10000000000000000 OR p_expected_transfer_price<>round(p_expected_transfer_price,4) OR p_expected_source_mapping_hash IS NULL OR p_expected_source_mapping_hash!~'^sha256:[0-9a-f]{64}$'
  OR p_expected_target_mapping_hash IS NULL OR p_expected_target_mapping_hash!~'^sha256:[0-9a-f]{64}$' OR p_expected_carrying IS NULL OR p_expected_carrying<=0 OR p_expected_carrying>=10000000000000000 OR p_expected_carrying<>round(p_expected_carrying,4)
  OR p_expected_unit_version IS NULL OR p_expected_unit_version<0 OR p_expected_target_attachment_hash IS NULL OR p_expected_target_attachment_hash!~'^sha256:[0-9a-f]{64}$' OR cardinality(COALESCE(p_target_attachments,'{}'::uuid[]))=0
  OR cardinality(COALESCE(p_source_carrying_accounts,'{}'::text[])) NOT BETWEEN 1 AND 50 OR p_source_carrying_accounts IS DISTINCT FROM ARRAY(SELECT DISTINCT btrim(value) FROM unnest(COALESCE(p_source_carrying_accounts,'{}'::text[])) value WHERE length(btrim(value)) BETWEEN 1 AND 64 ORDER BY btrim(value))
  OR p_idempotency_key IS NULL OR length(p_idempotency_key) NOT BETWEEN 8 AND 200 OR p_request_hash IS NULL OR p_request_hash!~'^sha256:[0-9a-f]{64}$'
  OR length(btrim(coalesce(p_unit,''))) NOT BETWEEN 1 AND 128 OR length(btrim(coalesce(p_source_number,''))) NOT BETWEEN 1 AND 100
  OR length(btrim(coalesce(p_target_number,''))) NOT BETWEEN 1 AND 100 OR length(btrim(coalesce(p_reason,''))) NOT BETWEEN 8 AND 2000
  OR p_request_hash IS DISTINCT FROM refs_create_unit_transfer_hash(p_tenant,p_source_entity,p_target_entity,p_source_period,p_target_period,p_date,p_unit,
    p_source_document,p_source_line,p_expected_source_version,p_expected_source_hash,p_expected_source_line_hash,p_expected_source_attachment_hash,p_expected_transfer_price,p_source_mapping,p_expected_source_mapping_hash,p_target_mapping,
    p_expected_target_mapping_hash,p_source_carrying_accounts,p_source_gain_loss_account,p_target_inventory_account,p_expected_carrying,p_expected_unit_version,p_target_attachments,p_expected_target_attachment_hash,p_source_number,p_target_number,p_reason)
 THEN RAISE EXCEPTION 'Invalid Unit Transfer command' USING ERRCODE='22023';END IF;
 INSERT INTO idempotency_receipt(tenant_id,operation_scope,idempotency_key,request_hash,status,actor_id) VALUES(p_tenant,'UNIT_TRANSFER:'||p_source_entity,p_idempotency_key,p_request_hash,'IN_PROGRESS',actor) ON CONFLICT DO NOTHING;
 SELECT * INTO idem FROM idempotency_receipt WHERE tenant_id=p_tenant AND operation_scope='UNIT_TRANSFER:'||p_source_entity AND idempotency_key=p_idempotency_key FOR UPDATE;
 IF idem.actor_id IS DISTINCT FROM actor OR idem.request_hash IS DISTINCT FROM p_request_hash THEN RAISE EXCEPTION 'Unit Transfer idempotency conflict' USING ERRCODE='23505';END IF;
 IF idem.status='SUCCEEDED' THEN RETURN idem.response_body||jsonb_build_object('idempotent',true);END IF;
 SELECT * INTO source_entity_row FROM entity WHERE tenant_id=p_tenant AND entity_id=p_source_entity AND active FOR SHARE;SELECT * INTO target_entity_row FROM entity WHERE tenant_id=p_tenant AND entity_id=p_target_entity AND active FOR SHARE;
 IF source_entity_row.entity_id IS NULL OR target_entity_row.entity_id IS NULL OR source_entity_row.base_currency IS DISTINCT FROM target_entity_row.base_currency THEN RAISE EXCEPTION 'Unit Transfer requires two active entities with one base currency' USING ERRCODE='0A000';END IF;
 SELECT * INTO source_period FROM accounting_period WHERE tenant_id=p_tenant AND entity_id=p_source_entity AND period_id=p_source_period AND ledger_code='PRIMARY' AND status='OPEN' AND p_date BETWEEN starts_on AND ends_on FOR SHARE;
 SELECT * INTO target_period FROM accounting_period WHERE tenant_id=p_tenant AND entity_id=p_target_entity AND period_id=p_target_period AND ledger_code='PRIMARY' AND status='OPEN' AND p_date BETWEEN starts_on AND ends_on FOR SHARE;
 IF source_period.period_id IS NULL OR target_period.period_id IS NULL OR source_period.starts_on<>target_period.starts_on OR source_period.ends_on<>target_period.ends_on THEN RAISE EXCEPTION 'Unit Transfer requires aligned OPEN primary periods' USING ERRCODE='55000';END IF;
 SELECT * INTO source_document FROM source_document WHERE tenant_id=p_tenant AND entity_id=p_source_entity AND source_document_id=p_source_document FOR SHARE;
 SELECT * INTO source_line FROM source_document_line WHERE tenant_id=p_tenant AND entity_id=p_source_entity AND source_document_id=p_source_document AND source_document_line_id=p_source_line FOR SHARE;
 IF source_document.source_document_id IS NULL OR source_line.source_document_line_id IS NULL OR source_document.version IS DISTINCT FROM p_expected_source_version OR source_document.payload_hash IS DISTINCT FROM p_expected_source_hash
   OR source_document.status NOT IN('APPROVED','POSTED') OR source_document.document_type<>'UNIT_TRANSFER_AUTHORIZATION' OR source_document.business_date>p_date OR source_document.accounting_date>p_date OR source_document.accounting_date NOT BETWEEN source_period.starts_on AND source_period.ends_on
  OR refs_jsonb_hash(to_jsonb(source_line)) IS DISTINCT FROM p_expected_source_line_hash OR source_line.amount IS DISTINCT FROM p_expected_transfer_price
  OR source_line.unit_ref IS DISTINCT FROM btrim(p_unit) OR NULLIF(btrim(source_line.property_ref),'') IS NULL
 THEN RAISE EXCEPTION 'Unit Transfer source evidence changed' USING ERRCODE='40001';END IF;
 PERFORM pg_advisory_xact_lock(hashtextextended(p_tenant::text||':'||source_line.property_ref||':'||btrim(p_unit),0));
 IF EXISTS(SELECT 1 FROM unit_transfer_pair p JOIN unit_transfer_unit_control u ON u.tenant_id=p.tenant_id AND u.unit_control_id=p.unit_control_id WHERE p.tenant_id=p_tenant AND u.property_ref=source_line.property_ref AND u.unit_ref=btrim(p_unit) AND p.status NOT IN('POSTED_PAIR','CANCELLED_PAIR')) THEN RAISE EXCEPTION 'Unit already has an incomplete transfer' USING ERRCODE='23505';END IF;
 currency:=source_document.currency;price:=source_line.amount;IF currency IS DISTINCT FROM source_entity_row.base_currency OR price<=0 OR price>=10000000000000000 OR price<>round(price,4) OR source_line.direction NOT IN('DEBIT','NONE') THEN RAISE EXCEPTION 'Unit Transfer source line must retain a valid same-base-currency unit amount' USING ERRCODE='23514';END IF;
 SELECT array_agg(DISTINCT attachment_id ORDER BY attachment_id) INTO attachments FROM source_link WHERE tenant_id=p_tenant AND entity_id=p_source_entity AND source_document_id=p_source_document AND link_type='SOURCE_ATTACHMENT';
 attachment_hash:=refs_unit_transfer_attachment_snapshot(p_tenant,p_source_entity,p_source_document);IF attachment_hash IS NULL OR attachment_hash IS DISTINCT FROM p_expected_source_attachment_hash THEN RAISE EXCEPTION 'Unit Transfer requires the exact verified-clean source attachment snapshot' USING ERRCODE='23514';END IF;
 SELECT ARRAY(SELECT DISTINCT value FROM unnest(p_target_attachments) value ORDER BY value) INTO target_attachments;
 IF cardinality(target_attachments)<>cardinality(p_target_attachments) THEN RAISE EXCEPTION 'Duplicate target attachment identifiers are not allowed' USING ERRCODE='22023';END IF;
 target_attachment_hash:=refs_unit_transfer_attachment_ids_snapshot(p_tenant,p_target_entity,target_attachments);IF target_attachment_hash IS NULL OR target_attachment_hash IS DISTINCT FROM p_expected_target_attachment_hash THEN RAISE EXCEPTION 'Unit Transfer requires exact verified-clean target evidence attachments' USING ERRCODE='23514';END IF;
 SELECT * INTO source_map FROM mapping_snapshot WHERE tenant_id=p_tenant AND entity_id=p_source_entity AND scope_type='ENTITY' AND scope_key=p_source_entity::text AND mapping_snapshot_id=p_source_mapping AND family='INTERCOMPANY_ACCOUNT_PAIR' AND status='APPROVED' AND input_key_hash=refs_jsonb_hash(input_keys) AND snapshot_hash=p_expected_source_mapping_hash AND effective_from<=(p_date::timestamp AT TIME ZONE 'UTC') AND(effective_to IS NULL OR effective_to>(p_date::timestamp AT TIME ZONE 'UTC')) FOR SHARE;
 SELECT * INTO target_map FROM mapping_snapshot WHERE tenant_id=p_tenant AND entity_id=p_target_entity AND scope_type='ENTITY' AND scope_key=p_target_entity::text AND mapping_snapshot_id=p_target_mapping AND family='INTERCOMPANY_ACCOUNT_PAIR' AND status='APPROVED' AND input_key_hash=refs_jsonb_hash(input_keys) AND snapshot_hash=p_expected_target_mapping_hash AND effective_from<=(p_date::timestamp AT TIME ZONE 'UTC') AND(effective_to IS NULL OR effective_to>(p_date::timestamp AT TIME ZONE 'UTC')) FOR SHARE;
 source_due:=source_map.input_keys->>'account_code';target_due:=target_map.input_keys->>'account_code';
 IF source_map.mapping_snapshot_id IS NULL OR target_map.mapping_snapshot_id IS NULL OR source_map.snapshot_hash IS DISTINCT FROM refs_jsonb_hash(jsonb_build_object('input_keys',source_map.input_keys,'output_rules',source_map.output_rules)) OR target_map.snapshot_hash IS DISTINCT FROM refs_jsonb_hash(jsonb_build_object('input_keys',target_map.input_keys,'output_rules',target_map.output_rules))
   OR source_map.input_keys->>'counterparty_entity_id' IS DISTINCT FROM p_target_entity::text OR target_map.input_keys->>'counterparty_entity_id' IS DISTINCT FROM p_source_entity::text OR source_due IS NULL OR target_due IS NULL
   OR source_map.output_rules->>'classification' IS DISTINCT FROM 'DUE_FROM' OR source_map.output_rules->>'counterparty_classification' IS DISTINCT FROM 'DUE_TO' OR source_map.output_rules->>'counterparty_account_code' IS DISTINCT FROM target_due
   OR target_map.output_rules->>'classification' IS DISTINCT FROM 'DUE_TO' OR target_map.output_rules->>'counterparty_classification' IS DISTINCT FROM 'DUE_FROM' OR target_map.output_rules->>'counterparty_account_code' IS DISTINCT FROM source_due
   OR ARRAY(SELECT value FROM jsonb_array_elements_text(source_map.output_rules->'unit_transfer_carrying_account_codes') value ORDER BY value) IS DISTINCT FROM p_source_carrying_accounts
   OR source_map.output_rules->>'unit_transfer_gain_account_code' IS DISTINCT FROM btrim(p_source_gain_loss_account)
   OR target_map.output_rules->>'unit_transfer_inventory_account_code' IS DISTINCT FROM btrim(p_target_inventory_account)
   OR source_map.output_rules->>'unit_transfer_source_lifecycle_stage' NOT IN('CWIP','FINISHED_INVENTORY')
   OR target_map.output_rules->>'unit_transfer_target_lifecycle_stage' NOT IN('CWIP','FINISHED_INVENTORY')
   OR NOT refs_unit_transfer_mapping_is_current(p_tenant,p_source_entity,p_source_mapping,p_date)
   OR NOT refs_unit_transfer_mapping_is_current(p_tenant,p_target_entity,p_target_mapping,p_date)
 THEN RAISE EXCEPTION 'Unit Transfer requires exact reciprocal approved intercompany mappings' USING ERRCODE='23514';END IF;
 IF btrim(p_source_gain_loss_account)=ANY(p_source_carrying_accounts) OR source_due=ANY(p_source_carrying_accounts) OR source_due=btrim(p_source_gain_loss_account) THEN RAISE EXCEPTION 'Unit Transfer source accounts must be distinct by purpose' USING ERRCODE='23514';END IF;
 PERFORM 1 FROM account_master WHERE tenant_id=p_tenant AND entity_id=p_source_entity AND account_code=ANY(p_source_carrying_accounts||ARRAY[btrim(p_source_gain_loss_account),source_due]) AND active GROUP BY tenant_id HAVING count(*)=cardinality(p_source_carrying_accounts)+2;
 IF NOT FOUND THEN RAISE EXCEPTION 'Unit Transfer source accounts are unavailable' USING ERRCODE='23503';END IF;
 PERFORM 1 FROM account_master WHERE tenant_id=p_tenant AND entity_id=p_target_entity AND account_code IN(btrim(p_target_inventory_account),target_due) AND active GROUP BY tenant_id HAVING count(*)=2;
 IF NOT FOUND THEN RAISE EXCEPTION 'Unit Transfer target accounts are unavailable' USING ERRCODE='23503';END IF;
 SELECT member_ref INTO source_affiliate FROM member_master WHERE tenant_id=p_tenant AND entity_id=p_source_entity AND member_ref=target_entity_row.entity_code AND member_type='AFFILIATE' AND active FOR SHARE;
 SELECT member_ref INTO target_affiliate FROM member_master WHERE tenant_id=p_tenant AND entity_id=p_target_entity AND member_ref=source_entity_row.entity_code AND member_type='AFFILIATE' AND active FOR SHARE;
 IF source_affiliate IS NULL OR target_affiliate IS NULL THEN RAISE EXCEPTION 'Unit Transfer requires reciprocal active affiliate members' USING ERRCODE='23503';END IF;
 cost_snapshot:=refs_unit_transfer_cost_snapshot(p_tenant,p_source_entity,p_date,source_line.property_ref,btrim(p_unit),currency,p_source_carrying_accounts,NULL);
 IF cost_snapshot IS NULL THEN RAISE EXCEPTION 'Unit Transfer cost layers are incomplete or invalid' USING ERRCODE='23514';END IF;
 carrying:=(cost_snapshot->>'amount')::numeric;cost_line_ids:=ARRAY(SELECT value::uuid FROM jsonb_array_elements_text(cost_snapshot->'ledger_line_ids') value ORDER BY value::uuid);cost_basis_hash:=cost_snapshot->>'basis_hash';cost_layers:=cost_snapshot->'layers';
 IF carrying<=0 OR carrying<>p_expected_carrying THEN RAISE EXCEPTION 'Unit Transfer carrying amount changed' USING ERRCODE='40001';END IF;
 SELECT * INTO unit_control FROM unit_transfer_unit_control WHERE tenant_id=p_tenant AND property_ref=source_line.property_ref AND unit_ref=btrim(p_unit) FOR UPDATE;
 IF NOT FOUND THEN
  IF p_expected_unit_version<>0 OR EXISTS(SELECT 1 FROM ledger_line l JOIN journal_entry j ON j.tenant_id=l.tenant_id AND j.entity_id=l.entity_id AND j.journal_entry_id=l.journal_entry_id AND j.status='POSTED' JOIN accounting_period ap ON ap.tenant_id=j.tenant_id AND ap.entity_id=j.entity_id AND ap.period_id=j.period_id AND ap.ledger_code='PRIMARY' WHERE l.tenant_id=p_tenant AND l.entity_id<>p_source_entity AND l.currency=currency AND l.dimensions->>'unit_ref'=btrim(p_unit) AND l.dimensions->>'property_ref'=source_line.property_ref GROUP BY l.entity_id HAVING sum(l.debit_amount-l.credit_amount)>0) THEN RAISE EXCEPTION 'Unit ownership evidence is ambiguous or stale' USING ERRCODE='40001';END IF;
  INSERT INTO unit_transfer_unit_control(tenant_id,property_ref,unit_ref,current_owner_entity_id,current_asset_account_codes,currency,lifecycle_stage,initial_owner_entity_id,initial_source_document_id,initial_source_document_line_id,initial_source_payload_hash,created_by) VALUES(p_tenant,source_line.property_ref,btrim(p_unit),p_source_entity,p_source_carrying_accounts,currency,source_map.output_rules->>'unit_transfer_source_lifecycle_stage',p_source_entity,p_source_document,p_source_line,source_document.payload_hash,actor) RETURNING * INTO unit_control;
 ELSE
  IF unit_control.version<>p_expected_unit_version OR unit_control.current_owner_entity_id<>p_source_entity OR unit_control.currency<>currency THEN RAISE EXCEPTION 'Unit ownership or version changed' USING ERRCODE='40001';END IF;
  IF unit_control.current_asset_account_codes<>p_source_carrying_accounts OR unit_control.lifecycle_stage<>source_map.output_rules->>'unit_transfer_source_lifecycle_stage' THEN
   IF unit_control.last_transfer_pair_id IS NOT NULL OR EXISTS(SELECT 1 FROM unit_transfer_pair prior WHERE prior.tenant_id=p_tenant AND prior.unit_control_id=unit_control.unit_control_id AND prior.status<>'CANCELLED_PAIR') THEN RAISE EXCEPTION 'Established Unit ownership profile cannot be rebaselined' USING ERRCODE='40001';END IF;
   INSERT INTO unit_transfer_internal_gate VALUES(pg_backend_pid(),txid_current(),p_tenant,pair_id,'UNIT',unit_control.unit_control_id,'REBASELINED');
   payload:=jsonb_build_object('schema_version','UNIT_TRANSFER_UNIT_REBASELINE_V1','unit_transfer_pair_id',pair_id,'unit_control_id',unit_control.unit_control_id,'source_entity_id',p_source_entity,'target_entity_id',p_target_entity,'before_version',unit_control.version,'after_version',unit_control.version+1,'before_account_codes',to_jsonb(unit_control.current_asset_account_codes),'after_account_codes',to_jsonb(p_source_carrying_accounts),'before_lifecycle_stage',unit_control.lifecycle_stage,'after_lifecycle_stage',source_map.output_rules->>'unit_transfer_source_lifecycle_stage');
   UPDATE unit_transfer_unit_control SET current_asset_account_codes=p_source_carrying_accounts,lifecycle_stage=source_map.output_rules->>'unit_transfer_source_lifecycle_stage',version=version+1,updated_at=clock_timestamp() WHERE tenant_id=p_tenant AND unit_control_id=unit_control.unit_control_id AND version=p_expected_unit_version RETURNING * INTO unit_control;IF NOT FOUND THEN RAISE EXCEPTION 'Unit ownership rebaseline revision conflict' USING ERRCODE='40001';END IF;
   INSERT INTO audit_event(tenant_id,entity_id,event_type,object_type,object_id,action,actor_id,actor_type,permission_used,request_id,correlation_id,idempotency_key,after_hash,reason,metadata) VALUES(p_tenant,p_source_entity,'UNIT_TRANSFER_UNIT_REBASELINED','UNIT_TRANSFER_UNIT_CONTROL',unit_control.unit_control_id,'REBASELINE',actor,'USER','REAL_ESTATE.UNIT_TRANSFER.CREATE',p_idempotency_key,p_idempotency_key,p_idempotency_key,refs_jsonb_hash(payload),btrim(p_reason),payload);
   INSERT INTO audit_event(tenant_id,entity_id,event_type,object_type,object_id,action,actor_id,actor_type,permission_used,request_id,correlation_id,idempotency_key,after_hash,reason,metadata) VALUES(p_tenant,p_target_entity,'UNIT_TRANSFER_UNIT_REBASELINED','UNIT_TRANSFER_UNIT_CONTROL',unit_control.unit_control_id,'REBASELINE',actor,'USER','REAL_ESTATE.UNIT_TRANSFER.CREATE',p_idempotency_key,p_idempotency_key,p_idempotency_key,refs_jsonb_hash(payload),btrim(p_reason),payload);
   INSERT INTO outbox_event(tenant_id,entity_id,aggregate_type,aggregate_id,event_type,payload,payload_hash) VALUES(p_tenant,p_source_entity,'UNIT_TRANSFER_UNIT_CONTROL',unit_control.unit_control_id,'UNIT_TRANSFER_UNIT_REBASELINED',payload,refs_jsonb_hash(payload));
   INSERT INTO outbox_event(tenant_id,entity_id,aggregate_type,aggregate_id,event_type,payload,payload_hash) VALUES(p_tenant,p_target_entity,'UNIT_TRANSFER_UNIT_CONTROL',unit_control.unit_control_id,'UNIT_TRANSFER_UNIT_REBASELINED',payload,refs_jsonb_hash(payload));
  END IF;
 END IF;
 margin:=price-carrying;IF margin<0 THEN RAISE EXCEPTION 'Transfer below carrying amount requires a separately approved impairment workflow' USING ERRCODE='0A000';END IF;dims:=jsonb_build_object('unit_control_id',unit_control.unit_control_id,'unit_ref',btrim(p_unit),'property_ref',source_line.property_ref,'unit_transfer_pair_id',pair_id,'counterparty_entity_id',p_target_entity);
 SELECT jsonb_agg(jsonb_build_object('line_no',layer.ordinality+1,'account_code',layer.value->>'account_code','debit_amount',0,'credit_amount',(layer.value->>'amount')::numeric,'member_ref',NULL,'dimensions',dims) ORDER BY layer.ordinality) INTO layer_lines FROM jsonb_array_elements(cost_layers) WITH ORDINALITY layer(value,ordinality);
 source_lines:=jsonb_build_array(jsonb_build_object('line_no',1,'account_code',source_due,'debit_amount',price,'credit_amount',0,'member_ref',source_affiliate,'dimensions',dims))||layer_lines;
 IF margin>0 THEN source_lines:=source_lines||jsonb_build_array(jsonb_build_object('line_no',jsonb_array_length(source_lines)+1,'account_code',btrim(p_source_gain_loss_account),'debit_amount',0,'credit_amount',margin,'member_ref',NULL,'dimensions',dims));END IF;
 dims:=jsonb_build_object('unit_control_id',unit_control.unit_control_id,'unit_ref',btrim(p_unit),'property_ref',source_line.property_ref,'unit_transfer_pair_id',pair_id,'counterparty_entity_id',p_source_entity);
 target_lines:=jsonb_build_array(jsonb_build_object('line_no',1,'account_code',btrim(p_target_inventory_account),'debit_amount',price,'credit_amount',0,'member_ref',NULL,'dimensions',dims),jsonb_build_object('line_no',2,'account_code',target_due,'debit_amount',0,'credit_amount',price,'member_ref',target_affiliate,'dimensions',dims));
 inner_hash:=refs_create_manual_journal_hash(p_tenant,p_source_entity,p_source_period,p_source_number,p_date,currency,btrim(p_reason),source_lines,attachments);source_result:=refs_create_manual_journal(p_tenant,p_source_entity,p_source_period,p_source_number,p_date,currency,btrim(p_reason),source_lines,attachments,'unit-transfer-source:'||pair_id,inner_hash);source_journal:=(source_result->>'journal_entry_id')::uuid;
 inner_hash:=refs_create_manual_journal_hash(p_tenant,p_target_entity,p_target_period,p_target_number,p_date,currency,btrim(p_reason),target_lines,target_attachments);target_result:=refs_create_manual_journal(p_tenant,p_target_entity,p_target_period,p_target_number,p_date,currency,btrim(p_reason),target_lines,target_attachments,'unit-transfer-target:'||pair_id,inner_hash);target_journal:=(target_result->>'journal_entry_id')::uuid;
 INSERT INTO source_link(tenant_id,entity_id,link_type,source_document_id,source_document_line_id,journal_entry_id,created_by) VALUES(p_tenant,p_source_entity,'SOURCE_TO_JE',p_source_document,p_source_line,source_journal,actor);
 source_snapshot:=refs_unit_transfer_journal_snapshot(p_tenant,p_source_entity,source_journal);target_snapshot:=refs_unit_transfer_journal_snapshot(p_tenant,p_target_entity,target_journal);
evidence:=refs_jsonb_hash(jsonb_build_object('schema_version','UNIT_TRANSFER_EVIDENCE_V1','unit_transfer_pair_id',pair_id,'unit_control_id',unit_control.unit_control_id,'expected_unit_version',unit_control.version,'source_entity_id',p_source_entity,'target_entity_id',p_target_entity,'source_period_id',p_source_period,'target_period_id',p_target_period,'transfer_date',p_date,'currency',currency,'property_ref',source_line.property_ref,'unit_ref',btrim(p_unit),'source_lifecycle_stage',source_map.output_rules->>'unit_transfer_source_lifecycle_stage','target_lifecycle_stage',target_map.output_rules->>'unit_transfer_target_lifecycle_stage','source_document_id',p_source_document,'source_document_line_id',p_source_line,'source_document_version',source_document.version,'source_payload_hash',source_document.payload_hash,'source_line_hash',refs_jsonb_hash(to_jsonb(source_line)),'attachment_snapshot_hash',attachment_hash,'target_attachment_snapshot_hash',target_attachment_hash,'source_mapping_snapshot_id',source_map.mapping_snapshot_id,'source_mapping_snapshot_hash',source_map.snapshot_hash,'target_mapping_snapshot_id',target_map.mapping_snapshot_id,'target_mapping_snapshot_hash',target_map.snapshot_hash,'source_carrying_account_codes',to_jsonb(p_source_carrying_accounts),'source_cost_ledger_line_ids',to_jsonb(cost_line_ids),'source_cost_layers',cost_layers,'source_cost_basis_hash',cost_basis_hash,'carrying_amount',carrying,'transfer_price',price,'source_journal_entry_id',source_journal,'target_journal_entry_id',target_journal,'source_journal_snapshot_hash',source_snapshot,'target_journal_snapshot_hash',target_snapshot));
 INSERT INTO unit_transfer_pair(unit_transfer_pair_id,unit_control_id,tenant_id,source_entity_id,target_entity_id,source_period_id,target_period_id,transfer_date,currency,unit_ref,source_document_id,source_document_line_id,source_document_version,source_payload_hash,source_line_hash,attachment_ids,attachment_snapshot_hash,target_attachment_ids,target_attachment_snapshot_hash,source_mapping_snapshot_id,source_mapping_snapshot_hash,target_mapping_snapshot_id,target_mapping_snapshot_hash,source_carrying_account_codes,source_due_from_account_code,source_gain_loss_account_code,target_inventory_account_code,target_due_to_account_code,source_lifecycle_stage,target_lifecycle_stage,carrying_amount,source_cost_ledger_line_ids,source_cost_layers,source_cost_basis_hash,expected_unit_version,transfer_price,source_journal_entry_id,target_journal_entry_id,source_journal_snapshot_hash,target_journal_snapshot_hash,created_by,evidence_hash)
 VALUES(pair_id,unit_control.unit_control_id,p_tenant,p_source_entity,p_target_entity,p_source_period,p_target_period,p_date,currency,btrim(p_unit),p_source_document,p_source_line,source_document.version,source_document.payload_hash,refs_jsonb_hash(to_jsonb(source_line)),attachments,attachment_hash,target_attachments,target_attachment_hash,source_map.mapping_snapshot_id,source_map.snapshot_hash,target_map.mapping_snapshot_id,target_map.snapshot_hash,p_source_carrying_accounts,source_due,btrim(p_source_gain_loss_account),btrim(p_target_inventory_account),target_due,source_map.output_rules->>'unit_transfer_source_lifecycle_stage',target_map.output_rules->>'unit_transfer_target_lifecycle_stage',carrying,cost_line_ids,cost_layers,cost_basis_hash,unit_control.version,price,source_journal,target_journal,source_snapshot,target_snapshot,actor,evidence);
 payload:=jsonb_build_object('schema_version','UNIT_TRANSFER_DRAFT_PAIR_V1','unit_transfer_pair_id',pair_id,'source_entity_id',p_source_entity,'target_entity_id',p_target_entity,'unit_ref',btrim(p_unit),'currency',currency,'carrying_amount',carrying::text,'transfer_price',price::text,'source_journal_entry_id',source_journal,'target_journal_entry_id',target_journal,'status','DRAFT_PAIR','revision',0,'evidence_hash',evidence,'idempotent',false);
 INSERT INTO audit_event(tenant_id,entity_id,event_type,object_type,object_id,action,actor_id,actor_type,permission_used,request_id,correlation_id,idempotency_key,after_hash,reason,metadata) VALUES(p_tenant,p_source_entity,'UNIT_TRANSFER_DRAFT_PAIR_CREATED','UNIT_TRANSFER_PAIR',pair_id,'CREATE',actor,'USER','REAL_ESTATE.UNIT_TRANSFER.CREATE',p_idempotency_key,p_idempotency_key,p_idempotency_key,evidence,btrim(p_reason),payload);
 INSERT INTO audit_event(tenant_id,entity_id,event_type,object_type,object_id,action,actor_id,actor_type,permission_used,request_id,correlation_id,idempotency_key,after_hash,reason,metadata) VALUES(p_tenant,p_target_entity,'UNIT_TRANSFER_DRAFT_PAIR_CREATED','UNIT_TRANSFER_PAIR',pair_id,'CREATE',actor,'USER','REAL_ESTATE.UNIT_TRANSFER.CREATE',p_idempotency_key,p_idempotency_key,p_idempotency_key,evidence,btrim(p_reason),payload);
 INSERT INTO outbox_event(tenant_id,entity_id,aggregate_type,aggregate_id,event_type,payload,payload_hash) VALUES(p_tenant,p_source_entity,'UNIT_TRANSFER_PAIR',pair_id,'UNIT_TRANSFER_DRAFT_PAIR_CREATED',payload,refs_jsonb_hash(payload));
 INSERT INTO outbox_event(tenant_id,entity_id,aggregate_type,aggregate_id,event_type,payload,payload_hash) VALUES(p_tenant,p_target_entity,'UNIT_TRANSFER_PAIR',pair_id,'UNIT_TRANSFER_DRAFT_PAIR_CREATED',payload,refs_jsonb_hash(payload));
 UPDATE idempotency_receipt SET status='SUCCEEDED',response_status=201,response_body=payload,completed_at=clock_timestamp() WHERE idempotency_receipt_id=idem.idempotency_receipt_id;RETURN payload;
END;$$;

REVOKE ALL ON FUNCTION refs_create_unit_transfer(uuid,uuid,uuid,uuid,uuid,date,text,uuid,uuid,bigint,text,text,text,numeric,uuid,text,uuid,text,text[],text,text,numeric,bigint,uuid[],text,text,text,text,text,text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION refs_create_unit_transfer(uuid,uuid,uuid,uuid,uuid,date,text,uuid,uuid,bigint,text,text,text,numeric,uuid,text,uuid,text,text[],text,text,numeric,bigint,uuid[],text,text,text,text,text,text) TO refs_app;

COMMIT;
