BEGIN;
DROP FUNCTION IF EXISTS refs_read_project_cost_layers(uuid,uuid,text,uuid);
DROP FUNCTION IF EXISTS refs_read_project_masters(uuid,uuid);
DROP FUNCTION IF EXISTS refs_transition_project_master(uuid,uuid,text,uuid,integer,text,text,text,text);
DROP FUNCTION IF EXISTS refs_transition_project_master_hash(uuid,uuid,text,uuid,integer,text,text);
DROP FUNCTION IF EXISTS refs_create_project_unit(uuid,uuid,uuid,text,text,text,numeric,text,text,text);
DROP FUNCTION IF EXISTS refs_create_project_unit_hash(uuid,uuid,uuid,text,text,text,numeric,text);
DROP FUNCTION IF EXISTS refs_create_project_cost_code(uuid,uuid,uuid,text,text,text,boolean,text,text,text);
DROP FUNCTION IF EXISTS refs_create_project_cost_code_hash(uuid,uuid,uuid,text,text,text,boolean,text);
DROP FUNCTION IF EXISTS refs_create_project_master(uuid,uuid,text,text,text,text,text,text,text);
DROP FUNCTION IF EXISTS refs_create_project_master_hash(uuid,uuid,text,text,text,text,text);
DROP FUNCTION IF EXISTS refs_record_project_master_event(uuid,uuid,text,uuid,text,text,text,text);
DROP FUNCTION IF EXISTS refs_project_master_snapshot(text,uuid);
DROP TABLE IF EXISTS project_master_event;
DROP TABLE IF EXISTS project_unit;
DROP TABLE IF EXISTS project_cost_code;
DROP TABLE IF EXISTS project_master;
DELETE FROM runtime_human_permission_authority WHERE permission_code IN('PROJECT.MASTER.CREATE','PROJECT.MASTER.APPROVE');
UPDATE permission_catalog SET active=false,effective_to=clock_timestamp() WHERE permission_code IN('PROJECT.MASTER.VIEW','PROJECT.MASTER.CREATE','PROJECT.MASTER.APPROVE');
COMMIT;
