BEGIN;

-- Removes 441's additive VIEW authorities and restores 412's check. Refuses while a live grant
-- relies on one of them, since that grant would become invalid.
DO $$ BEGIN
  IF EXISTS(SELECT 1 FROM runtime_actor_grant g WHERE g.revoked_at IS NULL AND (g.permission,g.authority_class) IN(
    ('GROUP.CONSOLIDATION.CONFIG.VIEW','DRAFT'), ('GROUP.CONSOLIDATION.CONFIG.VIEW','SUBMIT'), ('GROUP.CONSOLIDATION.CONFIG.VIEW','APPROVE'), ('GROUP.INTERCOMPANY_ELIMINATION.VIEW','DRAFT'), ('GROUP.INTERCOMPANY_ELIMINATION.VIEW','SUBMIT'), ('GROUP.INTERCOMPANY_ELIMINATION.VIEW','REVIEW'), ('GROUP.INTERCOMPANY_ELIMINATION.VIEW','APPROVE'), ('GROUP.INTERCOMPANY_ELIMINATION.VIEW','POST'), ('INTEGRATION.WEBHOOK.VIEW','DRAFT'), ('INTEGRATION.WEBHOOK.VIEW','SUBMIT'), ('INTEGRATION.WEBHOOK.VIEW','APPROVE'), ('INTEGRATION.WEBHOOK.VIEW','JE_REVIEW'), ('REPORT.FORECAST.VIEW','DRAFT'), ('REPORT.FORECAST.VIEW','SUBMIT'), ('REPORT.FORECAST.VIEW','APPROVE'))) THEN
    RAISE EXCEPTION 'Cannot remove additive VIEW authority while live grants use it' USING ERRCODE='55006';
  END IF;
END $$;
DELETE FROM runtime_human_additive_permission_authority WHERE (permission_code,authority_class) IN(
  ('GROUP.CONSOLIDATION.CONFIG.VIEW','DRAFT'), ('GROUP.CONSOLIDATION.CONFIG.VIEW','SUBMIT'), ('GROUP.CONSOLIDATION.CONFIG.VIEW','APPROVE'), ('GROUP.INTERCOMPANY_ELIMINATION.VIEW','DRAFT'), ('GROUP.INTERCOMPANY_ELIMINATION.VIEW','SUBMIT'), ('GROUP.INTERCOMPANY_ELIMINATION.VIEW','REVIEW'), ('GROUP.INTERCOMPANY_ELIMINATION.VIEW','APPROVE'), ('GROUP.INTERCOMPANY_ELIMINATION.VIEW','POST'), ('INTEGRATION.WEBHOOK.VIEW','DRAFT'), ('INTEGRATION.WEBHOOK.VIEW','SUBMIT'), ('INTEGRATION.WEBHOOK.VIEW','APPROVE'), ('INTEGRATION.WEBHOOK.VIEW','JE_REVIEW'), ('REPORT.FORECAST.VIEW','DRAFT'), ('REPORT.FORECAST.VIEW','SUBMIT'), ('REPORT.FORECAST.VIEW','APPROVE'));
ALTER TABLE runtime_human_additive_permission_authority
  DROP CONSTRAINT runtime_human_additive_permission_authority_check;
ALTER TABLE runtime_human_additive_permission_authority
  ADD CONSTRAINT runtime_human_additive_permission_authority_check CHECK(
    (permission_code='ATTACHMENT.CREATE' AND authority_class IN('DRAFT','PAYMENT','RECEIPT','ADJUSTMENT'))
    OR (permission_code='ACCOUNTING.SETTINGS.WORKFLOW.VIEW' AND authority_class IN('DRAFT','SUBMIT','REVIEW','APPROVE','POST'))
    OR (permission_code='RECURRING.SCHEDULE.VIEW' AND authority_class IN('DRAFT','SUBMIT','APPROVE','REVIEW','SCHEDULE'))
  );

COMMIT;
