import assert from 'node:assert/strict';
import {WBS_LIVE_PILOT_VIEWS} from '../src/accounting-api.js';
import {accountingApiConfig,activateAuthoritativeWbsOperatorAccess,activateAuthoritativeWbsReadAccess,applyAuthoritativeCredit,attestAuthoritativeWbsPayableObservation,createAuthoritativeAdjustment,createAuthoritativeBankPaymentMatch,createAuthoritativeBusinessDocument,createAuthoritativeReconciliationAdjustmentDraft,createAuthoritativeSettlement,readAuthoritativeAdmittedBankStatement,readAuthoritativeJournalEntryDetail,readAuthoritativeJournalWorkflowCapabilities,refreshAuthoritativeAccountRegister,refreshAuthoritativeAdmittedBankStatements,refreshAuthoritativeAiWbsExceptionFindings,refreshAuthoritativeBankTransactions,refreshAuthoritativeBankMatchCandidates,refreshAuthoritativeBudgetVsActual,refreshAuthoritativeChartOfAccounts,refreshAuthoritativeConsolidation,refreshAuthoritativeDocuments,refreshAuthoritativeJournalEntries,refreshAuthoritativeReconciliation,refreshAuthoritativeReconciliationWorksheet,refreshAuthoritativeScope,setAuthoritativeReconciliationAdjustmentClearance,setAuthoritativeReconciliationClearance,startAuthoritativeReconciliation,startAuthoritativeReconciliationFromAdmittedStatement,transitionAuthoritativeReconciliation,transitionAuthoritativeJournal,unmatchAuthoritativeBankPayment,refreshAuthoritativeAging,refreshAuthoritativeCashFlowClassification,refreshAuthoritativeConstructionLoanRollforward,refreshAuthoritativeCwipRollforward,refreshAuthoritativeControlTotals,refreshAuthoritativeDimensionProfitability,refreshAuthoritativeIntercompanyReconciliation,refreshAuthoritativePrepaidRollforward,refreshAuthoritativeWbsAutoRecReview,refreshAuthoritativeWbsControlReconciliation,refreshAuthoritativeWbsLivePilot,refreshAuthoritativeWbsOperatorPayableAttestations,refreshAuthoritativeWbsOperatorPayableExceptionRows,verifyAuthoritativeWbsTransitionContract} from '../src/accounting-api.js';
import {bindAuthoritativeFetcher} from '../src/authoritative-app.jsx';
import {createWbsLivePilotReadService} from '../server/runtime/wbs-live-pilot-read-service.mjs';
import {canonicalRequestHash} from '../server/runtime/request-hash.mjs';
const entityId='11111111-1111-4111-8111-111111111111';
const periodId='33333333-3333-4333-8333-333333333333';
assert.equal(accountingApiConfig({__REFS_ACCOUNTING_API__:{baseUrl:'http://unsafe.example',entityId,periodId}}),null);
const accessToken='a'.repeat(48);assert.equal(accountingApiConfig({__REFS_ACCOUNTING_API__:{baseUrl:'https://api.example/',entityId,periodId}}),null);
const configured=accountingApiConfig({__REFS_ACCOUNTING_API__:{baseUrl:'https://api.example/',entityId,periodId,cashAccountCode:'111000',getAccessToken:async()=>accessToken}});
assert.equal(configured.baseUrl,'https://api.example');assert.equal(configured.cashAccountCode,'111000');
assert.equal(accountingApiConfig({__REFS_ACCOUNTING_API__:{baseUrl:'https://api.example/',entityId,periodId,cashAccountCode:'cash account',getAccessToken:async()=>accessToken}}).cashAccountCode,null);
const rows={
  '/ap/bills':[{business_document_id:entityId,document_number:'B-1',counterparty_ref:'V-1',counterparty_name:'Vendor',currency:'USD',accounting_date:'2026-08-01',due_date:'2026-08-31',gross_amount:'10.2500',open_balance:'7.2500',status:'PARTIALLY_PAID',posted_journal_entry_id:null,version:3,offset_account_code:'610000',description:'Bill evidence',journal_entry_id:null,journal_status:null,journal_revision:null,period_id:periodId}],
  '/ar/invoices':[{business_document_id:'22222222-2222-4222-8222-222222222222',document_number:'I-1',counterparty_ref:'C-1',counterparty_name:'Customer',currency:'USD',accounting_date:'2026-08-01',due_date:null,gross_amount:'8.0000',open_balance:'8.0000',status:'OPEN',posted_journal_entry_id:null,version:0,offset_account_code:'411100',description:'Invoice evidence',journal_entry_id:null,journal_status:null,journal_revision:null,period_id:periodId}],
  '/ap/adjustments':[{business_adjustment_id:entityId,adjustment_kind:'AP_VENDOR_CREDIT',business_document_id:null,source_adjustment_id:null,amount:'3.0000',currency:'USD',accounting_date:'2026-08-01',period_id:periodId,reason:'Approved vendor credit',status:'DRAFT',version:0,journal_entry_id:null,journal_status:null,journal_revision:null,created_at:'2026-08-01T00:00:00.000Z'}],
  '/ar/adjustments':[{business_adjustment_id:'22222222-2222-4222-8222-222222222222',adjustment_kind:'AR_CREDIT_MEMO',business_document_id:null,source_adjustment_id:null,amount:'2.0000',currency:'USD',accounting_date:'2026-08-01',period_id:periodId,reason:'Approved customer credit',status:'POSTED',version:'2',journal_entry_id:entityId,journal_status:'POSTED',journal_revision:'3',created_at:'2026-08-01T00:00:00.000Z'}],
};
const config=configured;
(async()=>{
  const coaRow={period_id:periodId,period_code:'2026-08',period_start:'2026-08-01',period_end:'2026-08-31',account_code:'291001',account_name:'Accounts payable control',requires_member:false,required_member_type:null,active:true,currency:null,opening_balance:null,period_debit:null,period_credit:null,ending_balance:null,posted_ledger_line_count:'0'};
  const coaRead=await refreshAuthoritativeChartOfAccounts({config,fetcher:async(url,options)=>{assert.match(url,/\/general-ledger\/chart-of-accounts\?periodId=/);assert.equal(options.method,'GET');return {ok:true,json:async()=>({ok:true,data:[coaRow]})};}});
  assert.equal(coaRead.ok,true,'PostgreSQL bigint count strings must be accepted by the browser contract');
  assert.equal(coaRead.rows[0].posted_ledger_line_count,0);
  const scopeRow={entity_id:entityId,entity_name:'Wan Pacific Real Estate Development LLC',entity_code:'WBPA',base_currency:'USD',period_id:periodId,period_code:'2026-08',period_start:'2026-08-01',period_end:'2026-08-31',period_status:'OPEN'};
  const scopeRead=await refreshAuthoritativeScope({config,fetcher:async(url,options)=>{assert.match(url,/\/scope\?periodId=/);assert.equal(options.method,'GET');assert.equal(options.headers.authorization,`Bearer ${accessToken}`);return {ok:true,json:async()=>({ok:true,data:scopeRow})};}});
  assert.equal(scopeRead.ok,true);assert.equal(scopeRead.row.entity_name,'Wan Pacific Real Estate Development LLC');
  assert.equal((await refreshAuthoritativeScope({config,fetcher:async()=>({ok:true,json:async()=>({ok:true,data:{...scopeRow,period_end:'2026-09-01'}})})})).code,'ACCOUNTING_API_PROTOCOL');
  assert.equal((await refreshAuthoritativeChartOfAccounts({config,fetcher:async()=>({ok:true,json:async()=>({ok:true,data:[{...coaRow,posted_ledger_line_count:'9007199254740992'}]})})})).code,'ACCOUNTING_API_PROTOCOL');
  assert.equal((await refreshAuthoritativeChartOfAccounts({config,fetcher:async()=>({ok:true,json:async()=>({ok:true,data:[{...coaRow,period_start:'2026-07-31T16:00:00.000Z'}]})})})).code,'ACCOUNTING_API_PROTOCOL');
  for(const changed of [{period_start:'2026-08-31',period_end:'2026-08-01'},{period_code:'2026-07'},{period_end:'2026-09-01'}])assert.equal((await refreshAuthoritativeChartOfAccounts({config,fetcher:async()=>({ok:true,json:async()=>({ok:true,data:[{...coaRow,...changed}]})})})).code,'ACCOUNTING_API_PROTOCOL');
  const registerRow={period_id:periodId,period_code:'2026-08',period_start:'2026-08-01',period_end:'2026-08-31',account_code:'111000',account_name:'Cash',currency:'USD',journal_date:'2026-08-01',journal_entry_id:entityId,journal_number:'JE-1',journal_line_id:'22222222-2222-4222-8222-222222222222',ledger_line_id:'44444444-4444-4444-8444-444444444444',member_ref:'BANK-1',description:null,debit_amount:'25.0000',credit_amount:'0.0000',opening_balance:'0.0000',running_balance:'25.0000',source_document_ids:[]};
  const registerRead=await refreshAuthoritativeAccountRegister({config,accountCode:'111000',fetcher:async()=>({ok:true,json:async()=>({ok:true,data:[registerRow]})})});assert.equal(registerRead.ok,true);
  assert.equal((await refreshAuthoritativeAccountRegister({config,accountCode:'111000',fetcher:async()=>({ok:true,json:async()=>({ok:true,data:[{...registerRow,journal_date:'2026-07-31T16:00:00.000Z'}]})})})).code,'ACCOUNTING_API_PROTOCOL');
  for(const changed of [{journal_date:'2026-07-31'},{journal_date:'2026-09-01'},{period_start:'2026-08-31',period_end:'2026-08-01'},{period_code:'2026-07'}])assert.equal((await refreshAuthoritativeAccountRegister({config,accountCode:'111000',fetcher:async()=>({ok:true,json:async()=>({ok:true,data:[{...registerRow,...changed}]})})})).code,'ACCOUNTING_API_PROTOCOL');
  const dimensionRow={period_id:periodId,period_code:'2026-08',period_start:'2026-08-01',period_end:'2026-08-31',dimension_type:'PROPERTY',dimension_ref:'PROPERTY-01',statement_type:'PROPERTY_PNL',statement_section:'REVENUE',classification_basis:'POSTED_LEDGER_DIMENSION_EXACT',account_code:'400000',account_name:'Rental revenue',period_debit:'0.0000',period_credit:'10.1010',display_balance:'10.1010',journal_entry_ids:[entityId],journal_line_ids:['22222222-2222-4222-8222-222222222222'],ledger_line_ids:['33333333-3333-4333-8333-333333333333'],source_document_ids:['44444444-4444-4444-8444-444444444444']};
  const dimensionRead=await refreshAuthoritativeDimensionProfitability({config,dimensionType:'PROPERTY',dimensionRef:'PROPERTY-01',fetcher:async(url,options)=>{assert.match(url,/\/reports\/dimension-profitability\?periodId=/);assert.match(url,/dimensionType=PROPERTY/);assert.match(url,/dimensionRef=PROPERTY-01/);assert.equal(options.method,'GET');assert.equal(options.headers.authorization,`Bearer ${accessToken}`);return {ok:true,json:async()=>({ok:true,data:[dimensionRow]})};}});
  assert.equal(dimensionRead.ok,true);assert.equal(dimensionRead.rows[0].display_balance,'10.1010');
  for(const invalid of [{dimensionType:'PROPERTY',dimensionRef:'PROPERTY-01 '},{dimensionType:'ACCOUNT',dimensionRef:'PROPERTY-01'}])assert.equal((await refreshAuthoritativeDimensionProfitability({...invalid,config,fetcher:async()=>{throw new Error('must not fetch')}})).code,'ACCOUNTING_API_SCOPE_INVALID');
  assert.equal((await refreshAuthoritativeDimensionProfitability({config,dimensionType:'PROPERTY',dimensionRef:'PROPERTY-01',fetcher:async()=>({ok:true,json:async()=>({ok:true,data:[{...dimensionRow,dimension_ref:'OTHER'}]})})})).code,'ACCOUNTING_API_PROTOCOL');
  const cashFlowRow={period_id:periodId,period_code:'2026-08',period_start:'2026-08-01',period_end:'2026-08-31',classification:'OPERATING',mapping_status:'CLASSIFIED',classification_basis:'APPROVED_CASH_FLOW_MAPPING_SNAPSHOT_EXACT',cash_account_code:'111000',counterpart_account_code:'610000',cash_effect:'10.1010',mapping_snapshot_id:'55555555-5555-4555-8555-555555555555',mapping_version:'1',mapping_snapshot_hash:`sha256:${'a'.repeat(64)}`,journal_entry_ids:[entityId],journal_line_ids:['22222222-2222-4222-8222-222222222222'],ledger_line_ids:['33333333-3333-4333-8333-333333333333'],source_document_ids:['44444444-4444-4444-8444-444444444444']};
  const cashFlowRead=await refreshAuthoritativeCashFlowClassification({config,fetcher:async(url,options)=>{assert.match(url,/\/reports\/cash-flow-classification\?periodId=/);assert.equal(options.method,'GET');assert.equal(options.headers.authorization,`Bearer ${accessToken}`);return {ok:true,json:async()=>({ok:true,data:[cashFlowRow]})};}});
  assert.equal(cashFlowRead.ok,true);assert.equal(cashFlowRead.complete,true);assert.equal(cashFlowRead.rows[0].cash_effect,'10.1010');
  const blockedCashFlow={...cashFlowRow,classification:'BLOCKED',mapping_status:'BLOCKED_MAPPING_REQUIRED',classification_basis:'CASH_FLOW_MAPPING_SNAPSHOT_REQUIRED',mapping_snapshot_id:null,mapping_version:null,mapping_snapshot_hash:null};
  const blockedRead=await refreshAuthoritativeCashFlowClassification({config,fetcher:async()=>({ok:true,json:async()=>({ok:true,data:[blockedCashFlow]})})});
  assert.equal(blockedRead.ok,true);assert.equal(blockedRead.complete,false);
  const emptyCashFlowRead=await refreshAuthoritativeCashFlowClassification({config,fetcher:async()=>({ok:true,json:async()=>({ok:true,data:[]})})});
  assert.equal(emptyCashFlowRead.ok,true);assert.equal(emptyCashFlowRead.complete,false);assert.deepEqual(emptyCashFlowRead.rows,[]);
  assert.equal((await refreshAuthoritativeCashFlowClassification({config,fetcher:async()=>({ok:true,json:async()=>({ok:true,data:[{...cashFlowRow,mapping_snapshot_id:null}]})})})).code,'ACCOUNTING_API_PROTOCOL');
  const cwipRow={period_id:periodId,period_code:'2026-08',period_start:'2026-08-01',period_end:'2026-08-31',account_code:'151000',account_name:'CWIP',mapping_status:'MAPPED_CWIP_ACCOUNT',classification_basis:'APPROVED_CWIP_ACCOUNT_MAPPING_SNAPSHOT_EXACT',opening_balance:'100.0000',period_debit:'10.1010',period_credit:'0.0000',closing_balance:'110.1010',mapping_snapshot_id:'55555555-5555-4555-8555-555555555555',mapping_version:'1',mapping_snapshot_hash:`sha256:${'b'.repeat(64)}`,journal_entry_ids:[entityId],journal_line_ids:['22222222-2222-4222-8222-222222222222'],ledger_line_ids:['33333333-3333-4333-8333-333333333333'],source_document_ids:['44444444-4444-4444-8444-444444444444']};
  const cwipRead=await refreshAuthoritativeCwipRollforward({config,fetcher:async(url,options)=>{assert.match(url,/\/reports\/cwip-rollforward\?periodId=/);assert.equal(options.method,'GET');return {ok:true,json:async()=>({ok:true,data:[cwipRow]})};}});
  assert.equal(cwipRead.ok,true);assert.equal(cwipRead.rows[0].closing_balance,'110.1010');
  assert.equal((await refreshAuthoritativeCwipRollforward({config,fetcher:async()=>({ok:true,json:async()=>({ok:true,data:[{...cwipRow,closing_balance:'10.1'}]})})})).code,'ACCOUNTING_API_PROTOCOL');
  const constructionLoanRow={period_id:periodId,period_code:'2026-08',period_start:'2026-08-01',period_end:'2026-08-31',account_code:'270100',account_name:'Construction loan',mapping_status:'MAPPED_CONSTRUCTION_LOAN_ACCOUNT',classification_basis:'APPROVED_CONSTRUCTION_LOAN_ACCOUNT_MAPPING_SNAPSHOT_EXACT',opening_balance:'100.0000',period_draws:'10.1010',period_repayments:'0.0000',closing_balance:'110.1010',mapping_snapshot_id:'66666666-6666-4666-8666-666666666666',mapping_version:'1',mapping_snapshot_hash:`sha256:${'c'.repeat(64)}`,journal_entry_ids:[entityId],journal_line_ids:['22222222-2222-4222-8222-222222222222'],ledger_line_ids:['33333333-3333-4333-8333-333333333333'],source_document_ids:['44444444-4444-4444-8444-444444444444']};
  const constructionLoanRead=await refreshAuthoritativeConstructionLoanRollforward({config,fetcher:async(url,options)=>{assert.match(url,/\/reports\/construction-loan-rollforward\?periodId=/);assert.equal(options.method,'GET');return {ok:true,json:async()=>({ok:true,data:[constructionLoanRow]})};}});
  assert.equal(constructionLoanRead.ok,true);assert.equal(constructionLoanRead.rows[0].period_draws,'10.1010');
  assert.equal((await refreshAuthoritativeConstructionLoanRollforward({config,fetcher:async()=>({ok:true,json:async()=>({ok:true,data:[{...constructionLoanRow,period_draws:'10.1'}]})})})).code,'ACCOUNTING_API_PROTOCOL');
  const prepaidRow={period_id:periodId,period_code:'2026-08',period_start:'2026-08-01',period_end:'2026-08-31',account_code:'161000',account_name:'Prepaid insurance',mapping_status:'MAPPED_PREPAID_ACCOUNT',classification_basis:'APPROVED_PREPAID_ACCOUNT_MAPPING_SNAPSHOT_EXACT',opening_balance:'100.0000',period_additions:'10.1010',period_amortization:'2.0000',closing_balance:'108.1010',mapping_snapshot_id:'77777777-7777-4777-8777-777777777777',mapping_version:'1',mapping_snapshot_hash:`sha256:${'d'.repeat(64)}`,journal_entry_ids:[entityId],journal_line_ids:['22222222-2222-4222-8222-222222222222'],ledger_line_ids:['33333333-3333-4333-8333-333333333333'],source_document_ids:['44444444-4444-4444-8444-444444444444']};
  const prepaidRead=await refreshAuthoritativePrepaidRollforward({config,fetcher:async(url,options)=>{assert.match(url,/\/reports\/prepaid-rollforward\?periodId=/);assert.equal(options.method,'GET');return {ok:true,json:async()=>({ok:true,data:[prepaidRow]})};}});
  assert.equal(prepaidRead.ok,true);assert.equal(prepaidRead.rows[0].period_amortization,'2.0000');
  assert.equal((await refreshAuthoritativePrepaidRollforward({config,fetcher:async()=>({ok:true,json:async()=>({ok:true,data:[{...prepaidRow,period_amortization:'2.0'}]})})})).code,'ACCOUNTING_API_PROTOCOL');
  const counterpartyEntityId='88888888-8888-4888-8888-888888888888',counterpartyPeriodId='99999999-9999-4999-8999-999999999999';
  const intercompanyRow={period_id:periodId,counterparty_period_id:counterpartyPeriodId,period_code:'2026-08',period_start:'2026-08-01',period_end:'2026-08-31',account_code:'132100',account_name:'Due from affiliate',counterparty_account_code:'232100',counterparty_account_name:'Due to affiliate',mapping_status:'MAPPED_INTERCOMPANY_PAIR',classification_basis:'APPROVED_BIDIRECTIONAL_INTERCOMPANY_MAPPING_SNAPSHOTS_EXACT',current_closing_balance:'10.1010',counterparty_closing_balance:'-10.1010',difference_amount:'0.0000',in_balance:true,mapping_snapshot_id:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',mapping_version:'1',mapping_snapshot_hash:`sha256:${'e'.repeat(64)}`,counterparty_mapping_snapshot_id:'bbbbbbbb-bbbb-4bbb-8bbb-bbbbbbbbbbbb',counterparty_mapping_version:'1',counterparty_mapping_snapshot_hash:`sha256:${'f'.repeat(64)}`,journal_entry_ids:[entityId],journal_line_ids:['22222222-2222-4222-8222-222222222222'],ledger_line_ids:['33333333-3333-4333-8333-333333333333'],source_document_ids:['44444444-4444-4444-8444-444444444444'],counterparty_journal_entry_ids:['55555555-5555-4555-8555-555555555555'],counterparty_journal_line_ids:['66666666-6666-4666-8666-666666666666'],counterparty_ledger_line_ids:['77777777-7777-4777-8777-777777777777'],counterparty_source_document_ids:['88888888-8888-4888-8888-888888888888']};
  const intercompanyRead=await refreshAuthoritativeIntercompanyReconciliation({config,counterpartyEntityId,counterpartyPeriodId,fetcher:async(url,options)=>{assert.match(url,/\/reports\/intercompany-reconciliation\?periodId=/);assert.match(url,new RegExp(`counterpartyEntityId=${counterpartyEntityId}`));assert.match(url,new RegExp(`counterpartyPeriodId=${counterpartyPeriodId}`));assert.equal(options.method,'GET');assert.equal(options.cache,'no-store');return {ok:true,json:async()=>({ok:true,data:[intercompanyRow]})};}});
  assert.equal(intercompanyRead.ok,true);assert.equal(intercompanyRead.complete,true);assert.equal(intercompanyRead.rows[0].difference_amount,'0.0000');
  assert.equal((await refreshAuthoritativeIntercompanyReconciliation({config,counterpartyEntityId,counterpartyPeriodId,fetcher:async()=>({ok:true,json:async()=>({ok:true,data:[{...intercompanyRow,difference_amount:'0'}]})})})).code,'ACCOUNTING_API_PROTOCOL');
  assert.equal((await refreshAuthoritativeIntercompanyReconciliation({config,counterpartyEntityId:entityId,counterpartyPeriodId,fetcher:async()=>{throw new Error('must not fetch')}})).code,'ACCOUNTING_API_SCOPE_INVALID');
  const budgetRow={period_id:periodId,period_code:'2026-08',period_start:'2026-08-01',period_end:'2026-08-31',account_code:'610000',account_name:'Operating expense',currency:'USD',comparison_side:'DEBIT',report_status:'APPROVED_BUDGET_VS_ACTUAL',classification_basis:'APPROVED_IMMUTABLE_BUDGET_SNAPSHOT_AND_POSTED_LEDGER_EXACT',budget_amount:'120.0000',actual_amount:'10.1010',variance_amount:'109.8990',budget_snapshot_id:'cccccccc-cccc-4ccc-8ccc-cccccccccccc',budget_version:'1',budget_snapshot_hash:`sha256:${'1'.repeat(64)}`,budget_receipt_hash:`sha256:${'2'.repeat(64)}`,budget_source_ref:'budget-source-2026-08',budget_source_version:'1',journal_entry_ids:[entityId],journal_line_ids:['22222222-2222-4222-8222-222222222222'],ledger_line_ids:['33333333-3333-4333-8333-333333333333'],source_document_ids:['44444444-4444-4444-8444-444444444444']};
  const budgetRead=await refreshAuthoritativeBudgetVsActual({config,fetcher:async(url,options)=>{assert.match(url,/\/reports\/budget-vs-actual\?periodId=/);assert.equal(options.method,'GET');assert.equal(options.cache,'no-store');return {ok:true,json:async()=>({ok:true,data:[budgetRow]})};}});
  assert.equal(budgetRead.ok,true);assert.equal(budgetRead.complete,true);assert.equal(budgetRead.rows[0].variance_amount,'109.8990');
  assert.equal((await refreshAuthoritativeBudgetVsActual({config,fetcher:async()=>({ok:true,json:async()=>({ok:true,data:[{...budgetRow,actual_amount:'10.1'}]})})})).code,'ACCOUNTING_API_PROTOCOL');
  assert.equal((await refreshAuthoritativeBudgetVsActual({config:{...config,periodId:'not-a-uuid'},fetcher:async()=>{throw new Error('must not fetch')}})).code,'ACCOUNTING_API_SCOPE_INVALID');
  const consolidationRow={group_ref:'GROUP-01',period_id:periodId,period_code:'2026-08',period_start:'2026-08-01',period_end:'2026-08-31',currency:'USD',presentation_account_code:'210000',presentation_side:'CREDIT',report_status:'APPROVED_CONSOLIDATION_SNAPSHOT_AND_POSTED_LEDGER_EXACT',classification_basis:'APPROVED_IMMUTABLE_GROUP_MEMBER_MAPPING_ELIMINATION_AND_POSTED_LEDGER_EXACT',member_count:2,evidence_member_count:2,member_actual_amount:'120.0000',elimination_amount:'20.0000',consolidated_amount:'100.0000',consolidation_snapshot_id:'dddddddd-dddd-4ddd-8ddd-dddddddddddd',consolidation_version:'1',consolidation_snapshot_hash:`sha256:${'3'.repeat(64)}`,consolidation_receipt_hash:`sha256:${'4'.repeat(64)}`,consolidation_source_ref:'consolidation-source-2026-08',consolidation_source_version:'1',member_entity_ids:[entityId,counterpartyEntityId],journal_entry_ids:[entityId],journal_line_ids:['22222222-2222-4222-8222-222222222222'],ledger_line_ids:['33333333-3333-4333-8333-333333333333'],source_document_ids:['44444444-4444-4444-8444-444444444444'],elimination_refs:['ELIM-01']};
  const consolidationRead=await refreshAuthoritativeConsolidation({config,groupRef:'GROUP-01',fetcher:async(url,options)=>{assert.match(url,/\/reports\/consolidation\?periodId=/);assert.match(url,/groupRef=GROUP-01/);assert.equal(options.method,'GET');assert.equal(options.cache,'no-store');return {ok:true,json:async()=>({ok:true,data:[consolidationRow]})};}});
  assert.equal(consolidationRead.ok,true);assert.equal(consolidationRead.complete,true);assert.equal(consolidationRead.rows[0].consolidated_amount,'100.0000');
  assert.equal((await refreshAuthoritativeConsolidation({config,groupRef:'GROUP-01',fetcher:async()=>({ok:true,json:async()=>({ok:true,data:[{...consolidationRow,consolidated_amount:'100'}]})})})).code,'ACCOUNTING_API_PROTOCOL');
  assert.equal((await refreshAuthoritativeConsolidation({config,groupRef:'  ',fetcher:async()=>{throw new Error('must not fetch')}})).code,'ACCOUNTING_API_SCOPE_INVALID');
  const receiverEnvironment={name:'authoritative-browser-environment'};
  const receiverCalls=[];
  const receiverSensitiveFetcher=function(url,options){assert.equal(this,receiverEnvironment);receiverCalls.push(url);return {ok:true,json:async()=>({ok:true,data:url.endsWith('/journal-entries')?[]:rows[new URL(url).pathname.replace(`/api/v1/entities/${entityId}`,'')]||[]})};};
  const receiverBoundFetcher=bindAuthoritativeFetcher(receiverEnvironment,receiverSensitiveFetcher);
  assert.equal((await refreshAuthoritativeDocuments({config,fetcher:receiverBoundFetcher})).ok,true);
  assert.equal((await refreshAuthoritativeJournalEntries({config,fetcher:receiverBoundFetcher})).ok,true);
  assert.equal((await refreshAuthoritativeBankTransactions({config,bankAccountRef:'BANK-1',fetcher:receiverBoundFetcher})).ok,true);
  assert.equal(receiverCalls.length,6,'document, journal, and child-workspace reads must share the environment-bound fetcher');

  const readCalls=[];const result=await refreshAuthoritativeDocuments({config,fetcher:async(url,options)=>{readCalls.push({url,options});return {ok:true,json:async()=>({ok:true,data:rows[new URL(url).pathname.replace(`/api/v1/entities/${entityId}`,'')]})};}});
  assert.equal(result.ok,true);assert.equal(result.ap.bills[0].business_document_id,entityId);assert.equal(result.ap.bills[0].open_balance,7.25);assert.equal(result.ar.invoices[0].business_document_id,'22222222-2222-4222-8222-222222222222');assert.equal(result.ar.invoices[0].inv_no,'I-1');assert.equal(result.ap.adjustments[0].adjustment_kind,'AP_VENDOR_CREDIT');assert.equal(result.ar.adjustments[0].status,'POSTED');assert.equal(result.ar.adjustments[0].version,2);assert.equal(result.ar.adjustments[0].journal_revision,3);
  assert.equal(result.ap.bills[0].lineage,null,'a current list contract without immutable lineage must remain blocked by the presentation layer');
  const futureLineage={entity_id:entityId,record_id:entityId,record_revision:3};
  const lineageRead=await refreshAuthoritativeDocuments({config,fetcher:async url=>{const path=new URL(url).pathname.replace(`/api/v1/entities/${entityId}`,'');const data=path==='/ap/bills'?[{...rows[path][0],lineage:futureLineage}]:rows[path];return {ok:true,json:async()=>({ok:true,data})};}});
  assert.equal(lineageRead.ap.bills[0].lineage,futureLineage,'the client may pass through only an explicit future API lineage object; it does not synthesize one from AP list facts');
  assert.equal(readCalls.length,4);for(const read of readCalls){assert.equal(read.options.method,'GET');assert.equal(read.options.credentials,'include');assert.equal(read.options.cache,'no-store');assert.equal(read.options.headers.authorization,`Bearer ${accessToken}`);}
  const journalRead=await refreshAuthoritativeJournalEntries({config,fetcher:async(url,options)=>{assert.match(url,/\/journal-entries$/);assert.equal(options.method,'GET');assert.equal(options.cache,'no-store');return {ok:true,json:async()=>({ok:true,data:[{journal_entry_id:entityId,journal_number:'JE-1',journal_type:'MANUAL',status:'DRAFT',journal_date:'2026-08-01',currency:'USD',revision:'2',created_at:'2026-08-01T00:00:00.000Z',posted_at:null,ledger_line_count:'0'}]})};}});
  assert.equal(journalRead.ok,true);assert.equal(journalRead.journals[0].revision,2);assert.equal(journalRead.journals[0].ledger_line_count,0);
  let capabilityCall;const capabilityRead=await readAuthoritativeJournalWorkflowCapabilities({config,fetcher:async(url,options)=>{capabilityCall={url,options};return {ok:true,json:async()=>({ok:true,data:{entity_id:entityId,can_submit:true,can_review:false,can_approve:false,can_post:false}})};}});
  assert.equal(capabilityRead.ok,true);assert.equal(capabilityRead.capabilities.can_submit,true);assert.match(capabilityCall.url,/\/journal-workflow\/capabilities$/);assert.equal(capabilityCall.options.method,'GET');assert.equal(capabilityCall.options.cache,'no-store');assert.equal('body' in capabilityCall.options,false);
  for(const invalid of [{entity_id:'22222222-2222-4222-8222-222222222222',can_submit:true,can_review:false,can_approve:false,can_post:false},{entity_id:entityId,can_submit:'yes',can_review:false,can_approve:false,can_post:false},{entity_id:entityId,can_submit:true,can_review:false,can_approve:false,can_post:false,permission:'GL.JE.POST'}])assert.equal((await readAuthoritativeJournalWorkflowCapabilities({config,fetcher:async()=>({ok:true,json:async()=>({ok:true,data:invalid})})})).code,'ACCOUNTING_API_PROTOCOL');
  const validJournal={journal_entry_id:entityId,journal_number:'JE-1',journal_type:'MANUAL',status:'DRAFT',journal_date:'2026-08-01',currency:'USD',description:null,revision:'2',created_at:'2026-08-01T00:00:00.000Z',posted_at:null,ledger_line_count:'0'};
  const readJournalRows=async data=>refreshAuthoritativeJournalEntries({config,fetcher:async()=>({ok:true,json:async()=>({ok:true,data})})});
  const exactLine={journal_entry_id:entityId,journal_line_id:'33333333-3333-4333-8333-333333333333',ledger_line_id:'44444444-4444-4444-8444-444444444444',line_no:1,account_code:'111000',debit_amount:'10.0000',credit_amount:'0.0000',member_ref:'BANK-1',description:'Exact API line',source_document_ids:['55555555-5555-4555-8555-555555555555']};
  const exactJournal={...validJournal,ledger_line_count:'1',line_evidence:[exactLine]};
  const exactJournalRead=await readJournalRows([exactJournal]);
  assert.equal(exactJournalRead.ok,true,'a future explicit exact Journal line extension may be passed through only after strict validation');
  assert.deepEqual(exactJournalRead.journals[0].line_evidence,[exactLine]);
  for(const invalidLineEvidence of [[],[{...exactLine,journal_entry_id:'22222222-2222-4222-8222-222222222222'}],[{...exactLine,journal_line_id:'not-a-uuid'}],[{...exactLine,debit_amount:'0.0000',credit_amount:'0.0000'}],[{...exactLine,source_document_ids:['not-a-uuid']}],[exactLine,{...exactLine,line_no:1,ledger_line_id:'66666666-6666-4666-8666-666666666666'}]])assert.equal((await readJournalRows([{...exactJournal,line_evidence:invalidLineEvidence}])).code,'ACCOUNTING_API_PROTOCOL','partial, mismatched, or duplicate Journal line facts must fail closed');
  assert.equal((await readJournalRows([{...exactJournal,ledger_line_count:'2'}])).code,'ACCOUNTING_API_PROTOCOL','a line extension must account for the exact list ledger-line count');
  for(const invalid of [
    {...validJournal,journal_entry_id:'not-a-uuid'}, {...validJournal,journal_number:''}, {...validJournal,journal_type:'IMPORTED'},
    {...validJournal,status:'REVIEWED'}, {...validJournal,journal_date:'2026-02-30'}, {...validJournal,currency:'US'},
    {...validJournal,description:'x'.repeat(2001)}, {...validJournal,revision:'-1'}, {...validJournal,created_at:'not-a-time'},
    {...validJournal,posted_at:'not-a-time'}, {...validJournal,ledger_line_count:'-1'}, {...validJournal,status:'POSTED',posted_at:null},
    {...validJournal,status:'DRAFT',posted_at:'2026-08-02T00:00:00.000Z'},
  ]) assert.equal((await readJournalRows([invalid])).code,'ACCOUNTING_API_PROTOCOL');
  assert.equal((await readJournalRows([validJournal,{...validJournal,journal_number:'JE-2'}])).code,'ACCOUNTING_API_PROTOCOL','duplicate journal IDs must fail closed');
  assert.equal((await readJournalRows([validJournal,{...validJournal,journal_entry_id:'22222222-2222-4222-8222-222222222222'}])).code,'ACCOUNTING_API_PROTOCOL','duplicate journal numbers must fail closed');
  let bankCall;const bankRead=await refreshAuthoritativeBankTransactions({config,bankAccountRef:'BANK-1',from:'2026-07-01',through:'2026-07-31',limit:25,offset:50,fetcher:async(url,options)=>{bankCall={url,options};return {ok:true,json:async()=>({ok:true,data:[{bank_source_id:entityId,bank_account_ref:'BANK-1',external_bank_line_id:'BANK-LINE-1',transaction_date:'2026-07-15',currency:'USD',amount:'-125.2500',version:'3',source_document_id:'22222222-2222-4222-8222-222222222222',source_ref:'SOURCE-1',document_type:'BANK_TRANSACTION',bank_match_id:null,match_status:null,business_source_document_id:null,journal_entry_id:null,journal_line_id:null,candidate_rule_code:null,amount_delta:null,currency_match:null,date_delta_days:null,matched_by:null,matched_at:null,match_version:null}]})};}});
  assert.equal(bankRead.ok,true);assert.equal(bankRead.rows[0].amount,'-125.2500');assert.equal(bankRead.rows[0].version,3);assert.equal(bankRead.scope.offset,50);assert.match(bankCall.url,/\/bank\/transactions\?bankAccountRef=BANK-1&limit=25&offset=50&from=2026-07-01&through=2026-07-31$/);assert.equal(bankCall.options.method,'GET');assert.equal(bankCall.options.cache,'no-store');assert.equal(bankCall.options.headers.authorization,`Bearer ${accessToken}`);assert.equal('body' in bankCall.options,false);
  const validBank={bank_source_id:entityId,bank_account_ref:'BANK-1',external_bank_line_id:'BANK-LINE-1',transaction_date:'2026-07-15',currency:'USD',amount:'-125.2500',version:'3',source_document_id:'22222222-2222-4222-8222-222222222222',source_ref:'SOURCE-1',document_type:'BANK_TRANSACTION',bank_match_id:null,match_status:null,business_source_document_id:null,journal_entry_id:null,journal_line_id:null,candidate_rule_code:null,amount_delta:null,currency_match:null,date_delta_days:null,matched_by:null,matched_at:null,match_version:null};
  const matchedBank={...validBank,bank_match_id:'33333333-3333-4333-8333-333333333333',match_status:'ACTIVE',business_source_document_id:'44444444-4444-4444-8444-444444444444',journal_entry_id:'55555555-5555-4555-8555-555555555555',journal_line_id:'66666666-6666-4666-8666-666666666666',candidate_rule_code:'EXACT_POSTED_PAYMENT',amount_delta:'0.0000',currency_match:true,date_delta_days:0,matched_by:'auth0|actor',matched_at:'2026-07-16T00:00:00.000Z',match_version:'1'};
  const readBankRows=async data=>refreshAuthoritativeBankTransactions({config,bankAccountRef:'BANK-1',fetcher:async()=>({ok:true,json:async()=>({ok:true,data})})});
  assert.equal((await readBankRows([matchedBank])).ok,true);
  for(const invalid of [{...validBank,external_bank_line_id:''},{...validBank,transaction_date:'2026-02-30'},{...validBank,source_ref:'\u0000'},{...validBank,bank_match_id:null,match_status:'ACTIVE'},{...matchedBank,match_status:'MATCHED'},{...matchedBank,business_source_document_id:null},{...matchedBank,journal_entry_id:null},{...matchedBank,amount_delta:'0'},{...matchedBank,currency_match:'true'},{...matchedBank,matched_at:'not-a-time'},{...matchedBank,match_version:'-1'}])assert.equal((await readBankRows([invalid])).code,'ACCOUNTING_API_PROTOCOL');
  assert.equal((await readBankRows([validBank,{...validBank,external_bank_line_id:'BANK-LINE-2'}])).code,'ACCOUNTING_API_PROTOCOL','duplicate bank source IDs must fail closed');
  assert.equal((await readBankRows([validBank,{...validBank,bank_source_id:'77777777-7777-4777-8777-777777777777'}])).code,'ACCOUNTING_API_PROTOCOL','duplicate external bank line IDs must fail closed');
  let candidateCall;const candidateRow={payment_occurrence_id:'33333333-3333-4333-8333-333333333333',occurrence_version:'1',occurrence_kind:'AP_PAYMENT',business_source_document_id:'22222222-2222-4222-8222-222222222222',accounting_date:'2026-07-15',currency:'USD',amount:'125.2500',journal_entry_id:'44444444-4444-4444-8444-444444444444',journal_line_id:'55555555-5555-4555-8555-555555555555',ledger_line_id:'66666666-6666-4666-8666-666666666666',date_delta_days:0};
  const candidateRead=await refreshAuthoritativeBankMatchCandidates({config,bankSourceId:entityId,fetcher:async(url,options)=>{candidateCall={url,options};return {ok:true,json:async()=>({ok:true,data:[candidateRow]})};}});
  assert.equal(candidateRead.ok,true);assert.equal(candidateRead.candidates[0].occurrence_version,1);assert.equal(candidateRead.candidates[0].amount,'125.2500');assert.equal(candidateRead.candidates[0].amount_text,'125.2500');assert.match(candidateCall.url,/\/bank\/transactions\/.+\/match-candidates$/);assert.equal(candidateCall.options.method,'GET');assert.equal(candidateCall.options.headers.authorization,`Bearer ${accessToken}`);assert.equal('body' in candidateCall.options,false);
  const readCandidates=data=>refreshAuthoritativeBankMatchCandidates({config,bankSourceId:entityId,fetcher:async()=>({ok:true,json:async()=>({ok:true,data})})});
  for(const invalid of [{...candidateRow,payment_occurrence_id:'not-a-uuid'},{...candidateRow,occurrence_version:'-1'},{...candidateRow,occurrence_kind:'PAYMENT'},{...candidateRow,accounting_date:'2026-02-30'},{...candidateRow,amount:'1.00000'},{...candidateRow,date_delta_days:32},{...candidateRow,journal_line_id:null}])assert.equal((await readCandidates([invalid])).code,'ACCOUNTING_API_PROTOCOL');
  assert.equal((await readCandidates([candidateRow,{...candidateRow,journal_entry_id:'77777777-7777-4777-8777-777777777777'}])).code,'ACCOUNTING_API_PROTOCOL','duplicate occurrence candidates must fail closed');
  let call;
  const match=await createAuthoritativeBankPaymentMatch({config,bankSourceId:entityId,bankRevision:3,candidate:candidateRead.candidates[0],reason:'Controller reviewed exact posted evidence',fetcher:async(url,options)=>{call={url,options};return {ok:true,status:201,json:async()=>({ok:true,data:{bank_match_id:'77777777-7777-4777-8777-777777777777',status:'ACTIVE'}})};}});
  assert.equal(match.ok,true);assert.match(call.url,/\/bank\/transactions\/.+\/matches$/);assert.equal(call.options.headers['if-match'],'"3"');assert.match(call.options.headers['idempotency-key'],/^UI-BANK-MATCH-/);assert.deepEqual(JSON.parse(call.options.body),{paymentOccurrenceId:candidateRow.payment_occurrence_id,expectedOccurrenceRevision:1,reason:'Controller reviewed exact posted evidence'});
  const preciseCandidateRead=await refreshAuthoritativeBankMatchCandidates({config,bankSourceId:entityId,fetcher:async()=>({ok:true,json:async()=>({ok:true,data:[{...candidateRow,amount:'10.1010'}]})})});
  let preciseCall;const preciseMatch=await createAuthoritativeBankPaymentMatch({config,bankSourceId:entityId,bankRevision:3,candidate:preciseCandidateRead.candidates[0],reason:'Controller reviewed exact posted evidence',fetcher:async(url,options)=>{preciseCall={url,options};return {ok:true,status:201,json:async()=>({ok:true,data:{bank_match_id:'77777777-7777-4777-8777-777777777777',status:'ACTIVE'}})};}});
  assert.equal(preciseCandidateRead.candidates[0].amount_text,'10.1010');assert.equal(preciseMatch.ok,true);assert.match(preciseCall.url,/\/bank\/transactions\/.+\/matches$/);assert.equal((await createAuthoritativeBankPaymentMatch({config,bankSourceId:entityId,bankRevision:3,candidate:{...preciseCandidateRead.candidates[0],amount_text:'10.10100'},reason:'Controller reviewed exact posted evidence',fetcher:async()=>{throw new Error('must not call');}})).code,'ACCOUNTING_API_COMMAND_INVALID');
  const unmatched=await unmatchAuthoritativeBankPayment({config,bankSourceId:entityId,bankMatchId:'77777777-7777-4777-8777-777777777777',bankMatchRevision:0,reason:'Controller approved exact evidence correction',fetcher:async(url,options)=>{call={url,options};return {ok:true,status:201,json:async()=>({ok:true,data:{status:'UNMATCHED'}})};}});
  assert.equal(unmatched.ok,true);assert.match(call.url,/\/bank\/transactions\/.+\/matches\/.+\/unmatch$/);assert.equal(call.options.headers['if-match'],'"0"');assert.match(call.options.headers['idempotency-key'],/^UI-BANK-UNMATCH-/);assert.deepEqual(JSON.parse(call.options.body),{reason:'Controller approved exact evidence correction'});
  assert.equal((await createAuthoritativeBankPaymentMatch({config,bankSourceId:entityId,bankRevision:3,candidate:candidateRead.candidates[0],reason:'short',fetcher:async()=>{throw new Error('must not call');}})).code,'ACCOUNTING_API_COMMAND_INVALID');
  assert.equal((await unmatchAuthoritativeBankPayment({config,bankSourceId:entityId,bankMatchId:'bad',bankMatchRevision:0,reason:'Controller approved exact evidence correction',fetcher:async()=>{throw new Error('must not call');}})).code,'ACCOUNTING_API_COMMAND_INVALID');
  let reconciliationCall;const reconciliationRead=await refreshAuthoritativeReconciliation({config,bankAccountRef:'BANK-1',statementEndingDate:'2026-07-31',fetcher:async(url,options)=>{reconciliationCall={url,options};return {ok:true,json:async()=>({ok:true,data:[{reconciliation_id:entityId,bank_account_ref:'BANK-1',statement_ending_date:'2026-07-31',statement_ending_balance:'1000.0000',difference:'0.0000',status:'RECONCILED',version:'4',reconciled_by:'controller',reconciled_at:'2026-08-01T00:00:00.000Z',reopened_by:null,reopened_at:null,bank_transaction_count:'6',active_match_count:'5',unmatched_transaction_count:'1',statement_activity_amount:'250.0000'}]})};}});
  assert.equal(reconciliationRead.ok,true);assert.equal(reconciliationRead.row.bank_transaction_count,6);assert.match(reconciliationCall.url,/\/bank\/reconciliation\?bankAccountRef=BANK-1&statementEndingDate=2026-07-31$/);assert.equal(reconciliationCall.options.method,'GET');assert.equal(reconciliationCall.options.headers.authorization,`Bearer ${accessToken}`);assert.equal('body' in reconciliationCall.options,false);
  const validReconciliation={reconciliation_id:entityId,bank_account_ref:'BANK-1',statement_ending_date:'2026-07-31',statement_ending_balance:'1000.0000',difference:'0.0000',status:'RECONCILED',version:'4',reconciled_by:'controller',reconciled_at:'2026-08-01T00:00:00.000Z',reopened_by:null,reopened_at:null,bank_transaction_count:'6',active_match_count:'5',unmatched_transaction_count:'1',statement_activity_amount:'250.0000'};
  const readReconciliationRows=async data=>refreshAuthoritativeReconciliation({config,bankAccountRef:'BANK-1',statementEndingDate:'2026-07-31',fetcher:async()=>({ok:true,json:async()=>({ok:true,data})})});
  for(const invalid of [{...validReconciliation,status:'CLOSED'},{...validReconciliation,difference:'1.0000'},{...validReconciliation,reconciled_at:null},{...validReconciliation,reopened_by:'reviewer',reopened_at:null},{...validReconciliation,bank_transaction_count:'5'},{...validReconciliation,active_match_count:'-1'},{...validReconciliation,statement_activity_amount:'250'}])assert.equal((await readReconciliationRows([invalid])).code,'ACCOUNTING_API_PROTOCOL');
  const statementReceiptId='77777777-7777-4777-8777-777777777777';
  const admittedStatement={wbs_bank_statement_receipt_id:statementReceiptId,bank_account_ref:'BANK-1',statement_start_date:'2026-07-01',statement_end_date:'2026-07-31',currency:'USD',opening_balance:'900.0000',ending_balance:'1000.0000',transaction_count:'6',statement_activity_amount:'100.0000',admission_hash:`sha256:${'7'.repeat(64)}`,signature_verified:true,admission_status:'ADMITTED',admitted_at:'2026-08-01T00:00:00.000Z',reconciliation_id:null,reconciliation_status:null,reconciliation_version:null,selection_state:'AVAILABLE_FOR_SERVER_VALIDATION'};
  const admittedList=await refreshAuthoritativeAdmittedBankStatements({config,bankAccountRef:'BANK-1',limit:10,fetcher:async(url,options)=>{call={url,options};return {ok:true,json:async()=>({ok:true,data:[admittedStatement]})};}});
  assert.equal(admittedList.ok,true);assert.equal(admittedList.rows[0].transaction_count,6);assert.match(call.url,/\/bank\/reconciliations\/admitted-statements\?bankAccountRef=BANK-1&limit=10$/);assert.equal(call.options.method,'GET');assert.equal(call.options.cache,'no-store');assert.equal('body' in call.options,false);assert.equal('idempotency-key' in call.options.headers,false);
  const admittedDetail=await readAuthoritativeAdmittedBankStatement({config,statementReceiptId,bankAccountRef:'BANK-1',fetcher:async(url,options)=>{call={url,options};return {ok:true,json:async()=>({ok:true,data:admittedStatement})};}});
  assert.equal(admittedDetail.ok,true);assert.match(call.url,new RegExp(`/bank/reconciliations/admitted-statements/${statementReceiptId}$`));assert.equal(call.options.method,'GET');assert.equal('body' in call.options,false);
  const readAdmitted=async row=>refreshAuthoritativeAdmittedBankStatements({config,bankAccountRef:'BANK-1',fetcher:async()=>({ok:true,json:async()=>({ok:true,data:[row]})})});
  for(const invalid of [{...admittedStatement,statement_start_date:'2026-06-30T16:00:00.000Z'},{...admittedStatement,statement_activity_amount:'99.0000'},{...admittedStatement,signature_verified:false},{...admittedStatement,admission_status:'PILOT'},{...admittedStatement,selection_state:'AVAILABLE_FOR_SERVER_VALIDATION',reconciliation_id:entityId,reconciliation_status:'DRAFT',reconciliation_version:'0'},{...admittedStatement,provider_payload_ref:'forbidden'}])assert.equal((await readAdmitted(invalid)).code,'ACCOUNTING_API_PROTOCOL');
  assert.equal((await readAuthoritativeAdmittedBankStatement({config,statementReceiptId,bankAccountRef:'BANK-OTHER',fetcher:async()=>({ok:true,json:async()=>({ok:true,data:admittedStatement})})})).code,'ACCOUNTING_API_PROTOCOL');
  const admittedStarted=await startAuthoritativeReconciliationFromAdmittedStatement({config,statement:admittedDetail.row,reason:'Controller starts signed statement review',fetcher:async(url,options)=>{call={url,options};return {ok:true,status:201,json:async()=>({ok:true,data:{reconciliation_id:entityId,wbs_bank_statement_receipt_id:statementReceiptId,status:'DRAFT'}})};}});
  assert.equal(admittedStarted.ok,true);assert.match(call.url,/\/bank\/reconciliations\/from-admitted-statement$/);assert.match(call.options.headers['idempotency-key'],/^UI-RECONCILIATION-START_ADMITTED_STATEMENT-[a-f0-9]{64}$/);assert.equal(call.options.headers['if-match'],undefined);assert.deepEqual(JSON.parse(call.options.body),{statementReceiptId,reason:'Controller starts signed statement review'});
  for(const blocked of [{...admittedDetail.row,signature_verified:false},{...admittedDetail.row,admission_status:'PILOT'},{...admittedDetail.row,selection_state:'BLOCKED_OPEN_RECONCILIATION'}])assert.equal((await startAuthoritativeReconciliationFromAdmittedStatement({config,statement:blocked,reason:'Controller starts signed statement review',fetcher:async()=>{throw new Error('must not call');}})).code,'ACCOUNTING_API_COMMAND_INVALID');
  const worksheetRow={reconciliation_id:entityId,reconciliation_version:'4',bank_source_id:'22222222-2222-4222-8222-222222222222',bank_version:'3',bank_account_ref:'BANK-1',external_bank_line_id:'BANK-LINE-1',transaction_date:'2026-07-15',currency:'USD',amount:'-125.2500',bank_match_id:'33333333-3333-4333-8333-333333333333',bank_match_version:'1',match_status:'ACTIVE',business_source_document_id:'44444444-4444-4444-8444-444444444444',journal_entry_id:'55555555-5555-4555-8555-555555555555',journal_line_id:'66666666-6666-4666-8666-666666666666',clearance_state:'NOT_CLEARED',reconciliation_item_id:null,item_version:null,cleared_by:null,cleared_at:null,uncleared_by:null,uncleared_at:null};
  let worksheetCall;const worksheetRead=await refreshAuthoritativeReconciliationWorksheet({config,reconciliationId:entityId,fetcher:async(url,options)=>{worksheetCall={url,options};return {ok:true,json:async()=>({ok:true,data:[worksheetRow]})};}});
  assert.equal(worksheetRead.ok,true);assert.equal(worksheetRead.rows[0].bank_version,3);assert.match(worksheetCall.url,/\/bank\/reconciliations\/.+\/worksheet$/);assert.equal(worksheetCall.options.method,'GET');assert.equal('body' in worksheetCall.options,false);
  const readWorksheet=data=>refreshAuthoritativeReconciliationWorksheet({config,reconciliationId:entityId,fetcher:async()=>({ok:true,json:async()=>({ok:true,data})})});
  assert.equal((await readWorksheet([{...worksheetRow,match_status:'UNMATCHED'}])).code,'ACCOUNTING_API_PROTOCOL');
  assert.equal((await readWorksheet([{...worksheetRow,clearance_state:'CLEARED',reconciliation_item_id:null}])).code,'ACCOUNTING_API_PROTOCOL');
  const clearance=await setAuthoritativeReconciliationClearance({config,reconciliationId:entityId,reconciliationRevision:4,row:worksheetRead.rows[0],clear:true,reason:'Controller reviewed exact active match evidence',fetcher:async(url,options)=>{call={url,options};return {ok:true,status:201,json:async()=>({ok:true,data:{status:'CLEARED'}})};}});
  assert.equal(clearance.ok,true);assert.match(call.url,/\/bank\/reconciliations\/.+\/items\/.+\/clearance$/);assert.equal(call.options.headers['if-match'],'"4"');assert.match(call.options.headers['idempotency-key'],/^UI-RECONCILIATION-CLEAR-/);assert.deepEqual(JSON.parse(call.options.body),{clear:true,expectedBankRevision:3,reason:'Controller reviewed exact active match evidence'});
  assert.equal((await setAuthoritativeReconciliationClearance({config,reconciliationId:entityId,reconciliationRevision:4,row:{...worksheetRead.rows[0],match_status:null,bank_match_id:null},clear:true,reason:'Controller reviewed exact active match evidence',fetcher:async()=>{throw new Error('must not call');}})).code,'ACCOUNTING_API_COMMAND_INVALID');
  const adjustmentRow={...worksheetRead.rows[0],amount:125.25,amount_text:'125.2500',bank_match_id:null,bank_match_version:null,match_status:null,business_source_document_id:null,journal_entry_id:null,journal_line_id:null,adjustment_journal_entry_id:'88888888-8888-4888-8888-888888888888',adjustment_journal_version:4,adjustment_journal_status:'POSTED',adjustment_clearance_eligible:true};
  const adjustment=await createAuthoritativeReconciliationAdjustmentDraft({config,reconciliationId:entityId,reconciliationRevision:4,row:adjustmentRow,journalNumber:'REC-ADJ-001',journalDate:'2026-07-31',offsetAccountCode:'610000',description:'Controller-reviewed reconciliation adjustment',attachmentIds:['77777777-7777-4777-8777-777777777777'],reason:'Controller records an exact bank adjustment',fetcher:async(url,options)=>{call={url,options};return {ok:true,status:201,json:async()=>({ok:true,data:{journal_entry_id:'88888888-8888-4888-8888-888888888888',journal_status:'DRAFT'}})};}});
  assert.equal(adjustment.ok,true);assert.match(call.url,/\/bank\/reconciliations\/.+\/adjustment-drafts$/);assert.equal(call.options.headers['if-match'],'"4"');assert.match(call.options.headers['idempotency-key'],/^UI-RECONCILIATION-ADJUSTMENT_DRAFT-[a-f0-9]{64}$/);assert.deepEqual(JSON.parse(call.options.body),{bankSourceId:adjustmentRow.bank_source_id,periodId,journalNumber:'REC-ADJ-001',journalDate:'2026-07-31',currency:'USD',description:'Controller-reviewed reconciliation adjustment',lines:[{lineNo:1,accountCode:'111000',debitAmount:'125.2500',creditAmount:'0.0000',memberRef:'BANK-1',description:'Controller-reviewed reconciliation adjustment',dimensions:{}},{lineNo:2,accountCode:'610000',debitAmount:'0.0000',creditAmount:'125.2500',memberRef:null,description:'Controller-reviewed reconciliation adjustment',dimensions:{}}],attachmentIds:['77777777-7777-4777-8777-777777777777'],reason:'Controller records an exact bank adjustment'});
  assert.equal((await createAuthoritativeReconciliationAdjustmentDraft({config,reconciliationId:entityId,reconciliationRevision:4,row:adjustmentRow,journalNumber:'REC-ADJ-001',journalDate:'2026-07-31',offsetAccountCode:'111000',attachmentIds:[entityId],reason:'Controller records an exact bank adjustment',fetcher:async()=>{throw new Error('must not call');}})).code,'ACCOUNTING_API_COMMAND_INVALID');
  const adjustmentClearance=await setAuthoritativeReconciliationAdjustmentClearance({config,reconciliationId:entityId,reconciliationRevision:4,row:adjustmentRow,clear:true,reason:'Controller clears exact posted adjustment evidence',fetcher:async(url,options)=>{call={url,options};return {ok:true,status:201,json:async()=>({ok:true,data:{status:'CLEARED'}})};}});
  assert.equal(adjustmentClearance.ok,true);assert.match(call.url,/\/bank\/reconciliations\/.+\/adjustment-items\/.+\/clearance$/);assert.equal(call.options.headers['if-match'],'"4"');assert.match(call.options.headers['idempotency-key'],/^UI-RECONCILIATION-ADJUSTMENT-CLEAR-/);assert.deepEqual(JSON.parse(call.options.body),{clear:true,expectedBankRevision:3,reason:'Controller clears exact posted adjustment evidence'});
  const started=await startAuthoritativeReconciliation({config,bankAccountRef:'BANK-1',statementEndingDate:'2026-07-31',statementOpeningBalance:'900.0000',statementEndingBalance:'1000.0000',reason:'Controller starts July statement review',fetcher:async(url,options)=>{call={url,options};return {ok:true,status:201,json:async()=>({ok:true,data:{reconciliation_id:entityId,status:'DRAFT'}})};}});
  assert.equal(started.ok,true);assert.match(call.url,/\/bank\/reconciliations$/);assert.equal(call.options.headers['if-match'],undefined);assert.match(call.options.headers['idempotency-key'],/^UI-RECONCILIATION-START-[a-f0-9]{64}$/);assert.deepEqual(JSON.parse(call.options.body),{bankAccountRef:'BANK-1',statementEndingDate:'2026-07-31',statementOpeningBalance:'900.0000',statementEndingBalance:'1000.0000',reason:'Controller starts July statement review'});
  const reviewed=await transitionAuthoritativeReconciliation({config,reconciliationId:entityId,revision:4,action:'REVIEW',reason:'Independent reviewer checked worksheet',fetcher:async(url,options)=>{call={url,options};return {ok:true,status:201,json:async()=>({ok:true,data:{status:'IN_REVIEW'}})};}});
  assert.equal(reviewed.ok,true);assert.match(call.url,/\/bank\/reconciliations\/.+\/transitions\/review$/);assert.equal(call.options.headers['if-match'],'"4"');assert.match(call.options.headers['idempotency-key'],/^UI-RECONCILIATION-REVIEW-[a-f0-9]{64}$/);assert.deepEqual(JSON.parse(call.options.body),{reason:'Independent reviewer checked worksheet'});
  assert.equal((await startAuthoritativeReconciliation({config,bankAccountRef:'BANK-1',statementEndingDate:'2026-07-31',statementOpeningBalance:'900',statementEndingBalance:'1000.0000',reason:'Controller starts July statement review',fetcher:async()=>{throw new Error('must not call');}})).code,'ACCOUNTING_API_COMMAND_INVALID');
  assert.equal((await transitionAuthoritativeReconciliation({config,reconciliationId:entityId,revision:4,action:'DELETE',reason:'Invalid transition action',fetcher:async()=>{throw new Error('must not call');}})).code,'ACCOUNTING_API_COMMAND_INVALID');
  assert.equal((await refreshAuthoritativeBankTransactions({config,bankAccountRef:'',fetcher:async()=>{throw new Error('must not call');}})).code,'ACCOUNTING_API_SCOPE_INVALID');
  assert.equal((await refreshAuthoritativeBankTransactions({config,bankAccountRef:'BANK-1',from:'2026-08-01',through:'2026-07-31',fetcher:async()=>{throw new Error('must not call');}})).code,'ACCOUNTING_API_SCOPE_INVALID');
  assert.equal((await refreshAuthoritativeReconciliation({config,bankAccountRef:'BANK-1',statementEndingDate:'2026-02-30',fetcher:async()=>{throw new Error('must not call');}})).code,'ACCOUNTING_API_SCOPE_INVALID');
  const attachmentId='44444444-4444-4444-8444-444444444444';const created=await createAuthoritativeBusinessDocument({config,kind:'AP_BILL',idempotencyKey:'AP-BILL-request-0001',document:{documentNumber:'B-2',counterpartyRef:'V-2',counterpartyName:'Vendor 2',currency:'USD',accountingDate:'2026-08-01',dueDate:'2026-08-31',amount:3,offsetAccountCode:'641600',attachmentIds:[attachmentId]},fetcher:async(url,options)=>{call={url,options};return {ok:true,status:201,json:async()=>({ok:true,data:{business_document_id:entityId,status:'DRAFT'}})};}});
  assert.equal(created.ok,true);assert.match(call.url,/\/ap\/bills$/);assert.equal(call.options.credentials,'include');assert.equal(call.options.headers.authorization,`Bearer ${accessToken}`);assert.equal(call.options.headers['idempotency-key'],'AP-BILL-request-0001');assert.equal(JSON.parse(call.options.body).periodId,periodId);assert.deepEqual(JSON.parse(call.options.body).attachmentIds,[attachmentId]);
  const paid=await createAuthoritativeSettlement({config,kind:'AP_PAYMENT',businessDocumentId:entityId,accountingDate:'2026-08-02',amount:7.25,idempotencyKey:'AP-PAY-request-0001',fetcher:async(url,options)=>{call={url,options};return {ok:true,status:201,json:async()=>({ok:true,data:{status:'DRAFT'}})};}});
  assert.equal(paid.ok,true);assert.match(call.url,/\/ap\/bills\/.+\/payments$/);assert.equal(JSON.parse(call.options.body).cashAccountCode,'111000');assert.equal(JSON.parse(call.options.body).bankMemberRef,null);
  const credit=await createAuthoritativeAdjustment({config,kind:'AP_VENDOR_CREDIT',idempotencyKey:'AP-CREDIT-request-0001',adjustment:{number:'VC-100',date:'2026-08-02',counterpartyRef:'V-1',counterpartyName:'Vendor',amount:10,lines:[{line_no:1,account_code:'610000',amount:10}],reason:'Approved vendor credit'},fetcher:async(url,options)=>{call={url,options};return {ok:true,status:201,json:async()=>({ok:true,data:{business_adjustment_id:entityId,status:'DRAFT'}})};}});
  assert.equal(credit.ok,true);assert.match(call.url,/\/ap\/vendor-credits$/);assert.equal(JSON.parse(call.options.body).creditNumber,'VC-100');
  const memo=await createAuthoritativeAdjustment({config,kind:'AR_CREDIT_MEMO',idempotencyKey:'AR-CREDIT-request-0001',adjustment:{number:'CM-100',date:'2026-08-02',counterpartyRef:'C-1',counterpartyName:'Customer',amount:4,lines:[{line_no:1,account_code:'411100',amount:4}],reason:'Approved customer credit'},fetcher:async(url,options)=>{call={url,options};return {ok:true,status:201,json:async()=>({ok:true,data:{business_adjustment_id:entityId,status:'DRAFT'}})};}});
  assert.equal(memo.ok,true);assert.match(call.url,/\/ar\/credit-memos$/);assert.equal(JSON.parse(call.options.body).memoNumber,'CM-100');
  const allocation=await applyAuthoritativeCredit({config,kind:'AR_CREDIT_MEMO',businessAdjustmentId:entityId,businessDocumentId:'22222222-2222-4222-8222-222222222222',amount:5,reason:'Apply posted credit',idempotencyKey:'AR-CREDIT-ALLOC-0001',fetcher:async(url,options)=>{call={url,options};return {ok:true,status:201,json:async()=>({ok:true,data:{status:'PENDING'}})};}});
  assert.equal(allocation.ok,true);assert.match(call.url,/\/ar\/credit-memos\/.+\/allocations$/);assert.equal(JSON.parse(call.options.body).amount,5);
  const refund=await createAuthoritativeAdjustment({config,kind:'AR_REFUND',idempotencyKey:'AR-REFUND-request-0001',adjustment:{sourceAdjustmentId:entityId,number:'RF-100',date:'2026-08-02',amount:5,reason:'Return customer credit'},fetcher:async(url,options)=>{call={url,options};return {ok:true,status:201,json:async()=>({ok:true,data:{status:'DRAFT'}})};}});
  assert.equal(refund.ok,true);assert.match(call.url,/\/ar\/refunds$/);assert.equal(JSON.parse(call.options.body).cashAccountCode,'111000');
  const advanced=await transitionAuthoritativeJournal({config,journalEntryId:entityId,revision:2,action:'POST',fetcher:async(url,options)=>{call={url,options};return {ok:true,status:201,json:async()=>({ok:true,data:{status:'POSTED',revision:3}})};}});
  assert.equal(advanced.ok,true);assert.match(call.url,/\/journal-entries\/.+\/post$/);assert.equal(call.options.headers['if-match'],'"2"');assert.equal(JSON.parse(call.options.body).periodId,periodId);
  const attachmentMissing=await createAuthoritativeBusinessDocument({config,kind:'AP_BILL',idempotencyKey:'AP-BILL-attachment-missing',document:{documentNumber:'B-3'},fetcher:async()=>{throw new Error('must not call');}});assert.equal(attachmentMissing.code,'ATTACHMENT_REQUIRED');
  const missingToken=await createAuthoritativeBusinessDocument({config:{...config,getAccessToken:async()=>null},kind:'AP_BILL',idempotencyKey:'AP-BILL-token-missing',document:{documentNumber:'B-3',attachmentIds:[attachmentId]},fetcher:async()=>{throw new Error('must not call');}});assert.equal(missingToken.code,'AUTHENTICATION_REQUIRED');
  let agingCall;const apAging=await refreshAuthoritativeAging({config,side:'ap',asOfDate:'2026-07-31',fetcher:async(url,options)=>{agingCall={url,options};return {ok:true,json:async()=>({ok:true,data:[{currency:'USD',current_amount:'100.0000',days_1_30:'0.0000',days_31_60:'0.0000',days_61_90:'0.0000',days_91_plus:'25.5000',total_open_balance:'125.5000'}]})};}});
  assert.equal(apAging.ok,true);assert.equal(apAging.rows[0].total_open_balance,'125.5000');assert.match(agingCall.url,/\/ap\/aging\?asOf=2026-07-31$/);assert.equal(agingCall.options.method,'GET');assert.equal(agingCall.options.cache,'no-store');assert.equal(agingCall.options.headers.authorization,`Bearer ${accessToken}`);assert.equal('body' in agingCall.options,false);
  const arAgingNum=await refreshAuthoritativeAging({config,side:'ar',asOfDate:'2026-07-31',fetcher:async()=>({ok:true,json:async()=>({ok:true,data:[{currency:'USD',current_amount:5,days_1_30:0,days_31_60:0,days_61_90:0,days_91_plus:0,total_open_balance:5}]})})});
  assert.equal(arAgingNum.ok,true);assert.equal(arAgingNum.rows[0].total_open_balance,'5.0000');
  assert.equal((await refreshAuthoritativeAging({config,side:'ap',asOfDate:'2026-02-30',fetcher:async()=>{throw new Error('must not call');}})).code,'ACCOUNTING_API_SCOPE_INVALID');
  assert.equal((await refreshAuthoritativeAging({config,side:'xx',asOfDate:'2026-07-31',fetcher:async()=>{throw new Error('must not call');}})).code,'ACCOUNTING_API_SCOPE_INVALID');
  let ctCall;const apControl=await refreshAuthoritativeControlTotals({config,side:'ap',fetcher:async(url,options)=>{ctCall={url,options};return {ok:true,json:async()=>({ok:true,data:[{currency:'USD',open_balance:'125.5000',control_balance:'125.5000',in_balance:true}]})};}});
  assert.equal(apControl.ok,true);assert.equal(apControl.rows[0].in_balance,true);assert.equal(apControl.rows[0].open_balance,'125.5000');assert.match(ctCall.url,/\/ap\/control-totals$/);assert.equal(ctCall.options.method,'GET');assert.equal('body' in ctCall.options,false);
  assert.equal((await refreshAuthoritativeControlTotals({config,side:'zz',fetcher:async()=>{throw new Error('must not call');}})).code,'ACCOUNTING_API_SCOPE_INVALID');

  // -------------------------------------------------------------------------
  // Failure classification.
  //
  // These are simulated responses, not a live accounting API: there is no API
  // reachable from this test environment. What is proven here is that the
  // client turns each observable condition into a distinct code, so the UI can
  // tell the reader what actually happened instead of guessing a cause.
  // -------------------------------------------------------------------------
  const respond=(status,body)=>({ok:status>=200&&status<300,status,json:async()=>body});
  const transportFailure=async()=>{throw new TypeError('Failed to fetch');};

  for(const [status,expected] of [[401,'AUTHENTICATION_REQUIRED'],[403,'AUTHORIZATION_DENIED'],[500,'ACCOUNTING_API_SERVER_ERROR'],[502,'ACCOUNTING_API_SERVER_ERROR'],[400,'JSON_OBJECT_REQUIRED'],[404,'SOMETHING_ELSE'],[409,'SOMETHING_ELSE']]){
    const journals=await refreshAuthoritativeJournalEntries({config,fetcher:async()=>respond(status,{ok:false,code:status===400?'JSON_OBJECT_REQUIRED':'SOMETHING_ELSE',message:'server text'})});
    assert.equal(journals.ok,false);
    assert.equal(journals.code,expected,`HTTP ${status} must classify as ${expected}`);
    assert.equal(journals.status,status);
    const documents=await refreshAuthoritativeDocuments({config,fetcher:async()=>respond(status,{ok:false,code:status===400?'JSON_OBJECT_REQUIRED':'SOMETHING_ELSE',message:'server text'})});
    assert.equal(documents.code,expected,`AP/AR read must classify HTTP ${status} as ${expected}`);
  }

  // A status with no domain code in the body still classifies from the status.
  for(const [status,expected] of [[404,'ACCOUNTING_API_SCOPE_NOT_FOUND'],[429,'ACCOUNTING_API_RATE_LIMITED'],[418,'ACCOUNTING_API_REQUEST_REJECTED']]){
    const bare=await refreshAuthoritativeJournalEntries({config,fetcher:async()=>respond(status,{ok:false})});
    assert.equal(bare.code,expected,`HTTP ${status} without a domain code must classify as ${expected}`);
  }
  // A 5xx is decided by the status line: a server failure must not be relabelled
  // by whatever the failing server put in the body.
  assert.equal((await refreshAuthoritativeJournalEntries({config,fetcher:async()=>respond(503,{ok:false,code:'PERIOD_CLOSED'})})).code,'ACCOUNTING_API_SERVER_ERROR');
  assert.match((await refreshAuthoritativeJournalEntries({config,fetcher:async()=>respond(503,{ok:false,code:'PERIOD_CLOSED'})})).message,/Read: JOURNAL_ENTRIES\./);
  const failedBill=await refreshAuthoritativeDocuments({config,fetcher:async url=>url.includes('/ap/bills')?respond(500,{ok:false,code:'INTERNAL_ERROR'}):respond(200,{ok:true,data:[]})});
  assert.equal(failedBill.code,'ACCOUNTING_API_SERVER_ERROR');
  assert.match(failedBill.message,/Read: AP_BILLS\./);

  // A 401 or 403 is decided by the status line. A body code must not be able to
  // relabel an authentication failure as an authorization failure or the reverse.
  assert.equal((await refreshAuthoritativeJournalEntries({config,fetcher:async()=>respond(403,{ok:false,code:'AUTHENTICATION_REQUIRED',message:'wrong'})})).code,'AUTHORIZATION_DENIED');
  assert.equal((await refreshAuthoritativeJournalEntries({config,fetcher:async()=>respond(401,{ok:false,code:'AUTHORIZATION_DENIED',message:'wrong'})})).code,'AUTHENTICATION_REQUIRED');
  // An authorization refusal must not echo the server text: it must not describe
  // what the caller is not allowed to see.
  const refused=await refreshAuthoritativeJournalEntries({config,fetcher:async()=>respond(403,{ok:false,code:'X',message:'entity 42 belongs to tenant Northwind'})});
  assert.ok(!refused.message.includes('Northwind'),'a 403 must not echo server-supplied detail');

  // No HTTP response at all is a transport failure and is reported as one.
  for(const read of [refreshAuthoritativeJournalEntries,refreshAuthoritativeDocuments]){
    const result=await read({config,fetcher:transportFailure});
    assert.equal(result.ok,false);assert.equal(result.code,'ACCOUNTING_API_UNREACHABLE');
  }
  assert.equal((await refreshAuthoritativeBankTransactions({config,bankAccountRef:'BANK-1',fetcher:transportFailure})).code,'ACCOUNTING_API_UNREACHABLE');
  assert.equal((await refreshAuthoritativeBankMatchCandidates({config,bankSourceId:entityId,fetcher:transportFailure})).code,'ACCOUNTING_API_UNREACHABLE');
  assert.equal((await refreshAuthoritativeReconciliation({config,bankAccountRef:'BANK-1',statementEndingDate:'2026-07-31',fetcher:transportFailure})).code,'ACCOUNTING_API_UNREACHABLE');
  assert.equal((await transitionAuthoritativeJournal({config,journalEntryId:entityId,revision:1,action:'POST',fetcher:transportFailure})).code,'ACCOUNTING_API_UNREACHABLE');

  // A 200 whose shape the read contract rejects is neither unreachable nor a
  // server error: partial data is discarded rather than displayed.
  assert.equal((await refreshAuthoritativeJournalEntries({config,fetcher:async()=>respond(200,{ok:true,data:{}})})).code,'ACCOUNTING_API_PROTOCOL');
  assert.equal((await refreshAuthoritativeDocuments({config,fetcher:async()=>respond(200,{ok:true,data:'not-an-array'})})).code,'ACCOUNTING_API_PROTOCOL');
  const malformedDocument=await refreshAuthoritativeDocuments({config,fetcher:async url=>respond(200,{ok:true,data:url.includes('/ap/bills')?[{...rows['/ap/bills'][0],accounting_date:'2026-02-30'}]:url.includes('/ar/invoices')?rows['/ar/invoices']:url.includes('/ap/adjustments')?rows['/ap/adjustments']:rows['/ar/adjustments']})});
  assert.equal(malformedDocument.code,'ACCOUNTING_API_PROTOCOL');
  const malformedAdjustment=await refreshAuthoritativeDocuments({config,fetcher:async url=>respond(200,{ok:true,data:url.includes('/ap/bills')?rows['/ap/bills']:url.includes('/ar/invoices')?rows['/ar/invoices']:url.includes('/ap/adjustments')?[{...rows['/ap/adjustments'][0],adjustment_kind:'AR_CREDIT_MEMO'}]:rows['/ar/adjustments']})});
  assert.equal(malformedAdjustment.code,'ACCOUNTING_API_PROTOCOL');
  const unboundedAmount=await refreshAuthoritativeDocuments({config,fetcher:async url=>respond(200,{ok:true,data:url.includes('/ap/bills')?[{...rows['/ap/bills'][0],gross_amount:`${'9'.repeat(400)}.0000`}]:url.includes('/ar/invoices')?rows['/ar/invoices']:url.includes('/ap/adjustments')?rows['/ap/adjustments']:rows['/ar/adjustments']})});
  assert.equal(unboundedAmount.code,'ACCOUNTING_API_PROTOCOL');

  // A read where one of the four business-document calls is refused reports that
  // refusal, not a generic failure.
  const mixed=await refreshAuthoritativeDocuments({config,fetcher:async url=>url.includes('/ar/adjustments')?respond(403,{ok:false}):respond(200,{ok:true,data:[]})});
  assert.equal(mixed.code,'AUTHORIZATION_DENIED');

  // No configuration at all is a deployment problem, not an API failure.
  assert.equal((await refreshAuthoritativeDocuments({config:null,fetcher:async()=>respond(200,{ok:true,data:[]})})).code,'CONFIGURATION_REQUIRED');
  assert.equal((await refreshAuthoritativeJournalEntries({config:null,fetcher:async()=>respond(200,{ok:true,data:[]})})).code,'CONFIGURATION_REQUIRED');

  // An expired or absent access token is reported before any request is made.
  assert.equal((await refreshAuthoritativeJournalEntries({config:{...config,getAccessToken:async()=>{throw new Error('OIDC access token is unavailable or expired');}},fetcher:async()=>{throw new Error('must not call');}})).code,'AUTHENTICATION_REQUIRED');

  const transitionEvidence={schema_version:'WBS_AUTOREC_TRANSITION_CONTRACT_V1',source_system:'WBS',environment:'PRODUCTION',contract_id:entityId,contract_hash:`sha256:${'a'.repeat(64)}`,issued_at:'2026-08-11T00:00:00.000Z',valid_from:'2026-08-11T00:00:00.000Z',valid_until:'2026-08-12T00:00:00.000Z',scope:{company_keys:['COMPANY-A'],dictionary_version:'WBS-2026-08'},transitions:[{transition_id:'CANCEL_RELEASE_V1',operation:'CANCEL_RELEASE',from_state:'RELEASED',to_state:'NOT_MATCHED',requires_reason:true,required_actor_roles:['AUTOREC_CONTROLLER'],segregation_of_duties:{review_required:true,requester_reviewer_must_differ:true},accounting_guard:{blocks_when_accounting_reviewed:true,blocks_when_accounting_approved:true,blocks_when_accounting_posted:true}}],signature:{key_id:'wbs-ed25519-1',algorithm:'Ed25519'},signature_verified:true,transition_authority:'WBS_SIGNED_EXTERNAL_EVIDENCE_ONLY',can_transition_refs:false,can_release:false,can_incur:false,can_reverse:false,can_create_draft:false,can_post:false};
  let wbsAccessRequest;const wbsAccess=await activateAuthoritativeWbsReadAccess({config,idempotencyKey:'wbs-read-access-0001',fetcher:async(url,options)=>{wbsAccessRequest={url,options};return respond(201,{ok:true,data:{upgraded:true,idempotent:false,permission_count:6}});}});
  assert.equal(wbsAccess.ok,true);assert.match(wbsAccessRequest.url,/\/access\/self-service-wbs-read-grant\/upgrade$/);assert.equal(wbsAccessRequest.options.method,'POST');assert.equal(wbsAccessRequest.options.headers['idempotency-key'],'wbs-read-access-0001');assert.deepEqual(JSON.parse(wbsAccessRequest.options.body),{});
  assert.equal((await activateAuthoritativeWbsReadAccess({config,idempotencyKey:'short',fetcher:async()=>{throw new Error('must not call');}})).code,'WBS_READ_ACCESS_SCOPE_INVALID');
  assert.equal((await activateAuthoritativeWbsReadAccess({config,idempotencyKey:'wbs-read-access-0002',fetcher:async()=>respond(201,{ok:true,data:{upgraded:true,permission_count:7}})})).code,'ACCOUNTING_API_PROTOCOL');
  let operatorAccessRequest;const operatorAccess=await activateAuthoritativeWbsOperatorAccess({config,idempotencyKey:'wbs-operator-access-0001',fetcher:async(url,options)=>{operatorAccessRequest={url,options};return respond(201,{ok:true,data:{upgraded:true,idempotent:false,permission_count:7}});}});
  assert.equal(operatorAccess.ok,true);assert.match(operatorAccessRequest.url,/\/access\/self-service-wbs-operator-grant\/upgrade$/);assert.equal(operatorAccessRequest.options.method,'POST');assert.equal(operatorAccessRequest.options.headers['idempotency-key'],'wbs-operator-access-0001');
  assert.equal((await activateAuthoritativeWbsOperatorAccess({config,idempotencyKey:'short',fetcher:async()=>{throw new Error('must not call');}})).code,'WBS_OPERATOR_ACCESS_SCOPE_INVALID');
  const pilotRows={
    list_payables:{source_record_hash:`sha256:${'1'.repeat(64)}`,accounting_date:'2026-08-01',currency:'USD',amount:'25.0000',status:'OPEN'},
    list_bank_transactions:{source_record_hash:`sha256:${'2'.repeat(64)}`,accounting_date:'2026-08-01',currency:'USD',amount:'25.0000',direction:'DEBIT',status:'UNMATCHED'},
    list_autorec_details:{source_record_hash:`sha256:${'3'.repeat(64)}`,accounting_date:'2026-08-01',currency:'USD',payment_amount:'25.0000',deposit_amount:'0.0000',status:'RELEASED',match_status:'MATCHED'},
    list_autorec_banks:{source_record_hash:`sha256:${'4'.repeat(64)}`,currency:'USD',pay_amount:'25.0000',debit_amount:'0.0000',quantity:'1.0000',released_amount:'25.0000',released_quantity:'1.0000',incurred_amount:'25.0000',status:'ACTIVE'},
    list_journal_entries:{source_record_hash:`sha256:${'5'.repeat(64)}`,accounting_date:'2026-08-01',currency:'USD',debit_amount:'25.0000',credit_amount:'0.0000',review_status:'REVIEWED'}
  };
  const pilotEvidence=(tool,row=pilotRows[tool])=>({schema_version:'WBS_LIVE_PILOT_OBSERVATION_V1',status:'NOT_ADMITTED',observation_mode:'UNSIGNED_PILOT',source_system:'WBS',tool,environment:'PRODUCTION',entity_id:entityId,captured_at:'2026-08-12T00:00:00.000Z',provider_content_sha256:'a'.repeat(64),observation_hash:`sha256:${'b'.repeat(64)}`,record_count:row?1:0,signature_verified:false,scope:{company_codes:['COMPANY-A'],date_range:['2026-08-01','2026-08-12']},rows:row?[row]:[],can_import:false,can_create_transaction:false,can_match:false,can_allocate:false,can_create_draft:false,can_approve:false,can_post:false,can_reverse:false});
  for(const [tool,row] of Object.entries(pilotRows)){
    let request;const read=await refreshAuthoritativeWbsLivePilot({config,tool,fetcher:async(url,options)=>{request={url,options};return respond(200,{ok:true,data:pilotEvidence(tool)});}});
    assert.equal(read.ok,true);assert.match(request.url,new RegExp(`/wbs/live-pilot\\?tool=${tool}&limit=10$`));assert.equal(request.options.method,'GET');assert.equal(request.options.cache,'no-store');assert.equal(request.options.headers.authorization,`Bearer ${accessToken}`);assert.equal('body' in request.options,false);assert.equal('idempotency-key' in request.options.headers,false);
    const withUnexpected={...row,description:'must never reach browser'};
    assert.equal((await refreshAuthoritativeWbsLivePilot({config,tool,fetcher:async()=>respond(200,{ok:true,data:pilotEvidence(tool,withUnexpected)})})).code,'WBS_LIVE_PILOT_PROTOCOL');
  }
  const providerBankRow={pb_guid:'provider-row-redacted',pay_amount:'100.00000',debit_amount:'0.00000',quantity:'2.00000',released:'50.00000',released_quantity:null,incurred:'25.00000',status:'N'};
  const providerEnvelope={tool_name:'list_autorec_banks',contract_version:'WBS-REFS-MCP-V1',environment:'production',captured_at:'2026-08-12T00:00:00.000Z',scope:{company_codes:[],date_range:[]},record_count:1,content_sha256:canonicalRequestHash([providerBankRow]).slice(7),cursor_next:null,rows:[providerBankRow]};
  const providerService=createWbsLivePilotReadService({client:{initialize:async()=>{},listTools:async()=>{},readView:async()=>providerEnvelope},authorize:async()=>true});
  const sanitizedProviderBank=await providerService.readObservation({tenantId:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',entityId,tool:'list_autorec_banks',limit:10});
  const providerBankRead=await refreshAuthoritativeWbsLivePilot({config,tool:'list_autorec_banks',fetcher:async()=>respond(200,{ok:true,data:sanitizedProviderBank})});
  assert.equal(providerBankRead.ok,true);assert.equal(providerBankRead.data.rows[0].released_quantity,null);assert.deepEqual(Object.keys(providerBankRead.data.rows[0]),WBS_LIVE_PILOT_VIEWS.list_autorec_banks.fields);assert.equal(JSON.stringify(providerBankRead.data).includes('provider-row-redacted'),false);
  let scopedRequest;const scopedPilot=await refreshAuthoritativeWbsLivePilot({config,tool:'list_payables',companyCode:'COMPANY-A',dateFrom:'2026-01-01',dateTo:'2026-12-31',fetcher:async(url,options)=>{scopedRequest={url,options};return respond(200,{ok:true,data:{...pilotEvidence('list_payables'),scope:{company_codes:['COMPANY-A'],date_range:['2026-01-01','2026-12-31']}}});}});
  assert.equal(scopedPilot.ok,true);assert.match(scopedRequest.url,/tool=list_payables&limit=10&company_code=COMPANY-A&date_from=2026-01-01&date_to=2026-12-31$/);assert.deepEqual(scopedPilot.scope,{entityId,tool:'list_payables',limit:10,companyCode:'COMPANY-A',dateFrom:'2026-01-01',dateTo:'2026-12-31'});
  assert.equal((await refreshAuthoritativeWbsLivePilot({config,tool:'list_payables',companyCode:'COMPANY-A',dateFrom:'2026-01-01',dateTo:'2026-12-31',fetcher:async()=>respond(200,{ok:true,data:{...pilotEvidence('list_payables'),scope:{company_codes:['OTHER'],date_range:['2026-01-01','2026-12-31']}}})})).code,'WBS_LIVE_PILOT_PROTOCOL');
  assert.equal((await refreshAuthoritativeWbsLivePilot({config,tool:'list_payables',dateFrom:'2026-01-01',fetcher:async()=>{throw new Error('must not call');}})).code,'WBS_LIVE_PILOT_SCOPE_INVALID');
  const liveJournalProviderFixture={tool_name:'list_journal_entries',contract_version:'WBS-REFS-MCP-V1',environment:'production',captured_at:'2026-08-12T00:00:00.000Z',scope:{company_codes:['COMPANY-A'],date_range:['2026-08-01','2026-08-12']},record_count:1,content_sha256:'c'.repeat(64),cursor_next:null,rows:[{id:7,posting_date:'2026-08-08 04:05:06',debtor:'9.25',lender:'0.00',review:'0'}]};
  const liveJournalService=createWbsLivePilotReadService({client:{initialize:async()=>{},listTools:async()=>{},readView:async()=>liveJournalProviderFixture},authorize:async()=>{}});
  const liveJournalResponse=await liveJournalService.readObservation({tenantId:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',entityId,tool:'list_journal_entries',limit:1});
  assert.deepEqual(liveJournalResponse.rows,[{source_record_hash:liveJournalResponse.rows[0].source_record_hash,currency:'USD',accounting_date:'2026-08-08',debit_amount:'9.2500',credit_amount:'0.0000',review_status:'CODE_0'}]);
  const liveJournalClientRead=await refreshAuthoritativeWbsLivePilot({config,tool:'list_journal_entries',limit:1,fetcher:async(url,options)=>{assert.match(url,/\/wbs\/live-pilot\?tool=list_journal_entries&limit=1$/);assert.equal(options.method,'GET');assert.equal('body' in options,false);return respond(200,{ok:true,data:liveJournalResponse});}});
  assert.equal(liveJournalClientRead.ok,true);assert.equal(liveJournalClientRead.data.status,'NOT_ADMITTED');assert.equal(liveJournalClientRead.data.signature_verified,false);assert.equal(liveJournalClientRead.data.can_post,false);
  assert.equal((await refreshAuthoritativeWbsLivePilot({config,tool:'trace_by_key',fetcher:async()=>{throw new Error('must not call');}})).code,'WBS_LIVE_PILOT_SCOPE_INVALID');
  assert.equal((await refreshAuthoritativeWbsLivePilot({config,tool:'list_autorec_details',limit:11,fetcher:async()=>{throw new Error('must not call');}})).code,'WBS_LIVE_PILOT_SCOPE_INVALID');
  assert.equal((await refreshAuthoritativeWbsLivePilot({config,tool:'list_autorec_details',fetcher:async()=>respond(200,{ok:true,data:{...pilotEvidence('list_autorec_details'),signature_verified:true}})})).code,'WBS_LIVE_PILOT_PROTOCOL');
  assert.equal((await refreshAuthoritativeWbsLivePilot({config,tool:'list_autorec_details',fetcher:async()=>respond(200,{ok:true,data:{...pilotEvidence('list_autorec_details'),can_create_draft:true}})})).code,'WBS_LIVE_PILOT_PROTOCOL');
  assert.equal((await refreshAuthoritativeWbsLivePilot({config,tool:'list_autorec_details',fetcher:async()=>respond(200,{ok:true,data:{...pilotEvidence('list_autorec_details'),entity_id:'22222222-2222-4222-8222-222222222222'}})})).code,'WBS_LIVE_PILOT_PROTOCOL');
  assert.equal((await refreshAuthoritativeWbsLivePilot({config,tool:'list_autorec_details',fetcher:async()=>respond(200,{ok:true,data:pilotEvidence('list_autorec_details',{...pilotRows.list_autorec_details,payment_amount:'25.00000'})})})).code,'WBS_LIVE_PILOT_PROTOCOL');
  assert.equal((await refreshAuthoritativeWbsLivePilot({config,tool:'list_journal_entries',fetcher:async()=>respond(200,{ok:true,data:pilotEvidence('list_journal_entries',{...pilotRows.list_journal_entries,accounting_date:'2026-08-01T00:00:00Z'})})})).code,'WBS_LIVE_PILOT_PROTOCOL');
  const emptyPilot=await refreshAuthoritativeWbsLivePilot({config,tool:'list_payables',fetcher:async()=>respond(200,{ok:true,data:pilotEvidence('list_payables',null)})});assert.equal(emptyPilot.ok,true);assert.equal(emptyPilot.data.record_count,0);
  const retainedRow={wbs_operator_payable_attestation_id:'22222222-2222-4222-8222-222222222222',captured_at:'2026-08-12T00:00:00.000Z',company_code:'COMPANY-A',company_codes:['COMPANY-A'],company_scope_status:'ENTITY_SCOPE_MATCHED',row_count:1,provenance_mode:'OPERATOR_ATTESTED',signature_verified:false,evidence_status:'EXCEPTION_REVIEW_REQUIRED',can_create_draft:false,can_post:false,attested_at:'2026-08-12T00:01:00.000Z'};
  let retainedRequest;const retained=await refreshAuthoritativeWbsOperatorPayableAttestations({config,limit:25,fetcher:async(url,options)=>{retainedRequest={url,options};return respond(200,{ok:true,data:[retainedRow]});}});assert.equal(retained.ok,true);assert.deepEqual(retained.rows,[retainedRow]);assert.match(retainedRequest.url,/\/wbs\/operator-attested\/payables\?limit=25$/);assert.equal(retainedRequest.options.method,'GET');
  assert.equal((await refreshAuthoritativeWbsOperatorPayableAttestations({config,fetcher:async()=>respond(200,{ok:true,data:[{...retainedRow,signature_verified:true}]})})).code,'WBS_OPERATOR_ATTESTATION_PROTOCOL');

  const exceptionRow={wbs_operator_payable_attestation_id:'11111111-1111-4111-8111-111111111111',wbs_operator_payable_evidence_row_id:'22222222-2222-4222-8222-222222222222',captured_at:'2026-08-13T00:00:00Z',provider_content_hash:'sha256:'+'3'.repeat(64),observation_hash:'sha256:'+'4'.repeat(64),company_code:null,company_scope_status:'UNASSIGNED_COMPANY',source_record_id:'payable-1',source_version:'operator:v1',row_hash:'sha256:'+'5'.repeat(64),document_number:'INV-100',accounting_date:'2026-04-09',currency:'USD',observed_amount:'810.0000',provider_status:'Clear',signed_link_status:'EXCEPTION_REVIEW_REQUIRED',signed_wbs_inbound_row_id:null,next_owner:'Accounting data steward',next_action:'Assign this row to one approved WBS company, then obtain a signed provider package.',evidence_status:'EXCEPTION_REVIEW_REQUIRED',signature_verified:false,can_review:false,can_create_draft:false,can_post:false};
  let exceptionRequest;const exception=await refreshAuthoritativeWbsOperatorPayableExceptionRows({config,attestationId:exceptionRow.wbs_operator_payable_attestation_id,fetcher:async(url,options)=>{exceptionRequest={url,options};return respond(200,{ok:true,data:[exceptionRow]});}});assert.equal(exception.ok,true);assert.deepEqual(exception.rows,[exceptionRow]);assert.match(exceptionRequest.url,/\/operator-attested\/payables\/11111111-1111-4111-8111-111111111111\/rows\?limit=10$/);assert.equal(exceptionRequest.options.method,'GET');
  assert.equal((await refreshAuthoritativeWbsOperatorPayableExceptionRows({config,attestationId:exceptionRow.wbs_operator_payable_attestation_id,fetcher:async()=>respond(200,{ok:true,data:[{...exceptionRow,can_review:true}]})})).code,'WBS_OPERATOR_EXCEPTION_ROW_PROTOCOL');
  const aiFinding={ai_finding_id:'33333333-3333-4333-8333-333333333333',finding_key:'WBS_UNSIGNED_SOURCE:payable-1',source_evidence_row_id:exceptionRow.wbs_operator_payable_evidence_row_id,source_record_id:exceptionRow.source_record_id,source_version:exceptionRow.source_version,source_row_hash:exceptionRow.row_hash,provider_content_hash:exceptionRow.provider_content_hash,observation_hash:exceptionRow.observation_hash,rule_id:'WBS_UNSIGNED_SOURCE',risk_level:'HIGH',confidence:'0.9500',status:'OPEN',reason:'Provider signature is not available for this immutable exception evidence row.',suggested_action:'Obtain a later provider-signed delivery before accounting review.',suggested_owner:'CONTROLLER',due_date:null,due_date_status:'HUMAN_ASSIGNMENT_REQUIRED',created_at:'2026-08-13T00:00:00Z',can_create_draft:false,can_review:false,can_approve:false,can_post:false};
  let aiRequest;const aiFindings=await refreshAuthoritativeAiWbsExceptionFindings({config,fetcher:async(url,options)=>{aiRequest={url,options};return respond(200,{ok:true,data:[aiFinding]});}});assert.equal(aiFindings.ok,true);assert.equal(aiFindings.rows[0].confidence,0.95);assert.match(aiRequest.url,/\/ai\/findings\/wbs-exceptions\?limit=50$/);assert.equal(aiRequest.options.method,'GET');assert.equal('body' in aiRequest.options,false);assert.equal('idempotency-key' in aiRequest.options.headers,false);assert.equal((await refreshAuthoritativeAiWbsExceptionFindings({config,fetcher:async()=>respond(200,{ok:true,data:[{...aiFinding,can_post:true}]})})).code,'AI_WBS_EXCEPTION_FINDING_PROTOCOL');
  let attestRequest;const attested=await attestAuthoritativeWbsPayableObservation({config,observation:pilotEvidence('list_payables'),expectedCompanyCode:'COMPANY-A',dateFrom:'2026-08-01',dateTo:'2026-08-12',reason:'Retain exact WBS Payable data for exception review',idempotencyKey:'operator-attest-client-0001',fetcher:async(url,options)=>{attestRequest={url,options};return respond(201,{ok:true,data:{wbs_operator_payable_attestation_id:retainedRow.wbs_operator_payable_attestation_id,status:'EXCEPTION_REVIEW_REQUIRED',provenance_mode:'OPERATOR_ATTESTED',signature_verified:false,company_scope_status:'ENTITY_SCOPE_MATCHED',row_count:1,can_import_to_staging:false,can_review:false,can_create_draft:false,can_approve:false,can_post:false}});}});assert.equal(attested.ok,true);assert.match(attestRequest.url,/\/wbs\/operator-attested\/payables$/);assert.equal(attestRequest.options.method,'POST');const attestedBody=JSON.parse(attestRequest.options.body);assert.equal(attestedBody.expectedObservationHash,pilotEvidence('list_payables').observation_hash);assert.equal(attestedBody.expectedCompanyCode,'COMPANY-A');assert.equal(attestedBody.dateFrom,'2026-08-01');assert.equal(attestedBody.dateTo,'2026-08-12');assert.equal(Object.hasOwn(attestedBody,'rows'),false);
  assert.equal((await attestAuthoritativeWbsPayableObservation({config,observation:pilotEvidence('list_payables',null),reason:'Retain empty observation',idempotencyKey:'operator-attest-client-0002',fetcher:async()=>{throw new Error('must not call');}})).code,'WBS_OPERATOR_ATTESTATION_COMMAND_INVALID');
  const reviewCandidate={review_candidate_id:`sha256:${'1'.repeat(64)}`,stage:'STAGING_REVIEWED',side:'BANK_SIDE',source_type:'BANK_TRANSACTION',entity_id:entityId,company_key:'COMPANY-A',currency:'USD',amount:'-25.0000',business_date:'2026-08-01',accounting_date:'2026-08-01',bank_account_ref:'BANK-1',source_record_id:'BANK-ROW-1',source_version:'v1',raw_event_id:'raw-1',source_document_id:'source-1',staging_item_id:'staging-1',mapping:{mapping_id:'map-1',version:'1',snapshot_hash:`sha256:${'2'.repeat(64)}`},can_dispatch:false,can_allocate:false,can_release:false,can_create_draft:false,can_post:false};
  const reviewEvidence={status:'READ_ONLY_PROJECTED',request_hash:`sha256:${'3'.repeat(64)}`,replayed:false,candidates:[reviewCandidate],exceptions:[],controls:{candidate_count:1,can_dispatch:false,can_post:false},review_plans:[],observed_state_evidence:[],can_dispatch:false,can_create_draft:false,can_post:false};
  let reviewRequest;const reviewRead=await refreshAuthoritativeWbsAutoRecReview({config,companyKey:' COMPANY-A ',sourceRecordIds:['BANK-ROW-1','BANK-ROW-1'],fetcher:async(url,options)=>{reviewRequest={url,options};return respond(200,{ok:true,data:reviewEvidence});}});
  assert.equal(reviewRead.ok,true);assert.match(reviewRequest.url,/\/wbs\/auto-reconciliation\/review-candidates\?/);assert.match(reviewRequest.url,/companyKey=COMPANY-A/);assert.equal((reviewRequest.url.match(/sourceRecordId=BANK-ROW-1/g)||[]).length,1);assert.equal(reviewRequest.options.method,'GET');assert.equal('body' in reviewRequest.options,false);assert.equal('idempotency-key' in reviewRequest.options.headers,false);
  assert.equal((await refreshAuthoritativeWbsAutoRecReview({config,companyKey:'COMPANY-A',sourceRecordIds:[],fetcher:async()=>{throw new Error('must not call');}})).code,'WBS_AUTOREC_SCOPE_INVALID');
  assert.equal((await refreshAuthoritativeWbsAutoRecReview({config,companyKey:'COMPANY-A',sourceRecordIds:['BANK-ROW-1'],fetcher:async()=>respond(200,{ok:true,data:{...reviewEvidence,candidates:[{...reviewCandidate,entity_id:'22222222-2222-4222-8222-222222222222'}]}})})).code,'WBS_AUTOREC_REVIEW_PROTOCOL');
  assert.equal((await refreshAuthoritativeWbsAutoRecReview({config,companyKey:'COMPANY-A',sourceRecordIds:['OTHER-ROW'],fetcher:async()=>respond(200,{ok:true,data:reviewEvidence})})).code,'WBS_AUTOREC_REVIEW_PROTOCOL');
  assert.equal((await refreshAuthoritativeWbsAutoRecReview({config,companyKey:'COMPANY-A',sourceRecordIds:['BANK-ROW-1'],fetcher:async()=>respond(200,{ok:true,data:{...reviewEvidence,candidates:[{...reviewCandidate,can_dispatch:true}]}})})).code,'WBS_AUTOREC_REVIEW_PROTOCOL');
  assert.equal((await refreshAuthoritativeWbsAutoRecReview({config,companyKey:'COMPANY-A',sourceRecordIds:['BANK-ROW-1'],fetcher:async()=>respond(200,{ok:true,data:{...reviewEvidence,candidates:[{...reviewCandidate,can_match:true}]}})})).code,'WBS_AUTOREC_REVIEW_PROTOCOL');
  assert.equal((await refreshAuthoritativeWbsAutoRecReview({config,companyKey:'COMPANY-A',sourceRecordIds:['BANK-ROW-1'],fetcher:async()=>respond(200,{ok:true,data:{...reviewEvidence,candidates:[{...reviewCandidate,amount:-25}]}})})).code,'WBS_AUTOREC_REVIEW_PROTOCOL');

  const controlScope={tenant_id:'aaaaaaaa-aaaa-4aaa-8aaa-aaaaaaaaaaaa',entity_id:entityId,company_key:'COMPANY-A',period:'2026-08',currency:'USD'};
  const controlComparison={metric_key:'COST_METRIC_01',source_amount:'25.0000',target_amount:'25.0000',difference:'0.0000',matched:true,forward_trace:{},reverse_trace:{}};
  const controlEvidence={status:'READ_ONLY_CONTROL_RECONCILED',request_hash:`sha256:${'4'.repeat(64)}`,replayed:false,reconciliation:{source_type:'COST_GENERAL_LEDGER',status:'RECONCILED',scope:controlScope,comparisons:[controlComparison],control_totals:{metric_count:1,difference_count:0,source_total:'25.0000',target_total:'25.0000',difference_total:'0.0000'},can_create_transaction:false,can_allocate:false,can_create_draft:false,can_post:false},trace:{forward_trace:{},reverse_trace:{}},can_create_transaction:false,can_allocate:false,can_create_draft:false,can_post:false};
  let controlRequest;const controlRead=await refreshAuthoritativeWbsControlReconciliation({config,sourceType:'COST_GENERAL_LEDGER',companyKey:'COMPANY-A',period:'2026-08',currency:'usd',fetcher:async(url,options)=>{controlRequest={url,options};return respond(200,{ok:true,data:controlEvidence});}});
  assert.equal(controlRead.ok,true);assert.match(controlRequest.url,/\/wbs\/control-reconciliation\?/);assert.match(controlRequest.url,/sourceType=COST_GENERAL_LEDGER/);assert.match(controlRequest.url,/period=2026-08/);assert.match(controlRequest.url,/currency=USD/);assert.equal(controlRequest.options.method,'GET');assert.equal('body' in controlRequest.options,false);
  assert.equal((await refreshAuthoritativeWbsControlReconciliation({config,sourceType:'COST_GENERAL_LEDGER',companyKey:'COMPANY-A',period:'2026-13',currency:'USD',fetcher:async()=>{throw new Error('must not call');}})).code,'WBS_CONTROL_SCOPE_INVALID');
  assert.equal((await refreshAuthoritativeWbsControlReconciliation({config,sourceType:'COST_GENERAL_LEDGER',companyKey:'COMPANY-A',period:'2026-08',currency:'USD',fetcher:async()=>respond(200,{ok:true,data:{...controlEvidence,reconciliation:{...controlEvidence.reconciliation,can_post:true}}})})).code,'WBS_CONTROL_RECONCILIATION_PROTOCOL');
  assert.equal((await refreshAuthoritativeWbsControlReconciliation({config,sourceType:'COST_GENERAL_LEDGER',companyKey:'COMPANY-A',period:'2026-08',currency:'USD',fetcher:async()=>respond(200,{ok:true,data:{...controlEvidence,reconciliation:{...controlEvidence.reconciliation,comparisons:[{...controlComparison,source_amount:25}]}}})})).code,'WBS_CONTROL_RECONCILIATION_PROTOCOL');
  const propertyScope={...controlScope,property_ref:'PROPERTY-A',period_start:'2026-08-01',period_end:'2026-08-31',bank_account_ref:'BANK-1'};delete propertyScope.period;
  const propertyControl={...controlEvidence,reconciliation:{...controlEvidence.reconciliation,source_type:'PROPERTY_COMPARISON',scope:propertyScope}};
  assert.equal((await refreshAuthoritativeWbsControlReconciliation({config,sourceType:'PROPERTY_COMPARISON',companyKey:'COMPANY-A',propertyRef:'PROPERTY-A',periodStart:'2026-08-01',periodEnd:'2026-08-31',currency:'USD',bankAccountRef:'BANK-1',fetcher:async()=>respond(200,{ok:true,data:propertyControl})})).ok,true);
  let transitionRequest;const transition=await verifyAuthoritativeWbsTransitionContract({config,contract:{provider:'signed-contract'},fetcher:async(url,options)=>{transitionRequest={url,options};return respond(200,{ok:true,data:transitionEvidence});}});
  assert.equal(transition.ok,true);assert.match(transitionRequest.url,/\/wbs\/auto-reconciliation\/transition-contracts\/verify$/);assert.equal(transitionRequest.options.method,'POST');assert.equal(transitionRequest.options.cache,'no-store');assert.equal(transitionRequest.options.headers.authorization,`Bearer ${accessToken}`);assert.equal('idempotency-key' in transitionRequest.options.headers,false);assert.equal('if-match' in transitionRequest.options.headers,false);assert.deepEqual(JSON.parse(transitionRequest.options.body),{contract:{provider:'signed-contract'}});
  assert.equal((await verifyAuthoritativeWbsTransitionContract({config,contract:{provider:'signed-contract'},fetcher:async()=>respond(200,{ok:true,data:{...transitionEvidence,can_post:true}})})).code,'WBS_TRANSITION_CONTRACT_PROTOCOL');

  const postedJournalId='22222222-2222-4222-8222-222222222222';
  const exactJournalDetail={entity_id:entityId,period_id:periodId,journal_entry_id:postedJournalId,journal_number:'JE-DETAIL-1',journal_type:'MANUAL',status:'POSTED',journal_date:'2026-08-01',currency:'USD',description:'Exact detail',revision:'4',created_at:'2026-08-01T00:00:00.000Z',posted_at:'2026-08-01T01:00:00.000Z',lines:[{line_no:1,journal_line_id:'44444444-4444-4444-8444-444444444444',ledger_line_id:'55555555-5555-4555-8555-555555555555',account_code:'111000',debit_amount:'25.0000',credit_amount:'0.0000',member_ref:'BANK-1',description:'Cash',dimensions:{property:'P-1'},source_document_ids:['66666666-6666-4666-8666-666666666666']},{line_no:2,journal_line_id:'77777777-7777-4777-8777-777777777777',ledger_line_id:'88888888-8888-4888-8888-888888888888',account_code:'291001',debit_amount:'0.0000',credit_amount:'25.0000',member_ref:null,description:null,dimensions:{},source_document_ids:[]}]};
  let journalDetailRequest;const journalDetail=await readAuthoritativeJournalEntryDetail({config,journalEntryId:postedJournalId,fetcher:async(url,options)=>{journalDetailRequest={url,options};return respond(200,{ok:true,data:exactJournalDetail});}});
  assert.equal(journalDetail.ok,true);assert.equal(journalDetail.journal.revision,4);assert.match(journalDetailRequest.url,new RegExp(`/journal-entries/${postedJournalId}\\?periodId=${periodId}$`));assert.equal(journalDetailRequest.options.method,'GET');assert.equal('body' in journalDetailRequest.options,false);
  assert.equal((await readAuthoritativeJournalEntryDetail({config,journalEntryId:postedJournalId,fetcher:async()=>respond(200,{ok:true,data:{...exactJournalDetail,period_id:'99999999-9999-4999-8999-999999999999'}})})).code,'ACCOUNTING_API_PROTOCOL');
  assert.equal((await readAuthoritativeJournalEntryDetail({config,journalEntryId:postedJournalId,fetcher:async()=>respond(200,{ok:true,data:{...exactJournalDetail,lines:[{...exactJournalDetail.lines[0],ledger_line_id:null}]}})})).code,'ACCOUNTING_API_PROTOCOL');
  const draft={...exactJournalDetail,status:'DRAFT',posted_at:null,lines:exactJournalDetail.lines.map(line=>({...line,ledger_line_id:null}))};
  assert.equal((await readAuthoritativeJournalEntryDetail({config,journalEntryId:postedJournalId,fetcher:async()=>respond(200,{ok:true,data:draft})})).ok,true);
  assert.equal((await readAuthoritativeJournalEntryDetail({config,journalEntryId:postedJournalId,fetcher:async()=>respond(200,{ok:true,data:{...draft,lines:[{...draft.lines[0],ledger_line_id:exactJournalDetail.lines[0].ledger_line_id}]}})})).code,'ACCOUNTING_API_PROTOCOL');

  console.log('accounting-api-client: all assertions passed');
})().catch(error=>{console.error(error);process.exitCode=1;});
