import React from 'react';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {renderToStaticMarkup} from 'react-dom/server';
import {AuthoritativeAdmittedStatements,AuthoritativeBankDetail,AuthoritativeBankTable,AuthoritativeBankWorkspace,AuthoritativeReconciliationDetail,AuthoritativeReconciliationSummary,AuthoritativeReconciliationWorkspace} from '../src/authoritative-bank-workspace.jsx';
import {routeRequiresSharedAccountingBootstrap} from '../src/authoritative-app.jsx';

const config={entityId:'11111111-1111-4111-8111-111111111111'};
const displayConfig={...config,scopePresentation:{entityLabel:'Wan Pacific Real Estate Development LLC'}};
assert.equal(routeRequiresSharedAccountingBootstrap('reconciliation'),false,'a direct Reconciliation reload must mount its scoped reader without waiting for unrelated AP/AR or Journal requests');
assert.equal(routeRequiresSharedAccountingBootstrap('bank'),false);
assert.equal(routeRequiresSharedAccountingBootstrap('overview'),true);
assert.equal(routeRequiresSharedAccountingBootstrap('payables'),true);
const bankRow={bank_source_id:'11111111-1111-4111-8111-111111111111',bank_account_ref:'BANK-1',external_bank_line_id:'BANK-LINE-1',transaction_date:'2026-07-15',currency:'USD',amount:'-125.2500',version:3,source_ref:'SOURCE-1',document_type:'BANK_TRANSACTION',match_status:null,journal_entry_id:null};
const activeMatchRow={...bankRow,bank_match_id:'22222222-2222-4222-8222-222222222222',match_status:'ACTIVE',business_source_document_id:'33333333-3333-4333-8333-333333333333',journal_entry_id:'44444444-4444-4444-8444-444444444444',journal_line_id:'55555555-5555-4555-8555-555555555555',candidate_rule_code:'EXACT_POSTED_CASH',amount_delta:'0.0000',currency_match:true,date_delta_days:0,match_version:4,matched_by:'controller@example.test',matched_at:'2026-07-16T10:00:00.000Z'};
const historicalMatchRow={...activeMatchRow,match_status:'REVERSED'};
const reconciliationRow={reconciliation_id:'11111111-1111-4111-8111-111111111111',bank_account_ref:'BANK-1',statement_ending_date:'2026-07-31',statement_ending_balance:'1000.0000',difference:'0.0000',status:'RECONCILED',version:4,bank_transaction_count:6,active_match_count:5,unmatched_transaction_count:1,statement_activity_amount:'250.0000'};

const bankInitial=renderToStaticMarkup(<AuthoritativeBankWorkspace config={config} fetcher={async()=>{throw new Error('SSR must not fetch');}}/>);
assert.match(bankInitial,/Bank transaction evidence/);assert.match(bankInitial,/Bank account/);assert.match(bankInitial,/From/);assert.match(bankInitial,/Through/);assert.match(bankInitial,/Choose one bank account/);assert.doesNotMatch(bankInitial,/localStorage|seed row/i);
const namedBankInitial=renderToStaticMarkup(<AuthoritativeBankWorkspace config={displayConfig} fetcher={async()=>{throw new Error('SSR must not fetch');}}/>);
assert.match(namedBankInitial,/Wan Pacific Real Estate Development LLC/);assert.doesNotMatch(namedBankInitial,/Entity 11111111-1111-4111-8111-111111111111/);

const reconciliationInitial=renderToStaticMarkup(<AuthoritativeReconciliationWorkspace config={config} fetcher={async()=>{throw new Error('SSR must not fetch');}}/>);
assert.match(reconciliationInitial,/Reconciliation evidence/);assert.match(reconciliationInitial,/Statement ending date/);assert.match(reconciliationInitial,/Review one retained statement/);
assert.match(reconciliationInitial,/Selecting a retained statement fills the account and cutoff\. No lifecycle action runs\./);assert.doesNotMatch(reconciliationInitial,/The API rejects missing or cross-scope statement evidence/);
assert.match(reconciliationInitial,/Available reconciliation scopes/);assert.match(reconciliationInitial,/Discovering reconciliation scopes/);assert.match(reconciliationInitial,/READ ONLY/);
assert.match(reconciliationInitial,/Signed admitted statements/);assert.match(reconciliationInitial,/SIGNED \+ ADMITTED/);assert.match(reconciliationInitial,/separate from UNSIGNED PILOT/);assert.match(reconciliationInitial,/Load signed statements/);
const admittedInitial=renderToStaticMarkup(<AuthoritativeAdmittedStatements config={config} bankAccountRef="BANK-1" fetcher={async()=>{throw new Error('SSR must not fetch');}}/>);
assert.match(admittedInitial,/Signed statement read not requested/);assert.match(admittedInitial,/Bank account BANK-1/);assert.match(admittedInitial,/SERVER REVALIDATED/);assert.doesNotMatch(admittedInitial,/Start Draft from signed statement/);

const bankTable=renderToStaticMarkup(<AuthoritativeBankTable rows={[bankRow]}/>);
assert.match(bankTable,/BANK-LINE-1/);assert.match(bankTable,/SOURCE-1/);assert.match(bankTable,/UNMATCHED/);assert.match(bankTable,/READ ONLY/);assert.match(bankTable,/Open detail/);assert.doesNotMatch(bankTable,/>\s*(Match|Clear|Post|Delete|Create)\s*</);
assert.match(bankTable,/SOURCE → MATCH → JOURNAL/);assert.match(bankTable,/Queue status never implies reconciliation/);assert.match(bankTable,/Direction/);assert.match(bankTable,/OUTFLOW/);assert.match(bankTable,/v3/);
assert.match(bankTable,/Bank queue read summary/);assert.match(bankTable,/Returned sources/);assert.match(bankTable,/Active Matches/);assert.match(bankTable,/Unmatched sources/);assert.match(bankTable,/Journal references/);assert.doesNotMatch(bankTable,/Create reviewed Match|Unmatch evidence/);
assert.equal((bankTable.match(/class="qbo-card"/g)||[]).length,4,'Bank summary must use the shared demonstration card presentation');
const emptyBank=renderToStaticMarkup(<AuthoritativeBankTable rows={[]} readAt="2026-08-14T10:00:00.000Z"/>);assert.match(emptyBank,/SCOPE_EMPTY/);assert.match(emptyBank,/0 bank transactions/);assert.match(emptyBank,/not TRUE_EMPTY/);assert.match(emptyBank,/API records returned: 0/);assert.match(emptyBank,/Source freshness: not supplied by this endpoint/);assert.doesNotMatch(emptyBank,/<table/);

const bankDetail=renderToStaticMarkup(<AuthoritativeBankDetail row={bankRow} scope={{entityId:config.entityId,bankAccountRef:'BANK-1',from:'2026-07-01',through:'2026-07-31'}} onBack={()=>{}}/>);
assert.match(bankDetail,/Back to bank transactions/);assert.match(bankDetail,/Bank transaction detail/);assert.match(bankDetail,/-\$125\.25/);assert.match(bankDetail,/2026-07-01/);assert.match(bankDetail,/2026-07-31/);
assert.match(bankDetail,/full-bleed qbo-transaction-report/);
assert.match(bankDetail,/AUTHORITATIVE SOURCE EVIDENCE/);assert.match(bankDetail,/Bank evidence lifecycle/);assert.match(bankDetail,/Reconciliation separate/);assert.match(bankDetail,/Authoritative evidence scope/);
assert.match(bankDetail,/Match review/);assert.match(bankDetail,/Journal reference unavailable/);
assert.match(bankDetail,/Direction/);assert.match(bankDetail,/OUTFLOW/);
const mismatchedBankDetail=renderToStaticMarkup(<AuthoritativeBankDetail row={bankRow} scope={{entityId:config.entityId,bankAccountRef:'BANK-OTHER',from:'2026-07-01',through:'2026-07-31'}} onBack={()=>{}} config={config} fetcher={async()=>{throw new Error('SSR must not fetch');}}/>);
assert.match(mismatchedBankDetail,/BLOCKED — immutable bank scope mismatch/);assert.match(mismatchedBankDetail,/Back to bank transactions/);
assert.doesNotMatch(mismatchedBankDetail,/Bank match candidate review|Active Match correction|Load exact candidate|Create reviewed Match|Unmatch evidence/);
const activeMatchDetail=renderToStaticMarkup(<AuthoritativeBankDetail row={activeMatchRow} scope={{entityId:config.entityId,bankAccountRef:'BANK-1',from:'2026-07-01',through:'2026-07-31'}} onBack={()=>{}}/>);
assert.match(activeMatchDetail,/Business source document/);assert.match(activeMatchDetail,/Journal entry/);assert.match(activeMatchDetail,/Journal line/);assert.match(activeMatchDetail,/Ledger line/);assert.match(activeMatchDetail,/Unavailable from the active-Match read/);assert.match(activeMatchDetail,/Matched by/);assert.match(activeMatchDetail,/Matched at/);assert.match(activeMatchDetail,/Match version/);assert.match(activeMatchDetail,/Active Match retained/);assert.match(activeMatchDetail,/Journal reference retained/);
const historicalMatchDetail=renderToStaticMarkup(<AuthoritativeBankDetail row={historicalMatchRow} scope={{entityId:config.entityId,bankAccountRef:'BANK-1',from:'2026-07-01',through:'2026-07-31'}} onBack={()=>{}} config={config} fetcher={async()=>{throw new Error('SSR must not fetch');}}/>);
assert.match(historicalMatchDetail,/Match correction blocked/);assert.match(historicalMatchDetail,/not ACTIVE/);assert.match(historicalMatchDetail,/READ ONLY HISTORY/);assert.doesNotMatch(historicalMatchDetail,/Unmatch evidence/);

const reconciliation=renderToStaticMarkup(<AuthoritativeReconciliationSummary row={reconciliationRow} scope={{entityId:config.entityId,bankAccountRef:'BANK-1',statementEndingDate:'2026-07-31'}}/>);
assert.match(reconciliation,/RECONCILED/);assert.match(reconciliation,/\$1,000\.00/);assert.match(reconciliation,/Unmatched/);assert.match(reconciliation,/READ ONLY/);assert.match(reconciliation,/Open statement detail/);
assert.match(reconciliation,/STATEMENT → REVIEW → SIGN-OFF/);assert.match(reconciliation,/Reconciliation lifecycle/);assert.match(reconciliation,/Immutable history/);assert.match(reconciliation,/Independent sign-off retained/);assert.match(reconciliation,/Immutable history retained/);
assert.match(reconciliation,/Authoritative evidence scope/);assert.match(reconciliation,/Bank account/);assert.match(reconciliation,/Statement cutoff/);assert.match(reconciliation,/2026-07-31/);assert.match(reconciliation,/v4/);
const emptyReconciliation=renderToStaticMarkup(<AuthoritativeReconciliationSummary row={null}/>);assert.match(emptyReconciliation,/Reconciliation evidence blocked/);assert.match(emptyReconciliation,/BLOCKED — The accounting API returned no authorized reconciliation statement/);assert.match(emptyReconciliation,/not evidence of zero statement activity/);assert.doesNotMatch(emptyReconciliation,/Open statement detail|Start DRAFT|Connect now|Get started/);

const reconciliationDetail=renderToStaticMarkup(<AuthoritativeReconciliationDetail row={reconciliationRow} scope={{entityId:config.entityId,bankAccountRef:'BANK-1',statementEndingDate:'2026-07-31'}} onBack={()=>{}}/>);
assert.match(reconciliationDetail,/Back to reconciliation evidence/);assert.match(reconciliationDetail,/Statement ending 2026-07-31/);assert.match(reconciliationDetail,/\$1,000\.00/);assert.match(reconciliationDetail,/Configured entity/);
assert.match(reconciliationDetail,/Commands require server-returned evidence and separate authorization/);assert.doesNotMatch(reconciliationDetail,/Scope: Configured entity|independent workflow approval and posting remain outside this screen/);
assert.match(reconciliationDetail,/full-bleed qbo-transaction-report/);assert.match(reconciliationDetail,/Reconciled by/);
assert.match(reconciliationDetail,/Load reconciliation worksheet/);assert.match(reconciliationDetail,/CONTROLLER REVIEW/);
assert.match(reconciliationDetail,/AUTHORITATIVE STATEMENT WORKSHEET/);assert.match(reconciliationDetail,/Reconciliation lifecycle/);assert.match(reconciliationDetail,/Authoritative evidence scope/);
const mismatchedReconciliationDetail=renderToStaticMarkup(<AuthoritativeReconciliationDetail row={reconciliationRow} scope={{entityId:config.entityId,bankAccountRef:'BANK-OTHER',statementEndingDate:'2026-07-30'}} onBack={()=>{}} config={config} fetcher={async()=>{throw new Error('SSR must not fetch');}}/>);
assert.match(mismatchedReconciliationDetail,/BLOCKED — immutable reconciliation scope mismatch/);assert.match(mismatchedReconciliationDetail,/Back to reconciliation evidence/);
assert.doesNotMatch(mismatchedReconciliationDetail,/Load reconciliation worksheet|Prepare adjustment Draft|Create adjustment Draft|Clear matched item|Send to independent review|Sign off reviewed statement|Reopen signed statement/);

const source=readFileSync('src/authoritative-bank-workspace.jsx','utf8');
// Phase 2a: the four states are rendered only by the shared StateBlock, which
// is what carries role="status" / aria-busy. Assert both halves of that contract.
assert.match(source,/phase==='LOADING'.*<StateBlock tone="loading"/s,'authoritative reads must expose a loading state through StateBlock');
assert.match(readFileSync('src/ui.jsx','utf8'),/role=\{tone==='error' \? 'alert' : 'status'\}[\s\S]*aria-busy=\{tone==='loading' \? 'true' : undefined\}/,'StateBlock must announce loading as a busy status region');
assert.match(source,/phase==='ERROR'.*<ReadError/s,'authoritative reads must expose an API error with retry');
assert.match(source,/phase==='READY'.*AuthoritativeBankTable/s,'Bank results must render only after an API success');
assert.match(source,/phase==='READY'.*AuthoritativeReconciliationSummary/s,'Reconciliation results must render only after an API success');
assert.match(source,/if\(selected\).*AuthoritativeBankDetail/s,'Bank detail must replace the list and retain an explicit Back path');
assert.match(source,/if\(selected\).*AuthoritativeReconciliationDetail/s,'Reconciliation detail must replace the summary and retain an explicit Back path');
assert.match(source,/authoritative-bank-\$\{row\.bank_source_id\}/,'Bank detail must retain a stable opener for focus restoration');
assert.match(source,/authoritative-reconciliation-\$\{row\.reconciliation_id\}/,'Reconciliation detail must retain a stable opener for focus restoration');
assert.match(source,/className="table-wrap" role="region" tabIndex=\{0\} aria-label="Bank transactions; scroll horizontally to view every column"/,'Bank evidence table must be keyboard-focusable and named when it overflows at narrow widths');
assert.match(source,/className="table-wrap" role="region" tabIndex=\{0\} aria-label="Reconciliation worksheet; scroll horizontally to view every column"/,'Reconciliation worksheet table must be keyboard-focusable and named when it overflows at narrow widths');
assert.match(source,/restoreAuthoritativeReturnContext\(environment,config,context\)/,'Bank and reconciliation Back must restore scope, scroll position and focus');
assert.match(source,/bankAccountRef:scope\.bankAccountRef/,'Bank Back must retain the exact account scope');
assert.match(source,/getElementById\?\.\(focusId\)\?\.closest\?\.\('\.table-wrap'\)\?\.scrollLeft/,'Bank detail must freeze the originating contained table position');
assert.match(source,/view:\{\.\.\.DEFAULT_AUTHORITATIVE_LIST_VIEW,from:scope\.from,through:scope\.through,offset:state\.offset\},focusId,scrollY:Number\(environment\?\.scrollY\)\|\|0,tableX/,'Bank detail return context must retain table position with account, dates and page offset');
assert.match(source,/getTable:\(\)=>environment\?\.document\?\.getElementById\?\.\(context\?\.focusId\)\?\.closest\?\.\('\.table-wrap'\)/,'Bank Back must locate the remounted table from the frozen opener ID');
assert.match(source,/view:\{\.\.\.DEFAULT_AUTHORITATIVE_LIST_VIEW,from:scope\.from,through:scope\.through,offset:state\.offset\}/,'Bank detail return context must retain the exact authoritative page offset');
assert.match(source,/Number\.isSafeInteger\(context\?\.view\?\.offset\).*offset:context\.view\.offset/s,'Bank Back must restore the exact validated page offset');
assert.match(source,/offset:Math\.max\(0,state\.offset-100\)/,'Bank Previous page must retain the scoped authoritative pagination contract');
assert.match(source,/offset:state\.offset\+100/,'Bank Next page must retain the scoped authoritative pagination contract');
assert.match(source,/onMatchChanged=\{\(\)=>load\(null,\{preserveDetail:true,offset:state\.offset\}\)\}/,'A successful Match refresh must retain the current authoritative page instead of silently returning to page zero');
assert.match(source,/const bankRowMatchesScope=/,'Bank detail must reject a row outside the immutable parent account scope');
assert.match(source,/scopeMatches&&config&&<AuthoritativeBankMatchReview/,'Bank match controls require a matching immutable account scope');
assert.match(source,/BLOCKED — immutable bank scope mismatch/,'Bank scope mismatches must remain evidence-only');
assert.match(source,/load\(null,\{preserveDetail:true\}\)/,'A successful bank command must re-read the current scoped source and retain the full-page detail');
assert.match(source,/const refreshed=result\.rows\.find\(row=>row\.bank_source_id===current\.row\.bank_source_id\)/,'A refreshed Bank detail must use the same immutable source identity, never a positional row');
assert.match(source,/statementEndingDate:scope\.statementEndingDate/,'Reconciliation Back must retain the exact cutoff scope');
assert.match(source,/const reconciliationRowMatchesScope=/,'Reconciliation detail must bind account and statement cutoff to its parent scope');
assert.match(source,/scopeMatches&&worksheet\.phase==='IDLE'/,'A mismatched reconciliation cannot fetch worksheet evidence');
assert.match(source,/scopeMatches&&hasAuthorizedWorksheetEvidence&&<section className="card" aria-label="Reconciliation lifecycle command"/,'Lifecycle controls require matching immutable scope and server worksheet evidence');
assert.match(source,/BLOCKED — immutable reconciliation scope mismatch/,'Reconciliation scope mismatches must remain evidence-only');
assert.match(source,/AuthoritativeReconciliationSummary row=\{state\.row\} scope=\{\{\.\.\.scope,entityId:config\.entityId,entityLabel:entityLabel\(config\)\}\}/,'Reconciliation summary must retain its exact entity and statement scope after a successful authoritative read');
assert.doesNotMatch(source,/localStorage|SEED_|bankRecord|bankSignoff/,'authoritative Bank/Reconcile UI must not depend on demo state or legacy mutation helpers');
assert.match(source,/refreshAuthoritativeBankMatchCandidates/,'Bank Match must start from server-validated candidate evidence, not a caller-supplied occurrence ID');
assert.match(source,/aria-label="Exact posted candidate evidence"/,'The candidate card must identify its server-returned evidence boundary');
for(const label of ['Business source document','Occurrence revision','Journal entry','Journal line','Ledger line','Date delta days'])assert.match(source,new RegExp(`<i>${label}</i>`),`Exact candidate evidence must expose ${label} from the authoritative reader`);
assert.match(source,/candidates\.length!==1/,'zero or multiple candidate sets must block the Match command');
assert.match(source,/createAuthoritativeBankPaymentMatch/,'an exact candidate must execute through the authoritative command client');
assert.match(source,/unmatchAuthoritativeBankPayment/,'an active match must use the authoritative Unmatch command client');
assert.match(source,/row\.bank_match_id&&row\.match_status!=='ACTIVE'/,'a historical non-ACTIVE Match must not imply an Unmatch command is available');
assert.match(source,/Match correction blocked/,'historical Match evidence must be explicit BLOCKED/read-only history');
assert.match(source,/refreshAuthoritativeReconciliationWorksheet/,'Reconciliation must load server-owned worksheet evidence before a clearance command');
assert.match(source,/refreshAuthoritativeAdmittedBankStatements/,'Signed statement selection must start from the closed authenticated list reader');
assert.match(source,/readAuthoritativeAdmittedBankStatement\(\{config,statementReceiptId:row\.wbs_bank_statement_receipt_id,bankAccountRef:account,fetcher\}\)/,'Selecting a signed receipt must re-read its exact UUID and retained account before exposing a command');
assert.match(source,/\['wbs_bank_statement_receipt_id','bank_account_ref','statement_start_date','statement_end_date','currency','opening_balance','ending_balance','transaction_count','statement_activity_amount','admission_hash','signature_verified','admission_status','admitted_at','reconciliation_id','reconciliation_status','reconciliation_version','selection_state'\]\.every/,'The re-read detail must retain the complete closed list identity and state before exposing a command');
assert.match(source,/row\?\.signature_verified===true&&row\?\.admission_status==='ADMITTED'&&row\?\.selection_state==='AVAILABLE_FOR_SERVER_VALIDATION'/,'Start Draft must require fresh signed, admitted, available detail evidence');
assert.match(source,/startAuthoritativeReconciliationFromAdmittedStatement\(\{config,statement:row,reason,fetcher\}\)/,'The UI must use the receipt-only server-derived start command client');
assert.match(source,/const nextScope=\{bankAccountRef:row\.bank_account_ref,statementEndingDate:row\.statement_end_date\}/,'Successful start must switch to the exact server receipt scope');
assert.match(source,/await readSummary\(nextScope,false\)/,'Successful start must re-read the authoritative reconciliation summary');
assert.match(source,/aria-label="Signed admitted statements; scroll horizontally to view every column"/,'Signed statement rows must remain in a named keyboard-focusable contained table');
assert.match(source,/This is separate from UNSIGNED PILOT observations/,'Signed admitted evidence must remain visually and semantically separate from pilot observations');
assert.doesNotMatch(source,/statementOpeningBalance|statementEndingBalance/,'The signed statement UI must never submit client-provided balances');
assert.match(source,/setAuthoritativeReconciliationClearance/,'Clear and Unclear must use the authoritative command client');
assert.doesNotMatch(source,/Start DRAFT reconciliation|Start controlled reconciliation/,'A missing scoped statement must fail closed instead of presenting a false Start Draft affordance');
assert.match(source,/transitionAuthoritativeReconciliation/,'Review, sign-off, and reopen must use the authoritative lifecycle command client');
assert.match(source,/REOPENED:\{action:'REVIEW',label:'Send reopened statement to independent review'\}/,'A reopened reconciliation must be able to re-enter the existing independent review command');
assert.match(source,/refreshAuthoritativeReconciliationScopes/,'Reconciliation account and cutoff selection must come from an authoritative discovery read');
assert.match(source,/aria-label="Existing reconciliation statement"/,'Discovered reconciliation scopes must be selectable without freehand account and cutoff entry');
assert.match(source,/item\.match_status==='ACTIVE'/,'Only a server-returned active Match may expose Clear');
assert.match(source,/row:item/,'Clearance command must receive the selected server worksheet row, not the reconciliation summary');
assert.match(source,/const reasonReady=reason\.trim\(\)\.length>=8/,'Clearance commands must require a non-blank controller reason before they can be clicked');
assert.match(source,/disabled=\{commandInFlight\|\|!reasonReady\}/,'Clearance and lifecycle buttons must remain disabled until the controller reason is valid');
assert.match(source,/createAuthoritativeReconciliationAdjustmentDraft/,'An adjustment Draft must use the authoritative reconciliation command client');
assert.match(source,/Prepare adjustment Draft/,'Only a selected server worksheet source may initiate an adjustment Draft');
assert.match(source,/Posted adjustment clearance is BLOCKED until the API returns separate posted adjustment evidence/,'The ordinary worksheet row must keep adjustment clearance blocked until separate verified evidence exists');
assert.match(source,/setAuthoritativeReconciliationAdjustmentClearance/,'The UI must use the separate authoritative adjustment-clearance command only after the evidence contract is present');
assert.match(source,/hasPostedAdjustmentEvidence/,'Posted adjustment controls must require server-verified Posted JE evidence instead of inferring it from a bank row');
assert.match(source,/Posted adjustment clearance evidence/,'Verified adjustment evidence must be rendered separately from ordinary Match clearance');
assert.match(source,/Clear posted adjustment/,'A verified Posted adjustment must have an explicit controller clearance action');
assert.match(source,/item\.clearance_state==='CLEARED'&&item\.match_status==='ACTIVE'/,'Only an active server-returned Match can expose the ordinary Unclear command');
assert.match(source,/configured cash account, exact four-decimal source amount/,'The UI must explain that it retains source amount and configured cash-account evidence instead of inferring a mapping');
assert.match(source,/preserveDetail:true/,'A successful worksheet command must refresh the authoritative statement revision without losing the full-page detail context');
assert.match(source,/Reconciliation evidence blocked/,'A missing statement must report an explicit evidence BLOCKED state');
assert.match(source,/tone="blocked"/,'Unavailable reconciliation statements and worksheets must use the distinct warning BLOCKED state');
assert.match(source,/hasAuthorizedWorksheetEvidence/,'Controller controls must be gated on exact server-returned worksheet evidence');
assert.match(source,/Reconciliation controls blocked/,'An empty authoritative worksheet must explicitly block controller actions');
assert.match(source,/hasAuthorizedWorksheetEvidence&&<section className="card" aria-label="Reconciliation lifecycle command"/,'Review, sign-off, and reopen controls must not render without authorized worksheet evidence');
assert.doesNotMatch(source,/legacy-demo-app|module-banktx|module-bankrec/,'authoritative Bank/Reconcile hierarchy must not import legacy demo UI modules');
assert.match(source,/NO_PERMISSION — authoritative read denied/,'Bank/Reconcile must distinguish an authorization failure from an empty response');
assert.match(source,/SCOPE_EMPTY — configured scope unavailable/,'Bank/Reconcile must distinguish an unavailable scope from a zero balance');
assert.match(source,/API_ERROR — authoritative read failed/,'Bank/Reconcile must distinguish a service failure from an empty response');
assert.match(source,/INGESTION_BLOCKED — no signed admitted statements returned/,'Missing signed bank admission must be explicit rather than a generic zero');
assert.match(source,/Source freshness: not supplied by this endpoint/,'The UI must not invent source freshness when the API returns none');
assert.match(source,/Last authoritative API read/,'Bank/Reconcile must expose the latest successful API read time');
// Keep the authoritative Bank/Reconcile surface English-readable. These are
// deliberate punctuation characters, not mojibake; the source must never gain
// a replacement glyph or CJK/mis-decoded text in a visible label.
for(const label of ['SOURCE → MATCH → JOURNAL','STATEMENT → REVIEW → SIGN-OFF','BLOCKED — The accounting API returned no authorized reconciliation statement','BLOCKED — The accounting API returned no authorized worksheet evidence','Selected bank source'])assert.match(source,new RegExp(label.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')),`authoritative Bank/Reconcile UI must retain readable ${label}`);
assert.match(source,/\{adjustment\.item\.external_bank_line_id\} · \{money\(adjustment\.item\.amount\)\}/,'Adjustment evidence must use the canonical middle-dot separator');
assert.doesNotMatch(source,/[\u4E00-\u9FFF\uFFFD]/,'authoritative Bank/Reconcile visible source must not contain CJK or replacement-character mojibake');
const css=readFileSync('index.html','utf8');
assert.match(css,/\.authoritative-bank-scope-strip/,'Bank/Reconcile detail scope must have a dedicated responsive hierarchy');
assert.match(css,/\.authoritative-evidence-stage/,'Bank/Reconcile must render a text-labelled lifecycle hierarchy rather than infer state from colour');
assert.match(source,/className="qbo-grid authoritative-bank-summary-grid"/,'Bank queue summary must use the shared authoritative card grid');
assert.match(source,/report-workbench recon-summary authoritative-reconciliation-summary/,'Reconciliation summary must use the shared demonstration reconciliation workbench');
assert.match(readFileSync('src/ui.jsx','utf8'),/blocked: 'empty empty-state state-block state-blocked'/,'The shared state system must represent an authoritative BLOCKED result distinctly from an ordinary empty result');
assert.match(css,/\.state-blocked\{border-color:var\(--qb-warn-line\)/,'The BLOCKED state must have a visible warning treatment without becoming a disabled action');
assert.match(css,/\.authoritative-admitted-statements\{border-left:4px solid var\(--qb-ok\)/,'Signed admitted evidence must have a distinct retained-evidence boundary');
assert.match(css,/\.authoritative-admitted-statements-table \.tbl\{min-width:900px/,'Signed statement columns must remain inside a contained table on narrow screens');
assert.match(css,/@media \(max-width:430px\)\{\.authoritative-admitted-statements\{padding:16px;/,'Signed statement controls must stack at phone widths');
assert.match(css,/\.authoritative-admitted-actions \.btn,[^\n]*min-height:44px/,'Signed statement controls must keep WCAG-sized touch targets');
const appSource=readFileSync('src/authoritative-app.jsx','utf8');
assert.match(appSource,/if \(!routeRequiresSharedAccountingBootstrap\(route\)\) \{[\s\S]*setPhase\('READY'\);[\s\S]*return;/,'self-loading routes must enter READY without awaiting the shared accounting bundle');
assert.match(appSource,/phase === 'READY' && routeRequiresSharedAccountingBootstrap\(route\) && !sharedAccountingLoaded/,'later navigation to a shared-data page must still load AP\/AR and Journal evidence exactly when needed');

console.log('authoritative-bank-workspace: scoped full-page read-only SSR contract passed');
