import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {AuthoritativeChartOfAccountsWorkspace,authoritativeCoaScopeText,authoritativeRangeLabel,restoreAuthoritativeCoaReturnContext} from '../src/authoritative-coa-register-workspace.jsx';
import {AuthoritativeAccountRegisterView,AuthoritativeChartOfAccountsView} from '../src/authoritative-coa-view.jsx';

const config={entityId:'11111111-1111-4111-8111-111111111111',periodId:'22222222-2222-4222-8222-222222222222',baseUrl:'https://api.example',getAccessToken:async()=> 'a'.repeat(48)};
const markup=renderToStaticMarkup(<AuthoritativeChartOfAccountsWorkspace config={config} fetcher={async()=>({ok:true,json:async()=>({ok:true,data:[]})})}/>);
assert.match(markup,/Chart of accounts/);assert.doesNotMatch(markup,/>Chart of Accounts</,'the visible heading must use the authenticated QBO sentence-case label');assert.match(markup,/Search/);assert.match(markup,/Filter by name or number/);assert.match(markup,/Status/);assert.match(markup,/Currency/);assert.match(markup,/Rows per page/);assert.match(markup,/READ ONLY/);assert.match(markup,/Loading accounts and posted balances/);assert.doesNotMatch(markup,/Master status|Posted currency|Loading authoritative account master|Accounts returned|Exact API snapshot/,'COA must use concise accounting copy without repeating implementation labels or summary cards');
assert.match(markup,/<span class="result-count" aria-live="polite">/,'COA result changes must be announced without adding another summary card');
assert.match(markup,/<button type="button" class="btn btn-sm" disabled="">Loading…<\/button>/,'COA must prevent duplicate refresh reads while its GET is pending');
const source=fs.readFileSync(path.join(process.cwd(),'src','authoritative-coa-register-workspace.jsx'),'utf8');
assert.match(source,/eyebrow="ACCOUNTING"/);assert.match(source,/Review accounts and posted balances\./);assert.doesNotMatch(source,/GENERAL LEDGER \| ACCOUNT MASTER|Review accounts and posted balances by currency\./,'the COA heading must use concise customer-facing accounting language');assert.match(source,/'Loading…':'Refresh'/);assert.doesNotMatch(source,/Entity-scoped account master facts|All retained currencies|No entity-scoped account-master row/);
const presentation=fs.readFileSync(path.join(process.cwd(),'src','authoritative-coa-view.jsx'),'utf8');
const app=fs.readFileSync(path.join(process.cwd(),'src','authoritative-app.jsx'),'utf8');
const coaRoute=app.slice(app.indexOf("['chart-of-accounts','account-inquiry']"),app.indexOf("route === 'general-ledger'"));
assert.match(coaRoute,/config=\{displayConfig\}/,'Chart of Accounts and Account Inquiry must receive the shared readable scope presentation');
assert.match(source,/refreshAuthoritativeChartOfAccounts/);assert.match(source,/refreshAuthoritativeAccountRegister/);assert.match(source,/Back to chart of accounts/);assert.doesNotMatch(source,/<span>Posted account activity<\/span>/,'the register Back row must not repeat the page purpose beside its direct return action');assert.match(source,/authoritative-coa-table/);assert.match(source,/authoritative-register-table/);assert.doesNotMatch(source,/authoritative-coa-summary/,'COA must not retain the redundant four-card summary');assert.match(source,/authoritative-register-scope/);assert.match(source,/Clear filters/);assert.match(source,/View register/,'COA rows must use the authenticated QBO action vocabulary');assert.match(source,/Run report/,'COA rows must expose the observed read-only report action');assert.match(source,/initialAccountCode=\{selection\.accountCode\}/,'row Run report must bind the selected authoritative account code');assert.match(source,/workspaceTitle="Account QuickReport"/);assert.match(source,/kind:'ACCOUNT_LIST'/,'top-level Run report must open the existing authoritative Account List reader');assert.match(source,/AuthoritativeAccountListReport state=\{state\}/);assert.match(source,/id="authoritative-coa-run-report"/);assert.match(source,/backLabel="Back to chart of accounts"/,'both account reports must return to the exact COA parent');assert.doesNotMatch(source,/>Open register<\/button>/);assert.match(source,/Chart of accounts filters retained/);assert.match(source,/Company \/ period/);assert.match(source,/Loading account activity/);
assert.match(source,/role="group" aria-label=\{`Account views for \$\{row\.account_name\}`\}/,'until the API returns account type, both proven read-only views must form one named action group instead of pretending to choose the QBO type-specific primary action');
const shellCss=fs.readFileSync(path.join(process.cwd(),'index.html'),'utf8');
assert.match(shellCss,/\.authoritative-coa-row-actions\{display:inline-flex;align-items:stretch;gap:0/,'COA read-only views must render as one compact split control');
assert.match(source,/>Source documents</);assert.match(source,/>Details</);assert.match(source,/'Not available'/);
assert.doesNotMatch(source,/Retained source IDs|No retained source ID|No posted currency evidence|>Evidence</,
  'COA and Register tables must use concise accounting labels while preserving source IDs and register drill-through');
assert.doesNotMatch(source,/Search register evidence|Currencies returned|Loading or no retained entries|Refresh evidence|No posted register entries returned/,'Account Register must use the same concise first-screen language as COA and GL');
assert.equal(authoritativeRangeLabel({page:0,pageSize:25,total:200,itemLabel:'accounts'}),'Showing accounts 1 to 25 of 200');
assert.equal(authoritativeRangeLabel({page:7,pageSize:25,total:200,itemLabel:'accounts'}),'Showing accounts 176 to 200 of 200');
assert.equal(authoritativeRangeLabel({page:0,pageSize:25,total:0,itemLabel:'accounts'}),'No accounts');
assert.equal(authoritativeCoaScopeText({entityId:config.entityId,periodId:config.periodId},{...config,scopePresentation:{entityLabel:'Wan Pacific Real Estate Development LLC',periodLabel:'2026-08'}}),'Wan Pacific Real Estate Development LLC · 2026-08');
assert.equal(authoritativeCoaScopeText({entityId:config.entityId,periodId:config.periodId},config),'Configured entity · Configured period');
assert.doesNotMatch(authoritativeCoaScopeText({entityId:config.entityId,periodId:config.periodId},config),new RegExp(`${config.entityId}|${config.periodId}`),'Register scope must not expose raw UUIDs as visible labels');
assert.match(source,/evidenceScope\(state\.scope\|\|\{entityId:config\.entityId,periodId:config\.periodId\},config\)/,'Chart of Accounts must use the same readable scope labels as its Register');
assert.match(source,/API amounts use fixed four-decimal strings/,'the exact amount-format contract must remain available as audit metadata rather than long visible copy');
assert.match(source,/· balances by currency/,'COA must expose one concise visible currency boundary');
assert.doesNotMatch(source,/>Configured entity · configured period\./,'Chart of Accounts must not hard-code generic scope text when runtime labels are available');
assert.doesNotMatch(source,/localStorage|from ['"]\.\/repo|from ['"]\.\/seed|from ['"]\.\/data|\b(?:POST|PUT|PATCH|DELETE)\b|[鈥路]/);
const styles=fs.readFileSync(path.join(process.cwd(),'index.html'),'utf8');
assert.match(styles,/\.authoritative-register-scope/);assert.match(styles,/\.authoritative-coa-filter/);assert.match(styles,/\.authoritative-coa-presentation \.authoritative-coa-filter\{padding:10px 0;border:0;border-radius:0;background:transparent;box-shadow:none;\}/);assert.match(styles,/\.authoritative-coa-pagination/);assert.match(styles,/\.authoritative-status\.is-active/);assert.match(styles,/@media \(max-width:600px\)/);
assert.match(styles,/\.authoritative-register-scope\{display:flex;gap:0;overflow-x:auto;margin:0 0 14px;border:var\(--qb-hair\) solid var\(--qb-divider\);border-radius:var\(--qb-r-card\);background:var\(--qb-surface\);box-shadow:none;scrollbar-width:thin;\}/,'Register scope must use one compact, keyboard-scrollable fact strip at every width');
assert.match(styles,/\.authoritative-register-scope>span\{flex:1 0 150px;min-height:0;padding:9px 12px;border:0;border-right:var\(--qb-hair\) solid var\(--qb-divider\);border-radius:0;background:transparent;box-shadow:none;\}/,'Register scope facts must use compact dividers rather than four tall cards');
assert.match(styles,/\.authoritative-register-scope>span:first-child,[^\n]+\{border-top:0;\}/,'Register scope must remove the unrelated four-color card accents');
assert.match(styles,/\.authoritative-register-table,\.authoritative-coa-table,\.authoritative-journal-table,\.authoritative-journal-line-table,\.authoritative-general-ledger-table,\.authoritative-document-table,\.authoritative-adjustment-table\{max-height:60vh;overflow:auto;overscroll-behavior:contain;\}/,'long accounting and document tables must remain contained on mobile after the generic table override');
assert.match(source,/AuthoritativeChartOfAccountsView/);assert.match(source,/AuthoritativeAccountRegisterView/);assert.doesNotMatch(source,/Chart of Accounts reading path/,'QBO-style COA must not add a reading rail above a simple list');assert.doesNotMatch(source,/Account register reading path/,'Account Register must not repeat its scope and table structure as a reading rail');
assert.match(source,/authoritative-register-filter[\s\S]*aria-live="polite"[\s\S]*disabled=\{state\.phase==='LOADING'\}[\s\S]*'Loading…':'Refresh'/,'Register must announce result changes and prevent duplicate refresh reads while loading');
assert.match(source,/AuthoritativeLineageDrill/,'Register rows must open the shared authoritative Journal, GL, and Source evidence drill');
assert.match(source,/initial=\{\{kind:'GL',row:detail,context:\{entityId:config\.entityId,periodId:config\.periodId,journalEntryId:detail\.journal_entry_id,journalLineId:detail\.journal_line_id,ledgerLineId:detail\.ledger_line_id\}\}\}/,'Register drill must bind exact entity, period, Journal, journal-line, and ledger-line identity');
assert.match(source,/registerTableRef\.current\?\.scrollTo[\s\S]*detailOpener\.current\)\?\.focus[\s\S]*scrollTo\?\.\(\{top:detailScrollY\.current/,'Back from Register evidence must restore table scroll, opener focus, and page scroll');
assert.match(source,/authoritative-register-line-[\s\S]*View details/,'each retained Register row must expose an explicit read-only detail action');
assert.match(source,/<details className="authoritative-return-context authoritative-register-return"><summary>Chart of accounts filters retained<\/summary>/,'Register Back context must remain available in a concise native disclosure');
assert.match(source,/scrollY:Number\(environment\?\.scrollY\)\|\|0,tableX:Number\(tableRef\.current\?\.scrollLeft\)\|\|0/,'opening a Register must freeze both page and contained-table scroll positions');
assert.match(source,/ref=\{tableRef\} className="table-wrap authoritative-coa-table"/,'the account table scroller must be retained for exact Back restoration');
assert.match(source,/ref=\{registerTableRef\} className="table-wrap authoritative-register-table"/,'the Register table scroller must be retained for nested Back restoration');
assert.match(source,/title="Account Register" subtitle="Posted activity for one account and period\."/,'Register needs a stable concise page title instead of repeating a potentially long account name');
assert.match(source,/<i>Account<\/i><b>\{accountName\}<\/b><small>\{accountCode\}<\/small>/,'the selected account name and code must remain visible in the scoped account fact');
assert.match(source,/aria-label="Chart of Accounts"/,'the account region needs a width-neutral accessible name');
assert.doesNotMatch(source,/Chart of Accounts; scroll horizontally/,'the account region must not promise horizontal scrolling after phone reflow');
assert.match(source,/data-label="Account"/,'phone-width account cards must retain an explicit account label');
assert.match(source,/data-label="Posted lines"/,'phone-width account cards must retain posted-line evidence');
assert.match(source,/data-label="Action"/,'phone-width account cards must retain the Register and report actions');
assert.match(styles,/@media \(max-width:600px\)\{[\s\S]*?\.authoritative-coa-table \.tbl\{min-width:0;table-layout:auto;\}/,'phone-width Chart of Accounts must reflow instead of retaining the desktop minimum width');
assert.match(styles,/\.authoritative-coa-table tbody td::before\{content:attr\(data-label\)/,'reflowed account facts need visible labels when the desktop header is hidden');
assert.match(source,/authoritative-coa-query-filter/,'the COA search control needs a stable responsive slot');
assert.match(source,/authoritative-coa-status-filter/,'the authoritative status filter must remain available on phones');
assert.match(source,/authoritative-coa-currency-filter/,'the authoritative currency filter must remain available on phones');
assert.match(source,/const COA_PAGE_SIZES=Object\.freeze\(\[25,50,100,200\]\)/,'the COA pager must include the observed 200-account page capacity');
assert.match(source,/const \[query,setQuery\]=useState\(''\);const \[status,setStatus\]=useState\('ALL'\);const \[currency,setCurrency\]=useState\('ALL'\);const \[page,setPage\]=useState\(0\);const \[pageSize,setPageSize\]=useState\(200\)/,'Chart of Accounts must default to the observed 200-account page capacity');
assert.match(source,/<PageSize label="Rows per page" value=\{pageSize\} sizes=\{COA_PAGE_SIZES\}/,'only the COA list should receive the 200-row option');
assert.match(styles,/@media\(max-width:600px\)\{[\s\S]*?\.authoritative-coa-filter\{display:grid!important;grid-template-columns:repeat\(6,minmax\(0,1fr\)\)/,'phone-width COA filters must use a compact toolbar instead of seven full-width rows');
const restoreCalls=[];
const restoreEnvironment={scrollTo:options=>restoreCalls.push(['page',options]),setTimeout:callback=>{restoreCalls.push(['timer']);callback();},document:{getElementById:id=>({focus:()=>restoreCalls.push(['focus',id])})}};
const restoreTable={scrollTo:options=>restoreCalls.push(['table',options])};
assert.equal(restoreAuthoritativeCoaReturnContext(restoreEnvironment,config,{entityId:config.entityId,periodId:config.periodId,scrollY:640,tableX:275},{getTable:()=>restoreTable,focusId:'account-opener'}),true);
assert.deepEqual(restoreCalls,[['timer'],['page',{top:640,behavior:'auto'}],['table',{left:275,behavior:'auto'}],['focus','account-opener']]);
assert.equal(restoreAuthoritativeCoaReturnContext(restoreEnvironment,{...config,periodId:'33333333-3333-4333-8333-333333333333'},{entityId:config.entityId,periodId:config.periodId,scrollY:1,tableX:1},{getTable:()=>restoreTable,focusId:'stale'}),false,'Register Back must fail closed before restoring stale scope');
assert.equal(restoreCalls.length,4,'stale Back context must not schedule scroll or focus restoration');
assert.match(presentation,/authoritative-coa-presentation/);assert.match(presentation,/authoritative-account-register-presentation/);
assert.doesNotMatch(presentation,/localStorage|from ['"]\.\/repo|from ['"]\.\/seed|from ['"]\.\/data|accounting-api|legacy-demo-app/);
assert.match(renderToStaticMarkup(<AuthoritativeChartOfAccountsView><div>API slot</div></AuthoritativeChartOfAccountsView>),/API slot/);
assert.match(renderToStaticMarkup(<AuthoritativeAccountRegisterView><div>API register slot</div></AuthoritativeAccountRegisterView>),/API register slot/);
assert.match(styles,/\.authoritative-ledger-toolbar/);
console.log('authoritative COA/Register workspace: API-only filters, paging, exact Back context, contained tables, and responsive evidence verified');
