import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {AuthoritativeSourceDocumentsWorkspace,authoritativeSourceScopeLabels} from '../src/authoritative-source-documents-workspace.jsx';
import {AuthoritativeSourceDocumentsView} from '../src/authoritative-source-documents-view.jsx';

const config={entityId:'11111111-1111-4111-8111-111111111111',periodId:'22222222-2222-4222-8222-222222222222',baseUrl:'https://api.example',getAccessToken:async()=> 'a'.repeat(48)};
assert.deepEqual(authoritativeSourceScopeLabels({...config,scopePresentation:{entityLabel:'Wan Pacific Real Estate Development LLC',periodLabel:'2026-08'}}),{entity:'Wan Pacific Real Estate Development LLC',period:'2026-08'});
assert.deepEqual(authoritativeSourceScopeLabels(config),{entity:'Configured entity',period:'Configured period'});
const markup=renderToStaticMarkup(<AuthoritativeSourceDocumentsWorkspace config={config} fetcher={async()=>({ok:true,json:async()=>({ok:true,data:[]})})}/>);
assert.match(markup,/Loading authoritative Source Document evidence/);
const source=fs.readFileSync(path.join(process.cwd(),'src','authoritative-source-documents-workspace.jsx'),'utf8');
const presentation=fs.readFileSync(path.join(process.cwd(),'src','authoritative-source-documents-view.jsx'),'utf8');
const app=fs.readFileSync(path.join(process.cwd(),'src','authoritative-app.jsx'),'utf8');
const sourceRoute=app.slice(app.indexOf("route === 'source-documents'"),app.indexOf("route === 'chart-of-accounts'"));
assert.match(sourceRoute,/config=\{displayConfig\}/,'the authoritative Source Documents route must pass shared readable scope labels, not raw runtime config only');
assert.match(source,/refreshAuthoritativeSourceDocuments/);assert.match(source,/readAuthoritativeSourceDocumentDetail/);assert.match(source,/does not expose attachment content, raw provider payloads/);assert.match(source,/Back to Source Documents/);
assert.match(source,/AuthoritativeSourceDocumentsView/,'Source Documents must use the authoritative register presentation');
assert.match(presentation,/full-bleed.*authoritative-source-documents-presentation/,'Source Documents must retain the authoritative full-page register frame');
assert.match(presentation,/Source Documents Register/,'Source Documents must retain the demo register heading');
assert.match(presentation,/kpi-row authoritative-source-summary/,'Source Documents must present API-returned scope counts in the demo KPI hierarchy');
assert.match(source,/authoritative-source-scope/,'Source Documents must visibly retain the API entity and period scope above the evidence register');
assert.match(source,/scopeLabels\.entity/);assert.match(source,/scopeLabels\.period/);assert.doesNotMatch(source,/<b>\{config\.(?:entityId|periodId)\}<\/b>/,'Source Documents must not promote raw scope UUIDs as visible labels');
assert.match(source,/Journal-linked/,'Source Documents must distinguish retained journal references from unlinked list facts');
assert.match(source,/authoritative-source-intro/,'Source Documents must disclose its evidence-only boundary before the list');
assert.match(source,/authoritative-source-filters/,'Source Documents must provide presentation-only source evidence filters');
assert.match(source,/sourceSystem==='ALL'\|\|row\.source_system===sourceSystem/,'Source filtering must be applied only to rows already returned by the authoritative API');
assert.match(source,/detailReturnRef\.current=\{focusId:`authoritative-source-document-\$\{id\}`,pageY:globalThis\.scrollY\|\|0,tableX:listScrollRef\.current\?\.scrollLeft\|\|0,query,sourceSystem\}/,'Source Document details must retain exact list filter and scroll context before replacing the list');
assert.match(source,/setQuery\(context\?\.query\|\|'\'\);setSourceSystem\(context\?\.sourceSystem\|\|'ALL'\);/,'Source Document Back must restore the captured presentation filters');
assert.match(source,/Retained source lines/,'Source Document detail must name its retained line evidence');
assert.match(source,/This page exposes only immutable metadata and retained line evidence/,'Source Document detail must be explicit about the authority boundary');
assert.match(source,/Not retained/,'Source Document detail must use an explicit API-field absence state');
assert.doesNotMatch(source,/[\u4e00-\u9fff]|鈥|路|�/,'Source Document visible UI must remain English-only and free from known mojibake artifacts');
assert.match(source,/listScrollRef\.current\?\.scrollTo\?\.\(\{left:context\?\.tableX\|\|0\}\)/,'Source Document Back must restore narrow-table horizontal position');
assert.match(source,/getElementById\(context\?\.focusId\)\?\.focus\?\.\(\{preventScroll:true\}\)/,'Source Document Back must restore keyboard focus to the exact list opener');
assert.match(source,/className="table-wrap authoritative-source-document-list" role="region" tabIndex=\{0\} aria-label="Source Documents; scroll horizontally to view every column"/,'Source Document list must be a named keyboard-focusable narrow-table scroll region');
assert.match(source,/className="table-wrap authoritative-source-document-lines" role="region" tabIndex=\{0\} aria-label="Source Document lines; scroll horizontally to view every column"/,'Source Document detail lines must be a named keyboard-focusable narrow-table scroll region');
assert.doesNotMatch(source,/localStorage|from ['"]\.\/repo|from ['"]\.\/seed|from ['"]\.\/data|\b(?:POST|PUT|PATCH|DELETE)\b/);
assert.doesNotMatch(presentation,/localStorage|from ['"]\.\/repo|from ['"]\.\/seed|from ['"]\.\/data|accounting-api|legacy-demo-app/);
const presentationMarkup=renderToStaticMarkup(<AuthoritativeSourceDocumentsView scope="API scope" metrics={<span>1</span>} actions={<button>Refresh</button>}><div>API slot</div></AuthoritativeSourceDocumentsView>);
assert.match(presentationMarkup,/Source Documents Register/);assert.match(presentationMarkup,/API slot/);
console.log('authoritative Source Documents workspace: API-only persisted evidence, full-page detail, filters, responsive table regions, and immutable return context verified');
