import assert from 'node:assert/strict';
import fs from 'node:fs';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {AuthoritativeWbsPayableWorkspace,restoreAuthoritativeWbsPayableReturnContext} from '../src/authoritative-wbs-payable-workspace.jsx';
import {AuthoritativeWbsPayableReviewWorkspace} from '../src/authoritative-wbs-payable-review-workspace.jsx';

const config={entityId:'11111111-1111-4111-8111-111111111111',periodId:'33333333-3333-4333-8333-333333333333',baseUrl:'https://accounting.example',getAccessToken:async()=> 'a'.repeat(48)};
const markup=renderToStaticMarkup(<AuthoritativeWbsPayableWorkspace config={config} fetcher={async()=>{throw new Error('SSR must not fetch');}}/>);
assert.match(markup,/Reviewed WBS Payables/);assert.match(markup,/Loading reviewed WBS Payables/);
const reviewMarkup=renderToStaticMarkup(<AuthoritativeWbsPayableReviewWorkspace config={config} fetcher={async()=>{throw new Error('SSR must not fetch');}}/>);
for(const token of ['Admitted WBS Payables awaiting review','SIGNED \\+ ADMITTED','SERVER DERIVED','REVIEW ONLY','NO DRAFT','Loading admitted WBS Payables'])assert.match(reviewMarkup,new RegExp(token,'i'));
const source=fs.readFileSync('src/authoritative-wbs-payable-workspace.jsx','utf8');
for(const token of ['refreshAuthoritativeWbsPayableReviewEvidence','createAuthoritativeWbsPayableApDraft','Create AP Bill Draft','maker reason','Nothing was submitted, reviewed, approved, or posted'])assert.match(source,new RegExp(token,'i'));
assert.doesNotMatch(source,/localStorage|seed\.js|Submit Bill|Approve Bill|Post Journal/);
assert.match(source,/detailReturnRef\.current=\{entityId:config\.entityId,periodId:config\.periodId,scrollY:Number\(environment\?\.scrollY\)\|\|0,tableX:Number\(listTableRef\.current\?\.scrollLeft\)\|\|0,focusId\}/,'opening reviewed WBS Payable evidence must freeze exact list and contained-table position');
assert.match(source,/ref=\{listTableRef\} className="table-wrap authoritative-wbs-payable-table"/,'the reviewed Payables table scroller must be retained for Back restoration and mobile containment');
assert.match(source,/Review approved source evidence and prepare a Draft\./);assert.doesNotMatch(source,/exact 094 review evidence|Refresh evidence/,'the first screen must not expose migration or read-model terminology');
for(const token of ['Loading reviewed Payables.','No reviewed Payables are ready for Draft preparation.'])assert.match(source,new RegExp(token.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')),'reviewed Payables loading and empty states must use concise user-facing language');
assert.doesNotMatch(source,/Reading retained PostgreSQL evidence only|immutable READY_FOR_DRAFT/,'reviewed Payables states must not expose storage or internal enum terminology');
assert.match(source,/>View details<\/button>/,'the reviewed queue must use the shared detail-action label');
assert.doesNotMatch(source,/>Open evidence<\/button>/,'the reviewed queue must not use a second action vocabulary');
const css=fs.readFileSync('index.html','utf8');assert.match(css,/\.authoritative-wbs-payable-table\{max-height:60vh;overflow:auto;overscroll-behavior:contain;\}/,'reviewed WBS Payables must remain contained at phone widths');
const restoreCalls=[];const environment={scrollTo:options=>restoreCalls.push(['page',options]),setTimeout:callback=>{restoreCalls.push(['timer']);callback();},document:{getElementById:id=>({focus:()=>restoreCalls.push(['focus',id])})}};const table={scrollTo:options=>restoreCalls.push(['table',options])};
assert.equal(restoreAuthoritativeWbsPayableReturnContext(environment,config,{entityId:config.entityId,periodId:config.periodId,scrollY:525,tableX:180,focusId:'wbs-row'},()=>table),true);
assert.deepEqual(restoreCalls,[['timer'],['page',{top:525,behavior:'auto'}],['table',{left:180,behavior:'auto'}],['focus','wbs-row']]);
assert.equal(restoreAuthoritativeWbsPayableReturnContext(environment,{...config,entityId:'22222222-2222-4222-8222-222222222222'},{entityId:config.entityId,periodId:config.periodId,scrollY:1,tableX:1,focusId:'stale'},()=>table),false);
assert.equal(restoreCalls.length,4,'stale WBS Payable context must not restore page, table, or focus');
const reviewSource=fs.readFileSync('src/authoritative-wbs-payable-review-workspace.jsx','utf8');
assert.match(reviewSource,/className="table-wrap authoritative-wbs-payable-table" role="region" tabIndex=\{0\} aria-label="Admitted WBS Payables awaiting review/,'the admitted review queue must reuse the shared Payables narrow-screen table region');
for(const token of ['refreshAuthoritativeWbsPayableReviewCandidates','reviewAuthoritativeWbsPayable','refreshAuthoritativeWbsPayableAttachmentUploads','uploadVerifiedAttachment','bindAuthoritativeWbsPayableUploadedAttachment','Add support evidence','Independent binder required','No Bill or Journal Draft was created','Nothing was submitted, approved, or posted'])assert.match(reviewSource,new RegExp(token,'i'));
assert.match(reviewSource,/<th>Action<\/th>/,'the admitted queue must label its final column as an action');
assert.doesNotMatch(reviewSource,/<th>Evidence<\/th>/,'the admitted queue must not use a competing column label');
assert.match(reviewSource,/Inspect review evidence/,'the review action must remain distinct from adding support evidence');
for(const token of ['Checking source, scope, mapping, separation of duties, and attachments.','No signed Payables are ready for review. Unsigned pilot rows remain excluded.'])assert.match(reviewSource,new RegExp(token.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')),'admitted Payables states must be concise while preserving review controls');
assert.doesNotMatch(reviewSource,/exact production receipt, entity, currency, period, approved mapping, local master data, SoD|authenticated API returned a valid empty result/,'admitted Payables states must not expose implementation-heavy prose');
for(const token of ['NO_PERMISSION — WBS Payable reviewer access required','WBS_PAYABLE_REVIEWER','WBS.PAYABLE.REVIEW','AP.VIEW','Unsigned Pilot observations remain excluded'])assert.match(reviewSource,new RegExp(token.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')),'WBS review denial must name the exact read role and preserve the unsigned boundary');
assert.doesNotMatch(reviewSource,/localStorage|seed\.js|createAuthoritativeWbsPayableApDraft|Submit Bill|Approve Bill|Post Journal/);
console.log('authoritative WBS Payable workspace: admitted review and separate reviewed-evidence Draft boundaries');
