import assert from 'node:assert/strict';
import fs from 'node:fs';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {AuthoritativeWbsTransitionWorkspace} from '../src/authoritative-wbs-transition-workspace.jsx';

const config={entityId:'11111111-1111-4111-8111-111111111111',periodId:'33333333-3333-4333-8333-333333333333',baseUrl:'https://accounting.example',getAccessToken:async()=> 'a'.repeat(48)};
const markup=renderToStaticMarkup(<AuthoritativeWbsTransitionWorkspace config={config} fetcher={async()=>{throw new Error('SSR must not verify a contract');}}/>);
assert.match(markup,/WBS Payables and exception review/);
assert.match(markup,/LIVE DATA/);
assert.match(markup,/Signed provider contract JSON/);
assert.match(markup,/Verify signed contract evidence/);
assert.match(markup,/BLOCKED - signed provider evidence required/);
assert.match(markup,/Exception/);
assert.match(markup,/Signed redelivery/);
assert.match(markup,/Approval \/ Post/);
assert.doesNotMatch(markup,/Enable WBS evidence read|WBS evidence read access/);
assert.match(markup,/Production WBS provider observation/);
assert.match(markup,/UNSIGNED PILOT/);
assert.match(markup,/GET ONLY/);
assert.match(markup,/NOT ADMITTED/);
assert.match(markup,/NOT POSTABLE/);
assert.match(markup,/aria-label="Production WBS observation boundary"/);
assert.match(markup,/Load WBS observation/);
assert.match(markup,/Payables/);
assert.match(markup,/Bank transactions/);
assert.match(markup,/AutoRec details/);
assert.match(markup,/AutoRec banks/);
assert.match(markup,/Journal entries/);
assert.match(markup,/No WBS records loaded/);
assert.match(markup,/Mixed or unassigned records can be retained for finance review, but no accounting entry will be created/);
assert.match(markup,/Persisted AutoRec review evidence/);
assert.match(markup,/Load AutoRec review evidence/);
assert.match(markup,/Match Review → G11 posted evidence/);
assert.match(markup,/Load Match Review/);
assert.match(markup,/Trace G11 \/ GL/);
assert.match(markup,/WBS \/ REFS control reconciliation/);
assert.match(markup,/Load control reconciliation/);
assert.match(markup,/No direct WBS read or provider request occurs from this browser page/);
assert.match(markup,/No WBS ingress, REFS write, Draft, approval, posting, reversal, reserve, or release is available here/);
assert.doesNotMatch(markup,/localStorage|seed\.js|Create Draft|Approve|Post journal/);
assert.match(markup,/class="report-shelf"/);
assert.match(markup,/class="report-workbench"/);
assert.match(markup,/WBS Payable accounting path/);
assert.match(markup,/Advanced: verify a signed transition contract/);
const source=fs.readFileSync('src/authoritative-wbs-transition-workspace.jsx','utf8');
assert.match(source,/G11 posted journal and ledger evidence/);
assert.match(source,/verifyAuthoritativeWbsTransitionContract/);
assert.match(source,/refreshAuthoritativeWbsAutoRecReview/);
assert.match(source,/refreshAuthoritativeWbsAutoRecMatchReview/);
assert.match(source,/refreshAuthoritativeWbsAutoRecG11Evidence/);
assert.match(source,/refreshAuthoritativeWbsControlReconciliation/);
assert.match(source,/AuthoritativeWbsLivePilotObservation/);
assert.match(source,/WBS_LIVE_PILOT_SURFACE_TOOLS\.wbs/);
const livePilotSource=fs.readFileSync('src/authoritative-wbs-live-pilot-observation.jsx','utf8');
assert.match(livePilotSource,/refreshAuthoritativeWbsLivePilot/);
assert.match(livePilotSource,/WBS_LIVE_PILOT_VIEWS/);
assert.match(livePilotSource,/row\[field\]===null\?'Unavailable':row\[field\]/);
assert.doesNotMatch(livePilotSource,/vendor_name|vendor_no|payee|localStorage|seed\.js/);
assert.doesNotMatch(source,/activateAuthoritativeWbsReadAccess|activateWbsRead|accessState/);
assert.match(source,/status!=='BLOCKED'\?\{phase:'READY',data:result\.data,error:null\}:\{phase:'BLOCKED',data:current\.data/);
assert.match(source,/Advanced: verify a signed transition contract/);
assert.match(source,/AuthoritativeWorkspaceView/);
assert.match(source,/AuthoritativeWorkspaceHeader/);
assert.doesNotMatch(source,/legacy-demo-app|\.\/seed|\.\/repo|localStorage/);
assert.doesNotMatch(source,/Number\(row\.(?:amount|source_amount|target_amount|difference)\)|toFixed\(4\)/);
assert.doesNotMatch(source,/vendor_name|vendor_no|payee/);
const css=fs.readFileSync('index.html','utf8');
assert.match(css,/\.authoritative-wbs-review-table \.tbl\{min-width:1180px;table-layout:fixed;\}/);
assert.match(css,/\.authoritative-wbs-control-table \.tbl\{min-width:760px;table-layout:fixed;\}/);
assert.match(css,/\.authoritative-wbs-live-pilot-controls select,\.authoritative-wbs-live-pilot-controls \.btn\{min-height:44px;\}/);
assert.match(css,/\.authoritative-wbs-live-pilot-table \.tbl\{min-width:1040px;table-layout:fixed;\}/);
console.log('authoritative WBS transition workspace: signed evidence only, no authority actions');
