import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {aiAccountingDecisionCommandIdempotencyKey,aiAccountingDecisionRunIdempotencyKey,aiAccountingPostedOutcomeIdempotencyKey,createAuthoritativeAiAccountingDecisionDraft,decideAuthoritativeAiAccountingDecision,refreshAuthoritativeAiAccountingDecisionQueue,refreshAuthoritativeAiAccountingPostedOutcomeHistory,retainAuthoritativeAiAccountingDecisionRun,retainAuthoritativeAiAccountingPostedOutcomeReview} from '../src/accounting-api.js';

const id=n=>`${String(n).padStart(8,'0')}-0000-4000-8000-${String(n).padStart(12,'0')}`;
const entityId=id(1),periodId=id(2),decisionId=id(3),humanId=id(4),hash=`sha256:${'a'.repeat(64)}`;
const config={baseUrl:'https://accounting.example',entityId,periodId,getAccessToken:async()=> 'a'.repeat(48)};
const action_flags={can_accept_or_reject:true,can_create_draft:false,can_retain_posted_outcome:false,can_submit:false,can_review:false,can_approve:false,can_post:false};
const decision={ai_accounting_decision_id:decisionId,decision_hash:hash,packet_status:'READY_FOR_HUMAN_REVIEW',action_flags};
const canonical=value=>{if(value===null||typeof value!=='object')return JSON.stringify(value);if(Array.isArray(value))return `[${value.map(canonical).join(',')}]`;return `{${Object.keys(value).sort().map(key=>`${JSON.stringify(key)}:${canonical(value[key])}`).join(',')}}`;};
const canonicalHash=value=>`sha256:${createHash('sha256').update(canonical(value)).digest('hex')}`;

test('browser reads an empty retained decision page with no-store and exact scope',async()=>{
  let request;const data={schema_version:'AI_ACCOUNTING_DECISION_QUEUE_SNAPSHOT_V1',scope:{tenant_id:id(9),entity_id:entityId,accounting_period_id:periodId},total_count:0,read_count:0,limit:50,offset:0,population_complete:true,population_hash:hash,snapshot_token:hash,rows:[]};
  const result=await refreshAuthoritativeAiAccountingDecisionQueue({config,fetcher:async(url,init)=>(request={url,init},{ok:true,json:async()=>({ok:true,data})})});
  assert.equal(result.ok,true);assert.match(request.url,/accounting-decision-queue/);assert.equal(request.init.method,'GET');assert.equal(request.init.cache,'no-store');assert.equal(result.data.rows.length,0);
  for(const unsafe of [{...data,population_complete:false},{...data,read_count:1},{...data,debug:true}]){const rejected=await refreshAuthoritativeAiAccountingDecisionQueue({config,fetcher:async()=>({ok:true,json:async()=>({ok:true,data:unsafe})})});assert.equal(rejected.code,'AI_ACCOUNTING_DECISION_QUEUE_PROTOCOL');}
  const missingToken=await refreshAuthoritativeAiAccountingDecisionQueue({config,offset:50,fetcher:async()=>{throw new Error('must not call network')}});assert.equal(missingToken.code,'AI_ACCOUNTING_DECISION_QUEUE_SCOPE_INVALID');
});

test('Run and retain uses a nonce-bound stable identity and accepts only a closed no-action receipt',async()=>{
  const runNonce='1'.repeat(64),first=await aiAccountingDecisionRunIdempotencyKey({config,limit:100,runNonce}),second=await aiAccountingDecisionRunIdempotencyKey({config,limit:100,runNonce});assert.equal(first,second);assert.match(first,/^ai-accounting-decision-run:[0-9a-f]{64}$/);
  const retained={schema_version:'AI_ACCOUNTING_DECISION_RETAINED_V1',ai_accounting_decision_id:decisionId,decision_hash:hash,packet_status:'READY_FOR_HUMAN_REVIEW',source_document_id:id(10),can_create_draft:false,can_review:false,can_approve:false,can_post:false,idempotent:false};
  const receipt={schema_version:'AI_ACCOUNTING_DECISION_RUN_RECEIPT_V1',accounting_period_id:periodId,population:{total_count:1,population_hash:`sha256:${'e'.repeat(64)}`,population_complete:true},row_count:1,receipts:[retained],can_create_draft:false,can_review:false,can_approve:false,can_post:false,idempotent:false};let request;
  const result=await retainAuthoritativeAiAccountingDecisionRun({config,limit:100,runNonce,idempotencyKey:first,fetcher:async(url,init)=>(request={url,init},{ok:true,status:201,json:async()=>({ok:true,data:receipt})})});
  assert.equal(result.ok,true,JSON.stringify(result));assert.match(request.url,/\/ai\/accounting-decision-runs$/);assert.equal(request.init.method,'POST');assert.equal(request.init.cache,'no-store');assert.equal(request.init.headers['idempotency-key'],first);assert.deepEqual(JSON.parse(request.init.body),{accounting_period_id:periodId,limit:100});assert.equal(result.data.can_create_draft,false);assert.equal(result.data.can_post,false);
  const wrongNonce=await retainAuthoritativeAiAccountingDecisionRun({config,limit:100,runNonce:'2'.repeat(64),idempotencyKey:first,fetcher:async()=>{throw new Error('must not call network')}});assert.equal(wrongNonce.code,'AI_ACCOUNTING_DECISION_RUN_COMMAND_INVALID');
  const absentIdentity=await retainAuthoritativeAiAccountingDecisionRun({config,limit:100,runNonce:'invalid',idempotencyKey:null,fetcher:async()=>{throw new Error('must not call network')}});assert.equal(absentIdentity.code,'AI_ACCOUNTING_DECISION_RUN_COMMAND_INVALID');
  const distinct={...retained,ai_accounting_decision_id:id(11),decision_hash:`sha256:${'b'.repeat(64)}`,source_document_id:id(12)};
  for(const unsafe of [{...receipt,can_create_draft:true},{...receipt,debug:true},{...receipt,population:{...receipt.population,total_count:2}},{...receipt,population:{...receipt.population,population_complete:false}},{...receipt,row_count:2,population:{...receipt.population,total_count:2},receipts:[retained,retained]},{...receipt,row_count:2,population:{...receipt.population,total_count:2},receipts:[retained,{...distinct,decision_hash:retained.decision_hash}]},{...receipt,row_count:2,population:{...receipt.population,total_count:2},receipts:[retained,{...distinct,source_document_id:retained.source_document_id}]}]){const rejected=await retainAuthoritativeAiAccountingDecisionRun({config,limit:100,runNonce,idempotencyKey:first,fetcher:async()=>({ok:true,status:201,json:async()=>({ok:true,data:unsafe})})});assert.equal(rejected.code,'AI_ACCOUNTING_DECISION_RUN_PROTOCOL');}
  const replay={...receipt,idempotent:true,receipts:[{...retained,idempotent:true}]},replayed=await retainAuthoritativeAiAccountingDecisionRun({config,limit:100,runNonce,idempotencyKey:first,fetcher:async()=>({ok:true,status:200,json:async()=>({ok:true,data:replay})})});assert.equal(replayed.ok,true);assert.equal(replayed.data.idempotent,true);
});

test('human decision command uses stable hash-bound idempotency and validates its receipt',async()=>{
  const reason='Controller verified the retained source evidence.';
  const first=await aiAccountingDecisionCommandIdempotencyKey({config,decision,action:'ACCEPTED',reason}),second=await aiAccountingDecisionCommandIdempotencyKey({config,decision,action:'ACCEPTED',reason});assert.equal(first,second);assert.match(first,/^ai-accounting-decision:[0-9a-f]{64}$/);
  let request;const receipt={schema_version:'AI_ACCOUNTING_HUMAN_DECISION_V1',ai_accounting_decision_id:decisionId,ai_accounting_human_decision_id:humanId,decision_hash:hash,evidence_hash:hash,outcome:'ACCEPTED',can_create_draft:false,can_review:false,can_approve:false,can_post:false,idempotent:false};
  const result=await decideAuthoritativeAiAccountingDecision({config,decision,outcome:'ACCEPTED',reason,idempotencyKey:first,fetcher:async(url,init)=>(request={url,init},{ok:true,status:201,json:async()=>({ok:true,data:receipt})})});
  assert.equal(result.ok,true);assert.equal(request.init.cache,'no-store');assert.equal(request.init.headers['idempotency-key'],first);assert.equal(JSON.parse(request.init.body).expected_decision_hash,hash);
});

test('accepted evidence can create only a Draft receipt',async()=>{
  const accepted={...decision,human_decision:{ai_accounting_human_decision_id:humanId,outcome:'ACCEPTED',evidence_hash:hash},action_flags:{...action_flags,can_accept_or_reject:false,can_create_draft:true}},reason='Maker verified the accepted evidence for Draft creation.',idempotencyKey='decision-draft-key-1';
  const receipt={schema_version:'AI_ACCOUNTING_DECISION_DRAFT_V1',ai_accounting_decision_draft_evidence_id:id(5),ai_accounting_decision_id:decisionId,ai_accounting_human_decision_id:humanId,journal_entry_id:id(6),status:'DRAFT',revision:0,idempotent:false,can_review:false,can_approve:false,can_post:false};
  const result=await createAuthoritativeAiAccountingDecisionDraft({config,decision:accepted,reason,idempotencyKey,fetcher:async()=>({ok:true,status:201,json:async()=>({ok:true,data:receipt})})});
  assert.equal(result.ok,true);assert.equal(result.data.status,'DRAFT');assert.equal(result.data.can_post,false);
});

test('Posted decision retains only server-derived review evidence with canonical hash and command identity',async()=>{
  const posted={...decision,draft_evidence:{journal_status:'POSTED'},latest_posted_outcome_review:null,action_flags:{...action_flags,can_accept_or_reject:false,can_retain_posted_outcome:true}};
  const key=await aiAccountingPostedOutcomeIdempotencyKey({config,decision:posted});assert.match(key,/^ai-posted-outcome:[0-9a-f]{64}$/);
  const evidence={schema_version:'AI_ACCOUNTING_POSTED_OUTCOME_EVIDENCE_V1',ai_accounting_decision_id:decisionId,decision_hash:hash,human_decision_id:humanId,acceptance_hash:hash,draft_evidence_id:id(5),draft_evidence_hash:hash,journal_entry_id:id(6),journal_status:'POSTED',journal_revision:4,proposed_lines_hash:hash,journal_lines_hash:hash,ledger_lines_hash:hash,workflow_evidence_hash:hash,expected_report_deltas_hash:hash,actual_report_deltas_hash:hash,financial_statement_snapshot_id:id(7),financial_statement_snapshot_hash:hash,ledger_evidence_hash:hash,proposed_journal_exact:true,posted_ledger_exact:true,workflow_exact:true,report_snapshot_exact:true,can_create_draft:false,can_review:false,can_approve:false,can_post:false};
  const base={schema_version:'AI_ACCOUNTING_POSTED_OUTCOME_REVIEW_V1',ai_accounting_posted_outcome_review_id:id(8),ai_accounting_decision_id:decisionId,review_revision:0,status:'CONSISTENT',reason_codes:[],reviewed_by:'controller',reviewed_at:'2026-08-28T12:00:00.000Z',evidence,can_create_draft:false,can_review:false,can_approve:false,can_post:false};
  const review={...base,review_hash:canonicalHash({decision_id:decisionId,revision:0,status:'CONSISTENT',reason_codes:[],evidence}),idempotent:false};let request;
  const retained=await retainAuthoritativeAiAccountingPostedOutcomeReview({config,decision:posted,idempotencyKey:key,fetcher:async(url,init)=>(request={url,init},{ok:true,status:201,json:async()=>({ok:true,data:review})})});
  assert.equal(retained.ok,true,JSON.stringify(retained));assert.equal(retained.data.status,'CONSISTENT');assert.equal(request.init.cache,'no-store');assert.deepEqual(JSON.parse(request.init.body),{expected_decision_hash:hash,expected_review_revision:-1});assert.equal(Object.hasOwn(JSON.parse(request.init.body),'evidence'),false);
  const forged={...review,review_hash:hash};const rejected=await retainAuthoritativeAiAccountingPostedOutcomeReview({config,decision:posted,idempotencyKey:key,fetcher:async()=>({ok:true,status:201,json:async()=>({ok:true,data:forged})})});assert.equal(rejected.code,'AI_POSTED_OUTCOME_REVIEW_PROTOCOL');
  const wrongKey=await retainAuthoritativeAiAccountingPostedOutcomeReview({config,decision:posted,idempotencyKey:'posted-outcome-wrong-key',fetcher:async()=>{throw new Error('must not call network')}});assert.equal(wrongKey.code,'AI_POSTED_OUTCOME_REVIEW_COMMAND_INVALID');
  const historyReview={...review};delete historyReview.idempotent;const history=await refreshAuthoritativeAiAccountingPostedOutcomeHistory({config,decision:{...posted,latest_posted_outcome_review:{ai_accounting_posted_outcome_review_id:id(8),review_revision:0,status:'CONSISTENT',review_hash:review.review_hash,reviewed_by:'controller',reviewed_at:'2026-08-28T12:00:00.000Z'}},fetcher:async(url,init)=>(request={url,init},{ok:true,status:200,json:async()=>({ok:true,data:{schema_version:'AI_ACCOUNTING_POSTED_OUTCOME_REVIEW_HISTORY_V1',limit:200,read_count:1,population_complete:true,rows:[historyReview]}})})});assert.equal(history.ok,true,JSON.stringify(history));assert.equal(history.data.rows[0].evidence.posted_ledger_exact,true);assert.equal(request.init.cache,'no-store');
  const incomplete=await refreshAuthoritativeAiAccountingPostedOutcomeHistory({config,decision:{...posted,latest_posted_outcome_review:{ai_accounting_posted_outcome_review_id:id(8),review_revision:0,status:'CONSISTENT',review_hash:review.review_hash,reviewed_by:'controller',reviewed_at:'2026-08-28T12:00:00.000Z'}},limit:1,fetcher:async()=>({ok:true,status:200,json:async()=>({ok:true,data:{schema_version:'AI_ACCOUNTING_POSTED_OUTCOME_REVIEW_HISTORY_V1',limit:1,read_count:1,population_complete:false,rows:[historyReview]}})})});assert.equal(incomplete.code,'AI_POSTED_OUTCOME_REVIEW_HISTORY_POPULATION_INCOMPLETE');
});
