import assert from 'node:assert/strict';
import fs from 'node:fs';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {AuthoritativeWbsTransitionWorkspace} from '../src/authoritative-wbs-transition-workspace.jsx';

const config={entityId:'11111111-1111-4111-8111-111111111111',periodId:'33333333-3333-4333-8333-333333333333',baseUrl:'https://accounting.example',getAccessToken:async()=> 'a'.repeat(48)};
const markup=renderToStaticMarkup(<AuthoritativeWbsTransitionWorkspace config={config} fetcher={async()=>{throw new Error('SSR must not verify a contract');}}/>);
assert.match(markup,/WBS AutoRec transition evidence/);
assert.match(markup,/EVIDENCE ONLY/);
assert.match(markup,/Signed provider contract JSON/);
assert.match(markup,/Verify signed contract evidence/);
assert.match(markup,/BLOCKED - signed provider evidence required/);
assert.match(markup,/never operates WBS or accounting/);
assert.match(markup,/Signed contract required/);
assert.match(markup,/Pinned provider verification/);
assert.match(markup,/Zero REFS action authority/);
assert.match(markup,/Persisted AutoRec review evidence/);
assert.match(markup,/Load AutoRec review evidence/);
assert.match(markup,/WBS \/ REFS control reconciliation/);
assert.match(markup,/Load control reconciliation/);
assert.match(markup,/GET ONLY/);
assert.match(markup,/No direct WBS read or provider request occurs from this browser page/);
assert.match(markup,/No WBS ingress, REFS write, Draft, approval, posting, reversal, reserve, or release is available here/);
assert.doesNotMatch(markup,/localStorage|seed\.js|Create Draft|Approve|Post journal/);
assert.match(markup,/class="report-shelf"/);
assert.match(markup,/class="qbo-grid"/);
assert.match(markup,/class="report-workbench"/);
const source=fs.readFileSync('src/authoritative-wbs-transition-workspace.jsx','utf8');
assert.match(source,/verifyAuthoritativeWbsTransitionContract/);
assert.match(source,/refreshAuthoritativeWbsAutoRecReview/);
assert.match(source,/refreshAuthoritativeWbsControlReconciliation/);
assert.match(source,/status!=='BLOCKED'\?\{phase:'READY',data:result\.data,error:null\}:\{phase:'BLOCKED',data:current\.data/);
assert.match(source,/no-action guard/);
assert.match(source,/AuthoritativeDemoView/);
assert.match(source,/AuthoritativeDemoWorkspaceHeader/);
assert.doesNotMatch(source,/legacy-demo-app|\.\/seed|\.\/repo|localStorage/);
assert.doesNotMatch(source,/Number\(row\.(?:amount|source_amount|target_amount|difference)\)|toFixed\(4\)/);
const css=fs.readFileSync('index.html','utf8');
assert.match(css,/\.authoritative-wbs-review-table \.tbl\{min-width:1180px;table-layout:fixed;\}/);
assert.match(css,/\.authoritative-wbs-control-table \.tbl\{min-width:760px;table-layout:fixed;\}/);
console.log('authoritative WBS transition workspace: signed evidence only, no authority actions');
