import assert from'node:assert/strict';import test from'node:test';import{refreshAuthoritativeDimensionMappings,refreshAuthoritativeMappingCatalogs}from'../src/accounting-api.js';
const id=n=>`${String(n).padStart(8,'0')}-1111-4111-8111-111111111111`,hash=`sha256:${'a'.repeat(64)}`,config={baseUrl:'https://api.example.test',entityId:id(2),periodId:id(3),getAccessToken:async()=>'token-token-token-token'};
const row={rule_id:'project-one',scope_level:'PROJECT',project_ref:'project-1',property_ref:null,cost_code_ref:null,member_ref:null,ownership_requirement:'OPTIONAL',member_requirement:'OPTIONAL',capitalization_treatment:'CWIP',cwip_account_role:'CWIP',status:'ACTIVE',effective_from:'2026-01-01',effective_to:null,completion_date:null,pis_date:null,effective_for_period:true,mapping_hash:hash};
const data={schema_version:'AUTHORITATIVE_DIMENSION_MAPPING_CATALOG_V1',scope:{tenant_id:id(1),entity_id:id(2),company_code:'WBPA',period_id:id(3),period_code:'2026-07',period_start:'2026-07-01',period_end:'2026-07-31',period_status:'OPEN',currency:'USD'},approval:{settings_snapshot_id:id(4),settings_version:1,settings_hash:hash,dimension_mapping_snapshot_id:id(5),dimension_mapping_version:1,dimension_mapping_hash:hash,approval_status:'APPROVED',approved_by:'controller-a',approved_at:'2026-08-28T00:00:00.000Z'},population:{total_count:1,read_count:1,population_complete:true,population_hash:hash},mappings:[row],action_flags:{can_create_draft:false,can_review:false,can_approve:false,can_post:false}};
test('browser reads a complete exact-scope dimension-mapping catalog with no-store',async()=>{let request;const read=value=>refreshAuthoritativeDimensionMappings({config,fetcher:async(url,init)=>(request={url,init},{ok:true,json:async()=>({ok:true,data:value})})});assert.equal((await read(data)).ok,true);assert.match(request.url,/dimension-mappings\?periodId=/);assert.equal(request.init.cache,'no-store');for(const unsafe of [{...data,scope:{...data.scope,entity_id:id(9)}},{...data,population:{...data.population,population_complete:false}},{...data,mappings:[row,{...row}]},{...data,mappings:[{...row,effective_for_period:false}]},{...data,action_flags:{...data.action_flags,can_post:true}},{...data,approval:{...data.approval,approved_by:'Bearer unsafe-token'}},{...data,approval:{...data.approval,approved_at:'2026-08-28T00:00:00+00:00'}}])assert.equal((await read(unsafe)).code,'DIMENSION_MAPPING_PROTOCOL');});

test('combined Mapping Center read rejects catalogs from different approved Settings snapshots',async()=>{
 const reportRow={account_code:'1000',account_role:'CASH',account_class:'ASSET',account_type:'Cash',dimension_requirements:[],statement:'BS',report_row_code:'CASH',normal_balance:'DEBIT',contra:false,cash_flow_class:'OPERATING',effective_from:'2026-01-01',effective_to:null,status:'ACTIVE_FOR_PERIOD',mapping_hash:hash};
 const report={schema_version:'AUTHORITATIVE_REPORT_MAPPING_CATALOG_V1',scope:data.scope,approval:{settings_snapshot_id:id(4),settings_version:2,settings_hash:hash,report_mapping_snapshot_id:id(6),report_mapping_version:1,report_mapping_hash:hash,approval_status:'APPROVED',approved_by:'controller-a',approved_at:'2026-08-28T00:00:00.000Z'},population:{total_count:1,read_count:1,population_complete:true,population_hash:hash},mappings:[reportRow],action_flags:data.action_flags};
 const vendorRow={rule_id:'vendor-one',vendor_ref:'VENDOR-1',aliases:[],contract_keys:[],service_keys:[],treatment:'EXPENSE',payment_terms_days:30,recurring:false,duplicate_normalization:true,source_requirements:['invoice_no'],effective_from:'2026-01-01',effective_to:null,effective_for_period:true,mapping_hash:hash};
 const vendors={schema_version:'AUTHORITATIVE_VENDOR_TREATMENT_MAPPING_CATALOG_V1',scope:data.scope,approval:{settings_snapshot_id:id(4),settings_version:1,settings_hash:hash,vendor_treatment_snapshot_id:id(7),vendor_treatment_version:1,vendor_treatment_hash:hash,approval_status:'APPROVED',approved_by:'controller-a',approved_at:'2026-08-28T00:00:00.000Z'},policy:{default_treatment:'BLOCKED'},population:{total_count:1,read_count:1,population_complete:true,population_hash:hash},mappings:[vendorRow],action_flags:data.action_flags};
 const taxRow={code:'US-GROSS',rate:'0.0000',basis:'GROSS',recoverability:'NON_RECOVERABLE',expense_treatment:'EXPENSE',evidence_requirements:['invoice_no'],effective_from:'2026-01-01',effective_to:null,effective_for_period:true,mapping_hash:hash};
 const tax={schema_version:'AUTHORITATIVE_TAX_MAPPING_CATALOG_V1',scope:data.scope,approval:{settings_snapshot_id:id(4),settings_version:1,settings_hash:hash,tax_snapshot_id:id(8),tax_version:1,tax_hash:hash,approval_status:'APPROVED',approved_by:'controller-a',approved_at:'2026-08-28T00:00:00.000Z'},policy:{jurisdiction:'US',treatment:'GROSS',allocation_method:'STRAIGHT_LINE_DAILY',allocation_precision:'0.0001',coverage_start:'2026-07-01',coverage_end:'2026-07-31',residual_rule:'EXPENSE',expense_account_role:'EXPENSE',prepaid_account_role:'PREPAID',accrual_account_role:'ACCRUED_LIABILITY',effective_from:'2026-01-01',effective_to:null,policy_hash:hash},population:{total_count:1,read_count:1,population_complete:true,population_hash:hash},mappings:[taxRow],action_flags:data.action_flags};
 const intercompanyRow={company_code:'ICPARTNER',counterparty_entity_id:id(9),counterparty_approval_id:id(10),counterparty_approval_hash:hash,currency:'USD',dimension_requirements:[],due_to_account_role:'INTERCOMPANY_DUE_TO',due_from_account_role:'INTERCOMPANY_DUE_FROM',elimination_account_role:'INTERCOMPANY_ELIMINATION',effective_from:'2026-01-01',effective_to:null,effective_for_period:true,mapping_hash:hash};
 const intercompany={schema_version:'AUTHORITATIVE_INTERCOMPANY_MAPPING_CATALOG_V1',scope:data.scope,approval:{settings_snapshot_id:id(4),settings_version:1,settings_hash:hash,intercompany_snapshot_id:id(11),intercompany_version:1,intercompany_hash:hash,approval_status:'APPROVED',approved_by:'controller-a',approved_at:'2026-08-28T00:00:00.000Z'},policy:{enabled:true,clearing_account_role:'INTERCOMPANY_CLEARING',policy_hash:hash},population:{total_count:1,read_count:1,population_complete:true,population_hash:hash},mappings:[intercompanyRow],action_flags:data.action_flags};
 const loanRow={project_ref:'project-1',property_ref:null,asset_ref:null,effective_from:'2026-01-01',effective_to:null,effective_for_period:true,mapping_hash:hash};
 const loan={schema_version:'AUTHORITATIVE_LOAN_CAPITALIZATION_MAPPING_CATALOG_V1',scope:data.scope,approval:{settings_snapshot_id:id(4),settings_version:1,settings_hash:hash,loan_capitalization_snapshot_id:id(12),loan_capitalization_version:1,loan_capitalization_hash:hash,approval_status:'APPROVED',approved_by:'controller-a',approved_at:'2026-08-28T00:00:00.000Z'},policy:{currency:'USD',loan_purpose:'QUALIFYING_ASSET_ONLY',capitalization_start_policy:'WHEN_QUALIFYING_ACTIVITY_STARTS',suspension_policy:'PAUSE_DURING_EXTENDED_SUSPENSION',cessation_policy:'ON_READY_FOR_INTENDED_USE',eligible_interest_policy:'ACTUAL_INTEREST',eligible_fee_policy:'DIRECT_FEES_ONLY',expense_account_role:'EXPENSE',cwip_account_role:'CWIP',fixed_asset_account_role:'FIXED_ASSET',materiality_amount:'100.0000',required_evidence:['loan_agreement'],effective_from:'2026-01-01',effective_to:null,policy_hash:hash},population:{total_count:1,read_count:1,population_complete:true,population_hash:hash},mappings:[loanRow],action_flags:data.action_flags};
 const result=await refreshAuthoritativeMappingCatalogs({config,fetcher:async url=>({ok:true,json:async()=>({ok:true,data:url.includes('dimension-mappings')?data:url.includes('vendor-treatment-mappings')?vendors:url.includes('tax-mappings')?tax:url.includes('intercompany-mappings')?intercompany:url.includes('loan-capitalization-mappings')?loan:report})})});assert.equal(result.code,'MAPPING_CATALOG_SNAPSHOT_DRIFT');
});
