import assert from 'node:assert/strict';
import {refreshAuthoritativeAiVendorInvoiceNearDuplicates,retainAuthoritativeAiVendorInvoiceNearDuplicates} from '../src/accounting-api.js';

const entityId='11111111-1111-4111-8111-111111111111',periodId='22222222-2222-4222-8222-222222222222',priorPeriodId='77777777-7777-4777-8777-777777777777',hash=`sha256:${'a'.repeat(64)}`;
const config={baseUrl:'https://accounting.example',entityId,periodId,getAccessToken:async()=> 'a'.repeat(48)},flags={can_create_draft:false,can_review:false,can_approve:false,can_post:false};
const trace=(documentId,lineId,accountingPeriodId,invoiceNumber,invoiceDate)=>({source_document_id:documentId,source_document_line_id:lineId,source_payload_hash:hash,source_line_hash:hash,accounting_period_id:accountingPeriodId,invoice_number:invoiceNumber,invoice_date:invoiceDate,amount:'100.0000'});
const finding={schema_version:'AI_VENDOR_INVOICE_NEAR_DUPLICATE_FINDING_V1',finding_type:'VENDOR_INVOICE_NEAR_DUPLICATE',risk_level:'HIGH',rule_id:'AI_VENDOR_INVOICE_NORMALIZED_ID_AMOUNT_DATE_V1',entity_id:entityId,accounting_period_ids:[periodId,priorPeriodId],vendor_ref:'VENDOR-1',vendor_name:'Vendor One',currency:'USD',project_ref:null,property_ref:null,normalized_invoice_number:'INV1001',amount_variance:'0.0000',amount_variance_basis_points:0,date_gap_days:1,reason:'Two retained invoices have the same normalized identity.',suggested_action:'Compare both signed sources and payment status before any accounting action.',confidence:.97,owner_role:'CONTROLLER_REVIEW',due_basis:'BEFORE_PAYMENT_OR_PERIOD_CLOSE',required_human_fields:['duplicate_determination','source_document_comparison','goods_or_services_received','payment_status','resolution_reason'],source_trace:[trace('33333333-3333-4333-8333-333333333333','44444444-4444-4444-8444-444444444444',periodId,'INV-1001','2026-08-01'),trace('55555555-5555-4555-8555-555555555555','66666666-6666-4666-8666-666666666666',priorPeriodId,'INV 1001','2026-07-31')],policy_evidence:{schema_version:'AI_VENDOR_INVOICE_NEAR_DUPLICATE_POLICY_V1',setting_snapshot_id:'88888888-8888-4888-8888-888888888888',setting_snapshot_hash:hash,policy_version:1,maximum_date_gap_days:7,maximum_amount_variance_basis_points:100,maximum_absolute_amount_variance:'10.0000'},action_flags:flags};
const envelope={ok:true,data:{schema_version:'AI_VENDOR_INVOICE_NEAR_DUPLICATE_BATCH_V1',current_accounting_period_id:periodId,scanned_line_count:2,finding_count:1,findings:[finding],action_flags:flags}};
let request;
const read=await refreshAuthoritativeAiVendorInvoiceNearDuplicates({config,fetcher:async(url,options)=>(request={url,options},{ok:true,json:async()=>envelope})});
assert.equal(read.ok,true,JSON.stringify(read));assert.equal(read.data.findings[0].source_trace.length,2);assert.match(request.url,/vendor-invoice-near-duplicates/);assert.equal(request.options.cache,'no-store');
for(const changed of [{...finding,secret:'unsafe'},{...finding,source_trace:[finding.source_trace[0]]},{...finding,source_trace:[finding.source_trace[0],finding.source_trace[0]]},{...finding,action_flags:{...flags,can_post:true}}]){const result=await refreshAuthoritativeAiVendorInvoiceNearDuplicates({config,fetcher:async()=>({ok:true,json:async()=>({...envelope,data:{...envelope.data,findings:[changed]}})})});assert.equal(result.ok,false);}
const receipt={schema_version:'AI_VENDOR_INVOICE_NEAR_DUPLICATE_RUN_RECEIPT_V1',accounting_period_id:periodId,row_count:1,inserted_count:1,replayed_count:0,finding_ids:['99999999-9999-4999-8999-999999999999'],request_hash:hash,...flags,idempotent:false};
const retained=await retainAuthoritativeAiVendorInvoiceNearDuplicates({config,idempotencyKey:'near-duplicate-run-001',fetcher:async(url,options)=>(request={url,options},{ok:true,status:201,json:async()=>({ok:true,data:receipt})})});
assert.equal(retained.ok,true);assert.match(request.url,/vendor-invoice-near-duplicate-runs/);assert.equal(request.options.headers['idempotency-key'],'near-duplicate-run-001');assert.deepEqual(JSON.parse(request.options.body),{accounting_period_id:periodId,limit:500});
console.log('authoritative AI vendor near-duplicate client tests passed');
