import assert from 'node:assert/strict';
import test from 'node:test';
import {refreshAuthoritativeAiFullControllerScan} from '../src/accounting-api.js';
const entityId='22222222-2222-4222-8222-222222222222',periodId='33333333-3333-4333-8333-333333333333',actions={can_create_draft:false,can_review:false,can_approve:false,can_post:false};
const config={baseUrl:'https://accounting.example',entityId,periodId,getAccessToken:async()=> 'a'.repeat(48)};
const finding={entity_id:entityId,accounting_period_id:periodId,current_month_total:'500.0000',rule_id:'AI_VENDOR_MONTHLY_SPEND_V1',risk_level:'HIGH',reason:'Monthly total increased from 100 to 500.',suggested_action:'Review the complete retained invoice population and approved baseline.'};
const data={schema_version:'AI_FULL_CONTROLLER_SCAN_V1',entity_id:entityId,current_accounting_period_id:periodId,status:'COMPLETE',required_section_count:1,complete_section_count:1,finding_count:1,risk_summary:{high:1,medium:0,low:0},coverage_summary:{complete_section_count:1,unavailable_section_count:0,unavailable_sections:[]},sections:[{category:'VENDOR_MONTHLY_SPEND',status:'COMPLETE',schema_version:'AI_VENDOR_MONTHLY_SPEND_ANOMALY_BATCH_V1',finding_count:1,findings:[finding],action_flags:actions}],action_flags:actions};
test('browser reads one no-store authoritative Full Controller scan',async()=>{let request;const result=await refreshAuthoritativeAiFullControllerScan({config,fetcher:async(url,init)=>(request={url,init},{ok:true,json:async()=>({ok:true,data})})});assert.equal(result.ok,true);assert.match(request.url,/full-controller-scan/);assert.equal(request.init.method,'GET');assert.equal(request.init.cache,'no-store');assert.equal(result.data.finding_count,1);assert.equal(result.data.sections[0].findings[0].current_month_total,'500.0000');});
test('browser rejects secret expansion, action authority, false completeness, forged totals, and unexplained findings',async()=>{for(const unsafe of [{...data,action_flags:{...actions,can_post:true}},{...data,sections:[{...data.sections[0],findings:[{...finding,raw_payload:'secret'}]}]},{...data,status:'COMPLETE',complete_section_count:0},{...data,risk_summary:{high:0,medium:0,low:0}},{...data,coverage_summary:{complete_section_count:0,unavailable_section_count:1,unavailable_sections:[{category:'FORGED',error_code:'FORGED'}]}},{...data,sections:[{...data.sections[0],findings:[{...finding,rule_id:'INVALID rule'}]}]},{...data,sections:[{...data.sections[0],findings:[{...finding,reason:'short'}]}]}]){const result=await refreshAuthoritativeAiFullControllerScan({config,fetcher:async()=>({ok:true,json:async()=>({ok:true,data:unsafe})})});assert.equal(result.ok,false);assert.equal(result.code,'AI_FULL_CONTROLLER_SCAN_PROTOCOL');}});
