import assert from 'node:assert/strict';
import {refreshAuthoritativeAiWbsPayableDraftProposals,reviewAuthoritativeAiWbsPayableDraftProposal} from '../src/accounting-api.js';

const entityId='11111111-1111-4111-8111-111111111111';
const config={entityId,periodId:'33333333-3333-4333-8333-333333333333',baseUrl:'https://accounting.example',getAccessToken:async()=> 'a'.repeat(48)};
const proposal={ai_wbs_payable_draft_proposal_id:'22222222-2222-4222-8222-222222222222',wbs_payable_review_evidence_id:'33333333-3333-4333-8333-333333333333',source_document_id:'44444444-4444-4444-8444-444444444444',staging_item_id:'55555555-5555-4555-8555-555555555555',mapping_snapshot_id:'66666666-6666-4666-8666-666666666666',model_id:'REFS_RULE_ASSIST_V1',prompt_version:'WBS_PAYABLE_V1',proposal_lines:[{line_no:1,account_code:'610000',debit_amount:'89.1250',credit_amount:'0.0000',source:'REVIEWED_MAPPING'},{line_no:2,account_code:'291001',debit_amount:'0.0000',credit_amount:'89.1250',source:'REVIEWED_MAPPING'}],proposal_hash:`sha256:${'1'.repeat(64)}`,created_at:'2026-08-19T00:00:00.000Z',decision:null,decision_reason:null,reviewed_by:null,reviewed_at:null,can_create_draft:false,can_submit:false,can_review:false,can_approve:false,can_post:false};

let readCall;
const read=await refreshAuthoritativeAiWbsPayableDraftProposals({config,fetcher:async(url,options)=>{readCall={url,options};return {ok:true,json:async()=>({ok:true,data:[proposal]})};}});
assert.equal(read.ok,true);assert.equal(read.rows[0].proposal_lines.length,2);assert.match(readCall.url,/\/ai\/wbs-payable-draft-proposals\?limit=50$/);assert.equal(readCall.options.method,'GET');assert.equal(readCall.options.cache,'no-store');assert.equal(readCall.options.credentials,'include');assert.equal('body' in readCall.options,false);
const invalidRead=async row=>refreshAuthoritativeAiWbsPayableDraftProposals({config,fetcher:async()=>({ok:true,json:async()=>({ok:true,data:[row]})})});
for(const invalid of [{...proposal,can_post:true},{...proposal,unexpected:'secret'},{...proposal,proposal_lines:[proposal.proposal_lines[0],{...proposal.proposal_lines[1],credit_amount:'88.1250'}]},{...proposal,proposal_lines:[proposal.proposal_lines[0],{...proposal.proposal_lines[1],account_code:'bad code'}]}])assert.equal((await invalidRead(invalid)).code,'AI_WBS_PAYABLE_PROPOSAL_PROTOCOL');

const reason='The balanced lines agree with the retained payable review evidence.';
const receipt={schema_version:'AI_WBS_PAYABLE_DRAFT_PROPOSAL_REVIEW_V1',ai_wbs_payable_draft_proposal_review_id:'77777777-7777-4777-8777-777777777777',ai_wbs_payable_draft_proposal_id:proposal.ai_wbs_payable_draft_proposal_id,wbs_payable_review_evidence_id:proposal.wbs_payable_review_evidence_id,decision:'ACCEPTED',can_create_draft:false,can_submit:false,can_review:false,can_approve:false,can_post:false,idempotent:false};
let reviewCall;
const reviewed=await reviewAuthoritativeAiWbsPayableDraftProposal({config,proposal,decision:'ACCEPTED',reason,idempotencyKey:'ai-wbs-payable-review:stable-001',fetcher:async(url,options)=>{reviewCall={url,options};return {ok:true,status:201,json:async()=>({ok:true,data:receipt})};}});
assert.equal(reviewed.ok,true);assert.equal(reviewed.data.can_post,false);assert.match(reviewCall.url,new RegExp(`/ai/wbs-payable-draft-proposals/${proposal.ai_wbs_payable_draft_proposal_id}/reviews$`));assert.equal(reviewCall.options.method,'POST');assert.equal(reviewCall.options.cache,'no-store');assert.equal(reviewCall.options.headers['idempotency-key'],'ai-wbs-payable-review:stable-001');assert.deepEqual(JSON.parse(reviewCall.options.body),{decision:'ACCEPTED',reason});
assert.equal((await reviewAuthoritativeAiWbsPayableDraftProposal({config,proposal,decision:'POSTED',reason,idempotencyKey:'ai-wbs-payable-review:stable-002',fetcher:async()=>{throw new Error('must not fetch');}})).code,'AI_WBS_PAYABLE_PROPOSAL_REVIEW_COMMAND_INVALID');
assert.equal((await reviewAuthoritativeAiWbsPayableDraftProposal({config,proposal,decision:'ACCEPTED',reason,idempotencyKey:'ai-wbs-payable-review:stable-003',fetcher:async()=>({ok:true,status:201,json:async()=>({ok:true,data:{...receipt,can_create_draft:true}})})})).code,'AI_WBS_PAYABLE_PROPOSAL_REVIEW_PROTOCOL');
assert.equal((await reviewAuthoritativeAiWbsPayableDraftProposal({config,proposal:{...proposal,decision:'REJECTED',decision_reason:reason,reviewed_by:'maker-b',reviewed_at:'2026-08-19T01:00:00.000Z'},decision:'ACCEPTED',reason,idempotencyKey:'ai-wbs-payable-review:stable-004',fetcher:async()=>{throw new Error('must not fetch');}})).code,'AI_WBS_PAYABLE_PROPOSAL_REVIEW_COMMAND_INVALID');
console.log('authoritative AI JE API client: balanced payable proposals remain evidence-only through human decision');
