import assert from 'node:assert/strict';
import {proposeAuthoritativeAiInvoiceCapitalization,refreshAuthoritativeAiInvoiceCapitalizationEvidence,refreshAuthoritativeAiInvoiceCapitalizationProposals} from '../src/accounting-api.js';

const entityId='11111111-1111-4111-8111-111111111111',periodId='33333333-3333-4333-8333-333333333333',evidenceId='44444444-4444-4444-8444-444444444444',documentId='55555555-5555-4555-8555-555555555555',lineId='66666666-6666-4666-8666-666666666666',proposalId='77777777-7777-4777-8777-777777777777',policyId='88888888-8888-4888-8888-888888888888',hash=`sha256:${'a'.repeat(64)}`,config={entityId,periodId,baseUrl:'https://accounting.example',getAccessToken:async()=> 'a'.repeat(48)};
const evidence={classification_evidence_id:evidenceId,accounting_period_id:periodId,source_document_id:documentId,source_document_line_id:lineId,source_payload_hash:hash,source_line_hash:hash,classifier_version:'AI_INVOICE_ACCOUNTING_CLASSIFICATION_V2',classification:'CAPITALIZATION_REVIEW',reason:'Approved policy requires construction cost review.',confidence:0.99,required_human_fields:['capital_account'],rule_id:'AI_CAPITALIZATION_POLICY_V1',policy_snapshot_id:policyId,policy_snapshot_hash:hash,classification_hash:hash,status:'REVIEW_REQUIRED',created_at:'2026-08-19T10:00:00.000Z',can_create_draft:false,can_review:false,can_approve:false,can_post:false};
const proposal={ai_invoice_capitalization_proposal_id:proposalId,classification_evidence_id:evidenceId,classification_hash:hash,source_document_id:documentId,source_document_line_id:lineId,source_payload_hash:hash,source_line_hash:hash,accounting_period_id:periodId,capitalization_treatment:'CWIP',asset_account_code:'150100',liability_account_code:'291001',asset_class:'CONSTRUCTION_IN_PROGRESS',currency:'USD',amount:'25000.0000',member_trace:{project_ref:'PROJECT-1',property_ref:'PROPERTY-1',allocation_basis:'SOURCE_DIMENSIONED'},placed_in_service_date:null,useful_life_months:null,rule_id:'AI_CAPITALIZATION_POLICY_V1',policy_snapshot_id:policyId,policy_snapshot_hash:hash,confidence:0.99,proposal_reason:'Controller verified policy eligibility.',proposal_hash:hash,status:'PROPOSED',created_at:'2026-08-19T10:01:00.000Z',can_create_draft:false,can_review:false,can_approve:false,can_post:false};
const evidenceRead=await refreshAuthoritativeAiInvoiceCapitalizationEvidence({config,fetcher:async(url,options)=>{assert.match(url,/invoice-capitalization\/evidence\?periodId=/);assert.equal(options.cache,'no-store');return {ok:true,json:async()=>({ok:true,data:[evidence]})};}});assert.equal(evidenceRead.ok,true);
const proposalRead=await refreshAuthoritativeAiInvoiceCapitalizationProposals({config,fetcher:async(url,options)=>{assert.match(url,/invoice-capitalization\/proposals\?limit=50$/);assert.equal(options.method,'GET');return {ok:true,json:async()=>({ok:true,data:[proposal]})};}});assert.equal(proposalRead.ok,true);assert.equal(proposalRead.rows[0].can_post,false);
for(const flag of ['can_create_draft','can_review','can_approve','can_post'])assert.equal((await refreshAuthoritativeAiInvoiceCapitalizationProposals({config,fetcher:async()=>({ok:true,json:async()=>({ok:true,data:[{...proposal,[flag]:true}]})})})).code,'AI_INVOICE_CAPITALIZATION_PROPOSAL_PROTOCOL');
const receipt={schema_version:'AI_INVOICE_CAPITALIZATION_PROPOSAL_V1',...proposal,idempotent:false};delete receipt.proposal_reason;delete receipt.proposal_hash;delete receipt.created_at;
let call;const proposed=await proposeAuthoritativeAiInvoiceCapitalization({config,evidence,capitalizationTreatment:'CWIP',assetAccountCode:'150100',liabilityAccountCode:'291001',assetClass:'CONSTRUCTION_IN_PROGRESS',memberTrace:{project_ref:'PROJECT-1',property_ref:'PROPERTY-1',allocation_basis:'SOURCE_DIMENSIONED'},reason:'Controller verified policy eligibility.',idempotencyKey:'invoice-capitalization-001',fetcher:async(url,options)=>{call={url,options};return {ok:true,status:201,json:async()=>({ok:true,data:receipt})};}});assert.equal(proposed.ok,true);assert.equal(proposed.data.can_create_draft,false);assert.equal(call.options.headers['idempotency-key'],'invoice-capitalization-001');
assert.equal((await proposeAuthoritativeAiInvoiceCapitalization({config,evidence,capitalizationTreatment:'FIXED_ASSET',assetAccountCode:'150100',liabilityAccountCode:'291001',assetClass:'BUILDING',memberTrace:{project_ref:'PROJECT-1',property_ref:'PROPERTY-1',allocation_basis:'SOURCE_DIMENSIONED'},reason:'Controller verified policy eligibility.',idempotencyKey:'invoice-capitalization-002',fetcher:async()=>{throw new Error('must not fetch');}})).code,'AI_INVOICE_CAPITALIZATION_PROPOSAL_COMMAND_INVALID');
console.log('authoritative capitalization client: policy-bound no-action proposals only');
