import assert from 'node:assert/strict';
import React from 'react';
import {renderToStaticMarkup} from 'react-dom/server';
import {readFileSync} from 'node:fs';
import {AuthoritativeReceiptsWorkspace,ReceiptRegisterTable,receiptPage} from '../src/authoritative-receipts-workspace.jsx';
const markup=renderToStaticMarkup(<AuthoritativeReceiptsWorkspace config={{baseUrl:'https://fixture.example',tenantId:'11111111-1111-4111-8111-111111111111',entityId:'22222222-2222-4222-8222-222222222222',periodId:'33333333-3333-4333-8333-333333333333'}}/>);
assert.match(markup,/Receipts/);assert.match(markup,/Read-only queue/);assert.match(markup,/Loading Receipts/);assert.match(markup,/immutable receipt and attachment evidence/);assert.doesNotMatch(markup,/Upload receipt|Run OCR|Review receipt|Add to books|Promote payment/);
assert.match(markup,/aria-label="Receipts workspace"/);assert.doesNotMatch(markup,/undefined workspace/);
assert.match(markup,/All periods for this company/);assert.match(markup,/selected workflow period does not filter this queue/);
const rows=Array.from({length:1237},(_,index)=>({receipt_id:`fixture-${index}`,attachment_name:`Receipt ${index}`,media_type:'text/csv',size_bytes:1,storage_version:'test-only',content_hash:'retained-fixture-hash',source_document_revision:1,source_payload_hash:'retained-source-hash',review_status:'FOR_REVIEW',reviewed_by:null,extracted_facts:{document_no:`Document ${index}`,source_system:'WBS',source_module:'payable',accounting_date:index%2?'2026-01-31':'2026-06-30',gross_amount:'1.0000',currency:'USD',document_type:'WBS_TEST_PAYABLE',line_count:1}}));
assert.deepEqual(receiptPage(rows,0).rows,rows.slice(0,50));assert.equal(receiptPage(rows,1).start,50);assert.equal(receiptPage(rows,999).page,24);assert.equal(receiptPage(rows,24).rows.length,37);assert.equal(receiptPage(rows,-1).page,0);
const first=renderToStaticMarkup(<ReceiptRegisterTable rows={rows}/>),second=renderToStaticMarkup(<ReceiptRegisterTable rows={rows} page={1}/>),last=renderToStaticMarkup(<ReceiptRegisterTable rows={rows} page={999}/>);
assert.equal((first.match(/>Open receipt</g)||[]).length,50);assert.equal((second.match(/>Open receipt</g)||[]).length,50);assert.equal((last.match(/>Open receipt</g)||[]).length,37);
assert.match(first,/1–50 of 1237 matching receipts · Page 1 of 25/);assert.match(second,/51–100 of 1237 matching receipts · Page 2 of 25/);assert.match(last,/1201–1237 of 1237 matching receipts · Page 25 of 25/);
assert.doesNotMatch(first,/id="receipt-fixture-50"/);assert.match(second,/id="receipt-fixture-50"/);assert.match(first,/2026-01-31/);assert.match(first,/2026-06-30/,'own dates must remain visible across periods');
const filtered=renderToStaticMarkup(<ReceiptRegisterTable rows={[rows[1200]]} page={24}/>);assert.match(filtered,/1–1 of 1 matching receipts · Page 1 of 1/);assert.match(filtered,/receipt-fixture-1200/,'filtering the full API population must find off-page receipts');
const code=readFileSync('src/authoritative-receipts-workspace.jsx','utf8');
assert.match(code,/area="Receipt detail"/);assert.match(code,/setQuery\(event.target.value\);setPage\(0\)/);assert.match(code,/token!==requestVersion.current/,'late company/queue detail reads must not replace current evidence');
assert.match(code,/document.getElementById\(returnButton.current\)\?\.focus\(\)/,'Back restores the newly mounted stable receipt button, not a detached DOM node');
assert.match(code,/document.getElementById\(sourceButton.current\)\?\.focus\(\)/);
console.log('Receipts: truthful all-period scope, named regions, bounded 1237-row pages, search and stable return-focus contracts passed');
