import test from 'node:test';
import assert from 'node:assert/strict';
import {closeAuthoritativePeriod,periodCloseCommandIdempotencyKey,periodReopenCommandIdempotencyKey,refreshAuthoritativePeriodCloseHistory,refreshAuthoritativePeriodCloseReadiness,refreshAuthoritativePeriodReopenHistory,reopenAuthoritativePeriod} from '../src/accounting-api.js';

const id=n=>`${String(n).padStart(8,'0')}-0000-4000-8000-${String(n).padStart(12,'0')}`;
const entityId=id(1),periodId=id(2),hash=`sha256:${'a'.repeat(64)}`;
const config={baseUrl:'https://accounting.example',entityId,periodId,getAccessToken:async()=>'a'.repeat(48)};
const readiness={schema_version:'PERIOD_CLOSE_READINESS_V1',tenant_id:id(9),entity_id:entityId,period_id:periodId,period_code:'2026-08',period_version:'3',period_status:'OPEN',settings_snapshot_id:id(4),settings_hash:hash,close_policy_snapshot_id:id(5),close_policy_hash:hash,financial_statement_snapshot_id:id(6),financial_statement_snapshot_hash:hash,ledger_evidence_hash:hash,unposted_journal_count:0,admitted_source_blocker_count:0,blockers:[],ready:true,can_close:true,readiness_hash:hash};

test('browser reads exact no-store period close readiness',async()=>{
  let request;
  const result=await refreshAuthoritativePeriodCloseReadiness({config,fetcher:async(url,init)=>(request={url,init},{ok:true,json:async()=>({ok:true,data:readiness})})});
  assert.equal(result.ok,true);assert.match(request.url,/periods\/.+\/close-readiness$/);assert.equal(request.init.method,'GET');assert.equal(request.init.cache,'no-store');assert.equal(result.data.readiness_hash,hash);
  for(const unsafe of [{...readiness,entity_id:id(7)},{...readiness,ready:false},{...readiness,debug:true}]){const rejected=await refreshAuthoritativePeriodCloseReadiness({config,fetcher:async()=>({ok:true,json:async()=>({ok:true,data:unsafe})})});assert.equal(rejected.code,'PERIOD_CLOSE_READINESS_PROTOCOL');}
});

test('close command binds strong version, readiness hash, reason and idempotency key',async()=>{
  let request;const receipt={schema_version:'PERIOD_CLOSE_RECEIPT_V2',period_id:periodId,status:'CLOSED',version:4,readiness_hash:hash,closed_by:'auth0|controller',idempotent:false};
  const reason='Controller verified all retained close evidence.',key=await periodCloseCommandIdempotencyKey({config,readiness,reason}),replayKey=await periodCloseCommandIdempotencyKey({config,readiness,reason});assert.equal(key,replayKey);assert.match(key,/^period-close:[0-9a-f]{64}$/);
  const result=await closeAuthoritativePeriod({config,readiness,reason,idempotencyKey:key,fetcher:async(url,init)=>(request={url,init},{ok:true,json:async()=>({ok:true,data:receipt})})});
  assert.equal(result.ok,true);assert.equal(request.init.method,'POST');assert.equal(request.init.cache,'no-store');assert.equal(request.init.headers['if-match'],'"3"');assert.equal(request.init.headers['idempotency-key'],key);assert.deepEqual(JSON.parse(request.init.body),{expectedReadinessHash:hash,reason});
  const stale=await closeAuthoritativePeriod({config,readiness:{...readiness,ready:false,can_close:false,blockers:[{code:'UNPOSTED_JOURNALS',count:1}]},reason:'Controller verified all retained close evidence.',idempotencyKey:'period-close-key-0001',fetcher:async()=>{throw new Error('must not call network')}});assert.equal(stale.code,'PERIOD_CLOSE_COMMAND_INVALID');
  const forged=await closeAuthoritativePeriod({config,readiness,reason:'Controller verified all retained close evidence.',idempotencyKey:'period-close-key-0001',fetcher:async()=>({ok:true,json:async()=>({ok:true,data:{...receipt,readiness_hash:`sha256:${'b'.repeat(64)}`}})})});assert.equal(forged.code,'PERIOD_CLOSE_PROTOCOL');
});

test('browser reads closed period history without raw reason or command identity',async()=>{const auditId=id(10),item={schema_version:'PERIOD_CLOSE_HISTORY_ITEM_V1',audit_event_id:auditId,period_id:periodId,period_code:'2026-08',version:'4',status:'CLOSED',recorded_at:'2026-08-24T12:00:00.000Z',closed_by:'auth0|controller',readiness_hash:hash,settings_snapshot_id:id(4),settings_hash:hash,close_policy_snapshot_id:id(5),close_policy_hash:hash,financial_statement_snapshot_id:id(6),financial_statement_snapshot_hash:hash,ledger_evidence_hash:hash,reason_hash:hash,command_reference_hash:hash,outbox_event_id:id(11),outbox_payload_hash:hash,delivery:{status:'PENDING',attempt_count:0,published_at:null},integrity_verified:true},page={schema_version:'PERIOD_CLOSE_HISTORY_PAGE_V1',scope:{tenant_id:id(9),entity_id:entityId,period_id:periodId},total_count:1,read_count:1,items:[item],has_more:false,next_cursor:null,redaction:{reason_hashed:true,command_reference_hashed:true,credential_shaped_actor_redacted:true},action_flags:{can_create_draft:false,can_review:false,can_approve:false,can_post:false}};let request;const result=await refreshAuthoritativePeriodCloseHistory({config,fetcher:async(url,init)=>(request={url,init},{ok:true,json:async()=>({ok:true,data:page})})});assert.equal(result.ok,true);assert.match(request.url,/close-history\?limit=25$/);assert.equal(request.init.cache,'no-store');assert.equal(result.data.items[0].reason,undefined);for(const unsafe of [{...page,action_flags:{...page.action_flags,can_post:true}},{...page,items:[{...item,closed_by:'sk-abcdefgh12345678'}]}]){const rejected=await refreshAuthoritativePeriodCloseHistory({config,fetcher:async()=>({ok:true,json:async()=>({ok:true,data:unsafe})})});assert.equal(rejected.code,'PERIOD_CLOSE_HISTORY_PROTOCOL');}});

test('browser reads exact prior-close-bound reopen history without raw reason or command identity',async()=>{const item={schema_version:'PERIOD_REOPEN_HISTORY_ITEM_V1',audit_event_id:id(12),period_id:periodId,period_code:'2026-08',version:'5',status:'OPEN',recorded_at:'2026-08-25T12:00:00.000Z',reopened_by:'auth0|reopener',reopened_by_hash:`sha256:${'b'.repeat(64)}`,prior_close_audit_event_id:id(10),prior_readiness_hash:hash,prior_closed_by:'auth0|controller',prior_closed_by_hash:`sha256:${'c'.repeat(64)}`,prior_closed_at:'2026-08-24T12:00:00.000Z',reason_hash:hash,command_reference_hash:hash,outbox_event_id:id(13),outbox_payload_hash:hash,delivery:{status:'PENDING',attempt_count:0,published_at:null},integrity_verified:true,separation_verified:true},page={schema_version:'PERIOD_REOPEN_HISTORY_PAGE_V1',scope:{tenant_id:id(9),entity_id:entityId,period_id:periodId},total_count:1,read_count:1,items:[item],has_more:false,next_cursor:null,redaction:{reason_hashed:true,command_reference_hashed:true,credential_shaped_actor_redacted:true},action_flags:{can_create_draft:false,can_review:false,can_approve:false,can_post:false}};let request;const result=await refreshAuthoritativePeriodReopenHistory({config,fetcher:async(url,init)=>(request={url,init},{ok:true,json:async()=>({ok:true,data:page})})});assert.equal(result.ok,true);assert.match(request.url,/reopen-history\?limit=25$/);assert.equal(request.init.cache,'no-store');assert.equal(result.data.items[0].reason,undefined);for(const unsafe of [{...page,action_flags:{...page.action_flags,can_post:true}},{...page,items:[{...item,prior_closed_by_hash:item.reopened_by_hash}]},{...page,items:[{...item,separation_verified:false}]},{...page,items:[{...item,reopened_by:'sk-abcdefgh12345678'}]}]){const rejected=await refreshAuthoritativePeriodReopenHistory({config,fetcher:async()=>({ok:true,json:async()=>({ok:true,data:unsafe})})});assert.equal(rejected.code,'PERIOD_REOPEN_HISTORY_PROTOCOL');}});

test('browser period reopen binds the current CLOSED version to its latest retained close evidence',async()=>{const auditId=id(10),closeEvidence={schema_version:'PERIOD_CLOSE_HISTORY_ITEM_V1',audit_event_id:auditId,period_id:periodId,period_code:'2026-08',version:'4',status:'CLOSED',recorded_at:'2026-08-24T12:00:00.000Z',closed_by:'auth0|controller',readiness_hash:hash,settings_snapshot_id:id(4),settings_hash:hash,close_policy_snapshot_id:id(5),close_policy_hash:hash,financial_statement_snapshot_id:id(6),financial_statement_snapshot_hash:hash,ledger_evidence_hash:hash,reason_hash:hash,command_reference_hash:hash,outbox_event_id:id(11),outbox_payload_hash:hash,delivery:{status:'PENDING',attempt_count:0,published_at:null},integrity_verified:true},closedReadiness={...readiness,period_version:'4',period_status:'CLOSED',ready:false,can_close:false,blockers:[{code:'PERIOD_NOT_OPEN',count:1}],readiness_hash:`sha256:${'b'.repeat(64)}`},reason='Independent controller approved reopening this period.',receipt={schema_version:'PERIOD_REOPEN_RECEIPT_V1',period_id:periodId,version:'5',status:'OPEN',prior_close_audit_event_id:auditId,prior_readiness_hash:hash,reopened_by:'auth0|independent-reopener',idempotent:false};let request;const key=await periodReopenCommandIdempotencyKey({config,readiness:closedReadiness,closeEvidence,reason});assert.match(key,/^period-reopen:[0-9a-f]{64}$/);const result=await reopenAuthoritativePeriod({config,readiness:closedReadiness,closeEvidence,reason,idempotencyKey:key,fetcher:async(url,init)=>(request={url,init},{ok:true,json:async()=>({ok:true,data:receipt})})});assert.equal(result.ok,true);assert.match(request.url,/periods\/.+\/reopen$/);assert.equal(request.init.headers['if-match'],'"4"');assert.equal(request.init.headers['idempotency-key'],key);assert.deepEqual(JSON.parse(request.init.body),{expectedCloseAuditEventId:auditId,expectedReadinessHash:hash,reason});for(const input of [{readiness:{...closedReadiness,period_status:'OPEN'}},{closeEvidence:{...closeEvidence,version:'3'}}]){const rejected=await reopenAuthoritativePeriod({config,readiness:input.readiness||closedReadiness,closeEvidence:input.closeEvidence||closeEvidence,reason,idempotencyKey:key,fetcher:async()=>{throw new Error('must not call network')}});assert.equal(rejected.code,'PERIOD_REOPEN_COMMAND_INVALID');}const forged=await reopenAuthoritativePeriod({config,readiness:closedReadiness,closeEvidence,reason,idempotencyKey:key,fetcher:async()=>({ok:true,json:async()=>({ok:true,data:{...receipt,reopened_by:'Bearer unsafe-token'}})})});assert.equal(forged.code,'PERIOD_REOPEN_PROTOCOL');});
