import {matchesAssetMovementJournal} from '../src/asset-movement-journal-contract.js';
import {movementFixture} from '../server/tests/fixtures/fixed-asset-movement.mjs';
import test from 'node:test';
import assert from 'node:assert/strict';
import {refreshAuthoritativeFixedAssets,refreshAuthoritativeFixedAssetMovements} from '../src/accounting-api.js';
import {validateFixedAssetRegister} from '../src/fixed-asset-register-contract.js';
const id=n=>String(n).padStart(8,'0')+'-1111-4111-8111-'+String(n).padStart(12,'0');
const config={baseUrl:'https://accounting.example',entityId:id(1),tenantId:id(2),getAccessToken:async()=> 'a'.repeat(48)},asOfDate='2026-07-31';
export const asset={fixed_asset_register_evidence_id:id(3),tenant_id:id(2),entity_id:id(1),asset_tag:'A-001',asset_class:'Equipment',currency:'USD',cost_basis:'25000.0000',salvage_value:'0.0000',posted_cost_balance:'25000.0000',accumulated_depreciation:'2000.0000',accumulated_impairment:'5000.0000',net_book_value:'18000.0000',as_of_date:asOfDate,status:'ACTIVE',placed_in_service_date:'2026-07-02',useful_life_months:60,depreciation_method:'STRAIGHT_LINE',depreciation_convention:'FULL_MONTH',asset_account_code:'150100',accumulated_depreciation_account_code:'159100',depreciation_expense_account_code:'680100',capitalization_proposal_id:id(4),source_document_id:id(5),source_payload_hash:'sha256:'+'a'.repeat(64),register_evidence_hash:'sha256:'+'b'.repeat(64),reviewed_by:'reviewer',reviewed_at:'2026-07-02T12:00:00Z',member_trace:{project_ref:null,property_ref:null,allocation_basis:'DIRECT'},posted_ledger_line_count:6,disposal_journal_entry_id:null,disposal_binding_id:null,fixed_asset_disposal_evidence_id:null,disposal_source_document_id:null,disposal_date:null,disposal_source_payload_hash:null,disposal_source_document_version:null,disposal_source_link_id:null};
const snapshot=(rows=[asset],next_cursor=null)=>({schema_version:'FIXED_ASSET_REGISTER_READ_V2',tenant_id:id(2),entity_id:id(1),as_of_date:asOfDate,basis:'POSTED_PRIMARY_LEDGER',population_basis:'PLACED_IN_SERVICE_DATE',rows,next_cursor});
const reply=data=>({ok:true,status:200,json:async()=>({ok:true,data})});
test('asset client uses authenticated scoped dated reads and preserves decimal precision',async()=>{const seen=[];const result=await refreshAuthoritativeFixedAssets({config,asOfDate,fetcher:async(url,options)=>{seen.push({url,options});return reply(snapshot());}});assert.equal(result.ok,true);assert.equal(result.data.rows[0].net_book_value,'18000.0000');assert.match(seen[0].url,/asOfDate=2026-07-31/);assert.equal(seen[0].options.cache,'no-store');assert.ok(seen[0].options.headers.authorization);assert.equal(seen[0].options.body,undefined);});
test('asset client rejects crossed scope, date, malformed amounts and incorrect arithmetic',()=>{for(const patch of [{entity_id:id(9)},{as_of_date:'2026-08-01'},{net_book_value:18000},{net_book_value:'18001.0000'},{status:'DISPOSED_REVIEWED'},{source_payload_hash:'bad'}])assert.equal(validateFixedAssetRegister(snapshot([{...asset,...patch}]),{entityId:id(1),tenantId:id(2),asOfDate}),null);const large={...asset,cost_basis:'9999999999999999.9999',posted_cost_balance:'9999999999999999.9999',accumulated_depreciation:'0.0001',accumulated_impairment:'0.0000',net_book_value:'9999999999999999.9998'};assert.ok(validateFixedAssetRegister(snapshot([large]),{entityId:id(1),tenantId:id(2),asOfDate}));});
test('asset pages accept opaque cursors and reject duplicates, ordering errors and raw UUID cursors',()=>{const second={...asset,fixed_asset_register_evidence_id:id(6)};assert.ok(validateFixedAssetRegister(snapshot([asset,second],'e30=.'+'a'.repeat(64)),{entityId:id(1),tenantId:id(2),asOfDate,limit:2}));for(const value of [snapshot([asset,asset]),snapshot([second,asset]),snapshot([asset],id(6))])assert.equal(validateFixedAssetRegister(value,{entityId:id(1),tenantId:id(2),asOfDate,limit:2}),null);assert.equal(validateFixedAssetRegister(snapshot([asset]),{entityId:id(1),tenantId:id(2),asOfDate,after:id(6)}),null);});
test('asset detail binds exact requested identity and rejects absent or wrong data',async()=>{const result=await refreshAuthoritativeFixedAssets({config,asOfDate,assetId:id(6),fetcher:async()=>reply(snapshot())});assert.equal(result.ok,false);assert.equal(result.code,'FIXED_ASSET_PROTOCOL');});
test('invalid dates and missing sessions do not issue asset network requests',async()=>{let calls=0;const fetcher=async()=>{calls++;return reply(snapshot());};assert.equal((await refreshAuthoritativeFixedAssets({config,asOfDate:'2026-02-30',fetcher})).ok,false);assert.equal((await refreshAuthoritativeFixedAssets({config:{...config,getAccessToken:async()=>null},asOfDate,fetcher})).ok,false);assert.equal(calls,0);});

test('asset response rejects missing trusted tenant and closed-state corruption',()=>{assert.equal(validateFixedAssetRegister(snapshot(),{entityId:id(1),asOfDate}),null);for(const patch of [{member_trace:[]},{unexpected:true},{disposal_source_payload_hash:'sha256:'+'c'.repeat(64)},{status:'REGISTERED',posted_ledger_line_count:0}])assert.equal(validateFixedAssetRegister(snapshot([{...asset,...patch}]),{tenantId:id(2),entityId:id(1),asOfDate}),null);});

test('asset movement client preserves exact ledger identities and blocks cross-asset evidence',async()=>{const data=movementFixture({tenantId:id(2),entityId:id(1),assetId:id(3),asOfDate});let seen;const result=await refreshAuthoritativeFixedAssetMovements({config,assetId:id(3),asOfDate,fetcher:async(url,options)=>{seen={url,options};return reply(data);}});assert.equal(result.ok,true);assert.match(seen.url,/register.*movements/);assert.equal(seen.options.body,undefined);assert.equal(result.data.rows[0].source_binding_status,'BLOCKED_MISSING_EXACT_SOURCE_BINDING');assert.equal((await refreshAuthoritativeFixedAssetMovements({config,assetId:id(4),asOfDate,fetcher:async()=>reply(data)})).code,'FIXED_ASSET_PROTOCOL');});

test('asset journal drill rejects drift outside the selected line and changed journal identity',()=>{
 const row=movementFixture({tenantId:id(2),entityId:id(1),assetId:id(3),asOfDate}).rows[0];
 const journal={...row,status:'POSTED',lines:[{...row,source_document_ids:[]},{journal_line_id:id(91),ledger_line_id:id(92),account_code:'300100',debit_amount:'0.0000',credit_amount:'25000.0000',dimensions:{},source_document_ids:[]}]};
 assert.equal(matchesAssetMovementJournal(journal,row),true);
 for(const field of ['journal_number','journal_date'])assert.equal(matchesAssetMovementJournal({...journal,[field]:'changed'},row),false);
 assert.equal(matchesAssetMovementJournal({...journal,lines:journal.lines.slice(0,1)},row),false);
 assert.equal(matchesAssetMovementJournal({...journal,lines:[journal.lines[0],{...journal.lines[1],credit_amount:'25001.0000'}]},row),false);
 assert.equal(matchesAssetMovementJournal({...journal,lines:[{...journal.lines[0],dimensions:{fixed_asset_register_evidence_id:id(99)}},journal.lines[1]]},row),false);
 assert.equal(matchesAssetMovementJournal({...journal,lines:[journal.lines[0],{...journal.lines[1],credit_amount:'-25000.0000'}]},row),false);
});
