import test from 'node:test';
import assert from 'node:assert/strict';
import {createAuthoritativeInsuranceAmortizationDraft,refreshAuthoritativeInsurancePrepaidAmortization,reviewAuthoritativeInsurancePrepaidAmortization} from '../src/accounting-api.js';

const uuid=n=>`${String(n).padStart(8,'0')}-1111-4111-8111-${String(n).padStart(12,'0')}`;
const hash=n=>`sha256:${String(n).repeat(64).slice(0,64)}`;
const config={baseUrl:'https://accounting.example',entityId:uuid(1),periodId:uuid(2),getAccessToken:async()=> 'a'.repeat(48)};
const response=(status,data)=>({ok:status>=200&&status<300,status,json:async()=>data,text:async()=>JSON.stringify(data)});
const ready={
  ai_amortization_schedule_id:uuid(3),ai_amortization_schedule_line_id:uuid(4),source_document_id:uuid(5),source_payload_hash:hash(1),source_document_version:'7',wbs_provider_signed_payable_admission_id:uuid(6),ai_amortization_coverage_evidence_id:uuid(7),coverage_hash:hash(2),proposal_hash:hash(3),period_id:config.periodId,period_status:'OPEN',amortization_month:'2026-08-01',amount:'8.3333',currency:'USD',prepaid_account_code:'141500',expense_account_code:'610100',amortization_setting_snapshot_id:uuid(8),amortization_setting_snapshot_hash:hash(4),prepaid_mapping_snapshot_id:uuid(9),prepaid_mapping_snapshot_hash:hash(5),capitalization_journal_entry_id:uuid(10),capitalization_journal_line_id:uuid(11),capitalization_ledger_line_id:uuid(12),insurance_prepaid_amortization_review_id:null,review_evidence_hash:null,reviewed_by:null,reviewed_at:null,insurance_prepaid_amortization_draft_evidence_id:null,draft_evidence_hash:null,journal_entry_id:null,journal_status:null,journal_revision:null,derived_source_document_id:null,draft_created_by:null,draft_created_at:null,readiness_status:'READY_FOR_INDEPENDENT_REVIEW',blocked_reasons:[],can_independently_review:true,can_create_draft:false,can_submit:false,can_approve:false,can_post:false
};

test('client accepts only exact MONEY4/hash/version entity-period readiness',async()=>{
  let request;const result=await refreshAuthoritativeInsurancePrepaidAmortization({config,fetcher:async(url,options)=>(request={url,options},response(200,{ok:true,data:[ready]}))});
  assert.equal(result.ok,true);assert.equal(result.rows[0].amount,'8.3333');assert.equal(result.rows[0].source_document_version,7);assert.match(request.url,new RegExp(`/entities/${config.entityId}/prepaid/amortization\\?periodId=${config.periodId}&limit=50$`));assert.equal(request.options.method,'GET');assert.equal(request.options.cache,'no-store');assert.equal('body' in request.options,false);assert.equal('idempotency-key' in request.options.headers,false);
  for(const invalid of [{...ready,amount:'8.33'},{...ready,source_payload_hash:'sha256:bad'},{...ready,source_document_version:'7.0'},{...ready,period_id:uuid(99)},{...ready,readiness_status:'PROPOSED'}]){
    const rejected=await refreshAuthoritativeInsurancePrepaidAmortization({config,fetcher:async()=>response(200,{ok:true,data:[invalid]})});assert.equal(rejected.code,'INSURANCE_AMORTIZATION_PROTOCOL');
  }
});

test('independent review sends the exact retained IDs and hashes and cannot run on an AI-only proposal',async()=>{
  let request;const reviewed={insurance_prepaid_amortization_review_id:uuid(13),source_document_id:ready.source_document_id,schedule_line_id:ready.ai_amortization_schedule_line_id,period_id:config.periodId,amount:'8.3333',evidence_hash:hash(6),status:'INDEPENDENTLY_REVIEWED',can_create_draft:false,can_submit:false,can_approve:false,can_post:false,idempotent:false};
  const result=await reviewAuthoritativeInsurancePrepaidAmortization({config,evidence:ready,reason:'Independent controller review.',idempotencyKey:'insurance-review-001',fetcher:async(url,options)=>(request={url,options},response(201,{ok:true,data:reviewed}))});
  assert.equal(result.ok,true);assert.equal(request.options.method,'POST');assert.equal(request.options.headers['idempotency-key'],'insurance-review-001');assert.equal(request.options.headers['if-match'],'"7"');const body=JSON.parse(request.options.body);assert.deepEqual(body,{admissionId:ready.wbs_provider_signed_payable_admission_id,scheduleId:ready.ai_amortization_schedule_id,scheduleLineId:ready.ai_amortization_schedule_line_id,periodId:config.periodId,settingSnapshotId:ready.amortization_setting_snapshot_id,mappingSnapshotId:ready.prepaid_mapping_snapshot_id,capitalizationJournalEntryId:ready.capitalization_journal_entry_id,capitalizationLedgerLineId:ready.capitalization_ledger_line_id,expectedSourceHash:ready.source_payload_hash,expectedProposalHash:ready.proposal_hash,expectedCoverageHash:ready.coverage_hash,reason:'Independent controller review.'});
  let called=false;const blocked=await reviewAuthoritativeInsurancePrepaidAmortization({config,evidence:{...ready,readiness_status:'BLOCKED',can_independently_review:false},reason:'Independent controller review.',idempotencyKey:'insurance-review-002',fetcher:async()=>{called=true;}});assert.equal(blocked.code,'INSURANCE_AMORTIZATION_REVIEW_INVALID');assert.equal(called,false);
});

test('Draft client requires independently reviewed evidence and validates an AUTO Draft-only receipt',async()=>{
  const reviewed={...ready,insurance_prepaid_amortization_review_id:uuid(13),review_evidence_hash:hash(6),reviewed_by:'insurance-controller',reviewed_at:'2026-08-16T00:00:00.000Z',readiness_status:'INDEPENDENTLY_REVIEWED',can_independently_review:false,can_create_draft:true};let request;
  const receipt={insurance_prepaid_amortization_draft_evidence_id:uuid(14),insurance_prepaid_amortization_review_id:uuid(13),source_document_id:ready.source_document_id,derived_source_document_id:uuid(15),derived_staging_item_id:uuid(16),journal_entry_id:uuid(17),expense_journal_line_id:uuid(18),prepaid_journal_line_id:uuid(19),amount:'8.3333',status:'DRAFT',journal_type:'AUTO',revision:0,evidence_hash:hash(7),can_create_draft:false,can_submit:false,can_review:false,can_approve:false,can_post:false,idempotent:false};
  const result=await createAuthoritativeInsuranceAmortizationDraft({config,evidence:reviewed,reason:'Prepare reviewed monthly Draft.',idempotencyKey:'insurance-draft-001',fetcher:async(url,options)=>(request={url,options},response(201,{ok:true,data:receipt}))});assert.equal(result.ok,true);assert.match(request.url,/\/prepaid\/amortization\/reviews\/.*\/drafts$/);assert.equal(request.options.headers['if-match'],'"0"');assert.deepEqual(JSON.parse(request.options.body),{expectedEvidenceHash:hash(6),reason:'Prepare reviewed monthly Draft.'});assert.equal(result.data.status,'DRAFT');
  const rejected=await createAuthoritativeInsuranceAmortizationDraft({config,evidence:ready,reason:'Prepare reviewed monthly Draft.',idempotencyKey:'insurance-draft-002',fetcher:async()=>{throw new Error('must not fetch');}});assert.equal(rejected.code,'INSURANCE_AMORTIZATION_DRAFT_INVALID');
});
