import assert from 'node:assert/strict';
import test from 'node:test';
import {exportAuthoritativeJournalUploadFile} from '../src/accounting-api.js';
const config={baseUrl:'https://accounting.example',entityId:'00000002-1111-4111-8111-000000000002',periodId:'00000003-1111-4111-8111-000000000003',getAccessToken:async()=>'token-token-token'};
const content='JournalNumber,JournalDate\nJE-100,2026-09-13\r\n';
const hash='sha256:'.concat('0'.repeat(64));
const response=(headers={})=>({ok:true,headers:{get:name=>headers[name.toLowerCase()]??null},text:async()=>content});
test('JE upload client verifies hash, row count, and safe filename',async()=>{const cryptoApi={subtle:{digest:async()=>new Uint8Array(32)}};const result=await exportAuthoritativeJournalUploadFile({config,cryptoApi,fetcher:async(url,options)=>{assert.match(url,/journal-entries\/export\?periodId=/);assert.equal(options.method,'GET');assert.equal(options.cache,'no-store');return response({'content-type':'text/csv; charset=utf-8','x-journal-upload-export-hash':hash,'x-journal-upload-row-count':'2','content-disposition':'attachment; filename="journal-upload.csv"'});}});assert.equal(result.ok,true);assert.equal(result.data.filename,'journal-upload.csv');assert.equal(result.data.rowCount,2);});
test('JE upload client rejects drift and invalid response headers',async()=>{const cryptoApi={subtle:{digest:async()=>new Uint8Array(32)}};const bad=await exportAuthoritativeJournalUploadFile({config,cryptoApi,fetcher:async()=>response({'content-type':'application/json','x-journal-upload-export-hash':hash,'x-journal-upload-row-count':'2','content-disposition':'attachment; filename="x.csv"'})});assert.equal(bad.ok,false);assert.equal(bad.code,'JOURNAL_UPLOAD_EXPORT_PROTOCOL');const drift=await exportAuthoritativeJournalUploadFile({config,cryptoApi,fetcher:async()=>response({'content-type':'text/csv; charset=utf-8','x-journal-upload-export-hash':'sha256:'.concat('f'.repeat(64)),'x-journal-upload-row-count':'2','content-disposition':'attachment; filename="x.csv"'})});assert.equal(drift.ok,false);assert.equal(drift.code,'JOURNAL_UPLOAD_EXPORT_PROTOCOL');});
