import test from 'node:test';
import assert from 'node:assert/strict';
import {readReceiptDetail,readReceiptRegister} from '../src/receipt-register.js';
const id=n=>`${n.repeat(8)}-${n.repeat(4)}-4${n.repeat(3)}-8${n.repeat(3)}-${n.repeat(12)}`;
const entityId=id('2'),receiptId=id('3'),config={baseUrl:'https://fixture.example',tenantId:id('1'),entityId,periodId:id('9'),getAccessToken:async()=>'fixture-token-'.repeat(4)},flags={can_upload:false,can_run_ocr:false,can_review:false,can_add_to_books:false,can_export:false,can_customize:false,can_promote_payment:false};
const row={receipt_id:receiptId,receipt_created_by:'binder',receipt_created_at:'2026-09-10T01:00:00Z',attachment_id:id('4'),attachment_name:'receipt.pdf',media_type:'application/pdf',size_bytes:'10',content_hash:'sha256:'+'a'.repeat(64),storage_ref:'object://receipts/1',storage_version:'v1',uploaded_by:'uploader',uploaded_at:'2026-09-10T00:00:00Z',verified_at:'2026-09-10T00:01:00Z',finalized_at:'2026-09-10T00:01:01Z',scan_status:'CLEAN',finalization_status:'VERIFIED_CLEAN',source_document_id:id('5'),source_document_revision:0,source_payload_hash:'sha256:'+'b'.repeat(64),staging_item_id:null,staging_revision:null,review_status:'FOR_REVIEW',reviewed_by:null,reviewed_at:null,extracted_facts:{source_system:'WBS',source_module:'payable',source_record_id:'P-1',source_version:'v1',document_type:'BILL',document_no:null,business_date:'2026-09-10',accounting_date:'2026-09-10',currency:'USD',gross_amount:'10.0000',line_count:1,party_refs:[],project_refs:[],property_refs:[],unit_refs:[],loan_refs:[],cost_code_refs:[]},action_flags:flags};
const page={schema_version:'RECEIPT_REGISTER_V1',entity_id:entityId,review_status:'FOR_REVIEW',row_count:1,total_size_bytes:'10',rows:[row],action_flags:flags},response=(body,status=200)=>({ok:status<400,status,json:async()=>body});
test('client reads exact no-store Receipt queue and detail evidence',async()=>{const calls=[],fetcher=async(url,options)=>(calls.push({url,...options}),response({ok:true,data:url.endsWith(receiptId)?row:page}));const list=await readReceiptRegister({config,fetcher});assert.equal(list.ok,true);const detail=await readReceiptDetail({config,row,fetcher});assert.equal(detail.ok,true);assert.match(calls[0].url,/receipts\?reviewStatus=FOR_REVIEW$/);assert.match(calls[1].url,new RegExp(`/receipts/${receiptId}$`));assert.ok(calls.every(call=>call.method==='GET'&&call.cache==='no-store'&&/^Bearer /.test(call.headers.authorization)));});
test('client fails closed on queue, object version, or action drift',async()=>{for(const data of [{...page,review_status:'REVIEWED'},{...page,rows:[{...row,storage_version:''}]},{...page,action_flags:{...flags,can_upload:true}}])assert.equal((await readReceiptRegister({config,fetcher:async()=>response({ok:true,data})})).ok,false);assert.equal((await readReceiptDetail({config,row,fetcher:async()=>response({ok:true,data:{...row,content_hash:'sha256:'+'c'.repeat(64)}})})).ok,false);});
