import test from 'node:test';import assert from 'node:assert/strict';
import {readSalesBankCandidates,prepareSalesBankMatch,sendSalesBankMatch,validSalesBankCommand} from '../src/sales-receipt-bank-api.js';
import {reserveSalesBankIntent,readSalesBankIntent,releaseSalesBankIntent,SalesBankRecoveryError} from '../src/sales-receipt-bank-recovery.js';
import {readBankSalesReceipt,readBankSalesReceiptJournal} from '../src/bank-sales-receipt-detail.js';
const id=n=>`${n.repeat(8)}-${n.repeat(4)}-4${n.repeat(3)}-8${n.repeat(3)}-${n.repeat(12)}`;
const config={baseUrl:'https://fixture.example',entityId:id('1'),periodId:id('2'),getAccessToken:async()=>'fixture-token-'.repeat(4)};
const bank={bank_source_id:id('3'),version:2,bank_account_ref:'BANK-1',currency:'USD',amount:'1.2345',bank_match_id:null};
const candidate={sales_receipt_id:id('4'),receipt_revision:'1',receipt_number:'SALE-001',period_id:id('2'),customer_ref:'CUSTOMER-1',customer_name:'Customer One',bank_member_ref:'BANK-1',cash_account_code:'111001',accounting_date:'2026-07-15',currency:'USD',amount:'1.2345',journal_entry_id:id('5'),journal_revision:'4',journal_line_id:id('6'),ledger_line_id:id('7'),date_delta_days:-1};
const access=actor=>({ok:true,data:{tenant_id:id('8'),entity_id:config.entityId,actor_id:actor,grant_set_version:1,permissions:['BANK.MATCH.CREATE'],configured_permissions:['BANK.MATCH.CREATE'],session_refresh_required:false}});
const response=(body,status=200)=>({ok:status<400,status,json:async()=>body});
const page={schema_version:'SALES_RECEIPT_BANK_CANDIDATES_V1',entity_id:config.entityId,bank_source_id:bank.bank_source_id,bank_revision:'2',after_id:null,limit:25,rows:[candidate],next_id:null};
test('bank source opens its exact posted receipt and cash journal across periods with GET only',async()=>{
 const row={...bank,bank_match_id:id('9'),match_status:'ACTIVE',match_source_kind:'SALES_RECEIPT',payment_occurrence_id:null,business_source_document_id:null,sales_receipt_id:candidate.sales_receipt_id,sales_receipt_number:candidate.receipt_number,sales_receipt_revision:'1',journal_entry_id:candidate.journal_entry_id,journal_line_id:candidate.journal_line_id,ledger_line_id:candidate.ledger_line_id};
 const record={sales_receipt_id:candidate.sales_receipt_id,period_id:id('8'),receipt_number:candidate.receipt_number,customer_ref:'CUST-1',customer_name:'Customer One',bank_member_ref:'BANK-1',cash_account_code:'111001',category_account_code:'400001',accounting_date:'2026-06-30',currency:'USD',amount:'1.2345',description:'Reviewed cash sale receipt',status:'POSTED',revision:'1',journal_entry_id:candidate.journal_entry_id,journal_number:'JE-SALE-1',journal_status:'POSTED',journal_revision:'4',created_at:'2026-06-30T01:02:03.123456Z',posted_at:'2026-06-30T01:02:04.123456Z'};
 const journal={entity_id:config.entityId,period_id:record.period_id,journal_entry_id:record.journal_entry_id,journal_number:record.journal_number,journal_type:'MANUAL',status:'POSTED',journal_date:record.accounting_date,currency:'USD',description:null,revision:4,created_at:'2026-06-30T01:02:03.123Z',posted_at:'2026-06-30T01:02:04.123Z',lines:[{line_no:1,journal_line_id:row.journal_line_id,ledger_line_id:row.ledger_line_id,account_code:record.cash_account_code,debit_amount:'1.2345',credit_amount:'0.0000',member_ref:'BANK-1',description:null,dimensions:{},source_document_ids:[]},{line_no:2,journal_line_id:id('9'),ledger_line_id:id('8'),account_code:record.category_account_code,debit_amount:'0.0000',credit_amount:'1.2345',member_ref:'CUST-1',description:null,dimensions:{},source_document_ids:[]}]};
 const detail=changed=>({schema_version:'SALES_RECEIPT_DETAIL_V1',entity_id:config.entityId,record:{...record,...changed}}),calls=[];
 const fetcher=async(url,options)=>{calls.push(url);assert.equal(options.method,'GET');assert.equal(options.body,undefined);assert.equal(options.cache,'no-store');return response({ok:true,data:url.includes('/ar/sales-receipts/')?detail():journal});};
 const result=await readBankSalesReceiptJournal({config,row,fetcher});assert.equal(result.ok,true,JSON.stringify(result));assert.equal(result.config.periodId,record.period_id);assert.equal(config.periodId,id('2'));assert.equal(result.record.amount,'1.2345');assert.equal(calls.length,2);assert.ok(calls[0].endsWith('/ar/sales-receipts/'+row.sales_receipt_id));assert.ok(calls[1].includes('/journal-entries/'+row.journal_entry_id));
 for(const patch of [{revision:'2'},{amount:'1.2346'},{currency:'EUR'},{bank_member_ref:'BANK-2'},{journal_entry_id:id('9')},{receipt_number:'OTHER'}]){let reads=0;const result=await readBankSalesReceiptJournal({config,row,fetcher:async()=>{reads++;return response({ok:true,data:detail(patch)});}});assert.equal(result.ok,false);assert.equal(reads,1);}
 for(const patch of [{ledger_line_id:id('8')},{journal_line_id:id('8')},{account_code:'111002'},{member_ref:'BANK-2'},{debit_amount:'1.2346'}]){const result=await readBankSalesReceiptJournal({config,row,fetcher:async url=>response({ok:true,data:url.includes('/ar/sales-receipts/')?detail():{...journal,lines:[{...journal.lines[0],...patch},journal.lines[1]]}})});assert.equal(result.ok,false);}
 let denied=0;assert.equal((await readBankSalesReceiptJournal({config,row,fetcher:async()=>{denied++;return response({},403);}})).ok,false);assert.equal(denied,1);
 assert.equal((await readBankSalesReceipt({config,row:{...row,match_source_kind:'PAYMENT'},fetcher:()=>{throw Error('must not read wrong source');}})).ok,false);
});
test('persisted match intent rejects changed scope, trace and command contents before access or POST',async()=>{
 const prepared=await prepareSalesBankMatch({config,bank,candidate,bankRevision:'2',reason:'Reviewed matching receipt',expectedActorId:'matcher',fetcher:async()=>response(access('matcher'))});
 assert.equal(prepared.ok,true);const command=structuredClone(prepared.command),scope={config,bankSourceId:bank.bank_source_id,actorId:'matcher'};
 assert.equal(await validSalesBankCommand({...scope,command}),true);
 for(const changed of [null,[],{...command,receipt:{}},{...command,bankRevision:2},{...command,bankRevision:'02'},{...command,actorId:'other'},{...command,entityId:id('9')},{...command,bankSourceId:id('9')},{...command,body:{...command.body,reason:'Another reason'}},{...command,trace:{...command.trace,journal_entry_id:id('9')}},{...command,trace:{...command.trace,journal_line_id:id('9')}},{...command,trace:{...command.trace,ledger_line_id:id('9')}}])assert.equal(await validSalesBankCommand({...scope,command:changed}),false);
 let calls=0;const result=await sendSalesBankMatch({config,command:{...command,trace:{...command.trace,ledger_line_id:id('9')}},fetcher:async()=>{calls++;throw Error('must not fetch');}});assert.equal(result.ok,false);assert.equal(calls,0);
 for(const run of [()=>reserveSalesBankIntent(scope,command,{indexedDB:null}),()=>readSalesBankIntent(scope,{indexedDB:null}),()=>releaseSalesBankIntent(scope,command.idempotencyKey,{indexedDB:null})])await assert.rejects(run,SalesBankRecoveryError);
});
test('cash sale candidate pages retain exact amount, source, revision and cursor scope',async()=>{
 let call;const read=await readSalesBankCandidates({config,bankSourceId:bank.bank_source_id,fetcher:async(url,options)=>{call={url,...options};return response({ok:true,data:page});}});
 assert.equal(read.ok,true);assert.equal(read.data.rows[0].amount,'1.2345');assert.equal(read.data.rows[0].date_delta_days,-1);assert.equal(call.method,'GET');assert.match(call.url,/sales-receipt-candidates\?limit=25$/);
 for(const patch of [{entity_id:id('9')},{bank_revision:2},{next_id:candidate.sales_receipt_id},{rows:[{...candidate,amount:1.2345}]}])assert.equal((await readSalesBankCandidates({config,bankSourceId:bank.bank_source_id,fetcher:async()=>response({ok:true,data:{...page,...patch}})})).ok,false);
});
test('cash sale match retries bind actor, versions, exact request and posted trace',async()=>{
 const posts=[];let actor='matcher',loseResponse=true;
 const receipt={bank_match_id:id('9'),bank_source_id:bank.bank_source_id,sales_receipt_id:candidate.sales_receipt_id,journal_entry_id:candidate.journal_entry_id,journal_line_id:candidate.journal_line_id,ledger_line_id:candidate.ledger_line_id,status:'ACTIVE',revision:0,idempotent:true};
 const fetcher=async(url,options)=>{if(url.endsWith('/access/self'))return response(access(actor));posts.push({url,...options});if(loseResponse){loseResponse=false;throw Error('response lost after commit');}return response({ok:true,data:receipt});};
 const prepared=await prepareSalesBankMatch({config,bank,candidate,bankRevision:'2',reason:'Reviewed matching receipt',expectedActorId:actor,fetcher});assert.equal(prepared.ok,true,JSON.stringify(prepared));
 const later=await prepareSalesBankMatch({config,bank:{...bank,bank_match_id:id('9'),match_status:'UNMATCHED'},candidate,bankRevision:'2',reason:'Reviewed matching receipt',expectedActorId:actor,fetcher});assert.equal(later.ok,true);assert.notEqual(later.command.idempotencyKey,prepared.command.idempotencyKey,'a new review after unmatch is distinct from replaying the earlier command');
 const first=await sendSalesBankMatch({config,command:prepared.command,fetcher});assert.equal(first.unconfirmed,true);assert.equal(posts.length,1);
 actor='another-matcher';assert.equal((await sendSalesBankMatch({config,command:prepared.command,fetcher})).ok,false);assert.equal(posts.length,1);
 actor='matcher';const replay=await sendSalesBankMatch({config,command:prepared.command,fetcher});assert.equal(replay.ok,true,JSON.stringify(replay));assert.equal(posts.length,2);
 assert.equal(posts[0].body,posts[1].body);assert.equal(posts[0].headers['idempotency-key'],posts[1].headers['idempotency-key']);assert.equal(posts[0].headers['if-match'],'"2"');
 assert.deepEqual(JSON.parse(posts[0].body),{salesReceiptId:candidate.sales_receipt_id,expectedReceiptRevision:1,reason:'Reviewed matching receipt'});
 assert.equal((await sendSalesBankMatch({config,command:{...prepared.command,body:{...prepared.command.body,reason:'Changed request reason'}},fetcher})).ok,false);assert.equal(posts.length,2);
 const malformed=await sendSalesBankMatch({config,command:prepared.command,fetcher:async(url)=>url.endsWith('/access/self')?response(access(actor)):response({ok:true,data:{...receipt,ledger_line_id:id('8')}})});assert.equal(malformed.unconfirmed,true);
 let tokenCalls=0;const seenAuth=[];
 const created=await sendSalesBankMatch({config:{...config,getAccessToken:async()=>{tokenCalls++;return `fixture-token-${tokenCalls}-`.repeat(4);}},command:prepared.command,fetcher:async(url,options)=>{seenAuth.push(options.headers.authorization);return url.endsWith('/access/self')?response(access(actor)):response({ok:true,data:{...receipt,idempotent:false}},201);}});
 assert.equal(created.ok,true);assert.equal(tokenCalls,1);assert.equal(seenAuth.length,2);assert.equal(seenAuth[0],seenAuth[1],'access check and command use the same bearer');
 for(const changed of [{...bank,amount:'1.2346'},{...bank,version:3}])assert.equal((await prepareSalesBankMatch({config,bank:changed,candidate,bankRevision:'2',reason:'Reviewed matching receipt',expectedActorId:actor,fetcher})).ok,false);
});
