BEGIN;

INSERT INTO permission_catalog(permission_code,domain,risk_class,sod_class) VALUES
  ('PREPAID.AMORTIZATION.REVIEW','PREPAID','HIGH','PREPAID_AMORTIZATION_REVIEWER'),
  ('PREPAID.AMORTIZATION.DRAFT','PREPAID','HIGH','PREPAID_AMORTIZATION_DRAFTER')
ON CONFLICT(permission_code) DO NOTHING;

-- This bridge never classifies a description as insurance.  It accepts only an
-- exact provider-signed WBS import, retained coverage evidence, a deterministic
-- schedule, an approved INSURANCE/PREPAID mapping, and an already POSTED
-- capitalization debit.  Review and Draft are separate immutable acts.
CREATE TABLE insurance_prepaid_amortization_review (
  insurance_prepaid_amortization_review_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES tenant(tenant_id), entity_id uuid NOT NULL,
  wbs_provider_signed_payable_admission_id uuid NOT NULL, source_document_id uuid NOT NULL,
  source_payload_hash text NOT NULL CHECK(source_payload_hash~'^sha256:[0-9a-f]{64}$'),
  source_document_version bigint NOT NULL CHECK(source_document_version>=0),
  ai_amortization_coverage_evidence_id uuid NOT NULL, coverage_hash text NOT NULL CHECK(coverage_hash~'^sha256:[0-9a-f]{64}$'),
  ai_amortization_schedule_id uuid NOT NULL, proposal_hash text NOT NULL CHECK(proposal_hash~'^sha256:[0-9a-f]{64}$'),
  ai_amortization_schedule_line_id uuid NOT NULL, period_id uuid NOT NULL,
  amortization_setting_snapshot_id uuid NOT NULL, amortization_setting_snapshot_hash text NOT NULL CHECK(amortization_setting_snapshot_hash~'^sha256:[0-9a-f]{64}$'),
  prepaid_mapping_snapshot_id uuid NOT NULL, prepaid_mapping_snapshot_hash text NOT NULL CHECK(prepaid_mapping_snapshot_hash~'^sha256:[0-9a-f]{64}$'),
  capitalization_journal_entry_id uuid NOT NULL, capitalization_journal_line_id uuid NOT NULL, capitalization_ledger_line_id uuid NOT NULL,
  amortization_month date NOT NULL, amount numeric(20,4) NOT NULL CHECK(amount>0), currency char(3) NOT NULL CHECK(currency~'^[A-Z]{3}$'),
  prepaid_account_code text NOT NULL, expense_account_code text NOT NULL,
  evidence_hash text NOT NULL CHECK(evidence_hash~'^sha256:[0-9a-f]{64}$'),
  review_reason text NOT NULL CHECK(length(btrim(review_reason)) BETWEEN 8 AND 2000),
  reviewed_by text NOT NULL, reviewed_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  request_hash text NOT NULL CHECK(request_hash~'^sha256:[0-9a-f]{64}$'),
  UNIQUE(tenant_id,entity_id,ai_amortization_schedule_line_id),
  UNIQUE(tenant_id,entity_id,insurance_prepaid_amortization_review_id),
  FOREIGN KEY(tenant_id,entity_id) REFERENCES entity(tenant_id,entity_id),
  FOREIGN KEY(tenant_id,entity_id,wbs_provider_signed_payable_admission_id) REFERENCES wbs_provider_signed_payable_admission(tenant_id,entity_id,wbs_provider_signed_payable_admission_id),
  FOREIGN KEY(tenant_id,entity_id,source_document_id) REFERENCES source_document(tenant_id,entity_id,source_document_id),
  FOREIGN KEY(tenant_id,entity_id,ai_amortization_coverage_evidence_id) REFERENCES ai_amortization_coverage_evidence(tenant_id,entity_id,ai_amortization_coverage_evidence_id),
  FOREIGN KEY(tenant_id,entity_id,ai_amortization_schedule_id) REFERENCES ai_amortization_schedule(tenant_id,entity_id,ai_amortization_schedule_id),
  FOREIGN KEY(tenant_id,entity_id,ai_amortization_schedule_line_id) REFERENCES ai_amortization_schedule_line(tenant_id,entity_id,ai_amortization_schedule_line_id),
  FOREIGN KEY(tenant_id,amortization_setting_snapshot_id) REFERENCES setting_snapshot(tenant_id,setting_snapshot_id),
  FOREIGN KEY(tenant_id,prepaid_mapping_snapshot_id) REFERENCES mapping_snapshot(tenant_id,mapping_snapshot_id),
  FOREIGN KEY(tenant_id,entity_id,period_id) REFERENCES accounting_period(tenant_id,entity_id,period_id),
  FOREIGN KEY(tenant_id,entity_id,capitalization_journal_entry_id) REFERENCES journal_entry(tenant_id,entity_id,journal_entry_id),
  FOREIGN KEY(tenant_id,entity_id,capitalization_journal_line_id) REFERENCES journal_line(tenant_id,entity_id,journal_line_id),
  FOREIGN KEY(tenant_id,entity_id,capitalization_ledger_line_id) REFERENCES ledger_line(tenant_id,entity_id,ledger_line_id)
);

CREATE TABLE insurance_prepaid_amortization_draft_evidence (
  insurance_prepaid_amortization_draft_evidence_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES tenant(tenant_id), entity_id uuid NOT NULL,
  insurance_prepaid_amortization_review_id uuid NOT NULL, source_document_id uuid NOT NULL,
  ai_amortization_schedule_line_id uuid NOT NULL, journal_entry_id uuid NOT NULL,
  derived_raw_event_id uuid NOT NULL, derived_source_document_id uuid NOT NULL, derived_staging_item_id uuid NOT NULL,
  expense_journal_line_id uuid NOT NULL, prepaid_journal_line_id uuid NOT NULL,
  evidence_hash text NOT NULL CHECK(evidence_hash~'^sha256:[0-9a-f]{64}$'),
  request_hash text NOT NULL CHECK(request_hash~'^sha256:[0-9a-f]{64}$'), maker_reason text NOT NULL CHECK(length(btrim(maker_reason)) BETWEEN 8 AND 2000),
  created_by text NOT NULL, created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  UNIQUE(tenant_id,entity_id,insurance_prepaid_amortization_review_id),
  UNIQUE(tenant_id,entity_id,ai_amortization_schedule_line_id),
  UNIQUE(tenant_id,entity_id,journal_entry_id),
  FOREIGN KEY(tenant_id,entity_id) REFERENCES entity(tenant_id,entity_id),
  FOREIGN KEY(tenant_id,entity_id,insurance_prepaid_amortization_review_id) REFERENCES insurance_prepaid_amortization_review(tenant_id,entity_id,insurance_prepaid_amortization_review_id),
  FOREIGN KEY(tenant_id,entity_id,source_document_id) REFERENCES source_document(tenant_id,entity_id,source_document_id),
  FOREIGN KEY(tenant_id,entity_id,ai_amortization_schedule_line_id) REFERENCES ai_amortization_schedule_line(tenant_id,entity_id,ai_amortization_schedule_line_id),
  FOREIGN KEY(tenant_id,derived_raw_event_id) REFERENCES raw_event(tenant_id,raw_event_id),
  FOREIGN KEY(tenant_id,entity_id,derived_source_document_id) REFERENCES source_document(tenant_id,entity_id,source_document_id),
  FOREIGN KEY(tenant_id,entity_id,derived_staging_item_id) REFERENCES staging_item(tenant_id,entity_id,staging_item_id),
  FOREIGN KEY(tenant_id,entity_id,journal_entry_id) REFERENCES journal_entry(tenant_id,entity_id,journal_entry_id),
  FOREIGN KEY(tenant_id,entity_id,expense_journal_line_id) REFERENCES journal_line(tenant_id,entity_id,journal_line_id),
  FOREIGN KEY(tenant_id,entity_id,prepaid_journal_line_id) REFERENCES journal_line(tenant_id,entity_id,journal_line_id)
);

ALTER TABLE insurance_prepaid_amortization_review ENABLE ROW LEVEL SECURITY;
CREATE POLICY insurance_prepaid_amortization_review_scope ON insurance_prepaid_amortization_review USING(tenant_id=refs_current_tenant() AND refs_entity_allowed(entity_id)) WITH CHECK(tenant_id=refs_current_tenant() AND refs_entity_allowed(entity_id));
ALTER TABLE insurance_prepaid_amortization_draft_evidence ENABLE ROW LEVEL SECURITY;
CREATE POLICY insurance_prepaid_amortization_draft_scope ON insurance_prepaid_amortization_draft_evidence USING(tenant_id=refs_current_tenant() AND refs_entity_allowed(entity_id)) WITH CHECK(tenant_id=refs_current_tenant() AND refs_entity_allowed(entity_id));
CREATE TRIGGER insurance_prepaid_amortization_review_append_only BEFORE UPDATE OR DELETE ON insurance_prepaid_amortization_review FOR EACH ROW EXECUTE FUNCTION reject_mutation();
CREATE TRIGGER insurance_prepaid_amortization_draft_append_only BEFORE UPDATE OR DELETE ON insurance_prepaid_amortization_draft_evidence FOR EACH ROW EXECUTE FUNCTION reject_mutation();

CREATE FUNCTION refs_review_insurance_prepaid_amortization_hash(
  p_tenant uuid,p_entity uuid,p_admission uuid,p_schedule uuid,p_schedule_line uuid,p_period uuid,p_setting uuid,p_mapping uuid,
  p_capitalization_journal uuid,p_capitalization_ledger_line uuid,p_expected_source_hash text,p_expected_proposal_hash text,p_expected_coverage_hash text,p_reason text
) RETURNS text LANGUAGE sql IMMUTABLE SET search_path=pg_catalog,public,pg_temp AS $$
  SELECT refs_jsonb_hash(jsonb_build_object('tenant_id',p_tenant,'entity_id',p_entity,'admission_id',p_admission,'schedule_id',p_schedule,
    'schedule_line_id',p_schedule_line,'period_id',p_period,'setting_snapshot_id',p_setting,'mapping_snapshot_id',p_mapping,'capitalization_journal_entry_id',p_capitalization_journal,
    'capitalization_ledger_line_id',p_capitalization_ledger_line,'expected_source_hash',p_expected_source_hash,'expected_proposal_hash',p_expected_proposal_hash,
    'expected_coverage_hash',p_expected_coverage_hash,'reason',btrim(p_reason)))
$$;

CREATE FUNCTION refs_review_insurance_prepaid_amortization(
  p_tenant uuid,p_entity uuid,p_admission uuid,p_schedule uuid,p_schedule_line uuid,p_period uuid,p_setting uuid,p_mapping uuid,
  p_capitalization_journal uuid,p_capitalization_ledger_line uuid,p_expected_source_hash text,p_expected_proposal_hash text,p_expected_coverage_hash text,
  p_reason text,p_idempotency_key text,p_request_hash text
) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE actor text:=refs_current_actor(); idem idempotency_receipt; schedule ai_amortization_schedule; schedule_line ai_amortization_schedule_line;
DECLARE coverage ai_amortization_coverage_evidence; source source_document; admission wbs_provider_signed_payable_admission; setting setting_snapshot; mapping mapping_snapshot;
DECLARE period accounting_period; capitalization journal_entry; capitalization_line journal_line; capitalization_ledger ledger_line;
DECLARE review_id uuid:=gen_random_uuid(); evidence text; payload jsonb; result jsonb;
BEGIN
  PERFORM refs_assert_scope(p_tenant,p_entity,'PREPAID.AMORTIZATION.REVIEW');
  IF actor IS NULL THEN RAISE EXCEPTION 'Authenticated insurance amortization reviewer missing' USING ERRCODE='42501'; END IF;
  IF p_request_hash IS DISTINCT FROM refs_review_insurance_prepaid_amortization_hash(p_tenant,p_entity,p_admission,p_schedule,p_schedule_line,p_period,p_setting,p_mapping,p_capitalization_journal,p_capitalization_ledger_line,p_expected_source_hash,p_expected_proposal_hash,p_expected_coverage_hash,p_reason) THEN RAISE EXCEPTION 'Insurance amortization review request hash is not canonical' USING ERRCODE='22023'; END IF;
  IF p_expected_source_hash!~'^sha256:[0-9a-f]{64}$' OR p_expected_proposal_hash!~'^sha256:[0-9a-f]{64}$' OR p_expected_coverage_hash!~'^sha256:[0-9a-f]{64}$' OR COALESCE(length(btrim(p_reason)),0) NOT BETWEEN 8 AND 2000 THEN RAISE EXCEPTION 'Insurance amortization review requires exact hashes and reason' USING ERRCODE='22023'; END IF;
  INSERT INTO idempotency_receipt(tenant_id,operation_scope,idempotency_key,request_hash,status,actor_id) VALUES(p_tenant,'INSURANCE_PREPAID_AMORTIZATION_REVIEW:'||p_entity,p_idempotency_key,p_request_hash,'IN_PROGRESS',actor) ON CONFLICT DO NOTHING;
  SELECT * INTO idem FROM idempotency_receipt WHERE tenant_id=p_tenant AND operation_scope='INSURANCE_PREPAID_AMORTIZATION_REVIEW:'||p_entity AND idempotency_key=p_idempotency_key FOR UPDATE;
  IF idem.request_hash<>p_request_hash THEN RAISE EXCEPTION 'Idempotency key reused with a different insurance amortization review' USING ERRCODE='23505'; END IF;
  IF idem.status='SUCCEEDED' THEN RETURN idem.response_body||jsonb_build_object('idempotent',true); END IF;
  SELECT * INTO schedule FROM ai_amortization_schedule WHERE tenant_id=p_tenant AND entity_id=p_entity AND ai_amortization_schedule_id=p_schedule FOR SHARE;
  SELECT * INTO schedule_line FROM ai_amortization_schedule_line WHERE tenant_id=p_tenant AND entity_id=p_entity AND ai_amortization_schedule_line_id=p_schedule_line AND ai_amortization_schedule_id=p_schedule FOR SHARE;
  IF schedule.ai_amortization_schedule_id IS NULL OR schedule_line.ai_amortization_schedule_line_id IS NULL OR schedule.status<>'PROPOSED' OR schedule_line.status<>'PROPOSED' OR schedule.proposal_hash<>p_expected_proposal_hash OR schedule_line.source_payload_hash<>schedule.source_payload_hash THEN RAISE EXCEPTION 'Immutable amortization schedule evidence is missing or changed' USING ERRCODE='40001'; END IF;
  SELECT * INTO source FROM source_document WHERE tenant_id=p_tenant AND entity_id=p_entity AND source_document_id=schedule.source_document_id FOR SHARE;
  SELECT * INTO coverage FROM ai_amortization_coverage_evidence WHERE tenant_id=p_tenant AND entity_id=p_entity AND source_document_id=schedule.source_document_id AND source_document_version=schedule.source_document_version FOR SHARE;
  SELECT a.* INTO admission FROM wbs_provider_signed_payable_admission a JOIN raw_event r ON r.tenant_id=a.tenant_id AND r.import_batch_id=a.import_batch_id WHERE a.tenant_id=p_tenant AND a.entity_id=p_entity AND a.wbs_provider_signed_payable_admission_id=p_admission AND r.raw_event_id=source.raw_event_id FOR SHARE OF a;
  IF source.source_document_id IS NULL OR coverage.ai_amortization_coverage_evidence_id IS NULL OR admission.wbs_provider_signed_payable_admission_id IS NULL OR source.source_system<>'WBS' OR source.source_module<>'payable' OR source.document_type<>'WBS_PAYABLE' OR source.status<>'POSTED' OR source.payload_hash<>p_expected_source_hash OR source.payload_hash<>schedule.source_payload_hash OR source.version<schedule.source_document_version OR source.gross_amount<>schedule.original_amount OR coverage.coverage_hash<>p_expected_coverage_hash OR coverage.source_document_version<>schedule.source_document_version OR coverage.source_payload_hash<>source.payload_hash OR coverage.coverage_start<>schedule.coverage_start OR coverage.coverage_end<>schedule.coverage_end THEN RAISE EXCEPTION 'Signed admitted insurance source, coverage, and schedule are not one exact chain' USING ERRCODE='23514'; END IF;
  SELECT * INTO period FROM accounting_period WHERE tenant_id=p_tenant AND entity_id=p_entity AND period_id=p_period FOR SHARE;
  IF period.period_id IS NULL OR schedule_line.amortization_month NOT BETWEEN period.starts_on AND period.ends_on THEN RAISE EXCEPTION 'Amortization schedule line is outside the exact accounting period' USING ERRCODE='23514'; END IF;
  SELECT * INTO setting FROM setting_snapshot WHERE tenant_id=p_tenant AND entity_id=p_entity AND setting_snapshot_id=p_setting FOR SHARE;
  IF setting.setting_snapshot_id IS NULL OR setting.family<>'PREPAID_AMORTIZATION_POLICY' OR setting.status NOT IN ('APPROVED','RETIRED') OR setting.snapshot->>'rule_id'<>'PREPAID_AMORTIZATION_V1' OR setting.snapshot->>'frequency'<>'MONTHLY' OR setting.snapshot_hash<>refs_jsonb_hash(setting.snapshot) OR setting.effective_from::date>period.ends_on OR setting.effective_to IS NOT NULL AND setting.effective_to::date<=period.ends_on THEN RAISE EXCEPTION 'Exact approved monthly amortization setting is missing or changed' USING ERRCODE='23514'; END IF;
  SELECT * INTO mapping FROM mapping_snapshot WHERE tenant_id=p_tenant AND entity_id=p_entity AND mapping_snapshot_id=p_mapping FOR SHARE;
  IF mapping.mapping_snapshot_id IS NULL OR mapping.family<>'PREPAID_ACCOUNT_CLASSIFICATION' OR mapping.status NOT IN ('APPROVED','RETIRED') OR mapping.input_keys<>jsonb_build_object('account_code',schedule.prepaid_account_code) OR mapping.output_rules->>'classification'<>'PREPAID' OR mapping.output_rules->>'prepaid_type'<>'INSURANCE' OR mapping.snapshot_hash<>refs_jsonb_hash(jsonb_build_object('input_keys',mapping.input_keys,'output_rules',mapping.output_rules)) OR mapping.effective_from::date>period.ends_on OR mapping.effective_to IS NOT NULL AND mapping.effective_to::date<=period.ends_on THEN RAISE EXCEPTION 'Exact approved insurance prepaid mapping is missing or changed' USING ERRCODE='23514'; END IF;
  SELECT * INTO capitalization FROM journal_entry WHERE tenant_id=p_tenant AND entity_id=p_entity AND journal_entry_id=p_capitalization_journal FOR SHARE;
  SELECT ll.* INTO capitalization_ledger FROM ledger_line ll WHERE ll.tenant_id=p_tenant AND ll.entity_id=p_entity AND ll.ledger_line_id=p_capitalization_ledger_line AND ll.journal_entry_id=p_capitalization_journal FOR SHARE;
  SELECT jl.* INTO capitalization_line FROM journal_line jl WHERE jl.tenant_id=p_tenant AND jl.entity_id=p_entity AND jl.journal_entry_id=p_capitalization_journal AND jl.journal_line_id=capitalization_ledger.journal_line_id FOR SHARE;
  IF capitalization.journal_entry_id IS NULL OR capitalization.status<>'POSTED' OR capitalization_ledger.ledger_line_id IS NULL OR capitalization_line.journal_line_id IS NULL OR capitalization_line.account_code<>schedule.prepaid_account_code OR capitalization_line.debit_amount<>schedule.original_amount OR capitalization_line.credit_amount<>0 OR capitalization_ledger.account_code<>capitalization_line.account_code OR capitalization_ledger.debit_amount<>capitalization_line.debit_amount OR capitalization_ledger.credit_amount<>0 OR NOT EXISTS(SELECT 1 FROM source_link l WHERE l.tenant_id=p_tenant AND l.entity_id=p_entity AND l.source_document_id=source.source_document_id AND l.journal_entry_id=capitalization.journal_entry_id) THEN RAISE EXCEPTION 'Posted prepaid capitalization is missing, changed, or not source-linked' USING ERRCODE='23514'; END IF;
  IF actor IN (schedule.created_by,coverage.created_by,capitalization.created_by,capitalization.reviewed_by,capitalization.approved_by,capitalization.posted_by) THEN RAISE EXCEPTION 'Insurance amortization reviewer must be independent from proposal, coverage, and capitalization actors' USING ERRCODE='42501'; END IF;
  evidence:=refs_jsonb_hash(jsonb_build_object('admission_id',p_admission,'source_document_id',source.source_document_id,'source_payload_hash',source.payload_hash,'source_document_version',schedule.source_document_version,'coverage_evidence_id',coverage.ai_amortization_coverage_evidence_id,'coverage_hash',coverage.coverage_hash,'schedule_id',p_schedule,'proposal_hash',schedule.proposal_hash,'schedule_line_id',p_schedule_line,'period_id',p_period,'setting_snapshot_id',p_setting,'setting_snapshot_hash',setting.snapshot_hash,'mapping_snapshot_id',p_mapping,'mapping_snapshot_hash',mapping.snapshot_hash,'capitalization_journal_entry_id',p_capitalization_journal,'capitalization_journal_line_id',capitalization_line.journal_line_id,'capitalization_ledger_line_id',p_capitalization_ledger_line,'amortization_month',schedule_line.amortization_month,'amount',to_char(schedule_line.amount,'FM999999999999990.0000'),'currency',schedule.currency,'prepaid_account_code',schedule.prepaid_account_code,'expense_account_code',schedule.expense_account_code));
  INSERT INTO insurance_prepaid_amortization_review(insurance_prepaid_amortization_review_id,tenant_id,entity_id,wbs_provider_signed_payable_admission_id,source_document_id,source_payload_hash,source_document_version,ai_amortization_coverage_evidence_id,coverage_hash,ai_amortization_schedule_id,proposal_hash,ai_amortization_schedule_line_id,period_id,amortization_setting_snapshot_id,amortization_setting_snapshot_hash,prepaid_mapping_snapshot_id,prepaid_mapping_snapshot_hash,capitalization_journal_entry_id,capitalization_journal_line_id,capitalization_ledger_line_id,amortization_month,amount,currency,prepaid_account_code,expense_account_code,evidence_hash,review_reason,reviewed_by,request_hash) VALUES(review_id,p_tenant,p_entity,p_admission,source.source_document_id,source.payload_hash,schedule.source_document_version,coverage.ai_amortization_coverage_evidence_id,coverage.coverage_hash,p_schedule,schedule.proposal_hash,p_schedule_line,p_period,p_setting,setting.snapshot_hash,p_mapping,mapping.snapshot_hash,p_capitalization_journal,capitalization_line.journal_line_id,p_capitalization_ledger_line,schedule_line.amortization_month,schedule_line.amount,schedule.currency,schedule.prepaid_account_code,schedule.expense_account_code,evidence,btrim(p_reason),actor,p_request_hash);
  payload:=jsonb_build_object('insurance_prepaid_amortization_review_id',review_id,'source_document_id',source.source_document_id,'schedule_line_id',p_schedule_line,'period_id',p_period,'amount',to_char(schedule_line.amount,'FM999999999999990.0000'),'evidence_hash',evidence,'status','INDEPENDENTLY_REVIEWED','can_create_draft',false,'can_submit',false,'can_approve',false,'can_post',false);
  INSERT INTO audit_event(tenant_id,entity_id,event_type,object_type,object_id,action,actor_id,actor_type,permission_used,request_id,correlation_id,idempotency_key,after_hash,reason,metadata) VALUES(p_tenant,p_entity,'INSURANCE_PREPAID_AMORTIZATION_REVIEWED','INSURANCE_PREPAID_AMORTIZATION_REVIEW',review_id,'REVIEW',actor,'USER','PREPAID.AMORTIZATION.REVIEW',p_idempotency_key,p_idempotency_key,p_idempotency_key,evidence,btrim(p_reason),payload);
  INSERT INTO outbox_event(tenant_id,entity_id,aggregate_type,aggregate_id,event_type,payload,payload_hash) VALUES(p_tenant,p_entity,'INSURANCE_PREPAID_AMORTIZATION_REVIEW',review_id,'INSURANCE_PREPAID_AMORTIZATION_REVIEWED',payload,refs_jsonb_hash(payload));
  result:=payload||jsonb_build_object('idempotent',false);UPDATE idempotency_receipt SET status='SUCCEEDED',response_status=201,response_body=result,completed_at=clock_timestamp() WHERE idempotency_receipt_id=idem.idempotency_receipt_id;RETURN result;
END;$$;

CREATE FUNCTION refs_create_insurance_prepaid_amortization_draft_hash(p_tenant uuid,p_entity uuid,p_review uuid,p_expected_evidence_hash text,p_reason text) RETURNS text LANGUAGE sql IMMUTABLE SET search_path=pg_catalog,public,pg_temp AS $$
  SELECT refs_jsonb_hash(jsonb_build_object('tenant_id',p_tenant,'entity_id',p_entity,'insurance_prepaid_amortization_review_id',p_review,'expected_evidence_hash',p_expected_evidence_hash,'reason',btrim(p_reason)))
$$;

CREATE FUNCTION refs_create_insurance_prepaid_amortization_draft(p_tenant uuid,p_entity uuid,p_review uuid,p_expected_evidence_hash text,p_reason text,p_idempotency_key text,p_request_hash text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE actor text:=refs_current_actor(); idem idempotency_receipt; review insurance_prepaid_amortization_review; source source_document; period accounting_period; schedule ai_amortization_schedule; schedule_line ai_amortization_schedule_line; setting setting_snapshot; mapping mapping_snapshot;
DECLARE import_id uuid:=gen_random_uuid(); raw_id uuid:=gen_random_uuid(); derived_document_id uuid:=gen_random_uuid(); rule_id uuid:=gen_random_uuid(); staging_id uuid:=gen_random_uuid(); bridge_id uuid:=gen_random_uuid(); journal_id uuid; expense_line_id uuid; prepaid_line_id uuid;
DECLARE journal_number text; description text; record_id text; derived_hash text; input_digest text; evaluation_digest text; lines jsonb; auto_hash text; auto_result jsonb; evidence text; payload jsonb; result jsonb; source_entity text;
BEGIN
  PERFORM refs_assert_scope(p_tenant,p_entity,'PREPAID.AMORTIZATION.DRAFT');PERFORM refs_assert_scope(p_tenant,p_entity,'GL.JE.AUTO.CREATE');
  IF actor IS NULL THEN RAISE EXCEPTION 'Authenticated insurance amortization Draft maker missing' USING ERRCODE='42501'; END IF;
  IF p_request_hash IS DISTINCT FROM refs_create_insurance_prepaid_amortization_draft_hash(p_tenant,p_entity,p_review,p_expected_evidence_hash,p_reason) OR p_expected_evidence_hash!~'^sha256:[0-9a-f]{64}$' OR COALESCE(length(btrim(p_reason)),0) NOT BETWEEN 8 AND 2000 THEN RAISE EXCEPTION 'Insurance amortization Draft request is not canonical' USING ERRCODE='22023'; END IF;
  INSERT INTO idempotency_receipt(tenant_id,operation_scope,idempotency_key,request_hash,status,actor_id) VALUES(p_tenant,'INSURANCE_PREPAID_AMORTIZATION_DRAFT:'||p_entity,p_idempotency_key,p_request_hash,'IN_PROGRESS',actor) ON CONFLICT DO NOTHING;
  SELECT * INTO idem FROM idempotency_receipt WHERE tenant_id=p_tenant AND operation_scope='INSURANCE_PREPAID_AMORTIZATION_DRAFT:'||p_entity AND idempotency_key=p_idempotency_key FOR UPDATE;
  IF idem.request_hash<>p_request_hash THEN RAISE EXCEPTION 'Idempotency key reused with a different insurance amortization Draft' USING ERRCODE='23505'; END IF;IF idem.status='SUCCEEDED' THEN RETURN idem.response_body||jsonb_build_object('idempotent',true);END IF;
  SELECT * INTO review FROM insurance_prepaid_amortization_review WHERE tenant_id=p_tenant AND entity_id=p_entity AND insurance_prepaid_amortization_review_id=p_review FOR SHARE;
  IF review.insurance_prepaid_amortization_review_id IS NULL OR review.evidence_hash<>p_expected_evidence_hash THEN RAISE EXCEPTION 'Reviewed insurance amortization evidence is missing or changed' USING ERRCODE='40001'; END IF;
  IF actor=review.reviewed_by THEN RAISE EXCEPTION 'Insurance amortization maker and reviewer must be different actors' USING ERRCODE='42501'; END IF;
  SELECT * INTO source FROM source_document WHERE tenant_id=p_tenant AND entity_id=p_entity AND source_document_id=review.source_document_id FOR SHARE;SELECT * INTO period FROM accounting_period WHERE tenant_id=p_tenant AND entity_id=p_entity AND period_id=review.period_id FOR SHARE;SELECT * INTO schedule FROM ai_amortization_schedule WHERE tenant_id=p_tenant AND entity_id=p_entity AND ai_amortization_schedule_id=review.ai_amortization_schedule_id FOR SHARE;SELECT * INTO schedule_line FROM ai_amortization_schedule_line WHERE tenant_id=p_tenant AND entity_id=p_entity AND ai_amortization_schedule_line_id=review.ai_amortization_schedule_line_id FOR SHARE;SELECT * INTO setting FROM setting_snapshot WHERE tenant_id=p_tenant AND entity_id=p_entity AND setting_snapshot_id=review.amortization_setting_snapshot_id FOR SHARE;SELECT * INTO mapping FROM mapping_snapshot WHERE tenant_id=p_tenant AND entity_id=p_entity AND mapping_snapshot_id=review.prepaid_mapping_snapshot_id FOR SHARE;
  IF period.status<>'OPEN' THEN RAISE EXCEPTION 'Insurance amortization Draft period must be OPEN' USING ERRCODE='55000'; END IF;
  IF source.status<>'POSTED' OR source.payload_hash<>review.source_payload_hash OR source.version<review.source_document_version OR schedule.source_document_version<>review.source_document_version OR schedule.proposal_hash<>review.proposal_hash OR schedule_line.amount<>review.amount OR schedule_line.amortization_month<>review.amortization_month OR setting.snapshot_hash<>review.amortization_setting_snapshot_hash OR setting.snapshot->>'rule_id'<>'PREPAID_AMORTIZATION_V1' OR setting.snapshot->>'frequency'<>'MONTHLY' OR mapping.snapshot_hash<>review.prepaid_mapping_snapshot_hash OR mapping.output_rules->>'classification'<>'PREPAID' OR mapping.output_rules->>'prepaid_type'<>'INSURANCE' OR EXISTS(SELECT 1 FROM insurance_prepaid_amortization_draft_evidence WHERE tenant_id=p_tenant AND entity_id=p_entity AND ai_amortization_schedule_line_id=review.ai_amortization_schedule_line_id) THEN RAISE EXCEPTION 'Reviewed insurance amortization chain is changed or already drafted' USING ERRCODE='23514'; END IF;
  PERFORM 1 FROM account_master WHERE tenant_id=p_tenant AND entity_id=p_entity AND account_code IN(review.expense_account_code,review.prepaid_account_code) AND active GROUP BY tenant_id,entity_id HAVING count(*)=2;IF NOT FOUND THEN RAISE EXCEPTION 'Insurance amortization accounts are inactive or missing' USING ERRCODE='23503';END IF;
  SELECT source_entity_id INTO source_entity FROM entity WHERE tenant_id=p_tenant AND entity_id=p_entity FOR SHARE;record_id:='AMORT-'||replace(review.ai_amortization_schedule_line_id::text,'-','');derived_hash:=refs_jsonb_hash(jsonb_build_object('schema_version','INSURANCE_AMORTIZATION_OCCURRENCE_V1','review_id',p_review,'review_evidence_hash',review.evidence_hash,'signed_source_document_id',review.source_document_id,'schedule_line_id',review.ai_amortization_schedule_line_id,'period_id',review.period_id,'amount',to_char(review.amount,'FM999999999999990.0000')));
  INSERT INTO import_batch(import_batch_id,tenant_id,connector_code,source_module,source_entity_id,idempotency_key,request_hash,status,row_count,started_at,completed_at) VALUES(import_id,p_tenant,'REFS_AMORTIZATION','payable',source_entity,'derived-'||p_idempotency_key,derived_hash,'SUCCEEDED',1,clock_timestamp(),clock_timestamp());
  INSERT INTO raw_event(raw_event_id,tenant_id,entity_id,import_batch_id,source_system,source_module,source_entity_id,source_record_id,source_version,event_type,occurred_at,payload_hash,payload_ref,correlation_id) VALUES(raw_id,p_tenant,p_entity,import_id,'WBS','payable',source_entity,record_id,review.evidence_hash,'UPSERT',period.ends_on::timestamptz,derived_hash,'object://refs-derived/amortization/'||p_review,p_idempotency_key);
  INSERT INTO source_document(source_document_id,tenant_id,entity_id,raw_event_id,source_system,source_module,source_entity_id,source_record_id,source_version,document_type,document_no,business_date,accounting_date,currency,gross_amount,status,source_ref,payload_hash) VALUES(derived_document_id,p_tenant,p_entity,raw_id,'WBS','payable',source_entity,record_id,review.evidence_hash,'INSURANCE_AMORTIZATION',record_id,review.amortization_month,period.ends_on,review.currency,review.amount,'READY_FOR_DRAFT','object://refs-derived/amortization/'||p_review,derived_hash);
  INSERT INTO source_document_line(tenant_id,entity_id,source_document_id,source_line_id,line_no,amount,direction,description) VALUES(p_tenant,p_entity,derived_document_id,'AMORTIZATION',1,review.amount,'DEBIT','Reviewed monthly insurance amortization occurrence');
  input_digest:=review.evidence_hash;evaluation_digest:=refs_rule_evaluation_hash(derived_document_id,review.amortization_setting_snapshot_id,review.prepaid_mapping_snapshot_id,'PREPAID_AMORTIZATION_V1',1,jsonb_build_object('signed_source_document_id',review.source_document_id,'schedule_line_id',review.ai_amortization_schedule_line_id),jsonb_build_object('expense_account_code',review.expense_account_code,'prepaid_account_code',review.prepaid_account_code,'amount',to_char(review.amount,'FM999999999999990.0000')),input_digest);
  INSERT INTO rule_evaluation(rule_evaluation_id,tenant_id,source_document_id,setting_snapshot_id,mapping_snapshot_id,rule_code,rule_version,matched_facts,result,confidence,reason,input_digest,evaluation_digest,evaluated_at) VALUES(rule_id,p_tenant,derived_document_id,review.amortization_setting_snapshot_id,review.prepaid_mapping_snapshot_id,'PREPAID_AMORTIZATION_V1',1,jsonb_build_object('signed_source_document_id',review.source_document_id,'schedule_line_id',review.ai_amortization_schedule_line_id),jsonb_build_object('expense_account_code',review.expense_account_code,'prepaid_account_code',review.prepaid_account_code,'amount',to_char(review.amount,'FM999999999999990.0000')),1,btrim(p_reason),input_digest,evaluation_digest,period.ends_on::timestamptz);
  INSERT INTO staging_item(staging_item_id,tenant_id,entity_id,source_document_id,setting_snapshot_id,mapping_snapshot_id,rule_evaluation_id,status,version,reviewed_by,reviewed_at) VALUES(staging_id,p_tenant,p_entity,derived_document_id,review.amortization_setting_snapshot_id,review.prepaid_mapping_snapshot_id,rule_id,'READY_FOR_DRAFT',0,review.reviewed_by,review.reviewed_at);
  INSERT INTO source_link(tenant_id,entity_id,link_type,raw_event_id,source_document_id,staging_item_id,created_by) VALUES(p_tenant,p_entity,'DERIVED_AMORTIZATION_OCCURRENCE',raw_id,derived_document_id,staging_id,actor);
  journal_number:='INS-AMORT-'||replace(review.ai_amortization_schedule_line_id::text,'-','');description:='Insurance amortization '||to_char(review.amortization_month,'YYYY-MM');lines:=jsonb_build_array(jsonb_build_object('line_no',1,'account_code',review.expense_account_code,'debit_amount',review.amount,'credit_amount',0,'description',description,'dimensions','{}'::jsonb),jsonb_build_object('line_no',2,'account_code',review.prepaid_account_code,'debit_amount',0,'credit_amount',review.amount,'description',description,'dimensions','{}'::jsonb));auto_hash:=refs_create_auto_journal_hash(p_tenant,p_entity,staging_id,review.period_id,0,journal_number,description,lines);auto_result:=refs_create_auto_journal(p_tenant,p_entity,staging_id,review.period_id,0,journal_number,description,lines,'INSURANCE-AMORT:'||p_idempotency_key,auto_hash);journal_id:=(auto_result->>'journal_entry_id')::uuid;
  SELECT journal_line_id INTO expense_line_id FROM journal_line WHERE tenant_id=p_tenant AND entity_id=p_entity AND journal_entry_id=journal_id AND line_no=1;SELECT journal_line_id INTO prepaid_line_id FROM journal_line WHERE tenant_id=p_tenant AND entity_id=p_entity AND journal_entry_id=journal_id AND line_no=2;
  INSERT INTO source_link(tenant_id,entity_id,link_type,source_document_id,journal_entry_id,created_by) VALUES(p_tenant,p_entity,'SIGNED_SOURCE_TO_AMORTIZATION_JE',review.source_document_id,journal_id,actor);
  evidence:=refs_jsonb_hash(jsonb_build_object('review_id',p_review,'review_evidence_hash',review.evidence_hash,'source_document_id',review.source_document_id,'derived_raw_event_id',raw_id,'derived_source_document_id',derived_document_id,'derived_staging_item_id',staging_id,'schedule_line_id',review.ai_amortization_schedule_line_id,'journal_entry_id',journal_id,'expense_journal_line_id',expense_line_id,'prepaid_journal_line_id',prepaid_line_id,'amount',to_char(review.amount,'FM999999999999990.0000')));
  INSERT INTO insurance_prepaid_amortization_draft_evidence(insurance_prepaid_amortization_draft_evidence_id,tenant_id,entity_id,insurance_prepaid_amortization_review_id,source_document_id,ai_amortization_schedule_line_id,journal_entry_id,derived_raw_event_id,derived_source_document_id,derived_staging_item_id,expense_journal_line_id,prepaid_journal_line_id,evidence_hash,request_hash,maker_reason,created_by) VALUES(bridge_id,p_tenant,p_entity,p_review,review.source_document_id,review.ai_amortization_schedule_line_id,journal_id,raw_id,derived_document_id,staging_id,expense_line_id,prepaid_line_id,evidence,p_request_hash,btrim(p_reason),actor);
  payload:=jsonb_build_object('insurance_prepaid_amortization_draft_evidence_id',bridge_id,'insurance_prepaid_amortization_review_id',p_review,'source_document_id',review.source_document_id,'derived_source_document_id',derived_document_id,'derived_staging_item_id',staging_id,'journal_entry_id',journal_id,'expense_journal_line_id',expense_line_id,'prepaid_journal_line_id',prepaid_line_id,'amount',to_char(review.amount,'FM999999999999990.0000'),'status','DRAFT','journal_type','AUTO','revision',0,'evidence_hash',evidence,'can_create_draft',false,'can_submit',false,'can_review',false,'can_approve',false,'can_post',false);
  INSERT INTO audit_event(tenant_id,entity_id,event_type,object_type,object_id,action,actor_id,actor_type,permission_used,request_id,correlation_id,idempotency_key,after_hash,reason,metadata) VALUES(p_tenant,p_entity,'INSURANCE_PREPAID_AMORTIZATION_DRAFT_CREATED','JOURNAL_ENTRY',journal_id,'CREATE_DRAFT',actor,'USER','PREPAID.AMORTIZATION.DRAFT',p_idempotency_key,p_idempotency_key,p_idempotency_key,evidence,btrim(p_reason),payload);
  INSERT INTO outbox_event(tenant_id,entity_id,aggregate_type,aggregate_id,event_type,payload,payload_hash) VALUES(p_tenant,p_entity,'JOURNAL_ENTRY',journal_id,'INSURANCE_PREPAID_AMORTIZATION_DRAFT_CREATED',payload,refs_jsonb_hash(payload));
  result:=payload||jsonb_build_object('idempotent',false);UPDATE idempotency_receipt SET status='SUCCEEDED',response_status=201,response_body=result,completed_at=clock_timestamp() WHERE idempotency_receipt_id=idem.idempotency_receipt_id;RETURN result;
END;$$;

REVOKE ALL ON insurance_prepaid_amortization_review,insurance_prepaid_amortization_draft_evidence FROM PUBLIC,refs_app;
REVOKE ALL ON FUNCTION refs_review_insurance_prepaid_amortization_hash(uuid,uuid,uuid,uuid,uuid,uuid,uuid,uuid,uuid,uuid,text,text,text,text),refs_review_insurance_prepaid_amortization(uuid,uuid,uuid,uuid,uuid,uuid,uuid,uuid,uuid,uuid,text,text,text,text,text,text),refs_create_insurance_prepaid_amortization_draft_hash(uuid,uuid,uuid,text,text),refs_create_insurance_prepaid_amortization_draft(uuid,uuid,uuid,text,text,text,text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION refs_review_insurance_prepaid_amortization_hash(uuid,uuid,uuid,uuid,uuid,uuid,uuid,uuid,uuid,uuid,text,text,text,text),refs_review_insurance_prepaid_amortization(uuid,uuid,uuid,uuid,uuid,uuid,uuid,uuid,uuid,uuid,text,text,text,text,text,text),refs_create_insurance_prepaid_amortization_draft_hash(uuid,uuid,uuid,text,text),refs_create_insurance_prepaid_amortization_draft(uuid,uuid,uuid,text,text,text,text) TO refs_app;

COMMIT;
