BEGIN;

INSERT INTO permission_catalog(permission_code,domain,risk_class,sod_class) VALUES
 ('WBS.PROPERTY.RENT.REVIEW','WBS','HIGH','WBS_PROPERTY_RENT_REVIEWER'),
 ('WBS.PROPERTY.RENT.DRAFT','WBS','HIGH','WBS_PROPERTY_RENT_DRAFTER')
ON CONFLICT(permission_code) DO UPDATE SET active=true,domain=EXCLUDED.domain,risk_class=EXCLUDED.risk_class,sod_class=EXCLUDED.sod_class,version=permission_catalog.version+1,effective_to=NULL;

CREATE TABLE wbs_property_rent_review_evidence(
 wbs_property_rent_review_evidence_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,entity_id uuid NOT NULL,
 wbs_property_rent_source_admission_id uuid NOT NULL,wbs_inbound_row_id uuid NOT NULL,source_document_id uuid NOT NULL,staging_item_id uuid NOT NULL,
 rule_evaluation_id uuid NOT NULL,setting_snapshot_id uuid NOT NULL,mapping_snapshot_id uuid NOT NULL,period_id uuid NOT NULL,
 evidence_hash text NOT NULL CHECK(evidence_hash~'^sha256:[0-9a-f]{64}$'),reviewed_by text NOT NULL,review_reason text NOT NULL CHECK(length(btrim(review_reason)) BETWEEN 8 AND 2000),
 request_hash text NOT NULL CHECK(request_hash~'^sha256:[0-9a-f]{64}$'),created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
 UNIQUE(tenant_id,entity_id,wbs_property_rent_review_evidence_id),UNIQUE(tenant_id,entity_id,wbs_property_rent_source_admission_id),UNIQUE(tenant_id,entity_id,wbs_inbound_row_id),UNIQUE(tenant_id,entity_id,source_document_id),UNIQUE(tenant_id,entity_id,staging_item_id),
 FOREIGN KEY(tenant_id,entity_id) REFERENCES entity(tenant_id,entity_id),
 FOREIGN KEY(tenant_id,entity_id,wbs_property_rent_source_admission_id) REFERENCES wbs_property_rent_source_admission(tenant_id,entity_id,wbs_property_rent_source_admission_id),
 FOREIGN KEY(tenant_id,entity_id,wbs_inbound_row_id) REFERENCES wbs_inbound_row(tenant_id,entity_id,wbs_inbound_row_id),
 FOREIGN KEY(tenant_id,entity_id,source_document_id) REFERENCES source_document(tenant_id,entity_id,source_document_id),
 FOREIGN KEY(tenant_id,entity_id,staging_item_id) REFERENCES staging_item(tenant_id,entity_id,staging_item_id),
 FOREIGN KEY(tenant_id,rule_evaluation_id) REFERENCES rule_evaluation(tenant_id,rule_evaluation_id),
 FOREIGN KEY(tenant_id,setting_snapshot_id) REFERENCES setting_snapshot(tenant_id,setting_snapshot_id),
 FOREIGN KEY(tenant_id,mapping_snapshot_id) REFERENCES mapping_snapshot(tenant_id,mapping_snapshot_id),
 FOREIGN KEY(tenant_id,entity_id,period_id) REFERENCES accounting_period(tenant_id,entity_id,period_id)
);
CREATE TABLE wbs_property_rent_draft_evidence(
 wbs_property_rent_draft_evidence_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,entity_id uuid NOT NULL,
 wbs_property_rent_review_evidence_id uuid NOT NULL,source_document_id uuid NOT NULL,staging_item_id uuid NOT NULL,business_document_id uuid NOT NULL,journal_entry_id uuid NOT NULL,
 mapping_snapshot_id uuid NOT NULL,evidence_hash text NOT NULL CHECK(evidence_hash~'^sha256:[0-9a-f]{64}$'),created_by text NOT NULL,
 request_hash text NOT NULL CHECK(request_hash~'^sha256:[0-9a-f]{64}$'),created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
 UNIQUE(tenant_id,entity_id,wbs_property_rent_review_evidence_id),UNIQUE(tenant_id,entity_id,source_document_id),UNIQUE(tenant_id,entity_id,staging_item_id),UNIQUE(tenant_id,entity_id,business_document_id),UNIQUE(tenant_id,entity_id,journal_entry_id),
 FOREIGN KEY(tenant_id,entity_id) REFERENCES entity(tenant_id,entity_id),
 FOREIGN KEY(tenant_id,entity_id,wbs_property_rent_review_evidence_id) REFERENCES wbs_property_rent_review_evidence(tenant_id,entity_id,wbs_property_rent_review_evidence_id),
 FOREIGN KEY(tenant_id,entity_id,source_document_id) REFERENCES source_document(tenant_id,entity_id,source_document_id),
 FOREIGN KEY(tenant_id,entity_id,staging_item_id) REFERENCES staging_item(tenant_id,entity_id,staging_item_id),
 FOREIGN KEY(tenant_id,entity_id,business_document_id) REFERENCES business_document(tenant_id,entity_id,business_document_id),
 FOREIGN KEY(tenant_id,entity_id,journal_entry_id) REFERENCES journal_entry(tenant_id,entity_id,journal_entry_id),
 FOREIGN KEY(tenant_id,mapping_snapshot_id) REFERENCES mapping_snapshot(tenant_id,mapping_snapshot_id)
);
ALTER TABLE wbs_property_rent_review_evidence ENABLE ROW LEVEL SECURITY;ALTER TABLE wbs_property_rent_draft_evidence ENABLE ROW LEVEL SECURITY;
CREATE POLICY wbs_property_rent_review_evidence_scope ON wbs_property_rent_review_evidence USING(tenant_id=refs_current_tenant() AND refs_entity_allowed(entity_id)) WITH CHECK(tenant_id=refs_current_tenant() AND refs_entity_allowed(entity_id));
CREATE POLICY wbs_property_rent_draft_evidence_scope ON wbs_property_rent_draft_evidence USING(tenant_id=refs_current_tenant() AND refs_entity_allowed(entity_id)) WITH CHECK(tenant_id=refs_current_tenant() AND refs_entity_allowed(entity_id));
CREATE TRIGGER wbs_property_rent_review_evidence_append_only BEFORE UPDATE OR DELETE ON wbs_property_rent_review_evidence FOR EACH ROW EXECUTE FUNCTION reject_mutation();
CREATE TRIGGER wbs_property_rent_draft_evidence_append_only BEFORE UPDATE OR DELETE ON wbs_property_rent_draft_evidence FOR EACH ROW EXECUTE FUNCTION reject_mutation();

CREATE FUNCTION refs_review_wbs_property_rent_hash(p_tenant uuid,p_entity uuid,p_admission uuid,p_period uuid,p_expected_evidence_hash text,p_reason text) RETURNS text
LANGUAGE sql IMMUTABLE SET search_path=pg_catalog,public,pg_temp AS $$ SELECT refs_jsonb_hash(jsonb_build_object('tenant_id',p_tenant,'entity_id',p_entity,'admission_id',p_admission,'period_id',p_period,'expected_evidence_hash',p_expected_evidence_hash,'reason',btrim(p_reason))) $$;

CREATE FUNCTION refs_review_wbs_property_rent(p_tenant uuid,p_entity uuid,p_admission uuid,p_period uuid,p_expected_evidence_hash text,p_reason text,p_idempotency_key text,p_request_hash text) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE actor text:=refs_current_actor();idem idempotency_receipt;admission wbs_property_rent_source_admission;source source_document;staging staging_item;setting setting_snapshot;mapping mapping_snapshot;period accounting_period;entity_row entity;
DECLARE mapping_keys jsonb;matched jsonb;result jsonb;input_digest text;evaluation_digest text;rule_id uuid:=gen_random_uuid();review_id uuid:=gen_random_uuid();response jsonb;event_payload jsonb;
DECLARE setting_count integer;mapping_count integer;revenue_account text;control_account text;customer_name text;due_days integer;rule_code text;rule_version bigint;
BEGIN
 PERFORM refs_assert_scope(p_tenant,p_entity,'WBS.PROPERTY.RENT.REVIEW');
 IF actor IS NULL OR p_request_hash<>refs_review_wbs_property_rent_hash(p_tenant,p_entity,p_admission,p_period,p_expected_evidence_hash,p_reason) OR p_expected_evidence_hash!~'^sha256:[0-9a-f]{64}$' OR coalesce(length(btrim(p_reason)),0) NOT BETWEEN 8 AND 2000 THEN RAISE EXCEPTION 'Property Rent review request is invalid' USING ERRCODE='22023';END IF;
 INSERT INTO idempotency_receipt(tenant_id,operation_scope,idempotency_key,request_hash,status,actor_id) VALUES(p_tenant,'WBS_PROPERTY_RENT_REVIEW:'||p_entity,p_idempotency_key,p_request_hash,'IN_PROGRESS',actor) ON CONFLICT DO NOTHING;
 SELECT * INTO idem FROM idempotency_receipt WHERE tenant_id=p_tenant AND operation_scope='WBS_PROPERTY_RENT_REVIEW:'||p_entity AND idempotency_key=p_idempotency_key FOR UPDATE;
 IF idem.request_hash<>p_request_hash THEN RAISE EXCEPTION 'Property Rent review idempotency conflict' USING ERRCODE='23505';END IF;IF idem.status='SUCCEEDED' THEN RETURN idem.response_body||jsonb_build_object('idempotent',true);END IF;
 SELECT * INTO admission FROM wbs_property_rent_source_admission WHERE tenant_id=p_tenant AND entity_id=p_entity AND wbs_property_rent_source_admission_id=p_admission FOR SHARE;
 IF NOT FOUND OR admission.evidence_hash<>p_expected_evidence_hash THEN RAISE EXCEPTION 'Property Rent admission is missing or changed' USING ERRCODE='40001';END IF;
 IF actor=admission.admitted_by THEN RAISE EXCEPTION 'Property Rent admission and review require different actors' USING ERRCODE='42501';END IF;
 SELECT * INTO source FROM source_document WHERE tenant_id=p_tenant AND entity_id=p_entity AND source_document_id=admission.source_document_id FOR UPDATE;
 SELECT * INTO staging FROM staging_item WHERE tenant_id=p_tenant AND entity_id=p_entity AND staging_item_id=admission.staging_item_id FOR UPDATE;
 SELECT * INTO period FROM accounting_period WHERE tenant_id=p_tenant AND entity_id=p_entity AND period_id=p_period AND status='OPEN' AND source.accounting_date BETWEEN starts_on AND ends_on FOR SHARE;
 SELECT * INTO entity_row FROM entity WHERE tenant_id=p_tenant AND entity_id=p_entity AND active FOR SHARE;
 IF source.source_document_id IS NULL OR staging.staging_item_id IS NULL OR period.period_id IS NULL OR entity_row.entity_id IS NULL OR source.status<>'PENDING_REVIEW' OR staging.status<>'PENDING_REVIEW' OR staging.version<>0 OR source.document_type<>'WBS_PROPERTY_RENT_CHARGE' OR source.source_system<>'WBS' OR source.currency<>entity_row.base_currency OR source.gross_amount<=0 OR source.source_record_id IS DISTINCT FROM (SELECT source_record_id FROM wbs_inbound_row WHERE wbs_inbound_row_id=admission.wbs_inbound_row_id) THEN RAISE EXCEPTION 'Property Rent review scope, currency, version, or state is invalid' USING ERRCODE='23514';END IF;
 mapping_keys:=jsonb_build_object('company_key',entity_row.source_entity_id,'currency',source.currency,'property_ref',admission.property_ref,'unit_ref',admission.unit_ref,'lease_ref',admission.lease_ref,'tenant_ref',admission.tenant_ref);
 SELECT count(*) INTO setting_count FROM setting_snapshot s WHERE s.tenant_id=p_tenant AND s.entity_id=p_entity AND s.family='WBS_PROPERTY_RENT_REVIEW' AND s.scope_type='ENTITY' AND s.scope_key=p_entity::text AND s.status='APPROVED' AND source.accounting_date::timestamp AT TIME ZONE 'UTC'>=s.effective_from AND (s.effective_to IS NULL OR source.accounting_date::timestamp AT TIME ZONE 'UTC'<s.effective_to) AND s.snapshot_hash=refs_jsonb_hash(s.snapshot);
 IF setting_count<>1 THEN RAISE EXCEPTION 'Property Rent review requires exactly one server-resolved approved setting' USING ERRCODE='23514';END IF;
 SELECT * INTO setting FROM setting_snapshot s WHERE s.tenant_id=p_tenant AND s.entity_id=p_entity AND s.family='WBS_PROPERTY_RENT_REVIEW' AND s.scope_type='ENTITY' AND s.scope_key=p_entity::text AND s.status='APPROVED' AND source.accounting_date::timestamp AT TIME ZONE 'UTC'>=s.effective_from AND (s.effective_to IS NULL OR source.accounting_date::timestamp AT TIME ZONE 'UTC'<s.effective_to) AND s.snapshot_hash=refs_jsonb_hash(s.snapshot) FOR SHARE;
 SELECT count(*) INTO mapping_count FROM mapping_snapshot m WHERE m.tenant_id=p_tenant AND m.entity_id=p_entity AND m.family='WBS_PROPERTY_RENT_PICKUP' AND m.scope_type='ENTITY' AND m.scope_key=p_entity::text AND m.status='APPROVED' AND m.input_keys=mapping_keys AND m.input_key_hash=refs_jsonb_hash(mapping_keys) AND m.snapshot_hash=refs_jsonb_hash(jsonb_build_object('input_keys',m.input_keys,'output_rules',m.output_rules)) AND source.accounting_date::timestamp AT TIME ZONE 'UTC'>=m.effective_from AND (m.effective_to IS NULL OR source.accounting_date::timestamp AT TIME ZONE 'UTC'<m.effective_to) AND NOT EXISTS(SELECT 1 FROM mapping_snapshot h WHERE h.tenant_id=m.tenant_id AND h.family=m.family AND h.scope_type=m.scope_type AND h.scope_key=m.scope_key AND h.input_key_hash=m.input_key_hash AND h.status='APPROVED' AND h.priority>m.priority AND source.accounting_date::timestamp AT TIME ZONE 'UTC'>=h.effective_from AND (h.effective_to IS NULL OR source.accounting_date::timestamp AT TIME ZONE 'UTC'<h.effective_to));
 IF mapping_count<>1 THEN RAISE EXCEPTION 'Property Rent review requires exactly one highest-priority server-resolved mapping' USING ERRCODE='23514';END IF;
 SELECT * INTO mapping FROM mapping_snapshot m WHERE m.tenant_id=p_tenant AND m.entity_id=p_entity AND m.family='WBS_PROPERTY_RENT_PICKUP' AND m.scope_type='ENTITY' AND m.scope_key=p_entity::text AND m.status='APPROVED' AND m.input_keys=mapping_keys AND m.input_key_hash=refs_jsonb_hash(mapping_keys) AND m.snapshot_hash=refs_jsonb_hash(jsonb_build_object('input_keys',m.input_keys,'output_rules',m.output_rules)) AND source.accounting_date::timestamp AT TIME ZONE 'UTC'>=m.effective_from AND (m.effective_to IS NULL OR source.accounting_date::timestamp AT TIME ZONE 'UTC'<m.effective_to) ORDER BY m.priority DESC LIMIT 1 FOR SHARE;
 IF actor IN(setting.created_by,setting.approved_by,mapping.created_by,mapping.approved_by) THEN RAISE EXCEPTION 'Property Rent review conflicts with configuration duties' USING ERRCODE='42501';END IF;
 control_account:=btrim(mapping.output_rules->>'receivable_account_code');revenue_account:=btrim(mapping.output_rules->>'revenue_account_code');due_days:=(mapping.output_rules->>'due_days')::integer;rule_code:=btrim(mapping.output_rules->>'rule_code');rule_version:=(mapping.output_rules->>'rule_version')::bigint;
 SELECT display_name INTO customer_name FROM member_master WHERE tenant_id=p_tenant AND entity_id=p_entity AND member_ref=admission.tenant_ref AND member_type='CUSTOMER' AND active FOR SHARE;
 IF control_account<>'120200' OR revenue_account='' OR revenue_account=control_account OR due_days NOT BETWEEN 0 AND 365 OR rule_code='' OR rule_version<1 OR customer_name IS NULL OR (SELECT count(*) FROM account_master WHERE tenant_id=p_tenant AND entity_id=p_entity AND account_code IN(control_account,revenue_account) AND active)<>2 THEN RAISE EXCEPTION 'Property Rent mapping output, customer, or accounts are invalid' USING ERRCODE='23514';END IF;
 matched:=mapping_keys||jsonb_build_object('source_version',admission.source_version,'receipt_hash',admission.receipt_hash,'amount_money4',to_char(source.gross_amount,'FM9999999999999990.0000'));
 result:=jsonb_build_object('receivable_account_code',control_account,'revenue_account_code',revenue_account,'customer_ref',admission.tenant_ref,'customer_name',customer_name,'due_date',(source.accounting_date+due_days)::text,'gross_amount',to_char(source.gross_amount,'FM9999999999999990.0000'),'currency',source.currency,'period_id',p_period,'dimensions',jsonb_build_object('property_ref',admission.property_ref,'unit_ref',admission.unit_ref,'lease_ref',admission.lease_ref));
 input_digest:=admission.evidence_hash;evaluation_digest:=refs_rule_evaluation_hash(source.source_document_id,setting.setting_snapshot_id,mapping.mapping_snapshot_id,rule_code,rule_version,matched,result,input_digest);
 INSERT INTO rule_evaluation(rule_evaluation_id,tenant_id,source_document_id,setting_snapshot_id,mapping_snapshot_id,rule_code,rule_version,matched_facts,result,confidence,reason,input_digest,evaluation_digest) VALUES(rule_id,p_tenant,source.source_document_id,setting.setting_snapshot_id,mapping.mapping_snapshot_id,rule_code,rule_version,matched,result,1,btrim(p_reason),input_digest,evaluation_digest);
 UPDATE source_document SET status='READY_FOR_DRAFT' WHERE tenant_id=p_tenant AND entity_id=p_entity AND source_document_id=source.source_document_id AND status='PENDING_REVIEW';IF NOT FOUND THEN RAISE EXCEPTION 'Property Rent source review state conflict' USING ERRCODE='40001';END IF;
 UPDATE staging_item SET setting_snapshot_id=setting.setting_snapshot_id,mapping_snapshot_id=mapping.mapping_snapshot_id,rule_evaluation_id=rule_id,status='READY_FOR_DRAFT',reviewed_by=actor,reviewed_at=clock_timestamp(),updated_at=clock_timestamp() WHERE tenant_id=p_tenant AND entity_id=p_entity AND staging_item_id=staging.staging_item_id AND version=0 AND status='PENDING_REVIEW';IF NOT FOUND THEN RAISE EXCEPTION 'Property Rent staging review state conflict' USING ERRCODE='40001';END IF;
 UPDATE accounting_exception SET status='RESOLVED',resolved_by=actor,resolved_at=clock_timestamp(),resolution='Formal Property Rent review and server-resolved mapping installed' WHERE tenant_id=p_tenant AND entity_id=p_entity AND source_document_id=source.source_document_id AND staging_item_id=staging.staging_item_id AND exception_code='PROPERTY_RENT_PRODUCER_UNAVAILABLE' AND status='OPEN';IF NOT FOUND THEN RAISE EXCEPTION 'Property Rent producer exception is missing or changed' USING ERRCODE='40001';END IF;
 INSERT INTO wbs_property_rent_review_evidence(wbs_property_rent_review_evidence_id,tenant_id,entity_id,wbs_property_rent_source_admission_id,wbs_inbound_row_id,source_document_id,staging_item_id,rule_evaluation_id,setting_snapshot_id,mapping_snapshot_id,period_id,evidence_hash,reviewed_by,review_reason,request_hash) VALUES(review_id,p_tenant,p_entity,p_admission,admission.wbs_inbound_row_id,source.source_document_id,staging.staging_item_id,rule_id,setting.setting_snapshot_id,mapping.mapping_snapshot_id,p_period,admission.evidence_hash,actor,btrim(p_reason),p_request_hash);
 event_payload:=jsonb_build_object('review_evidence_id',review_id,'source_document_id',source.source_document_id,'staging_item_id',staging.staging_item_id,'mapping_snapshot_id',mapping.mapping_snapshot_id,'status','READY_FOR_DRAFT');
 INSERT INTO audit_event(tenant_id,entity_id,event_type,object_type,object_id,action,actor_id,actor_type,permission_used,idempotency_key,after_hash,reason,metadata) VALUES(p_tenant,p_entity,'WBS_PROPERTY_RENT_REVIEWED','WBS_PROPERTY_RENT_REVIEW',review_id,'REVIEW',actor,'USER','WBS.PROPERTY.RENT.REVIEW',p_idempotency_key,p_request_hash,btrim(p_reason),event_payload);
 INSERT INTO outbox_event(tenant_id,entity_id,aggregate_type,aggregate_id,event_type,payload,payload_hash) VALUES(p_tenant,p_entity,'WBS_PROPERTY_RENT_REVIEW',review_id,'WBS_PROPERTY_RENT_REVIEWED',event_payload,refs_jsonb_hash(event_payload));
 response:=event_payload||jsonb_build_object('period_id',p_period,'revision',0,'idempotent',false,'can_create_draft',true,'can_post',false);UPDATE idempotency_receipt SET status='SUCCEEDED',response_status=200,response_body=response,completed_at=clock_timestamp() WHERE idempotency_receipt_id=idem.idempotency_receipt_id;RETURN response;
END $$;

CREATE FUNCTION refs_create_wbs_property_rent_draft_hash(p_tenant uuid,p_entity uuid,p_review uuid,p_expected_evidence_hash text,p_reason text) RETURNS text LANGUAGE sql IMMUTABLE SET search_path=pg_catalog,public,pg_temp AS $$ SELECT refs_jsonb_hash(jsonb_build_object('tenant_id',p_tenant,'entity_id',p_entity,'review_evidence_id',p_review,'expected_evidence_hash',p_expected_evidence_hash,'reason',btrim(p_reason))) $$;
CREATE FUNCTION refs_create_wbs_property_rent_draft(p_tenant uuid,p_entity uuid,p_review uuid,p_expected_evidence_hash text,p_reason text,p_idempotency_key text,p_request_hash text) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE actor text:=refs_current_actor();idem idempotency_receipt;evidence wbs_property_rent_review_evidence;admission wbs_property_rent_source_admission;source source_document;staging staging_item;mapping mapping_snapshot;evaluation rule_evaluation;
DECLARE amount numeric(20,4);control_account text;revenue_account text;customer_ref text;customer_name text;due_date date;dimensions jsonb;lines jsonb;journal_number text;description text;auto_hash text;draft jsonb;business_id uuid:=gen_random_uuid();bridge_id uuid:=gen_random_uuid();response jsonb;event_payload jsonb;
BEGIN
 PERFORM refs_assert_scope(p_tenant,p_entity,'WBS.PROPERTY.RENT.DRAFT');PERFORM refs_assert_scope(p_tenant,p_entity,'AR.INVOICE.CREATE');PERFORM refs_assert_scope(p_tenant,p_entity,'GL.JE.AUTO.CREATE');
 IF actor IS NULL OR p_request_hash<>refs_create_wbs_property_rent_draft_hash(p_tenant,p_entity,p_review,p_expected_evidence_hash,p_reason) OR p_expected_evidence_hash!~'^sha256:[0-9a-f]{64}$' OR coalesce(length(btrim(p_reason)),0) NOT BETWEEN 8 AND 2000 THEN RAISE EXCEPTION 'Property Rent Draft request is invalid' USING ERRCODE='22023';END IF;
 INSERT INTO idempotency_receipt(tenant_id,operation_scope,idempotency_key,request_hash,status,actor_id) VALUES(p_tenant,'WBS_PROPERTY_RENT_DRAFT:'||p_entity,p_idempotency_key,p_request_hash,'IN_PROGRESS',actor) ON CONFLICT DO NOTHING;
 SELECT * INTO idem FROM idempotency_receipt WHERE tenant_id=p_tenant AND operation_scope='WBS_PROPERTY_RENT_DRAFT:'||p_entity AND idempotency_key=p_idempotency_key FOR UPDATE;IF idem.request_hash<>p_request_hash THEN RAISE EXCEPTION 'Property Rent Draft idempotency conflict' USING ERRCODE='23505';END IF;IF idem.status='SUCCEEDED' THEN RETURN idem.response_body||jsonb_build_object('idempotent',true);END IF;
 SELECT * INTO evidence FROM wbs_property_rent_review_evidence WHERE tenant_id=p_tenant AND entity_id=p_entity AND wbs_property_rent_review_evidence_id=p_review FOR SHARE;IF NOT FOUND OR evidence.evidence_hash<>p_expected_evidence_hash THEN RAISE EXCEPTION 'Property Rent review evidence is missing or changed' USING ERRCODE='40001';END IF;
 SELECT * INTO admission FROM wbs_property_rent_source_admission WHERE tenant_id=p_tenant AND entity_id=p_entity AND wbs_property_rent_source_admission_id=evidence.wbs_property_rent_source_admission_id FOR SHARE;
 IF actor IN(evidence.reviewed_by,admission.admitted_by) THEN RAISE EXCEPTION 'Property Rent admission, review, and Draft require independent actors' USING ERRCODE='42501';END IF;
 SELECT * INTO source FROM source_document WHERE tenant_id=p_tenant AND entity_id=p_entity AND source_document_id=evidence.source_document_id FOR SHARE;SELECT * INTO staging FROM staging_item WHERE tenant_id=p_tenant AND entity_id=p_entity AND staging_item_id=evidence.staging_item_id FOR UPDATE;SELECT * INTO mapping FROM mapping_snapshot WHERE tenant_id=p_tenant AND mapping_snapshot_id=evidence.mapping_snapshot_id FOR SHARE;SELECT * INTO evaluation FROM rule_evaluation WHERE tenant_id=p_tenant AND rule_evaluation_id=evidence.rule_evaluation_id FOR SHARE;
 IF source.source_document_id IS NULL OR staging.staging_item_id IS NULL OR mapping.mapping_snapshot_id IS NULL OR evaluation.rule_evaluation_id IS NULL OR source.status<>'READY_FOR_DRAFT' OR staging.status<>'READY_FOR_DRAFT' OR staging.version<>0 OR staging.mapping_snapshot_id<>mapping.mapping_snapshot_id OR evaluation.source_document_id<>source.source_document_id OR evaluation.mapping_snapshot_id<>mapping.mapping_snapshot_id OR evaluation.evaluation_digest<>refs_rule_evaluation_hash(evaluation.source_document_id,evaluation.setting_snapshot_id,evaluation.mapping_snapshot_id,evaluation.rule_code,evaluation.rule_version,evaluation.matched_facts,evaluation.result,evaluation.input_digest) OR mapping.snapshot_hash<>refs_jsonb_hash(jsonb_build_object('input_keys',mapping.input_keys,'output_rules',mapping.output_rules)) OR NOT refs_auto_staging_ready(p_tenant,p_entity,staging.staging_item_id,evidence.period_id) THEN RAISE EXCEPTION 'Property Rent Draft evidence chain is incomplete or changed' USING ERRCODE='23514';END IF;
 amount:=source.gross_amount;control_account:=evaluation.result->>'receivable_account_code';revenue_account:=evaluation.result->>'revenue_account_code';customer_ref:=evaluation.result->>'customer_ref';customer_name:=evaluation.result->>'customer_name';due_date:=(evaluation.result->>'due_date')::date;dimensions:=evaluation.result->'dimensions';
 IF evaluation.result->>'gross_amount' IS DISTINCT FROM to_char(amount,'FM9999999999999990.0000') OR evaluation.result->>'currency' IS DISTINCT FROM source.currency OR control_account<>'120200' OR revenue_account='' OR customer_ref<>admission.tenant_ref OR jsonb_typeof(dimensions)<>'object' OR amount<=0 THEN RAISE EXCEPTION 'Property Rent Draft MONEY4 or server-derived mapping facts changed' USING ERRCODE='23514';END IF;
 journal_number:='WBS-RENT-'||replace(p_review::text,'-','');description:='WBS Property Rent '||source.document_no;
 lines:=jsonb_build_array(jsonb_build_object('line_no',1,'account_code',control_account,'debit_amount',amount,'credit_amount',0,'member_ref',customer_ref,'description',description,'dimensions',dimensions),jsonb_build_object('line_no',2,'account_code',revenue_account,'debit_amount',0,'credit_amount',amount,'description',description,'dimensions',dimensions));
 auto_hash:=refs_create_auto_journal_hash(p_tenant,p_entity,staging.staging_item_id,evidence.period_id,0,journal_number,description,lines);draft:=refs_create_auto_journal(p_tenant,p_entity,staging.staging_item_id,evidence.period_id,0,journal_number,description,lines,'WBS-RENT:'||p_idempotency_key,auto_hash);
 INSERT INTO business_document(business_document_id,tenant_id,entity_id,source_document_id,draft_journal_entry_id,document_kind,document_number,counterparty_ref,counterparty_name,currency,accounting_date,due_date,gross_amount,open_balance,status,created_by) VALUES(business_id,p_tenant,p_entity,source.source_document_id,(draft->>'journal_entry_id')::uuid,'AR_INVOICE',source.document_no,customer_ref,customer_name,source.currency,source.accounting_date,due_date,amount,amount,'DRAFT',actor);
 INSERT INTO wbs_property_rent_draft_evidence(wbs_property_rent_draft_evidence_id,tenant_id,entity_id,wbs_property_rent_review_evidence_id,source_document_id,staging_item_id,business_document_id,journal_entry_id,mapping_snapshot_id,evidence_hash,created_by,request_hash) VALUES(bridge_id,p_tenant,p_entity,p_review,source.source_document_id,staging.staging_item_id,business_id,(draft->>'journal_entry_id')::uuid,mapping.mapping_snapshot_id,evidence.evidence_hash,actor,p_request_hash);
 event_payload:=jsonb_build_object('draft_evidence_id',bridge_id,'review_evidence_id',p_review,'source_document_id',source.source_document_id,'business_document_id',business_id,'journal_entry_id',draft->>'journal_entry_id','mapping_snapshot_id',mapping.mapping_snapshot_id,'status','DRAFT');
 INSERT INTO audit_event(tenant_id,entity_id,event_type,object_type,object_id,action,actor_id,actor_type,permission_used,idempotency_key,after_hash,reason,metadata) VALUES(p_tenant,p_entity,'WBS_PROPERTY_RENT_DRAFT_CREATED','BUSINESS_DOCUMENT',business_id,'CREATE_RENT_AR_INVOICE',actor,'USER','WBS.PROPERTY.RENT.DRAFT',p_idempotency_key,p_request_hash,btrim(p_reason),event_payload);
 INSERT INTO outbox_event(tenant_id,entity_id,aggregate_type,aggregate_id,event_type,payload,payload_hash) VALUES(p_tenant,p_entity,'BUSINESS_DOCUMENT',business_id,'WBS_PROPERTY_RENT_DRAFT_CREATED',event_payload,refs_jsonb_hash(event_payload));
 response:=event_payload||draft||jsonb_build_object('idempotent',false,'can_submit',true,'can_review',false,'can_approve',false,'can_post',false);UPDATE idempotency_receipt SET status='SUCCEEDED',response_status=201,response_body=response,completed_at=clock_timestamp() WHERE idempotency_receipt_id=idem.idempotency_receipt_id;RETURN response;
END $$;

REVOKE ALL ON wbs_property_rent_review_evidence,wbs_property_rent_draft_evidence FROM PUBLIC,refs_app;GRANT SELECT ON wbs_property_rent_review_evidence,wbs_property_rent_draft_evidence TO refs_app;
REVOKE ALL ON FUNCTION refs_review_wbs_property_rent_hash(uuid,uuid,uuid,uuid,text,text),refs_review_wbs_property_rent(uuid,uuid,uuid,uuid,text,text,text,text),refs_create_wbs_property_rent_draft_hash(uuid,uuid,uuid,text,text),refs_create_wbs_property_rent_draft(uuid,uuid,uuid,text,text,text,text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION refs_review_wbs_property_rent_hash(uuid,uuid,uuid,uuid,text,text),refs_review_wbs_property_rent(uuid,uuid,uuid,uuid,text,text,text,text),refs_create_wbs_property_rent_draft_hash(uuid,uuid,uuid,text,text),refs_create_wbs_property_rent_draft(uuid,uuid,uuid,text,text,text,text) TO refs_app;

COMMIT;
