BEGIN;
INSERT INTO permission_catalog(permission_code,domain,risk_class,sod_class) VALUES('AI.LOAN.CLASSIFY','AI_ACCOUNTING','MEDIUM','PREPARER'),('AI.LOAN.VIEW','AI_ACCOUNTING','LOW','VIEWER') ON CONFLICT(permission_code) DO UPDATE SET active=true,domain=EXCLUDED.domain,risk_class=EXCLUDED.risk_class,sod_class=EXCLUDED.sod_class,version=permission_catalog.version+1,effective_to=NULL;
CREATE TABLE ai_construction_loan_classification_evidence(
 ai_construction_loan_classification_evidence_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenant(tenant_id),entity_id uuid NOT NULL,source_document_id uuid NOT NULL,source_document_line_id uuid NOT NULL,source_payload_hash text NOT NULL CHECK(source_payload_hash~'^sha256:[0-9a-f]{64}$'),source_document_version bigint NOT NULL CHECK(source_document_version>=0),source_line_hash text NOT NULL CHECK(source_line_hash~'^sha256:[0-9a-f]{64}$'),loan_ref text NOT NULL,classification text NOT NULL CHECK(classification IN('LOAN_DRAW','INTEREST_REVIEW','PRINCIPAL_REPAYMENT','LOAN_FEE_REVIEW','ESCROW_RESERVE')),rule_id text NOT NULL,reason text NOT NULL CHECK(length(btrim(reason)) BETWEEN 8 AND 2000),confidence numeric(5,4) NOT NULL CHECK(confidence=0.9900),required_human_fields jsonb NOT NULL CHECK(jsonb_typeof(required_human_fields)='array'),entry_shape jsonb NOT NULL CHECK(jsonb_typeof(entry_shape)='array' AND jsonb_array_length(entry_shape)=2),classification_hash text NOT NULL CHECK(classification_hash~'^sha256:[0-9a-f]{64}$'),status text NOT NULL DEFAULT 'REVIEW_REQUIRED' CHECK(status='REVIEW_REQUIRED'),created_by text NOT NULL,created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
 UNIQUE(tenant_id,entity_id,source_document_line_id,source_document_version),UNIQUE(tenant_id,entity_id,classification_hash),FOREIGN KEY(tenant_id,entity_id) REFERENCES entity(tenant_id,entity_id),FOREIGN KEY(tenant_id,entity_id,source_document_id) REFERENCES source_document(tenant_id,entity_id,source_document_id),FOREIGN KEY(tenant_id,entity_id,source_document_line_id) REFERENCES source_document_line(tenant_id,entity_id,source_document_line_id));
ALTER TABLE ai_construction_loan_classification_evidence ENABLE ROW LEVEL SECURITY;CREATE POLICY ai_construction_loan_classification_evidence_scope ON ai_construction_loan_classification_evidence USING(tenant_id=refs_current_tenant() AND refs_entity_allowed(entity_id)) WITH CHECK(tenant_id=refs_current_tenant() AND refs_entity_allowed(entity_id));CREATE TRIGGER ai_construction_loan_classification_evidence_append_only BEFORE UPDATE OR DELETE ON ai_construction_loan_classification_evidence FOR EACH ROW EXECUTE FUNCTION reject_mutation();

CREATE FUNCTION refs_classify_ai_construction_loan_line(p_tenant uuid,p_entity uuid,p_source_line uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE d source_document;l source_document_line;signals integer;classification text;rule_id text;fields jsonb;shape jsonb;line_hash text;
BEGIN
 PERFORM refs_assert_scope(p_tenant,p_entity,'AI.LOAN.CLASSIFY');SELECT * INTO l FROM source_document_line WHERE tenant_id=p_tenant AND entity_id=p_entity AND source_document_line_id=p_source_line FOR SHARE;SELECT * INTO d FROM source_document WHERE tenant_id=p_tenant AND entity_id=p_entity AND source_document_id=l.source_document_id FOR SHARE;
 IF l.source_document_line_id IS NULL OR d.source_document_id IS NULL OR d.source_module<>'loan' OR d.status<>'READY_FOR_DRAFT' OR NULLIF(btrim(l.loan_ref),'') IS NULL OR l.amount<=0 OR NULLIF(btrim(l.description),'') IS NULL THEN RAISE EXCEPTION 'Loan classification requires exact ready source, loan reference, amount, and description' USING ERRCODE='23514';END IF;
 signals:=(l.description~*'\m(loan draw|construction draw|draw advance|funding advance)\M')::int+(l.description~*'\m(interest|accrued interest|interest payment)\M')::int+(l.description~*'\m(principal|loan repayment|principal payment|paydown)\M')::int+(l.description~*'\m(loan fee|financing fee|origination fee|commitment fee)\M')::int+(l.description~*'\m(escrow|reserve|interest reserve|tax reserve)\M')::int;
 IF signals<>1 THEN RAISE EXCEPTION 'Loan transaction nature is unsupported or ambiguous' USING ERRCODE='23514';END IF;
 IF l.description~*'\m(loan draw|construction draw|draw advance|funding advance)\M' THEN classification:='LOAN_DRAW';rule_id:='AI_CONSTRUCTION_LOAN_DRAW_V1';fields:='["cash_account","loan_payable_account"]';shape:='[{"side":"DEBIT","account_role":"CASH"},{"side":"CREDIT","account_role":"CONSTRUCTION_LOAN_PAYABLE"}]';IF l.direction<>'INFLOW' THEN RAISE EXCEPTION 'Loan draw direction conflicts with source' USING ERRCODE='23514';END IF;
 ELSIF l.description~*'\m(interest|accrued interest|interest payment)\M' THEN classification:='INTEREST_REVIEW';rule_id:='AI_CONSTRUCTION_LOAN_INTEREST_V1';fields:='["interest_treatment","project_status","capitalization_policy","offset_account"]';shape:='[{"side":"DEBIT","account_role":"CWIP_OR_INTEREST_EXPENSE"},{"side":"CREDIT","account_role":"CASH_OR_INTEREST_PAYABLE"}]';IF l.direction<>'OUTFLOW' THEN RAISE EXCEPTION 'Loan interest direction conflicts with source' USING ERRCODE='23514';END IF;
 ELSIF l.description~*'\m(principal|loan repayment|principal payment|paydown)\M' THEN classification:='PRINCIPAL_REPAYMENT';rule_id:='AI_CONSTRUCTION_LOAN_PRINCIPAL_V1';fields:='["loan_payable_account","cash_account"]';shape:='[{"side":"DEBIT","account_role":"CONSTRUCTION_LOAN_PAYABLE"},{"side":"CREDIT","account_role":"CASH"}]';IF l.direction<>'OUTFLOW' THEN RAISE EXCEPTION 'Loan repayment direction conflicts with source' USING ERRCODE='23514';END IF;
 ELSIF l.description~*'\m(loan fee|financing fee|origination fee|commitment fee)\M' THEN classification:='LOAN_FEE_REVIEW';rule_id:='AI_CONSTRUCTION_LOAN_FEE_V1';fields:='["fee_treatment","coverage_or_term","deferred_fee_account","expense_account"]';shape:='[{"side":"DEBIT","account_role":"DEFERRED_LOAN_COST_OR_EXPENSE"},{"side":"CREDIT","account_role":"CASH_OR_LOAN_PAYABLE"}]';IF l.direction<>'OUTFLOW' THEN RAISE EXCEPTION 'Loan fee direction conflicts with source' USING ERRCODE='23514';END IF;
 ELSE classification:='ESCROW_RESERVE';rule_id:='AI_CONSTRUCTION_LOAN_ESCROW_V1';fields:='["escrow_asset_or_liability_account","cash_or_loan_account"]';shape:='[{"side":"DEBIT_OR_CREDIT","account_role":"ESCROW_OR_RESERVE"},{"side":"OFFSET","account_role":"CASH_OR_CONSTRUCTION_LOAN_PAYABLE"}]';END IF;
 line_hash:=refs_jsonb_hash(jsonb_build_object('schema_version','AI_CONSTRUCTION_LOAN_SOURCE_LINE_V1','source_document_line_id',l.source_document_line_id,'source_line_id',l.source_line_id,'line_no',l.line_no,'amount',l.amount,'direction',l.direction,'description',l.description,'loan_ref',l.loan_ref,'bank_account_ref',l.bank_account_ref,'project_ref',l.project_ref,'property_ref',l.property_ref));
 RETURN jsonb_build_object('schema_version','AI_CONSTRUCTION_LOAN_CLASSIFICATION_V1','source_document_id',d.source_document_id,'source_document_line_id',l.source_document_line_id,'source_payload_hash',d.payload_hash,'source_document_version',d.version,'source_line_hash',line_hash,'loan_ref',btrim(l.loan_ref),'classification',classification,'rule_id',rule_id,'reason','Retained loan source evidence supports '||classification||'; accounts and policy-sensitive treatment require human review.','confidence',0.99,'required_human_fields',fields,'entry_shape',shape,'can_create_draft',false,'can_review',false,'can_approve',false,'can_post',false);
END;$$;

CREATE FUNCTION refs_materialize_ai_construction_loan_classification(p_tenant uuid,p_entity uuid,p_source_line uuid,p_expected_classification text,p_idempotency_key text,p_request_hash text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE actor text:=refs_current_actor();classified jsonb;expected_hash text;idem idempotency_receipt;evidence_id uuid:=gen_random_uuid();classification_hash text;payload jsonb;response jsonb;
BEGIN
 PERFORM refs_assert_scope(p_tenant,p_entity,'AI.LOAN.CLASSIFY');IF actor IS NULL THEN RAISE EXCEPTION 'Authenticated loan classifier missing' USING ERRCODE='42501';END IF;classified:=refs_classify_ai_construction_loan_line(p_tenant,p_entity,p_source_line);expected_hash:=refs_jsonb_hash(jsonb_build_object('schema_version','AI_CONSTRUCTION_LOAN_CLASSIFICATION_COMMAND_V1','tenant_id',p_tenant,'entity_id',p_entity,'source_document_line_id',p_source_line,'expected_classification',p_expected_classification));IF p_request_hash IS DISTINCT FROM expected_hash OR classified->>'classification' IS DISTINCT FROM p_expected_classification THEN RAISE EXCEPTION 'Loan classification command does not match authoritative source classification' USING ERRCODE='23514';END IF;
 INSERT INTO idempotency_receipt(tenant_id,operation_scope,idempotency_key,request_hash,status,actor_id) VALUES(p_tenant,'AI_CONSTRUCTION_LOAN_CLASSIFICATION:'||p_entity,p_idempotency_key,p_request_hash,'IN_PROGRESS',actor) ON CONFLICT(tenant_id,operation_scope,idempotency_key) DO NOTHING;SELECT * INTO idem FROM idempotency_receipt WHERE tenant_id=p_tenant AND operation_scope='AI_CONSTRUCTION_LOAN_CLASSIFICATION:'||p_entity AND idempotency_key=p_idempotency_key FOR UPDATE;IF idem.request_hash<>p_request_hash OR idem.actor_id IS DISTINCT FROM actor THEN RAISE EXCEPTION 'Loan classification idempotency key conflicts with payload or actor' USING ERRCODE='23505';END IF;IF idem.status='SUCCEEDED' THEN RETURN idem.response_body||jsonb_build_object('idempotent',true);END IF;
 classification_hash:=refs_jsonb_hash(classified-'can_create_draft'-'can_review'-'can_approve'-'can_post');INSERT INTO ai_construction_loan_classification_evidence(ai_construction_loan_classification_evidence_id,tenant_id,entity_id,source_document_id,source_document_line_id,source_payload_hash,source_document_version,source_line_hash,loan_ref,classification,rule_id,reason,confidence,required_human_fields,entry_shape,classification_hash,created_by) VALUES(evidence_id,p_tenant,p_entity,(classified->>'source_document_id')::uuid,p_source_line,classified->>'source_payload_hash',(classified->>'source_document_version')::bigint,classified->>'source_line_hash',classified->>'loan_ref',classified->>'classification',classified->>'rule_id',classified->>'reason',(classified->>'confidence')::numeric,classified->'required_human_fields',classified->'entry_shape',classification_hash,actor);
 payload:=classified||jsonb_build_object('ai_construction_loan_classification_evidence_id',evidence_id,'classification_hash',classification_hash,'status','REVIEW_REQUIRED');INSERT INTO audit_event(tenant_id,entity_id,event_type,object_type,object_id,action,actor_id,actor_type,permission_used,request_id,correlation_id,idempotency_key,after_hash,reason,metadata) VALUES(p_tenant,p_entity,'AI_CONSTRUCTION_LOAN_CLASSIFIED','AI_CONSTRUCTION_LOAN_CLASSIFICATION_EVIDENCE',evidence_id,'CLASSIFY',actor,'USER','AI.LOAN.CLASSIFY',p_idempotency_key,p_idempotency_key,p_idempotency_key,classification_hash,'Deterministic source-bound construction loan classification; no accounting action',payload);INSERT INTO outbox_event(tenant_id,entity_id,aggregate_type,aggregate_id,event_type,payload,payload_hash) VALUES(p_tenant,p_entity,'AI_CONSTRUCTION_LOAN_CLASSIFICATION_EVIDENCE',evidence_id,'AI_CONSTRUCTION_LOAN_CLASSIFIED',payload,refs_jsonb_hash(payload));response:=payload||jsonb_build_object('idempotent',false);UPDATE idempotency_receipt SET status='SUCCEEDED',response_status=201,response_body=response,completed_at=clock_timestamp() WHERE idempotency_receipt_id=idem.idempotency_receipt_id;RETURN response;
END;$$;
CREATE FUNCTION refs_read_ai_construction_loan_classifications(p_tenant uuid,p_entity uuid,p_limit integer DEFAULT 100) RETURNS SETOF ai_construction_loan_classification_evidence LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$ BEGIN PERFORM refs_assert_scope(p_tenant,p_entity,'AI.LOAN.VIEW');IF p_limit<1 OR p_limit>100 THEN RAISE EXCEPTION 'Loan classification limit must be between 1 and 100' USING ERRCODE='22023';END IF;RETURN QUERY SELECT e.* FROM ai_construction_loan_classification_evidence e WHERE e.tenant_id=p_tenant AND e.entity_id=p_entity ORDER BY e.created_at DESC,e.ai_construction_loan_classification_evidence_id DESC LIMIT p_limit;END;$$;
REVOKE ALL ON ai_construction_loan_classification_evidence FROM PUBLIC,refs_app;REVOKE EXECUTE ON FUNCTION refs_classify_ai_construction_loan_line(uuid,uuid,uuid),refs_materialize_ai_construction_loan_classification(uuid,uuid,uuid,text,text,text),refs_read_ai_construction_loan_classifications(uuid,uuid,integer) FROM PUBLIC;GRANT EXECUTE ON FUNCTION refs_classify_ai_construction_loan_line(uuid,uuid,uuid),refs_materialize_ai_construction_loan_classification(uuid,uuid,uuid,text,text,text),refs_read_ai_construction_loan_classifications(uuid,uuid,integer) TO refs_app;
COMMIT;
