BEGIN;
INSERT INTO permission_catalog(permission_code,domain,risk_class,sod_class) VALUES('AI.LOAN.PROPOSE','AI_ACCOUNTING','MEDIUM','PREPARER') ON CONFLICT(permission_code) DO UPDATE SET active=true,domain=EXCLUDED.domain,risk_class=EXCLUDED.risk_class,sod_class=EXCLUDED.sod_class,version=permission_catalog.version+1,effective_to=NULL;
CREATE TABLE ai_construction_loan_entry_proposal(
 ai_construction_loan_entry_proposal_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenant(tenant_id),entity_id uuid NOT NULL,ai_construction_loan_classification_evidence_id uuid NOT NULL,classification_hash text NOT NULL CHECK(classification_hash~'^sha256:[0-9a-f]{64}$'),source_document_id uuid NOT NULL,source_document_line_id uuid NOT NULL,source_payload_hash text NOT NULL CHECK(source_payload_hash~'^sha256:[0-9a-f]{64}$'),source_document_version bigint NOT NULL CHECK(source_document_version>=0),source_line_hash text NOT NULL CHECK(source_line_hash~'^sha256:[0-9a-f]{64}$'),accounting_period_id uuid NOT NULL,journal_date date NOT NULL,loan_ref text NOT NULL,classification text NOT NULL CHECK(classification IN('LOAN_DRAW','INTEREST_REVIEW','PRINCIPAL_REPAYMENT','LOAN_FEE_REVIEW','ESCROW_RESERVE')),treatment_decision text NOT NULL CHECK(treatment_decision IN('LOAN_DRAW_CASH','LOAN_DRAW_CWIP','CAPITALIZED_INTEREST','EXPENSED_INTEREST','PRINCIPAL_REPAYMENT','DEFERRED_LOAN_FEE','EXPENSED_LOAN_FEE','ESCROW_FUNDING','ESCROW_RELEASE')),debit_account_code text NOT NULL,credit_account_code text NOT NULL,currency char(3) NOT NULL CHECK(currency~'^[A-Z]{3}$'),amount numeric(20,4) NOT NULL CHECK(amount>0),member_trace jsonb NOT NULL CHECK(jsonb_typeof(member_trace)='object' AND member_trace?&ARRAY['project_ref','property_ref','allocation_basis'] AND (member_trace-'project_ref'-'property_ref'-'allocation_basis')='{}'::jsonb AND jsonb_typeof(member_trace->'project_ref') IN('string','null') AND jsonb_typeof(member_trace->'property_ref') IN('string','null') AND member_trace->>'allocation_basis' IN('ENTITY_ONLY','SOURCE_DIMENSIONED')),rule_id text NOT NULL,confidence numeric(5,4) NOT NULL CHECK(confidence=0.9900),proposal_reason text NOT NULL CHECK(length(btrim(proposal_reason)) BETWEEN 8 AND 2000),proposal_hash text NOT NULL CHECK(proposal_hash~'^sha256:[0-9a-f]{64}$'),status text NOT NULL DEFAULT 'PROPOSED' CHECK(status='PROPOSED'),created_by text NOT NULL,created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
 UNIQUE(tenant_id,entity_id,ai_construction_loan_entry_proposal_id),UNIQUE(tenant_id,entity_id,ai_construction_loan_classification_evidence_id),UNIQUE(tenant_id,entity_id,proposal_hash),FOREIGN KEY(tenant_id,entity_id) REFERENCES entity(tenant_id,entity_id),FOREIGN KEY(ai_construction_loan_classification_evidence_id) REFERENCES ai_construction_loan_classification_evidence(ai_construction_loan_classification_evidence_id),FOREIGN KEY(tenant_id,entity_id,source_document_id) REFERENCES source_document(tenant_id,entity_id,source_document_id),FOREIGN KEY(tenant_id,entity_id,source_document_line_id) REFERENCES source_document_line(tenant_id,entity_id,source_document_line_id),FOREIGN KEY(tenant_id,entity_id,accounting_period_id) REFERENCES accounting_period(tenant_id,entity_id,period_id),CHECK(debit_account_code<>credit_account_code)
);
ALTER TABLE ai_construction_loan_entry_proposal ENABLE ROW LEVEL SECURITY;CREATE POLICY ai_construction_loan_entry_proposal_scope ON ai_construction_loan_entry_proposal USING(tenant_id=refs_current_tenant() AND refs_entity_allowed(entity_id)) WITH CHECK(tenant_id=refs_current_tenant() AND refs_entity_allowed(entity_id));CREATE TRIGGER ai_construction_loan_entry_proposal_append_only BEFORE UPDATE OR DELETE ON ai_construction_loan_entry_proposal FOR EACH ROW EXECUTE FUNCTION reject_mutation();
CREATE FUNCTION refs_ai_construction_loan_entry_proposal_hash(p_tenant uuid,p_entity uuid,p_evidence uuid,p_classification_hash text,p_period uuid,p_treatment text,p_debit text,p_credit text,p_member_trace jsonb,p_reason text) RETURNS text LANGUAGE sql IMMUTABLE SET search_path=pg_catalog,public,pg_temp AS $$SELECT refs_jsonb_hash(jsonb_build_object('schema_version','AI_CONSTRUCTION_LOAN_ENTRY_PROPOSAL_V1','tenant_id',p_tenant,'entity_id',p_entity,'classification_evidence_id',p_evidence,'classification_hash',p_classification_hash,'accounting_period_id',p_period,'treatment_decision',p_treatment,'debit_account_code',btrim(p_debit),'credit_account_code',btrim(p_credit),'member_trace',p_member_trace,'reason',btrim(p_reason)))$$;
CREATE FUNCTION refs_propose_ai_construction_loan_entry(p_tenant uuid,p_entity uuid,p_evidence uuid,p_classification_hash text,p_period uuid,p_treatment text,p_debit text,p_credit text,p_member_trace jsonb,p_reason text,p_idempotency_key text,p_request_hash text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE actor text:=refs_current_actor();e ai_construction_loan_classification_evidence;d source_document;l source_document_line;period_row accounting_period;idem idempotency_receipt;proposal_id uuid:=gen_random_uuid();proposal_hash text;project_ref text;property_ref text;basis text;payload jsonb;result jsonb;
BEGIN
 PERFORM refs_assert_scope(p_tenant,p_entity,'AI.LOAN.PROPOSE');IF actor IS NULL THEN RAISE EXCEPTION 'Authenticated loan proposer missing' USING ERRCODE='42501';END IF;proposal_hash:=refs_ai_construction_loan_entry_proposal_hash(p_tenant,p_entity,p_evidence,p_classification_hash,p_period,p_treatment,p_debit,p_credit,p_member_trace,p_reason);
 IF p_request_hash IS DISTINCT FROM proposal_hash OR btrim(COALESCE(p_debit,''))='' OR btrim(COALESCE(p_credit,''))='' OR btrim(p_debit)=btrim(p_credit) OR p_member_trace IS NULL OR jsonb_typeof(p_member_trace)<>'object' OR length(btrim(COALESCE(p_reason,''))) NOT BETWEEN 8 AND 2000 THEN RAISE EXCEPTION 'Loan proposal requires canonical evidence, distinct accounts, member trace, and reason' USING ERRCODE='22023';END IF;
 project_ref:=NULLIF(btrim(p_member_trace->>'project_ref'),'');property_ref:=NULLIF(btrim(p_member_trace->>'property_ref'),'');basis:=p_member_trace->>'allocation_basis';IF (p_member_trace-'project_ref'-'property_ref'-'allocation_basis')<>'{}'::jsonb OR basis NOT IN('ENTITY_ONLY','SOURCE_DIMENSIONED') OR (basis='ENTITY_ONLY' AND(project_ref IS NOT NULL OR property_ref IS NOT NULL)) THEN RAISE EXCEPTION 'Loan proposal member trace is not closed' USING ERRCODE='22023';END IF;
 INSERT INTO idempotency_receipt(tenant_id,operation_scope,idempotency_key,request_hash,status,actor_id) VALUES(p_tenant,'AI_CONSTRUCTION_LOAN_ENTRY_PROPOSAL:'||p_entity,p_idempotency_key,p_request_hash,'IN_PROGRESS',actor) ON CONFLICT(tenant_id,operation_scope,idempotency_key) DO NOTHING;SELECT * INTO idem FROM idempotency_receipt WHERE tenant_id=p_tenant AND operation_scope='AI_CONSTRUCTION_LOAN_ENTRY_PROPOSAL:'||p_entity AND idempotency_key=p_idempotency_key FOR UPDATE;IF idem.request_hash<>p_request_hash OR idem.actor_id IS DISTINCT FROM actor THEN RAISE EXCEPTION 'Loan proposal idempotency key conflicts with payload or actor' USING ERRCODE='23505';END IF;IF idem.status='SUCCEEDED' THEN RETURN idem.response_body||jsonb_build_object('idempotent',true);END IF;
 SELECT * INTO e FROM ai_construction_loan_classification_evidence WHERE tenant_id=p_tenant AND entity_id=p_entity AND ai_construction_loan_classification_evidence_id=p_evidence FOR SHARE;IF NOT FOUND OR e.classification_hash<>p_classification_hash OR e.status<>'REVIEW_REQUIRED' THEN RAISE EXCEPTION 'Loan proposal requires exact retained classification evidence' USING ERRCODE='23514';END IF;
 IF NOT ((e.classification='LOAN_DRAW' AND p_treatment IN('LOAN_DRAW_CASH','LOAN_DRAW_CWIP')) OR(e.classification='INTEREST_REVIEW' AND p_treatment IN('CAPITALIZED_INTEREST','EXPENSED_INTEREST')) OR(e.classification='PRINCIPAL_REPAYMENT' AND p_treatment='PRINCIPAL_REPAYMENT') OR(e.classification='LOAN_FEE_REVIEW' AND p_treatment IN('DEFERRED_LOAN_FEE','EXPENSED_LOAN_FEE')) OR(e.classification='ESCROW_RESERVE' AND p_treatment IN('ESCROW_FUNDING','ESCROW_RELEASE'))) THEN RAISE EXCEPTION 'Loan treatment conflicts with retained classification' USING ERRCODE='23514';END IF;
 SELECT * INTO d FROM source_document WHERE tenant_id=p_tenant AND entity_id=p_entity AND source_document_id=e.source_document_id FOR SHARE;SELECT * INTO l FROM source_document_line WHERE tenant_id=p_tenant AND entity_id=p_entity AND source_document_line_id=e.source_document_line_id FOR SHARE;IF d.source_document_id IS NULL OR l.source_document_line_id IS NULL OR d.payload_hash<>e.source_payload_hash OR d.version<>e.source_document_version OR d.status<>'READY_FOR_DRAFT' OR d.source_module<>'loan' OR l.amount<=0 OR NULLIF(btrim(l.loan_ref),'') IS DISTINCT FROM e.loan_ref THEN RAISE EXCEPTION 'Loan source is missing, changed, or not review-ready' USING ERRCODE='23514';END IF;
 IF basis='ENTITY_ONLY' AND(NULLIF(btrim(l.project_ref),'') IS NOT NULL OR NULLIF(btrim(l.property_ref),'') IS NOT NULL) OR basis='SOURCE_DIMENSIONED' AND(project_ref IS DISTINCT FROM NULLIF(btrim(l.project_ref),'') OR property_ref IS DISTINCT FROM NULLIF(btrim(l.property_ref),'')) THEN RAISE EXCEPTION 'Loan member trace does not match source' USING ERRCODE='23514';END IF;
 SELECT * INTO period_row FROM accounting_period WHERE tenant_id=p_tenant AND entity_id=p_entity AND period_id=p_period FOR SHARE;IF NOT FOUND OR d.accounting_date<period_row.starts_on OR d.accounting_date>period_row.ends_on THEN RAISE EXCEPTION 'Loan accounting date is outside selected period' USING ERRCODE='23514';END IF;
 PERFORM 1 FROM account_master WHERE tenant_id=p_tenant AND entity_id=p_entity AND account_code=btrim(p_debit) AND active FOR SHARE;IF NOT FOUND THEN RAISE EXCEPTION 'Loan debit account is inactive or missing' USING ERRCODE='23503';END IF;PERFORM 1 FROM account_master WHERE tenant_id=p_tenant AND entity_id=p_entity AND account_code=btrim(p_credit) AND active FOR SHARE;IF NOT FOUND THEN RAISE EXCEPTION 'Loan credit account is inactive or missing' USING ERRCODE='23503';END IF;
 INSERT INTO ai_construction_loan_entry_proposal(ai_construction_loan_entry_proposal_id,tenant_id,entity_id,ai_construction_loan_classification_evidence_id,classification_hash,source_document_id,source_document_line_id,source_payload_hash,source_document_version,source_line_hash,accounting_period_id,journal_date,loan_ref,classification,treatment_decision,debit_account_code,credit_account_code,currency,amount,member_trace,rule_id,confidence,proposal_reason,proposal_hash,created_by) VALUES(proposal_id,p_tenant,p_entity,p_evidence,e.classification_hash,e.source_document_id,e.source_document_line_id,e.source_payload_hash,e.source_document_version,e.source_line_hash,p_period,d.accounting_date,e.loan_ref,e.classification,p_treatment,btrim(p_debit),btrim(p_credit),d.currency,l.amount,p_member_trace,e.rule_id,e.confidence,btrim(p_reason),proposal_hash,actor);
 payload:=jsonb_build_object('schema_version','AI_CONSTRUCTION_LOAN_ENTRY_PROPOSAL_V1','ai_construction_loan_entry_proposal_id',proposal_id,'classification_evidence_id',p_evidence,'classification_hash',e.classification_hash,'source_document_id',e.source_document_id,'source_document_line_id',e.source_document_line_id,'source_payload_hash',e.source_payload_hash,'source_document_version',e.source_document_version,'source_line_hash',e.source_line_hash,'accounting_period_id',p_period,'journal_date',d.accounting_date,'loan_ref',e.loan_ref,'classification',e.classification,'treatment_decision',p_treatment,'debit_account_code',btrim(p_debit),'credit_account_code',btrim(p_credit),'currency',d.currency,'amount',l.amount,'member_trace',p_member_trace,'rule_id',e.rule_id,'confidence',e.confidence,'status','PROPOSED','can_create_draft',false,'can_review',false,'can_approve',false,'can_post',false);
 INSERT INTO audit_event(tenant_id,entity_id,event_type,object_type,object_id,action,actor_id,actor_type,permission_used,request_id,correlation_id,idempotency_key,after_hash,reason,metadata) VALUES(p_tenant,p_entity,'AI_CONSTRUCTION_LOAN_ENTRY_PROPOSED','AI_CONSTRUCTION_LOAN_ENTRY_PROPOSAL',proposal_id,'PROPOSE',actor,'USER','AI.LOAN.PROPOSE',p_idempotency_key,p_idempotency_key,p_idempotency_key,proposal_hash,btrim(p_reason),payload);INSERT INTO outbox_event(tenant_id,entity_id,aggregate_type,aggregate_id,event_type,payload,payload_hash) VALUES(p_tenant,p_entity,'AI_CONSTRUCTION_LOAN_ENTRY_PROPOSAL',proposal_id,'AI_CONSTRUCTION_LOAN_ENTRY_PROPOSED',payload,refs_jsonb_hash(payload));result:=payload||jsonb_build_object('idempotent',false);UPDATE idempotency_receipt SET status='SUCCEEDED',response_status=201,response_body=result,completed_at=clock_timestamp() WHERE idempotency_receipt_id=idem.idempotency_receipt_id;RETURN result;
END;$$;
CREATE FUNCTION refs_read_ai_construction_loan_entry_proposals(p_tenant uuid,p_entity uuid,p_limit integer DEFAULT 50) RETURNS SETOF ai_construction_loan_entry_proposal LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$BEGIN PERFORM refs_assert_scope(p_tenant,p_entity,'AI.LOAN.VIEW');IF p_limit<1 OR p_limit>100 THEN RAISE EXCEPTION 'Loan proposal limit must be between 1 and 100' USING ERRCODE='22023';END IF;RETURN QUERY SELECT p.* FROM ai_construction_loan_entry_proposal p WHERE p.tenant_id=p_tenant AND p.entity_id=p_entity ORDER BY p.created_at DESC,p.ai_construction_loan_entry_proposal_id DESC LIMIT p_limit;END;$$;
REVOKE ALL ON ai_construction_loan_entry_proposal FROM PUBLIC,refs_app;REVOKE EXECUTE ON FUNCTION refs_ai_construction_loan_entry_proposal_hash(uuid,uuid,uuid,text,uuid,text,text,text,jsonb,text),refs_propose_ai_construction_loan_entry(uuid,uuid,uuid,text,uuid,text,text,text,jsonb,text,text,text),refs_read_ai_construction_loan_entry_proposals(uuid,uuid,integer) FROM PUBLIC;GRANT EXECUTE ON FUNCTION refs_ai_construction_loan_entry_proposal_hash(uuid,uuid,uuid,text,uuid,text,text,text,jsonb,text),refs_propose_ai_construction_loan_entry(uuid,uuid,uuid,text,uuid,text,text,text,jsonb,text,text,text),refs_read_ai_construction_loan_entry_proposals(uuid,uuid,integer) TO refs_app;
COMMIT;
