BEGIN;

CREATE TABLE ai_manual_journal_risk_finding (
  ai_manual_journal_risk_finding_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  tenant_id uuid NOT NULL REFERENCES tenant(tenant_id),entity_id uuid NOT NULL,accounting_period_id uuid NOT NULL,journal_entry_id uuid NOT NULL,
  policy_snapshot_id uuid NOT NULL,policy_snapshot_hash text NOT NULL CHECK(policy_snapshot_hash~'^sha256:[0-9a-f]{64}$'),finding_hash text NOT NULL CHECK(finding_hash~'^sha256:[0-9a-f]{64}$'),finding jsonb NOT NULL,
  status text NOT NULL DEFAULT 'OPEN' CHECK(status='OPEN'),created_by text NOT NULL,created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  UNIQUE(tenant_id,entity_id,ai_manual_journal_risk_finding_id),UNIQUE(tenant_id,entity_id,finding_hash),
  FOREIGN KEY(tenant_id,entity_id) REFERENCES entity(tenant_id,entity_id),FOREIGN KEY(tenant_id,entity_id,accounting_period_id) REFERENCES accounting_period(tenant_id,entity_id,period_id),
  FOREIGN KEY(tenant_id,entity_id,journal_entry_id) REFERENCES journal_entry(tenant_id,entity_id,journal_entry_id),FOREIGN KEY(tenant_id,policy_snapshot_id) REFERENCES setting_snapshot(tenant_id,setting_snapshot_id),
  CHECK(finding->>'schema_version'='AI_MANUAL_JOURNAL_RISK_FINDING_V1'),CHECK(finding->'action_flags'='{"can_create_draft":false,"can_review":false,"can_approve":false,"can_post":false}'::jsonb)
);
ALTER TABLE ai_manual_journal_risk_finding ENABLE ROW LEVEL SECURITY;
CREATE POLICY ai_manual_journal_risk_finding_scope ON ai_manual_journal_risk_finding USING(tenant_id=refs_current_tenant() AND refs_entity_allowed(entity_id)) WITH CHECK(tenant_id=refs_current_tenant() AND refs_entity_allowed(entity_id));
CREATE TRIGGER ai_manual_journal_risk_finding_append_only BEFORE UPDATE OR DELETE ON ai_manual_journal_risk_finding FOR EACH ROW EXECUTE FUNCTION reject_mutation();

CREATE FUNCTION refs_ai_manual_journal_risk_batch_hash(p_tenant uuid,p_entity uuid,p_period uuid,p_batch jsonb) RETURNS text LANGUAGE sql IMMUTABLE SET search_path=pg_catalog,public,pg_temp AS $$
 SELECT refs_jsonb_hash(jsonb_build_object('schema_version','AI_MANUAL_JOURNAL_RISK_RUN_V1','tenant_id',p_tenant,'entity_id',p_entity,'accounting_period_id',p_period,'batch',p_batch)) $$;

CREATE FUNCTION refs_materialize_ai_manual_journal_risk_batch(p_tenant uuid,p_entity uuid,p_period uuid,p_batch jsonb,p_idempotency_key text,p_request_hash text) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE actor text:=refs_current_actor();idem idempotency_receipt;item jsonb;journal journal_entry;approved_policy jsonb;expected jsonb;finding_id uuid;finding_hash text;event_payload jsonb;response jsonb;
DECLARE debit_total numeric(20,4);credit_total numeric(20,4);attachment_count bigint;source_ids jsonb;source_hashes jsonb;line_ids jsonb;no_support boolean;all_round boolean;rule_ids jsonb;risk text;reason text;confidence numeric;
DECLARE inserted_count integer:=0;replay_count integer:=0;result_ids jsonb:='[]'::jsonb;finding_keys text[]:=ARRAY['accounting_period_id','action_flags','attachment_count','confidence','currency','due_basis','entity_id','finding_type','journal_date','journal_entry_id','journal_number','line_ids','owner_role','policy_evidence','reason','required_human_fields','risk_level','rule_ids','schema_version','source_document_ids','source_payload_hashes','suggested_action','total_credits','total_debits'];
BEGIN
  PERFORM refs_assert_ai_analysis_scope(p_tenant,p_entity);IF actor IS NULL THEN RAISE EXCEPTION 'Authenticated manual Journal risk actor missing' USING ERRCODE='42501';END IF;
  IF p_request_hash IS DISTINCT FROM refs_ai_manual_journal_risk_batch_hash(p_tenant,p_entity,p_period,p_batch) THEN RAISE EXCEPTION 'Manual Journal risk request hash is not canonical' USING ERRCODE='22023';END IF;
  IF jsonb_typeof(p_batch)<>'object' OR (p_batch-'schema_version'-'current_accounting_period_id'-'scanned_journal_count'-'finding_count'-'findings'-'action_flags')<>'{}'::jsonb OR p_batch->>'schema_version'<>'AI_MANUAL_JOURNAL_RISK_BATCH_V1' OR p_batch->>'current_accounting_period_id'<>p_period::text OR jsonb_typeof(p_batch->'findings')<>'array' OR jsonb_array_length(p_batch->'findings')>500 OR (p_batch->>'finding_count')::integer<>jsonb_array_length(p_batch->'findings') OR p_batch->'action_flags' IS DISTINCT FROM '{"can_create_draft":false,"can_review":false,"can_approve":false,"can_post":false}'::jsonb THEN RAISE EXCEPTION 'Manual Journal risk batch is malformed or action-enabled' USING ERRCODE='22023';END IF;
  INSERT INTO idempotency_receipt(tenant_id,operation_scope,idempotency_key,request_hash,status,actor_id) VALUES(p_tenant,'AI_MANUAL_JOURNAL_RISK:'||p_entity||':'||p_period,p_idempotency_key,p_request_hash,'IN_PROGRESS',actor) ON CONFLICT(tenant_id,operation_scope,idempotency_key) DO NOTHING;
  SELECT * INTO idem FROM idempotency_receipt WHERE tenant_id=p_tenant AND operation_scope='AI_MANUAL_JOURNAL_RISK:'||p_entity||':'||p_period AND idempotency_key=p_idempotency_key FOR UPDATE;
  IF idem.request_hash IS DISTINCT FROM p_request_hash OR idem.actor_id IS DISTINCT FROM actor THEN RAISE EXCEPTION 'Manual Journal risk idempotency key conflicts with payload or actor' USING ERRCODE='23505';END IF;IF idem.status='SUCCEEDED' THEN RETURN idem.response_body||jsonb_build_object('idempotent',true);END IF;
  approved_policy:=refs_read_ai_manual_journal_risk_policy(p_tenant,p_entity,p_period);
  FOR item IN SELECT value FROM jsonb_array_elements(p_batch->'findings') LOOP
    IF ARRAY(SELECT jsonb_object_keys(item) ORDER BY 1) IS DISTINCT FROM finding_keys OR item->>'schema_version'<>'AI_MANUAL_JOURNAL_RISK_FINDING_V1' OR item->>'finding_type'<>'MANUAL_JOURNAL_RISK' OR item->>'entity_id'<>p_entity::text OR item->>'accounting_period_id'<>p_period::text OR item->'policy_evidence' IS DISTINCT FROM approved_policy OR item->'action_flags' IS DISTINCT FROM '{"can_create_draft":false,"can_review":false,"can_approve":false,"can_post":false}'::jsonb THEN RAISE EXCEPTION 'Manual Journal risk finding is malformed, unscoped, policy-drifted, or action-enabled' USING ERRCODE='22023';END IF;
    SELECT * INTO journal FROM journal_entry j WHERE j.tenant_id=p_tenant AND j.entity_id=p_entity AND j.period_id=p_period AND j.journal_entry_id=(item->>'journal_entry_id')::uuid AND j.journal_type='MANUAL' FOR SHARE;IF NOT FOUND THEN RAISE EXCEPTION 'Manual Journal risk is not bound to the exact manual Journal' USING ERRCODE='23514';END IF;
    SELECT coalesce(sum(debit_amount),0),coalesce(sum(credit_amount),0),jsonb_agg(journal_line_id ORDER BY line_no),bool_and((CASE WHEN debit_amount>0 THEN debit_amount ELSE credit_amount END % (approved_policy->>'round_amount_increment')::numeric)=0) INTO debit_total,credit_total,line_ids,all_round FROM journal_line WHERE tenant_id=p_tenant AND entity_id=p_entity AND period_id=p_period AND journal_entry_id=journal.journal_entry_id;
    IF jsonb_array_length(coalesce(line_ids,'[]'::jsonb))<2 OR debit_total<>credit_total THEN RAISE EXCEPTION 'Manual Journal risk source must be balanced and non-empty' USING ERRCODE='23514';END IF;
    SELECT count(*) INTO attachment_count FROM source_link sl JOIN attachment a ON a.tenant_id=sl.tenant_id AND a.attachment_id=sl.attachment_id WHERE sl.tenant_id=p_tenant AND sl.entity_id=p_entity AND sl.journal_entry_id=journal.journal_entry_id AND sl.link_type='JE_ATTACHMENT' AND a.finalization_status='VERIFIED_CLEAN';
    SELECT coalesce(jsonb_agg(d.source_document_id ORDER BY d.source_document_id),'[]'::jsonb),coalesce(jsonb_agg(d.payload_hash ORDER BY d.source_document_id),'[]'::jsonb) INTO source_ids,source_hashes FROM(SELECT DISTINCT sd.source_document_id,sd.payload_hash FROM source_link sl JOIN source_document sd ON sd.tenant_id=sl.tenant_id AND sd.entity_id=sl.entity_id AND sd.source_document_id=sl.source_document_id WHERE sl.tenant_id=p_tenant AND sl.entity_id=p_entity AND sl.journal_entry_id=journal.journal_entry_id AND sl.source_document_id IS NOT NULL)d;
    no_support:=attachment_count=0 AND jsonb_array_length(source_ids)=0;IF debit_total<(approved_policy->>'large_manual_journal_threshold')::numeric OR (NOT no_support AND NOT all_round) THEN RAISE EXCEPTION 'Manual Journal no longer meets the approved risk policy' USING ERRCODE='23514';END IF;
    rule_ids:='[]'::jsonb;IF no_support THEN rule_ids:=rule_ids||'"MANUAL_JE_LARGE_NO_ATTACHMENT"'::jsonb;END IF;IF all_round THEN rule_ids:=rule_ids||'"MANUAL_JE_ROUND_AMOUNT_PATTERN"'::jsonb;END IF;
    risk:=CASE WHEN no_support THEN 'HIGH' ELSE 'MEDIUM' END;reason:=CASE WHEN no_support THEN 'A large manual Journal Entry has no retained attachment or source document evidence.' ELSE 'A large manual Journal Entry is composed entirely of amounts aligned to the approved round-amount increment.' END;confidence:=CASE WHEN no_support THEN 0.99 ELSE 0.86 END;
    expected:=jsonb_build_object('schema_version','AI_MANUAL_JOURNAL_RISK_FINDING_V1','finding_type','MANUAL_JOURNAL_RISK','risk_level',risk,'rule_ids',rule_ids,'journal_entry_id',journal.journal_entry_id,'journal_number',journal.journal_number,'entity_id',journal.entity_id,'accounting_period_id',journal.period_id,'journal_date',journal.journal_date,'currency',journal.currency,'total_debits',to_char(debit_total,'FM9999999999999990.0000'),'total_credits',to_char(credit_total,'FM9999999999999990.0000'),'attachment_count',attachment_count,'source_document_ids',source_ids,'source_payload_hashes',source_hashes,'line_ids',line_ids,'reason',reason,'suggested_action','Require an independent Controller to inspect the complete journal, supporting source documents, account mapping, member trace, business purpose, and approval history before any further workflow action.','confidence',confidence,'owner_role','CONTROLLER_REVIEW','due_basis','BEFORE_APPROVAL_OR_PERIOD_CLOSE','required_human_fields',jsonb_build_array('business_purpose','source_support','account_mapping','member_trace','preparer_approver_separation','resolution_reason'),'policy_evidence',approved_policy,'action_flags',jsonb_build_object('can_create_draft',false,'can_review',false,'can_approve',false,'can_post',false));
    IF item IS DISTINCT FROM expected THEN RAISE EXCEPTION 'Manual Journal finding does not match the database-recomputed evidence' USING ERRCODE='23514';END IF;
    finding_hash:=refs_jsonb_hash(jsonb_build_object('schema_version','AI_MANUAL_JOURNAL_RISK_EVIDENCE_V1','tenant_id',p_tenant,'entity_id',p_entity,'accounting_period_id',p_period,'finding',item));SELECT ai_manual_journal_risk_finding_id INTO finding_id FROM ai_manual_journal_risk_finding WHERE tenant_id=p_tenant AND entity_id=p_entity AND finding_hash=finding_hash;
    IF FOUND THEN replay_count:=replay_count+1;ELSE finding_id:=gen_random_uuid();INSERT INTO ai_manual_journal_risk_finding(ai_manual_journal_risk_finding_id,tenant_id,entity_id,accounting_period_id,journal_entry_id,policy_snapshot_id,policy_snapshot_hash,finding_hash,finding,created_by) VALUES(finding_id,p_tenant,p_entity,p_period,journal.journal_entry_id,(approved_policy->>'setting_snapshot_id')::uuid,approved_policy->>'setting_snapshot_hash',finding_hash,item,actor);
      event_payload:=jsonb_build_object('schema_version','AI_MANUAL_JOURNAL_RISK_EVIDENCE_V1','finding_id',finding_id,'journal_entry_id',journal.journal_entry_id,'accounting_period_id',p_period,'source_document_ids',source_ids,'source_payload_hashes',source_hashes,'line_ids',line_ids,'policy_snapshot_id',approved_policy->>'setting_snapshot_id','policy_snapshot_hash',approved_policy->>'setting_snapshot_hash','finding_hash',finding_hash,'risk_level',risk,'rule_ids',rule_ids,'can_create_draft',false,'can_review',false,'can_approve',false,'can_post',false);
      INSERT INTO audit_event(tenant_id,entity_id,event_type,object_type,object_id,action,actor_id,actor_type,permission_used,request_id,correlation_id,idempotency_key,after_hash,reason,metadata) VALUES(p_tenant,p_entity,'AI_MANUAL_JOURNAL_RISK_MATERIALIZED','AI_MANUAL_JOURNAL_RISK_FINDING',finding_id,'MATERIALIZE',actor,'USER','AI.ANALYSIS.EXPLAIN',p_idempotency_key,p_idempotency_key,p_idempotency_key,finding_hash,'Database-recomputed manual Journal risk; no accounting action',event_payload);
      INSERT INTO outbox_event(tenant_id,entity_id,aggregate_type,aggregate_id,event_type,payload,payload_hash) VALUES(p_tenant,p_entity,'AI_MANUAL_JOURNAL_RISK_FINDING',finding_id,'AI_MANUAL_JOURNAL_RISK_MATERIALIZED',event_payload,refs_jsonb_hash(event_payload));inserted_count:=inserted_count+1;END IF;result_ids:=result_ids||jsonb_build_array(finding_id);
  END LOOP;
  response:=jsonb_build_object('schema_version','AI_MANUAL_JOURNAL_RISK_RUN_RECEIPT_V1','accounting_period_id',p_period,'row_count',jsonb_array_length(p_batch->'findings'),'inserted_count',inserted_count,'replayed_count',replay_count,'finding_ids',result_ids,'request_hash',p_request_hash,'can_create_draft',false,'can_review',false,'can_approve',false,'can_post',false,'idempotent',false);UPDATE idempotency_receipt SET status='SUCCEEDED',response_status=201,response_body=response,completed_at=clock_timestamp() WHERE idempotency_receipt_id=idem.idempotency_receipt_id;RETURN response;
END;$$;

REVOKE ALL ON ai_manual_journal_risk_finding FROM PUBLIC,refs_app;REVOKE ALL ON FUNCTION refs_ai_manual_journal_risk_batch_hash(uuid,uuid,uuid,jsonb),refs_materialize_ai_manual_journal_risk_batch(uuid,uuid,uuid,jsonb,text,text) FROM PUBLIC;GRANT EXECUTE ON FUNCTION refs_ai_manual_journal_risk_batch_hash(uuid,uuid,uuid,jsonb),refs_materialize_ai_manual_journal_risk_batch(uuid,uuid,uuid,jsonb,text,text) TO refs_app;
COMMIT;
