BEGIN;

CREATE FUNCTION refs_read_ai_budget_variance_policy(p_tenant uuid,p_entity uuid,p_period uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE period_end date;selected setting_snapshot;match_count integer;expected_keys text[]:=ARRAY['minimum_absolute_variance','policy_version','rule_id','schema_version','variance_threshold_basis_points'];
BEGIN
  PERFORM refs_assert_scope(p_tenant,p_entity,'AI.ANALYSIS.EXPLAIN');SELECT ends_on INTO period_end FROM accounting_period WHERE tenant_id=p_tenant AND entity_id=p_entity AND period_id=p_period AND ledger_code='PRIMARY';IF NOT FOUND THEN RAISE EXCEPTION 'Accounting period is outside the budget variance policy scope' USING ERRCODE='22023';END IF;
  SELECT count(*) INTO match_count FROM setting_snapshot WHERE tenant_id=p_tenant AND entity_id=p_entity AND family='AI_BUDGET_VARIANCE_POLICY' AND scope_type='ENTITY' AND scope_key=p_entity::text AND status='APPROVED' AND effective_from<=period_end::timestamptz AND(effective_to IS NULL OR effective_to>period_end::timestamptz);
  IF match_count=0 THEN RETURN NULL;END IF;IF match_count<>1 THEN RAISE EXCEPTION 'AI budget variance policy scope is ambiguous' USING ERRCODE='23514';END IF;
  SELECT * INTO selected FROM setting_snapshot WHERE tenant_id=p_tenant AND entity_id=p_entity AND family='AI_BUDGET_VARIANCE_POLICY' AND scope_type='ENTITY' AND scope_key=p_entity::text AND status='APPROVED' AND effective_from<=period_end::timestamptz AND(effective_to IS NULL OR effective_to>period_end::timestamptz) FOR SHARE;
  IF selected.snapshot_hash IS DISTINCT FROM refs_jsonb_hash(selected.snapshot) OR ARRAY(SELECT jsonb_object_keys(selected.snapshot) ORDER BY 1) IS DISTINCT FROM expected_keys OR selected.snapshot->>'schema_version'<>'AI_BUDGET_VARIANCE_POLICY_SNAPSHOT_V1' OR selected.snapshot->>'rule_id'<>'AI_APPROVED_BUDGET_VS_POSTED_ACTUAL_V1' OR jsonb_typeof(selected.snapshot->'policy_version')<>'number' OR(selected.snapshot->>'policy_version')::integer<1 OR jsonb_typeof(selected.snapshot->'variance_threshold_basis_points')<>'number' OR(selected.snapshot->>'variance_threshold_basis_points')::integer NOT BETWEEN 100 AND 100000 OR coalesce(selected.snapshot->>'minimum_absolute_variance','')!~'^(0|[1-9][0-9]*)\.[0-9]{4}$' THEN RAISE EXCEPTION 'Approved AI budget variance policy is malformed or hash-invalid' USING ERRCODE='23514';END IF;
  RETURN (selected.snapshot-'schema_version'-'rule_id')||jsonb_build_object('schema_version','AI_BUDGET_VARIANCE_POLICY_V1','setting_snapshot_id',selected.setting_snapshot_id,'setting_snapshot_hash',selected.snapshot_hash);
END;$$;

CREATE FUNCTION refs_read_ai_budget_vs_actual_source(p_tenant uuid,p_entity uuid,p_period uuid)
RETURNS TABLE(period_id uuid,period_code text,period_start text,period_end text,account_code text,account_name text,currency text,comparison_side text,report_status text,classification_basis text,budget_amount numeric(20,4),actual_amount numeric(20,4),variance_amount numeric(20,4),budget_snapshot_id uuid,budget_version text,budget_snapshot_hash text,budget_receipt_hash text,budget_source_ref text,budget_source_version text,journal_entry_ids uuid[],journal_line_ids uuid[],ledger_line_ids uuid[],source_document_ids uuid[])
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE v_period record;v_currency text;
BEGIN
  PERFORM refs_assert_scope(p_tenant,p_entity,'AI.ANALYSIS.EXPLAIN');SELECT ap.period_id,ap.period_code,ap.starts_on,ap.ends_on,e.base_currency INTO v_period FROM accounting_period ap JOIN entity e ON e.tenant_id=ap.tenant_id AND e.entity_id=ap.entity_id WHERE ap.tenant_id=p_tenant AND ap.entity_id=p_entity AND ap.period_id=p_period AND ap.ledger_code='PRIMARY';IF NOT FOUND THEN RAISE EXCEPTION 'A valid primary accounting period is required' USING ERRCODE='22023';END IF;v_currency:=v_period.base_currency;
  RETURN QUERY WITH current_budget AS(SELECT bs.* FROM budget_snapshot bs WHERE bs.tenant_id=p_tenant AND bs.entity_id=p_entity AND bs.period_id=p_period ORDER BY bs.version DESC,bs.budget_snapshot_id DESC LIMIT 1),posted AS(SELECT l.ledger_line_id,l.journal_entry_id,l.journal_line_id,l.account_code,l.debit_amount,l.credit_amount,j.currency FROM ledger_line l JOIN journal_entry j ON j.tenant_id=l.tenant_id AND j.entity_id=l.entity_id AND j.journal_entry_id=l.journal_entry_id AND j.status='POSTED' WHERE l.tenant_id=p_tenant AND l.entity_id=p_entity AND l.period_id=p_period),evidence AS(SELECT bl.*,bs.version,bs.currency budget_currency,bs.snapshot_hash,bs.receipt_hash,bs.source_ref,bs.source_version,a.account_name,a.active,count(p.ledger_line_id)::integer actual_line_count,count(DISTINCT p.currency)::integer actual_currency_count,max(p.currency) actual_currency,coalesce(sum(CASE bl.comparison_side WHEN 'DEBIT' THEN p.debit_amount-p.credit_amount ELSE p.credit_amount-p.debit_amount END),0)::numeric(20,4) actual_amount,array_agg(DISTINCT p.journal_entry_id ORDER BY p.journal_entry_id) FILTER(WHERE p.ledger_line_id IS NOT NULL) journal_entry_ids,array_agg(DISTINCT p.journal_line_id ORDER BY p.journal_line_id) FILTER(WHERE p.ledger_line_id IS NOT NULL) journal_line_ids,array_agg(DISTINCT p.ledger_line_id ORDER BY p.ledger_line_id) FILTER(WHERE p.ledger_line_id IS NOT NULL) ledger_line_ids FROM current_budget bs JOIN budget_line bl ON bl.budget_snapshot_id=bs.budget_snapshot_id LEFT JOIN account_master a ON a.tenant_id=p_tenant AND a.entity_id=p_entity AND a.account_code=bl.account_code LEFT JOIN posted p ON p.account_code=bl.account_code GROUP BY bl.budget_line_id,bl.budget_snapshot_id,bl.account_code,bl.comparison_side,bl.budget_amount,bs.version,bs.currency,bs.snapshot_hash,bs.receipt_hash,bs.source_ref,bs.source_version,a.account_name,a.active),retained AS(SELECT e.*,ARRAY(SELECT DISTINCT sl.source_document_id FROM source_link sl WHERE sl.tenant_id=p_tenant AND sl.entity_id=p_entity AND sl.source_document_id IS NOT NULL AND sl.journal_entry_id=ANY(coalesce(e.journal_entry_ids,ARRAY[]::uuid[])) ORDER BY sl.source_document_id)::uuid[] source_document_ids FROM evidence e)
  SELECT v_period.period_id,v_period.period_code,to_char(v_period.starts_on,'YYYY-MM-DD'),to_char(v_period.ends_on,'YYYY-MM-DD'),e.account_code,coalesce(e.account_name,'Unmapped account'),e.budget_currency,e.comparison_side,CASE WHEN NOT coalesce(e.active,false) THEN 'BLOCKED_ACCOUNT_REQUIRED' WHEN e.budget_currency<>v_currency THEN 'BLOCKED_BUDGET_CURRENCY_REQUIRED' WHEN e.actual_line_count=0 THEN 'BLOCKED_POSTED_ACTUAL_EVIDENCE_REQUIRED' WHEN e.actual_currency_count<>1 OR e.actual_currency<>e.budget_currency THEN 'BLOCKED_ACTUAL_CURRENCY_REQUIRED' ELSE 'APPROVED_BUDGET_VS_ACTUAL' END,CASE WHEN coalesce(e.active,false) AND e.budget_currency=v_currency AND e.actual_line_count>0 AND e.actual_currency_count=1 AND e.actual_currency=e.budget_currency THEN 'APPROVED_IMMUTABLE_BUDGET_SNAPSHOT_AND_POSTED_LEDGER_EXACT' ELSE 'APPROVED_BUDGET_SNAPSHOT_AND_POSTED_ACTUAL_EVIDENCE_REQUIRED' END,CASE WHEN coalesce(e.active,false) AND e.budget_currency=v_currency AND e.actual_line_count>0 AND e.actual_currency_count=1 AND e.actual_currency=e.budget_currency THEN e.budget_amount END,CASE WHEN coalesce(e.active,false) AND e.budget_currency=v_currency AND e.actual_line_count>0 AND e.actual_currency_count=1 AND e.actual_currency=e.budget_currency THEN e.actual_amount END,CASE WHEN coalesce(e.active,false) AND e.budget_currency=v_currency AND e.actual_line_count>0 AND e.actual_currency_count=1 AND e.actual_currency=e.budget_currency THEN e.budget_amount-e.actual_amount END,e.budget_snapshot_id,e.version::text,e.snapshot_hash,e.receipt_hash,e.source_ref,e.source_version,e.journal_entry_ids,e.journal_line_ids,e.ledger_line_ids,e.source_document_ids FROM retained e ORDER BY e.account_code;
END;$$;

REVOKE ALL ON FUNCTION refs_read_ai_budget_variance_policy(uuid,uuid,uuid),refs_read_ai_budget_vs_actual_source(uuid,uuid,uuid) FROM PUBLIC;GRANT EXECUTE ON FUNCTION refs_read_ai_budget_variance_policy(uuid,uuid,uuid),refs_read_ai_budget_vs_actual_source(uuid,uuid,uuid) TO refs_app;
COMMIT;
