BEGIN;
CREATE FUNCTION refs_read_ai_fixed_asset_depreciation_gap_source(p_tenant uuid,p_entity uuid,p_period uuid)
RETURNS SETOF jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
BEGIN
  PERFORM refs_assert_scope(p_tenant,p_entity,'AI.ANALYSIS.EXPLAIN');
  IF NOT EXISTS(SELECT 1 FROM accounting_period WHERE tenant_id=p_tenant AND entity_id=p_entity AND period_id=p_period AND ledger_code='PRIMARY') THEN RAISE EXCEPTION 'Exact primary accounting period is required' USING ERRCODE='22023'; END IF;
  RETURN QUERY WITH p AS (SELECT period_id,period_code,ends_on FROM accounting_period WHERE tenant_id=p_tenant AND entity_id=p_entity AND period_id=p_period AND ledger_code='PRIMARY'), mapped AS (
    SELECT key.account_code,m.mapping_snapshot_hash,m.asset_class,m.depreciation_treatment FROM (SELECT DISTINCT input_keys->>'account_code' account_code FROM mapping_snapshot WHERE tenant_id=p_tenant AND entity_id=p_entity AND family='FIXED_ASSET_ACCOUNT_CLASSIFICATION' AND input_keys?'account_code') key CROSS JOIN p LEFT JOIN LATERAL (WITH eligible AS (SELECT * FROM mapping_snapshot WHERE tenant_id=p_tenant AND entity_id=p_entity AND family='FIXED_ASSET_ACCOUNT_CLASSIFICATION' AND status IN('APPROVED','RETIRED') AND input_keys=jsonb_build_object('account_code',key.account_code) AND effective_from::date<=p.ends_on AND (effective_to IS NULL OR effective_to::date>p.ends_on)), highest AS (SELECT * FROM eligible WHERE priority=(SELECT max(priority) FROM eligible)) SELECT CASE WHEN count(*)=1 THEN (array_agg(snapshot_hash ORDER BY mapping_snapshot_id))[1] END mapping_snapshot_hash,CASE WHEN count(*)=1 THEN (array_agg(output_rules->>'asset_class' ORDER BY mapping_snapshot_id))[1] END asset_class,CASE WHEN count(*)=1 THEN (array_agg(output_rules->>'depreciation_treatment' ORDER BY mapping_snapshot_id))[1] END depreciation_treatment FROM highest) m ON true
  ), posted AS (SELECT m.*,a.account_name,l.currency::text currency,sum(l.debit_amount-l.credit_amount)::numeric(20,4) balance,array_agg(DISTINCT l.journal_entry_id ORDER BY l.journal_entry_id) je_ids,array_agg(DISTINCT l.journal_line_id ORDER BY l.journal_line_id) jl_ids,array_agg(DISTINCT l.ledger_line_id ORDER BY l.ledger_line_id) ll_ids FROM mapped m JOIN ledger_line l ON l.tenant_id=p_tenant AND l.entity_id=p_entity AND l.account_code=m.account_code JOIN journal_entry j ON j.tenant_id=l.tenant_id AND j.entity_id=l.entity_id AND j.journal_entry_id=l.journal_entry_id AND j.status='POSTED' CROSS JOIN p LEFT JOIN account_master a ON a.tenant_id=l.tenant_id AND a.entity_id=l.entity_id AND a.account_code=l.account_code WHERE j.journal_date<=p.ends_on AND m.mapping_snapshot_hash IS NOT NULL AND m.asset_class IS NOT NULL AND m.depreciation_treatment IN('NON_DEPRECIABLE','DEPRECIABLE','CWIP') GROUP BY m.account_code,m.mapping_snapshot_hash,m.asset_class,m.depreciation_treatment,a.account_name,l.currency HAVING sum(l.debit_amount-l.credit_amount)>=0
  ) SELECT jsonb_build_object('period_id',p.period_id,'period_code',p.period_code,'asset_account_code',posted.account_code,'account_name',coalesce(posted.account_name,'Unmapped asset account'),'asset_class',posted.asset_class,'depreciation_treatment',posted.depreciation_treatment,'mapping_snapshot_hash',posted.mapping_snapshot_hash,'currency',posted.currency,'posted_cost_balance',to_char(posted.balance,'FM999999999999990.0000'),'journal_entry_ids',posted.je_ids,'journal_line_ids',posted.jl_ids,'ledger_line_ids',posted.ll_ids,'source_document_ids',COALESCE((SELECT array_agg(DISTINCT sl.source_document_id ORDER BY sl.source_document_id) FROM source_link sl WHERE sl.tenant_id=p_tenant AND sl.entity_id=p_entity AND sl.source_document_id IS NOT NULL AND sl.journal_entry_id=ANY(posted.je_ids)),ARRAY[]::uuid[]),'asset_register_status','NOT_ESTABLISHED','depreciation_schedule_status','NOT_ESTABLISHED') FROM posted CROSS JOIN p ORDER BY posted.account_code;
END;$$;
REVOKE ALL ON FUNCTION refs_read_ai_fixed_asset_depreciation_gap_source(uuid,uuid,uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION refs_read_ai_fixed_asset_depreciation_gap_source(uuid,uuid,uuid) TO refs_app;
COMMIT;
