BEGIN;

CREATE FUNCTION refs_read_ai_construction_loan_decision_source(p_tenant uuid,p_entity uuid,p_period uuid,p_limit integer DEFAULT 100)
RETURNS TABLE(source_document_id uuid,source_document_line_id uuid,source_payload_hash text,source_line_hash text,entity_id uuid,accounting_period_id uuid,business_date date,accounting_date date,currency text,amount text,direction text,loan_ref text,lender_ref text,transaction_kind text,description text,bank_account_ref text,project_ref text,property_ref text,member_ref text,cost_code_ref text,source_attachment_count integer,source_attachment_ids uuid[],source_attachment_evidence jsonb,raw_event_id uuid,source_record_id text,source_version text,source_status text,duplicate_status text,accounting_status text)
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE period_row accounting_period; population_count integer;
BEGIN
  PERFORM refs_assert_scope(p_tenant,p_entity,'AI.ANALYSIS.EXPLAIN');
  IF p_limit IS NULL OR p_limit<1 OR p_limit>500 THEN RAISE EXCEPTION 'AI construction loan decision source limit must be between 1 and 500' USING ERRCODE='22023'; END IF;
  SELECT ap.* INTO period_row FROM accounting_period ap WHERE ap.tenant_id=p_tenant AND ap.entity_id=p_entity AND ap.period_id=p_period AND ap.ledger_code='PRIMARY' FOR SHARE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Authoritative primary accounting period is unavailable' USING ERRCODE='22023'; END IF;
  SELECT count(*) INTO population_count FROM source_document d JOIN raw_event e ON e.tenant_id=d.tenant_id AND e.entity_id=d.entity_id AND e.raw_event_id=d.raw_event_id AND e.source_record_id=d.source_record_id AND e.source_version=d.source_version AND e.is_current JOIN source_document_line l ON l.tenant_id=d.tenant_id AND l.entity_id=d.entity_id AND l.source_document_id=d.source_document_id WHERE d.tenant_id=p_tenant AND d.entity_id=p_entity AND d.source_module='loan' AND d.document_type='CONSTRUCTION_LOAN_TRANSACTION' AND d.accounting_date BETWEEN period_row.starts_on AND period_row.ends_on AND coalesce(l.external_dimension_refs->>'statement_balance_kind','')<>'CLOSING_PRINCIPAL_BALANCE';
  IF population_count>p_limit THEN RAISE EXCEPTION 'Complete construction loan decision population exceeds the bounded limit' USING ERRCODE='54000'; END IF;
  RETURN QUERY
  SELECT d.source_document_id,l.source_document_line_id,d.payload_hash,
    refs_jsonb_hash(jsonb_build_object('schema_version','AI_CONSTRUCTION_LOAN_DECISION_SOURCE_LINE_V1','source_document_line_id',l.source_document_line_id,'source_line_id',l.source_line_id,'line_no',l.line_no,'business_date',d.business_date,'accounting_date',d.accounting_date,'currency',d.currency,'amount',l.amount,'direction',l.direction,'description',l.description,'lender_ref',l.party_ref,'loan_ref',l.loan_ref,'transaction_kind',l.external_dimension_refs->>'transaction_kind','bank_account_ref',l.bank_account_ref,'project_ref',l.project_ref,'property_ref',l.property_ref,'member_ref',NULLIF(l.external_dimension_refs->>'member_ref',''),'cost_code_ref',l.cost_code_ref,'raw_event_id',d.raw_event_id,'source_record_id',d.source_record_id,'source_version',d.source_version)),
    p_entity,p_period,d.business_date,d.accounting_date,d.currency::text,abs(l.amount)::text,l.direction,l.loan_ref,l.party_ref,l.external_dimension_refs->>'transaction_kind',l.description,l.bank_account_ref,l.project_ref,l.property_ref,CASE WHEN EXISTS(SELECT 1 FROM member_master mm WHERE mm.tenant_id=p_tenant AND mm.entity_id=p_entity AND mm.member_type='BANK' AND mm.member_ref=l.bank_account_ref AND mm.active) THEN l.bank_account_ref ELSE NULL END,l.cost_code_ref,
    (SELECT count(*)::int FROM source_link sl JOIN attachment a ON a.tenant_id=sl.tenant_id AND a.entity_id=sl.entity_id AND a.attachment_id=sl.attachment_id WHERE sl.tenant_id=p_tenant AND sl.entity_id=p_entity AND sl.source_document_id=d.source_document_id AND sl.link_type='SOURCE_ATTACHMENT'),
    ARRAY(SELECT a.attachment_id FROM source_link sl JOIN attachment a ON a.tenant_id=sl.tenant_id AND a.entity_id=sl.entity_id AND a.attachment_id=sl.attachment_id WHERE sl.tenant_id=p_tenant AND sl.entity_id=p_entity AND sl.source_document_id=d.source_document_id AND sl.link_type='SOURCE_ATTACHMENT' ORDER BY a.attachment_id),
    COALESCE((SELECT jsonb_agg(jsonb_build_object('attachment_id',a.attachment_id,'content_hash',a.content_hash,'finalization_status',a.finalization_status,'scan_status',a.scan_status,'storage_version',a.storage_version,'evidence_type','source_attachment') ORDER BY a.attachment_id) FROM source_link sl JOIN attachment a ON a.tenant_id=sl.tenant_id AND a.entity_id=sl.entity_id AND a.attachment_id=sl.attachment_id WHERE sl.tenant_id=p_tenant AND sl.entity_id=p_entity AND sl.source_document_id=d.source_document_id AND sl.link_type='SOURCE_ATTACHMENT'),'[]'::jsonb),
    d.raw_event_id,d.source_record_id,d.source_version,d.status::text,
    CASE WHEN (SELECT count(*) FROM source_document d2 JOIN raw_event e2 ON e2.tenant_id=d2.tenant_id AND e2.entity_id=d2.entity_id AND e2.raw_event_id=d2.raw_event_id AND e2.is_current JOIN source_document_line l2 ON l2.tenant_id=d2.tenant_id AND l2.entity_id=d2.entity_id AND l2.source_document_id=d2.source_document_id WHERE d2.tenant_id=p_tenant AND d2.entity_id=p_entity AND d2.source_module='loan' AND d2.document_type='CONSTRUCTION_LOAN_TRANSACTION' AND l2.loan_ref=l.loan_ref AND l2.external_dimension_refs->>'transaction_kind'=l.external_dimension_refs->>'transaction_kind' AND d2.business_date=d.business_date AND d2.currency=d.currency AND abs(l2.amount)=abs(l.amount))>1 THEN 'POSSIBLE' ELSE 'NONE' END,
    CASE WHEN EXISTS(SELECT 1 FROM source_link x JOIN journal_entry j ON j.tenant_id=x.tenant_id AND j.entity_id=x.entity_id AND j.journal_entry_id=x.journal_entry_id WHERE x.tenant_id=p_tenant AND x.entity_id=p_entity AND x.source_document_id=d.source_document_id AND j.status='POSTED') THEN 'POSTED' WHEN EXISTS(SELECT 1 FROM source_link x JOIN journal_entry j ON j.tenant_id=x.tenant_id AND j.entity_id=x.entity_id AND j.journal_entry_id=x.journal_entry_id WHERE x.tenant_id=p_tenant AND x.entity_id=p_entity AND x.source_document_id=d.source_document_id) THEN 'DRAFT' ELSE 'NOT_RECORDED' END
  FROM source_document d JOIN raw_event e ON e.tenant_id=d.tenant_id AND e.entity_id=d.entity_id AND e.raw_event_id=d.raw_event_id AND e.source_record_id=d.source_record_id AND e.source_version=d.source_version AND e.is_current JOIN source_document_line l ON l.tenant_id=d.tenant_id AND l.entity_id=d.entity_id AND l.source_document_id=d.source_document_id
  WHERE d.tenant_id=p_tenant AND d.entity_id=p_entity AND d.source_module='loan' AND d.document_type='CONSTRUCTION_LOAN_TRANSACTION' AND d.accounting_date BETWEEN period_row.starts_on AND period_row.ends_on AND coalesce(l.external_dimension_refs->>'statement_balance_kind','')<>'CLOSING_PRINCIPAL_BALANCE'
  ORDER BY d.accounting_date,d.source_document_id,l.line_no,l.source_document_line_id LIMIT p_limit;
END $$;
REVOKE ALL ON FUNCTION refs_read_ai_construction_loan_decision_source(uuid,uuid,uuid,integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION refs_read_ai_construction_loan_decision_source(uuid,uuid,uuid,integer) TO refs_app;

ALTER FUNCTION refs_create_ai_accounting_decision_draft(uuid,uuid,uuid,text,text,text,text,text) RENAME TO refs_create_ai_accounting_decision_draft_v257;
REVOKE ALL ON FUNCTION refs_create_ai_accounting_decision_draft_v257(uuid,uuid,uuid,text,text,text,text,text) FROM PUBLIC,refs_app;
CREATE FUNCTION refs_create_ai_accounting_decision_draft(p_tenant uuid,p_entity uuid,p_decision uuid,p_expected_decision_hash text,p_expected_acceptance_hash text,p_reason text,p_idempotency_key text,p_request_hash text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE d ai_accounting_decision; source_type text; source_line uuid; expected_attachments jsonb; actual_attachments jsonb; expected_accounts jsonb; actual_accounts jsonb; account_codes text[]; duplicate_count integer;
BEGIN
  SELECT * INTO d FROM ai_accounting_decision WHERE tenant_id=p_tenant AND entity_id=p_entity AND ai_accounting_decision_id=p_decision FOR SHARE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Exact accepted decision evidence is required' USING ERRCODE='40001'; END IF;
  source_type:=d.packet#>>'{source,source_type}';
  IF source_type='INVOICE' THEN RETURN refs_create_ai_accounting_decision_draft_v257(p_tenant,p_entity,p_decision,p_expected_decision_hash,p_expected_acceptance_hash,p_reason,p_idempotency_key,p_request_hash); END IF;
  IF source_type<>'LOAN_TRANSACTION' THEN RAISE EXCEPTION 'Decision source type is not executable by the standard Draft dispatcher' USING ERRCODE='23514'; END IF;
  IF d.packet#>>'{source,admission_status}'<>'ADMITTED' OR d.packet#>>'{source,duplicate_status}'<>'NONE' THEN RAISE EXCEPTION 'Construction loan decision is not admitted and unique' USING ERRCODE='40001'; END IF;
  LOCK TABLE source_document IN SHARE MODE;
  LOCK TABLE source_document_line IN SHARE MODE;
  source_line:=(d.packet#>>'{source,source_document_line_id}')::uuid;
  PERFORM 1 FROM source_document WHERE tenant_id=p_tenant AND entity_id=p_entity AND source_document_id=d.source_document_id FOR UPDATE;
  PERFORM 1 FROM source_document sd JOIN raw_event re ON re.tenant_id=sd.tenant_id AND re.entity_id=sd.entity_id AND re.raw_event_id=sd.raw_event_id AND re.source_record_id=sd.source_record_id AND re.source_version=sd.source_version AND re.is_current JOIN source_document_line sl ON sl.tenant_id=sd.tenant_id AND sl.entity_id=sd.entity_id AND sl.source_document_id=sd.source_document_id AND sl.source_document_line_id=source_line WHERE sd.tenant_id=p_tenant AND sd.entity_id=p_entity AND sd.source_document_id=d.source_document_id AND sd.source_module='loan' AND sd.document_type='CONSTRUCTION_LOAN_TRANSACTION' AND sd.status='READY_FOR_DRAFT' AND sd.payload_hash=d.packet#>>'{source,source_payload_hash}' AND refs_jsonb_hash(jsonb_build_object('schema_version','AI_CONSTRUCTION_LOAN_DECISION_SOURCE_LINE_V1','source_document_line_id',sl.source_document_line_id,'source_line_id',sl.source_line_id,'line_no',sl.line_no,'business_date',sd.business_date,'accounting_date',sd.accounting_date,'currency',sd.currency,'amount',sl.amount,'direction',sl.direction,'description',sl.description,'lender_ref',sl.party_ref,'loan_ref',sl.loan_ref,'transaction_kind',sl.external_dimension_refs->>'transaction_kind','bank_account_ref',sl.bank_account_ref,'project_ref',sl.project_ref,'property_ref',sl.property_ref,'member_ref',NULLIF(sl.external_dimension_refs->>'member_ref',''),'cost_code_ref',sl.cost_code_ref,'raw_event_id',sd.raw_event_id,'source_record_id',sd.source_record_id,'source_version',sd.source_version))=d.packet#>>'{source,source_line_hash}' AND sd.business_date=(d.packet#>>'{source,business_date}')::date AND sd.accounting_date=(d.packet->>'accounting_date')::date AND sd.currency::text=d.packet#>>'{source,currency}' AND abs(sl.amount)=(d.packet#>>'{source,amount}')::numeric AND sl.loan_ref=d.packet#>>'{source,source_detail,loan_ref}' AND sl.external_dimension_refs->>'transaction_kind'=d.packet#>>'{source,source_detail,transaction_kind}' AND sl.project_ref IS NOT DISTINCT FROM d.packet#>>'{source,project_ref}' AND sl.property_ref IS NOT DISTINCT FROM d.packet#>>'{source,property_ref}' AND sl.cost_code_ref IS NOT DISTINCT FROM d.packet#>>'{source,cost_code_ref}' FOR SHARE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Construction loan retained source changed after AI decision' USING ERRCODE='40001'; END IF;
  SELECT count(*) INTO duplicate_count FROM source_document sd JOIN raw_event re ON re.tenant_id=sd.tenant_id AND re.entity_id=sd.entity_id AND re.raw_event_id=sd.raw_event_id AND re.source_record_id=sd.source_record_id AND re.source_version=sd.source_version AND re.is_current JOIN source_document_line sl ON sl.tenant_id=sd.tenant_id AND sl.entity_id=sd.entity_id AND sl.source_document_id=sd.source_document_id WHERE sd.tenant_id=p_tenant AND sd.entity_id=p_entity AND sd.source_module='loan' AND sd.document_type='CONSTRUCTION_LOAN_TRANSACTION' AND sl.loan_ref=d.packet#>>'{source,source_detail,loan_ref}' AND sl.external_dimension_refs->>'transaction_kind'=d.packet#>>'{source,source_detail,transaction_kind}' AND sd.business_date=(d.packet#>>'{source,business_date}')::date AND sd.currency::text=d.packet#>>'{source,currency}' AND abs(sl.amount)=(d.packet#>>'{source,amount}')::numeric;
  IF duplicate_count<>1 THEN RAISE EXCEPTION 'Construction loan source uniqueness changed after AI decision' USING ERRCODE='40001'; END IF;
  IF EXISTS(SELECT 1 FROM source_link x JOIN journal_entry j ON j.tenant_id=x.tenant_id AND j.entity_id=x.entity_id AND j.journal_entry_id=x.journal_entry_id WHERE x.tenant_id=p_tenant AND x.entity_id=p_entity AND x.source_document_id=d.source_document_id AND NOT EXISTS(SELECT 1 FROM ai_accounting_decision_draft_evidence de WHERE de.tenant_id=p_tenant AND de.entity_id=p_entity AND de.ai_accounting_decision_id=p_decision AND de.journal_entry_id=j.journal_entry_id)) THEN RAISE EXCEPTION 'Construction loan source acquired accounting evidence after AI decision' USING ERRCODE='40001'; END IF;
  PERFORM 1 FROM source_link sl JOIN attachment a ON a.tenant_id=sl.tenant_id AND a.entity_id=sl.entity_id AND a.attachment_id=sl.attachment_id WHERE sl.tenant_id=p_tenant AND sl.entity_id=p_entity AND sl.source_document_id=d.source_document_id AND sl.link_type='SOURCE_ATTACHMENT' FOR SHARE OF sl,a;
  expected_attachments:=d.packet#>'{source,source_detail,execution_evidence,attachments}';
  SELECT COALESCE(jsonb_agg(jsonb_build_object('attachment_id',a.attachment_id,'content_hash',a.content_hash,'finalization_status',a.finalization_status,'scan_status',a.scan_status,'storage_version',a.storage_version,'evidence_type','source_attachment') ORDER BY a.attachment_id),'[]'::jsonb) INTO actual_attachments FROM source_link sl JOIN attachment a ON a.tenant_id=sl.tenant_id AND a.entity_id=sl.entity_id AND a.attachment_id=sl.attachment_id WHERE sl.tenant_id=p_tenant AND sl.entity_id=p_entity AND sl.source_document_id=d.source_document_id AND sl.link_type='SOURCE_ATTACHMENT';
  IF expected_attachments IS NULL OR actual_attachments<>expected_attachments OR jsonb_array_length(actual_attachments)<1 OR EXISTS(SELECT 1 FROM jsonb_array_elements(actual_attachments) x WHERE x->>'scan_status'<>'CLEAN' OR x->>'finalization_status'<>'VERIFIED_CLEAN') THEN RAISE EXCEPTION 'Construction loan attachment evidence changed or is not clean' USING ERRCODE='40001'; END IF;
  expected_accounts:=d.packet#>'{source,source_detail,execution_evidence,account_master}';SELECT array_agg(value ORDER BY value) INTO account_codes FROM jsonb_array_elements_text(jsonb_path_query_array(d.packet,'$.approved_account_policies[*].account_code')) value;PERFORM 1 FROM account_master a WHERE a.tenant_id=p_tenant AND a.entity_id=p_entity AND a.account_code=ANY(account_codes) FOR SHARE;SELECT COALESCE(jsonb_agg(jsonb_build_object('account_code',a.account_code,'active',a.active,'required_member_type',a.required_member_type,'requires_member',a.requires_member) ORDER BY a.account_code),'[]'::jsonb) INTO actual_accounts FROM account_master a WHERE a.tenant_id=p_tenant AND a.entity_id=p_entity AND a.account_code=ANY(account_codes);
  IF expected_accounts IS NULL OR actual_accounts<>expected_accounts OR jsonb_array_length(actual_accounts)<>cardinality(account_codes) OR EXISTS(SELECT 1 FROM jsonb_array_elements(actual_accounts) x WHERE (x->>'active')::boolean IS DISTINCT FROM true) THEN RAISE EXCEPTION 'Construction loan account-master evidence changed or is not executable' USING ERRCODE='40001'; END IF;
  IF d.packet#>>'{source,member_ref}' IS NOT NULL AND NOT EXISTS(SELECT 1 FROM member_master m WHERE m.tenant_id=p_tenant AND m.entity_id=p_entity AND m.member_ref=d.packet#>>'{source,member_ref}' AND m.member_type='BANK' AND m.active FOR SHARE) THEN RAISE EXCEPTION 'Construction loan BANK member evidence changed or is unavailable' USING ERRCODE='40001'; END IF;
  RETURN refs_create_ai_accounting_decision_draft_v254(p_tenant,p_entity,p_decision,p_expected_decision_hash,p_expected_acceptance_hash,p_reason,p_idempotency_key,p_request_hash);
END $$;
REVOKE ALL ON FUNCTION refs_create_ai_accounting_decision_draft(uuid,uuid,uuid,text,text,text,text,text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION refs_create_ai_accounting_decision_draft(uuid,uuid,uuid,text,text,text,text,text) TO refs_app;
COMMIT;
