BEGIN;

CREATE FUNCTION refs_read_ai_invoice_decision_population_page(
  p_tenant uuid,p_entity uuid,p_period uuid,p_after_date date DEFAULT NULL,
  p_after_document uuid DEFAULT NULL,p_after_line_no integer DEFAULT NULL,
  p_after_line uuid DEFAULT NULL,p_page_size integer DEFAULT 250
)
RETURNS TABLE(line_no integer,source_document_id uuid,source_document_line_id uuid,source_payload_hash text,source_line_hash text,tenant_id uuid,entity_id uuid,accounting_period_id uuid,accounting_date date,vendor_ref text,vendor_member_ref text,invoice_no text,invoice_date date,currency text,amount text,service_period_start date,service_period_end date,description text,project_ref text,property_ref text,member_ref text,charge_code text,contract_id text,service_frequency text,source_attachment_count integer,source_attachment_ids uuid[],source_attachment_evidence jsonb,accounting_status text,posted_debit_account_classes text[],duplicate_status text,retained_outcome text,retained_exception_codes jsonb,source_status text)
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
BEGIN
  PERFORM refs_assert_scope(p_tenant,p_entity,'AI.ANALYSIS.EXPLAIN');
  IF p_page_size IS NULL OR p_page_size<1 OR p_page_size>500 THEN RAISE EXCEPTION 'AI decision invoice page size must be 1-500' USING ERRCODE='22023'; END IF;
  IF (p_after_date IS NULL)::integer+(p_after_document IS NULL)::integer+(p_after_line_no IS NULL)::integer+(p_after_line IS NULL)::integer NOT IN (0,4) THEN RAISE EXCEPTION 'AI decision invoice cursor must be wholly present or absent' USING ERRCODE='22023'; END IF;
  IF NOT EXISTS(SELECT 1 FROM accounting_period p WHERE p.tenant_id=p_tenant AND p.entity_id=p_entity AND p.period_id=p_period AND p.ledger_code='PRIMARY') THEN RAISE EXCEPTION 'Authoritative primary accounting period is unavailable' USING ERRCODE='22023'; END IF;
  RETURN QUERY
  SELECT l.line_no,d.source_document_id,l.source_document_line_id,d.payload_hash,r.raw_row_hash,p_tenant,p_entity,p_period,d.accounting_date,
         l.party_ref,CASE WHEN EXISTS(SELECT 1 FROM member_master mm WHERE mm.tenant_id=p_tenant AND mm.entity_id=p_entity AND mm.member_ref=l.party_ref AND mm.member_type='VENDOR' AND mm.active) THEN l.party_ref ELSE NULL END,d.document_no,(l.external_dimension_refs->>'signed_invoice_date')::date,d.currency::text,
         to_char(round(abs(l.amount),4),'FM999999999999999999990.0000'),NULLIF(l.external_dimension_refs->>'signed_service_period_start','')::date,
         NULLIF(l.external_dimension_refs->>'signed_service_period_end','')::date,NULLIF(l.external_dimension_refs->>'signed_invoice_description',''),l.project_ref,l.property_ref,NULL::text,
         NULLIF(l.external_dimension_refs->>'signed_charge_code',''),NULLIF(l.external_dimension_refs->>'signed_contract_id',''),NULLIF(l.external_dimension_refs->>'signed_service_frequency',''),
         (SELECT count(*)::integer FROM source_link sal JOIN attachment a ON a.tenant_id=sal.tenant_id AND a.entity_id=sal.entity_id AND a.attachment_id=sal.attachment_id WHERE sal.tenant_id=p_tenant AND sal.entity_id=p_entity AND sal.source_document_id=d.source_document_id AND sal.link_type='SOURCE_ATTACHMENT'),
         ARRAY(SELECT a.attachment_id FROM source_link sal JOIN attachment a ON a.tenant_id=sal.tenant_id AND a.entity_id=sal.entity_id AND a.attachment_id=sal.attachment_id WHERE sal.tenant_id=p_tenant AND sal.entity_id=p_entity AND sal.source_document_id=d.source_document_id AND sal.link_type='SOURCE_ATTACHMENT' ORDER BY a.attachment_id),
         COALESCE((SELECT jsonb_agg(jsonb_build_object('attachment_id',a.attachment_id,'content_hash',a.content_hash,'finalization_status',a.finalization_status,'scan_status',a.scan_status,'storage_version',a.storage_version) ORDER BY a.attachment_id) FROM source_link sal JOIN attachment a ON a.tenant_id=sal.tenant_id AND a.entity_id=sal.entity_id AND a.attachment_id=sal.attachment_id WHERE sal.tenant_id=p_tenant AND sal.entity_id=p_entity AND sal.source_document_id=d.source_document_id AND sal.link_type='SOURCE_ATTACHMENT'),'[]'::jsonb),
         CASE WHEN EXISTS(SELECT 1 FROM source_link sl JOIN journal_entry j ON j.tenant_id=sl.tenant_id AND j.entity_id=sl.entity_id AND j.journal_entry_id=sl.journal_entry_id WHERE sl.tenant_id=p_tenant AND sl.entity_id=p_entity AND sl.source_document_id=d.source_document_id AND j.status='POSTED') THEN 'POSTED' WHEN EXISTS(SELECT 1 FROM source_link sl JOIN journal_entry j ON j.tenant_id=sl.tenant_id AND j.entity_id=sl.entity_id AND j.journal_entry_id=sl.journal_entry_id WHERE sl.tenant_id=p_tenant AND sl.entity_id=p_entity AND sl.source_document_id=d.source_document_id) THEN 'DRAFT' ELSE 'NOT_RECORDED' END,
         ARRAY(SELECT DISTINCT CASE WHEN jl.account_code LIKE '1%' THEN 'ASSET' WHEN jl.account_code LIKE '2%' THEN 'LIABILITY' WHEN jl.account_code LIKE '3%' THEN 'EQUITY' WHEN jl.account_code LIKE '4%' THEN 'REVENUE' WHEN jl.account_code~'^[5-9]' THEN 'EXPENSE' ELSE 'UNCLASSIFIED' END FROM source_link sl JOIN journal_entry j ON j.tenant_id=sl.tenant_id AND j.entity_id=sl.entity_id AND j.journal_entry_id=sl.journal_entry_id JOIN journal_line jl ON jl.tenant_id=j.tenant_id AND jl.entity_id=j.entity_id AND jl.journal_entry_id=sl.journal_entry_id AND (sl.journal_line_id IS NULL OR sl.journal_line_id=jl.journal_line_id) WHERE sl.tenant_id=p_tenant AND sl.entity_id=p_entity AND sl.source_document_id=d.source_document_id AND j.status='POSTED' AND jl.debit_amount>0 ORDER BY 1),
         CASE WHEN EXISTS(SELECT 1 FROM ai_duplicate_payable_finding f WHERE f.tenant_id=p_tenant AND f.entity_id=p_entity AND f.status='OPEN' AND d.source_document_id IN(f.source_document_id,f.candidate_source_document_id)) THEN 'POSSIBLE' ELSE 'NONE' END,r.outcome,r.exception_codes,d.status::text
    FROM wbs_final1_retained_source_row r JOIN raw_event e ON e.tenant_id=r.tenant_id AND e.entity_id=r.entity_id AND e.raw_event_id=r.raw_event_id AND e.source_record_id=r.source_record_id AND e.source_version=r.source_version AND e.is_current JOIN source_document d ON d.tenant_id=r.tenant_id AND d.entity_id=r.entity_id AND d.source_document_id=r.source_document_id AND d.raw_event_id=e.raw_event_id JOIN source_document_line l ON l.tenant_id=r.tenant_id AND l.entity_id=r.entity_id AND l.source_document_line_id=r.source_document_line_id AND l.source_document_id=r.source_document_id
   WHERE r.tenant_id=p_tenant AND r.entity_id=p_entity AND r.accounting_period_id=p_period AND r.domain='PAYABLES'
     AND (p_after_date IS NULL OR (d.accounting_date,d.source_document_id,l.line_no,l.source_document_line_id)>(p_after_date,p_after_document,p_after_line_no,p_after_line))
   ORDER BY d.accounting_date,d.source_document_id,l.line_no,l.source_document_line_id LIMIT p_page_size;
END $$;

CREATE FUNCTION refs_read_ai_loan_decision_population_page(
  p_tenant uuid,p_entity uuid,p_period uuid,p_after_date date DEFAULT NULL,
  p_after_document uuid DEFAULT NULL,p_after_line_no integer DEFAULT NULL,
  p_after_line uuid DEFAULT NULL,p_page_size integer DEFAULT 250
)
RETURNS TABLE(line_no integer,source_document_id uuid,source_document_line_id uuid,source_payload_hash text,source_line_hash text,tenant_id uuid,entity_id uuid,accounting_period_id uuid,business_date date,accounting_date date,currency text,amount text,direction text,loan_ref text,lender_ref text,transaction_kind text,description text,bank_account_ref text,project_ref text,property_ref text,member_ref text,cost_code_ref text,source_attachment_count integer,source_attachment_ids uuid[],source_attachment_evidence jsonb,raw_event_id uuid,source_record_id text,source_version text,source_status text,duplicate_status text,accounting_status text)
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE period_row accounting_period;
BEGIN
  PERFORM refs_assert_scope(p_tenant,p_entity,'AI.ANALYSIS.EXPLAIN');
  IF p_page_size IS NULL OR p_page_size<1 OR p_page_size>500 THEN RAISE EXCEPTION 'AI decision loan page size must be 1-500' USING ERRCODE='22023'; END IF;
  IF (p_after_date IS NULL)::integer+(p_after_document IS NULL)::integer+(p_after_line_no IS NULL)::integer+(p_after_line IS NULL)::integer NOT IN (0,4) THEN RAISE EXCEPTION 'AI decision loan cursor must be wholly present or absent' USING ERRCODE='22023'; END IF;
  SELECT ap.* INTO period_row FROM accounting_period ap WHERE ap.tenant_id=p_tenant AND ap.entity_id=p_entity AND ap.period_id=p_period AND ap.ledger_code='PRIMARY' FOR SHARE;
  IF NOT FOUND THEN RAISE EXCEPTION 'Authoritative primary accounting period is unavailable' USING ERRCODE='22023'; END IF;
  RETURN QUERY
  SELECT l.line_no,d.source_document_id,l.source_document_line_id,d.payload_hash,
    refs_jsonb_hash(jsonb_build_object('schema_version','AI_CONSTRUCTION_LOAN_DECISION_SOURCE_LINE_V1','source_document_line_id',l.source_document_line_id,'source_line_id',l.source_line_id,'line_no',l.line_no,'business_date',d.business_date,'accounting_date',d.accounting_date,'currency',d.currency,'amount',l.amount,'direction',l.direction,'description',l.description,'lender_ref',l.party_ref,'loan_ref',l.loan_ref,'transaction_kind',l.external_dimension_refs->>'transaction_kind','bank_account_ref',l.bank_account_ref,'project_ref',l.project_ref,'property_ref',l.property_ref,'member_ref',NULLIF(l.external_dimension_refs->>'member_ref',''),'cost_code_ref',l.cost_code_ref,'raw_event_id',d.raw_event_id,'source_record_id',d.source_record_id,'source_version',d.source_version)),
    p_tenant,p_entity,p_period,d.business_date,d.accounting_date,d.currency::text,to_char(round(abs(l.amount),4),'FM999999999999999999990.0000'),l.direction,l.loan_ref,l.party_ref,l.external_dimension_refs->>'transaction_kind',l.description,l.bank_account_ref,l.project_ref,l.property_ref,CASE WHEN EXISTS(SELECT 1 FROM member_master mm WHERE mm.tenant_id=p_tenant AND mm.entity_id=p_entity AND mm.member_type='BANK' AND mm.member_ref=l.bank_account_ref AND mm.active) THEN l.bank_account_ref ELSE NULL END,l.cost_code_ref,
    (SELECT count(*)::int FROM source_link sl JOIN attachment a ON a.tenant_id=sl.tenant_id AND a.entity_id=sl.entity_id AND a.attachment_id=sl.attachment_id WHERE sl.tenant_id=p_tenant AND sl.entity_id=p_entity AND sl.source_document_id=d.source_document_id AND sl.link_type='SOURCE_ATTACHMENT'),
    ARRAY(SELECT a.attachment_id FROM source_link sl JOIN attachment a ON a.tenant_id=sl.tenant_id AND a.entity_id=sl.entity_id AND a.attachment_id=sl.attachment_id WHERE sl.tenant_id=p_tenant AND sl.entity_id=p_entity AND sl.source_document_id=d.source_document_id AND sl.link_type='SOURCE_ATTACHMENT' ORDER BY a.attachment_id),
    COALESCE((SELECT jsonb_agg(jsonb_build_object('attachment_id',a.attachment_id,'content_hash',a.content_hash,'finalization_status',a.finalization_status,'scan_status',a.scan_status,'storage_version',a.storage_version,'evidence_type','source_attachment') ORDER BY a.attachment_id) FROM source_link sl JOIN attachment a ON a.tenant_id=sl.tenant_id AND a.entity_id=sl.entity_id AND a.attachment_id=sl.attachment_id WHERE sl.tenant_id=p_tenant AND sl.entity_id=p_entity AND sl.source_document_id=d.source_document_id AND sl.link_type='SOURCE_ATTACHMENT'),'[]'::jsonb),d.raw_event_id,d.source_record_id,d.source_version,d.status::text,
    CASE WHEN (SELECT count(*) FROM source_document d2 JOIN raw_event e2 ON e2.tenant_id=d2.tenant_id AND e2.entity_id=d2.entity_id AND e2.raw_event_id=d2.raw_event_id AND e2.is_current JOIN source_document_line l2 ON l2.tenant_id=d2.tenant_id AND l2.entity_id=d2.entity_id AND l2.source_document_id=d2.source_document_id WHERE d2.tenant_id=p_tenant AND d2.entity_id=p_entity AND d2.source_module='loan' AND d2.document_type='CONSTRUCTION_LOAN_TRANSACTION' AND l2.loan_ref=l.loan_ref AND l2.external_dimension_refs->>'transaction_kind'=l.external_dimension_refs->>'transaction_kind' AND d2.business_date=d.business_date AND d2.currency=d.currency AND abs(l2.amount)=abs(l.amount))>1 THEN 'POSSIBLE' ELSE 'NONE' END,
    CASE WHEN EXISTS(SELECT 1 FROM source_link x JOIN journal_entry j ON j.tenant_id=x.tenant_id AND j.entity_id=x.entity_id AND j.journal_entry_id=x.journal_entry_id WHERE x.tenant_id=p_tenant AND x.entity_id=p_entity AND x.source_document_id=d.source_document_id AND j.status='POSTED') THEN 'POSTED' WHEN EXISTS(SELECT 1 FROM source_link x JOIN journal_entry j ON j.tenant_id=x.tenant_id AND j.entity_id=x.entity_id AND j.journal_entry_id=x.journal_entry_id WHERE x.tenant_id=p_tenant AND x.entity_id=p_entity AND x.source_document_id=d.source_document_id) THEN 'DRAFT' ELSE 'NOT_RECORDED' END
  FROM source_document d JOIN raw_event e ON e.tenant_id=d.tenant_id AND e.entity_id=d.entity_id AND e.raw_event_id=d.raw_event_id AND e.source_record_id=d.source_record_id AND e.source_version=d.source_version AND e.is_current JOIN source_document_line l ON l.tenant_id=d.tenant_id AND l.entity_id=d.entity_id AND l.source_document_id=d.source_document_id
  WHERE d.tenant_id=p_tenant AND d.entity_id=p_entity AND d.source_module='loan' AND d.document_type='CONSTRUCTION_LOAN_TRANSACTION' AND d.accounting_date BETWEEN period_row.starts_on AND period_row.ends_on AND coalesce(l.external_dimension_refs->>'statement_balance_kind','')<>'CLOSING_PRINCIPAL_BALANCE'
    AND (p_after_date IS NULL OR (d.accounting_date,d.source_document_id,l.line_no,l.source_document_line_id)>(p_after_date,p_after_document,p_after_line_no,p_after_line))
  ORDER BY d.accounting_date,d.source_document_id,l.line_no,l.source_document_line_id LIMIT p_page_size;
END $$;

REVOKE ALL ON FUNCTION refs_read_ai_invoice_decision_population_page(uuid,uuid,uuid,date,uuid,integer,uuid,integer),refs_read_ai_loan_decision_population_page(uuid,uuid,uuid,date,uuid,integer,uuid,integer) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION refs_read_ai_invoice_decision_population_page(uuid,uuid,uuid,date,uuid,integer,uuid,integer),refs_read_ai_loan_decision_population_page(uuid,uuid,uuid,date,uuid,integer,uuid,integer) TO refs_app;

ALTER FUNCTION refs_retain_ai_accounting_decision_batch(uuid,uuid,uuid,jsonb,text,text) RENAME TO refs_retain_ai_accounting_decision_batch_v256;
REVOKE ALL ON FUNCTION refs_retain_ai_accounting_decision_batch_v256(uuid,uuid,uuid,jsonb,text,text) FROM PUBLIC,refs_app;
CREATE FUNCTION refs_retain_ai_accounting_decision_batch(p_tenant uuid,p_entity uuid,p_period uuid,p_packets jsonb,p_population_count integer,p_population_hash text,p_idempotency_key text,p_request_hash text)
RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE actor text:=refs_current_actor(); receipt idempotency_receipt; packet jsonb; item jsonb; receipts jsonb:='[]'::jsonb; response jsonb; expected_hash text; actual_population_hash text; actual_population_count integer; index_no integer:=0; row_count integer;
BEGIN
  PERFORM refs_assert_scope(p_tenant,p_entity,'AI.ANALYSIS.EXPLAIN');
  IF actor IS NULL THEN RAISE EXCEPTION 'Authenticated AI analysis actor missing' USING ERRCODE='42501'; END IF;
  IF jsonb_typeof(p_packets)<>'array' THEN RAISE EXCEPTION 'Decision batch packets must be an array' USING ERRCODE='22023'; END IF;
  row_count:=jsonb_array_length(p_packets);
  IF row_count>10000 THEN RAISE EXCEPTION 'Decision population exceeds 10000 packets' USING ERRCODE='22023'; END IF;
  IF NOT EXISTS(SELECT 1 FROM accounting_period WHERE tenant_id=p_tenant AND entity_id=p_entity AND period_id=p_period) THEN RAISE EXCEPTION 'Decision batch period is unavailable' USING ERRCODE='22023'; END IF;
  IF EXISTS(SELECT 1 FROM jsonb_array_elements(p_packets) x WHERE x->>'tenant_id' IS DISTINCT FROM p_tenant::text OR x->>'entity_id' IS DISTINCT FROM p_entity::text OR x->>'accounting_period_id' IS DISTINCT FROM p_period::text OR x#>>'{source,tenant_id}' IS DISTINCT FROM p_tenant::text OR x#>>'{source,entity_id}' IS DISTINCT FROM p_entity::text OR x#>>'{source,accounting_period_id}' IS DISTINCT FROM p_period::text OR x->>'accounting_date' IS DISTINCT FROM x#>>'{source,accounting_date}' OR x#>>'{action_flags,can_create_draft}' IS DISTINCT FROM 'false' OR x#>>'{action_flags,can_review}' IS DISTINCT FROM 'false' OR x#>>'{action_flags,can_approve}' IS DISTINCT FROM 'false' OR x#>>'{action_flags,can_post}' IS DISTINCT FROM 'false') THEN RAISE EXCEPTION 'Decision population scope or action contract drifted' USING ERRCODE='23514'; END IF;
  IF EXISTS(SELECT 1 FROM jsonb_array_elements(p_packets) x GROUP BY refs_jsonb_hash(x) HAVING count(*)>1) THEN RAISE EXCEPTION 'Decision population contains a duplicate canonical packet' USING ERRCODE='23514'; END IF;
  IF EXISTS(SELECT 1 FROM jsonb_array_elements(p_packets) x GROUP BY x#>>'{source,source_document_id}' HAVING count(*)>1) THEN RAISE EXCEPTION 'Decision population contains more than one decision for a retained source' USING ERRCODE='23514'; END IF;
  IF EXISTS(SELECT 1 FROM jsonb_array_elements(p_packets) x WHERE
    (x#>>'{source,source_type}'='INVOICE' AND NOT EXISTS(SELECT 1 FROM wbs_final1_retained_source_row r JOIN raw_event e ON e.tenant_id=r.tenant_id AND e.entity_id=r.entity_id AND e.raw_event_id=r.raw_event_id AND e.source_record_id=r.source_record_id AND e.source_version=r.source_version AND e.is_current JOIN source_document d ON d.tenant_id=r.tenant_id AND d.entity_id=r.entity_id AND d.source_document_id=r.source_document_id AND d.raw_event_id=e.raw_event_id WHERE r.tenant_id=p_tenant AND r.entity_id=p_entity AND r.accounting_period_id=p_period AND r.domain='PAYABLES' AND r.source_document_id=(x#>>'{source,source_document_id}')::uuid AND r.source_document_line_id=(x#>>'{source,source_document_line_id}')::uuid AND d.payload_hash=x#>>'{source,source_payload_hash}' AND r.raw_row_hash=x#>>'{source,source_line_hash}' AND to_char(d.accounting_date,'YYYY-MM-DD')=x->>'accounting_date'))
    OR (x#>>'{source,source_type}'='LOAN_TRANSACTION' AND NOT EXISTS(SELECT 1 FROM source_document d JOIN raw_event e ON e.tenant_id=d.tenant_id AND e.entity_id=d.entity_id AND e.raw_event_id=d.raw_event_id AND e.source_record_id=d.source_record_id AND e.source_version=d.source_version AND e.is_current JOIN source_document_line l ON l.tenant_id=d.tenant_id AND l.entity_id=d.entity_id AND l.source_document_id=d.source_document_id JOIN accounting_period ap ON ap.tenant_id=d.tenant_id AND ap.entity_id=d.entity_id AND ap.period_id=p_period AND ap.ledger_code='PRIMARY' WHERE d.tenant_id=p_tenant AND d.entity_id=p_entity AND d.source_module='loan' AND d.document_type='CONSTRUCTION_LOAN_TRANSACTION' AND d.accounting_date BETWEEN ap.starts_on AND ap.ends_on AND COALESCE(l.external_dimension_refs->>'statement_balance_kind','')<>'CLOSING_PRINCIPAL_BALANCE' AND d.source_document_id=(x#>>'{source,source_document_id}')::uuid AND l.source_document_line_id=(x#>>'{source,source_document_line_id}')::uuid AND d.payload_hash=x#>>'{source,source_payload_hash}' AND refs_jsonb_hash(jsonb_build_object('schema_version','AI_CONSTRUCTION_LOAN_DECISION_SOURCE_LINE_V1','source_document_line_id',l.source_document_line_id,'source_line_id',l.source_line_id,'line_no',l.line_no,'business_date',d.business_date,'accounting_date',d.accounting_date,'currency',d.currency,'amount',l.amount,'direction',l.direction,'description',l.description,'lender_ref',l.party_ref,'loan_ref',l.loan_ref,'transaction_kind',l.external_dimension_refs->>'transaction_kind','bank_account_ref',l.bank_account_ref,'project_ref',l.project_ref,'property_ref',l.property_ref,'member_ref',NULLIF(l.external_dimension_refs->>'member_ref',''),'cost_code_ref',l.cost_code_ref,'raw_event_id',d.raw_event_id,'source_record_id',d.source_record_id,'source_version',d.source_version))=x#>>'{source,source_line_hash}' AND to_char(d.accounting_date,'YYYY-MM-DD')=x->>'accounting_date'))
    OR x#>>'{source,source_type}' NOT IN ('INVOICE','LOAN_TRANSACTION')) THEN RAISE EXCEPTION 'Decision packet is not an exact current population member' USING ERRCODE='40001'; END IF;
  WITH population AS (
    SELECT 0 AS kind_order,p_tenant AS tenant_id,p_entity AS entity_id,p_period AS accounting_period_id,'INVOICE'::text AS source_kind,d.accounting_date,d.source_document_id,l.line_no,l.source_document_line_id,d.payload_hash AS source_payload_hash,r.raw_row_hash AS source_line_hash,r.outcome AS retained_outcome,r.exception_codes AS retained_exception_codes,d.status::text AS source_status
      FROM wbs_final1_retained_source_row r JOIN raw_event e ON e.tenant_id=r.tenant_id AND e.entity_id=r.entity_id AND e.raw_event_id=r.raw_event_id AND e.source_record_id=r.source_record_id AND e.source_version=r.source_version AND e.is_current JOIN source_document d ON d.tenant_id=r.tenant_id AND d.entity_id=r.entity_id AND d.source_document_id=r.source_document_id AND d.raw_event_id=e.raw_event_id JOIN source_document_line l ON l.tenant_id=r.tenant_id AND l.entity_id=r.entity_id AND l.source_document_line_id=r.source_document_line_id AND l.source_document_id=r.source_document_id
     WHERE r.tenant_id=p_tenant AND r.entity_id=p_entity AND r.accounting_period_id=p_period AND r.domain='PAYABLES'
    UNION ALL
    SELECT 1,p_tenant,p_entity,p_period,'LOAN_TRANSACTION',d.accounting_date,d.source_document_id,l.line_no,l.source_document_line_id,d.payload_hash,
      refs_jsonb_hash(jsonb_build_object('schema_version','AI_CONSTRUCTION_LOAN_DECISION_SOURCE_LINE_V1','source_document_line_id',l.source_document_line_id,'source_line_id',l.source_line_id,'line_no',l.line_no,'business_date',d.business_date,'accounting_date',d.accounting_date,'currency',d.currency,'amount',l.amount,'direction',l.direction,'description',l.description,'lender_ref',l.party_ref,'loan_ref',l.loan_ref,'transaction_kind',l.external_dimension_refs->>'transaction_kind','bank_account_ref',l.bank_account_ref,'project_ref',l.project_ref,'property_ref',l.property_ref,'member_ref',NULLIF(l.external_dimension_refs->>'member_ref',''),'cost_code_ref',l.cost_code_ref,'raw_event_id',d.raw_event_id,'source_record_id',d.source_record_id,'source_version',d.source_version))
      ,NULL::text,'[]'::jsonb,d.status::text
      FROM source_document d JOIN raw_event e ON e.tenant_id=d.tenant_id AND e.entity_id=d.entity_id AND e.raw_event_id=d.raw_event_id AND e.source_record_id=d.source_record_id AND e.source_version=d.source_version AND e.is_current JOIN source_document_line l ON l.tenant_id=d.tenant_id AND l.entity_id=d.entity_id AND l.source_document_id=d.source_document_id JOIN accounting_period ap ON ap.tenant_id=d.tenant_id AND ap.entity_id=d.entity_id AND ap.period_id=p_period AND ap.ledger_code='PRIMARY'
     WHERE d.tenant_id=p_tenant AND d.entity_id=p_entity AND d.source_module='loan' AND d.document_type='CONSTRUCTION_LOAN_TRANSACTION' AND d.accounting_date BETWEEN ap.starts_on AND ap.ends_on AND COALESCE(l.external_dimension_refs->>'statement_balance_kind','')<>'CLOSING_PRINCIPAL_BALANCE'
  ), attestation AS (
    SELECT count(*)::integer AS total_count,refs_jsonb_hash(COALESCE(jsonb_agg(jsonb_build_object('tenant_id',tenant_id,'entity_id',entity_id,'accounting_period_id',accounting_period_id,'source_kind',source_kind,'accounting_date',to_char(accounting_date,'YYYY-MM-DD'),'source_document_id',source_document_id,'line_no',line_no,'source_document_line_id',source_document_line_id,'source_payload_hash',source_payload_hash,'source_line_hash',source_line_hash,'retained_outcome',retained_outcome,'retained_exception_codes',retained_exception_codes,'source_status',source_status) ORDER BY kind_order,accounting_date,source_document_id,line_no,source_document_line_id),'[]'::jsonb)) AS population_hash FROM population
  ) SELECT total_count,population_hash INTO actual_population_count,actual_population_hash FROM attestation;
  IF p_population_count IS DISTINCT FROM row_count OR p_population_count IS DISTINCT FROM actual_population_count OR p_population_hash IS DISTINCT FROM actual_population_hash THEN RAISE EXCEPTION 'Decision population attestation drifted before retention' USING ERRCODE='40001'; END IF;
  expected_hash:=refs_jsonb_hash(jsonb_build_object('tenant_id',p_tenant,'entity_id',p_entity,'period_id',p_period,'packets',p_packets));
  IF p_request_hash<>expected_hash THEN RAISE EXCEPTION 'Decision batch retention hash is not canonical' USING ERRCODE='22023'; END IF;
  INSERT INTO idempotency_receipt(tenant_id,operation_scope,idempotency_key,request_hash,status,actor_id) VALUES(p_tenant,'AI_ACCOUNTING_DECISION_BATCH_RETAIN:'||p_entity,p_idempotency_key,p_request_hash,'IN_PROGRESS',actor) ON CONFLICT DO NOTHING;
  SELECT * INTO receipt FROM idempotency_receipt WHERE tenant_id=p_tenant AND operation_scope='AI_ACCOUNTING_DECISION_BATCH_RETAIN:'||p_entity AND idempotency_key=p_idempotency_key FOR UPDATE;
  IF receipt.request_hash<>p_request_hash OR receipt.actor_id<>actor THEN RAISE EXCEPTION 'Idempotency key reused with different batch or actor' USING ERRCODE='23505'; END IF;
  IF receipt.status='SUCCEEDED' THEN RETURN receipt.response_body||jsonb_build_object('idempotent',true); END IF;
  FOR packet IN SELECT value FROM jsonb_array_elements(p_packets) LOOP
    item:=refs_retain_ai_accounting_decision(p_tenant,p_entity,packet,refs_jsonb_hash(jsonb_build_object('parent_idempotency_key',p_idempotency_key,'packet_index',index_no)),refs_jsonb_hash(jsonb_build_object('tenant_id',p_tenant,'entity_id',p_entity,'packet',packet)));
    IF NOT (item ?& ARRAY['schema_version','ai_accounting_decision_id','decision_hash','packet_status','source_document_id','can_create_draft','can_review','can_approve','can_post','idempotent']) OR item-ARRAY['schema_version','ai_accounting_decision_id','decision_hash','packet_status','source_document_id','can_create_draft','can_review','can_approve','can_post','idempotent']<>'{}'::jsonb OR item->>'schema_version'<>'AI_ACCOUNTING_DECISION_RETAINED_V1' OR item->>'packet_status' NOT IN ('READY_FOR_HUMAN_REVIEW','EXCEPTION') OR item->>'can_create_draft'<>'false' OR item->>'can_review'<>'false' OR item->>'can_approve'<>'false' OR item->>'can_post'<>'false' THEN RAISE EXCEPTION 'Decision batch item returned unsafe evidence' USING ERRCODE='23514'; END IF;
    receipts:=receipts||jsonb_build_array(item);index_no:=index_no+1;
  END LOOP;
  response:=jsonb_build_object('schema_version','AI_ACCOUNTING_DECISION_RUN_RECEIPT_V1','accounting_period_id',p_period,'population',jsonb_build_object('total_count',actual_population_count,'population_hash',actual_population_hash,'population_complete',true),'row_count',row_count,'receipts',receipts,'can_create_draft',false,'can_review',false,'can_approve',false,'can_post',false,'idempotent',false);
  UPDATE idempotency_receipt SET status='SUCCEEDED',response_status=201,response_body=response,completed_at=clock_timestamp() WHERE tenant_id=p_tenant AND operation_scope='AI_ACCOUNTING_DECISION_BATCH_RETAIN:'||p_entity AND idempotency_key=p_idempotency_key;
  RETURN response;
END $$;
REVOKE ALL ON FUNCTION refs_retain_ai_accounting_decision_batch(uuid,uuid,uuid,jsonb,integer,text,text,text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION refs_retain_ai_accounting_decision_batch(uuid,uuid,uuid,jsonb,integer,text,text,text) TO refs_app;

COMMIT;
