BEGIN;

INSERT INTO permission_catalog(permission_code,domain,risk_class,sod_class)
VALUES('FIXED_ASSET.DISPOSAL.DRAFT','FIXED_ASSET','HIGH','FIXED_ASSET_DISPOSAL_MAKER')
ON CONFLICT(permission_code) DO UPDATE SET active=true,version=permission_catalog.version+1,effective_to=NULL;
INSERT INTO runtime_human_permission_authority(permission_code,authority_class)
VALUES('FIXED_ASSET.DISPOSAL.DRAFT','DRAFT') ON CONFLICT(permission_code) DO NOTHING;

CREATE TABLE fixed_asset_disposal_draft_binding(
  binding_id uuid PRIMARY KEY,
  tenant_id uuid NOT NULL,
  entity_id uuid NOT NULL,
  fixed_asset_register_evidence_id uuid NOT NULL REFERENCES fixed_asset_register_evidence,
  accounting_period_id uuid NOT NULL REFERENCES accounting_period,
  journal_entry_id uuid NOT NULL,
  source_document_id uuid NOT NULL REFERENCES source_document,
  source_document_version bigint NOT NULL CHECK(source_document_version>0),
  source_payload_hash text NOT NULL CHECK(source_payload_hash~'^sha256:[a-f0-9]{64}$'),
  register_evidence_hash text NOT NULL CHECK(register_evidence_hash~'^sha256:[a-f0-9]{64}$'),
  disposal_snapshot jsonb NOT NULL,
  disposal_snapshot_hash text NOT NULL CHECK(disposal_snapshot_hash~'^sha256:[a-f0-9]{64}$'),
  proceeds numeric(20,4) NOT NULL CHECK(proceeds>=0),
  proceeds_account_code text,
  proceeds_member_ref text,
  gain_loss_account_code text NOT NULL,
  journal_snapshot_hash text NOT NULL CHECK(journal_snapshot_hash~'^sha256:[a-f0-9]{64}$'),
  created_by text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  UNIQUE(tenant_id,entity_id,journal_entry_id),
  FOREIGN KEY(tenant_id,entity_id,journal_entry_id) REFERENCES journal_entry(tenant_id,entity_id,journal_entry_id),
  FOREIGN KEY(tenant_id,entity_id,source_document_id) REFERENCES source_document(tenant_id,entity_id,source_document_id),
  FOREIGN KEY(tenant_id,entity_id,proceeds_account_code) REFERENCES account_master(tenant_id,entity_id,account_code),
  FOREIGN KEY(tenant_id,entity_id,proceeds_member_ref) REFERENCES member_master(tenant_id,entity_id,member_ref),
  FOREIGN KEY(tenant_id,entity_id,gain_loss_account_code) REFERENCES account_master(tenant_id,entity_id,account_code),
  CHECK((proceeds=0 AND proceeds_account_code IS NULL AND proceeds_member_ref IS NULL) OR (proceeds>0 AND proceeds_account_code IS NOT NULL AND proceeds_member_ref IS NOT NULL))
);
ALTER TABLE fixed_asset_disposal_draft_binding ENABLE ROW LEVEL SECURITY;
CREATE POLICY fixed_asset_disposal_draft_binding_scope ON fixed_asset_disposal_draft_binding USING(tenant_id=refs_current_tenant() AND refs_entity_allowed(entity_id));
CREATE TRIGGER fixed_asset_disposal_draft_binding_immutable BEFORE UPDATE OR DELETE ON fixed_asset_disposal_draft_binding FOR EACH ROW EXECUTE FUNCTION reject_mutation();
REVOKE ALL ON fixed_asset_disposal_draft_binding FROM PUBLIC,refs_app;

CREATE FUNCTION refs_fixed_asset_disposal_snapshot(p_tenant uuid,p_entity uuid,p_asset uuid,p_period uuid,p_date date) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE asset fixed_asset_register_evidence;period accounting_period;posted_cost numeric(20,4):=0;posted_depreciation numeric(20,4):=0;posted_impairment numeric(20,4):=0;
 impairment_rows jsonb:='[]'::jsonb;acquisition_posted boolean:=false;disposal_recorded boolean:=false;later_movement boolean:=false;impairment_date_conflict boolean:=false;impairment_evidence_valid boolean:=true;carrying numeric(20,4);readiness text;
BEGIN
 SELECT * INTO asset FROM fixed_asset_register_evidence WHERE tenant_id=p_tenant AND entity_id=p_entity AND fixed_asset_register_evidence_id=p_asset FOR SHARE;
 IF NOT FOUND THEN RAISE EXCEPTION 'Scoped disposal asset missing' USING ERRCODE='P0002';END IF;
 SELECT * INTO period FROM accounting_period WHERE tenant_id=p_tenant AND entity_id=p_entity AND period_id=p_period AND ledger_code='PRIMARY' FOR SHARE;
 IF NOT FOUND THEN RAISE EXCEPTION 'Scoped disposal period missing' USING ERRCODE='P0002';END IF;
 SELECT EXISTS(SELECT 1 FROM fixed_asset_acquisition_posting p JOIN journal_entry j ON j.tenant_id=p.tenant_id AND j.entity_id=p.entity_id AND j.journal_entry_id=p.journal_entry_id AND j.status='POSTED' WHERE p.tenant_id=p_tenant AND p.entity_id=p_entity AND p.asset_id=p_asset AND j.journal_date<=p_date) INTO acquisition_posted;
 SELECT coalesce(sum(l.debit_amount-l.credit_amount),0) INTO posted_cost FROM ledger_line l JOIN journal_entry j ON j.tenant_id=l.tenant_id AND j.entity_id=l.entity_id AND j.journal_entry_id=l.journal_entry_id AND j.status='POSTED' WHERE l.tenant_id=p_tenant AND l.entity_id=p_entity AND l.dimensions->>'fixed_asset_register_evidence_id'=p_asset::text AND l.account_code=asset.asset_account_code AND j.journal_date<=p_date;
 SELECT coalesce(sum(l.credit_amount-l.debit_amount),0) INTO posted_depreciation FROM ledger_line l JOIN journal_entry j ON j.tenant_id=l.tenant_id AND j.entity_id=l.entity_id AND j.journal_entry_id=l.journal_entry_id AND j.status='POSTED' WHERE l.tenant_id=p_tenant AND l.entity_id=p_entity AND l.dimensions->>'fixed_asset_register_evidence_id'=p_asset::text AND l.account_code=asset.accumulated_depreciation_account_code AND j.journal_date<=p_date;
 WITH accounts AS (SELECT DISTINCT accumulated_impairment_account_code account_code FROM fixed_asset_impairment_assessment_evidence WHERE tenant_id=p_tenant AND entity_id=p_entity AND fixed_asset_register_evidence_id=p_asset AND assessment_date<p_date),balances AS (
   SELECT a.account_code,coalesce(sum(l.credit_amount-l.debit_amount),0)::numeric(20,4) amount FROM accounts a LEFT JOIN (SELECT ll.* FROM ledger_line ll JOIN journal_entry j ON j.tenant_id=ll.tenant_id AND j.entity_id=ll.entity_id AND j.journal_entry_id=ll.journal_entry_id AND j.status='POSTED' WHERE ll.tenant_id=p_tenant AND ll.entity_id=p_entity AND ll.dimensions->>'fixed_asset_register_evidence_id'=p_asset::text AND j.journal_date<=p_date) l ON l.account_code=a.account_code GROUP BY a.account_code
 ) SELECT coalesce(jsonb_agg(jsonb_build_object('account_code',account_code,'amount',to_char(amount,'FM999999999999990.0000')) ORDER BY account_code),'[]'::jsonb),coalesce(sum(amount),0) INTO impairment_rows,posted_impairment FROM balances;
 impairment_date_conflict:=EXISTS(SELECT 1 FROM fixed_asset_impairment_assessment_evidence WHERE tenant_id=p_tenant AND entity_id=p_entity AND fixed_asset_register_evidence_id=p_asset AND assessment_date>=p_date);
 IF asset.asset_account_code IN(SELECT accumulated_impairment_account_code FROM fixed_asset_impairment_assessment_evidence WHERE tenant_id=p_tenant AND entity_id=p_entity AND fixed_asset_register_evidence_id=p_asset)
 OR asset.accumulated_depreciation_account_code IN(SELECT accumulated_impairment_account_code FROM fixed_asset_impairment_assessment_evidence WHERE tenant_id=p_tenant AND entity_id=p_entity AND fixed_asset_register_evidence_id=p_asset) THEN impairment_evidence_valid:=false;END IF;
 IF EXISTS(SELECT 1 FROM ledger_line l JOIN journal_entry j ON j.tenant_id=l.tenant_id AND j.entity_id=l.entity_id AND j.journal_entry_id=l.journal_entry_id AND j.status='POSTED' LEFT JOIN fixed_asset_impairment_assessment_evidence i ON i.tenant_id=l.tenant_id AND i.entity_id=l.entity_id AND i.fixed_asset_impairment_assessment_evidence_id::text=l.dimensions->>'fixed_asset_impairment_assessment_evidence_id' WHERE l.tenant_id=p_tenant AND l.entity_id=p_entity AND l.dimensions->>'fixed_asset_register_evidence_id'=p_asset::text AND j.journal_date<=p_date AND l.account_code IN(SELECT DISTINCT accumulated_impairment_account_code FROM fixed_asset_impairment_assessment_evidence WHERE tenant_id=p_tenant AND entity_id=p_entity AND fixed_asset_register_evidence_id=p_asset) AND (i.fixed_asset_impairment_assessment_evidence_id IS NULL OR i.fixed_asset_register_evidence_id<>p_asset OR i.accumulated_impairment_account_code<>l.account_code OR j.journal_date<i.assessment_date OR l.currency<>asset.currency OR i.currency<>asset.currency)) THEN impairment_evidence_valid:=false;END IF;
 IF EXISTS(SELECT 1 FROM ledger_line l JOIN journal_entry j ON j.tenant_id=l.tenant_id AND j.entity_id=l.entity_id AND j.journal_entry_id=l.journal_entry_id AND j.status='POSTED' JOIN fixed_asset_impairment_assessment_evidence i ON i.tenant_id=l.tenant_id AND i.entity_id=l.entity_id AND i.fixed_asset_impairment_assessment_evidence_id::text=l.dimensions->>'fixed_asset_impairment_assessment_evidence_id' WHERE l.tenant_id=p_tenant AND l.entity_id=p_entity AND l.dimensions->>'fixed_asset_register_evidence_id'=p_asset::text AND l.account_code=i.accumulated_impairment_account_code AND j.journal_date<=p_date GROUP BY i.fixed_asset_impairment_assessment_evidence_id,i.impairment_loss HAVING sum(l.credit_amount-l.debit_amount)<>i.impairment_loss) THEN impairment_evidence_valid:=false;END IF;
 IF EXISTS(SELECT 1 FROM ledger_line l LEFT JOIN fixed_asset_impairment_assessment_evidence i ON i.tenant_id=l.tenant_id AND i.entity_id=l.entity_id AND i.fixed_asset_impairment_assessment_evidence_id::text=l.dimensions->>'fixed_asset_impairment_assessment_evidence_id' WHERE l.tenant_id=p_tenant AND l.entity_id=p_entity AND l.journal_entry_id IN(SELECT h.journal_entry_id FROM ledger_line h JOIN journal_entry j ON j.tenant_id=h.tenant_id AND j.entity_id=h.entity_id AND j.journal_entry_id=h.journal_entry_id AND j.status='POSTED' WHERE h.tenant_id=p_tenant AND h.entity_id=p_entity AND h.dimensions->>'fixed_asset_register_evidence_id'=p_asset::text AND h.account_code IN(SELECT DISTINCT accumulated_impairment_account_code FROM fixed_asset_impairment_assessment_evidence WHERE tenant_id=p_tenant AND entity_id=p_entity AND fixed_asset_register_evidence_id=p_asset) AND j.journal_date<=p_date) AND (i.fixed_asset_impairment_assessment_evidence_id IS NULL OR i.fixed_asset_register_evidence_id<>p_asset OR l.dimensions->>'fixed_asset_register_evidence_id' IS DISTINCT FROM p_asset::text OR l.currency<>i.currency OR l.account_code NOT IN(i.impairment_expense_account_code,i.accumulated_impairment_account_code) OR (l.account_code=i.impairment_expense_account_code AND l.credit_amount<>0) OR (l.account_code=i.accumulated_impairment_account_code AND l.debit_amount<>0))) THEN impairment_evidence_valid:=false;END IF;
 IF EXISTS(SELECT 1 FROM ledger_line l JOIN journal_entry j ON j.tenant_id=l.tenant_id AND j.entity_id=l.entity_id AND j.journal_entry_id=l.journal_entry_id AND j.status='POSTED' JOIN fixed_asset_impairment_assessment_evidence i ON i.tenant_id=l.tenant_id AND i.entity_id=l.entity_id AND i.fixed_asset_impairment_assessment_evidence_id::text=l.dimensions->>'fixed_asset_impairment_assessment_evidence_id' WHERE l.tenant_id=p_tenant AND l.entity_id=p_entity AND l.dimensions->>'fixed_asset_register_evidence_id'=p_asset::text AND j.journal_date<=p_date GROUP BY i.fixed_asset_impairment_assessment_evidence_id,i.impairment_loss,i.impairment_expense_account_code HAVING coalesce(sum(l.debit_amount-l.credit_amount) FILTER(WHERE l.account_code=i.impairment_expense_account_code),0)<>i.impairment_loss) THEN impairment_evidence_valid:=false;END IF;
 disposal_recorded:=EXISTS(SELECT 1 FROM fixed_asset_disposal_evidence WHERE tenant_id=p_tenant AND entity_id=p_entity AND fixed_asset_register_evidence_id=p_asset) OR EXISTS(SELECT 1 FROM fixed_asset_disposal_posting WHERE tenant_id=p_tenant AND entity_id=p_entity AND fixed_asset_register_evidence_id=p_asset);
 later_movement:=EXISTS(SELECT 1 FROM ledger_line l JOIN journal_entry j ON j.tenant_id=l.tenant_id AND j.entity_id=l.entity_id AND j.journal_entry_id=l.journal_entry_id AND j.status='POSTED' WHERE l.tenant_id=p_tenant AND l.entity_id=p_entity AND l.dimensions->>'fixed_asset_register_evidence_id'=p_asset::text AND j.journal_date>p_date);
 carrying:=asset.cost_basis-posted_depreciation-posted_impairment;
 readiness:=CASE WHEN asset.status<>'ACTIVE' THEN 'BLOCKED_ASSET_INACTIVE' WHEN period.status<>'OPEN' THEN 'BLOCKED_PERIOD_NOT_OPEN' WHEN p_date IS NULL OR p_date NOT BETWEEN period.starts_on AND period.ends_on OR p_date<asset.placed_in_service_date THEN 'BLOCKED_DATE_OUTSIDE_PERIOD' WHEN NOT acquisition_posted THEN 'BLOCKED_ACQUISITION_NOT_POSTED' WHEN disposal_recorded THEN 'BLOCKED_ASSET_DISPOSED' WHEN later_movement THEN 'BLOCKED_LATER_ASSET_MOVEMENT' WHEN impairment_date_conflict THEN 'BLOCKED_IMPAIRMENT_DATE_CONFLICT' WHEN NOT impairment_evidence_valid OR posted_cost<>asset.cost_basis OR posted_depreciation<0 OR posted_impairment<0 OR carrying<0 THEN 'BLOCKED_LEDGER_RECONCILIATION' ELSE 'READY' END;
 RETURN jsonb_build_object('schema_version','FIXED_ASSET_DISPOSAL_SNAPSHOT_V1','tenant_id',p_tenant,'entity_id',p_entity,'asset_id',p_asset,'asset_tag',asset.asset_tag,'asset_status',asset.status,'register_evidence_hash',asset.register_evidence_hash,'currency',asset.currency,'member_trace',asset.member_trace,'placed_in_service_date',asset.placed_in_service_date,'period',jsonb_build_object('period_id',period.period_id,'period_code',period.period_code,'starts_on',period.starts_on,'ends_on',period.ends_on,'status',period.status),'disposal_date',p_date,'cost_basis',to_char(asset.cost_basis,'FM999999999999990.0000'),'posted_cost_balance',to_char(posted_cost,'FM999999999999990.0000'),'accumulated_depreciation',to_char(posted_depreciation,'FM999999999999990.0000'),'impairment_reversals',impairment_rows,'accumulated_impairment',to_char(posted_impairment,'FM999999999999990.0000'),'carrying_value',to_char(carrying,'FM999999999999990.0000'),'asset_account_code',asset.asset_account_code,'accumulated_depreciation_account_code',asset.accumulated_depreciation_account_code,'acquisition_posted',acquisition_posted,'disposal_recorded',disposal_recorded,'later_asset_movement',later_movement,'impairment_date_conflict',impairment_date_conflict,'impairment_evidence_valid',impairment_evidence_valid,'readiness_status',readiness);
END;$$;
REVOKE EXECUTE ON FUNCTION refs_fixed_asset_disposal_snapshot(uuid,uuid,uuid,uuid,date) FROM PUBLIC,refs_app;

CREATE FUNCTION refs_asset_disposal_journal_snapshot(p_tenant uuid,p_entity uuid,p_journal uuid) RETURNS text
LANGUAGE sql STABLE SET search_path=pg_catalog,public,pg_temp AS $$
 SELECT refs_jsonb_hash(jsonb_build_object('period_id',j.period_id,'journal_date',j.journal_date,'currency',j.currency,'journal_type',j.journal_type,
  'lines',(SELECT jsonb_agg(jsonb_build_object('line_no',l.line_no,'account_code',l.account_code,'debit_amount',l.debit_amount,'credit_amount',l.credit_amount,'member_ref',l.member_ref,'description',l.description,'dimensions',l.dimensions) ORDER BY l.line_no) FROM journal_line l WHERE l.tenant_id=j.tenant_id AND l.entity_id=j.entity_id AND l.journal_entry_id=j.journal_entry_id)))
 FROM journal_entry j WHERE j.tenant_id=p_tenant AND j.entity_id=p_entity AND j.journal_entry_id=p_journal
$$;
REVOKE EXECUTE ON FUNCTION refs_asset_disposal_journal_snapshot(uuid,uuid,uuid) FROM PUBLIC,refs_app;

CREATE FUNCTION refs_read_fixed_asset_disposal_options(p_tenant uuid,p_entity uuid,p_asset uuid,p_period uuid,p_date date) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE snapshot jsonb;sources jsonb;proceeds_accounts jsonb;members jsonb;gain_accounts jsonb;pending jsonb;more_pending boolean;has_zero_source boolean;has_compatible_proceeds boolean;readiness text;
BEGIN
 PERFORM refs_assert_scope(p_tenant,p_entity,'FIXED_ASSET.DISPOSAL.DRAFT');PERFORM refs_assert_scope(p_tenant,p_entity,'GL.JE.VIEW');
 snapshot:=refs_fixed_asset_disposal_snapshot(p_tenant,p_entity,p_asset,p_period,p_date);
 SELECT coalesce(jsonb_agg(jsonb_build_object('source_document_id',source_document_id,'source_document_version',version,'source_payload_hash',payload_hash,'source_module',source_module,'document_type',document_type,'document_no',document_no,'business_date',business_date,'accounting_date',accounting_date,'gross_amount',to_char(gross_amount,'FM999999999999990.0000'),'status',status) ORDER BY business_date DESC,source_document_id),'[]'::jsonb) INTO sources FROM source_document WHERE tenant_id=p_tenant AND entity_id=p_entity AND currency=snapshot->>'currency' AND version>0 AND gross_amount>=0 AND business_date<=p_date AND accounting_date<=p_date AND source_document_id<>(SELECT source_document_id FROM fixed_asset_register_evidence WHERE tenant_id=p_tenant AND entity_id=p_entity AND fixed_asset_register_evidence_id=p_asset) AND status IN('READY_FOR_DRAFT','DRAFT_CREATED','PENDING_JE_REVIEW','PENDING_JE_APPROVAL','APPROVED','POSTED');
 SELECT coalesce(jsonb_agg(jsonb_build_object('account_code',account_code,'account_name',account_name,'required_member_type',required_member_type) ORDER BY account_code),'[]'::jsonb) INTO proceeds_accounts FROM account_master WHERE tenant_id=p_tenant AND entity_id=p_entity AND active AND requires_member AND required_member_type IN('BANK','CUSTOMER_OR_AFFILIATE');
 SELECT coalesce(jsonb_agg(jsonb_build_object('member_ref',member_ref,'member_type',member_type,'display_name',display_name) ORDER BY member_type,member_ref),'[]'::jsonb) INTO members FROM member_master WHERE tenant_id=p_tenant AND entity_id=p_entity AND active AND member_type IN('BANK','CUSTOMER','AFFILIATE');
 has_zero_source:=EXISTS(SELECT 1 FROM jsonb_array_elements(sources) source_row WHERE (source_row->>'gross_amount')::numeric=0);
 has_compatible_proceeds:=EXISTS(SELECT 1 FROM jsonb_array_elements(proceeds_accounts) account_row CROSS JOIN jsonb_array_elements(members) member_row WHERE member_row->>'member_type'=account_row->>'required_member_type' OR account_row->>'required_member_type'='CUSTOMER_OR_AFFILIATE' AND member_row->>'member_type' IN('CUSTOMER','AFFILIATE'));
 SELECT coalesce(jsonb_agg(jsonb_build_object('account_code',account_code,'account_name',account_name) ORDER BY account_code),'[]'::jsonb) INTO gain_accounts FROM account_master WHERE tenant_id=p_tenant AND entity_id=p_entity AND active AND NOT requires_member AND account_code NOT IN(snapshot->>'asset_account_code',snapshot->>'accumulated_depreciation_account_code') AND account_code NOT IN(SELECT value->>'account_code' FROM jsonb_array_elements(snapshot->'impairment_reversals') value);
 SELECT coalesce(jsonb_agg(to_jsonb(x) ORDER BY x.journal_entry_id),'[]'::jsonb) INTO pending FROM (SELECT j.journal_entry_id,j.period_id,j.journal_number,j.journal_date,j.status,j.revision FROM fixed_asset_disposal_source_binding b JOIN journal_entry j ON j.tenant_id=b.tenant_id AND j.entity_id=b.entity_id AND j.journal_entry_id=b.journal_entry_id WHERE b.tenant_id=p_tenant AND b.entity_id=p_entity AND b.fixed_asset_register_evidence_id=p_asset AND j.status IN('DRAFT','PENDING_REVIEW','PENDING_APPROVAL','APPROVED') ORDER BY j.journal_entry_id LIMIT 21) x;
 more_pending:=jsonb_array_length(pending)>20;IF more_pending THEN SELECT jsonb_agg(value ORDER BY ordinal) INTO pending FROM jsonb_array_elements(pending) WITH ORDINALITY x(value,ordinal) WHERE ordinal<=20;END IF;
 readiness:=snapshot->>'readiness_status';IF readiness='READY' AND jsonb_array_length(pending)>0 THEN readiness:='BLOCKED_PENDING_DISPOSAL';ELSIF readiness='READY' AND jsonb_array_length(sources)=0 THEN readiness:='BLOCKED_SOURCE_UNAVAILABLE';ELSIF readiness='READY' AND NOT has_zero_source AND NOT has_compatible_proceeds THEN readiness:='BLOCKED_PROCEEDS_ACCOUNT_UNAVAILABLE';ELSIF readiness='READY' AND jsonb_array_length(gain_accounts)=0 THEN readiness:='BLOCKED_GAIN_LOSS_ACCOUNT_UNAVAILABLE';END IF;
 RETURN jsonb_build_object('schema_version','FIXED_ASSET_DISPOSAL_OPTIONS_V1','tenant_id',p_tenant,'entity_id',p_entity,'asset_id',p_asset,'options_hash',refs_jsonb_hash(snapshot),'snapshot',snapshot,'sources',sources,'proceeds_accounts',proceeds_accounts,'members',members,'gain_loss_accounts',gain_accounts,'pending_journals',pending,'more_pending_journals',more_pending,'readiness_status',readiness,'requires_command_validation',true);
END;$$;

CREATE FUNCTION refs_create_fixed_asset_disposal_hash(p_tenant uuid,p_entity uuid,p_asset uuid,p_period uuid,p_number text,p_date date,p_source uuid,p_source_version bigint,p_source_hash text,p_proceeds_account text,p_proceeds_member text,p_gain_account text,p_options_hash text,p_reason text) RETURNS text
LANGUAGE sql IMMUTABLE SET search_path=pg_catalog,public,pg_temp AS $$
 SELECT refs_jsonb_hash(jsonb_build_object('schema_version','FIXED_ASSET_DISPOSAL_DRAFT_V1','tenant_id',p_tenant,'entity_id',p_entity,'asset_id',p_asset,'period_id',p_period,'journal_number',btrim(p_number),'disposal_date',p_date,'source_document_id',p_source,'expected_source_version',p_source_version,'expected_source_hash',p_source_hash,'proceeds_account_code',p_proceeds_account,'proceeds_member_ref',p_proceeds_member,'gain_loss_account_code',p_gain_account,'expected_options_hash',p_options_hash,'reason',btrim(p_reason)))
$$;

CREATE FUNCTION refs_create_fixed_asset_disposal(p_tenant uuid,p_entity uuid,p_asset uuid,p_period uuid,p_number text,p_date date,p_source uuid,p_source_version bigint,p_source_hash text,p_proceeds_account text,p_proceeds_member text,p_gain_account text,p_options_hash text,p_reason text,p_key text,p_hash text) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE actor text:=refs_current_actor();idem idempotency_receipt;snapshot jsonb;asset fixed_asset_register_evidence;source source_document;proceeds_master account_master;member member_master;gain_master account_master;binding uuid:=gen_random_uuid();journal_id uuid;link_id uuid:=gen_random_uuid();attachments uuid[]:=ARRAY[]::uuid[];dims jsonb;lines jsonb:='[]'::jsonb;line_no integer:=0;imp jsonb;gain_loss numeric(20,4);inner_hash text;result jsonb;payload jsonb;
BEGIN
 PERFORM refs_assert_scope(p_tenant,p_entity,'FIXED_ASSET.DISPOSAL.DRAFT');PERFORM refs_assert_scope(p_tenant,p_entity,'GL.JE.CREATE');
 IF actor IS NULL OR p_date IS NULL OR p_source_version IS NULL OR p_source_version<1 OR length(btrim(coalesce(p_number,''))) NOT BETWEEN 1 AND 100 OR length(btrim(coalesce(p_reason,''))) NOT BETWEEN 8 AND 2000 OR p_source_hash!~'^sha256:[a-f0-9]{64}$' OR p_options_hash!~'^sha256:[a-f0-9]{64}$' OR length(btrim(coalesce(p_gain_account,''))) NOT BETWEEN 1 AND 128 OR p_hash IS DISTINCT FROM refs_create_fixed_asset_disposal_hash(p_tenant,p_entity,p_asset,p_period,p_number,p_date,p_source,p_source_version,p_source_hash,p_proceeds_account,p_proceeds_member,p_gain_account,p_options_hash,p_reason) THEN RAISE EXCEPTION 'Invalid disposal command' USING ERRCODE='22023';END IF;
 INSERT INTO idempotency_receipt(tenant_id,operation_scope,idempotency_key,request_hash,status,actor_id) VALUES(p_tenant,'FIXED_ASSET_DISPOSAL_DRAFT:'||p_entity,p_key,p_hash,'IN_PROGRESS',actor) ON CONFLICT(tenant_id,operation_scope,idempotency_key) DO NOTHING;
 SELECT * INTO idem FROM idempotency_receipt WHERE tenant_id=p_tenant AND operation_scope='FIXED_ASSET_DISPOSAL_DRAFT:'||p_entity AND idempotency_key=p_key FOR UPDATE;
 IF idem.actor_id IS DISTINCT FROM actor OR idem.request_hash IS DISTINCT FROM p_hash THEN RAISE EXCEPTION 'Disposal idempotency conflict' USING ERRCODE='23505';END IF;IF idem.status='SUCCEEDED' THEN RETURN idem.response_body||jsonb_build_object('idempotent',true);END IF;
 SELECT * INTO asset FROM fixed_asset_register_evidence WHERE tenant_id=p_tenant AND entity_id=p_entity AND fixed_asset_register_evidence_id=p_asset FOR UPDATE;IF NOT FOUND THEN RAISE EXCEPTION 'Scoped disposal asset missing' USING ERRCODE='P0002';END IF;
 IF EXISTS(SELECT 1 FROM fixed_asset_disposal_source_binding b JOIN journal_entry j ON j.tenant_id=b.tenant_id AND j.entity_id=b.entity_id AND j.journal_entry_id=b.journal_entry_id WHERE b.tenant_id=p_tenant AND b.entity_id=p_entity AND b.fixed_asset_register_evidence_id=p_asset AND j.status IN('DRAFT','PENDING_REVIEW','PENDING_APPROVAL','APPROVED')) THEN RAISE EXCEPTION 'A disposal journal is already in progress for this asset' USING ERRCODE='23505';END IF;
 snapshot:=refs_fixed_asset_disposal_snapshot(p_tenant,p_entity,p_asset,p_period,p_date);IF snapshot->>'readiness_status'<>'READY' THEN RAISE EXCEPTION 'Asset disposal is not ready' USING ERRCODE='23514';END IF;IF refs_jsonb_hash(snapshot) IS DISTINCT FROM p_options_hash THEN RAISE EXCEPTION 'Disposal options changed' USING ERRCODE='40001';END IF;
 SELECT * INTO source FROM source_document WHERE tenant_id=p_tenant AND entity_id=p_entity AND source_document_id=p_source FOR SHARE;
 IF NOT FOUND OR source.version<>p_source_version OR source.payload_hash IS DISTINCT FROM p_source_hash OR source.currency<>asset.currency OR source.gross_amount<0 OR source.business_date>p_date OR source.accounting_date>p_date OR source.source_document_id=asset.source_document_id OR source.status NOT IN('READY_FOR_DRAFT','DRAFT_CREATED','PENDING_JE_REVIEW','PENDING_JE_APPROVAL','APPROVED','POSTED') THEN RAISE EXCEPTION 'Disposal source changed or is unavailable' USING ERRCODE='40001';END IF;
 SELECT * INTO gain_master FROM account_master WHERE tenant_id=p_tenant AND entity_id=p_entity AND account_code=p_gain_account AND active AND NOT requires_member FOR SHARE;IF NOT FOUND OR p_gain_account IN(asset.asset_account_code,asset.accumulated_depreciation_account_code) OR p_gain_account IN(SELECT value->>'account_code' FROM jsonb_array_elements(snapshot->'impairment_reversals') value) THEN RAISE EXCEPTION 'Disposal gain or loss account is unavailable' USING ERRCODE='23514';END IF;
 IF source.gross_amount=0 THEN IF p_proceeds_account IS NOT NULL OR p_proceeds_member IS NOT NULL THEN RAISE EXCEPTION 'Zero-proceeds disposal cannot include a proceeds account or member' USING ERRCODE='22023';END IF;
 ELSE SELECT * INTO proceeds_master FROM account_master WHERE tenant_id=p_tenant AND entity_id=p_entity AND account_code=p_proceeds_account AND active AND requires_member AND required_member_type IN('BANK','CUSTOMER_OR_AFFILIATE') FOR SHARE;IF NOT FOUND THEN RAISE EXCEPTION 'Disposal proceeds account is unavailable' USING ERRCODE='23514';END IF;SELECT * INTO member FROM member_master WHERE tenant_id=p_tenant AND entity_id=p_entity AND member_ref=p_proceeds_member AND active FOR SHARE;IF NOT FOUND OR NOT(member.member_type=proceeds_master.required_member_type OR proceeds_master.required_member_type='CUSTOMER_OR_AFFILIATE' AND member.member_type IN('CUSTOMER','AFFILIATE')) THEN RAISE EXCEPTION 'Disposal proceeds member is unavailable or incompatible' USING ERRCODE='23514';END IF;END IF;
 SELECT coalesce(array_agg(DISTINCT a.attachment_id ORDER BY a.attachment_id),ARRAY[]::uuid[]) INTO attachments FROM source_link sl JOIN attachment a ON a.tenant_id=sl.tenant_id AND a.entity_id=sl.entity_id AND a.attachment_id=sl.attachment_id AND a.finalization_status='VERIFIED_CLEAN' AND a.scan_status='CLEAN' WHERE sl.tenant_id=p_tenant AND sl.entity_id=p_entity AND sl.source_document_id=p_source AND sl.link_type='SOURCE_ATTACHMENT';
 dims:=coalesce(asset.member_trace,'{}'::jsonb)||jsonb_build_object('fixed_asset_register_evidence_id',p_asset,'fixed_asset_disposal_draft_binding_id',binding,'accounting_period_id',p_period);
 IF (snapshot->>'accumulated_depreciation')::numeric>0 THEN line_no:=line_no+1;lines:=lines||jsonb_build_array(jsonb_build_object('line_no',line_no,'account_code',asset.accumulated_depreciation_account_code,'debit_amount',(snapshot->>'accumulated_depreciation')::numeric,'credit_amount',0,'member_ref',NULL,'description','Reverse accumulated depreciation on disposal','dimensions',dims));END IF;
 FOR imp IN SELECT value FROM jsonb_array_elements(snapshot->'impairment_reversals') value LOOP IF (imp->>'amount')::numeric>0 THEN line_no:=line_no+1;lines:=lines||jsonb_build_array(jsonb_build_object('line_no',line_no,'account_code',imp->>'account_code','debit_amount',(imp->>'amount')::numeric,'credit_amount',0,'member_ref',NULL,'description','Reverse accumulated impairment on disposal','dimensions',dims));END IF;END LOOP;
 IF source.gross_amount>0 THEN line_no:=line_no+1;lines:=lines||jsonb_build_array(jsonb_build_object('line_no',line_no,'account_code',p_proceeds_account,'debit_amount',source.gross_amount,'credit_amount',0,'member_ref',p_proceeds_member,'description','Asset disposal proceeds','dimensions',dims));END IF;
 line_no:=line_no+1;lines:=lines||jsonb_build_array(jsonb_build_object('line_no',line_no,'account_code',asset.asset_account_code,'debit_amount',0,'credit_amount',asset.cost_basis,'member_ref',NULL,'description','Derecognize disposed asset cost','dimensions',dims));
 gain_loss:=source.gross_amount-(snapshot->>'carrying_value')::numeric;IF gain_loss<>0 THEN line_no:=line_no+1;lines:=lines||jsonb_build_array(jsonb_build_object('line_no',line_no,'account_code',p_gain_account,'debit_amount',greatest(-gain_loss,0),'credit_amount',greatest(gain_loss,0),'member_ref',NULL,'description',CASE WHEN gain_loss>0 THEN 'Gain on asset disposal' ELSE 'Loss on asset disposal' END,'dimensions',dims));END IF;
 inner_hash:=refs_create_manual_journal_hash(p_tenant,p_entity,p_period,p_number,p_date,asset.currency,btrim(p_reason),lines,attachments);result:=refs_create_manual_journal(p_tenant,p_entity,p_period,p_number,p_date,asset.currency,btrim(p_reason),lines,attachments,'asset-disposal:'||binding,inner_hash);journal_id:=(result->>'journal_entry_id')::uuid;
 INSERT INTO source_link(source_link_id,tenant_id,entity_id,link_type,source_document_id,journal_entry_id,created_by) VALUES(link_id,p_tenant,p_entity,'SOURCE_TO_JE',p_source,journal_id,actor);
 INSERT INTO fixed_asset_disposal_source_binding(binding_id,tenant_id,entity_id,fixed_asset_register_evidence_id,journal_entry_id,source_document_id,source_document_version,source_payload_hash,source_link_id,created_by,reason,binding_hash) VALUES(binding,p_tenant,p_entity,p_asset,journal_id,p_source,source.version,source.payload_hash,link_id,actor,btrim(p_reason),p_hash);
 UPDATE journal_entry SET revision=revision+1 WHERE tenant_id=p_tenant AND entity_id=p_entity AND journal_entry_id=journal_id;
 INSERT INTO fixed_asset_disposal_draft_binding(binding_id,tenant_id,entity_id,fixed_asset_register_evidence_id,accounting_period_id,journal_entry_id,source_document_id,source_document_version,source_payload_hash,register_evidence_hash,disposal_snapshot,disposal_snapshot_hash,proceeds,proceeds_account_code,proceeds_member_ref,gain_loss_account_code,journal_snapshot_hash,created_by) VALUES(binding,p_tenant,p_entity,p_asset,p_period,journal_id,p_source,source.version,source.payload_hash,asset.register_evidence_hash,snapshot,p_options_hash,source.gross_amount,p_proceeds_account,p_proceeds_member,p_gain_account,refs_asset_disposal_journal_snapshot(p_tenant,p_entity,journal_id),actor);
 payload:=jsonb_build_object('schema_version','FIXED_ASSET_DISPOSAL_DRAFT_V1','binding_id',binding,'journal_entry_id',journal_id,'asset_id',p_asset,'period_id',p_period,'source_document_id',p_source,'source_document_version',source.version,'source_payload_hash',source.payload_hash,'source_link_id',link_id,'register_evidence_hash',asset.register_evidence_hash,'options_hash',p_options_hash,'proceeds',to_char(source.gross_amount,'FM999999999999990.0000'),'accumulated_depreciation',snapshot->>'accumulated_depreciation','accumulated_impairment',snapshot->>'accumulated_impairment','carrying_value',snapshot->>'carrying_value','gain_or_loss',to_char(gain_loss,'FM999999999999990.0000'),'status','DRAFT','revision',1,'idempotent',false);
 INSERT INTO audit_event(tenant_id,entity_id,event_type,object_type,object_id,action,actor_id,actor_type,permission_used,request_id,correlation_id,idempotency_key,after_hash,reason,metadata) VALUES(p_tenant,p_entity,'FIXED_ASSET_DISPOSAL_DRAFT_CREATED','JOURNAL_ENTRY',journal_id,'CREATE',actor,'USER','FIXED_ASSET.DISPOSAL.DRAFT',p_key,p_key,p_key,p_hash,btrim(p_reason),payload);
 INSERT INTO outbox_event(tenant_id,entity_id,aggregate_type,aggregate_id,event_type,payload,payload_hash) VALUES(p_tenant,p_entity,'JOURNAL_ENTRY',journal_id,'FIXED_ASSET_DISPOSAL_DRAFT_CREATED',payload,refs_jsonb_hash(payload));
 UPDATE idempotency_receipt SET status='SUCCEEDED',response_status=201,response_body=payload,completed_at=clock_timestamp() WHERE idempotency_receipt_id=idem.idempotency_receipt_id;RETURN payload;
END;$$;

CREATE FUNCTION refs_guard_native_fixed_asset_disposal_post() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE binding fixed_asset_disposal_draft_binding;fresh jsonb;source source_document;account account_master;member member_master;
BEGIN
 SELECT * INTO binding FROM fixed_asset_disposal_draft_binding WHERE tenant_id=NEW.tenant_id AND entity_id=NEW.entity_id AND journal_entry_id=NEW.journal_entry_id;
 IF NOT FOUND THEN RETURN NEW;END IF;
 fresh:=refs_fixed_asset_disposal_snapshot(NEW.tenant_id,NEW.entity_id,binding.fixed_asset_register_evidence_id,binding.accounting_period_id,NEW.journal_date);
 IF fresh->>'readiness_status'<>'READY' OR binding.disposal_snapshot IS DISTINCT FROM fresh OR binding.disposal_snapshot_hash IS DISTINCT FROM refs_jsonb_hash(fresh) OR binding.register_evidence_hash IS DISTINCT FROM fresh->>'register_evidence_hash' THEN RAISE EXCEPTION 'Disposal balances or asset evidence changed before Post' USING ERRCODE='23514';END IF;
 SELECT * INTO source FROM source_document WHERE tenant_id=NEW.tenant_id AND entity_id=NEW.entity_id AND source_document_id=binding.source_document_id FOR SHARE;IF NOT FOUND OR source.version<>binding.source_document_version OR source.payload_hash<>binding.source_payload_hash OR source.currency<>NEW.currency OR source.gross_amount<>binding.proceeds OR source.business_date>NEW.journal_date OR source.accounting_date>NEW.journal_date OR source.status NOT IN('READY_FOR_DRAFT','DRAFT_CREATED','PENDING_JE_REVIEW','PENDING_JE_APPROVAL','APPROVED','POSTED') THEN RAISE EXCEPTION 'Disposal source changed before Post' USING ERRCODE='23514';END IF;
 SELECT * INTO account FROM account_master WHERE tenant_id=NEW.tenant_id AND entity_id=NEW.entity_id AND account_code=binding.gain_loss_account_code AND active AND NOT requires_member FOR SHARE;IF NOT FOUND THEN RAISE EXCEPTION 'Disposal gain or loss account changed before Post' USING ERRCODE='23514';END IF;
 IF binding.proceeds>0 THEN SELECT * INTO account FROM account_master WHERE tenant_id=NEW.tenant_id AND entity_id=NEW.entity_id AND account_code=binding.proceeds_account_code AND active AND requires_member AND required_member_type IN('BANK','CUSTOMER_OR_AFFILIATE') FOR SHARE;SELECT * INTO member FROM member_master WHERE tenant_id=NEW.tenant_id AND entity_id=NEW.entity_id AND member_ref=binding.proceeds_member_ref AND active FOR SHARE;IF account.account_code IS NULL OR member.member_ref IS NULL OR NOT(member.member_type=account.required_member_type OR account.required_member_type='CUSTOMER_OR_AFFILIATE' AND member.member_type IN('CUSTOMER','AFFILIATE')) THEN RAISE EXCEPTION 'Disposal proceeds account or member changed before Post' USING ERRCODE='23514';END IF;END IF;
 IF binding.journal_snapshot_hash IS DISTINCT FROM refs_asset_disposal_journal_snapshot(NEW.tenant_id,NEW.entity_id,NEW.journal_entry_id) THEN RAISE EXCEPTION 'Disposal financial lines changed; create a corrected evidence-bound Draft' USING ERRCODE='23514';END IF;
 IF NOT EXISTS(SELECT 1 FROM fixed_asset_disposal_source_binding b JOIN source_link sl ON sl.source_link_id=b.source_link_id AND sl.tenant_id=b.tenant_id AND sl.entity_id=b.entity_id AND sl.source_document_id=b.source_document_id AND sl.journal_entry_id=b.journal_entry_id AND sl.link_type='SOURCE_TO_JE' WHERE b.binding_id=binding.binding_id AND b.tenant_id=NEW.tenant_id AND b.entity_id=NEW.entity_id AND b.journal_entry_id=NEW.journal_entry_id AND b.source_document_id=binding.source_document_id AND b.source_document_version=binding.source_document_version AND b.source_payload_hash=binding.source_payload_hash) THEN RAISE EXCEPTION 'Disposal source lineage changed before Post' USING ERRCODE='23514';END IF;
 RETURN NEW;
END;$$;
CREATE TRIGGER fixed_asset_disposal_draft_post_guard BEFORE UPDATE OF status ON journal_entry FOR EACH ROW WHEN(NEW.status='POSTED' AND OLD.status<>'POSTED') EXECUTE FUNCTION refs_guard_native_fixed_asset_disposal_post();
REVOKE EXECUTE ON FUNCTION refs_guard_native_fixed_asset_disposal_post() FROM PUBLIC,refs_app;

REVOKE ALL ON FUNCTION refs_read_fixed_asset_disposal_options(uuid,uuid,uuid,uuid,date),refs_create_fixed_asset_disposal_hash(uuid,uuid,uuid,uuid,text,date,uuid,bigint,text,text,text,text,text,text),refs_create_fixed_asset_disposal(uuid,uuid,uuid,uuid,text,date,uuid,bigint,text,text,text,text,text,text,text,text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION refs_read_fixed_asset_disposal_options(uuid,uuid,uuid,uuid,date),refs_create_fixed_asset_disposal_hash(uuid,uuid,uuid,uuid,text,date,uuid,bigint,text,text,text,text,text,text),refs_create_fixed_asset_disposal(uuid,uuid,uuid,uuid,text,date,uuid,bigint,text,text,text,text,text,text,text,text) TO refs_app;

COMMIT;
