BEGIN;

INSERT INTO permission_catalog(permission_code,domain,risk_class,sod_class) VALUES
 ('REPORT.SAVED_VIEW.VIEW','REPORTING','LOW','READ'),
 ('REPORT.SAVED_VIEW.CREATE','REPORTING','LOW','REPORT_SAVED_VIEW_MAINTAIN'),
 ('REPORT.SAVED_VIEW.UPDATE','REPORTING','LOW','REPORT_SAVED_VIEW_MAINTAIN'),
 ('REPORT.SAVED_VIEW.SHARE','REPORTING','MEDIUM','REPORT_SAVED_VIEW_SHARE')
ON CONFLICT(permission_code) DO UPDATE SET active=true,domain=EXCLUDED.domain,risk_class=EXCLUDED.risk_class,sod_class=EXCLUDED.sod_class,version=permission_catalog.version+1,effective_to=NULL;
INSERT INTO runtime_human_permission_authority(permission_code,authority_class) VALUES
 ('REPORT.SAVED_VIEW.VIEW','READ'),('REPORT.SAVED_VIEW.CREATE','DRAFT'),('REPORT.SAVED_VIEW.UPDATE','DRAFT'),('REPORT.SAVED_VIEW.SHARE','REVIEW')
ON CONFLICT(permission_code) DO UPDATE SET authority_class=EXCLUDED.authority_class;

CREATE TABLE report_saved_view(
 report_saved_view_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), tenant_id uuid NOT NULL REFERENCES tenant(tenant_id), entity_id uuid NOT NULL,
 owner_actor_id text NOT NULL CHECK(owner_actor_id=btrim(owner_actor_id) AND length(owner_actor_id) BETWEEN 1 AND 300),
 name text NOT NULL CHECK(name=btrim(name) AND length(name) BETWEEN 1 AND 160), report_type text NOT NULL CHECK(report_type IN('FINANCIAL_STATEMENTS','GENERAL_LEDGER','TRIAL_BALANCE','BALANCE_SHEET','INCOME_STATEMENT','CASH_FLOW','AP_AGING','AR_AGING','BUDGET_VS_ACTUAL','CWIP_ROLLFORWARD','PROJECT_COST','UNIT_COST_LEDGER')),
 period_id uuid NOT NULL, filters jsonb NOT NULL CHECK(jsonb_typeof(filters)='object'), visibility text NOT NULL CHECK(visibility IN('PRIVATE','ENTITY_SHARED')),
 revision bigint NOT NULL DEFAULT 0 CHECK(revision>=0), created_at timestamptz NOT NULL DEFAULT clock_timestamp(), updated_at timestamptz NOT NULL DEFAULT clock_timestamp(),
 UNIQUE(tenant_id,report_saved_view_id), UNIQUE(tenant_id,entity_id,owner_actor_id,name),
 FOREIGN KEY(tenant_id,entity_id) REFERENCES entity(tenant_id,entity_id), FOREIGN KEY(tenant_id,entity_id,period_id) REFERENCES accounting_period(tenant_id,entity_id,period_id)
);
CREATE INDEX report_saved_view_scope_idx ON report_saved_view(tenant_id,entity_id,visibility,updated_at DESC,report_saved_view_id DESC);
CREATE TABLE report_saved_view_history(
 report_saved_view_history_id uuid PRIMARY KEY DEFAULT gen_random_uuid(), report_saved_view_id uuid NOT NULL, tenant_id uuid NOT NULL REFERENCES tenant(tenant_id),
 revision bigint NOT NULL CHECK(revision>=0), actor_id text NOT NULL, action text NOT NULL CHECK(action IN('CREATE','UPDATE')), reason text NOT NULL CHECK(reason=btrim(reason) AND length(reason) BETWEEN 8 AND 2000),
 snapshot_hash text NOT NULL CHECK(snapshot_hash~'^sha256:[0-9a-f]{64}$'), created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
 UNIQUE(report_saved_view_id,revision), FOREIGN KEY(report_saved_view_id,tenant_id) REFERENCES report_saved_view(report_saved_view_id,tenant_id)
);
ALTER TABLE report_saved_view ENABLE ROW LEVEL SECURITY; ALTER TABLE report_saved_view_history ENABLE ROW LEVEL SECURITY;
CREATE POLICY report_saved_view_scope ON report_saved_view USING(tenant_id=refs_current_tenant() AND refs_entity_allowed(entity_id));
CREATE POLICY report_saved_view_history_scope ON report_saved_view_history USING(EXISTS(SELECT 1 FROM report_saved_view v WHERE v.report_saved_view_id=report_saved_view_history.report_saved_view_id AND v.tenant_id=refs_current_tenant() AND refs_entity_allowed(v.entity_id)));
REVOKE ALL ON report_saved_view,report_saved_view_history FROM PUBLIC,refs_app;
CREATE FUNCTION refs_guard_report_saved_view() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog,public,pg_temp AS $$
BEGIN
 IF TG_OP='DELETE' THEN RAISE EXCEPTION 'Saved report view is retained evidence' USING ERRCODE='55000'; END IF;
 IF NEW.tenant_id IS DISTINCT FROM OLD.tenant_id OR NEW.entity_id IS DISTINCT FROM OLD.entity_id OR NEW.owner_actor_id IS DISTINCT FROM OLD.owner_actor_id OR NEW.created_at IS DISTINCT FROM OLD.created_at OR NEW.revision<>OLD.revision+1 OR NEW.updated_at<OLD.updated_at THEN RAISE EXCEPTION 'Saved report view mutation requires authoritative command' USING ERRCODE='42501'; END IF; RETURN NEW;
END;$$;
CREATE TRIGGER report_saved_view_protect BEFORE UPDATE OR DELETE ON report_saved_view FOR EACH ROW EXECUTE FUNCTION refs_guard_report_saved_view();
CREATE TRIGGER report_saved_view_history_append_only BEFORE UPDATE OR DELETE ON report_saved_view_history FOR EACH ROW EXECUTE FUNCTION reject_mutation();

CREATE FUNCTION refs_report_saved_view_hash(p_entity uuid,p_owner text,p_name text,p_report_type text,p_period uuid,p_filters jsonb,p_visibility text) RETURNS text LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$ SELECT refs_jsonb_hash(jsonb_build_object('entity_id',p_entity,'owner_actor_id',p_owner,'name',p_name,'report_type',p_report_type,'period_id',p_period,'filters',p_filters,'visibility',p_visibility)) $$;
CREATE FUNCTION refs_report_saved_view_request_hash(p_tenant uuid,p_entity uuid,p_view uuid,p_expected_revision bigint,p_name text,p_report_type text,p_period uuid,p_filters jsonb,p_visibility text,p_reason text) RETURNS text LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$ SELECT refs_jsonb_hash(jsonb_build_object('tenant_id',p_tenant,'entity_id',p_entity,'view_id',p_view,'expected_revision',p_expected_revision,'name',p_name,'report_type',p_report_type,'period_id',p_period,'filters',p_filters,'visibility',p_visibility,'reason',p_reason)) $$;
CREATE FUNCTION refs_validate_report_saved_view(p_tenant uuid,p_entity uuid,p_name text,p_report_type text,p_period uuid,p_filters jsonb,p_visibility text) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
BEGIN
 IF p_name IS NULL OR p_name<>btrim(p_name) OR length(p_name) NOT BETWEEN 1 AND 160 OR p_report_type NOT IN('FINANCIAL_STATEMENTS','GENERAL_LEDGER','TRIAL_BALANCE','BALANCE_SHEET','INCOME_STATEMENT','CASH_FLOW','AP_AGING','AR_AGING','BUDGET_VS_ACTUAL','CWIP_ROLLFORWARD','PROJECT_COST','UNIT_COST_LEDGER') OR p_visibility NOT IN('PRIVATE','ENTITY_SHARED') OR jsonb_typeof(p_filters)<>'object' OR jsonb_object_length(p_filters)>30 OR NOT EXISTS(SELECT 1 FROM accounting_period WHERE tenant_id=p_tenant AND entity_id=p_entity AND period_id=p_period) THEN RAISE EXCEPTION 'Invalid report saved view' USING ERRCODE='22023'; END IF;
END;$$;
CREATE FUNCTION refs_report_saved_view_payload(p_tenant uuid,p_entity uuid,p_view uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$ DECLARE v report_saved_view; actor text:=refs_current_actor(); BEGIN PERFORM refs_assert_scope(p_tenant,p_entity,'REPORT.SAVED_VIEW.VIEW'); SELECT * INTO v FROM report_saved_view WHERE tenant_id=p_tenant AND entity_id=p_entity AND report_saved_view_id=p_view; IF NOT FOUND OR (v.visibility='PRIVATE' AND v.owner_actor_id IS DISTINCT FROM actor) THEN RAISE EXCEPTION 'Saved report view was not found' USING ERRCODE='P0002'; END IF; RETURN jsonb_build_object('schema_version','REPORT_SAVED_VIEW_V1','saved_view_id',v.report_saved_view_id,'tenant_id',v.tenant_id,'entity_id',v.entity_id,'owner_actor_id',v.owner_actor_id,'name',v.name,'report_type',v.report_type,'period_id',v.period_id,'filters',v.filters,'visibility',v.visibility,'revision',v.revision::text,'created_at',v.created_at,'updated_at',v.updated_at); END;$$;
CREATE FUNCTION refs_read_report_saved_views(p_tenant uuid,p_entity uuid,p_limit integer,p_after_updated_at timestamptz,p_after_id uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$ DECLARE actor text:=refs_current_actor(); rows jsonb; cursor jsonb; BEGIN PERFORM refs_assert_scope(p_tenant,p_entity,'REPORT.SAVED_VIEW.VIEW'); IF p_limit NOT BETWEEN 1 AND 100 OR (p_after_updated_at IS NULL)<>(p_after_id IS NULL) THEN RAISE EXCEPTION 'Invalid saved view page' USING ERRCODE='22023'; END IF; SELECT COALESCE(jsonb_agg(refs_report_saved_view_payload(p_tenant,p_entity,v.report_saved_view_id) ORDER BY v.updated_at DESC,v.report_saved_view_id DESC),'[]'::jsonb) INTO rows FROM (SELECT report_saved_view_id,updated_at FROM report_saved_view WHERE tenant_id=p_tenant AND entity_id=p_entity AND (visibility='ENTITY_SHARED' OR owner_actor_id=actor) AND (p_after_updated_at IS NULL OR (updated_at,report_saved_view_id)<(p_after_updated_at,p_after_id)) ORDER BY updated_at DESC,report_saved_view_id DESC LIMIT p_limit) v; IF jsonb_array_length(rows)=p_limit THEN cursor:=jsonb_build_object('updated_at',rows->(p_limit-1)->>'updated_at','saved_view_id',rows->(p_limit-1)->>'saved_view_id'); END IF; RETURN jsonb_build_object('schema_version','REPORT_SAVED_VIEW_PAGE_V1','entity_id',p_entity,'limit',p_limit,'after_updated_at',p_after_updated_at,'after_id',p_after_id,'next_cursor',cursor,'rows',rows); END;$$;
CREATE FUNCTION refs_create_report_saved_view(p_tenant uuid,p_entity uuid,p_name text,p_report_type text,p_period uuid,p_filters jsonb,p_visibility text,p_reason text,p_idempotency_key text,p_request_hash text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$ DECLARE actor text:=refs_current_actor(); idem idempotency_receipt; view_id uuid:=gen_random_uuid(); payload jsonb; result jsonb; permission text; BEGIN
 IF actor IS NULL OR length(btrim(coalesce(p_reason,''))) NOT BETWEEN 8 AND 2000 OR length(coalesce(p_idempotency_key,'')) NOT BETWEEN 8 AND 200 THEN RAISE EXCEPTION 'Invalid saved report view create command' USING ERRCODE='22023'; END IF; permission:=CASE WHEN p_visibility='ENTITY_SHARED' THEN 'REPORT.SAVED_VIEW.SHARE' ELSE 'REPORT.SAVED_VIEW.CREATE' END; PERFORM refs_assert_scope(p_tenant,p_entity,permission); PERFORM refs_assert_scope(p_tenant,p_entity,'REPORT.SAVED_VIEW.VIEW'); PERFORM refs_validate_report_saved_view(p_tenant,p_entity,p_name,p_report_type,p_period,p_filters,p_visibility); IF p_request_hash IS DISTINCT FROM refs_report_saved_view_request_hash(p_tenant,p_entity,NULL,NULL,p_name,p_report_type,p_period,p_filters,p_visibility,p_reason) THEN RAISE EXCEPTION 'Saved report view request hash mismatch' USING ERRCODE='22023'; END IF;
 INSERT INTO idempotency_receipt(tenant_id,operation_scope,idempotency_key,request_hash,status,actor_id) VALUES(p_tenant,'REPORT_SAVED_VIEW_CREATE:'||p_entity,p_idempotency_key,p_request_hash,'IN_PROGRESS',actor) ON CONFLICT DO NOTHING; SELECT * INTO idem FROM idempotency_receipt WHERE tenant_id=p_tenant AND operation_scope='REPORT_SAVED_VIEW_CREATE:'||p_entity AND idempotency_key=p_idempotency_key FOR UPDATE; IF idem.actor_id IS DISTINCT FROM actor OR idem.request_hash IS DISTINCT FROM p_request_hash THEN RAISE EXCEPTION 'Saved report view idempotency conflict' USING ERRCODE='23505'; END IF; IF idem.status='SUCCEEDED' THEN RETURN idem.response_body||jsonb_build_object('idempotent',true); END IF;
 INSERT INTO report_saved_view(report_saved_view_id,tenant_id,entity_id,owner_actor_id,name,report_type,period_id,filters,visibility) VALUES(view_id,p_tenant,p_entity,actor,p_name,p_report_type,p_period,p_filters,p_visibility); payload:=refs_report_saved_view_payload(p_tenant,p_entity,view_id); INSERT INTO report_saved_view_history(report_saved_view_id,tenant_id,revision,actor_id,action,reason,snapshot_hash) VALUES(view_id,p_tenant,0,actor,'CREATE',btrim(p_reason),refs_jsonb_hash(payload)); INSERT INTO audit_event(tenant_id,entity_id,event_type,object_type,object_id,action,actor_id,actor_type,permission_used,request_id,correlation_id,idempotency_key,after_hash,reason,metadata) VALUES(p_tenant,p_entity,'REPORT_SAVED_VIEW_CREATED','REPORT_SAVED_VIEW',view_id,'CREATE',actor,'USER',permission,p_idempotency_key,p_idempotency_key,p_idempotency_key,refs_jsonb_hash(payload),btrim(p_reason),payload); INSERT INTO outbox_event(tenant_id,entity_id,aggregate_type,aggregate_id,event_type,payload,payload_hash) VALUES(p_tenant,p_entity,'REPORT_SAVED_VIEW',view_id,'REPORT_SAVED_VIEW_CREATED',payload,refs_jsonb_hash(payload)); result:=payload||jsonb_build_object('idempotent',false); UPDATE idempotency_receipt SET status='SUCCEEDED',response_status=201,response_body=result,completed_at=clock_timestamp() WHERE idempotency_receipt_id=idem.idempotency_receipt_id; RETURN result; END;$$;
CREATE FUNCTION refs_update_report_saved_view(p_tenant uuid,p_entity uuid,p_view uuid,p_expected_revision bigint,p_name text,p_report_type text,p_period uuid,p_filters jsonb,p_visibility text,p_reason text,p_idempotency_key text,p_request_hash text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$ DECLARE actor text:=refs_current_actor(); idem idempotency_receipt; v report_saved_view; payload jsonb; result jsonb; permission text; BEGIN
 IF actor IS NULL OR p_expected_revision<0 OR length(btrim(coalesce(p_reason,''))) NOT BETWEEN 8 AND 2000 OR length(coalesce(p_idempotency_key,'')) NOT BETWEEN 8 AND 200 THEN RAISE EXCEPTION 'Invalid saved report view update command' USING ERRCODE='22023'; END IF; SELECT * INTO v FROM report_saved_view WHERE tenant_id=p_tenant AND entity_id=p_entity AND report_saved_view_id=p_view FOR UPDATE; IF NOT FOUND OR v.owner_actor_id IS DISTINCT FROM actor THEN RAISE EXCEPTION 'Saved report view is not owned by current actor' USING ERRCODE='42501'; END IF; permission:=CASE WHEN p_visibility='ENTITY_SHARED' OR v.visibility='ENTITY_SHARED' THEN 'REPORT.SAVED_VIEW.SHARE' ELSE 'REPORT.SAVED_VIEW.UPDATE' END; PERFORM refs_assert_scope(p_tenant,p_entity,permission); PERFORM refs_assert_scope(p_tenant,p_entity,'REPORT.SAVED_VIEW.VIEW'); PERFORM refs_validate_report_saved_view(p_tenant,p_entity,p_name,p_report_type,p_period,p_filters,p_visibility); IF p_request_hash IS DISTINCT FROM refs_report_saved_view_request_hash(p_tenant,p_entity,p_view,p_expected_revision,p_name,p_report_type,p_period,p_filters,p_visibility,p_reason) THEN RAISE EXCEPTION 'Saved report view request hash mismatch' USING ERRCODE='22023'; END IF;
 INSERT INTO idempotency_receipt(tenant_id,operation_scope,idempotency_key,request_hash,status,actor_id) VALUES(p_tenant,'REPORT_SAVED_VIEW_UPDATE:'||p_entity,p_idempotency_key,p_request_hash,'IN_PROGRESS',actor) ON CONFLICT DO NOTHING; SELECT * INTO idem FROM idempotency_receipt WHERE tenant_id=p_tenant AND operation_scope='REPORT_SAVED_VIEW_UPDATE:'||p_entity AND idempotency_key=p_idempotency_key FOR UPDATE; IF idem.actor_id IS DISTINCT FROM actor OR idem.request_hash IS DISTINCT FROM p_request_hash THEN RAISE EXCEPTION 'Saved report view idempotency conflict' USING ERRCODE='23505'; END IF; IF idem.status='SUCCEEDED' THEN RETURN idem.response_body||jsonb_build_object('idempotent',true); END IF; IF v.revision<>p_expected_revision THEN RAISE EXCEPTION 'Saved report view revision conflict' USING ERRCODE='40001'; END IF;
 UPDATE report_saved_view SET name=p_name,report_type=p_report_type,period_id=p_period,filters=p_filters,visibility=p_visibility,revision=revision+1,updated_at=clock_timestamp() WHERE report_saved_view_id=p_view; payload:=refs_report_saved_view_payload(p_tenant,p_entity,p_view); INSERT INTO report_saved_view_history(report_saved_view_id,tenant_id,revision,actor_id,action,reason,snapshot_hash) VALUES(p_view,p_tenant,p_expected_revision+1,actor,'UPDATE',btrim(p_reason),refs_jsonb_hash(payload)); INSERT INTO audit_event(tenant_id,entity_id,event_type,object_type,object_id,action,actor_id,actor_type,permission_used,request_id,correlation_id,idempotency_key,after_hash,reason,metadata) VALUES(p_tenant,p_entity,'REPORT_SAVED_VIEW_UPDATED','REPORT_SAVED_VIEW',p_view,'UPDATE',actor,'USER',permission,p_idempotency_key,p_idempotency_key,p_idempotency_key,refs_jsonb_hash(payload),btrim(p_reason),payload); INSERT INTO outbox_event(tenant_id,entity_id,aggregate_type,aggregate_id,event_type,payload,payload_hash) VALUES(p_tenant,p_entity,'REPORT_SAVED_VIEW',p_view,'REPORT_SAVED_VIEW_UPDATED',payload,refs_jsonb_hash(payload)); result:=payload||jsonb_build_object('idempotent',false); UPDATE idempotency_receipt SET status='SUCCEEDED',response_status=200,response_body=result,completed_at=clock_timestamp() WHERE idempotency_receipt_id=idem.idempotency_receipt_id; RETURN result; END;$$;
REVOKE ALL ON FUNCTION refs_report_saved_view_hash(uuid,text,text,text,uuid,jsonb,text),refs_report_saved_view_request_hash(uuid,uuid,uuid,bigint,text,text,uuid,jsonb,text,text),refs_read_report_saved_views(uuid,uuid,integer,timestamptz,uuid),refs_report_saved_view_payload(uuid,uuid,uuid),refs_create_report_saved_view(uuid,uuid,text,text,uuid,jsonb,text,text,text,text),refs_update_report_saved_view(uuid,uuid,uuid,bigint,text,text,uuid,jsonb,text,text,text,text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION refs_report_saved_view_hash(uuid,text,text,text,uuid,jsonb,text),refs_report_saved_view_request_hash(uuid,uuid,uuid,bigint,text,text,uuid,jsonb,text,text),refs_read_report_saved_views(uuid,uuid,integer,timestamptz,uuid),refs_report_saved_view_payload(uuid,uuid,uuid),refs_create_report_saved_view(uuid,uuid,text,text,uuid,jsonb,text,text,text,text),refs_update_report_saved_view(uuid,uuid,uuid,bigint,text,text,uuid,jsonb,text,text,text,text) TO refs_app;
COMMIT;
