BEGIN;

-- Webhook configuration is control-plane evidence only.  The existing outbox
-- dispatcher remains the sole delivery mechanism; this migration never sends
-- a network request and never retains endpoint credentials in readable data.
INSERT INTO permission_catalog(permission_code,domain,risk_class,sod_class) VALUES
 ('INTEGRATION.WEBHOOK.VIEW','INTEGRATION','LOW','READ'),
 ('INTEGRATION.WEBHOOK.CREATE','INTEGRATION','HIGH','WEBHOOK_SUBSCRIPTION_DRAFT'),
 ('INTEGRATION.WEBHOOK.SUBMIT','INTEGRATION','HIGH','WEBHOOK_SUBSCRIPTION_SUBMIT'),
 ('INTEGRATION.WEBHOOK.APPROVE','INTEGRATION','CRITICAL','WEBHOOK_SUBSCRIPTION_APPROVE'),
 ('INTEGRATION.WEBHOOK.SUSPEND','INTEGRATION','HIGH','WEBHOOK_SUBSCRIPTION_SUSPEND')
ON CONFLICT(permission_code) DO UPDATE SET active=true,domain=EXCLUDED.domain,risk_class=EXCLUDED.risk_class,sod_class=EXCLUDED.sod_class,version=permission_catalog.version+1,effective_to=NULL;
INSERT INTO runtime_human_permission_authority(permission_code,authority_class) VALUES
 ('INTEGRATION.WEBHOOK.VIEW','READ'),('INTEGRATION.WEBHOOK.CREATE','DRAFT'),('INTEGRATION.WEBHOOK.SUBMIT','SUBMIT'),('INTEGRATION.WEBHOOK.APPROVE','APPROVE'),('INTEGRATION.WEBHOOK.SUSPEND','JE_REVIEW')
ON CONFLICT(permission_code) DO UPDATE SET authority_class=EXCLUDED.authority_class;

CREATE TABLE webhook_subscription(
 webhook_subscription_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenant(tenant_id),entity_id uuid NOT NULL,
 subscription_name text NOT NULL CHECK(subscription_name=btrim(subscription_name) AND length(subscription_name) BETWEEN 1 AND 160 AND subscription_name !~ '[[:cntrl:]]'),
 -- Only a DNS name is retained.  Numeric addresses, localhost and private
 -- names are refused before any future dispatcher can resolve them.
 endpoint_host text NOT NULL CHECK(endpoint_host=btrim(endpoint_host) AND endpoint_host~'^[A-Za-z][A-Za-z0-9.-]{1,253}$' AND endpoint_host LIKE '%.%' AND endpoint_host !~* '^[0-9a-f:.]+$' AND endpoint_host !~* '(^|[.])localhost([.]|$)' AND endpoint_host !~* '(^|[.])(local|internal|test)([.]|$)'),
 endpoint_path text NOT NULL CHECK(endpoint_path=btrim(endpoint_path) AND endpoint_path~'^/[A-Za-z0-9._~!$&''()*+,;=:@/%-]{0,1023}$'),
 event_types text[] NOT NULL CHECK(cardinality(event_types) BETWEEN 1 AND 64 AND event_types=ARRAY(SELECT DISTINCT e FROM unnest(event_types) e ORDER BY e)),
 signing_key_reference text NOT NULL CHECK(signing_key_reference=btrim(signing_key_reference) AND length(signing_key_reference) BETWEEN 8 AND 300 AND signing_key_reference !~ '[[:cntrl:]]'),
 signing_key_fingerprint text NOT NULL CHECK(signing_key_fingerprint~'^sha256:[0-9a-f]{64}$'),
 status text NOT NULL DEFAULT 'DRAFT' CHECK(status IN('DRAFT','PENDING_APPROVAL','ACTIVE','SUSPENDED')),
 revision bigint NOT NULL DEFAULT 0 CHECK(revision>=0),created_by text NOT NULL,created_at timestamptz NOT NULL DEFAULT clock_timestamp(),submitted_by text,submitted_at timestamptz,approved_by text,approved_at timestamptz,suspended_by text,suspended_at timestamptz,
 UNIQUE(tenant_id,webhook_subscription_id),UNIQUE(tenant_id,entity_id,subscription_name),
 FOREIGN KEY(tenant_id,entity_id) REFERENCES entity(tenant_id,entity_id),
 CHECK((submitted_by IS NULL)=(submitted_at IS NULL) AND (approved_by IS NULL)=(approved_at IS NULL) AND (suspended_by IS NULL)=(suspended_at IS NULL)),
 CHECK(submitted_by IS NULL OR submitted_by<>created_by),CHECK(approved_by IS NULL OR approved_by<>created_by AND approved_by<>submitted_by),
 CHECK((status='DRAFT' AND revision=0 AND submitted_by IS NULL AND approved_by IS NULL AND suspended_by IS NULL)
    OR(status='PENDING_APPROVAL' AND revision=1 AND submitted_by IS NOT NULL AND approved_by IS NULL AND suspended_by IS NULL)
    OR(status='ACTIVE' AND revision=2 AND submitted_by IS NOT NULL AND approved_by IS NOT NULL AND suspended_by IS NULL)
    OR(status='SUSPENDED' AND revision=3 AND submitted_by IS NOT NULL AND approved_by IS NOT NULL AND suspended_by IS NOT NULL))
);
CREATE TABLE webhook_subscription_history(
 webhook_subscription_history_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),webhook_subscription_id uuid NOT NULL,tenant_id uuid NOT NULL,from_status text,to_status text NOT NULL,revision bigint NOT NULL CHECK(revision>=0),actor_id text NOT NULL,reason text NOT NULL,event_hash text NOT NULL CHECK(event_hash~'^sha256:[0-9a-f]{64}$'),created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
 UNIQUE(webhook_subscription_id,revision),FOREIGN KEY(tenant_id,webhook_subscription_id) REFERENCES webhook_subscription(tenant_id,webhook_subscription_id)
);
-- Delivery history has no response payload and no endpoint material.  It is
-- written only by a future dedicated service command, never by human APIs.
CREATE TABLE webhook_delivery_history(
 webhook_delivery_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,entity_id uuid NOT NULL,webhook_subscription_id uuid NOT NULL,outbox_event_id uuid NOT NULL,event_type text NOT NULL,payload_hash text NOT NULL CHECK(payload_hash~'^sha256:[0-9a-f]{64}$'),attempt_number integer NOT NULL CHECK(attempt_number>=1),status text NOT NULL CHECK(status IN('DELIVERED','RETRY_SCHEDULED','FAILED')),delivered_at timestamptz NOT NULL DEFAULT clock_timestamp(),response_status integer,response_hash text,
 UNIQUE(tenant_id,webhook_subscription_id,outbox_event_id,attempt_number),FOREIGN KEY(tenant_id,entity_id) REFERENCES entity(tenant_id,entity_id),FOREIGN KEY(tenant_id,webhook_subscription_id) REFERENCES webhook_subscription(tenant_id,webhook_subscription_id),FOREIGN KEY(outbox_event_id) REFERENCES outbox_event(outbox_event_id),
 CHECK(response_status IS NULL OR response_status BETWEEN 100 AND 599),CHECK(response_hash IS NULL OR response_hash~'^sha256:[0-9a-f]{64}$')
);
CREATE INDEX webhook_subscription_register_idx ON webhook_subscription(tenant_id,entity_id,created_at DESC,webhook_subscription_id DESC);
CREATE INDEX webhook_delivery_history_read_idx ON webhook_delivery_history(tenant_id,entity_id,webhook_subscription_id,delivered_at DESC,webhook_delivery_id DESC);
ALTER TABLE webhook_subscription ENABLE ROW LEVEL SECURITY;ALTER TABLE webhook_subscription_history ENABLE ROW LEVEL SECURITY;ALTER TABLE webhook_delivery_history ENABLE ROW LEVEL SECURITY;
CREATE POLICY webhook_subscription_scope ON webhook_subscription USING(tenant_id=refs_current_tenant() AND refs_entity_allowed(entity_id));
CREATE POLICY webhook_subscription_history_scope ON webhook_subscription_history USING(EXISTS(SELECT 1 FROM webhook_subscription s WHERE s.tenant_id=refs_current_tenant() AND s.webhook_subscription_id=webhook_subscription_history.webhook_subscription_id AND refs_entity_allowed(s.entity_id)));
CREATE POLICY webhook_delivery_history_scope ON webhook_delivery_history USING(tenant_id=refs_current_tenant() AND refs_entity_allowed(entity_id));
REVOKE ALL ON webhook_subscription,webhook_subscription_history,webhook_delivery_history FROM PUBLIC,refs_app;

CREATE TABLE webhook_subscription_gate(backend_pid integer NOT NULL,transaction_id bigint NOT NULL,tenant_id uuid NOT NULL,webhook_subscription_id uuid NOT NULL,operation text NOT NULL CHECK(operation IN('PENDING_APPROVAL','ACTIVE','SUSPENDED')),PRIMARY KEY(backend_pid,transaction_id,tenant_id,webhook_subscription_id,operation));
CREATE FUNCTION refs_guard_webhook_subscription() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog,public,pg_temp AS $$
BEGIN
 IF TG_OP='DELETE' THEN RAISE EXCEPTION 'Webhook subscription is retained evidence' USING ERRCODE='55000';END IF;
 IF TG_OP='INSERT' THEN IF NEW.status<>'DRAFT' OR NEW.revision<>0 OR NEW.created_by IS DISTINCT FROM refs_current_actor() THEN RAISE EXCEPTION 'Webhook subscription must start as authenticated actor Draft' USING ERRCODE='42501';END IF;RETURN NEW;END IF;
 IF NOT EXISTS(SELECT 1 FROM webhook_subscription_gate g WHERE g.backend_pid=pg_backend_pid() AND g.transaction_id=txid_current() AND g.tenant_id=OLD.tenant_id AND g.webhook_subscription_id=OLD.webhook_subscription_id AND g.operation=NEW.status) OR NEW.revision<>OLD.revision+1 OR (to_jsonb(NEW)-ARRAY['status','revision','submitted_by','submitted_at','approved_by','approved_at','suspended_by','suspended_at']::text[]) IS DISTINCT FROM(to_jsonb(OLD)-ARRAY['status','revision','submitted_by','submitted_at','approved_by','approved_at','suspended_by','suspended_at']::text[]) THEN RAISE EXCEPTION 'Webhook subscription mutation requires an authoritative command' USING ERRCODE='42501';END IF;RETURN NEW;
END;$$;
CREATE TRIGGER webhook_subscription_protect BEFORE INSERT OR UPDATE OR DELETE ON webhook_subscription FOR EACH ROW EXECUTE FUNCTION refs_guard_webhook_subscription();
CREATE TRIGGER webhook_subscription_history_append_only BEFORE UPDATE OR DELETE ON webhook_subscription_history FOR EACH ROW EXECUTE FUNCTION reject_mutation();
CREATE TRIGGER webhook_delivery_history_append_only BEFORE UPDATE OR DELETE ON webhook_delivery_history FOR EACH ROW EXECUTE FUNCTION reject_mutation();

CREATE FUNCTION refs_webhook_subscription_create_hash(p_tenant uuid,p_entity uuid,p_name text,p_host text,p_path text,p_events text[],p_key_ref text,p_key_fingerprint text,p_reason text) RETURNS text LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$ SELECT refs_jsonb_hash(jsonb_build_object('schema_version','WEBHOOK_SUBSCRIPTION_CREATE_V1','tenant_id',p_tenant,'entity_id',p_entity,'name',p_name,'host',lower(p_host),'path',p_path,'event_types',to_jsonb(p_events),'signing_key_reference',p_key_ref,'signing_key_fingerprint',p_key_fingerprint,'reason',p_reason)) $$;
CREATE FUNCTION refs_webhook_subscription_transition_hash(p_tenant uuid,p_entity uuid,p_subscription uuid,p_action text,p_revision bigint,p_reason text) RETURNS text LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$ SELECT refs_jsonb_hash(jsonb_build_object('schema_version','WEBHOOK_SUBSCRIPTION_TRANSITION_V1','tenant_id',p_tenant,'entity_id',p_entity,'subscription_id',p_subscription,'action',upper(p_action),'revision',p_revision,'reason',p_reason)) $$;
CREATE FUNCTION refs_webhook_subscription_payload(p_tenant uuid,p_entity uuid,p_subscription uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$ DECLARE s webhook_subscription;BEGIN PERFORM refs_assert_scope(p_tenant,p_entity,'INTEGRATION.WEBHOOK.VIEW');SELECT * INTO s FROM webhook_subscription WHERE tenant_id=p_tenant AND entity_id=p_entity AND webhook_subscription_id=p_subscription;IF NOT FOUND THEN RAISE EXCEPTION 'Webhook subscription was not found' USING ERRCODE='P0002';END IF;RETURN jsonb_build_object('schema_version','WEBHOOK_SUBSCRIPTION_V1','subscription_id',s.webhook_subscription_id,'tenant_id',s.tenant_id,'entity_id',s.entity_id,'subscription_name',s.subscription_name,'endpoint_host',s.endpoint_host,'endpoint_path',s.endpoint_path,'event_types',to_jsonb(s.event_types),'signing_key_fingerprint',s.signing_key_fingerprint,'status',s.status,'revision',s.revision::text,'created_by',s.created_by,'created_at',s.created_at,'submitted_by',s.submitted_by,'submitted_at',s.submitted_at,'approved_by',s.approved_by,'approved_at',s.approved_at,'suspended_by',s.suspended_by,'suspended_at',s.suspended_at);END;$$;
CREATE FUNCTION refs_create_webhook_subscription(p_tenant uuid,p_entity uuid,p_name text,p_host text,p_path text,p_events text[],p_key_ref text,p_key_fingerprint text,p_reason text,p_idempotency_key text,p_request_hash text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE actor text:=refs_current_actor();idem idempotency_receipt;sid uuid:=gen_random_uuid();payload jsonb;result jsonb;
BEGIN
 IF actor IS NULL OR p_name<>btrim(p_name) OR length(p_name) NOT BETWEEN 1 AND 160 OR p_host<>btrim(p_host) OR p_host!~'^[A-Za-z][A-Za-z0-9.-]{1,253}$' OR p_host NOT LIKE '%.%' OR p_host~*'^[0-9a-f:.]+$' OR p_host~*'(^|[.])localhost([.]|$)' OR p_host~*'(^|[.])(local|internal|test)([.]|$)' OR p_path<>btrim(p_path) OR p_path!~'^/[A-Za-z0-9._~!$&''()*+,;=:@/%-]{0,1023}$' OR cardinality(p_events) NOT BETWEEN 1 AND 64 OR p_events<>ARRAY(SELECT DISTINCT e FROM unnest(p_events) e ORDER BY e) OR EXISTS(SELECT 1 FROM unnest(p_events) e WHERE e !~ '^[A-Za-z][A-Za-z0-9_.:-]{0,127}$') OR p_key_ref<>btrim(p_key_ref) OR length(p_key_ref) NOT BETWEEN 8 AND 300 OR p_key_fingerprint !~ '^sha256:[0-9a-f]{64}$' OR length(btrim(coalesce(p_reason,''))) NOT BETWEEN 8 AND 2000 OR length(coalesce(p_idempotency_key,'')) NOT BETWEEN 8 AND 200 OR p_request_hash IS DISTINCT FROM refs_webhook_subscription_create_hash(p_tenant,p_entity,p_name,p_host,p_path,p_events,p_key_ref,p_key_fingerprint,p_reason) THEN RAISE EXCEPTION 'Invalid webhook subscription create command' USING ERRCODE='22023';END IF;
 PERFORM refs_assert_scope(p_tenant,p_entity,'INTEGRATION.WEBHOOK.VIEW');PERFORM refs_assert_scope(p_tenant,p_entity,'INTEGRATION.WEBHOOK.CREATE');PERFORM 1 FROM entity WHERE tenant_id=p_tenant AND entity_id=p_entity AND active FOR SHARE;IF NOT FOUND THEN RAISE EXCEPTION 'Webhook subscription entity was not found or active' USING ERRCODE='P0002';END IF;
 INSERT INTO idempotency_receipt(tenant_id,operation_scope,idempotency_key,request_hash,status,actor_id) VALUES(p_tenant,'WEBHOOK_SUBSCRIPTION_CREATE:'||p_entity,p_idempotency_key,p_request_hash,'IN_PROGRESS',actor) ON CONFLICT DO NOTHING;SELECT * INTO idem FROM idempotency_receipt WHERE tenant_id=p_tenant AND operation_scope='WEBHOOK_SUBSCRIPTION_CREATE:'||p_entity AND idempotency_key=p_idempotency_key FOR UPDATE;IF idem.actor_id IS DISTINCT FROM actor OR idem.request_hash IS DISTINCT FROM p_request_hash THEN RAISE EXCEPTION 'Webhook subscription idempotency conflict' USING ERRCODE='23505';END IF;IF idem.status='SUCCEEDED' THEN RETURN idem.response_body||jsonb_build_object('idempotent',true);END IF;
 PERFORM pg_advisory_xact_lock(hashtextextended('WEBHOOK_SUBSCRIPTION:'||p_tenant::text||':'||p_entity::text||':'||lower(p_name),0));INSERT INTO webhook_subscription(webhook_subscription_id,tenant_id,entity_id,subscription_name,endpoint_host,endpoint_path,event_types,signing_key_reference,signing_key_fingerprint,created_by) VALUES(sid,p_tenant,p_entity,p_name,lower(p_host),p_path,p_events,p_key_ref,p_key_fingerprint,actor);
 payload:=jsonb_build_object('subscription_id',sid,'status','DRAFT','revision','0','event_types',to_jsonb(p_events),'signing_key_fingerprint',p_key_fingerprint);INSERT INTO webhook_subscription_history(webhook_subscription_id,tenant_id,from_status,to_status,revision,actor_id,reason,event_hash) VALUES(sid,p_tenant,NULL,'DRAFT',0,actor,btrim(p_reason),refs_jsonb_hash(payload));INSERT INTO audit_event(tenant_id,entity_id,event_type,object_type,object_id,action,actor_id,actor_type,permission_used,request_id,correlation_id,idempotency_key,after_hash,reason,metadata) VALUES(p_tenant,p_entity,'WEBHOOK_SUBSCRIPTION_DRAFT_CREATED','WEBHOOK_SUBSCRIPTION',sid,'CREATE',actor,'USER','INTEGRATION.WEBHOOK.CREATE',p_idempotency_key,p_idempotency_key,p_idempotency_key,refs_jsonb_hash(payload),btrim(p_reason),payload);INSERT INTO outbox_event(tenant_id,entity_id,aggregate_type,aggregate_id,event_type,payload,payload_hash) VALUES(p_tenant,p_entity,'WEBHOOK_SUBSCRIPTION',sid,'WEBHOOK_SUBSCRIPTION_DRAFT_CREATED',payload,refs_jsonb_hash(payload));result:=refs_webhook_subscription_payload(p_tenant,p_entity,sid)||jsonb_build_object('idempotent',false);UPDATE idempotency_receipt SET status='SUCCEEDED',response_status=201,response_body=result,completed_at=clock_timestamp() WHERE idempotency_receipt_id=idem.idempotency_receipt_id;RETURN result;
END;$$;
CREATE FUNCTION refs_transition_webhook_subscription(p_tenant uuid,p_entity uuid,p_subscription uuid,p_action text,p_revision bigint,p_reason text,p_idempotency_key text,p_request_hash text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE actor text:=refs_current_actor();action text:=upper(p_action);permission text;next_status text;idem idempotency_receipt;s webhook_subscription;payload jsonb;result jsonb;
BEGIN
 IF actor IS NULL OR action NOT IN('SUBMIT','APPROVE','SUSPEND') OR p_revision IS NULL OR p_revision<0 OR length(btrim(coalesce(p_reason,''))) NOT BETWEEN 8 AND 2000 OR length(coalesce(p_idempotency_key,'')) NOT BETWEEN 8 AND 200 OR p_request_hash IS DISTINCT FROM refs_webhook_subscription_transition_hash(p_tenant,p_entity,p_subscription,action,p_revision,p_reason) THEN RAISE EXCEPTION 'Invalid webhook subscription transition' USING ERRCODE='22023';END IF;permission:='INTEGRATION.WEBHOOK.'||action;PERFORM refs_assert_scope(p_tenant,p_entity,'INTEGRATION.WEBHOOK.VIEW');PERFORM refs_assert_scope(p_tenant,p_entity,permission);
 INSERT INTO idempotency_receipt(tenant_id,operation_scope,idempotency_key,request_hash,status,actor_id) VALUES(p_tenant,'WEBHOOK_SUBSCRIPTION_'||action||':'||p_entity,p_idempotency_key,p_request_hash,'IN_PROGRESS',actor) ON CONFLICT DO NOTHING;SELECT * INTO idem FROM idempotency_receipt WHERE tenant_id=p_tenant AND operation_scope='WEBHOOK_SUBSCRIPTION_'||action||':'||p_entity AND idempotency_key=p_idempotency_key FOR UPDATE;IF idem.actor_id IS DISTINCT FROM actor OR idem.request_hash IS DISTINCT FROM p_request_hash THEN RAISE EXCEPTION 'Webhook subscription idempotency conflict' USING ERRCODE='23505';END IF;IF idem.status='SUCCEEDED' THEN RETURN idem.response_body||jsonb_build_object('idempotent',true);END IF;
 SELECT * INTO s FROM webhook_subscription WHERE tenant_id=p_tenant AND entity_id=p_entity AND webhook_subscription_id=p_subscription FOR UPDATE;IF NOT FOUND THEN RAISE EXCEPTION 'Webhook subscription was not found' USING ERRCODE='P0002';END IF;IF s.revision<>p_revision OR(action='SUBMIT' AND(s.status<>'DRAFT' OR actor=s.created_by))OR(action='APPROVE' AND(s.status<>'PENDING_APPROVAL' OR actor IN(s.created_by,s.submitted_by)))OR(action='SUSPEND' AND(s.status<>'ACTIVE' OR actor=s.created_by)) THEN RAISE EXCEPTION 'Webhook subscription revision conflict or separation of duties violation' USING ERRCODE='40001';END IF;next_status:=CASE action WHEN 'SUBMIT' THEN 'PENDING_APPROVAL' WHEN 'APPROVE' THEN 'ACTIVE' ELSE 'SUSPENDED' END;
 INSERT INTO webhook_subscription_gate VALUES(pg_backend_pid(),txid_current(),p_tenant,p_subscription,next_status);UPDATE webhook_subscription SET status=next_status,revision=revision+1,submitted_by=CASE WHEN action='SUBMIT' THEN actor ELSE submitted_by END,submitted_at=CASE WHEN action='SUBMIT' THEN clock_timestamp() ELSE submitted_at END,approved_by=CASE WHEN action='APPROVE' THEN actor ELSE approved_by END,approved_at=CASE WHEN action='APPROVE' THEN clock_timestamp() ELSE approved_at END,suspended_by=CASE WHEN action='SUSPEND' THEN actor ELSE suspended_by END,suspended_at=CASE WHEN action='SUSPEND' THEN clock_timestamp() ELSE suspended_at END WHERE webhook_subscription_id=p_subscription;DELETE FROM webhook_subscription_gate WHERE backend_pid=pg_backend_pid() AND transaction_id=txid_current() AND tenant_id=p_tenant AND webhook_subscription_id=p_subscription AND operation=next_status;
 payload:=jsonb_build_object('subscription_id',p_subscription,'status',next_status,'revision',(s.revision+1)::text);INSERT INTO webhook_subscription_history(webhook_subscription_id,tenant_id,from_status,to_status,revision,actor_id,reason,event_hash) VALUES(p_subscription,p_tenant,s.status,next_status,s.revision+1,actor,btrim(p_reason),refs_jsonb_hash(payload));INSERT INTO audit_event(tenant_id,entity_id,event_type,object_type,object_id,action,actor_id,actor_type,permission_used,request_id,correlation_id,idempotency_key,after_hash,reason,metadata) VALUES(p_tenant,p_entity,'WEBHOOK_SUBSCRIPTION_'||action,'WEBHOOK_SUBSCRIPTION',p_subscription,action,actor,'USER',permission,p_idempotency_key,p_idempotency_key,p_idempotency_key,refs_jsonb_hash(payload),btrim(p_reason),payload);INSERT INTO outbox_event(tenant_id,entity_id,aggregate_type,aggregate_id,event_type,payload,payload_hash) VALUES(p_tenant,p_entity,'WEBHOOK_SUBSCRIPTION',p_subscription,'WEBHOOK_SUBSCRIPTION_'||action,payload,refs_jsonb_hash(payload));result:=refs_webhook_subscription_payload(p_tenant,p_entity,p_subscription)||jsonb_build_object('idempotent',false);UPDATE idempotency_receipt SET status='SUCCEEDED',response_status=200,response_body=result,completed_at=clock_timestamp() WHERE idempotency_receipt_id=idem.idempotency_receipt_id;RETURN result;
END;$$;
CREATE FUNCTION refs_read_webhook_subscription(p_tenant uuid,p_entity uuid,p_subscription uuid) RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$ SELECT refs_webhook_subscription_payload(p_tenant,p_entity,p_subscription) $$;
CREATE FUNCTION refs_read_webhook_delivery_history(p_tenant uuid,p_entity uuid,p_subscription uuid,p_limit integer DEFAULT 50,p_before timestamptz DEFAULT NULL,p_before_id uuid DEFAULT NULL) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$ DECLARE rows jsonb;BEGIN PERFORM refs_assert_scope(p_tenant,p_entity,'INTEGRATION.WEBHOOK.VIEW');IF p_limit NOT BETWEEN 1 AND 100 OR (p_before IS NULL)<>(p_before_id IS NULL) OR NOT EXISTS(SELECT 1 FROM webhook_subscription WHERE tenant_id=p_tenant AND entity_id=p_entity AND webhook_subscription_id=p_subscription) THEN RAISE EXCEPTION 'Invalid webhook delivery history request' USING ERRCODE='22023';END IF;SELECT coalesce(jsonb_agg(jsonb_build_object('delivery_id',webhook_delivery_id,'outbox_event_id',outbox_event_id,'event_type',event_type,'payload_hash',payload_hash,'attempt_number',attempt_number,'status',status,'delivered_at',delivered_at,'response_status',response_status,'response_hash',response_hash) ORDER BY delivered_at DESC,webhook_delivery_id DESC),'[]'::jsonb) INTO rows FROM(SELECT * FROM webhook_delivery_history WHERE tenant_id=p_tenant AND entity_id=p_entity AND webhook_subscription_id=p_subscription AND(p_before IS NULL OR(delivered_at,webhook_delivery_id)<(p_before,p_before_id)) ORDER BY delivered_at DESC,webhook_delivery_id DESC LIMIT p_limit)d;RETURN jsonb_build_object('schema_version','WEBHOOK_DELIVERY_HISTORY_V1','subscription_id',p_subscription,'rows',rows,'limit',p_limit);END;$$;
REVOKE ALL ON FUNCTION refs_webhook_subscription_create_hash(uuid,uuid,text,text,text,text[],text,text,text),refs_webhook_subscription_transition_hash(uuid,uuid,uuid,text,bigint,text),refs_create_webhook_subscription(uuid,uuid,text,text,text,text[],text,text,text,text,text),refs_transition_webhook_subscription(uuid,uuid,uuid,text,bigint,text,text,text),refs_read_webhook_subscription(uuid,uuid,uuid),refs_read_webhook_delivery_history(uuid,uuid,uuid,integer,timestamptz,uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION refs_webhook_subscription_create_hash(uuid,uuid,text,text,text,text[],text,text,text),refs_webhook_subscription_transition_hash(uuid,uuid,uuid,text,bigint,text),refs_create_webhook_subscription(uuid,uuid,text,text,text,text[],text,text,text,text,text),refs_transition_webhook_subscription(uuid,uuid,uuid,text,bigint,text,text,text),refs_read_webhook_subscription(uuid,uuid,uuid),refs_read_webhook_delivery_history(uuid,uuid,uuid,integer,timestamptz,uuid) TO refs_app;
COMMIT;
