BEGIN;

INSERT INTO permission_catalog(permission_code,domain,risk_class,sod_class) VALUES
 ('RECURRING.SCHEDULE.VIEW','GENERAL_LEDGER','LOW','READ'),
 ('RECURRING.SCHEDULE.CREATE','GENERAL_LEDGER','HIGH','RECURRING_DRAFT'),
 ('RECURRING.SCHEDULE.SUBMIT','GENERAL_LEDGER','HIGH','RECURRING_SUBMIT'),
 ('RECURRING.SCHEDULE.APPROVE','GENERAL_LEDGER','CRITICAL','RECURRING_APPROVE'),
 ('RECURRING.SCHEDULE.MANAGE','GENERAL_LEDGER','HIGH','RECURRING_MANAGE'),
 ('RECURRING.SCHEDULE.RUN','GENERAL_LEDGER','HIGH','RECURRING_RUN')
ON CONFLICT(permission_code) DO UPDATE SET active=true,domain=EXCLUDED.domain,risk_class=EXCLUDED.risk_class,sod_class=EXCLUDED.sod_class,version=permission_catalog.version+1,effective_to=NULL;
INSERT INTO runtime_human_permission_authority(permission_code,authority_class) VALUES
 ('RECURRING.SCHEDULE.VIEW','READ'),('RECURRING.SCHEDULE.CREATE','DRAFT'),('RECURRING.SCHEDULE.SUBMIT','SUBMIT'),('RECURRING.SCHEDULE.APPROVE','APPROVE'),('RECURRING.SCHEDULE.MANAGE','REVIEW'),('RECURRING.SCHEDULE.RUN','SCHEDULE')
ON CONFLICT(permission_code) DO UPDATE SET authority_class=EXCLUDED.authority_class;

CREATE TABLE recurring_schedule(
 recurring_schedule_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL REFERENCES tenant(tenant_id),entity_id uuid NOT NULL REFERENCES entity(entity_id),
 name text NOT NULL CHECK(name=btrim(name) AND length(name) BETWEEN 1 AND 160),journal_prefix text NOT NULL CHECK(journal_prefix=btrim(journal_prefix) AND journal_prefix~'^[A-Za-z0-9._-]{1,40}$'),currency char(3) NOT NULL CHECK(currency~'^[A-Z]{3}$'),frequency text NOT NULL CHECK(frequency IN('DAILY','WEEKLY','MONTHLY','QUARTERLY','ANNUAL')),next_due_on date NOT NULL,ends_on date,template_lines jsonb NOT NULL CHECK(jsonb_typeof(template_lines)='array'),status text NOT NULL DEFAULT 'DRAFT' CHECK(status IN('DRAFT','PENDING_APPROVAL','ACTIVE','PAUSED')),revision bigint NOT NULL DEFAULT 0 CHECK(revision>=0),created_by text NOT NULL,created_at timestamptz NOT NULL DEFAULT clock_timestamp(),submitted_by text,submitted_at timestamptz,approved_by text,approved_at timestamptz,last_run_at timestamptz,
 UNIQUE(tenant_id,entity_id,name),UNIQUE(tenant_id,recurring_schedule_id),FOREIGN KEY(tenant_id,entity_id) REFERENCES entity(tenant_id,entity_id),CHECK(ends_on IS NULL OR ends_on>=next_due_on),CHECK((submitted_by IS NULL)=(submitted_at IS NULL) AND (approved_by IS NULL)=(approved_at IS NULL)),CHECK(submitted_by IS NULL OR submitted_by<>created_by),CHECK(approved_by IS NULL OR (approved_by<>created_by AND approved_by<>submitted_by))
);
CREATE TABLE recurring_schedule_history(
 recurring_schedule_history_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),recurring_schedule_id uuid NOT NULL,tenant_id uuid NOT NULL,from_status text,to_status text NOT NULL CHECK(to_status IN('DRAFT','PENDING_APPROVAL','ACTIVE','PAUSED')),action text NOT NULL CHECK(action IN('CREATE','SUBMIT','APPROVE','PAUSE','RESUME','RUN')),revision bigint NOT NULL CHECK(revision>=0),actor_id text NOT NULL,reason text NOT NULL CHECK(length(btrim(reason)) BETWEEN 8 AND 2000),event_hash text NOT NULL CHECK(event_hash~'^sha256:[0-9a-f]{64}$'),created_at timestamptz NOT NULL DEFAULT clock_timestamp(),UNIQUE(recurring_schedule_id,revision),FOREIGN KEY(tenant_id,recurring_schedule_id) REFERENCES recurring_schedule(tenant_id,recurring_schedule_id));
CREATE TABLE recurring_schedule_run(
 recurring_schedule_run_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,entity_id uuid NOT NULL,recurring_schedule_id uuid NOT NULL,due_on date NOT NULL,status text NOT NULL CHECK(status IN('RUNNING','DRAFT_CREATED','FAILED')),attempt_count bigint NOT NULL DEFAULT 1 CHECK(attempt_count>=1),journal_entry_id uuid,failure_code text,created_at timestamptz NOT NULL DEFAULT clock_timestamp(),completed_at timestamptz,UNIQUE(tenant_id,recurring_schedule_id,due_on),UNIQUE(tenant_id,recurring_schedule_run_id),FOREIGN KEY(tenant_id,entity_id) REFERENCES entity(tenant_id,entity_id),FOREIGN KEY(tenant_id,recurring_schedule_id) REFERENCES recurring_schedule(tenant_id,recurring_schedule_id),FOREIGN KEY(tenant_id,entity_id,journal_entry_id) REFERENCES journal_entry(tenant_id,entity_id,journal_entry_id),CHECK((status='DRAFT_CREATED' AND journal_entry_id IS NOT NULL AND failure_code IS NULL AND completed_at IS NOT NULL) OR (status='FAILED' AND journal_entry_id IS NULL AND failure_code IS NOT NULL AND completed_at IS NOT NULL) OR(status='RUNNING' AND journal_entry_id IS NULL AND failure_code IS NULL AND completed_at IS NULL)));
CREATE TABLE recurring_schedule_exception(recurring_schedule_exception_id uuid PRIMARY KEY DEFAULT gen_random_uuid(),tenant_id uuid NOT NULL,entity_id uuid NOT NULL,recurring_schedule_run_id uuid NOT NULL,exception_code text NOT NULL CHECK(exception_code~'^RECURRING_[A-Z0-9_]{3,120}$'),exception_hash text NOT NULL CHECK(exception_hash~'^sha256:[0-9a-f]{64}$'),created_at timestamptz NOT NULL DEFAULT clock_timestamp(),UNIQUE(recurring_schedule_run_id,exception_code,exception_hash),FOREIGN KEY(tenant_id,recurring_schedule_run_id) REFERENCES recurring_schedule_run(tenant_id,recurring_schedule_run_id));
CREATE TABLE recurring_schedule_gate(backend_pid integer NOT NULL,transaction_id bigint NOT NULL,tenant_id uuid NOT NULL,recurring_schedule_id uuid NOT NULL,operation text NOT NULL CHECK(operation IN('SUBMIT','APPROVE','PAUSE','RESUME','RUN')),PRIMARY KEY(backend_pid,transaction_id,tenant_id,recurring_schedule_id,operation));
CREATE TABLE recurring_schedule_run_gate(backend_pid integer NOT NULL,transaction_id bigint NOT NULL,tenant_id uuid NOT NULL,recurring_schedule_run_id uuid NOT NULL,PRIMARY KEY(backend_pid,transaction_id,tenant_id,recurring_schedule_run_id));
ALTER TABLE recurring_schedule ENABLE ROW LEVEL SECURITY;ALTER TABLE recurring_schedule_history ENABLE ROW LEVEL SECURITY;ALTER TABLE recurring_schedule_run ENABLE ROW LEVEL SECURITY;ALTER TABLE recurring_schedule_exception ENABLE ROW LEVEL SECURITY;
CREATE POLICY recurring_schedule_scope ON recurring_schedule USING(tenant_id=refs_current_tenant() AND refs_entity_allowed(entity_id));
CREATE POLICY recurring_schedule_history_scope ON recurring_schedule_history USING(EXISTS(SELECT 1 FROM recurring_schedule s WHERE s.tenant_id=refs_current_tenant() AND s.recurring_schedule_id=recurring_schedule_history.recurring_schedule_id AND refs_entity_allowed(s.entity_id)));
CREATE POLICY recurring_schedule_run_scope ON recurring_schedule_run USING(tenant_id=refs_current_tenant() AND refs_entity_allowed(entity_id));
CREATE POLICY recurring_schedule_exception_scope ON recurring_schedule_exception USING(EXISTS(SELECT 1 FROM recurring_schedule_run r WHERE r.tenant_id=refs_current_tenant() AND r.recurring_schedule_run_id=recurring_schedule_exception.recurring_schedule_run_id AND refs_entity_allowed(r.entity_id)));
REVOKE ALL ON recurring_schedule,recurring_schedule_history,recurring_schedule_run,recurring_schedule_exception,recurring_schedule_gate,recurring_schedule_run_gate FROM PUBLIC,refs_app;
CREATE FUNCTION refs_guard_recurring_schedule() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog,public,pg_temp AS $$ BEGIN
 IF TG_OP='DELETE' THEN RAISE EXCEPTION 'Recurring schedule is retained evidence' USING ERRCODE='55000'; END IF;
 IF NOT EXISTS(SELECT 1 FROM recurring_schedule_gate g WHERE g.backend_pid=pg_backend_pid() AND g.transaction_id=txid_current() AND g.tenant_id=OLD.tenant_id AND g.recurring_schedule_id=OLD.recurring_schedule_id) OR NEW.revision<>OLD.revision+1 THEN RAISE EXCEPTION 'Recurring schedule mutation requires an authoritative command' USING ERRCODE='42501'; END IF; RETURN NEW;
END;$$;
CREATE FUNCTION refs_guard_recurring_schedule_run() RETURNS trigger LANGUAGE plpgsql SET search_path=pg_catalog,public,pg_temp AS $$ BEGIN
 IF TG_OP='DELETE' OR NOT EXISTS(SELECT 1 FROM recurring_schedule_run_gate g WHERE g.backend_pid=pg_backend_pid() AND g.transaction_id=txid_current() AND g.tenant_id=OLD.tenant_id AND g.recurring_schedule_run_id=OLD.recurring_schedule_run_id) THEN RAISE EXCEPTION 'Recurring schedule run mutation requires scheduler gate' USING ERRCODE='42501'; END IF; RETURN NEW;
END;$$;
CREATE TRIGGER recurring_schedule_protect BEFORE UPDATE OR DELETE ON recurring_schedule FOR EACH ROW EXECUTE FUNCTION refs_guard_recurring_schedule();
CREATE TRIGGER recurring_schedule_history_append_only BEFORE UPDATE OR DELETE ON recurring_schedule_history FOR EACH ROW EXECUTE FUNCTION reject_mutation();
CREATE TRIGGER recurring_schedule_run_protect BEFORE UPDATE OR DELETE ON recurring_schedule_run FOR EACH ROW EXECUTE FUNCTION refs_guard_recurring_schedule_run();
CREATE TRIGGER recurring_schedule_exception_append_only BEFORE UPDATE OR DELETE ON recurring_schedule_exception FOR EACH ROW EXECUTE FUNCTION reject_mutation();

CREATE FUNCTION refs_recurring_schedule_next_due(p_due date,p_frequency text) RETURNS date LANGUAGE sql IMMUTABLE SET search_path=pg_catalog,public,pg_temp AS $$ SELECT CASE p_frequency WHEN 'DAILY' THEN p_due+1 WHEN 'WEEKLY' THEN p_due+7 WHEN 'MONTHLY' THEN (p_due+INTERVAL '1 month')::date WHEN 'QUARTERLY' THEN (p_due+INTERVAL '3 months')::date WHEN 'ANNUAL' THEN (p_due+INTERVAL '1 year')::date ELSE NULL END $$;
CREATE FUNCTION refs_recurring_schedule_create_hash(p_tenant uuid,p_entity uuid,p_name text,p_prefix text,p_currency text,p_frequency text,p_next_due date,p_ends_on date,p_lines jsonb,p_reason text) RETURNS text LANGUAGE sql IMMUTABLE SET search_path=pg_catalog,public,pg_temp AS $$ SELECT refs_jsonb_hash(jsonb_build_object('schema_version','RECURRING_SCHEDULE_CREATE_V1','tenant_id',p_tenant,'entity_id',p_entity,'name',p_name,'journal_prefix',p_prefix,'currency',p_currency,'frequency',p_frequency,'next_due_on',p_next_due,'ends_on',p_ends_on,'lines',p_lines,'reason',p_reason)) $$;
CREATE FUNCTION refs_recurring_schedule_transition_hash(p_tenant uuid,p_entity uuid,p_schedule uuid,p_action text,p_revision bigint,p_reason text) RETURNS text LANGUAGE sql IMMUTABLE SET search_path=pg_catalog,public,pg_temp AS $$ SELECT refs_jsonb_hash(jsonb_build_object('schema_version','RECURRING_SCHEDULE_TRANSITION_V1','tenant_id',p_tenant,'entity_id',p_entity,'schedule_id',p_schedule,'action',p_action,'revision',p_revision,'reason',p_reason)) $$;
CREATE FUNCTION refs_recurring_schedule_run_hash(p_tenant uuid,p_entity uuid,p_as_of date,p_limit integer) RETURNS text LANGUAGE sql IMMUTABLE SET search_path=pg_catalog,public,pg_temp AS $$ SELECT refs_jsonb_hash(jsonb_build_object('schema_version','RECURRING_SCHEDULE_RUN_V1','tenant_id',p_tenant,'entity_id',p_entity,'as_of_date',p_as_of,'limit',p_limit)) $$;

CREATE FUNCTION refs_recurring_schedule_payload(p_tenant uuid,p_entity uuid,p_schedule uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$ DECLARE s recurring_schedule; actor text:=refs_current_actor(); BEGIN
 PERFORM refs_assert_scope(p_tenant,p_entity,'RECURRING.SCHEDULE.VIEW'); SELECT * INTO s FROM recurring_schedule WHERE tenant_id=p_tenant AND entity_id=p_entity AND recurring_schedule_id=p_schedule; IF NOT FOUND THEN RAISE EXCEPTION 'Recurring schedule not found' USING ERRCODE='P0002'; END IF;
 RETURN jsonb_build_object('schema_version','RECURRING_SCHEDULE_V1','recurring_schedule_id',s.recurring_schedule_id,'tenant_id',s.tenant_id,'entity_id',s.entity_id,'name',s.name,'journal_prefix',s.journal_prefix,'currency',s.currency,'frequency',s.frequency,'next_due_on',s.next_due_on,'ends_on',s.ends_on,'status',s.status,'revision',s.revision::text,'lines',(SELECT coalesce(jsonb_agg(jsonb_build_object('lineNo',(x->>'lineNo')::integer,'accountCode',x->>'accountCode','debitAmount',x->>'debitAmount','creditAmount',x->>'creditAmount','memberRef',x->'memberRef','description',x->'description','dimensions',x->'dimensions') ORDER BY (x->>'lineNo')::integer),'[]'::jsonb) FROM jsonb_array_elements(s.template_lines) x),'created_by',s.created_by,'created_at',s.created_at,'submitted_by',s.submitted_by,'submitted_at',s.submitted_at,'approved_by',s.approved_by,'approved_at',s.approved_at,'last_run_at',s.last_run_at,'history',(SELECT coalesce(jsonb_agg(jsonb_build_object('from_status',h.from_status,'to_status',h.to_status,'action',h.action,'revision',h.revision::text,'actor_id',h.actor_id,'reason',h.reason,'event_hash',h.event_hash,'created_at',h.created_at) ORDER BY h.revision),'[]'::jsonb) FROM recurring_schedule_history h WHERE h.tenant_id=p_tenant AND h.recurring_schedule_id=p_schedule),'action_flags',jsonb_build_object('can_submit',s.status='DRAFT' AND actor IS DISTINCT FROM s.created_by AND refs_entity_has_permission(p_entity,'RECURRING.SCHEDULE.SUBMIT'),'can_approve',s.status='PENDING_APPROVAL' AND actor IS DISTINCT FROM s.created_by AND actor IS DISTINCT FROM s.submitted_by AND refs_entity_has_permission(p_entity,'RECURRING.SCHEDULE.APPROVE'),'can_pause',s.status='ACTIVE' AND actor IS DISTINCT FROM s.created_by AND refs_entity_has_permission(p_entity,'RECURRING.SCHEDULE.MANAGE'),'can_resume',s.status='PAUSED' AND actor IS DISTINCT FROM s.created_by AND refs_entity_has_permission(p_entity,'RECURRING.SCHEDULE.MANAGE'),'can_run_due',s.status='ACTIVE' AND refs_entity_has_permission(p_entity,'RECURRING.SCHEDULE.RUN'),'can_post',false),'idempotent',false);
END;$$;

CREATE FUNCTION refs_validate_recurring_schedule_lines(p_tenant uuid,p_entity uuid,p_lines jsonb) RETURNS void LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$ BEGIN
 IF jsonb_typeof(p_lines)<>'array' OR jsonb_array_length(p_lines) NOT BETWEEN 2 AND 500 OR EXISTS(SELECT 1 FROM jsonb_array_elements(p_lines) x WHERE ARRAY(SELECT jsonb_object_keys(x) ORDER BY 1)<>ARRAY['accountCode','creditAmount','debitAmount','description','dimensions','lineNo','memberRef'] OR x->>'lineNo' !~ '^[1-9][0-9]*$' OR x->>'accountCode' !~ '^[A-Za-z0-9._-]{1,64}$' OR x->>'debitAmount' !~ '^(0|[1-9][0-9]{0,15})\\.[0-9]{4}$' OR x->>'creditAmount' !~ '^(0|[1-9][0-9]{0,15})\\.[0-9]{4}$' OR NOT(((x->>'debitAmount')::numeric>0 AND (x->>'creditAmount')::numeric=0) OR((x->>'creditAmount')::numeric>0 AND (x->>'debitAmount')::numeric=0)) OR jsonb_typeof(x->'dimensions')<>'object' OR (x->'memberRef' IS NOT NULL AND (jsonb_typeof(x->'memberRef')<>'null' AND (x->>'memberRef'<>btrim(x->>'memberRef') OR length(x->>'memberRef') NOT BETWEEN 1 AND 128))) OR (x->'description' IS NOT NULL AND (jsonb_typeof(x->'description')<>'null' AND (x->>'description'<>btrim(x->>'description') OR length(x->>'description') NOT BETWEEN 1 AND 1000)))) OR EXISTS(SELECT 1 FROM jsonb_array_elements(p_lines) x GROUP BY (x->>'lineNo') HAVING count(*)>1) OR (SELECT sum((x->>'debitAmount')::numeric) FROM jsonb_array_elements(p_lines) x)<>(SELECT sum((x->>'creditAmount')::numeric) FROM jsonb_array_elements(p_lines) x) OR EXISTS(SELECT 1 FROM jsonb_array_elements(p_lines) x LEFT JOIN account_master a ON a.tenant_id=p_tenant AND a.entity_id=p_entity AND a.account_code=x->>'accountCode' AND a.active WHERE a.account_code IS NULL) THEN RAISE EXCEPTION 'Recurring schedule lines must be canonical, active-account, and balanced' USING ERRCODE='23514'; END IF;
END;$$;

CREATE FUNCTION refs_create_recurring_schedule(p_tenant uuid,p_entity uuid,p_name text,p_prefix text,p_currency text,p_frequency text,p_next_due date,p_ends_on date,p_lines jsonb,p_reason text,p_idempotency_key text,p_request_hash text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$ DECLARE actor text:=refs_current_actor();idem idempotency_receipt;schedule uuid:=gen_random_uuid();payload jsonb; BEGIN
 IF actor IS NULL OR p_name IS NULL OR p_name<>btrim(p_name) OR length(p_name) NOT BETWEEN 1 AND 160 OR p_prefix !~ '^[A-Za-z0-9._-]{1,40}$' OR p_currency !~ '^[A-Z]{3}$' OR p_frequency NOT IN('DAILY','WEEKLY','MONTHLY','QUARTERLY','ANNUAL') OR p_next_due IS NULL OR (p_ends_on IS NOT NULL AND p_ends_on<p_next_due) OR length(btrim(coalesce(p_reason,''))) NOT BETWEEN 8 AND 2000 OR length(coalesce(p_idempotency_key,'')) NOT BETWEEN 8 AND 200 OR p_request_hash IS DISTINCT FROM refs_recurring_schedule_create_hash(p_tenant,p_entity,p_name,p_prefix,p_currency,p_frequency,p_next_due,p_ends_on,p_lines,p_reason) THEN RAISE EXCEPTION 'Invalid recurring schedule create command' USING ERRCODE='22023'; END IF;
 PERFORM refs_assert_scope(p_tenant,p_entity,'RECURRING.SCHEDULE.CREATE');PERFORM refs_assert_scope(p_tenant,p_entity,'RECURRING.SCHEDULE.VIEW'); INSERT INTO idempotency_receipt(tenant_id,operation_scope,idempotency_key,request_hash,status,actor_id) VALUES(p_tenant,'RECURRING_SCHEDULE_CREATE:'||p_entity,p_idempotency_key,p_request_hash,'IN_PROGRESS',actor) ON CONFLICT DO NOTHING;SELECT * INTO idem FROM idempotency_receipt WHERE tenant_id=p_tenant AND operation_scope='RECURRING_SCHEDULE_CREATE:'||p_entity AND idempotency_key=p_idempotency_key FOR UPDATE;IF idem.actor_id IS DISTINCT FROM actor OR idem.request_hash IS DISTINCT FROM p_request_hash THEN RAISE EXCEPTION 'Recurring schedule idempotency conflict' USING ERRCODE='23505';END IF;IF idem.status='SUCCEEDED' THEN RETURN idem.response_body||jsonb_build_object('idempotent',true);END IF;
 PERFORM refs_validate_recurring_schedule_lines(p_tenant,p_entity,p_lines);PERFORM pg_advisory_xact_lock(hashtextextended('RECURRING_SCHEDULE:'||p_entity::text||':'||p_name,0));INSERT INTO recurring_schedule(recurring_schedule_id,tenant_id,entity_id,name,journal_prefix,currency,frequency,next_due_on,ends_on,template_lines,created_by) VALUES(schedule,p_tenant,p_entity,p_name,p_prefix,p_currency,p_frequency,p_next_due,p_ends_on,p_lines,actor);payload:=refs_recurring_schedule_payload(p_tenant,p_entity,schedule)||jsonb_build_object('idempotent',false);INSERT INTO recurring_schedule_history(recurring_schedule_id,tenant_id,from_status,to_status,action,revision,actor_id,reason,event_hash) VALUES(schedule,p_tenant,NULL,'DRAFT','CREATE',0,actor,btrim(p_reason),refs_jsonb_hash(payload));INSERT INTO audit_event(tenant_id,entity_id,event_type,object_type,object_id,action,actor_id,actor_type,permission_used,request_id,correlation_id,idempotency_key,after_hash,reason,metadata) VALUES(p_tenant,p_entity,'RECURRING_SCHEDULE_CREATED','RECURRING_SCHEDULE',schedule,'CREATE',actor,'USER','RECURRING.SCHEDULE.CREATE',p_idempotency_key,p_idempotency_key,p_idempotency_key,refs_jsonb_hash(payload),btrim(p_reason),payload);INSERT INTO outbox_event(tenant_id,entity_id,aggregate_type,aggregate_id,event_type,payload,payload_hash) VALUES(p_tenant,p_entity,'RECURRING_SCHEDULE',schedule,'RECURRING_SCHEDULE_CREATED',payload,refs_jsonb_hash(payload));UPDATE idempotency_receipt SET status='SUCCEEDED',response_status=201,response_body=payload,completed_at=clock_timestamp() WHERE idempotency_receipt_id=idem.idempotency_receipt_id;RETURN payload;
END;$$;

CREATE FUNCTION refs_transition_recurring_schedule(p_tenant uuid,p_entity uuid,p_schedule uuid,p_action text,p_revision bigint,p_reason text,p_idempotency_key text,p_request_hash text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$ DECLARE actor text:=refs_current_actor();action text:=upper(p_action);idem idempotency_receipt;s recurring_schedule;next_status text;permission text;payload jsonb;BEGIN
 IF actor IS NULL OR action NOT IN('SUBMIT','APPROVE','PAUSE','RESUME') OR p_revision IS NULL OR p_revision<0 OR length(btrim(coalesce(p_reason,''))) NOT BETWEEN 8 AND 2000 OR length(coalesce(p_idempotency_key,'')) NOT BETWEEN 8 AND 200 OR p_request_hash IS DISTINCT FROM refs_recurring_schedule_transition_hash(p_tenant,p_entity,p_schedule,action,p_revision,p_reason) THEN RAISE EXCEPTION 'Invalid recurring schedule transition command' USING ERRCODE='22023'; END IF; permission:=CASE action WHEN 'SUBMIT' THEN 'RECURRING.SCHEDULE.SUBMIT' WHEN 'APPROVE' THEN 'RECURRING.SCHEDULE.APPROVE' ELSE 'RECURRING.SCHEDULE.MANAGE' END;PERFORM refs_assert_scope(p_tenant,p_entity,permission);PERFORM refs_assert_scope(p_tenant,p_entity,'RECURRING.SCHEDULE.VIEW');INSERT INTO idempotency_receipt(tenant_id,operation_scope,idempotency_key,request_hash,status,actor_id) VALUES(p_tenant,'RECURRING_SCHEDULE_'||action||':'||p_entity,p_idempotency_key,p_request_hash,'IN_PROGRESS',actor) ON CONFLICT DO NOTHING;SELECT * INTO idem FROM idempotency_receipt WHERE tenant_id=p_tenant AND operation_scope='RECURRING_SCHEDULE_'||action||':'||p_entity AND idempotency_key=p_idempotency_key FOR UPDATE;IF idem.actor_id IS DISTINCT FROM actor OR idem.request_hash IS DISTINCT FROM p_request_hash THEN RAISE EXCEPTION 'Recurring schedule idempotency conflict' USING ERRCODE='23505';END IF;IF idem.status='SUCCEEDED' THEN RETURN idem.response_body||jsonb_build_object('idempotent',true);END IF;
 SELECT * INTO s FROM recurring_schedule WHERE tenant_id=p_tenant AND entity_id=p_entity AND recurring_schedule_id=p_schedule FOR UPDATE;next_status:=CASE action WHEN 'SUBMIT' THEN 'PENDING_APPROVAL' WHEN 'APPROVE' THEN 'ACTIVE' WHEN 'PAUSE' THEN 'PAUSED' ELSE 'ACTIVE' END;IF NOT FOUND OR s.revision<>p_revision OR(action='SUBMIT' AND(s.status<>'DRAFT' OR actor=s.created_by))OR(action='APPROVE' AND(s.status<>'PENDING_APPROVAL' OR actor IN(s.created_by,s.submitted_by)))OR(action='PAUSE' AND(s.status<>'ACTIVE' OR actor=s.created_by))OR(action='RESUME' AND(s.status<>'PAUSED' OR actor=s.created_by)) THEN RAISE EXCEPTION 'Recurring schedule state, revision, or separation of duties conflict' USING ERRCODE='40001';END IF; INSERT INTO recurring_schedule_gate VALUES(pg_backend_pid(),txid_current(),p_tenant,p_schedule,action);UPDATE recurring_schedule SET status=next_status,revision=revision+1,submitted_by=CASE WHEN action='SUBMIT' THEN actor ELSE submitted_by END,submitted_at=CASE WHEN action='SUBMIT' THEN clock_timestamp() ELSE submitted_at END,approved_by=CASE WHEN action='APPROVE' THEN actor ELSE approved_by END,approved_at=CASE WHEN action='APPROVE' THEN clock_timestamp() ELSE approved_at END WHERE tenant_id=p_tenant AND recurring_schedule_id=p_schedule;DELETE FROM recurring_schedule_gate WHERE backend_pid=pg_backend_pid() AND transaction_id=txid_current() AND tenant_id=p_tenant AND recurring_schedule_id=p_schedule AND operation=action;payload:=refs_recurring_schedule_payload(p_tenant,p_entity,p_schedule)||jsonb_build_object('idempotent',false);INSERT INTO recurring_schedule_history(recurring_schedule_id,tenant_id,from_status,to_status,action,revision,actor_id,reason,event_hash) VALUES(p_schedule,p_tenant,s.status,next_status,action,s.revision+1,actor,btrim(p_reason),refs_jsonb_hash(payload));INSERT INTO audit_event(tenant_id,entity_id,event_type,object_type,object_id,action,actor_id,actor_type,permission_used,request_id,correlation_id,idempotency_key,after_hash,reason,metadata) VALUES(p_tenant,p_entity,'RECURRING_SCHEDULE_'||action,'RECURRING_SCHEDULE',p_schedule,action,actor,'USER',permission,p_idempotency_key,p_idempotency_key,p_idempotency_key,refs_jsonb_hash(payload),btrim(p_reason),payload);INSERT INTO outbox_event(tenant_id,entity_id,aggregate_type,aggregate_id,event_type,payload,payload_hash) VALUES(p_tenant,p_entity,'RECURRING_SCHEDULE',p_schedule,'RECURRING_SCHEDULE_'||action,payload,refs_jsonb_hash(payload));UPDATE idempotency_receipt SET status='SUCCEEDED',response_status=200,response_body=payload,completed_at=clock_timestamp() WHERE idempotency_receipt_id=idem.idempotency_receipt_id;RETURN payload;
END;$$;

CREATE FUNCTION refs_run_due_recurring_schedules(p_tenant uuid,p_entity uuid,p_as_of date,p_limit integer,p_idempotency_key text,p_request_hash text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$ DECLARE actor text:=refs_current_actor();idem idempotency_receipt;s recurring_schedule;r recurring_schedule_run;run_id uuid;period uuid;journal uuid;payload jsonb;rows jsonb:='[]'::jsonb;reason text:='Scheduler run due date';drafts integer:=0;failures integer:=0;attempted integer:=0;BEGIN
 IF actor IS NULL OR p_as_of IS NULL OR p_limit NOT BETWEEN 1 AND 100 OR length(coalesce(p_idempotency_key,'')) NOT BETWEEN 8 AND 200 OR p_request_hash IS DISTINCT FROM refs_recurring_schedule_run_hash(p_tenant,p_entity,p_as_of,p_limit) THEN RAISE EXCEPTION 'Invalid recurring schedule run command' USING ERRCODE='22023'; END IF;PERFORM refs_assert_scope(p_tenant,p_entity,'RECURRING.SCHEDULE.RUN');PERFORM refs_assert_scope(p_tenant,p_entity,'RECURRING.SCHEDULE.VIEW');INSERT INTO idempotency_receipt(tenant_id,operation_scope,idempotency_key,request_hash,status,actor_id) VALUES(p_tenant,'RECURRING_SCHEDULE_RUN:'||p_entity,p_idempotency_key,p_request_hash,'IN_PROGRESS',actor) ON CONFLICT DO NOTHING;SELECT * INTO idem FROM idempotency_receipt WHERE tenant_id=p_tenant AND operation_scope='RECURRING_SCHEDULE_RUN:'||p_entity AND idempotency_key=p_idempotency_key FOR UPDATE;IF idem.actor_id IS DISTINCT FROM actor OR idem.request_hash IS DISTINCT FROM p_request_hash THEN RAISE EXCEPTION 'Recurring scheduler idempotency conflict' USING ERRCODE='23505';END IF;IF idem.status='SUCCEEDED' THEN RETURN idem.response_body||jsonb_build_object('idempotent',true);END IF;
 FOR s IN SELECT * FROM recurring_schedule WHERE tenant_id=p_tenant AND entity_id=p_entity AND status='ACTIVE' AND next_due_on<=p_as_of AND(ends_on IS NULL OR next_due_on<=ends_on) ORDER BY next_due_on,recurring_schedule_id LIMIT p_limit FOR UPDATE SKIP LOCKED LOOP
  PERFORM pg_advisory_xact_lock(hashtextextended('RECURRING_SCHEDULE_RUN:'||s.recurring_schedule_id::text||':'||s.next_due_on::text,0));
  INSERT INTO recurring_schedule_run(tenant_id,entity_id,recurring_schedule_id,due_on,status) VALUES(p_tenant,p_entity,s.recurring_schedule_id,s.next_due_on,'RUNNING') ON CONFLICT(tenant_id,recurring_schedule_id,due_on) DO NOTHING RETURNING recurring_schedule_run_id INTO run_id;
  IF run_id IS NULL THEN SELECT * INTO r FROM recurring_schedule_run WHERE tenant_id=p_tenant AND recurring_schedule_id=s.recurring_schedule_id AND due_on=s.next_due_on FOR UPDATE;IF r.status='FAILED' THEN run_id:=r.recurring_schedule_run_id;INSERT INTO recurring_schedule_run_gate VALUES(pg_backend_pid(),txid_current(),p_tenant,run_id);UPDATE recurring_schedule_run SET status='RUNNING',attempt_count=attempt_count+1,failure_code=NULL,completed_at=NULL WHERE recurring_schedule_run_id=run_id;DELETE FROM recurring_schedule_run_gate WHERE backend_pid=pg_backend_pid() AND transaction_id=txid_current() AND tenant_id=p_tenant AND recurring_schedule_run_id=run_id;ELSE CONTINUE;END IF;END IF;
  attempted:=attempted+1; BEGIN
   SELECT period_id INTO period FROM accounting_period WHERE tenant_id=p_tenant AND entity_id=p_entity AND ledger_code='PRIMARY' AND status='OPEN' AND s.next_due_on BETWEEN starts_on AND ends_on FOR SHARE;IF period IS NULL THEN RAISE EXCEPTION 'No open period for due date' USING ERRCODE='23514';END IF;
   journal:=gen_random_uuid();INSERT INTO journal_entry(journal_entry_id,tenant_id,entity_id,period_id,journal_number,journal_type,status,journal_date,currency,description,created_by) VALUES(journal,p_tenant,p_entity,period,left(s.journal_prefix||'-'||replace(s.recurring_schedule_id::text,'-','')||'-'||to_char(s.next_due_on,'YYYYMMDD'),120),'AUTO','DRAFT',s.next_due_on,s.currency,'Recurring schedule: '||s.name,actor);
   INSERT INTO journal_line(tenant_id,entity_id,period_id,journal_entry_id,line_no,account_code,debit_amount,credit_amount,member_ref,description,dimensions) SELECT p_tenant,p_entity,period,journal,(x->>'lineNo')::integer,x->>'accountCode',(x->>'debitAmount')::numeric,(x->>'creditAmount')::numeric,NULLIF(x->>'memberRef',''),NULLIF(x->>'description',''),x->'dimensions' FROM jsonb_array_elements(s.template_lines) x;
   INSERT INTO recurring_schedule_run_gate VALUES(pg_backend_pid(),txid_current(),p_tenant,run_id);UPDATE recurring_schedule_run SET status='DRAFT_CREATED',journal_entry_id=journal,completed_at=clock_timestamp() WHERE recurring_schedule_run_id=run_id;DELETE FROM recurring_schedule_run_gate WHERE backend_pid=pg_backend_pid() AND transaction_id=txid_current() AND tenant_id=p_tenant AND recurring_schedule_run_id=run_id;
   INSERT INTO recurring_schedule_gate VALUES(pg_backend_pid(),txid_current(),p_tenant,s.recurring_schedule_id,'RUN');UPDATE recurring_schedule SET next_due_on=refs_recurring_schedule_next_due(next_due_on,frequency),last_run_at=clock_timestamp(),revision=revision+1 WHERE recurring_schedule_id=s.recurring_schedule_id;DELETE FROM recurring_schedule_gate WHERE backend_pid=pg_backend_pid() AND transaction_id=txid_current() AND tenant_id=p_tenant AND recurring_schedule_id=s.recurring_schedule_id AND operation='RUN';INSERT INTO recurring_schedule_history(recurring_schedule_id,tenant_id,from_status,to_status,action,revision,actor_id,reason,event_hash) VALUES(s.recurring_schedule_id,p_tenant,'ACTIVE','ACTIVE','RUN',s.revision+1,actor,reason,refs_jsonb_hash(jsonb_build_object('run_id',run_id,'journal_entry_id',journal,'status','DRAFT_CREATED')));INSERT INTO audit_event(tenant_id,entity_id,event_type,object_type,object_id,action,actor_id,actor_type,permission_used,request_id,correlation_id,idempotency_key,after_hash,reason,metadata) VALUES(p_tenant,p_entity,'RECURRING_SCHEDULE_DRAFT_CREATED','RECURRING_SCHEDULE_RUN',run_id,'RUN',actor,'USER','RECURRING.SCHEDULE.RUN',p_idempotency_key,p_idempotency_key,p_idempotency_key,refs_jsonb_hash(jsonb_build_object('journal_entry_id',journal,'status','DRAFT')),reason,jsonb_build_object('recurring_schedule_id',s.recurring_schedule_id,'journal_entry_id',journal,'journal_status','DRAFT'));INSERT INTO outbox_event(tenant_id,entity_id,aggregate_type,aggregate_id,event_type,payload,payload_hash) VALUES(p_tenant,p_entity,'RECURRING_SCHEDULE_RUN',run_id,'RECURRING_SCHEDULE_DRAFT_CREATED',jsonb_build_object('recurring_schedule_id',s.recurring_schedule_id,'journal_entry_id',journal,'journal_status','DRAFT'),refs_jsonb_hash(jsonb_build_object('recurring_schedule_id',s.recurring_schedule_id,'journal_entry_id',journal,'journal_status','DRAFT')));rows:=rows||jsonb_build_array(jsonb_build_object('recurring_schedule_run_id',run_id,'recurring_schedule_id',s.recurring_schedule_id,'due_on',s.next_due_on,'status','DRAFT_CREATED','attempt_count','1','journal_entry_id',journal,'failure_code',NULL));drafts:=drafts+1;
  EXCEPTION WHEN OTHERS THEN
   INSERT INTO recurring_schedule_run_gate VALUES(pg_backend_pid(),txid_current(),p_tenant,run_id);UPDATE recurring_schedule_run SET status='FAILED',failure_code='RECURRING_DRAFT_MATERIALIZATION_FAILED',completed_at=clock_timestamp() WHERE recurring_schedule_run_id=run_id;DELETE FROM recurring_schedule_run_gate WHERE backend_pid=pg_backend_pid() AND transaction_id=txid_current() AND tenant_id=p_tenant AND recurring_schedule_run_id=run_id;INSERT INTO recurring_schedule_exception(tenant_id,entity_id,recurring_schedule_run_id,exception_code,exception_hash) VALUES(p_tenant,p_entity,run_id,'RECURRING_DRAFT_MATERIALIZATION_FAILED',refs_jsonb_hash(jsonb_build_object('schedule_id',s.recurring_schedule_id,'due_on',s.next_due_on,'code','RECURRING_DRAFT_MATERIALIZATION_FAILED')));INSERT INTO audit_event(tenant_id,entity_id,event_type,object_type,object_id,action,actor_id,actor_type,permission_used,request_id,correlation_id,idempotency_key,after_hash,reason,metadata) VALUES(p_tenant,p_entity,'RECURRING_SCHEDULE_DRAFT_FAILED','RECURRING_SCHEDULE_RUN',run_id,'RUN',actor,'USER','RECURRING.SCHEDULE.RUN',p_idempotency_key,p_idempotency_key,p_idempotency_key,NULL,reason,jsonb_build_object('recurring_schedule_id',s.recurring_schedule_id,'failure_code','RECURRING_DRAFT_MATERIALIZATION_FAILED'));INSERT INTO outbox_event(tenant_id,entity_id,aggregate_type,aggregate_id,event_type,payload,payload_hash) VALUES(p_tenant,p_entity,'RECURRING_SCHEDULE_RUN',run_id,'RECURRING_SCHEDULE_DRAFT_FAILED',jsonb_build_object('recurring_schedule_id',s.recurring_schedule_id,'failure_code','RECURRING_DRAFT_MATERIALIZATION_FAILED'),refs_jsonb_hash(jsonb_build_object('recurring_schedule_id',s.recurring_schedule_id,'failure_code','RECURRING_DRAFT_MATERIALIZATION_FAILED')));rows:=rows||jsonb_build_array(jsonb_build_object('recurring_schedule_run_id',run_id,'recurring_schedule_id',s.recurring_schedule_id,'due_on',s.next_due_on,'status','FAILED','attempt_count',(SELECT attempt_count::text FROM recurring_schedule_run WHERE recurring_schedule_run_id=run_id),'journal_entry_id',NULL,'failure_code','RECURRING_DRAFT_MATERIALIZATION_FAILED'));failures:=failures+1;
  END;
 END LOOP;
 payload:=jsonb_build_object('schema_version','RECURRING_SCHEDULE_RUN_BATCH_V1','tenant_id',p_tenant,'entity_id',p_entity,'as_of_date',p_as_of,'attempted_count',attempted::text,'draft_created_count',drafts::text,'failed_count',failures::text,'runs',rows,'idempotent',false,'action_flags',jsonb_build_object('can_post',false));UPDATE idempotency_receipt SET status='SUCCEEDED',response_status=200,response_body=payload,completed_at=clock_timestamp() WHERE idempotency_receipt_id=idem.idempotency_receipt_id;RETURN payload;
END;$$;
CREATE FUNCTION refs_read_recurring_schedule(p_tenant uuid,p_entity uuid,p_schedule uuid) RETURNS jsonb LANGUAGE sql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$ SELECT refs_recurring_schedule_payload(p_tenant,p_entity,p_schedule) $$;
REVOKE ALL ON FUNCTION refs_recurring_schedule_next_due(date,text),refs_recurring_schedule_create_hash(uuid,uuid,text,text,text,text,date,date,jsonb,text),refs_recurring_schedule_transition_hash(uuid,uuid,uuid,text,bigint,text),refs_recurring_schedule_run_hash(uuid,uuid,date,integer),refs_recurring_schedule_payload(uuid,uuid,uuid),refs_validate_recurring_schedule_lines(uuid,uuid,jsonb),refs_create_recurring_schedule(uuid,uuid,text,text,text,text,date,date,jsonb,text,text,text),refs_transition_recurring_schedule(uuid,uuid,uuid,text,bigint,text,text,text),refs_run_due_recurring_schedules(uuid,uuid,date,integer,text,text),refs_read_recurring_schedule(uuid,uuid,uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION refs_recurring_schedule_create_hash(uuid,uuid,text,text,text,text,date,date,jsonb,text),refs_recurring_schedule_transition_hash(uuid,uuid,uuid,text,bigint,text),refs_recurring_schedule_run_hash(uuid,uuid,date,integer),refs_create_recurring_schedule(uuid,uuid,text,text,text,text,date,date,jsonb,text,text,text),refs_transition_recurring_schedule(uuid,uuid,uuid,text,bigint,text,text,text),refs_run_due_recurring_schedules(uuid,uuid,date,integer,text,text),refs_read_recurring_schedule(uuid,uuid,uuid) TO refs_app;
COMMIT;
