BEGIN;

CREATE OR REPLACE FUNCTION refs_read_unit_transfer_pair(p_tenant uuid,p_entity uuid,p_pair uuid) RETURNS jsonb LANGUAGE plpgsql STABLE SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE actor text:=refs_current_actor();p unit_transfer_pair;u unit_transfer_unit_control;source_status text;target_status text;source_revision bigint;target_revision bigint;source_created text;source_reviewed text;source_approved text;target_created text;target_reviewed text;target_approved text;elimination jsonb;
BEGIN
 PERFORM refs_assert_scope(p_tenant,p_entity,'REAL_ESTATE.UNIT_TRANSFER.VIEW');PERFORM refs_assert_scope(p_tenant,p_entity,'GL.JE.VIEW');SELECT * INTO p FROM unit_transfer_pair WHERE tenant_id=p_tenant AND unit_transfer_pair_id=p_pair AND p_entity IN(source_entity_id,target_entity_id);
 IF NOT FOUND THEN RAISE EXCEPTION 'Unit Transfer pair not found' USING ERRCODE='P0002';END IF;PERFORM refs_assert_scope(p_tenant,p.source_entity_id,'REAL_ESTATE.UNIT_TRANSFER.VIEW');PERFORM refs_assert_scope(p_tenant,p.target_entity_id,'REAL_ESTATE.UNIT_TRANSFER.VIEW');PERFORM refs_assert_scope(p_tenant,p.source_entity_id,'GL.JE.VIEW');PERFORM refs_assert_scope(p_tenant,p.target_entity_id,'GL.JE.VIEW');
 SELECT * INTO u FROM unit_transfer_unit_control WHERE tenant_id=p_tenant AND unit_control_id=p.unit_control_id;
 SELECT status::text,revision,created_by,reviewed_by,approved_by INTO source_status,source_revision,source_created,source_reviewed,source_approved FROM journal_entry WHERE tenant_id=p_tenant AND entity_id=p.source_entity_id AND journal_entry_id=p.source_journal_entry_id;SELECT status::text,revision,created_by,reviewed_by,approved_by INTO target_status,target_revision,target_created,target_reviewed,target_approved FROM journal_entry WHERE tenant_id=p_tenant AND entity_id=p.target_entity_id AND journal_entry_id=p.target_journal_entry_id;
 SELECT jsonb_build_object('elimination_basis_id',elimination_basis_id,'intercompany_profit',intercompany_profit::text,'evidence_hash',evidence_hash) INTO elimination FROM unit_transfer_elimination_basis WHERE tenant_id=p_tenant AND unit_transfer_pair_id=p.unit_transfer_pair_id;
 RETURN jsonb_build_object('schema_version','UNIT_TRANSFER_PAIR_V1','unit_transfer_pair_id',p.unit_transfer_pair_id,'unit_control_id',p.unit_control_id,'property_ref',u.property_ref,'current_owner_entity_id',u.current_owner_entity_id,'current_unit_version',u.version::text,'source_entity_id',p.source_entity_id,'target_entity_id',p.target_entity_id,'source_period_id',p.source_period_id,'target_period_id',p.target_period_id,'transfer_date',p.transfer_date,'currency',p.currency,'unit_ref',p.unit_ref,'carrying_amount',p.carrying_amount::text,'transfer_price',p.transfer_price::text,'source_carrying_account_codes',to_jsonb(p.source_carrying_account_codes),'source_cost_ledger_line_ids',to_jsonb(p.source_cost_ledger_line_ids),'source_cost_layers',p.source_cost_layers,'source_cost_basis_hash',p.source_cost_basis_hash,'source_document_id',p.source_document_id,'source_document_line_id',p.source_document_line_id,'source_document_version',p.source_document_version::text,'source_payload_hash',p.source_payload_hash,'source_line_hash',p.source_line_hash,'source_attachment_ids',to_jsonb(p.attachment_ids),'source_attachment_snapshot_hash',p.attachment_snapshot_hash,'target_attachment_ids',to_jsonb(p.target_attachment_ids),'target_attachment_snapshot_hash',p.target_attachment_snapshot_hash,'source_mapping_snapshot_id',p.source_mapping_snapshot_id,'source_mapping_snapshot_hash',p.source_mapping_snapshot_hash,'target_mapping_snapshot_id',p.target_mapping_snapshot_id,'target_mapping_snapshot_hash',p.target_mapping_snapshot_hash)
  || jsonb_build_object('source_due_from_account_code',p.source_due_from_account_code,'source_gain_account_code',p.source_gain_loss_account_code,'target_inventory_account_code',p.target_inventory_account_code,'target_due_to_account_code',p.target_due_to_account_code,'source_lifecycle_stage',p.source_lifecycle_stage,'target_lifecycle_stage',p.target_lifecycle_stage,'source_journal_entry_id',p.source_journal_entry_id,'source_journal_status',source_status,'source_journal_revision',source_revision::text,'target_journal_entry_id',p.target_journal_entry_id,'target_journal_status',target_status,'target_journal_revision',target_revision::text,'status',p.status,'revision',p.revision::text,'evidence_hash',p.evidence_hash,'elimination_basis',elimination,'reversal_history',COALESCE((SELECT jsonb_agg(refs_read_unit_transfer_reversal_pair(p_tenant,p_entity,p.unit_transfer_pair_id,r.unit_transfer_reversal_pair_id) ORDER BY r.created_at,r.unit_transfer_reversal_pair_id) FROM unit_transfer_reversal_pair r WHERE r.tenant_id=p_tenant AND r.original_unit_transfer_pair_id=p.unit_transfer_pair_id),'[]'::jsonb),'active_reversal',(SELECT refs_read_unit_transfer_reversal_pair(p_tenant,p_entity,p.unit_transfer_pair_id,r.unit_transfer_reversal_pair_id) FROM unit_transfer_reversal_pair r WHERE r.tenant_id=p_tenant AND r.original_unit_transfer_pair_id=p.unit_transfer_pair_id AND r.status NOT IN('POSTED_PAIR','CANCELLED_PAIR') ORDER BY r.created_at DESC,r.unit_transfer_reversal_pair_id DESC LIMIT 1),'created_by',p.created_by,'created_at',p.created_at,'completed_at',p.completed_at,'cancelled_by',p.cancelled_by,'cancelled_at',p.cancelled_at,'cancel_reason',p.cancel_reason)
  || jsonb_build_object('action_flags',jsonb_build_object('can_create_draft',false,'can_submit',p.status='DRAFT_PAIR' AND refs_entity_has_permission(p.source_entity_id,'REAL_ESTATE.UNIT_TRANSFER.SUBMIT') AND refs_entity_has_permission(p.target_entity_id,'REAL_ESTATE.UNIT_TRANSFER.SUBMIT') AND refs_entity_has_permission(p.source_entity_id,'GL.JE.SUBMIT') AND refs_entity_has_permission(p.target_entity_id,'GL.JE.SUBMIT'),'can_review',p.status='PENDING_REVIEW_PAIR' AND refs_entity_has_permission(p.source_entity_id,'REAL_ESTATE.UNIT_TRANSFER.REVIEW') AND refs_entity_has_permission(p.target_entity_id,'REAL_ESTATE.UNIT_TRANSFER.REVIEW') AND refs_entity_has_permission(p.source_entity_id,'GL.JE.REVIEW') AND refs_entity_has_permission(p.target_entity_id,'GL.JE.REVIEW') AND actor IS DISTINCT FROM source_created AND actor IS DISTINCT FROM target_created,'can_approve',p.status='PENDING_APPROVAL_PAIR' AND refs_entity_has_permission(p.source_entity_id,'REAL_ESTATE.UNIT_TRANSFER.APPROVE') AND refs_entity_has_permission(p.target_entity_id,'REAL_ESTATE.UNIT_TRANSFER.APPROVE') AND refs_entity_has_permission(p.source_entity_id,'GL.JE.APPROVE') AND refs_entity_has_permission(p.target_entity_id,'GL.JE.APPROVE') AND actor IS DISTINCT FROM source_created AND actor IS DISTINCT FROM source_reviewed AND actor IS DISTINCT FROM target_created AND actor IS DISTINCT FROM target_reviewed,'can_reject',p.status IN('PENDING_REVIEW_PAIR','PENDING_APPROVAL_PAIR') AND refs_entity_has_permission(p.source_entity_id,'REAL_ESTATE.UNIT_TRANSFER.REJECT') AND refs_entity_has_permission(p.target_entity_id,'REAL_ESTATE.UNIT_TRANSFER.REJECT') AND refs_entity_has_permission(p.source_entity_id,'GL.JE.REJECT') AND refs_entity_has_permission(p.target_entity_id,'GL.JE.REJECT') AND actor IS DISTINCT FROM source_created AND actor IS DISTINCT FROM target_created,'can_cancel',p.status='DRAFT_PAIR' AND source_status='DRAFT' AND target_status='DRAFT' AND refs_entity_has_permission(p.source_entity_id,'REAL_ESTATE.UNIT_TRANSFER.CANCEL') AND refs_entity_has_permission(p.target_entity_id,'REAL_ESTATE.UNIT_TRANSFER.CANCEL') AND actor IS DISTINCT FROM source_created AND actor IS DISTINCT FROM target_created,'can_reverse',refs_unit_transfer_can_reverse(p_tenant,p,u),'can_post',p.status='APPROVED_PAIR' AND refs_entity_has_permission(p.source_entity_id,'REAL_ESTATE.UNIT_TRANSFER.POST') AND refs_entity_has_permission(p.target_entity_id,'REAL_ESTATE.UNIT_TRANSFER.POST') AND refs_entity_has_permission(p.source_entity_id,'GL.JE.POST') AND refs_entity_has_permission(p.target_entity_id,'GL.JE.POST') AND actor IS DISTINCT FROM source_created AND actor IS DISTINCT FROM source_reviewed AND actor IS DISTINCT FROM source_approved AND actor IS DISTINCT FROM target_created AND actor IS DISTINCT FROM target_reviewed AND actor IS DISTINCT FROM target_approved));
END;$$;

COMMIT;
