BEGIN;

CREATE OR REPLACE FUNCTION refs_transition_cash_transfer(p_tenant uuid,p_entity uuid,p_transfer uuid,p_action text,p_expected_revision bigint,p_expected_journal_revision bigint,p_reason text,p_idempotency_key text,p_request_hash text) RETURNS jsonb
LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE actor text:=refs_current_actor();t cash_transfer;idem idempotency_receipt;j journal_entry;target text;permission text;child_hash text;child jsonb;payload jsonb;
BEGIN
 IF p_action NOT IN('SUBMIT','REVIEW','APPROVE') OR actor IS NULL OR p_expected_revision IS NULL OR p_expected_revision<0 OR p_expected_journal_revision IS NULL OR p_expected_journal_revision<0 OR length(coalesce(p_idempotency_key,'')) NOT BETWEEN 8 AND 200 OR p_request_hash IS DISTINCT FROM refs_cash_transfer_transition_hash(p_tenant,p_entity,p_transfer,p_action,p_expected_revision,p_expected_journal_revision,p_reason) THEN RAISE EXCEPTION 'Invalid Cash Transfer transition command' USING ERRCODE='22023'; END IF;
 permission:='CASH.TRANSFER.'||p_action;PERFORM refs_assert_scope(p_tenant,p_entity,permission);PERFORM refs_assert_scope(p_tenant,p_entity,'GL.JE.'||p_action);
 idem:=refs_reserve_idempotency(p_tenant,'CASH_TRANSFER_'||p_action||':'||p_entity,p_idempotency_key,p_request_hash,actor);
 IF idem.actor_id IS DISTINCT FROM actor OR idem.request_hash IS DISTINCT FROM p_request_hash THEN RAISE EXCEPTION 'Cash Transfer idempotency conflict' USING ERRCODE='23505'; END IF; IF idem.status='SUCCEEDED' THEN RETURN idem.response_body||jsonb_build_object('idempotent',true); END IF;
 SELECT * INTO t FROM cash_transfer WHERE tenant_id=p_tenant AND entity_id=p_entity AND cash_transfer_id=p_transfer FOR UPDATE; IF NOT FOUND THEN RAISE EXCEPTION 'Cash Transfer was not found' USING ERRCODE='P0002'; END IF;
 SELECT * INTO j FROM journal_entry WHERE tenant_id=p_tenant AND entity_id=p_entity AND journal_entry_id=t.journal_entry_id FOR UPDATE;
 target:=CASE p_action WHEN 'SUBMIT' THEN 'PENDING_REVIEW' WHEN 'REVIEW' THEN 'PENDING_APPROVAL' ELSE 'APPROVED' END;
 IF t.revision<>p_expected_revision OR j.revision<>p_expected_journal_revision OR (p_action='SUBMIT' AND t.status<>'DRAFT') OR (p_action='REVIEW' AND (t.status<>'PENDING_REVIEW' OR actor=t.created_by)) OR (p_action='APPROVE' AND (t.status<>'PENDING_APPROVAL' OR actor IN(t.created_by,t.reviewed_by))) THEN RAISE EXCEPTION 'Cash Transfer state, revision, or segregation-of-duties conflict' USING ERRCODE='40001'; END IF;
 IF refs_cash_transfer_attachment_snapshot(p_tenant,p_entity,t.attachment_ids) IS DISTINCT FROM t.attachment_snapshot_hash THEN RAISE EXCEPTION 'Cash Transfer attachment evidence changed' USING ERRCODE='40001'; END IF;
 INSERT INTO cash_transfer_internal_gate VALUES(pg_backend_pid(),txid_current(),p_tenant,p_transfer,'JOURNAL',t.journal_entry_id,target);
 child_hash:=refs_journal_transition_hash(p_tenant,p_entity,t.journal_entry_id,p_action,p_expected_journal_revision,NULLIF(btrim(p_reason),''));child:=refs_transition_journal(p_tenant,p_entity,t.journal_entry_id,p_action,p_expected_journal_revision,NULLIF(btrim(p_reason),''),'cash-transfer:'||p_transfer||':'||p_action||':'||p_idempotency_key,child_hash);
 INSERT INTO cash_transfer_internal_gate VALUES(pg_backend_pid(),txid_current(),p_tenant,p_transfer,'TRANSFER',p_transfer,target);
 UPDATE cash_transfer SET status=target,revision=revision+1,reviewed_by=CASE WHEN p_action='REVIEW' THEN actor ELSE reviewed_by END,reviewed_at=CASE WHEN p_action='REVIEW' THEN clock_timestamp() ELSE reviewed_at END,approved_by=CASE WHEN p_action='APPROVE' THEN actor ELSE approved_by END,approved_at=CASE WHEN p_action='APPROVE' THEN clock_timestamp() ELSE approved_at END WHERE tenant_id=p_tenant AND entity_id=p_entity AND cash_transfer_id=p_transfer;
 payload:=jsonb_build_object('cash_transfer_id',p_transfer,'journal',child,'status',target,'revision',p_expected_revision+1,'idempotent',false);
 INSERT INTO audit_event(tenant_id,entity_id,event_type,object_type,object_id,action,actor_id,actor_type,permission_used,request_id,correlation_id,idempotency_key,after_hash,reason,metadata) VALUES(p_tenant,p_entity,'CASH_TRANSFER_'||p_action,'CASH_TRANSFER',p_transfer,p_action,actor,'USER',permission,p_idempotency_key,p_idempotency_key,p_idempotency_key,refs_jsonb_hash(payload),NULLIF(btrim(p_reason),''),payload);
 INSERT INTO outbox_event(tenant_id,entity_id,aggregate_type,aggregate_id,event_type,payload,payload_hash) VALUES(p_tenant,p_entity,'CASH_TRANSFER',p_transfer,'CASH_TRANSFER_'||p_action,payload,refs_jsonb_hash(payload));
 PERFORM refs_complete_cash_transfer_idempotency(p_tenant,'CASH_TRANSFER_'||p_action||':'||p_entity,idem.idempotency_receipt_id,actor,200,payload); RETURN payload;
END;$$;


CREATE OR REPLACE FUNCTION refs_cancel_cash_transfer_hash(p_tenant uuid,p_entity uuid,p_transfer uuid,p_expected_revision bigint,p_expected_journal_revision bigint,p_reason text) RETURNS text LANGUAGE sql IMMUTABLE SET search_path=pg_catalog,public,pg_temp AS $$ SELECT refs_jsonb_hash(jsonb_build_object('schema_version','CASH_TRANSFER_CANCEL_V1','tenant_id',p_tenant,'entity_id',p_entity,'cash_transfer_id',p_transfer,'expected_revision',p_expected_revision,'expected_journal_revision',p_expected_journal_revision,'reason',btrim(p_reason))) $$;
CREATE OR REPLACE FUNCTION refs_cancel_cash_transfer(p_tenant uuid,p_entity uuid,p_transfer uuid,p_expected_revision bigint,p_expected_journal_revision bigint,p_reason text,p_idempotency_key text,p_request_hash text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE actor text:=refs_current_actor();t cash_transfer;idem idempotency_receipt;j journal_entry;child_hash text;child jsonb;payload jsonb;
BEGIN
 PERFORM refs_assert_scope(p_tenant,p_entity,'CASH.TRANSFER.CANCEL');IF actor IS NULL OR p_expected_revision IS NULL OR p_expected_journal_revision IS NULL OR length(btrim(coalesce(p_reason,''))) NOT BETWEEN 8 AND 2000 OR length(coalesce(p_idempotency_key,'')) NOT BETWEEN 8 AND 200 OR p_request_hash IS DISTINCT FROM refs_cancel_cash_transfer_hash(p_tenant,p_entity,p_transfer,p_expected_revision,p_expected_journal_revision,p_reason) THEN RAISE EXCEPTION 'Invalid Cash Transfer cancellation command' USING ERRCODE='22023'; END IF;
 idem:=refs_reserve_idempotency(p_tenant,'CASH_TRANSFER_CANCEL:'||p_entity,p_idempotency_key,p_request_hash,actor);IF idem.status='SUCCEEDED' THEN RETURN idem.response_body||jsonb_build_object('idempotent',true); END IF;
 SELECT * INTO t FROM cash_transfer WHERE tenant_id=p_tenant AND entity_id=p_entity AND cash_transfer_id=p_transfer FOR UPDATE;SELECT * INTO j FROM journal_entry WHERE tenant_id=p_tenant AND entity_id=p_entity AND journal_entry_id=t.journal_entry_id FOR UPDATE;
 IF t.cash_transfer_id IS NULL OR t.status IN('POSTED','CANCELLED') OR t.revision<>p_expected_revision OR j.revision<>p_expected_journal_revision OR actor=t.created_by THEN RAISE EXCEPTION 'Cash Transfer cancellation state or segregation-of-duties conflict' USING ERRCODE='40001'; END IF;
 IF j.status::text<>'DRAFT' THEN PERFORM refs_assert_scope(p_tenant,p_entity,'GL.JE.REJECT');INSERT INTO cash_transfer_internal_gate VALUES(pg_backend_pid(),txid_current(),p_tenant,p_transfer,'JOURNAL',t.journal_entry_id,'DRAFT');child_hash:=refs_journal_transition_hash(p_tenant,p_entity,t.journal_entry_id,'REJECT',p_expected_journal_revision,btrim(p_reason));child:=refs_transition_journal(p_tenant,p_entity,t.journal_entry_id,'REJECT',p_expected_journal_revision,btrim(p_reason),'cash-transfer:'||p_transfer||':CANCEL:'||p_idempotency_key,child_hash); ELSE child:=jsonb_build_object('journal_entry_id',t.journal_entry_id,'status','DRAFT','revision',j.revision); END IF;
 INSERT INTO cash_transfer_internal_gate VALUES(pg_backend_pid(),txid_current(),p_tenant,p_transfer,'TRANSFER',p_transfer,'CANCELLED');UPDATE cash_transfer SET status='CANCELLED',revision=revision+1,cancelled_by=actor,cancelled_at=clock_timestamp(),cancel_reason=btrim(p_reason) WHERE tenant_id=p_tenant AND entity_id=p_entity AND cash_transfer_id=p_transfer;
 payload:=jsonb_build_object('cash_transfer_id',p_transfer,'journal',child,'status','CANCELLED','revision',p_expected_revision+1,'idempotent',false);INSERT INTO audit_event(tenant_id,entity_id,event_type,object_type,object_id,action,actor_id,actor_type,permission_used,request_id,correlation_id,idempotency_key,after_hash,reason,metadata) VALUES(p_tenant,p_entity,'CASH_TRANSFER_CANCELLED','CASH_TRANSFER',p_transfer,'CANCEL',actor,'USER','CASH.TRANSFER.CANCEL',p_idempotency_key,p_idempotency_key,p_idempotency_key,refs_jsonb_hash(payload),btrim(p_reason),payload);INSERT INTO outbox_event(tenant_id,entity_id,aggregate_type,aggregate_id,event_type,payload,payload_hash) VALUES(p_tenant,p_entity,'CASH_TRANSFER',p_transfer,'CASH_TRANSFER_CANCELLED',payload,refs_jsonb_hash(payload));PERFORM refs_complete_cash_transfer_idempotency(p_tenant,'CASH_TRANSFER_CANCEL:'||p_entity,idem.idempotency_receipt_id,actor,200,payload);RETURN payload;
END;$$;



CREATE OR REPLACE FUNCTION refs_guard_cash_transfer_journal() RETURNS trigger LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$
DECLARE t cash_transfer;gate integer;
BEGIN
 IF TG_OP='DELETE' THEN IF EXISTS(SELECT 1 FROM cash_transfer x WHERE x.tenant_id=OLD.tenant_id AND x.entity_id=OLD.entity_id AND x.journal_entry_id=OLD.journal_entry_id) THEN RAISE EXCEPTION 'Cash Transfer journal is retained evidence' USING ERRCODE='55000'; END IF;RETURN OLD; END IF;
 SELECT * INTO t FROM cash_transfer WHERE tenant_id=NEW.tenant_id AND entity_id=NEW.entity_id AND journal_entry_id=NEW.journal_entry_id FOR UPDATE;IF NOT FOUND THEN RETURN NEW; END IF;
 IF NEW.status IS NOT DISTINCT FROM OLD.status OR (NEW.tenant_id,NEW.entity_id,NEW.period_id,NEW.journal_entry_id,NEW.journal_number,NEW.journal_type,NEW.journal_date,NEW.currency,NEW.description,NEW.created_by,NEW.created_at,NEW.reversal_of_id,NEW.reclass_of_id) IS DISTINCT FROM (OLD.tenant_id,OLD.entity_id,OLD.period_id,OLD.journal_entry_id,OLD.journal_number,OLD.journal_type,OLD.journal_date,OLD.currency,OLD.description,OLD.created_by,OLD.created_at,OLD.reversal_of_id,OLD.reclass_of_id) THEN RAISE EXCEPTION 'Cash Transfer journal header is immutable' USING ERRCODE='55000'; END IF;
 DELETE FROM cash_transfer_internal_gate WHERE backend_pid=pg_backend_pid() AND transaction_id=txid_current() AND tenant_id=NEW.tenant_id AND cash_transfer_id=t.cash_transfer_id AND resource_kind='JOURNAL' AND resource_id=NEW.journal_entry_id AND operation=NEW.status::text RETURNING 1 INTO gate;IF gate IS NULL THEN RAISE EXCEPTION 'Cash Transfer journal must transition through its aggregate' USING ERRCODE='0A000'; END IF;RETURN NEW;
END;$$;

REVOKE ALL ON FUNCTION refs_transition_cash_transfer(uuid,uuid,uuid,text,bigint,bigint,text,text,text),refs_cancel_cash_transfer_hash(uuid,uuid,uuid,bigint,bigint,text),refs_cancel_cash_transfer(uuid,uuid,uuid,bigint,bigint,text,text,text),refs_guard_cash_transfer_journal() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION refs_transition_cash_transfer(uuid,uuid,uuid,text,bigint,bigint,text,text,text),refs_cancel_cash_transfer_hash(uuid,uuid,uuid,bigint,bigint,text),refs_cancel_cash_transfer(uuid,uuid,uuid,bigint,bigint,text,text,text) TO refs_app;

COMMIT;
