BEGIN;

-- Command handlers build their own receipt payload. Public reads remain VIEW-gated.
CREATE OR REPLACE FUNCTION refs_recurring_schedule_command_payload(p_tenant uuid,p_entity uuid,p_schedule uuid) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$ DECLARE s recurring_schedule; actor text:=refs_current_actor(); BEGIN
 SELECT * INTO s FROM recurring_schedule WHERE tenant_id=p_tenant AND entity_id=p_entity AND recurring_schedule_id=p_schedule; IF NOT FOUND THEN RAISE EXCEPTION 'Recurring schedule not found' USING ERRCODE='P0002'; END IF;
 RETURN jsonb_build_object('schema_version','RECURRING_SCHEDULE_V1','recurring_schedule_id',s.recurring_schedule_id,'tenant_id',s.tenant_id,'entity_id',s.entity_id,'name',s.name,'journal_prefix',s.journal_prefix,'currency',s.currency,'frequency',s.frequency,'next_due_on',s.next_due_on,'ends_on',s.ends_on,'status',s.status,'revision',s.revision::text,'lines',(SELECT coalesce(jsonb_agg(jsonb_build_object('lineNo',(x->>'lineNo')::integer,'accountCode',x->>'accountCode','debitAmount',x->>'debitAmount','creditAmount',x->>'creditAmount','memberRef',x->'memberRef','description',x->'description','dimensions',x->'dimensions') ORDER BY (x->>'lineNo')::integer),'[]'::jsonb) FROM jsonb_array_elements(s.template_lines) x),'created_by',s.created_by,'created_at',s.created_at,'submitted_by',s.submitted_by,'submitted_at',s.submitted_at,'approved_by',s.approved_by,'approved_at',s.approved_at,'last_run_at',s.last_run_at,'history',(SELECT coalesce(jsonb_agg(jsonb_build_object('from_status',h.from_status,'to_status',h.to_status,'action',h.action,'revision',h.revision::text,'actor_id',h.actor_id,'reason',h.reason,'event_hash',h.event_hash,'created_at',h.created_at) ORDER BY h.revision),'[]'::jsonb) FROM recurring_schedule_history h WHERE h.tenant_id=p_tenant AND h.recurring_schedule_id=p_schedule),'action_flags',jsonb_build_object('can_submit',s.status='DRAFT' AND actor IS DISTINCT FROM s.created_by AND refs_entity_has_permission(p_entity,'RECURRING.SCHEDULE.SUBMIT'),'can_approve',s.status='PENDING_APPROVAL' AND actor IS DISTINCT FROM s.created_by AND actor IS DISTINCT FROM s.submitted_by AND refs_entity_has_permission(p_entity,'RECURRING.SCHEDULE.APPROVE'),'can_pause',s.status='ACTIVE' AND actor IS DISTINCT FROM s.created_by AND refs_entity_has_permission(p_entity,'RECURRING.SCHEDULE.MANAGE'),'can_resume',s.status='PAUSED' AND actor IS DISTINCT FROM s.created_by AND refs_entity_has_permission(p_entity,'RECURRING.SCHEDULE.MANAGE'),'can_run_due',s.status='ACTIVE' AND refs_entity_has_permission(p_entity,'RECURRING.SCHEDULE.RUN'),'can_post',false),'idempotent',false);
END;$$;

CREATE OR REPLACE FUNCTION refs_create_recurring_schedule(p_tenant uuid,p_entity uuid,p_name text,p_prefix text,p_currency text,p_frequency text,p_next_due date,p_ends_on date,p_lines jsonb,p_reason text,p_idempotency_key text,p_request_hash text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$ DECLARE actor text:=refs_current_actor();idem idempotency_receipt;schedule uuid:=gen_random_uuid();payload jsonb; BEGIN
 IF actor IS NULL OR p_name IS NULL OR p_name<>btrim(p_name) OR length(p_name) NOT BETWEEN 1 AND 160 OR p_prefix !~ '^[A-Za-z0-9._-]{1,40}$' OR p_currency !~ '^[A-Z]{3}$' OR p_frequency NOT IN('DAILY','WEEKLY','MONTHLY','QUARTERLY','ANNUAL') OR p_next_due IS NULL OR (p_ends_on IS NOT NULL AND p_ends_on<p_next_due) OR length(btrim(coalesce(p_reason,''))) NOT BETWEEN 8 AND 2000 OR length(coalesce(p_idempotency_key,'')) NOT BETWEEN 8 AND 200 OR p_request_hash IS DISTINCT FROM refs_recurring_schedule_create_hash(p_tenant,p_entity,p_name,p_prefix,p_currency,p_frequency,p_next_due,p_ends_on,p_lines,p_reason) THEN RAISE EXCEPTION 'Invalid recurring schedule create command' USING ERRCODE='22023'; END IF;
 PERFORM refs_assert_scope(p_tenant,p_entity,'RECURRING.SCHEDULE.CREATE'); INSERT INTO idempotency_receipt(tenant_id,operation_scope,idempotency_key,request_hash,status,actor_id) VALUES(p_tenant,'RECURRING_SCHEDULE_CREATE:'||p_entity,p_idempotency_key,p_request_hash,'IN_PROGRESS',actor) ON CONFLICT DO NOTHING;SELECT * INTO idem FROM idempotency_receipt WHERE tenant_id=p_tenant AND operation_scope='RECURRING_SCHEDULE_CREATE:'||p_entity AND idempotency_key=p_idempotency_key FOR UPDATE;IF idem.actor_id IS DISTINCT FROM actor OR idem.request_hash IS DISTINCT FROM p_request_hash THEN RAISE EXCEPTION 'Recurring schedule idempotency conflict' USING ERRCODE='23505';END IF;IF idem.status='SUCCEEDED' THEN RETURN idem.response_body||jsonb_build_object('idempotent',true);END IF;
 PERFORM refs_validate_recurring_schedule_lines(p_tenant,p_entity,p_lines);PERFORM pg_advisory_xact_lock(hashtextextended('RECURRING_SCHEDULE:'||p_entity::text||':'||p_name,0));INSERT INTO recurring_schedule(recurring_schedule_id,tenant_id,entity_id,name,journal_prefix,currency,frequency,next_due_on,ends_on,template_lines,created_by) VALUES(schedule,p_tenant,p_entity,p_name,p_prefix,p_currency,p_frequency,p_next_due,p_ends_on,p_lines,actor);payload:=refs_recurring_schedule_command_payload(p_tenant,p_entity,schedule)||jsonb_build_object('idempotent',false);INSERT INTO recurring_schedule_history(recurring_schedule_id,tenant_id,from_status,to_status,action,revision,actor_id,reason,event_hash) VALUES(schedule,p_tenant,NULL,'DRAFT','CREATE',0,actor,btrim(p_reason),refs_jsonb_hash(payload));INSERT INTO audit_event(tenant_id,entity_id,event_type,object_type,object_id,action,actor_id,actor_type,permission_used,request_id,correlation_id,idempotency_key,after_hash,reason,metadata) VALUES(p_tenant,p_entity,'RECURRING_SCHEDULE_CREATED','RECURRING_SCHEDULE',schedule,'CREATE',actor,'USER','RECURRING.SCHEDULE.CREATE',p_idempotency_key,p_idempotency_key,p_idempotency_key,refs_jsonb_hash(payload),btrim(p_reason),payload);INSERT INTO outbox_event(tenant_id,entity_id,aggregate_type,aggregate_id,event_type,payload,payload_hash) VALUES(p_tenant,p_entity,'RECURRING_SCHEDULE',schedule,'RECURRING_SCHEDULE_CREATED',payload,refs_jsonb_hash(payload));UPDATE idempotency_receipt SET status='SUCCEEDED',response_status=201,response_body=payload,completed_at=clock_timestamp() WHERE idempotency_receipt_id=idem.idempotency_receipt_id;RETURN payload;
END;$$;

CREATE OR REPLACE FUNCTION refs_transition_recurring_schedule(p_tenant uuid,p_entity uuid,p_schedule uuid,p_action text,p_revision bigint,p_reason text,p_idempotency_key text,p_request_hash text) RETURNS jsonb LANGUAGE plpgsql SECURITY DEFINER SET search_path=pg_catalog,public,pg_temp AS $$ DECLARE actor text:=refs_current_actor();action text:=upper(p_action);idem idempotency_receipt;s recurring_schedule;next_status text;permission text;payload jsonb;BEGIN
 IF actor IS NULL OR action NOT IN('SUBMIT','APPROVE','PAUSE','RESUME') OR p_revision IS NULL OR p_revision<0 OR length(btrim(coalesce(p_reason,''))) NOT BETWEEN 8 AND 2000 OR length(coalesce(p_idempotency_key,'')) NOT BETWEEN 8 AND 200 OR p_request_hash IS DISTINCT FROM refs_recurring_schedule_transition_hash(p_tenant,p_entity,p_schedule,action,p_revision,p_reason) THEN RAISE EXCEPTION 'Invalid recurring schedule transition command' USING ERRCODE='22023'; END IF; permission:=CASE action WHEN 'SUBMIT' THEN 'RECURRING.SCHEDULE.SUBMIT' WHEN 'APPROVE' THEN 'RECURRING.SCHEDULE.APPROVE' ELSE 'RECURRING.SCHEDULE.MANAGE' END;PERFORM refs_assert_scope(p_tenant,p_entity,permission);INSERT INTO idempotency_receipt(tenant_id,operation_scope,idempotency_key,request_hash,status,actor_id) VALUES(p_tenant,'RECURRING_SCHEDULE_'||action||':'||p_entity,p_idempotency_key,p_request_hash,'IN_PROGRESS',actor) ON CONFLICT DO NOTHING;SELECT * INTO idem FROM idempotency_receipt WHERE tenant_id=p_tenant AND operation_scope='RECURRING_SCHEDULE_'||action||':'||p_entity AND idempotency_key=p_idempotency_key FOR UPDATE;IF idem.actor_id IS DISTINCT FROM actor OR idem.request_hash IS DISTINCT FROM p_request_hash THEN RAISE EXCEPTION 'Recurring schedule idempotency conflict' USING ERRCODE='23505';END IF;IF idem.status='SUCCEEDED' THEN RETURN idem.response_body||jsonb_build_object('idempotent',true);END IF;
 SELECT * INTO s FROM recurring_schedule WHERE tenant_id=p_tenant AND entity_id=p_entity AND recurring_schedule_id=p_schedule FOR UPDATE;next_status:=CASE action WHEN 'SUBMIT' THEN 'PENDING_APPROVAL' WHEN 'APPROVE' THEN 'ACTIVE' WHEN 'PAUSE' THEN 'PAUSED' ELSE 'ACTIVE' END;IF NOT FOUND OR s.revision<>p_revision OR(action='SUBMIT' AND(s.status<>'DRAFT' OR actor=s.created_by))OR(action='APPROVE' AND(s.status<>'PENDING_APPROVAL' OR actor IN(s.created_by,s.submitted_by)))OR(action='PAUSE' AND(s.status<>'ACTIVE' OR actor=s.created_by))OR(action='RESUME' AND(s.status<>'PAUSED' OR actor=s.created_by)) THEN RAISE EXCEPTION 'Recurring schedule state, revision, or separation of duties conflict' USING ERRCODE='40001';END IF; INSERT INTO recurring_schedule_gate VALUES(pg_backend_pid(),txid_current(),p_tenant,p_schedule,action);UPDATE recurring_schedule SET status=next_status,revision=revision+1,submitted_by=CASE WHEN action='SUBMIT' THEN actor ELSE submitted_by END,submitted_at=CASE WHEN action='SUBMIT' THEN clock_timestamp() ELSE submitted_at END,approved_by=CASE WHEN action='APPROVE' THEN actor ELSE approved_by END,approved_at=CASE WHEN action='APPROVE' THEN clock_timestamp() ELSE approved_at END WHERE tenant_id=p_tenant AND recurring_schedule_id=p_schedule;DELETE FROM recurring_schedule_gate WHERE backend_pid=pg_backend_pid() AND transaction_id=txid_current() AND tenant_id=p_tenant AND recurring_schedule_id=p_schedule AND operation=action;payload:=refs_recurring_schedule_command_payload(p_tenant,p_entity,p_schedule)||jsonb_build_object('idempotent',false);INSERT INTO recurring_schedule_history(recurring_schedule_id,tenant_id,from_status,to_status,action,revision,actor_id,reason,event_hash) VALUES(p_schedule,p_tenant,s.status,next_status,action,s.revision+1,actor,btrim(p_reason),refs_jsonb_hash(payload));INSERT INTO audit_event(tenant_id,entity_id,event_type,object_type,object_id,action,actor_id,actor_type,permission_used,request_id,correlation_id,idempotency_key,after_hash,reason,metadata) VALUES(p_tenant,p_entity,'RECURRING_SCHEDULE_'||action,'RECURRING_SCHEDULE',p_schedule,action,actor,'USER',permission,p_idempotency_key,p_idempotency_key,p_idempotency_key,refs_jsonb_hash(payload),btrim(p_reason),payload);INSERT INTO outbox_event(tenant_id,entity_id,aggregate_type,aggregate_id,event_type,payload,payload_hash) VALUES(p_tenant,p_entity,'RECURRING_SCHEDULE',p_schedule,'RECURRING_SCHEDULE_'||action,payload,refs_jsonb_hash(payload));UPDATE idempotency_receipt SET status='SUCCEEDED',response_status=200,response_body=payload,completed_at=clock_timestamp() WHERE idempotency_receipt_id=idem.idempotency_receipt_id;RETURN payload;
END;$$;

REVOKE ALL ON FUNCTION refs_recurring_schedule_command_payload(uuid,uuid,uuid) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION refs_recurring_schedule_command_payload(uuid,uuid,uuid) TO refs_app;

COMMIT;
