import React,{useEffect,useMemo,useRef,useState} from 'react';
import {readAuthoritativeSourceDocumentDetail,refreshAuthoritativeSourceDocuments} from './accounting-api.js';
import {StateBlock} from './ui.jsx';

const failure=(result,fallback)=>result?.message||fallback;
const empty='Not retained';

const documentCounts=rows=>({
  documents:rows.length,
  linked:rows.filter(row=>row.posted_journal_entry_ids.length>0).length,
  unlinked:rows.filter(row=>row.posted_journal_entry_ids.length===0).length,
  sourceSystems:new Set(rows.map(row=>row.source_system)).size,
});

const displayDocument=row=>row.document_no||row.source_record_id||row.source_document_id;
const detailScope=detail=>[
  `Source ${detail.source_system}`,
  `module ${detail.source_module}`,
  `record ${detail.source_record_id}`,
  `version ${detail.source_version}`,
].join(' | ');

export function AuthoritativeSourceDocumentsWorkspace({config,fetcher=globalThis.fetch}){
  const [state,setState]=useState({phase:'LOADING',rows:[],error:null,detail:null});
  const [query,setQuery]=useState('');
  const [sourceSystem,setSourceSystem]=useState('ALL');
  const listScrollRef=useRef(null);
  const detailReturnRef=useRef(null);
  const load=async()=>{setState(current=>({...current,phase:'LOADING',error:null}));const result=await refreshAuthoritativeSourceDocuments({config,fetcher});if(!result.ok){setState({phase:'ERROR',rows:[],error:failure(result,'Source Document evidence could not be loaded.'),detail:null});return;}setState({phase:'READY',rows:result.rows,error:null,detail:null});};
  useEffect(()=>{void load();},[config,fetcher]);
  const rows=useMemo(()=>state.rows.filter(row=>{
    const needle=query.trim().toLowerCase();
    const search=!needle||[row.document_no,row.source_record_id,row.document_type,row.source_system,row.source_module,row.status,row.currency].filter(Boolean).some(value=>String(value).toLowerCase().includes(needle));
    return search&&(sourceSystem==='ALL'||row.source_system===sourceSystem);
  }),[state.rows,query,sourceSystem]);
  const sourceSystems=useMemo(()=>[...new Set(state.rows.map(row=>row.source_system))].sort(),[state.rows]);
  const counts=useMemo(()=>documentCounts(state.rows),[state.rows]);
  const open=async id=>{detailReturnRef.current={focusId:`authoritative-source-document-${id}`,pageY:globalThis.scrollY||0,tableX:listScrollRef.current?.scrollLeft||0,query,sourceSystem};setState(current=>({...current,phase:'DETAIL_LOADING',error:null}));const result=await readAuthoritativeSourceDocumentDetail({config,sourceDocumentId:id,fetcher});if(!result.ok){detailReturnRef.current=null;setState(current=>({...current,phase:'READY',error:failure(result,'Source Document detail could not be loaded.')}));return;}setState(current=>({...current,phase:'READY',detail:result.detail}));};
  const backToList=()=>{const context=detailReturnRef.current;setQuery(context?.query||'');setSourceSystem(context?.sourceSystem||'ALL');setState(current=>({...current,detail:null}));const restore=()=>{listScrollRef.current?.scrollTo?.({left:context?.tableX||0});globalThis.scrollTo?.(0,context?.pageY||0);globalThis.document?.getElementById(context?.focusId)?.focus?.({preventScroll:true});detailReturnRef.current=null;};if(typeof globalThis.requestAnimationFrame==='function')globalThis.requestAnimationFrame(restore);else setTimeout(restore,0);};
  if(state.phase==='LOADING')return <StateBlock tone="loading">Loading authoritative Source Document evidence…</StateBlock>;
  if(state.detail){const detail=state.detail;return <section className="full-bleed qbo-transaction-report authoritative-source-document-detail" aria-labelledby="source-document-detail-title">
    <div className="qbo-report-back"><button type="button" className="btn btn-sm btn-ghost" onClick={backToList}>Back to Source Documents</button><span>{detailScope(detail)}</span></div>
    <header className="gl-drill-head authoritative-source-detail-head"><div><div className="gl-drill-crumb">Source &amp; staging / immutable evidence</div><h1 id="source-document-detail-title">{displayDocument(detail)}</h1><div className="gl-drill-account">{detail.document_type} | {detail.accounting_date} | {detail.currency}</div></div><span className="badge badge-muted">{detail.status}</span></header>
    <section className="authoritative-source-trace" aria-label="Source Document evidence trace"><span>Source</span><b>{detail.source_system}</b><span>Document</span><b>{detail.document_type}</b><span>Journals</span><b>{detail.posted_journal_entry_ids.length}</b><span>Lines</span><b>{detail.source_line_count}</b></section>
    <div className="authoritative-document-detail-summary authoritative-source-detail-summary" aria-label="Source Document evidence summary"><span><i>Document ID</i><b>{detail.source_document_id}</b></span><span><i>Revision</i><b>{detail.source_document_revision}</b></span><span><i>Gross amount</i><b>{detail.gross_amount} {detail.currency}</b></span><span><i>Business date</i><b>{detail.business_date}</b></span></div>
    <p className="report-drill-hint">This page exposes only immutable metadata and retained line evidence returned by the authenticated Source Document API. It does not expose attachment content, raw provider payloads, or any create, edit, post, export, or synchronization action.</p>
    <section className="authoritative-source-metadata" aria-label="Immutable Source Document metadata"><h2>Evidence identity</h2><dl className="evidence-grid"><div><dt>Source module</dt><dd>{detail.source_module}</dd></div><div><dt>Source record</dt><dd>{detail.source_record_id}</dd></div><div><dt>Source version</dt><dd>{detail.source_version}</dd></div><div><dt>Payload hash</dt><dd>{detail.payload_hash}</dd></div><div><dt>Created</dt><dd>{detail.created_at}</dd></div><div><dt>Updated</dt><dd>{detail.updated_at}</dd></div></dl></section>
    <section className="authoritative-source-lines-panel" aria-labelledby="source-document-lines-title"><div className="card-head"><div><h2 id="source-document-lines-title">Retained source lines</h2><p className="muted sm">Line facts only; account and dimensional references remain exactly as supplied by the evidence API.</p></div><span className="badge badge-muted">{detail.lines.length} lines</span></div><div className="table-wrap authoritative-source-document-lines" role="region" tabIndex={0} aria-label="Source Document lines; scroll horizontally to view every column"><table className="tbl"><thead><tr><th>Line</th><th>Direction</th><th className="ta-r">Amount</th><th>Party</th><th>Bank account</th><th>Project / property / unit</th><th>Loan / cost code</th></tr></thead><tbody>{detail.lines.map(line=><tr key={line.source_document_line_id}><td><b>{line.line_no}</b><small className="authoritative-source-line-id">{line.source_line_id}</small></td><td><span className="badge badge-muted">{line.direction}</span></td><td className="ta-r">{line.amount}</td><td>{line.party_ref||empty}</td><td>{line.bank_account_ref||empty}</td><td>{[line.project_ref,line.property_ref,line.unit_ref].filter(Boolean).join(' · ')||empty}</td><td>{[line.loan_ref,line.cost_code_ref].filter(Boolean).join(' · ')||empty}</td></tr>)}</tbody></table></div></section>
  </section>;}
  if(state.phase==='ERROR')return <StateBlock tone="error">{state.error}</StateBlock>;
  return <section className="authoritative-page authoritative-source-documents-workspace" aria-labelledby="source-documents-title">
    <header className="authoritative-page-header"><div><p className="authoritative-eyebrow">Source &amp; staging | retained evidence</p><h1 id="source-documents-title">Source Documents</h1><p className="page-subtitle">Entity-scoped persisted evidence from the accounting API. Browser state, attachment bytes, provider requests, and WBS calls are not used.</p></div><div className="row-acts"><span className="authoritative-readonly-chip">Read only</span><button type="button" className="btn btn-sm" onClick={load}>Refresh evidence</button></div></header>
    <section className="authoritative-source-scope" aria-label="Authoritative Source Document scope"><div><span>Entity scope</span><b>{config.entityId}</b></div><div><span>Period scope</span><b>{config.periodId}</b></div><div><span>Evidence channel</span><b>Authenticated API read</b></div></section>
    <section className="qbo-toolgrid authoritative-source-summary" aria-label="Source Document summary"><span><i>In scope</i><b>{counts.documents}</b><small>Retained documents</small></span><span><i>Journal-linked</i><b>{counts.linked}</b><small>API journal references</small></span><span><i>Unlinked</i><b>{counts.unlinked}</b><small>No journal reference returned</small></span><span><i>Source systems</i><b>{counts.sourceSystems}</b><small>Distinct retained sources</small></span></section>
    <section className="authoritative-source-intro" aria-label="Source Document evidence boundary"><div><b>Evidence register</b><p>Open one retained document to inspect its exact revision, hash, and retained line facts.</p></div><ul><li><b>Included</b><span>Persisted metadata, source identity, and line references.</span></li><li><b>Excluded</b><span>Attachment bytes and raw provider payloads.</span></li><li><b>Read-only</b><span>No import, mapping, posting, or external call.</span></li></ul></section>
    <div className="filter-bar authoritative-list-filters authoritative-source-filters" role="search" aria-label="Source Document presentation filters"><label>Search <input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Document, source, type, or status"/></label><label>Source system <select value={sourceSystem} onChange={event=>setSourceSystem(event.target.value)}><option value="ALL">All sources</option>{sourceSystems.map(value=><option key={value} value={value}>{value}</option>)}</select></label><span className="result-count" aria-live="polite">{rows.length} matching source documents</span><button type="button" className="btn btn-sm btn-ghost" onClick={()=>{setQuery('');setSourceSystem('ALL');}}>Clear filters</button></div>
    {state.error&&<StateBlock tone="error">{state.error}</StateBlock>}{state.phase==='DETAIL_LOADING'&&<StateBlock tone="loading">Loading immutable source evidence…</StateBlock>}{state.rows.length===0?<StateBlock tone="empty" title="No source documents in this scope">No source documents were returned for this entity. A scoped empty response is not evidence that no source activity exists.</StateBlock>:rows.length===0?<StateBlock tone="empty" title="No source documents match these filters">Change a presentation filter to see retained Source Document facts. A filtered empty result is not evidence of zero activity.</StateBlock>:<div ref={listScrollRef} className="table-wrap authoritative-source-document-list" role="region" tabIndex={0} aria-label="Source Documents; scroll horizontally to view every column"><table className="tbl"><thead><tr><th>Document</th><th>Source</th><th>Type</th><th>Accounting date</th><th className="ta-r">Amount</th><th>Currency</th><th>Status</th><th>Journal evidence</th><th>Open</th></tr></thead><tbody>{rows.map(row=><tr key={row.source_document_id}><td><b>{displayDocument(row)}</b><small className="authoritative-source-row-id">Revision {row.source_document_revision} | {row.source_record_id}</small></td><td>{row.source_system}<small className="authoritative-source-row-id">{row.source_module}</small></td><td>{row.document_type}</td><td>{row.accounting_date}</td><td className="ta-r">{row.gross_amount}</td><td>{row.currency}</td><td><span className="badge badge-muted">{row.status}</span></td><td>{row.posted_journal_entry_ids.length?`${row.posted_journal_entry_ids.length} retained`:'Not returned'}</td><td><button id={`authoritative-source-document-${row.source_document_id}`} type="button" className="btn btn-sm" onClick={()=>void open(row.source_document_id)}>Open evidence</button></td></tr>)}</tbody></table></div>}
  </section>;
}
