import React,{useCallback,useEffect,useState}from'react';
import{refreshAuthoritativeAuditLog}from'./accounting-api.js';
import{StateBlock}from'./ui.jsx';

const blank=Object.freeze({eventType:'',actorId:'',objectType:'',from:'',to:''});
const shortHash=value=>value?`${value.slice(0,15)}…${value.slice(-8)}`:'—';

export function AuthoritativeAuditLogWorkspace({config,fetcher=globalThis.fetch}){
 const[filters,setFilters]=useState({...blank}),[applied,setApplied]=useState({...blank}),[cursor,setCursor]=useState(null),[state,setState]=useState({phase:'LOADING',page:null,error:null});
 const load=useCallback(async(nextCursor=cursor,nextFilters=applied)=>{setState(current=>({...current,phase:'LOADING',error:null}));const result=await refreshAuthoritativeAuditLog({config,fetcher,filters:nextFilters,cursor:nextCursor,limit:50});setState(result.ok?{phase:'READY',page:result.data,error:null}:{phase:'ERROR',page:null,error:result});},[config,fetcher,cursor,applied]);
 useEffect(()=>{load(null,blank);},[config,fetcher]);
 const apply=event=>{event.preventDefault();setApplied({...filters});setCursor(null);load(null,filters);},reset=()=>{setFilters({...blank});setApplied({...blank});setCursor(null);load(null,blank);};
 const page=state.page;
 return <section className="workspace-card" aria-labelledby="audit-log-title"><header className="workspace-title-row"><div><p className="eyebrow">IMMUTABLE EVIDENCE</p><h2 id="audit-log-title">Audit Log</h2><p>Review entity-scoped accounting events. Sensitive metadata and free-text reasons are excluded; request references are hashed.</p></div><button type="button" onClick={()=>load()} disabled={state.phase==='LOADING'}>Refresh</button></header>
 <form className="filter-row" aria-label="Audit Log filters" onSubmit={apply}><label>Event type<input value={filters.eventType} onChange={e=>setFilters({...filters,eventType:e.target.value})}/></label><label>Actor<input value={filters.actorId} onChange={e=>setFilters({...filters,actorId:e.target.value})}/></label><label>Object type<input value={filters.objectType} onChange={e=>setFilters({...filters,objectType:e.target.value})}/></label><label>From (UTC)<input type="datetime-local" value={filters.from?filters.from.slice(0,16):''} onChange={e=>setFilters({...filters,from:e.target.value?`${e.target.value}:00.000Z`:''})}/></label><label>To (UTC)<input type="datetime-local" value={filters.to?filters.to.slice(0,16):''} onChange={e=>setFilters({...filters,to:e.target.value?`${e.target.value}:00.000Z`:''})}/></label><button type="submit">Apply</button><button type="button" onClick={reset}>Reset</button></form>
 {state.phase==='LOADING'&&<StateBlock tone="loading">Reading immutable audit evidence...</StateBlock>}{state.error&&<StateBlock tone="danger">{state.error.code}: {state.error.message}</StateBlock>}
 {page&&<><p className="muted sm">{page.read_count} events on this page · {page.total_count} matching events. Empty results do not prove that no accounting activity occurred outside the selected entity or filters.</p>{page.events.length===0?<StateBlock>No audit events match this scope.</StateBlock>:<div className="table-wrap" tabIndex="0" aria-label="Audit event results"><table><thead><tr><th>Occurred (UTC)</th><th>Event</th><th>Action</th><th>Object</th><th>Actor</th><th>Permission</th><th>Evidence hashes</th></tr></thead><tbody>{page.events.map(row=><tr key={row.audit_event_id}><td>{row.occurred_at}</td><td>{row.event_type}</td><td>{row.action}</td><td>{row.object_type}<br/><span className="mono sm">{row.object_id}</span></td><td>{row.actor_id}<br/><span className="muted sm">{row.actor_type}</span></td><td>{row.permission_used||'—'}</td><td className="mono sm">request {shortHash(row.request_ref_hash)}<br/>correlation {shortHash(row.correlation_ref_hash)}<br/>before {shortHash(row.before_hash)}<br/>after {shortHash(row.after_hash)}</td></tr>)}</tbody></table></div>}{page.has_more&&<button type="button" onClick={()=>{setCursor(page.next_cursor);load(page.next_cursor,applied);}}>Next page</button>}</>}
 </section>;
}
