import React,{useCallback,useEffect,useState}from'react';
import{refreshAuthoritativeAccountingSettings,refreshAuthoritativeSettingHistory,refreshAccountingSettingsWorkflowEvidence,refreshAccountingSettingsWorkflowOptions,refreshAccountingSettingsWorkflowRegister,accountingSettingsWorkflowCommandIdempotencyKey,createAccountingSettingsWorkflow,transitionAccountingSettingsWorkflow,settingsWorkflowReason}from'./accounting-api.js';
import{StateBlock}from'./ui.jsx';
const labels={coa:'Chart of accounts',vendor_treatment:'Vendor treatment',project_property_cost_code:'Project, property & cost code',period_close_policy:'Period close',tax:'Tax',intercompany:'Intercompany',materiality:'Materiality',approval_thresholds:'Approval thresholds',report_mapping:'Report mapping',loan_capitalization_policy:'Loan capitalization'};
const historyFamilies={AI_ACCOUNTING_COA_V1:'Chart of accounts',AI_ACCOUNTING_VENDOR_TREATMENT_V1:'Vendor treatment',AI_ACCOUNTING_PROJECT_PROPERTY_COST_CODE_V1:'Project, property & cost code',AI_ACCOUNTING_PERIOD_CLOSE_POLICY_V1:'Period close',AI_ACCOUNTING_TAX_V1:'Tax',AI_ACCOUNTING_INTERCOMPANY_V1:'Intercompany',AI_ACCOUNTING_MATERIALITY_V1:'Materiality',AI_ACCOUNTING_APPROVAL_THRESHOLDS_V1:'Approval thresholds',AI_ACCOUNTING_REPORT_MAPPING_V1:'Report mapping',AI_ACCOUNTING_LOAN_CAPITALIZATION_POLICY_V1:'Loan capitalization'};
const shortHash=value=>`${value.slice(0,15)}…${value.slice(-8)}`;
export function WorkflowEvidence({row,record,onLoad=()=>{}}){
 const data=record?.data;
 return <details onToggle={event=>{if(event.currentTarget.open&&(!record||record.phase==='ERROR'))onLoad(row);}}><summary>Review exact evidence</summary>
  {!record&&<p className="muted sm">Open to load the ten selected immutable policy snapshots.</p>}{record?.phase==='LOADING'&&<StateBlock tone="loading">Reading selected policy evidence...</StateBlock>}{record?.error&&<><StateBlock tone="danger">{record.error.code}: {record.error.message}</StateBlock><button type="button" onClick={()=>onLoad(row)}>Retry evidence</button></>}
  {data&&<><p className="sm">Workflow <span className="mono">{data.workflow_id}</span><br/>Parent hash <span className="mono">{data.canonical_parent_hash}</span></p><div className="table-wrap" tabIndex="0" aria-label={`Selected policy evidence for workflow ${data.workflow_id}`}><table><thead><tr><th>Policy</th><th>Version</th><th>Status</th><th>Approved</th><th>Full snapshot reference</th><th>Policy body</th></tr></thead><tbody>{data.selected_child_snapshots.map(child=><tr key={child.key}><td>{labels[child.key]}</td><td>{child.version}</td><td>{child.status}</td><td>{child.approved_by}<br/><small>{child.approved_at}</small></td><td className="mono sm">ID {child.setting_snapshot_id}<br/>Hash {child.snapshot_hash}<br/>Effective {child.effective_from}{child.effective_to?` to ${child.effective_to}`:''}</td><td><details><summary>Inspect policy values</summary><pre>{JSON.stringify(child.snapshot.settings,null,2)}</pre></details></td></tr>)}</tbody></table></div><div className="table-wrap" tabIndex="0" aria-label={`Decision history for workflow ${data.workflow_id}`}><table><thead><tr><th>Revision</th><th>Decision</th><th>Actor and time</th><th>Reason</th><th>Hash chain</th></tr></thead><tbody>{row.history.map(event=><tr key={event.revision}><td>{event.revision}</td><td>{event.from_status||'Created'} → {event.to_status}</td><td>{event.actor_id}<br/><small>{event.created_at}</small></td><td>{event.reason}</td><td className="mono sm">Previous {event.previous_event_hash||'GENESIS'}<br/>Event {event.event_hash}</td></tr>)}</tbody></table></div></>}
 </details>;
}
export function AccountingPostingPolicy({policy}){return <article><span>Posting policy</span><strong>{policy.effective_allow_post?'Posting permitted':'Posting locked'}</strong><small>Cutoff {policy.cutoff_date}</small></article>;}
export function AuthoritativeAccountingSettingsWorkspace({config,fetcher=globalThis.fetch}){
 const[state,setState]=useState({phase:'LOADING',data:null,error:null}),[workflow,setWorkflow]=useState({phase:'LOADING',options:null,register:null,error:null}),[evidence,setEvidence]=useState({}),[selected,setSelected]=useState({}),[reason,setReason]=useState(''),[command,setCommand]=useState({phase:'IDLE',error:null}),[historyFamily,setHistoryFamily]=useState('AI_ACCOUNTING_PERIOD_CLOSE_POLICY_V1'),[history,setHistory]=useState({phase:'LOADING',data:null,error:null});
 const load=useCallback(async()=>{setState({phase:'LOADING',data:null,error:null});const result=await refreshAuthoritativeAccountingSettings({config,fetcher});setState(result.ok?{phase:'READY',data:result.data,error:null}:{phase:'ERROR',data:null,error:result});},[config,fetcher]);
 const loadWorkflow=useCallback(async()=>{setWorkflow(current=>({...current,phase:'LOADING',error:null}));const[options,register]=await Promise.all([refreshAccountingSettingsWorkflowOptions({config,fetcher}),refreshAccountingSettingsWorkflowRegister({config,fetcher})]);setWorkflow(options.ok&&register.ok?{phase:'READY',options:options.data,register:register.data,error:null}:{phase:'ERROR',options:options.ok?options.data:null,register:register.ok?register.data:null,error:options.ok?register:options});setSelected({});setEvidence({});},[config,fetcher]);
 const loadEvidence=useCallback(async row=>{const id=row.accounting_settings_workflow_id;setEvidence(current=>({...current,[id]:{phase:'LOADING',data:null,error:null}}));const result=await refreshAccountingSettingsWorkflowEvidence({config,workflowId:id,periodId:row.period_id,fetcher});setEvidence(current=>({...current,[id]:result.ok?{phase:'READY',data:result.data,error:null}:{phase:'ERROR',data:null,error:result}}));},[config,fetcher]);
 const loadHistory=useCallback(async(cursor=null,append=false)=>{setHistory(current=>({phase:'LOADING',data:append?current.data:null,error:null}));const result=await refreshAuthoritativeSettingHistory({config,fetcher,family:historyFamily,limit:25,cursor});setHistory(current=>result.ok?{phase:'READY',data:append&&current.data?{...result.data,items:[...current.data.items,...result.data.items]}:result.data,error:null}:{phase:'ERROR',data:append?current.data:null,error:result});},[config,fetcher,historyFamily]);
 useEffect(()=>{load();loadWorkflow();},[load,loadWorkflow]);useEffect(()=>{loadHistory();},[loadHistory]);
 const createDraft=async()=>{setCommand({phase:'SAVING',error:null});const idempotencyKey=await accountingSettingsWorkflowCommandIdempotencyKey({config,childSettingSnapshotIds:selected,action:'CREATE',reason}),result=await createAccountingSettingsWorkflow({config,options:workflow.options,childSettingSnapshotIds:selected,reason,idempotencyKey,fetcher});if(!result.ok){setCommand({phase:'ERROR',error:result});return;}setCommand({phase:'IDLE',error:null});setReason('');await loadWorkflow();};
 const transition=async(row,action)=>{setCommand({phase:'SAVING',error:null});const idempotencyKey=await accountingSettingsWorkflowCommandIdempotencyKey({config,workflow:row,action,reason}),result=await transitionAccountingSettingsWorkflow({config,workflow:row,action,reason,idempotencyKey,fetcher});if(!result.ok){setCommand({phase:'ERROR',error:result});return;}setCommand({phase:'IDLE',error:null});setReason('');await Promise.all([loadWorkflow(),action==='ACTIVATE'?load():Promise.resolve()]);};
 const data=state.data,historyData=history.data,options=workflow.options,register=workflow.register,completeSelection=options?.prerequisites.every(row=>row.approved_options.some(option=>option.setting_snapshot_id===selected[row.key]))===true;
 return <section className="workspace-card" aria-labelledby="accounting-settings-title"><header className="workspace-title-row"><div><p className="eyebrow">ACCOUNTING POLICY CONTROL</p><h2 id="accounting-settings-title">Accounting settings</h2><p>Review active policy evidence and route a new parent snapshot through independent Submit, Review, Approve, and Activate decisions.</p></div><button type="button" onClick={()=>{load();loadWorkflow();}} disabled={state.phase==='LOADING'||workflow.phase==='LOADING'}>Refresh</button></header>
 <section aria-labelledby="settings-workflow-title"><h3 id="settings-workflow-title">Settings snapshot workflow</h3><p className="muted sm">This workflow activates a parent snapshot from ten already approved policy families. Policy-family authoring is outside this screen. Replacement is forward-only; an already active snapshot for this period cannot be replaced.</p>
 {workflow.phase==='LOADING'&&<StateBlock tone="loading">Reading approved prerequisites and workflow evidence...</StateBlock>}{workflow.error&&<StateBlock tone="danger">{workflow.error.code}: {workflow.error.message}</StateBlock>}{command.error&&<StateBlock tone="danger">{command.error.code}: {command.error.message}</StateBlock>}
 {options&&<>{options.blockers.period_status!=='OPEN'&&<StateBlock tone="danger">The target period is {options.blockers.period_status}. Create and transition actions require an OPEN period.</StateBlock>}{options.blockers.same_period_activation_exists&&<StateBlock tone="danger">This period already has retained active settings. Select a later period for a forward replacement.</StateBlock>}{options.blockers.forward_only_conflict&&!options.blockers.same_period_activation_exists&&<StateBlock tone="danger">This target is not later than all retained settings history. Select a later period.</StateBlock>}{options.blockers.missing_approved_families.length>0&&<StateBlock tone="danger">Approved prerequisites missing: {options.blockers.missing_approved_families.join(', ')}. Approve those policy families before creating a Draft.</StateBlock>}{options.blockers.forward_legacy_parent_setting_snapshot_id&&<p className="muted sm">Activation will retire legacy parent <span className="mono">{options.blockers.forward_legacy_parent_setting_snapshot_id}</span> at this period start in the same transaction.</p>}
 <div className="form-grid">{options.prerequisites.map(row=><label key={row.key}>{labels[row.key]}<select value={selected[row.key]||''} onChange={event=>setSelected(current=>({...current,[row.key]:event.target.value}))}><option value="">Select an approved snapshot</option>{row.approved_options.map(option=><option key={option.setting_snapshot_id} value={option.setting_snapshot_id}>Version {option.version} · {shortHash(option.snapshot_hash)}</option>)}</select></label>)}</div><label>Decision reason<textarea value={reason} onChange={event=>setReason(event.target.value)} placeholder="Explain the accounting policy change and effective period"/></label><button type="button" onClick={createDraft} disabled={!options.action_flags.can_create_draft||!completeSelection||!settingsWorkflowReason(reason)||command.phase==='SAVING'}>Create settings Draft</button></>}
 {register&&<><h4>Retained workflows</h4><div className="table-wrap" tabIndex="0" aria-label="Accounting settings workflows"><table><thead><tr><th>Version</th><th>Period</th><th>Status</th><th>Revision</th><th>Evidence</th><th>Allowed action</th></tr></thead><tbody>{register.rows.map(row=>{const record=evidence[row.accounting_settings_workflow_id],reviewed=record?.phase==='READY';return <tr key={row.accounting_settings_workflow_id}><td>{row.version}</td><td>{row.canonical_parent_snapshot.period_code}<br/><small>{row.target_period_status}</small></td><td>{row.status}</td><td>{row.revision}</td><td><span className="mono sm">{row.canonical_parent_hash}</span><br/><small>{row.source_current?'Current approved references':'Blocked: source evidence changed'}</small><WorkflowEvidence row={row} record={record} onLoad={loadEvidence}/></td><td>{Object.entries({SUBMIT:row.action_flags.can_submit,REVIEW:row.action_flags.can_review,APPROVE:row.action_flags.can_approve,ACTIVATE:row.action_flags.can_activate}).filter(([,allowed])=>allowed).map(([action])=><button type="button" key={action} onClick={()=>transition(row,action)} disabled={!reviewed||!settingsWorkflowReason(reason)||command.phase==='SAVING'}>{action[0]+action.slice(1).toLowerCase()}</button>)}{Object.values(row.action_flags).some(Boolean)&&!reviewed&&<small>Review exact evidence before acting.</small>}{!Object.values(row.action_flags).some(Boolean)&&<span>None for current user</span>}</td></tr>;})}</tbody></table></div>{register.rows.length===0&&<p className="muted">No retained settings workflow exists for this company.</p>}</>}
 </section>
 {state.phase==='LOADING'&&<StateBlock tone="loading">Reading active accounting settings...</StateBlock>}{state.error&&<StateBlock tone="danger">{state.error.code}: {state.error.message}</StateBlock>}
 {data&&<><div className="summary-grid"><article><span>Period</span><strong>{data.scope.period_code}</strong><small>{data.scope.period_status} · {data.scope.period_start} to {data.scope.period_end}</small></article><article><span>Active snapshot</span><strong>Version {data.approval.settings_version}</strong><small>{data.approval.approved_by} · {data.approval.approved_at}</small></article><AccountingPostingPolicy policy={data.period_close_policy}/><article><span>Evidence hash</span><strong className="mono sm">{shortHash(data.approval.settings_hash)}</strong><small>Immutable approved settings</small></article></div>
 <h3>Period calendar</h3><div className="summary-grid"><article><span>Business calendar</span><strong>{data.period_close_policy.business_calendar}</strong></article><article><span>Non-business dates</span><strong>{data.period_close_policy.non_business_dates.length}</strong><small>{data.period_close_policy.non_business_dates.join(', ')||'None in this policy'}</small></article><article><span>Accrual cutoff</span><strong>{data.period_close_policy.accrual_cutoff_date}</strong></article><article><span>Prepaid boundary</span><strong>{data.period_close_policy.prepaid_boundary_date}</strong></article></div>
 <h3>Policy coverage</h3><div className="summary-grid"><article><span>Posting accounts</span><strong>{data.coverage.active_posting_account_count}</strong></article><article><span>Vendor rules</span><strong>{data.coverage.vendor_rule_count}</strong></article><article><span>Report mappings</span><strong>{data.coverage.report_mapping_count}</strong></article><article><span>Intercompany</span><strong>{data.coverage.intercompany_enabled?`${data.coverage.intercompany_counterparty_count} counterparties`:'Disabled'}</strong></article></div>
 <h3>Materiality</h3><div className="table-wrap" tabIndex="0" aria-label="Approved materiality thresholds"><table><thead><tr><th>Financial statements</th><th>Budget variance</th><th>Manual journal</th><th>Duplicate</th><th>Loan difference</th></tr></thead><tbody><tr><td>{data.materiality.financial_statement_amount} {data.materiality.currency}</td><td>{data.materiality.budget_variance_amount}</td><td>{data.materiality.manual_je_amount}</td><td>{data.materiality.duplicate_amount}</td><td>{data.materiality.loan_difference_amount}</td></tr></tbody></table></div>
 <h3>Approved policy families</h3><div className="table-wrap" tabIndex="0" aria-label="Approved policy families"><table><thead><tr><th>Policy</th><th>Version</th><th>Approved by</th><th>Approved at</th><th>Snapshot hash</th></tr></thead><tbody>{data.families.map(row=><tr key={row.family}><td>{historyFamilies[row.family]}</td><td>{row.version}</td><td>{row.approved_by}</td><td>{row.approved_at}</td><td className="mono sm">{shortHash(row.snapshot_hash)}</td></tr>)}</tbody></table></div></>}
 <section aria-labelledby="setting-history-title"><div className="workspace-title-row"><div><h3 id="setting-history-title">Setting history</h3><p className="muted sm">Approved and retired snapshots with direct retained reference counts. References do not prove business usage.</p></div><label>Policy family <select value={historyFamily} onChange={event=>setHistoryFamily(event.target.value)}>{Object.entries(historyFamilies).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label></div>{history.phase==='LOADING'&&!historyData&&<StateBlock tone="loading">Reading retained setting history...</StateBlock>}{history.error&&<StateBlock tone="danger">{history.error.code}: {history.error.message}</StateBlock>}{historyData&&<><div className="table-wrap" tabIndex="0" aria-label="Retained setting history"><table><thead><tr><th>Version</th><th>Status</th><th>Effective</th><th>Approved</th><th>Retained references</th><th>Snapshot hash</th></tr></thead><tbody>{historyData.items.map(row=><tr key={row.setting_snapshot_id}><td>{row.version}</td><td>{row.status}</td><td>{row.effective_from}{row.effective_to?` to ${row.effective_to}`:''}</td><td>{row.approved_by}<br/><small>{row.approved_at}</small></td><td>{row.reference_counts.total}<br/><small>{row.reference_counts.entity_period_bindings} settings bindings · {row.reference_counts.rule_evaluations} rule evaluations · {row.reference_counts.staging_items} staging items · {row.reference_counts.wbs_reviews} WBS reviews · {row.reference_counts.ai_evidence} AI evidence</small></td><td className="mono sm">{shortHash(row.snapshot_hash)}</td></tr>)}</tbody></table></div>{historyData.items.length===0&&<p className="muted">No approved or retired snapshots are retained for this family.</p>}{historyData.has_more&&<button type="button" onClick={()=>loadHistory(historyData.next_cursor,true)} disabled={history.phase==='LOADING'}>Load more history</button>}</>}</section>
 </section>;
}
