import React,{useEffect,useState} from 'react';
import {classifyAuthoritativeAiConstructionLoanLine,proposeAuthoritativeAiConstructionLoanEntry,refreshAuthoritativeAiConstructionLoanClassifications,refreshAuthoritativeAiConstructionLoanEntryProposals} from './accounting-api.js';
import {StateBlock} from './ui.jsx';

const types=['LOAN_DRAW','INTEREST_REVIEW','PRINCIPAL_REPAYMENT','LOAN_FEE_REVIEW','ESCROW_RESERVE'];
const treatments={LOAN_DRAW:['LOAN_DRAW_CASH','LOAN_DRAW_CWIP'],INTEREST_REVIEW:['CAPITALIZED_INTEREST','EXPENSED_INTEREST'],PRINCIPAL_REPAYMENT:['PRINCIPAL_REPAYMENT'],LOAN_FEE_REVIEW:['DEFERRED_LOAN_FEE','EXPENSED_LOAN_FEE'],ESCROW_RESERVE:['ESCROW_FUNDING','ESCROW_RELEASE']};
export function AuthoritativeConstructionLoanPanel({config,fetcher=globalThis.fetch}){
  const [state,setState]=useState({phase:'LOADING',rows:[],proposals:[],error:null}),[lineId,setLineId]=useState(''),[classification,setClassification]=useState(''),[command,setCommand]=useState({phase:'IDLE',message:''}),[selectedId,setSelectedId]=useState(''),[treatment,setTreatment]=useState(''),[debit,setDebit]=useState(''),[credit,setCredit]=useState(''),[projectRef,setProjectRef]=useState(''),[propertyRef,setPropertyRef]=useState(''),[reason,setReason]=useState('');
  const load=async()=>{const [result,proposalResult]=await Promise.all([refreshAuthoritativeAiConstructionLoanClassifications({config,fetcher}),refreshAuthoritativeAiConstructionLoanEntryProposals({config,fetcher})]);setState(result.ok&&proposalResult.ok?{phase:'READY',rows:result.rows,proposals:proposalResult.rows,error:null}:{phase:'BLOCKED',rows:[],proposals:[],error:result.ok?proposalResult:result});};
  useEffect(()=>{void load();},[config?.entityId]);
  const classify=async event=>{event.preventDefault();setCommand({phase:'SAVING',message:''});const result=await classifyAuthoritativeAiConstructionLoanLine({config,sourceDocumentLineId:lineId.trim(),expectedClassification:classification,idempotencyKey:`ai-construction-loan:${globalThis.crypto?.randomUUID?.()||Date.now()}`,fetcher});if(!result.ok){setCommand({phase:'ERROR',message:`${result.code}: ${result.message}`});return;}setCommand({phase:'SAVED',message:'The source-bound loan classification was retained for Controller review. No accounting action occurred.'});setLineId('');setClassification('');await load();};
  const selected=state.rows.find(row=>row.ai_construction_loan_classification_evidence_id===selectedId)||null;
  const propose=async event=>{event.preventDefault();if(!selected)return;setCommand({phase:'SAVING',message:''});const project=projectRef.trim()||null,property=propertyRef.trim()||null,memberTrace={project_ref:project,property_ref:property,allocation_basis:project||property?'SOURCE_DIMENSIONED':'ENTITY_ONLY'},result=await proposeAuthoritativeAiConstructionLoanEntry({config,evidence:selected,treatmentDecision:treatment,debitAccountCode:debit.trim(),creditAccountCode:credit.trim(),memberTrace,reason,idempotencyKey:`ai-construction-loan-entry:${globalThis.crypto?.randomUUID?.()||Date.now()}`,fetcher});if(!result.ok){setCommand({phase:'ERROR',message:`${result.code}: ${result.message}`});return;}setCommand({phase:'SAVED',message:'Balanced construction-loan entry evidence was retained. No Draft, review, approval, or posting action occurred.'});setSelectedId('');setTreatment('');setDebit('');setCredit('');setProjectRef('');setPropertyRef('');setReason('');await load();};
  return <section className="card" aria-label="Construction loan accounting classifications"><div className="card-head"><div><h2>Construction loan accounting</h2><p className="muted sm">The server reclassifies exact retained loan lines as draw, interest, principal, financing fee, or escrow/reserve. Policy-sensitive accounts remain human decisions.</p></div><span className="badge badge-muted">REVIEW EVIDENCE ONLY</span></div>
    {state.phase==='BLOCKED'?<StateBlock tone="blocked" title={state.error?.code||'LOAN_CLASSIFICATION_READ_BLOCKED'}>{state.error?.message} No cached or demonstration evidence is substituted.</StateBlock>:null}
    <form className="form-grid" onSubmit={classify}><label>Retained source line ID<input value={lineId} onChange={event=>setLineId(event.target.value)} placeholder="UUID from authoritative source detail" required/></label><label>Expected transaction nature<select value={classification} onChange={event=>setClassification(event.target.value)} required><option value="">Select classification</option>{types.map(type=><option key={type} value={type}>{type.replaceAll('_',' ')}</option>)}</select></label><div className="form-span"><button className="btn btn-primary" disabled={command.phase==='SAVING'||!lineId||!classification}>{command.phase==='SAVING'?'Verifying source...':'Verify and retain classification'}</button> <span className="muted sm">The database rejects any treatment that conflicts with retained description or cash direction.</span></div></form>
    {command.message?<StateBlock tone={command.phase==='ERROR'?'blocked':'success'} title={command.phase==='ERROR'?'Classification blocked':'Classification retained'}>{command.message}</StateBlock>:null}
    {state.phase==='READY'&&state.rows.length===0?<StateBlock tone="empty" title="No retained loan classifications">No authoritative construction-loan source line has been classified for this entity.</StateBlock>:null}
    {state.rows.length>0?<div className="table-wrap" role="region" tabIndex={0} aria-label="Retained construction loan classifications"><table className="tbl"><thead><tr><th>Loan / source</th><th>Classification</th><th>Proposed entry shape</th><th>Human inputs required</th><th>Evidence</th><th>Authority</th></tr></thead><tbody>{state.rows.map(row=><tr key={row.ai_construction_loan_classification_evidence_id}><td><b>{row.loan_ref}</b><div className="muted sm">{row.source_document_id}<br/>Line {row.source_document_line_id}</div></td><td><b>{row.classification.replaceAll('_',' ')}</b><div className="muted sm">{row.reason}<br/>{(row.confidence*100).toFixed(0)}% / {row.rule_id}</div></td><td>{row.entry_shape.map((line,index)=><div key={`${line.side}-${index}`}><b>{line.side}</b> {line.account_role.replaceAll('_',' ')}</div>)}</td><td>{row.required_human_fields.map(field=><div key={field}>{field.replaceAll('_',' ')}</div>)}</td><td><details><summary>Immutable hashes</summary><div className="mono sm">{row.classification_hash}<br/>{row.source_payload_hash}<br/>{row.source_line_hash}</div></details></td><td><span className="badge badge-muted">REVIEW REQUIRED</span><div className="muted sm">NO DRAFT / REVIEW / APPROVE / POST</div></td></tr>)}</tbody></table></div>:null}
    {state.rows.length>0?<><div className="card-head"><div><h3>Balanced suggested entry</h3><p className="muted sm">Select retained classification evidence. The server derives date, currency, amount, loan reference, rule, and source hashes; a human supplies only treatment, account mapping, and exact source dimensions.</p></div><span className="badge badge-muted">PROPOSAL ONLY</span></div><form className="form-grid" onSubmit={propose}><label>Classification evidence<select value={selectedId} onChange={event=>{setSelectedId(event.target.value);setTreatment('');}} required><option value="">Select retained evidence</option>{state.rows.map(row=><option key={row.ai_construction_loan_classification_evidence_id} value={row.ai_construction_loan_classification_evidence_id}>{row.loan_ref} / {row.classification}</option>)}</select></label><label>Accounting treatment<select value={treatment} onChange={event=>setTreatment(event.target.value)} required disabled={!selected}><option value="">Select treatment</option>{(treatments[selected?.classification]||[]).map(value=><option key={value} value={value}>{value.replaceAll('_',' ')}</option>)}</select></label><label>Debit account<input value={debit} onChange={event=>setDebit(event.target.value)} maxLength={64} required/></label><label>Credit account<input value={credit} onChange={event=>setCredit(event.target.value)} maxLength={64} required/></label><label>Project reference<input value={projectRef} onChange={event=>setProjectRef(event.target.value)} maxLength={128} placeholder="Blank only for entity-only source"/></label><label>Property reference<input value={propertyRef} onChange={event=>setPropertyRef(event.target.value)} maxLength={128} placeholder="Blank only for entity-only source"/></label><label className="form-span">Controller rationale<textarea value={reason} onChange={event=>setReason(event.target.value)} minLength={8} maxLength={2000} required/></label><div className="form-span"><button className="btn btn-primary" disabled={command.phase==='SAVING'||!selected||!treatment||!debit||!credit||reason.trim().length<8}>{command.phase==='SAVING'?'Retaining proposal...':'Retain balanced proposal'}</button> <span className="muted sm">Entity-only member trace is used only when both dimensions are blank; the database rejects any mismatch with retained source evidence.</span></div></form></>:null}
    {state.proposals.length>0?<div className="table-wrap" role="region" tabIndex={0} aria-label="Retained construction loan entry proposals"><table className="tbl"><thead><tr><th>Loan / date</th><th>Treatment</th><th>Balanced entry</th><th>Amount</th><th>Source evidence</th><th>Authority</th></tr></thead><tbody>{state.proposals.map(row=><tr key={row.ai_construction_loan_entry_proposal_id}><td><b>{row.loan_ref}</b><div className="muted sm">{row.journal_date}</div></td><td>{row.treatment_decision.replaceAll('_',' ')}</td><td><div><b>DR</b> {row.debit_account_code}</div><div><b>CR</b> {row.credit_account_code}</div></td><td>{row.currency} {row.amount}</td><td><details><summary>Exact source trace</summary><div className="mono sm">{row.source_document_id}<br/>{row.source_document_line_id}<br/>{row.classification_hash}<br/>{row.proposal_hash}</div></details></td><td><span className="badge badge-muted">PROPOSED</span><div className="muted sm">NO DRAFT / REVIEW / APPROVE / POST</div></td></tr>)}</tbody></table></div>:null}
  </section>;
}
