import React,{useEffect,useState} from 'react';
import {proposeAuthoritativeAiInvoiceAccrual,refreshAuthoritativeAiAccrualCandidates,refreshAuthoritativeAiInvoiceAccrualEvidence,refreshAuthoritativeAiInvoiceAccrualProposals} from './accounting-api.js';
import {AuthoritativeWorkspaceHeader,AuthoritativeWorkspaceView} from './authoritative-workbench-view.jsx';
import {StateBlock} from './ui.jsx';

const idle={phase:'LOADING',data:null,error:null};
const amount=(value,currency)=>{const number=Number(value);return Number.isFinite(number)?new Intl.NumberFormat('en-US',{style:'currency',currency}).format(number):String(value||'');};
const sourceLabel=trace=>`${trace.period_key} - ${trace.service_period_start} to ${trace.service_period_end}`;

export function AuthoritativeAccrualWorkspace({config,fetcher=globalThis.fetch}){
  const [state,setState]=useState(idle);
  const [invoice,setInvoice]=useState({phase:'LOADING',evidence:[],proposals:[],error:null});
  const [form,setForm]=useState({evidenceId:'',expenseAccountCode:'',liabilityAccountCode:'',allocationBasis:'ENTITY_ONLY',projectRef:'',propertyRef:'',reversalDecision:'NO_AUTOMATIC_REVERSAL',reversalDate:'',reason:''});
  const [submit,setSubmit]=useState({phase:'IDLE',message:''});
  const load=async()=>{setState(current=>({...current,phase:'LOADING',error:null}));setInvoice(current=>({...current,phase:'LOADING',error:null}));const [result,evidenceResult,proposalResult]=await Promise.all([refreshAuthoritativeAiAccrualCandidates({config,fetcher}),refreshAuthoritativeAiInvoiceAccrualEvidence({config,fetcher}),refreshAuthoritativeAiInvoiceAccrualProposals({config,fetcher})]);setState(result.ok?{phase:'READY',data:result.data,error:null}:{phase:'BLOCKED',data:null,error:result});setInvoice(evidenceResult.ok&&proposalResult.ok?{phase:'READY',evidence:evidenceResult.rows,proposals:proposalResult.rows,error:null}:{phase:'BLOCKED',evidence:[],proposals:[],error:evidenceResult.ok?proposalResult:evidenceResult});};
  useEffect(()=>{void load();},[config?.entityId,config?.periodId]);
  const candidates=state.data?.candidates||[];
  const proposedIds=new Set(invoice.proposals.map(row=>row.classification_evidence_id));
  const availableEvidence=invoice.evidence.filter(row=>!proposedIds.has(row.classification_evidence_id));
  const selectedEvidence=availableEvidence.find(row=>row.classification_evidence_id===form.evidenceId)||null;
  const change=event=>setForm(current=>({...current,[event.target.name]:event.target.value}));
  const propose=async event=>{event.preventDefault();if(!selectedEvidence)return;setSubmit({phase:'SAVING',message:''});const sourceDimensioned=form.allocationBasis==='SOURCE_DIMENSIONED',result=await proposeAuthoritativeAiInvoiceAccrual({config,evidence:selectedEvidence,expenseAccountCode:form.expenseAccountCode.trim(),liabilityAccountCode:form.liabilityAccountCode.trim(),memberTrace:{project_ref:sourceDimensioned?(form.projectRef.trim()||null):null,property_ref:sourceDimensioned?(form.propertyRef.trim()||null):null,allocation_basis:form.allocationBasis},reversalDecision:form.reversalDecision,reversalDate:form.reversalDate||null,reason:form.reason,idempotencyKey:`ai-invoice-accrual:${globalThis.crypto?.randomUUID?.()||Date.now()}`,fetcher});if(!result.ok){setSubmit({phase:'ERROR',message:`${result.code}: ${result.message}`});return;}setSubmit({phase:'SAVED',message:'The source-bound accrual proposal was retained. No Draft or posting action occurred.'});setForm(current=>({...current,evidenceId:'',expenseAccountCode:'',liabilityAccountCode:'',reason:''}));await load();};
  return <AuthoritativeWorkspaceView area="Accrual Center">
    <AuthoritativeWorkspaceHeader eyebrow="AUTHORITATIVE - AI ACCOUNTING" title="Accrual Center" description="Review recurring obligations supported by retained source evidence." status="REVIEW REQUIRED"/>
    <section className="report-workbench" aria-label="Authoritative accrual analysis">
      <div className="report-workbench-head"><div><b>Recurring accrual review candidates</b><div className="page-subtitle">Three closed periods; no current-period source.</div></div><button type="button" className="btn" disabled={state.phase==='LOADING'} onClick={load}>{state.phase==='LOADING'?'Refreshing...':'Refresh'}</button></div>
      <details className="authoritative-secondary-disclosure authoritative-control-requirements"><summary><span>Control requirements</span><span className="badge badge-muted">NO AUTO POST</span></summary><section><p className="muted sm">The API requires three exact consecutive closed-period source records and no current-period retained or posted source before it exposes a candidate.</p><div className="report-shelf" aria-label="Accrual authority boundary"><span className="report-shelf-chip report-shelf-chip-on">SIGNED SOURCE TRACE</span><span className="report-shelf-chip">DETERMINISTIC RULE</span><span className="report-shelf-chip">HUMAN REVIEW REQUIRED</span><span className="report-shelf-chip">NO DRAFT OR POST</span></div></section></details>
      {state.phase==='LOADING'&&<StateBlock tone="loading" title="Loading authoritative accrual analysis">Reading only the configured entity and accounting period from the accounting API.</StateBlock>}
      {state.phase==='BLOCKED'&&<StateBlock tone="blocked" title={state.error?.code||'AI_ACCRUAL_ANALYSIS_BLOCKED'}>{state.error?.message} No browser-stored, substitute, or demonstration candidates are shown.</StateBlock>}
      {state.phase==='READY'&&candidates.length===0&&<StateBlock tone="empty" title="No review-required accrual candidates">No recurring-obligation candidate met the complete evidence rule for this entity and period. This does not prove that all accruals are complete.</StateBlock>}
      {state.phase==='READY'&&candidates.length>0&&<section className="card" aria-label="Review-required accrual candidates"><div className="card-head"><div><h2>Human review queue</h2><p className="muted sm">Each candidate still needs an owner, due date, accrual basis, account mapping, member trace, and reversing-entry decision before any separate Draft workflow may be considered.</p></div><span className="badge badge-warning">{candidates.length} REVIEW REQUIRED</span></div><div className="table-wrap" role="region" tabIndex={0} aria-label="Accrual candidates; scroll horizontally to view every column"><table className="tbl"><thead><tr><th>Obligation</th><th>Current period</th><th>Historical basis</th><th>Required human fields</th><th>Source evidence</th><th>Authority</th></tr></thead><tbody>{candidates.map(candidate=><tr key={candidate.recurring_obligation_id}><td><b>{candidate.recurring_obligation_id}</b><div className="muted sm">{candidate.service_frequency} - {candidate.currency}</div></td><td><b>{candidate.period_key}</b><div className="muted sm">{candidate.rule_id.replaceAll('_',' ')}</div></td><td>{candidate.historical_amounts.map((value,index)=><div key={`${candidate.recurring_obligation_id}-${index}`}>{amount(value,candidate.currency)}</div>)}</td><td>{candidate.required_human_fields.map(field=><span key={field} className="badge badge-muted">{field.replaceAll('_',' ')}</span>)}</td><td><details><summary>Three retained source records</summary><ul className="muted sm">{candidate.prior_source_trace.map(trace=><li key={trace.source_document_line_id}><b>{sourceLabel(trace)}</b><br/>{trace.source_document_id}<br/>{trace.source_payload_hash}</li>)}</ul></details></td><td><span className="badge badge-muted">NO DRAFT OR POST</span><div className="muted sm">Review only</div></td></tr>)}</tbody></table></div></section>}
      <section className="card" aria-label="Invoice accrual proposals"><div className="card-head"><div><h2>Invoice service-period accrual proposals</h2><p className="muted sm">Retained invoice classifications that indicate prior-period service can be converted into an immutable accounting proposal. A human supplies the accounts, dimensions, reversal decision, and rationale.</p></div><span className="badge badge-warning">PROPOSAL ONLY</span></div>
        {invoice.phase==='LOADING'&&<StateBlock tone="loading" title="Loading retained invoice accrual evidence">Reading retained classifications and proposals from the authoritative API.</StateBlock>}
        {invoice.phase==='BLOCKED'&&<StateBlock tone="blocked" title={invoice.error?.code||'AI_INVOICE_ACCRUAL_BLOCKED'}>{invoice.error?.message} No local substitute is shown.</StateBlock>}
        {invoice.phase==='READY'&&<><form className="form-grid" onSubmit={propose} aria-label="Retain invoice accrual proposal"><label>Retained classification<select name="evidenceId" value={form.evidenceId} onChange={change} required><option value="">Select source-bound evidence</option>{availableEvidence.map(row=><option key={row.classification_evidence_id} value={row.classification_evidence_id}>{row.source_document_id} - {(row.confidence*100).toFixed(0)}%</option>)}</select></label><label>Expense account<input name="expenseAccountCode" value={form.expenseAccountCode} onChange={change} required/></label><label>Accrued liability account<input name="liabilityAccountCode" value={form.liabilityAccountCode} onChange={change} required/></label><label>Allocation basis<select name="allocationBasis" value={form.allocationBasis} onChange={change}><option value="ENTITY_ONLY">Entity only</option><option value="SOURCE_DIMENSIONED">Source dimensioned</option></select></label>{form.allocationBasis==='SOURCE_DIMENSIONED'&&<><label>Project reference<input name="projectRef" value={form.projectRef} onChange={change}/></label><label>Property reference<input name="propertyRef" value={form.propertyRef} onChange={change}/></label></>}<label>Reversal decision<select name="reversalDecision" value={form.reversalDecision} onChange={change}><option value="NO_AUTOMATIC_REVERSAL">No automatic reversal</option><option value="REVERSE_NEXT_OPEN_PERIOD">Reverse next open period</option></select></label>{form.reversalDecision==='REVERSE_NEXT_OPEN_PERIOD'&&<label>Reversal date<input type="date" name="reversalDate" value={form.reversalDate} onChange={change} required/></label>}<label className="form-span">Controller rationale<textarea name="reason" value={form.reason} onChange={change} minLength={8} maxLength={2000} required/></label><div className="form-span"><button type="submit" className="btn btn-primary" disabled={!selectedEvidence||submit.phase==='SAVING'}>{submit.phase==='SAVING'?'Retaining proposal...':'Retain accrual proposal'}</button> <span className="muted sm">No Draft, review, approval, or posting authority.</span></div></form>{submit.message&&<StateBlock tone={submit.phase==='ERROR'?'blocked':'success'} title={submit.phase==='ERROR'?'Proposal not retained':'Proposal retained'}>{submit.message}</StateBlock>}
        {invoice.proposals.length===0?<StateBlock tone="empty" title="No retained invoice accrual proposals">No source-bound invoice accrual proposal has been retained for this entity.</StateBlock>:<div className="table-wrap" role="region" tabIndex={0} aria-label="Retained invoice accrual proposals"><table className="tbl"><thead><tr><th>Source</th><th>Amount</th><th>Accounts</th><th>Reversal</th><th>Evidence</th><th>Authority</th></tr></thead><tbody>{invoice.proposals.map(row=><tr key={row.ai_invoice_accrual_proposal_id}><td><b>{row.source_document_id}</b><div className="muted sm">Line {row.source_document_line_id}</div></td><td>{amount(row.amount,row.currency)}<div className="muted sm">Confidence {(row.confidence*100).toFixed(0)}%</div></td><td>Dr {row.expense_account_code}<br/>Cr {row.liability_account_code}</td><td>{row.reversal_decision.replaceAll('_',' ')}{row.reversal_date&&<div>{row.reversal_date}</div>}</td><td><details><summary>Source hashes</summary><div className="muted sm">{row.classification_hash}<br/>{row.source_payload_hash}<br/>{row.source_line_hash}</div></details></td><td><span className="badge badge-muted">PROPOSED</span><div className="muted sm">NO DRAFT OR POST</div></td></tr>)}</tbody></table></div>}</>}
      </section>
    </section>
  </AuthoritativeWorkspaceView>;
}
