import React,{useEffect,useMemo,useRef,useState} from 'react';
import {refreshAuthoritativeAccountRegister,refreshAuthoritativeChartOfAccounts} from './accounting-api.js';
import {StateBlock} from './ui.jsx';
import {AuthoritativeAccountRegisterView,AuthoritativeChartOfAccountsView} from './authoritative-coa-view.jsx';

const PAGE_SIZES=Object.freeze([25,50,100]);
const fixedMoney=value=>typeof value==='string'&&/^-?[0-9]+\.[0-9]{4}$/.test(value)?value:'Not returned';
const dash=value=>value===null||value===undefined||value===''?'—':value;
export const authoritativeCoaScopeText=(scope,config)=>{
  const presentation=config?.scopePresentation||{};
  const entity=presentation.entityLabel||'Configured entity';
  const period=presentation.periodLabel||scope?.period_code||'Configured period';
  return `${entity} · ${period}`;
};
const evidenceScope=(scope,config)=><p className="authoritative-coa-scope" title={`Entity ID: ${scope?.entityId}; Period ID: ${scope?.periodId}; API amounts use fixed four-decimal strings.`}>{authoritativeCoaScopeText(scope,config)} · balances by currency</p>;
const ErrorBlock=({state,onRetry})=>state.phase==='ERROR'?<StateBlock tone="error" title={state.error?.code||'ACCOUNTING_API_READ_FAILED'} actions={<button type="button" className="btn btn-sm" onClick={onRetry}>Retry read</button>}>{state.error?.message}</StateBlock>:null;
export const authoritativeRangeLabel=({page,pageSize,total,itemLabel='rows'})=>total?`Showing ${itemLabel} ${page*pageSize+1} to ${Math.min((page+1)*pageSize,total)} of ${total}`:`No ${itemLabel}`;
const Pagination=({page,pageCount,pageSize,total,onChange,label,itemLabel='rows'})=><nav className="authoritative-coa-pagination" aria-label={label}><span>{authoritativeRangeLabel({page,pageSize,total,itemLabel})}</span><button type="button" className="btn btn-sm btn-ghost" disabled={page===0} onClick={()=>onChange(page-1)}>Previous</button><button type="button" className="btn btn-sm btn-ghost" disabled={!pageCount||page>=pageCount-1} onClick={()=>onChange(page+1)}>Next</button></nav>;
const PageSize=({value,onChange,label})=><label className="authoritative-coa-page-size"><span>{label}</span><select value={value} onChange={event=>onChange(Number(event.target.value))}>{PAGE_SIZES.map(size=><option key={size} value={size}>{size}</option>)}</select></label>;
const pageRows=(rows,page,size)=>rows.slice(page*size,(page+1)*size);
export const restoreAuthoritativeCoaReturnContext=(environment,config,context,{table,getTable,focusId}={})=>{if(context?.entityId!==config?.entityId||context?.periodId!==config?.periodId)return false;const restore=()=>{try{environment?.scrollTo?.({top:context.scrollY,behavior:'auto'});}catch{}try{(getTable?.()||table)?.scrollTo?.({left:context.tableX,behavior:'auto'});}catch{}try{environment?.document?.getElementById?.(focusId)?.focus?.();}catch{}};try{environment?.setTimeout?.(restore,0);}catch{restore();}return true;};

function Register({config,selection,onBack,fetcher}){
  const {accountCode,accountName,returnContext}=selection;
  const [state,setState]=useState({phase:'LOADING',rows:[],error:null});
  const [query,setQuery]=useState('');const [page,setPage]=useState(0);const [pageSize,setPageSize]=useState(25);
  const load=async()=>{setState(current=>({...current,phase:'LOADING',error:null}));const result=await refreshAuthoritativeAccountRegister({config,accountCode,fetcher});setState(result.ok?{phase:'READY',rows:result.rows,scope:result.scope,error:null}:{phase:'ERROR',rows:[],scope:null,error:result});};
  useEffect(()=>{void load();},[accountCode,config,fetcher]);
  const rows=useMemo(()=>state.rows.filter(row=>`${row.journal_date} ${row.journal_number} ${row.member_ref||''} ${row.description||''}`.toLowerCase().includes(query.trim().toLowerCase())),[state.rows,query]);
  const pageCount=Math.ceil(rows.length/pageSize);const currentPage=Math.min(page,Math.max(pageCount-1,0));const visibleRows=pageRows(rows,currentPage,pageSize);
  const currencies=useMemo(()=>[...new Set(state.rows.map(row=>row.currency))],[state.rows]);
  const restoreText=[returnContext.query&&`account filter “${returnContext.query}”`,returnContext.status!=='ALL'&&`${returnContext.status.toLowerCase()} accounts`,returnContext.currency!=='ALL'&&returnContext.currency,`page ${returnContext.page+1}`].filter(Boolean).join(' | ');
  return <AuthoritativeAccountRegisterView eyebrow="ACCOUNTING REGISTER" title={`${accountCode} — ${accountName}`} subtitle="POSTED activity for one account and period.">
    <div className="qbo-report-back authoritative-register-back"><button type="button" className="btn btn-sm btn-ghost" onClick={onBack}>Back to Chart of Accounts</button><span>Posted account activity</span></div>
    <div className="authoritative-register-scope" aria-label="Account register scope"><span><i>Account</i><b>{accountCode}</b></span><span><i>Company / period</i><b>{authoritativeCoaScopeText(state.scope||config,config)}</b></span><span><i>Currency</i><b>{currencies.length?currencies.join(', '):'Not available'}</b></span><span><i>Posted entries</i><b>{state.phase==='READY'?state.rows.length:'—'}</b></span></div>
    <details className="authoritative-return-context authoritative-register-return"><summary>Chart of Accounts filters retained</summary><span>{restoreText||'All accounts'}</span></details>
    <div className="authoritative-filter-bar authoritative-register-filter authoritative-ledger-toolbar"><label><span>Search</span><input value={query} onChange={event=>{setQuery(event.target.value);setPage(0);}} placeholder="Date, journal, member, or description"/></label><PageSize label="Rows per page" value={pageSize} onChange={size=>{setPageSize(size);setPage(0);}}/><span className="result-count" aria-live="polite"><b>{state.phase==='READY'?rows.length:'—'}</b> entries</span>{query&&<button type="button" className="btn btn-sm btn-ghost" onClick={()=>{setQuery('');setPage(0);}}>Clear filter</button>}<button type="button" className="btn btn-sm" disabled={state.phase==='LOADING'} onClick={load}>{state.phase==='LOADING'?'Loading…':'Refresh'}</button></div>
    {state.phase==='LOADING'&&<StateBlock tone="loading">Loading account activity…</StateBlock>}
    <ErrorBlock state={state} onRetry={load}/>
    {state.phase==='READY'&&!rows.length&&<StateBlock tone="empty" title={state.rows.length?'No entries match this filter':'No posted entries found'}>{state.rows.length?'Change or clear the filter.':'No posted entries were returned for this account and period. This does not describe activity outside the selected period.'}</StateBlock>}
    {state.phase==='READY'&&rows.length>0&&<><div className="table-wrap authoritative-register-table" tabIndex={0} aria-label="Account register; scroll horizontally to view every column"><table className="tbl"><thead><tr><th scope="col">Date</th><th scope="col">Journal</th><th scope="col">Member</th><th scope="col">Description</th><th scope="col">Currency</th><th scope="col" className="ta-r">Debit</th><th scope="col" className="ta-r">Credit</th><th scope="col" className="ta-r">Opening</th><th scope="col" className="ta-r">Running balance</th><th scope="col">Source documents</th></tr></thead><tbody>{visibleRows.map(row=><tr key={row.ledger_line_id}><td>{row.journal_date}</td><td><code>{row.journal_number}</code></td><td>{dash(row.member_ref)}</td><td>{dash(row.description)}</td><td>{row.currency}</td><td className="ta-r">{fixedMoney(row.debit_amount)}</td><td className="ta-r">{fixedMoney(row.credit_amount)}</td><td className="ta-r">{fixedMoney(row.opening_balance)}</td><td className="ta-r">{fixedMoney(row.running_balance)}</td><td>{row.source_document_ids.length?row.source_document_ids.map(id=><code key={id}>{id}</code>):'None'}</td></tr>)}</tbody></table></div><Pagination page={currentPage} pageCount={pageCount} pageSize={pageSize} total={rows.length} onChange={setPage} label="Account register pages" itemLabel="entries"/></>}
  </AuthoritativeAccountRegisterView>;
}

export function AuthoritativeChartOfAccountsWorkspace({config,fetcher=globalThis.fetch,environment=globalThis}){
  const [state,setState]=useState({phase:'LOADING',rows:[],error:null});
  const [query,setQuery]=useState('');const [status,setStatus]=useState('ALL');const [currency,setCurrency]=useState('ALL');const [page,setPage]=useState(0);const [pageSize,setPageSize]=useState(25);const [selection,setSelection]=useState(null);const openerRef=useRef(null);const tableRef=useRef(null);
  const load=async()=>{setState(current=>({...current,phase:'LOADING',error:null}));const result=await refreshAuthoritativeChartOfAccounts({config,fetcher});setState(result.ok?{phase:'READY',rows:result.rows,scope:result.scope,error:null}:{phase:'ERROR',rows:[],scope:null,error:result});};
  useEffect(()=>{void load();},[config,fetcher]);
  const currencies=useMemo(()=>[...new Set(state.rows.map(row=>row.currency).filter(Boolean))].sort(),[state.rows]);
  const rows=useMemo(()=>state.rows.filter(row=>{const matchesQuery=`${row.account_code} ${row.account_name}`.toLowerCase().includes(query.trim().toLowerCase());const matchesStatus=status==='ALL'||(status==='ACTIVE'?row.active:!row.active);const matchesCurrency=currency==='ALL'||row.currency===currency;return matchesQuery&&matchesStatus&&matchesCurrency;}),[state.rows,query,status,currency]);
  const pageCount=Math.ceil(rows.length/pageSize);const currentPage=Math.min(page,Math.max(pageCount-1,0));const visibleRows=pageRows(rows,currentPage,pageSize);
  const resetFilters=()=>{setQuery('');setStatus('ALL');setCurrency('ALL');setPage(0);};
  const openRegister=(row,index)=>{openerRef.current=`authoritative-coa-account-${row.account_code}-${row.currency||'none'}-${index}`;setSelection({accountCode:row.account_code,accountName:row.account_name,returnContext:{entityId:config.entityId,periodId:config.periodId,query,status,currency,page:currentPage,pageSize,scrollY:Number(environment?.scrollY)||0,tableX:Number(tableRef.current?.scrollLeft)||0}});};
  const closeRegister=()=>{const context=selection?.returnContext;setSelection(null);restoreAuthoritativeCoaReturnContext(environment,config,context,{getTable:()=>tableRef.current,focusId:openerRef.current});};
  if(selection)return <Register config={config} fetcher={fetcher} selection={selection} onBack={closeRegister}/>;
  return <AuthoritativeChartOfAccountsView eyebrow="GENERAL LEDGER | ACCOUNT MASTER" title="Chart of Accounts" subtitle="Review accounts and posted balances by currency.">
    <div className="authoritative-filter-bar authoritative-coa-filter authoritative-ledger-toolbar" aria-label="Chart of Accounts filters"><label><span>Search</span><input value={query} onChange={event=>{setQuery(event.target.value);setPage(0);}} placeholder="Account name or number"/></label><label><span>Status</span><select value={status} onChange={event=>{setStatus(event.target.value);setPage(0);}}><option value="ALL">All statuses</option><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></select></label><label><span>Currency</span><select value={currency} onChange={event=>{setCurrency(event.target.value);setPage(0);}}><option value="ALL">All currencies</option>{currencies.map(value=><option key={value} value={value}>{value}</option>)}</select></label><PageSize label="Rows per page" value={pageSize} onChange={size=>{setPageSize(size);setPage(0);}}/><span className="result-count" aria-live="polite"><b>{state.phase==='READY'?rows.length:'—'}</b> shown</span>{(query||status!=='ALL'||currency!=='ALL')&&<button type="button" className="btn btn-sm btn-ghost" onClick={resetFilters}>Clear filters</button>}<button type="button" className="btn btn-sm" disabled={state.phase==='LOADING'} onClick={load}>{state.phase==='LOADING'?'Loading…':'Refresh'}</button></div>
    {evidenceScope(state.scope||{entityId:config.entityId,periodId:config.periodId},config)}
    {state.phase==='LOADING'&&<StateBlock tone="loading">Loading accounts and posted balances…</StateBlock>}
    <ErrorBlock state={state} onRetry={load}/>
    {state.phase==='READY'&&!rows.length&&<StateBlock tone="empty" title={state.rows.length?'No accounts match these filters':'No accounts returned'}>{state.rows.length?'Change or clear the filters.':'No accounts were returned for this company and period.'}</StateBlock>}
    {state.phase==='READY'&&rows.length>0&&<><div ref={tableRef} className="table-wrap authoritative-coa-table" tabIndex={0} aria-label="Chart of Accounts; scroll horizontally to view every column"><table className="tbl"><thead><tr><th scope="col">Account</th><th scope="col">Name</th><th scope="col">Member rule</th><th scope="col">Status</th><th scope="col">Currency</th><th scope="col" className="ta-r">Opening</th><th scope="col" className="ta-r">Period debit</th><th scope="col" className="ta-r">Period credit</th><th scope="col" className="ta-r">Ending</th><th scope="col" className="ta-r">Posted lines</th><th scope="col">Details</th></tr></thead><tbody>{visibleRows.map((row,index)=><tr key={`${row.account_code}:${row.currency||'none'}:${index}`}><td><code>{row.account_code}</code></td><td>{row.account_name}</td><td>{row.requires_member?row.required_member_type||'Required':'None'}</td><td><span className={`authoritative-status ${row.active?'is-active':'is-inactive'}`}>{row.active?'Active':'Inactive'}</span></td><td>{row.currency||'Not available'}</td><td className="ta-r">{row.opening_balance===null?'—':fixedMoney(row.opening_balance)}</td><td className="ta-r">{row.period_debit===null?'—':fixedMoney(row.period_debit)}</td><td className="ta-r">{row.period_credit===null?'—':fixedMoney(row.period_credit)}</td><td className="ta-r">{row.ending_balance===null?'—':fixedMoney(row.ending_balance)}</td><td className="ta-r">{row.posted_ledger_line_count}</td><td><button id={`authoritative-coa-account-${row.account_code}-${row.currency||'none'}-${index}`} type="button" className="btn btn-sm" onClick={()=>openRegister(row,index)}>Open register</button></td></tr>)}</tbody></table></div><Pagination page={currentPage} pageCount={pageCount} pageSize={pageSize} total={rows.length} onChange={setPage} label="Chart of Accounts pages" itemLabel="accounts"/></>}
  </AuthoritativeChartOfAccountsView>;
}
