import React,{useEffect,useRef,useState} from 'react';
import {readAuthoritativeSourceDocumentDetail,refreshAuthoritativeSourceDocuments} from './accounting-api.js';
import {StateBlock} from './ui.jsx';

const failure=(result,fallback)=>result?.message||fallback;

export function AuthoritativeSourceDocumentsWorkspace({config,fetcher=globalThis.fetch}){
  const [state,setState]=useState({phase:'LOADING',rows:[],error:null,detail:null});
  const listScrollRef=useRef(null);
  const detailReturnRef=useRef(null);
  const load=async()=>{setState(current=>({...current,phase:'LOADING',error:null}));const result=await refreshAuthoritativeSourceDocuments({config,fetcher});if(!result.ok){setState({phase:'ERROR',rows:[],error:failure(result,'Source Document evidence could not be loaded.'),detail:null});return;}setState({phase:'READY',rows:result.rows,error:null,detail:null});};
  useEffect(()=>{void load();},[config,fetcher]);
  const open=async id=>{detailReturnRef.current={focusId:`authoritative-source-document-${id}`,pageY:globalThis.scrollY||0,tableX:listScrollRef.current?.scrollLeft||0};setState(current=>({...current,phase:'DETAIL_LOADING',error:null}));const result=await readAuthoritativeSourceDocumentDetail({config,sourceDocumentId:id,fetcher});if(!result.ok){detailReturnRef.current=null;setState(current=>({...current,phase:'READY',error:failure(result,'Source Document detail could not be loaded.')}));return;}setState(current=>({...current,phase:'READY',detail:result.detail}));};
  const backToList=()=>{const context=detailReturnRef.current;setState(current=>({...current,detail:null}));const restore=()=>{listScrollRef.current?.scrollTo?.({left:context?.tableX||0});globalThis.scrollTo?.(0,context?.pageY||0);globalThis.document?.getElementById(context?.focusId)?.focus?.({preventScroll:true});detailReturnRef.current=null;};if(typeof globalThis.requestAnimationFrame==='function')globalThis.requestAnimationFrame(restore);else setTimeout(restore,0);};
  if(state.phase==='LOADING')return <StateBlock tone="loading">Loading authoritative Source Document evidence…</StateBlock>;
  if(state.detail)return <section className="authoritative-page" aria-labelledby="source-document-detail-title"><header className="authoritative-page-header"><div><p className="authoritative-eyebrow">Authoritative source evidence</p><h1 id="source-document-detail-title">Source Document detail</h1><p className="page-subtitle">Persisted REFS metadata and line evidence only. Attachment content and provider payloads are not exposed here.</p></div><span className="badge badge-muted">READ ONLY</span></header><button type="button" className="btn btn-sm btn-ghost" onClick={backToList}>Back to Source Documents</button><dl className="authoritative-unavailable-scope"><div><dt>Document ID</dt><dd>{state.detail.source_document_id}</dd></div><div><dt>Revision</dt><dd>{state.detail.source_document_revision}</dd></div><div><dt>Status</dt><dd>{state.detail.status}</dd></div><div><dt>Payload hash</dt><dd>{state.detail.payload_hash}</dd></div></dl><div className="table-wrap authoritative-source-document-lines" role="region" tabIndex={0} aria-label="Source Document lines; scroll horizontally to view every column"><table><thead><tr><th>Line</th><th>Direction</th><th>Amount</th><th>Party</th><th>Account / dimension evidence</th></tr></thead><tbody>{state.detail.lines.map(line=><tr key={line.source_document_line_id}><td>{line.line_no}</td><td>{line.direction}</td><td>{line.amount}</td><td>{line.party_ref||'—'}</td><td>{[line.bank_account_ref,line.project_ref,line.property_ref,line.unit_ref,line.loan_ref,line.cost_code_ref].filter(Boolean).join(' · ')||'—'}</td></tr>)}</tbody></table></div></section>;
  if(state.phase==='ERROR')return <StateBlock tone="error">{state.error}</StateBlock>;
  return <section className="authoritative-page" aria-labelledby="source-documents-title"><header className="authoritative-page-header"><div><p className="authoritative-eyebrow">Authoritative source evidence</p><h1 id="source-documents-title">Source Documents</h1><p className="page-subtitle">Entity-scoped persisted evidence. No browser state, attachment bytes, provider request, or WBS call is used.</p></div><div className="row-acts"><span className="badge badge-muted">READ ONLY</span><button type="button" className="btn btn-sm" onClick={load}>Refresh evidence</button></div></header>{state.error&&<StateBlock tone="error">{state.error}</StateBlock>}{state.phase==='DETAIL_LOADING'&&<StateBlock tone="loading">Loading immutable source evidence…</StateBlock>}{state.rows.length===0?<StateBlock tone="empty">No source documents were returned for this entity.</StateBlock>:<div ref={listScrollRef} className="table-wrap authoritative-source-document-list" role="region" tabIndex={0} aria-label="Source Documents; scroll horizontally to view every column"><table><thead><tr><th>Document</th><th>Type</th><th>Accounting date</th><th>Amount</th><th>Currency</th><th>Status</th><th>Posted journals</th></tr></thead><tbody>{state.rows.map(row=><tr key={row.source_document_id}><td><button id={`authoritative-source-document-${row.source_document_id}`} type="button" className="btn btn-sm btn-ghost" onClick={()=>void open(row.source_document_id)}>{row.document_no||row.source_document_id}</button></td><td>{row.document_type}</td><td>{row.accounting_date}</td><td>{row.gross_amount}</td><td>{row.currency}</td><td>{row.status}</td><td>{row.posted_journal_entry_ids.length}</td></tr>)}</tbody></table></div>}</section>;
}
