import React,{useEffect,useRef,useState} from 'react';
import {refreshAuthoritativeAiAccountingAnalysisReports,refreshAuthoritativeAiAccountingAnalysisSummary,refreshAuthoritativeAiFindingActions,refreshAuthoritativeAiInvoiceAccountingClassifications,retainAuthoritativeAiInvoiceAccountingClassifications} from './accounting-api.js';
import {AuthoritativeWorkspaceHeader,AuthoritativeWorkspaceView} from './authoritative-workbench-view.jsx';
import {StateBlock} from './ui.jsx';

const empty={phase:'LOADING',rows:[],error:null};
const timestamp=value=>typeof value==='string'?value.replace('T',' ').replace(/\.\d{3}Z$/,' UTC'):value;

function ReadBoundary({state,loading,emptyTitle,emptyBody,children}){
  if(state.phase==='LOADING')return <StateBlock tone="loading" title={loading}>Reading retained entity-scoped analysis evidence.</StateBlock>;
  if(state.phase==='BLOCKED')return <StateBlock tone="blocked" title={state.error?.code||'AI_ANALYSIS_REPORT_BLOCKED'}>{state.error?.message} No browser, cached, or demonstration analysis is substituted.</StateBlock>;
  if(state.rows.length===0)return <StateBlock tone="empty" title={emptyTitle}>{emptyBody}</StateBlock>;
  return children;
}

export function AuthoritativeAccountingAnalysisReport({config,fetcher=globalThis.fetch,onNavigate}){
  const [summary,setSummary]=useState(empty),[reports,setReports]=useState(empty),[actions,setActions]=useState(empty),[classifications,setClassifications]=useState({...empty,counts:null,scanned:0});
  const [retention,setRetention]=useState({phase:'IDLE',receipt:null,error:null});
  const retentionKey=useRef(null);
  const load=async()=>{
    setSummary(current=>({...current,phase:'LOADING',error:null}));setReports(current=>({...current,phase:'LOADING',error:null}));setActions(current=>({...current,phase:'LOADING',error:null}));setClassifications(current=>({...current,phase:'LOADING',error:null}));
    const [summaryResult,reportResult,actionResult,classificationResult]=await Promise.all([refreshAuthoritativeAiAccountingAnalysisSummary({config,fetcher}),refreshAuthoritativeAiAccountingAnalysisReports({config,limit:12,fetcher}),refreshAuthoritativeAiFindingActions({config,fetcher}),refreshAuthoritativeAiInvoiceAccountingClassifications({config,limit:500,fetcher})]);
    setSummary(summaryResult.ok?{phase:'READY',rows:summaryResult.rows,error:null}:{phase:'BLOCKED',rows:[],error:summaryResult});
    setReports(reportResult.ok?{phase:'READY',rows:reportResult.rows,error:null}:{phase:'BLOCKED',rows:[],error:reportResult});
    setActions(actionResult.ok?{phase:'READY',rows:actionResult.rows,error:null}:{phase:'BLOCKED',rows:[],error:actionResult});
    setClassifications(classificationResult.ok?{phase:'READY',rows:classificationResult.data.results,error:null,counts:classificationResult.data.classification_counts,scanned:classificationResult.data.scanned_document_count}:{phase:'BLOCKED',rows:[],error:classificationResult,counts:null,scanned:0});
  };
  useEffect(()=>{void load();},[config?.entityId,config?.periodId]);
  useEffect(()=>{retentionKey.current=null;setRetention({phase:'IDLE',receipt:null,error:null});},[config?.entityId,config?.periodId]);
  const retain=async()=>{if(retention.phase==='SAVING')return;const randomId=globalThis.crypto?.randomUUID?.();if(!retentionKey.current&&randomId)retentionKey.current=`ai-invoice-classification:${config.entityId}:${config.periodId}:${randomId}`;if(!retentionKey.current){setRetention({phase:'BLOCKED',receipt:null,error:{message:'This browser cannot create a safe command identity.'}});return;}setRetention(current=>({...current,phase:'SAVING',error:null}));const result=await retainAuthoritativeAiInvoiceAccountingClassifications({config,limit:500,idempotencyKey:retentionKey.current,fetcher});setRetention(result.ok?{phase:'READY',receipt:result.data,error:null}:{phase:'BLOCKED',receipt:null,error:result});};
  const loading=[summary,reports,actions,classifications].some(state=>state.phase==='LOADING');
  const latest=reports.rows[0]||null;
  const openActions=actions.rows.filter(row=>row.status==='OPEN');
  return <AuthoritativeWorkspaceView area="Accounting Analysis Report">
    <AuthoritativeWorkspaceHeader eyebrow="AUTHORITATIVE - CONTROLLER ANALYSIS" title="Accounting Analysis Report" description="Retained AI controller memos, finding totals, and accountable follow-up for the configured entity. This report explains evidence; it never creates, reviews, approves, or posts accounting." status="READ ONLY"/>
    <section className="report-workbench" aria-label="Accounting analysis report evidence">
      <div className="report-workbench-head"><div><b>Controller review package</b><div className="page-subtitle">Every count and memo comes from an OIDC-authenticated no-store API read. Empty evidence is not treated as a clean close.</div></div><div className="btn-row"><button type="button" className="btn" disabled={loading} onClick={load}>{loading?'Refreshing report...':'Refresh report'}</button>{typeof onNavigate==='function'?<button type="button" className="btn" onClick={()=>onNavigate('ai-audit')}>Open AI Audit Center</button>:null}</div></div>
      <div className="report-shelf" aria-label="Accounting analysis authority boundary"><span className="report-shelf-chip report-shelf-chip-on">RETAINED REPORT</span><span className="report-shelf-chip">SOURCE-BOUND FINDINGS</span><span className="report-shelf-chip">HUMAN ACCOUNTABILITY</span><span className="report-shelf-chip">NO DRAFT</span><span className="report-shelf-chip">NO APPROVAL</span><span className="report-shelf-chip">NO POST</span></div>
      <section className="card" aria-label="Latest controller memo"><div className="card-head"><div><h2>Latest Controller memo</h2><p className="muted sm">The latest durable explanation receipt and its exact request hash.</p></div><span className="badge badge-muted">NO ACCOUNTING EFFECT</span></div><ReadBoundary state={reports} loading="Loading retained Controller memos" emptyTitle="No retained Controller memo" emptyBody="No completed AI accounting analysis receipt was returned. Run analysis from AI Audit Center after authoritative findings exist.">{latest?<><div className="kv-grid"><div><span>Risk</span><b>{latest.report.result.risk_level}</b></div><div><span>Completed</span><b>{timestamp(latest.completed_at)}</b></div><div><span>Model</span><b>{latest.report.model}</b></div><div><span>Actor</span><b>{latest.actor_id}</b></div><div><span>Trace</span><b className="mono sm">{latest.report.traceId}</b></div><div><span>Request hash</span><b className="mono sm">{latest.request_hash}</b></div></div><h3>{latest.report.result.headline}</h3><p>{latest.report.result.narrative}</p><div className="table-wrap" role="region" tabIndex={0} aria-label="Controller memo actions; scroll horizontally to view every column"><table className="tbl"><thead><tr><th>Category</th><th>Recommended human action</th><th>Finding evidence</th><th>Authority</th></tr></thead><tbody>{latest.report.result.controller_actions.map((action,index)=><tr key={`${action.category}:${index}`}><td><b>{action.category.replaceAll('_',' ')}</b></td><td>{action.action}</td><td>{action.finding_ids.map(id=><div className="mono sm" key={id}>{id}</div>)}</td><td><span className="badge badge-muted">READ ONLY</span></td></tr>)}</tbody></table></div></>:null}</ReadBoundary></section>
      <section className="card" aria-label="Open finding summary"><div className="card-head"><div><h2>Open finding summary</h2><p className="muted sm">Risk counts materialized from retained findings; categories not returned are unknown, not zero.</p></div><span className="badge badge-muted">SERVER MATERIALIZED</span></div><ReadBoundary state={summary} loading="Loading finding totals" emptyTitle="No open finding totals returned" emptyBody="The API returned no open finding categories. This does not prove accounting completeness."><div className="table-wrap" role="region" tabIndex={0} aria-label="Open AI finding totals; scroll horizontally to view every column"><table className="tbl"><thead><tr><th>Category</th><th>Total</th><th>High</th><th>Medium</th><th>Low</th><th>Latest evidence</th></tr></thead><tbody>{summary.rows.map(row=><tr key={row.category}><td><b>{row.category.replaceAll('_',' ')}</b></td><td>{row.total_findings}</td><td>{row.high_findings}</td><td>{row.medium_findings}</td><td>{row.low_findings}</td><td>{timestamp(row.latest_materialized_at)}</td></tr>)}</tbody></table></div></ReadBoundary></section>
      <section className="card" aria-label="Invoice accounting classifications"><div className="card-head"><div><h2>Invoice accounting classifications</h2><p className="muted sm">Provider-signed retained invoices classified for the configured accounting period. Capitalization is never inferred from a project reference alone.</p></div><div className="btn-row"><span className="badge badge-muted">{classifications.scanned} SOURCE DOCUMENTS SCANNED</span><button type="button" className="btn" disabled={classifications.phase!=='READY'||retention.phase==='SAVING'} onClick={retain}>{retention.phase==='SAVING'?'Retaining evidence...':'Retain classification evidence'}</button></div></div>{retention.phase==='READY'?<StateBlock tone="success" title="Classification evidence retained">{retention.receipt.inserted_count} immutable evidence rows appended; {retention.receipt.replayed_count} replayed. Audit and outbox records were committed atomically. No Draft, review, approval, or posting action occurred.</StateBlock>:retention.phase==='BLOCKED'?<StateBlock tone="blocked" title={retention.error?.code||'CLASSIFICATION_RETENTION_BLOCKED'}>{retention.error?.message}</StateBlock>:null}<ReadBoundary state={classifications} loading="Scanning retained invoice evidence" emptyTitle="No eligible retained invoices" emptyBody="No formally admitted payable line was returned for this entity and period; this is not evidence that no invoices exist."><>{classifications.counts?<div className="report-shelf" aria-label="Invoice classification totals">{Object.entries(classifications.counts).map(([name,count])=><span className="report-shelf-chip" key={name}>{name.replaceAll('_',' ')} {count}</span>)}</div>:null}<div className="table-wrap" role="region" tabIndex={0} aria-label="Invoice accounting classifications; scroll horizontally to view every column"><table className="tbl"><thead><tr><th>Treatment</th><th>Confidence</th><th>Accounting reason</th><th>Required human fields</th><th>Source trace</th><th>Authority</th></tr></thead><tbody>{classifications.rows.map(row=><tr key={row.source_document_line_id}><td><b>{row.classification.replaceAll('_',' ')}</b></td><td>{Math.round(row.confidence*100)}%</td><td>{row.reason}</td><td>{row.required_human_fields.join(', ')||'None'}</td><td><div className="mono sm">{row.source_document_id}</div><div className="mono sm">{row.source_payload_hash}</div></td><td><span className="badge badge-muted">NO ACCOUNTING EFFECT</span></td></tr>)}</tbody></table></div></></ReadBoundary></section>
      <section className="card" aria-label="Controller action list"><div className="card-head"><div><h2>Controller action list</h2><p className="muted sm">Human-owned due dates and immutable finding hashes. Resolution remains in AI Audit Center.</p></div><span className="badge badge-muted">{openActions.length} OPEN</span></div><ReadBoundary state={{...actions,rows:openActions}} loading="Loading Controller actions" emptyTitle="No open retained actions" emptyBody="No open assigned actions were returned. Unassigned findings may still exist in AI Audit Center."><div className="table-wrap" role="region" tabIndex={0} aria-label="Controller action list; scroll horizontally to view every column"><table className="tbl"><thead><tr><th>Owner</th><th>Due date</th><th>Finding</th><th>Finding hash</th><th>Assigned</th><th>Authority</th></tr></thead><tbody>{openActions.map(row=><tr key={row.ai_finding_action_id}><td><b>{row.owner}</b></td><td>{row.due_date}</td><td>{row.finding_kind.replaceAll('_',' ')}<div className="mono sm">{row.finding_id}</div></td><td className="mono sm">{row.finding_hash}</td><td>{timestamp(row.assigned_at)}<div className="muted sm">by {row.assigned_by}</div></td><td><span className="badge badge-muted">NO ACCOUNTING EFFECT</span></td></tr>)}</tbody></table></div></ReadBoundary></section>
    </section>
  </AuthoritativeWorkspaceView>;
}
