import React,{useEffect,useMemo,useState} from 'react';
import {createAuthoritativeInsuranceAmortizationDraft,refreshAuthoritativeInsurancePrepaidAmortization,refreshAuthoritativePrepaidRollforward,reviewAuthoritativeInsurancePrepaidAmortization} from './accounting-api.js';
import {AuthoritativeWorkspaceHeader,AuthoritativeWorkspaceView} from './authoritative-workbench-view.jsx';
import {StateBlock} from './ui.jsx';

const idle={phase:'LOADING',rows:[],error:null};
const shortHash=value=>typeof value==='string'?`${value.slice(0,16)}...${value.slice(-6)}`:'Unavailable';
const commandKey=prefix=>`${prefix}-${globalThis.crypto?.randomUUID?.()||Date.now()}`;
const badge=status=>status==='DRAFT_CREATED'?'badge badge-info':status==='INDEPENDENTLY_REVIEWED'?'badge badge-success':status==='READY_FOR_INDEPENDENT_REVIEW'?'badge badge-warning':'badge badge-danger';

export function AuthoritativeAmortizationWorkspace({config,fetcher=globalThis.fetch,onBack=()=>{}}){
  const [evidence,setEvidence]=useState(idle),[rollforward,setRollforward]=useState(idle),[selectedId,setSelectedId]=useState(null),[reason,setReason]=useState(''),[command,setCommand]=useState({phase:'IDLE',message:null});
  const load=async()=>{
    setEvidence(current=>({...current,phase:'LOADING',error:null}));setRollforward(current=>({...current,phase:'LOADING',error:null}));
    const [evidenceResult,rollforwardResult]=await Promise.all([refreshAuthoritativeInsurancePrepaidAmortization({config,fetcher}),refreshAuthoritativePrepaidRollforward({config,fetcher})]);
    setEvidence(evidenceResult.ok?{phase:'READY',rows:evidenceResult.rows,error:null}:{phase:'BLOCKED',rows:[],error:evidenceResult});
    setRollforward(rollforwardResult.ok?{phase:'READY',rows:rollforwardResult.rows,error:null}:{phase:'BLOCKED',rows:[],error:rollforwardResult});
    if(evidenceResult.ok)setSelectedId(current=>evidenceResult.rows.some(row=>row.ai_amortization_schedule_line_id===current)?current:evidenceResult.rows[0]?.ai_amortization_schedule_line_id||null);
  };
  useEffect(()=>{void load();},[config?.entityId,config?.periodId]);
  const selected=useMemo(()=>evidence.rows.find(row=>row.ai_amortization_schedule_line_id===selectedId)||null,[evidence.rows,selectedId]);
  const reasonValid=reason===reason.trim()&&reason.length>=8&&reason.length<=2000;
  const run=async action=>{
    if(!selected||!reasonValid)return;
    setCommand({phase:'RUNNING',message:null});
    const result=action==='REVIEW'
      ?await reviewAuthoritativeInsurancePrepaidAmortization({config,evidence:selected,reason,idempotencyKey:commandKey('insurance-review'),fetcher})
      :await createAuthoritativeInsuranceAmortizationDraft({config,evidence:selected,reason,idempotencyKey:commandKey('insurance-draft'),fetcher});
    if(!result.ok){setCommand({phase:'BLOCKED',message:`${result.code}: ${result.message}`});return;}
    setCommand({phase:'DONE',message:action==='REVIEW'?'Independent review evidence was retained. Refreshing server state.':'Monthly AUTO Journal Entry was created in Draft. It was not submitted, approved, or posted.'});setReason('');await load();
  };
  const loading=evidence.phase==='LOADING'||rollforward.phase==='LOADING';
  return <AuthoritativeWorkspaceView area="Amortization Center">
    <AuthoritativeWorkspaceHeader eyebrow="AUTHORITATIVE - PREPAID CONTROL" title="Amortization Center" description="Signed Insurance source, immutable schedule proposal, independent review, monthly AUTO Draft, and posted prepaid rollforward. AI proposals remain proposals until a permitted controller performs the explicit review." status="CONTROLLED WORKFLOW"/>
    <section className="report-workbench" aria-label="Insurance prepaid amortization workflow">
      <div className="report-workbench-head"><div><b>Entity and period scoped evidence</b><div className="page-subtitle">Entity {config.entityId}; period {config.periodId}. Every ID, source version, hash, and MONEY4 amount is returned by the authenticated accounting API.</div></div><div className="row-acts"><button type="button" className="btn" onClick={onBack}>Back to Overview</button><button type="button" className="btn" onClick={load} disabled={loading}>{loading?'Refreshing...':'Refresh authority'}</button></div></div>
      <div className="report-shelf" aria-label="Amortization control boundaries"><span className="report-shelf-chip report-shelf-chip-on">SIGNED SOURCE</span><span className="report-shelf-chip">INDEPENDENT REVIEW</span><span className="report-shelf-chip">DRAFT ONLY</span><span className="report-shelf-chip">STANDARD POST</span><span className="report-shelf-chip">NO AUTO POST</span></div>
      {evidence.phase==='LOADING'?<StateBlock tone="loading" title="Loading amortization readiness">Reading retained source, configuration, capitalization, review, and Draft evidence.</StateBlock>:null}
      {evidence.phase==='BLOCKED'?<StateBlock tone="blocked" title={evidence.error?.code||'AMORTIZATION_READ_BLOCKED'}>{evidence.error?.message} No AI, browser-local, or demonstration schedule is substituted.</StateBlock>:null}
      {evidence.phase==='READY'&&evidence.rows.length===0?<StateBlock tone="empty" title="No source-bound amortization work">No schedule line tied to this exact entity and accounting period was returned. This does not prove that prepaid accounting is complete.</StateBlock>:null}
      {evidence.phase==='READY'&&evidence.rows.length>0?<div className="split two">
        <section className="card"><div className="card-head"><div><h2>Monthly control queue</h2><p className="muted sm">PROPOSED rows are not reviewed schedules. Only the readiness status returned by the control API enables an action.</p></div><span className="badge badge-muted">{evidence.rows.length} SERVER ROWS</span></div><div className="table-wrap" role="region" tabIndex={0} aria-label="Insurance amortization control queue"><table className="tbl"><thead><tr><th>Month</th><th>Amount</th><th>Accounts</th><th>State</th><th>Evidence</th></tr></thead><tbody>{evidence.rows.map(row=><tr key={row.ai_amortization_schedule_line_id} className={selectedId===row.ai_amortization_schedule_line_id?'selected':''} onClick={()=>setSelectedId(row.ai_amortization_schedule_line_id)}><td><button type="button" className="btn-link" onClick={()=>setSelectedId(row.ai_amortization_schedule_line_id)}>{row.amortization_month}</button></td><td>{row.currency} {row.amount}</td><td>Dr {row.expense_account_code}<br/>Cr {row.prepaid_account_code}</td><td><span className={badge(row.readiness_status)}>{row.readiness_status.replaceAll('_',' ')}</span>{row.blocked_reasons.length?<div className="muted sm">{row.blocked_reasons.join(', ')}</div>:null}</td><td><div className="muted sm">Source v{row.source_document_version}</div><div className="muted sm" title={row.source_payload_hash}>{shortHash(row.source_payload_hash)}</div></td></tr>)}</tbody></table></div></section>
        <section className="card sticky-card"><div className="card-head"><div><h2>Selected evidence</h2><p className="muted sm">The browser sends these exact retained IDs and hashes back to the server; the database revalidates the complete chain before any write.</p></div></div>{selected?<><dl className="kv-grid"><div><dt>Source document</dt><dd>{selected.source_document_id}</dd></div><div><dt>Signed admission</dt><dd>{selected.wbs_provider_signed_payable_admission_id||'Missing'}</dd></div><div><dt>Schedule / line</dt><dd>{selected.ai_amortization_schedule_id}<br/>{selected.ai_amortization_schedule_line_id}</dd></div><div><dt>Proposal hash</dt><dd title={selected.proposal_hash}>{shortHash(selected.proposal_hash)}</dd></div><div><dt>Coverage hash</dt><dd title={selected.coverage_hash||''}>{shortHash(selected.coverage_hash)}</dd></div><div><dt>Capitalization JE / GL</dt><dd>{selected.capitalization_journal_entry_id||'Missing'}<br/>{selected.capitalization_ledger_line_id||'Missing'}</dd></div><div><dt>Independent reviewer</dt><dd>{selected.reviewed_by||'Not reviewed'}</dd></div><div><dt>Draft JE</dt><dd>{selected.journal_entry_id?`${selected.journal_entry_id} / ${selected.journal_status} r${selected.journal_revision}`:'Not created'}</dd></div></dl><label className="field"><span>Controller reason</span><textarea value={reason} onChange={event=>setReason(event.target.value)} maxLength={2000} placeholder="Enter the independent review or Draft preparation rationale (8-2000 characters)."/></label><div className="row-acts"><button type="button" className="btn btn-primary" disabled={!selected.can_independently_review||!reasonValid||command.phase==='RUNNING'} onClick={()=>run('REVIEW')}>Retain independent review</button><button type="button" className="btn" disabled={!selected.can_create_draft||!reasonValid||command.phase==='RUNNING'} onClick={()=>run('DRAFT')}>Create monthly AUTO Draft</button></div><p className="muted sm">Draft creation never submits, reviews, approves, or posts the Journal Entry. Continue through the standard Journal Entries workflow with separately authorized actors.</p>{command.message?<StateBlock tone={command.phase==='BLOCKED'?'blocked':'success'} title={command.phase==='BLOCKED'?'Command blocked':'Server state updated'}>{command.message}</StateBlock>:null}</>:<StateBlock tone="empty" title="Select a schedule line">Choose one server-returned line to inspect its evidence.</StateBlock>}</section>
      </div>:null}
      <section className="card"><div className="card-head"><div><h2>Posted prepaid rollforward</h2><p className="muted sm">This report contains only POSTED ledger effects and approved prepaid mappings. A Draft above does not affect these totals.</p></div><span className="badge badge-muted">READ ONLY</span></div>{rollforward.phase==='LOADING'?<StateBlock tone="loading" title="Loading prepaid rollforward">Reading posted report evidence.</StateBlock>:null}{rollforward.phase==='BLOCKED'?<StateBlock tone="blocked" title={rollforward.error?.code||'PREPAID_REPORT_BLOCKED'}>{rollforward.error?.message}</StateBlock>:null}{rollforward.phase==='READY'&&rollforward.rows.length===0?<StateBlock tone="empty" title="No posted prepaid balance">No mapped POSTED prepaid ledger row was returned for this period.</StateBlock>:null}{rollforward.phase==='READY'&&rollforward.rows.length?<div className="table-wrap" role="region" tabIndex={0} aria-label="Posted prepaid rollforward"><table className="tbl"><thead><tr><th>Account</th><th>Opening</th><th>Additions</th><th>Amortization</th><th>Closing</th><th>Lineage</th></tr></thead><tbody>{rollforward.rows.map(row=><tr key={row.account_code}><td>{row.account_code} {row.account_name}</td><td>{row.opening_balance}</td><td>{row.period_additions}</td><td>{row.period_amortization}</td><td>{row.closing_balance}</td><td>{row.journal_entry_ids.length} JE / {row.ledger_line_ids.length} GL / {row.source_document_ids.length} source</td></tr>)}</tbody></table></div>:null}</section>
    </section>
  </AuthoritativeWorkspaceView>;
}
