import React,{useEffect,useMemo,useRef,useState} from 'react';
import {readAccountingStagingJournal,readAccountingStagingRegister,readAccountingStagingSource} from './accounting-staging-register.js';
import {AuthoritativeLineageDrill} from './authoritative-lineage-drill.jsx';
import {AuthoritativeWorkspaceHeader,AuthoritativeWorkspaceView} from './authoritative-workbench-view.jsx';
import {StateBlock} from './ui.jsx';

const initial={phase:'LOADING',data:null,error:null};
const label=value=>value.replaceAll('_',' ');
export function AuthoritativeAccountingStagingWorkspace({config,access=null,fetcher=globalThis.fetch}){
  const [state,setState]=useState(initial),[refresh,setRefresh]=useState(0),[query,setQuery]=useState(''),[status,setStatus]=useState('ALL'),[detail,setDetail]=useState(null),[detailError,setDetailError]=useState(null),[busy,setBusy]=useState(false);const returnButton=useRef(null);
  useEffect(()=>{let active=true;setState(initial);void readAccountingStagingRegister({config,fetcher}).then(result=>{if(active)setState(result.ok?{phase:'READY',data:result.data,error:null}:{phase:'ERROR',data:null,error:result.message});});return()=>{active=false;};},[config?.baseUrl,config?.entityId,config?.periodId,refresh,fetcher]);
  const rows=useMemo(()=>state.data?.rows.filter(row=>{const needle=query.trim().toLowerCase();return(status==='ALL'||row.status===status)&&(!needle||[row.document_no,row.source_record_id,row.document_type,row.source_system,row.source_module,row.status,...row.exceptions.map(item=>item.exception_code)].filter(Boolean).some(value=>String(value).toLowerCase().includes(needle)));})||[],[state.data,query,status]);
  const statuses=useMemo(()=>[...new Set((state.data?.rows||[]).map(row=>row.status))].sort(),[state.data]);
  const open=async(kind,row,evidence,button)=>{if(busy)return;setBusy(true);setDetailError(null);returnButton.current=button;const result=kind==='SOURCE'?await readAccountingStagingSource({config,row,fetcher}):await readAccountingStagingJournal({config,evidence,fetcher});setBusy(false);if(result.ok)setDetail(kind==='SOURCE'?{kind,detail:result.detail,row}:{kind,journal:result.journal,row});else setDetailError(result.message);};
  if(detail){const context={entityId:config.entityId,periodId:config.periodId,stagingItemId:detail.row.staging_item_id,sourceDocumentId:detail.row.source_document_id,sourceRevision:detail.row.source_document_revision,payloadHash:detail.row.payload_hash};return <AuthoritativeLineageDrill config={config} fetcher={fetcher} initial={detail.kind==='SOURCE'?{kind:'SOURCE',detail:detail.detail,context}:{kind:'JOURNAL',journal:detail.journal,context:{...context,journalId:detail.journal.journal_entry_id,journalRevision:detail.journal.revision,journalCurrency:detail.journal.currency}}} onExit={()=>{setDetail(null);queueMicrotask(()=>returnButton.current?.focus());}}/>;}
  return <AuthoritativeWorkspaceView className="authoritative-accounting-staging-workspace">
    <AuthoritativeWorkspaceHeader eyebrow="Source & staging" title="Accounting Staging" description="Inspect persisted source-to-staging state, exceptions, configuration evidence, and linked Journals for the selected period." status="Read-only register"/>
    <div className="filter-bar" role="search"><label>Search <input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Document, source, status, or exception"/></label><label>Status <select value={status} onChange={event=>setStatus(event.target.value)}><option value="ALL">All statuses</option>{statuses.map(value=><option key={value} value={value}>{label(value)}</option>)}</select></label><button type="button" className="btn" disabled={state.phase==='LOADING'} onClick={()=>setRefresh(value=>value+1)}>Refresh</button></div>
    {state.phase==='LOADING'?<StateBlock tone="loading" title="Loading Accounting Staging">Reading persisted staging items and immutable evidence links.</StateBlock>:null}
    {state.phase==='ERROR'?<StateBlock tone="error" title="Could not load Accounting Staging">{state.error}<button type="button" className="btn" onClick={()=>setRefresh(value=>value+1)}>Try again</button></StateBlock>:null}
    {detailError?<p role="alert">{detailError}</p>:null}
    {state.phase==='READY'?<>
      <div className="authoritative-kpi-grid"><article><span>Staging items</span><strong>{state.data.row_count}</strong></article><article><span>Exceptions</span><strong>{state.data.exception_count}</strong></article><article><span>Ready for Draft</span><strong>{state.data.ready_for_draft_count}</strong></article><article><span>Draft or later</span><strong>{state.data.draft_or_later_count}</strong></article></div>
      {rows.length?<div className="table-wrap" role="region" tabIndex={0} aria-label="Accounting Staging; scroll horizontally to view all fields"><table className="tbl"><thead><tr><th>Source document</th><th>Date</th><th>Amount</th><th>Staging status</th><th>Exceptions</th><th>Configuration</th><th>Journal evidence</th><th>Trace</th></tr></thead><tbody>{rows.map(row=><tr key={row.staging_item_id}><td><b>{row.document_no||row.source_record_id}</b><small>{row.source_system} · {row.source_module} · revision {row.source_document_revision}</small></td><td>{row.accounting_date}</td><td>{row.gross_amount} {row.currency}</td><td><span className="badge badge-muted">{label(row.status)}</span><small>staging v{row.staging_version}</small></td><td>{row.exceptions.length?row.exceptions.map(item=><small key={item.exception_id}>{item.severity} · {label(item.status)} · {item.exception_code}</small>):'None retained'}</td><td><small>Setting: {row.setting_snapshot_id||'Not bound'}</small><small>Mapping: {row.mapping_snapshot_id||'Not bound'}</small><small>Rule: {row.rule_evaluation_id||'Not bound'}</small><small>AI: {row.ai_decision_id||'Not bound'}</small></td><td>{row.journal_evidence.length?row.journal_evidence.map(item=><button key={item.journal_entry_id} type="button" className="btn btn-sm btn-ghost" disabled={busy||access?.session_refresh_required===true||!access?.permissions?.includes('GL.JE.VIEW')} onClick={event=>open('JOURNAL',row,item,event.currentTarget)}>{item.journal_number} · {label(item.status)}</button>):'No Journal linked'}</td><td><button type="button" className="btn btn-sm" disabled={busy} onClick={event=>open('SOURCE',row,null,event.currentTarget)}>Open source</button></td></tr>)}</tbody></table></div>:<StateBlock tone="empty" title="No staging items match this scope">No persisted staging item matched the selected company, period, status, and search. This does not assert that the source system had no activity.</StateBlock>}
      <details><summary>Register evidence boundary</summary><p>Every row is read from PostgreSQL staging and immutable Source Document records. Exceptions and Journal references are retained facts. This page cannot import, assign, review, create a Draft, approve, or post.</p></details>
    </>:null}
  </AuthoritativeWorkspaceView>;
}
