import React,{useEffect,useRef,useState} from 'react';
import {readConstructionLoanJournal,readConstructionLoanRegister} from './construction-loan-register.js';
import {AuthoritativeLineageDrill} from './authoritative-lineage-drill.jsx';
import {AuthoritativeWorkspaceHeader,AuthoritativeWorkspaceView} from './authoritative-workbench-view.jsx';
import {StateBlock} from './ui.jsx';

const empty={phase:'LOADING',data:null,error:null};
export function AuthoritativeLoanRegisterWorkspace({config,access=null,fetcher=globalThis.fetch,onBack=()=>{}}){
  const [state,setState]=useState(empty),[refresh,setRefresh]=useState(0),[detail,setDetail]=useState(null),[detailError,setDetailError]=useState(null),[busy,setBusy]=useState(false);
  const returnButton=useRef(null);
  useEffect(()=>{let active=true;setState(empty);void readConstructionLoanRegister({config,fetcher}).then(result=>{if(active)setState(result.ok?{phase:'READY',data:result.data,error:null}:{phase:'ERROR',data:null,error:result.message});});return()=>{active=false;};},[config?.baseUrl,config?.entityId,config?.periodId,refresh,fetcher]);
  const canReadJournal=access?.entity_id===config?.entityId&&access?.session_refresh_required===false&&access?.permissions?.includes('GL.JE.VIEW');
  const openJournal=async(row,button)=>{if(busy)return;setBusy(true);setDetailError(null);returnButton.current=button;try{const result=await readConstructionLoanJournal({config,journalEntryId:row.journal_entry_ids[0],currency:row.currency,fetcher});if(result.ok)setDetail(result.journal);else setDetailError(result.message);}finally{setBusy(false);}};
  if(detail)return <AuthoritativeLineageDrill config={config} fetcher={fetcher} initial={{kind:'JOURNAL',journal:detail,context:{entityId:config.entityId,periodId:config.periodId,journalId:detail.journal_entry_id,journalRevision:detail.revision,journalCurrency:detail.currency}}} onExit={()=>{setDetail(null);queueMicrotask(()=>returnButton.current?.focus());}}/>;
  return <AuthoritativeWorkspaceView className="authoritative-loan-register-workspace">
    <AuthoritativeWorkspaceHeader eyebrow="Projects & Property" title="Loan Register" description="Review posted construction-loan balances tied to exact loan and lender source references." status="Read-only register"/>
    <div className="filter-bar"><button type="button" className="btn" onClick={onBack}>Back to construction loan</button><span>{config?.scopePresentation?.entityLabel||'Selected company'} · {config?.scopePresentation?.periodLabel||'Selected period'}</span><button type="button" className="btn" disabled={state.phase==='LOADING'} onClick={()=>setRefresh(value=>value+1)}>Refresh</button></div>
    {state.phase==='LOADING'?<StateBlock tone="loading" title="Loading Loan Register">Reading posted ledger, approved account mapping, loan source, lender, and immutable lineage references.</StateBlock>:null}
    {state.phase==='ERROR'?<StateBlock tone="error" title="Could not load Loan Register">{state.error}<button type="button" className="btn" onClick={()=>setRefresh(value=>value+1)}>Try again</button></StateBlock>:null}
    {detailError?<p role="alert">{detailError}</p>:null}
    {state.phase==='READY'?<>
      <div className="authoritative-kpi-grid"><article><span>Loans</span><strong>{state.data.rows.length}</strong></article><article><span>Exact posted lines</span><strong>{state.data.exact_ledger_line_count}</strong></article><article><span>Blocked lines</span><strong>{state.data.blocked_ledger_line_count}</strong></article></div>
      <div className="table-wrap" role="region" tabIndex={0} aria-label="Loan Register; scroll horizontally to view all fields"><table className="tbl"><thead><tr><th>Loan</th><th>Lender</th><th>Account</th><th>Opening</th><th>Draws</th><th>Repayments</th><th>Closing</th><th>Evidence</th></tr></thead><tbody>{state.data.rows.map(row=><tr key={`${row.loan_ref}:${row.lender_ref}:${row.currency}:${row.account_code}`}><td>{row.loan_ref}</td><td>{row.lender_ref}</td><td title={row.account_name}>{row.account_code}</td><td>{row.opening_balance} {row.currency}</td><td>{row.period_draws} {row.currency}</td><td>{row.period_repayments} {row.currency}</td><td>{row.closing_balance} {row.currency}</td><td><button type="button" className="btn btn-sm btn-ghost" disabled={busy||!canReadJournal} onClick={event=>openJournal(row,event.currentTarget)}>View posted Journal</button></td></tr>)}</tbody></table></div>
      {!state.data.rows.length?<StateBlock tone="empty" title="No exact loans for this period">No posted construction-loan ledger line had an exact approved account mapping plus one unambiguous loan and lender source reference.</StateBlock>:null}
      {state.data.blocked_lines.length?<details open><summary>Blocked loan evidence ({state.data.blocked_lines.length})</summary><p>These posted mapped liability lines remain outside loan balances until their immutable source linkage is complete.</p><div className="table-wrap"><table className="tbl"><thead><tr><th>Date</th><th>Journal</th><th>Account</th><th>Debit</th><th>Credit</th><th>Reason</th></tr></thead><tbody>{state.data.blocked_lines.map(row=><tr key={row.ledger_line_id}><td>{row.journal_date}</td><td>{row.journal_number}</td><td>{row.account_code}</td><td>{row.debit_amount} {row.currency}</td><td>{row.credit_amount} {row.currency}</td><td>{row.source_binding_status.replaceAll('_',' ')}</td></tr>)}</tbody></table></div></details>:null}
      <details><summary>Exact evidence references</summary>{state.data.rows.map(row=><dl className="fixed-assets-detail-grid" key={`${row.loan_ref}:${row.account_code}`}>{[['Loan',row.loan_ref],['Lender',row.lender_ref],['Mapping snapshot',row.mapping_snapshot_id],['Mapping hash',row.mapping_snapshot_hash],['Journal IDs',row.journal_entry_ids.join(', ')],['Journal line IDs',row.journal_line_ids.join(', ')],['Ledger line IDs',row.ledger_line_ids.join(', ')],['Source document IDs',row.source_document_ids.join(', ')],['Source line IDs',row.source_document_line_ids.join(', ')]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>)}</details>
    </>:null}
  </AuthoritativeWorkspaceView>;
}
