import React,{useEffect,useMemo,useRef,useState} from 'react';
import {readMappingExceptionRegister,readMappingExceptionSource} from './mapping-exception-register.js';
import {AuthoritativeLineageDrill} from './authoritative-lineage-drill.jsx';
import {AuthoritativeWorkspaceHeader,AuthoritativeWorkspaceView} from './authoritative-workbench-view.jsx';
import {StateBlock} from './ui.jsx';
const initial={phase:'LOADING',data:null,error:null};
const label=value=>value?.replaceAll('_',' ')||'Not bound';
export function AuthoritativeMappingExceptionsWorkspace({config,fetcher=globalThis.fetch}){
  const [state,setState]=useState(initial),[refresh,setRefresh]=useState(0),[query,setQuery]=useState(''),[status,setStatus]=useState('ACTIVE'),[severity,setSeverity]=useState('ALL'),[detail,setDetail]=useState(null),[detailError,setDetailError]=useState(null),[busy,setBusy]=useState(false);const returnButton=useRef(null);
  useEffect(()=>{let active=true;setState(initial);void readMappingExceptionRegister({config,fetcher}).then(result=>{if(active)setState(result.ok?{phase:'READY',data:result.data,error:null}:{phase:'ERROR',data:null,error:result.message});});return()=>{active=false;};},[config?.baseUrl,config?.entityId,config?.periodId,refresh,fetcher]);
  const rows=useMemo(()=>state.data?.rows.filter(row=>{const needle=query.trim().toLowerCase(),statusMatch=status==='ALL'||(status==='ACTIVE'&&['OPEN','IN_REVIEW'].includes(row.status))||row.status===status;return statusMatch&&(severity==='ALL'||row.severity===severity)&&(!needle||[row.exception_code,row.reason,row.owner,row.document_no,row.source_record_id,row.mapping_family,row.mapping_status].filter(Boolean).some(value=>String(value).toLowerCase().includes(needle)));})||[],[state.data,query,status,severity]);
  const openSource=async(row,button)=>{if(busy)return;setBusy(true);setDetailError(null);returnButton.current=button;const result=await readMappingExceptionSource({config,row,fetcher});setBusy(false);if(result.ok)setDetail({row,detail:result.detail});else setDetailError(result.message);};
  if(detail){const {row}=detail;return <AuthoritativeLineageDrill config={config} fetcher={fetcher} initial={{kind:'SOURCE',detail:detail.detail,context:{entityId:config.entityId,periodId:config.periodId,sourceDocumentId:row.source_document_id,sourceRevision:row.source_document_revision,payloadHash:row.payload_hash,stagingItemId:row.staging_item_id}}} onExit={()=>{setDetail(null);queueMicrotask(()=>returnButton.current?.focus());}}/>;}
  return <AuthoritativeWorkspaceView className="authoritative-mapping-exceptions-workspace">
    <AuthoritativeWorkspaceHeader eyebrow="Source & staging" title="Mapping Exceptions" description="Inspect retained mapping failures with exact Source Document, staging, ownership, resolution, and immutable mapping evidence." status="Read-only register"/>
    <div className="filter-bar" role="search"><label>Search <input value={query} onChange={event=>setQuery(event.target.value)} placeholder="Exception, source, owner, or mapping"/></label><label>Status <select value={status} onChange={event=>setStatus(event.target.value)}><option value="ACTIVE">Open + in review</option><option value="ALL">All statuses</option><option value="OPEN">Open</option><option value="IN_REVIEW">In review</option><option value="RESOLVED">Resolved</option><option value="WAIVED">Waived</option></select></label><label>Severity <select value={severity} onChange={event=>setSeverity(event.target.value)}><option value="ALL">All severities</option>{['CRITICAL','HIGH','MEDIUM','LOW'].map(value=><option key={value} value={value}>{label(value)}</option>)}</select></label><button type="button" className="btn" disabled={state.phase==='LOADING'} onClick={()=>setRefresh(value=>value+1)}>Refresh</button></div>
    {state.phase==='LOADING'?<StateBlock tone="loading" title="Loading Mapping Exceptions">Reading retained mapping failures and immutable evidence.</StateBlock>:null}
    {state.phase==='ERROR'?<StateBlock tone="error" title="Could not load Mapping Exceptions">{state.error}<button type="button" className="btn" onClick={()=>setRefresh(value=>value+1)}>Try again</button></StateBlock>:null}
    {detailError?<p role="alert">{detailError}</p>:null}
    {state.phase==='READY'?<><div className="authoritative-kpi-grid"><article><span>Total exceptions</span><strong>{state.data.row_count}</strong></article><article><span>Open</span><strong>{state.data.open_count}</strong></article><article><span>In review</span><strong>{state.data.in_review_count}</strong></article><article><span>Resolved / waived</span><strong>{state.data.resolved_count+state.data.waived_count}</strong></article></div>
      {rows.length?<div className="table-wrap" role="region" tabIndex={0} aria-label="Mapping Exceptions; scroll horizontally to view all fields"><table className="tbl"><thead><tr><th>Exception</th><th>Source</th><th>Status</th><th>Owner / outcome</th><th>Mapping evidence</th><th>Trace</th></tr></thead><tbody>{rows.map(row=><tr key={row.exception_id}><td><b>{row.exception_code}</b><small>{row.severity} · v{row.exception_version}</small><small>{row.reason}</small></td><td><b>{row.document_no||row.source_record_id}</b><small>{row.accounting_date} · {row.gross_amount} {row.currency}</small><small>{row.source_system} · {row.source_module} · revision {row.source_document_revision}</small></td><td><span className="badge badge-muted">{label(row.status)}</span><small>Staging: {label(row.staging_status)}{row.staging_version===null?'':` · v${row.staging_version}`}</small></td><td><small>Owner: {row.owner||'Unassigned'}</small><small>Resolved by: {row.resolved_by||'—'}</small><small>{row.resolution||'No retained resolution'}</small></td><td>{row.mapping_snapshot_id?<><small>{row.mapping_family} · {label(row.mapping_status)} · v{row.mapping_version}</small><small>{row.mapping_snapshot_hash}</small><small>Effective {new Date(row.mapping_effective_from).toLocaleDateString()} {row.mapping_effective_to?`to ${new Date(row.mapping_effective_to).toLocaleDateString()}`:'onward'}</small></>:<small>No mapping snapshot was bound when this exception was retained.</small>}</td><td><button type="button" className="btn btn-sm" disabled={busy} onClick={event=>openSource(row,event.currentTarget)}>Open source</button></td></tr>)}</tbody></table></div>:<StateBlock tone="empty" title="No mapping exceptions match this scope">No retained mapping exception matched the selected company, period, status, severity, and search.</StateBlock>}
      <details><summary>Exception evidence boundary</summary><p>Rows come from retained PostgreSQL accounting exceptions and exact Source Document records. Mapping identity, version, hash, status, and effectivity appear only when a snapshot was bound. This page cannot assign, review, resolve, waive, create a Draft, or post.</p></details></>:null}
  </AuthoritativeWorkspaceView>;
}
