import React from 'react';
import { nextAuthoritativeWorkflowAction } from './authoritative-workflow.js';

const money=(value,currency)=>new Intl.NumberFormat('en-US',{style:'currency',currency:/^[A-Z]{3}$/.test(currency||'')?currency:'USD'}).format(Number(value)||0);
const date=/^\d{4}-\d{2}-\d{2}$/;
const amount=/^(?:0|[1-9]\d{0,15})(?:\.\d{1,4})?$/;
const account=/^[A-Za-z0-9._-]{1,64}$/;
export const validateAuthoritativeDocumentDraft=values=>{
  const kind=['AP_BILL','AR_INVOICE'].includes(values?.kind)?values.kind:null;
  const documentNumber=String(values?.documentNumber||'').trim(),counterpartyRef=String(values?.counterpartyRef||'').trim(),counterpartyName=String(values?.counterpartyName||'').trim(),currency=String(values?.currency||'').trim().toUpperCase(),accountingDate=String(values?.accountingDate||'').trim(),dueDate=String(values?.dueDate||'').trim(),value=String(values?.amount||'').trim(),offsetAccountCode=String(values?.offsetAccountCode||'').trim(),description=String(values?.description||'').trim();
  if(!kind||!documentNumber||documentNumber.length>128||!counterpartyRef||counterpartyRef.length>128||!counterpartyName||counterpartyName.length>255||!/^[A-Z]{3}$/.test(currency)||!date.test(accountingDate)||!amount.test(value)||Number(value)<=0||!account.test(offsetAccountCode)||description.length>2000||(dueDate&&!date.test(dueDate)))return {ok:false,code:'AUTHORITATIVE_DOCUMENT_INVALID',message:'Complete the Draft fields with valid dates, a positive four-decimal amount, and an account code.'};
  return {ok:true,kind,document:{documentNumber,counterpartyRef,counterpartyName,currency,accountingDate,dueDate:dueDate||null,amount:value,offsetAccountCode,description:description||null}};
};
export function AuthoritativeDocumentTable({title,documents=[],kind}){const bill=kind==='AP';return <section aria-label={title}><h2>{title}</h2><table className="tbl"><tbody>{documents.map(row=><tr key={row.journal_entry_id||row.business_document_id}><td>{row[bill?'bill_no':'inv_no']}</td><td>{row[bill?'vendor_name':'customer_name']}</td><td>{money(row.amount,row.currency)}</td><td>{row.status}</td></tr>)}</tbody></table></section>;}
export function AuthoritativeAdjustmentSummary({title,adjustments=[]}){return <section aria-label={title}><h2>{title}</h2>{adjustments.map(row=><div key={row.business_adjustment_id}>{row.adjustment_kind} {money(row.amount,row.currency)} {row.status}</div>)}</section>;}
export function AuthoritativeWorkflowTable({title,documents=[],kind,onWorkflow,workingJournalIds=new Set()}){const bill=kind==='AP';return <section aria-label={title}><h2>{title}</h2>{documents.map(row=>{const action=nextAuthoritativeWorkflowAction(row.journal_status);return <div key={row.journal_entry_id}>{row[bill?'bill_no':'inv_no']} {action?<button disabled={workingJournalIds.has(row.journal_entry_id)} onClick={()=>onWorkflow(row,action)}>{action}</button>:row.journal_status}</div>;})}</section>;}
export function AuthoritativeWorkflowAdjustmentTable({title,adjustments=[],onWorkflow,workingJournalIds=new Set()}){return <section aria-label={title}><h2>{title}</h2>{adjustments.map(row=>{const action=nextAuthoritativeWorkflowAction(row.journal_status);return <div key={row.business_adjustment_id}>{row.adjustment_kind} {action?<button disabled={workingJournalIds.has(row.journal_entry_id)} onClick={()=>onWorkflow(row,action)}>{action}</button>:row.journal_status}</div>;})}</section>;}
export function AuthoritativeCreditApplicationForm({kind,credits=[],documents=[]}){const label=kind==='AR_CREDIT_MEMO'?'Credit memo':'Vendor credit';return <section aria-label={`Apply ${label}`}><h2>Apply {label}</h2><select>{credits.filter(x=>x.status==='POSTED').map(x=><option key={x.business_adjustment_id}>{x.business_adjustment_id}</option>)}</select><select>{documents.map(x=><option key={x.business_document_id}>{x.inv_no||x.bill_no}</option>)}</select></section>;}
export function AuthoritativeRefundForm({credits=[]}){return <section aria-label="Create refund Draft"><h2>Create refund Draft</h2><label>Credit memo<select>{credits.filter(x=>x.status==='POSTED').map(x=><option key={x.business_adjustment_id}>{x.business_adjustment_id}</option>)}</select></label></section>;}
export function AuthoritativeDraftForm(){return <section aria-label="Create Draft only"><h2>Create Draft only</h2><p>Drafts are sent to the authoritative API and require review and approval before any separate posting command.</p></section>;}
export function AuthoritativeRuntimeLock(){return <main className="login-shell"><section className="login-card" role="alert"><h1>Authoritative API required</h1><p>The deployed REFS client is locked until its HTTPS accounting API and OIDC token provider are configured.</p></section></main>;}
