import React,{useCallback,useEffect,useMemo,useState}from'react';
import{refreshAuthoritativeMappingCatalogs}from'./accounting-api.js';
import{StateBlock}from'./ui.jsx';
const shortHash=value=>`${value.slice(0,15)}…${value.slice(-8)}`;
const statement=value=>value==='BS'?'Balance Sheet':'Income Statement';
const present=value=>value??'—';

export function AuthoritativeReportMappingsWorkspace({config,fetcher=globalThis.fetch}){
 const[state,setState]=useState({phase:'LOADING',data:null,error:null});const[query,setQuery]=useState('');const load=useCallback(async()=>{setState({phase:'LOADING',data:null,error:null});const result=await refreshAuthoritativeMappingCatalogs({config,fetcher});setState(result.ok?{phase:'READY',data:result.data,error:null}:{phase:'ERROR',data:null,error:result});},[config,fetcher]);useEffect(()=>{load();},[load]);const data=state.data;
 const reportRows=useMemo(()=>{const needle=query.trim().toLowerCase();return !needle||!data?data?.report.mappings||[]:data.report.mappings.filter(row=>[row.account_code,row.account_role,row.account_class,row.account_type,row.statement,row.report_row_code,row.cash_flow_class,...row.dimension_requirements].some(value=>String(value).toLowerCase().includes(needle)));},[data,query]);
 const dimensionRows=useMemo(()=>{const needle=query.trim().toLowerCase();return !needle||!data?data?.dimensions.mappings||[]:data.dimensions.mappings.filter(row=>[row.rule_id,row.scope_level,row.project_ref,row.property_ref,row.cost_code_ref,row.member_ref,row.capitalization_treatment,row.cwip_account_role,row.status].some(value=>String(value??'').toLowerCase().includes(needle)));},[data,query]);
 const vendorRows=useMemo(()=>{const needle=query.trim().toLowerCase();return !needle||!data?data?.vendors.mappings||[]:data.vendors.mappings.filter(row=>[row.rule_id,row.vendor_ref,row.treatment,...row.aliases,...row.contract_keys,...row.service_keys,...row.source_requirements].some(value=>String(value).toLowerCase().includes(needle)));},[data,query]);
 const taxRows=useMemo(()=>{const needle=query.trim().toLowerCase();return !needle||!data?data?.tax.mappings||[]:data.tax.mappings.filter(row=>[row.code,row.basis,row.recoverability,row.expense_treatment,...row.evidence_requirements].some(value=>String(value).toLowerCase().includes(needle)));},[data,query]);
 const intercompanyRows=useMemo(()=>{const needle=query.trim().toLowerCase();return !needle||!data?data?.intercompany.mappings||[]:data.intercompany.mappings.filter(row=>[row.company_code,row.counterparty_entity_id,row.currency,row.due_to_account_role,row.due_from_account_role,row.elimination_account_role,...row.dimension_requirements].some(value=>String(value).toLowerCase().includes(needle)));},[data,query]);
 const loanRows=useMemo(()=>{const needle=query.trim().toLowerCase();return !needle||!data?data?.loanCapitalization.mappings||[]:data.loanCapitalization.mappings.filter(row=>[row.project_ref,row.property_ref,row.asset_ref].some(value=>String(value??'').toLowerCase().includes(needle)));},[data,query]);
 return <section className="workspace-card" aria-labelledby="report-mappings-title"><header className="workspace-title-row"><div><p className="eyebrow">APPROVED MAPPING EVIDENCE</p><h2 id="report-mappings-title">Mapping Center</h2><p>Review complete approved report, dimension, vendor, tax-code, intercompany, and loan-capitalization mapping catalogs for this company and period.</p></div><button type="button" onClick={load} disabled={state.phase==='LOADING'}>Refresh</button></header>
 {state.phase==='LOADING'&&<StateBlock tone="loading">Reading approved mapping catalogs...</StateBlock>}{state.error&&<StateBlock tone="danger">{state.error.code}: {state.error.message}</StateBlock>}
 {data&&<><div className="summary-grid"><article><span>Period</span><strong>{data.report.scope.period_code}</strong><small>{data.report.scope.period_status} · {data.report.scope.currency}</small></article><article><span>Report mappings</span><strong>{data.report.population.total_count}</strong><small>Complete immutable population</small></article><article><span>Dimension mappings</span><strong>{data.dimensions.population.total_count}</strong><small>Complete immutable population</small></article><article><span>Policy mappings</span><strong>{data.vendors.population.total_count} vendor · {data.tax.population.total_count} tax · {data.intercompany.population.total_count} intercompany · {data.loanCapitalization.population.total_count} loan</strong><small>Complete immutable populations</small></article></div>
 <label className="field"><span>Find approved mappings</span><input type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Account, project, vendor, tax code, counterparty, asset, or rule"/></label>
 <h3>Account-to-report mappings</h3><p className="muted sm">Showing {reportRows.length} of {data.report.population.total_count} complete approved report mappings. Population hash: <span className="mono" title={data.report.population.population_hash}>{shortHash(data.report.population.population_hash)}</span></p>
 <div className="table-wrap" tabIndex="0" role="region" aria-label="Approved account-to-report mappings; scroll horizontally to view every column"><table><thead><tr><th>Account</th><th>Role / class</th><th>Statement / report row</th><th>Normal balance</th><th>Cash flow</th><th>Dimensions</th><th>Effective</th><th>Evidence hash</th></tr></thead><tbody>{reportRows.map(row=><tr key={`${row.account_code}:${row.account_role}`}><td><strong>{row.account_code}</strong><br/><span className="muted sm">{row.account_type}</span></td><td>{row.account_role}<br/><span className="muted sm">{row.account_class}{row.contra?' · Contra':''}</span></td><td>{statement(row.statement)}<br/><span className="mono sm">{row.report_row_code}</span></td><td>{row.normal_balance}</td><td>{row.cash_flow_class}</td><td>{row.dimension_requirements.length?row.dimension_requirements.join(', '):'None'}</td><td>{row.effective_from} to {row.effective_to||'Open-ended'}</td><td className="mono sm" title={row.mapping_hash}>{shortHash(row.mapping_hash)}</td></tr>)}</tbody></table></div>{reportRows.length===0&&<StateBlock tone="empty">No approved report mappings match this local filter. The authoritative population remains unchanged.</StateBlock>}
 <h3>Project, property, and cost-code mappings</h3><p className="muted sm">Showing {dimensionRows.length} of {data.dimensions.population.total_count} complete approved dimension mappings. Population hash: <span className="mono" title={data.dimensions.population.population_hash}>{shortHash(data.dimensions.population.population_hash)}</span></p>
 <div className="table-wrap" tabIndex="0" role="region" aria-label="Approved project, property, and cost-code mappings; scroll horizontally to view every column"><table><thead><tr><th>Rule / scope</th><th>Project</th><th>Property</th><th>Cost code / member</th><th>Treatment</th><th>Requirements</th><th>Status / effective</th><th>Evidence hash</th></tr></thead><tbody>{dimensionRows.map(row=><tr key={row.rule_id}><td><strong>{row.rule_id}</strong><br/><span className="muted sm">{row.scope_level}</span></td><td>{present(row.project_ref)}</td><td>{present(row.property_ref)}</td><td>{present(row.cost_code_ref)}<br/><span className="muted sm">Member: {present(row.member_ref)}</span></td><td>{row.capitalization_treatment}<br/><span className="muted sm">CWIP role: {row.cwip_account_role}</span></td><td>Ownership: {row.ownership_requirement}<br/><span className="muted sm">Member: {row.member_requirement}</span></td><td>{row.status} · {row.effective_for_period?'In period':'Outside period'}<br/><span className="muted sm">{row.effective_from} to {row.effective_to||'Open-ended'}</span></td><td className="mono sm" title={row.mapping_hash}>{shortHash(row.mapping_hash)}</td></tr>)}</tbody></table></div>{dimensionRows.length===0&&<StateBlock tone="empty">No approved dimension mappings match this local filter. The authoritative population remains unchanged.</StateBlock>}
 <h3>Vendor treatment mappings</h3><p className="muted sm">Showing {vendorRows.length} of {data.vendors.population.total_count} complete approved vendor treatment mappings. Population hash: <span className="mono" title={data.vendors.population.population_hash}>{shortHash(data.vendors.population.population_hash)}</span></p>
 <div className="table-wrap" tabIndex="0" role="region" aria-label="Approved vendor treatment mappings; scroll horizontally to view every column"><table><thead><tr><th>Vendor / rule</th><th>Treatment</th><th>Payment terms</th><th>Recurring / duplicates</th><th>Aliases</th><th>Source bindings</th><th>Effective</th><th>Evidence hash</th></tr></thead><tbody>{vendorRows.map(row=><tr key={row.rule_id}><td><strong>{row.vendor_ref}</strong><br/><span className="mono sm">{row.rule_id}</span></td><td>{row.treatment}</td><td>{row.payment_terms_days} days</td><td>{row.recurring?'Recurring':'Not recurring'}<br/><span className="muted sm">Duplicate normalization: {row.duplicate_normalization?'On':'Off'}</span></td><td>{row.aliases.length?row.aliases.join(', '):'None'}</td><td>Contracts: {row.contract_keys.length?row.contract_keys.join(', '):'None'}<br/><span className="muted sm">Services: {row.service_keys.length?row.service_keys.join(', '):'None'} · Required: {row.source_requirements.length?row.source_requirements.join(', '):'None'}</span></td><td>{row.effective_for_period?'In period':'Outside period'}<br/><span className="muted sm">{row.effective_from} to {row.effective_to||'Open-ended'}</span></td><td className="mono sm" title={row.mapping_hash}>{shortHash(row.mapping_hash)}</td></tr>)}</tbody></table></div>{vendorRows.length===0&&<StateBlock tone="empty">No approved vendor treatment mappings match this local filter. The authoritative population remains unchanged.</StateBlock>}
 <h3>Tax policy and code mappings</h3><p className="muted sm">{data.tax.policy.jurisdiction} · {data.tax.policy.treatment} · {data.tax.policy.allocation_method} · coverage {data.tax.policy.coverage_start} to {data.tax.policy.coverage_end}. Showing {taxRows.length} of {data.tax.population.total_count} complete approved tax-code mappings.</p>
 <div className="table-wrap" tabIndex="0" role="region" aria-label="Approved tax-code mappings; scroll horizontally to view every column"><table><thead><tr><th>Tax code</th><th>Rate / basis</th><th>Recoverability</th><th>Expense treatment</th><th>Evidence requirements</th><th>Effective</th><th>Mapping hash</th><th>Policy hash</th></tr></thead><tbody>{taxRows.map(row=><tr key={row.code}><td><strong>{row.code}</strong></td><td>{row.rate}<br/><span className="muted sm">{row.basis}</span></td><td>{row.recoverability}</td><td>{row.expense_treatment}</td><td>{row.evidence_requirements.length?row.evidence_requirements.join(', '):'None'}</td><td>{row.effective_for_period?'In period':'Outside period'}<br/><span className="muted sm">{row.effective_from} to {row.effective_to||'Open-ended'}</span></td><td className="mono sm" title={row.mapping_hash}>{shortHash(row.mapping_hash)}</td><td className="mono sm" title={data.tax.policy.policy_hash}>{shortHash(data.tax.policy.policy_hash)}</td></tr>)}</tbody></table></div>{taxRows.length===0&&<StateBlock tone="empty">No approved tax-code mappings match this local filter. The authoritative population remains unchanged.</StateBlock>}
 <h3>Intercompany counterparty mappings</h3><p className="muted sm">Policy {data.intercompany.policy.enabled?'enabled':'disabled'} · clearing role {data.intercompany.policy.clearing_account_role}. Showing {intercompanyRows.length} of {data.intercompany.population.total_count} complete approved counterparties.</p>
 <div className="table-wrap" tabIndex="0" role="region" aria-label="Approved intercompany counterparty mappings; scroll horizontally to view every column"><table><thead><tr><th>Counterparty company</th><th>Counterparty entity</th><th>Currency</th><th>Account roles</th><th>Dimensions</th><th>Approval evidence</th><th>Effective</th><th>Mapping hash</th></tr></thead><tbody>{intercompanyRows.map(row=><tr key={row.counterparty_entity_id}><td><strong>{row.company_code}</strong></td><td className="mono sm">{row.counterparty_entity_id}</td><td>{row.currency}</td><td>{row.due_from_account_role}<br/>{row.due_to_account_role}<br/><span className="muted sm">{row.elimination_account_role}</span></td><td>{row.dimension_requirements.length?row.dimension_requirements.join(', '):'None'}</td><td className="mono sm" title={row.counterparty_approval_hash}>{row.counterparty_approval_id}<br/>{shortHash(row.counterparty_approval_hash)}</td><td>{row.effective_for_period?'In period':'Outside period'}<br/><span className="muted sm">{row.effective_from} to {row.effective_to||'Open-ended'}</span></td><td className="mono sm" title={row.mapping_hash}>{shortHash(row.mapping_hash)}</td></tr>)}</tbody></table></div>{intercompanyRows.length===0&&<StateBlock tone="empty">No approved intercompany counterparties are configured for this period. This does not authorize cross-entity activity.</StateBlock>}
 <h3>Loan capitalization policy and qualifying combinations</h3><p className="muted sm">{data.loanCapitalization.policy.loan_purpose} · start {data.loanCapitalization.policy.capitalization_start_policy} · materiality {data.loanCapitalization.policy.currency} {data.loanCapitalization.policy.materiality_amount}. Required evidence: {data.loanCapitalization.policy.required_evidence.join(', ')}. Showing {loanRows.length} of {data.loanCapitalization.population.total_count} complete approved combinations.</p>
 <div className="table-wrap" tabIndex="0" role="region" aria-label="Approved loan-capitalization qualifying combinations; scroll horizontally to view every column"><table><thead><tr><th>Project</th><th>Property</th><th>Asset</th><th>Eligible costs</th><th>Account roles</th><th>Suspension / cessation</th><th>Effective</th><th>Mapping hash</th></tr></thead><tbody>{loanRows.map(row=><tr key={row.mapping_hash}><td>{present(row.project_ref)}</td><td>{present(row.property_ref)}</td><td>{present(row.asset_ref)}</td><td>{data.loanCapitalization.policy.eligible_interest_policy}<br/><span className="muted sm">{data.loanCapitalization.policy.eligible_fee_policy}</span></td><td>{data.loanCapitalization.policy.expense_account_role}<br/>{data.loanCapitalization.policy.cwip_account_role}<br/><span className="muted sm">{data.loanCapitalization.policy.fixed_asset_account_role}</span></td><td>{data.loanCapitalization.policy.suspension_policy}<br/><span className="muted sm">{data.loanCapitalization.policy.cessation_policy}</span></td><td>{row.effective_for_period?'In period':'Outside period'}<br/><span className="muted sm">{row.effective_from} to {row.effective_to||'Open-ended'}</span></td><td className="mono sm" title={row.mapping_hash}>{shortHash(row.mapping_hash)}</td></tr>)}</tbody></table></div>{loanRows.length===0&&<StateBlock tone="empty">No approved loan-capitalization combinations match this local filter. The authoritative population remains unchanged.</StateBlock>}
 <p className="muted sm">Read only. These catalogs cannot create, edit, approve, deactivate, import, automatically apply, classify a loan transaction, select supporting evidence, calculate a tax filing, settle or eliminate intercompany balances, or post accounting. Source-field, mapping-exception, usage, and mapping-history catalogs remain separate unavailable read models.</p></>}
 </section>;
}
