import React,{useEffect,useMemo,useRef,useState} from 'react';
import {refreshAuthoritativeAccountRegister,refreshAuthoritativeChartOfAccounts} from './accounting-api.js';
import {StateBlock} from './ui.jsx';
import {AuthoritativeAccountRegisterView,AuthoritativeChartOfAccountsView} from './authoritative-coa-view.jsx';
import {AuthoritativeGeneralLedgerWorkspace} from './authoritative-general-ledger-workspace.jsx';
import {AuthoritativeAccountListReport} from './authoritative-reports-workspace.jsx';
import {AuthoritativeLineageDrill} from './authoritative-lineage-drill.jsx';

const REGISTER_PAGE_SIZES=Object.freeze([25,50,100]);
const COA_PAGE_SIZES=Object.freeze([25,50,100,200]);
const fixedMoney=value=>typeof value==='string'&&/^-?[0-9]+\.[0-9]{4}$/.test(value)?value:'Not returned';
const dash=value=>value===null||value===undefined||value===''?'—':value;
export const authoritativeCoaScopeText=(scope,config)=>{
  const presentation=config?.scopePresentation||{};
  const entity=presentation.entityLabel||'Configured entity';
  const period=presentation.periodLabel||scope?.period_code||'Configured period';
  return `${entity} · ${period}`;
};
const evidenceScope=(scope,config)=><p className="authoritative-coa-scope" title={`Entity ID: ${scope?.entityId}; Period ID: ${scope?.periodId}; API amounts use fixed four-decimal strings.`}>{authoritativeCoaScopeText(scope,config)} · balances by currency</p>;
const ErrorBlock=({state,onRetry})=>state.phase==='ERROR'?<StateBlock tone="error" title={state.error?.code||'ACCOUNTING_API_READ_FAILED'} actions={<button type="button" className="btn btn-sm" onClick={onRetry}>Retry read</button>}>{state.error?.message}</StateBlock>:null;
export const authoritativeRangeLabel=({page,pageSize,total,itemLabel='rows'})=>total?`Showing ${itemLabel} ${page*pageSize+1} to ${Math.min((page+1)*pageSize,total)} of ${total}`:`No ${itemLabel}`;
const Pagination=({page,pageCount,pageSize,total,onChange,label,itemLabel='rows'})=><nav className="authoritative-coa-pagination" aria-label={label}><span>{authoritativeRangeLabel({page,pageSize,total,itemLabel})}</span><button type="button" className="btn btn-sm btn-ghost" disabled={page===0} onClick={()=>onChange(page-1)}>Previous</button><button type="button" className="btn btn-sm btn-ghost" disabled={!pageCount||page>=pageCount-1} onClick={()=>onChange(page+1)}>Next</button></nav>;
const PageSize=({value,onChange,label,sizes=REGISTER_PAGE_SIZES})=><label className="authoritative-coa-page-size"><span>{label}</span><select value={value} onChange={event=>onChange(Number(event.target.value))}>{sizes.map(size=><option key={size} value={size}>{size}</option>)}</select></label>;
const pageRows=(rows,page,size)=>rows.slice(page*size,(page+1)*size);
const money4Minor=value=>{const match=/^(-?)([0-9]+)\.([0-9]{4})$/.exec(value||'');return match?(match[1]?-1n:1n)*BigInt(`${match[2]}${match[3]}`):null;};
const registerAmountQuery=value=>{const match=/^([<>]?)(\$?)([0-9]{1,18})(?:\.([0-9]{1,4}))?$/.exec(value.trim());return match?{operator:match[1],usd:match[2]==='$',minor:BigInt(`${match[3]}${(match[4]||'').padEnd(4,'0')}`)}:null;};
const matchesRegisterQuery=(row,query)=>{const needle=query.trim().toLowerCase();if(!needle)return true;const amountQuery=registerAmountQuery(needle);if(amountQuery){if(amountQuery.usd&&row.currency!=='USD')return false;const debit=money4Minor(row.debit_amount),credit=money4Minor(row.credit_amount);if(debit===null||credit===null)return false;const magnitude=(debit<0n?-debit:debit)+(credit<0n?-credit:credit);return amountQuery.operator==='>'?magnitude>amountQuery.minor:amountQuery.operator==='<'?magnitude<amountQuery.minor:magnitude===amountQuery.minor;}return `${row.journal_date} ${row.journal_number} ${row.member_ref||''} ${row.description||''}`.toLowerCase().includes(needle);};
const ISO_DATE=/^\d{4}-\d{2}-\d{2}$/;
const validRegisterDate=value=>{if(!ISO_DATE.test(value))return false;const parsed=new Date(`${value}T00:00:00.000Z`);return !Number.isNaN(parsed.valueOf())&&parsed.toISOString().slice(0,10)===value;};
export const filterAuthoritativeRegisterRows=(rows,{query='',from='',through=''}={})=>{if(from&&!validRegisterDate(from)||through&&!validRegisterDate(through)||from&&through&&from>through)return [];return rows.filter(row=>matchesRegisterQuery(row,query)&&(!from||row.journal_date>=from)&&(!through||row.journal_date<=through));};
export const restoreAuthoritativeCoaReturnContext=(environment,config,context,{table,getTable,focusId}={})=>{if(context?.entityId!==config?.entityId||context?.periodId!==config?.periodId)return false;const restore=()=>{try{environment?.scrollTo?.({top:context.scrollY,behavior:'auto'});}catch{}try{(getTable?.()||table)?.scrollTo?.({left:context.tableX,behavior:'auto'});}catch{}try{environment?.document?.getElementById?.(focusId)?.focus?.();}catch{}};try{environment?.setTimeout?.(restore,0);}catch{restore();}return true;};

function Register({config,selection,onBack,fetcher,environment=globalThis}){
  const {accountCode,accountName,returnContext}=selection;
  const [state,setState]=useState({phase:'LOADING',rows:[],error:null});
  const [query,setQuery]=useState('');const [dateRange,setDateRange]=useState({from:'',through:''});const [filterDraft,setFilterDraft]=useState({query:'',from:'',through:''});const [page,setPage]=useState(0);const [pageSize,setPageSize]=useState(25);const [detail,setDetail]=useState(null);const detailOpener=useRef(null);const registerTableRef=useRef(null);const filterDetailsRef=useRef(null);const detailScrollY=useRef(0);const detailTableX=useRef(0);
  const load=async()=>{setState(current=>({...current,phase:'LOADING',error:null}));const result=await refreshAuthoritativeAccountRegister({config,accountCode,fetcher});setState(result.ok?{phase:'READY',rows:result.rows,scope:result.scope,error:null}:{phase:'ERROR',rows:[],scope:null,error:result});};
  useEffect(()=>{void load();},[accountCode,config,fetcher]);
  const rows=useMemo(()=>filterAuthoritativeRegisterRows(state.rows,{query,from:dateRange.from,through:dateRange.through}),[state.rows,query,dateRange]);
  const pageCount=Math.ceil(rows.length/pageSize);const currentPage=Math.min(page,Math.max(pageCount-1,0));const visibleRows=pageRows(rows,currentPage,pageSize);
  const currencies=useMemo(()=>[...new Set(state.rows.map(row=>row.currency))],[state.rows]);
  const restoreText=[returnContext.query&&`account filter “${returnContext.query}”`,returnContext.status!=='ALL'&&`${returnContext.status.toLowerCase()} accounts`,returnContext.currency!=='ALL'&&returnContext.currency,`page ${returnContext.page+1}`].filter(Boolean).join(' | ');
  const periodStart=state.rows[0]?.period_start||config.scopePresentation?.periodStart||'',periodEnd=state.rows[0]?.period_end||config.scopePresentation?.periodEnd||'';
  const invalidDateRange=Boolean(filterDraft.from&&!validRegisterDate(filterDraft.from)||filterDraft.through&&!validRegisterDate(filterDraft.through)||filterDraft.from&&filterDraft.through&&filterDraft.from>filterDraft.through),dateOutOfScope=Boolean(filterDraft.from&&periodStart&&(filterDraft.from<periodStart||periodEnd&&filterDraft.from>periodEnd)||filterDraft.through&&periodEnd&&(filterDraft.through>periodEnd||periodStart&&filterDraft.through<periodStart)),invalidFilter=invalidDateRange||dateOutOfScope,dateFilterCount=Number(Boolean(dateRange.from))+Number(Boolean(dateRange.through));
  const resetRegisterFilters=()=>{setQuery('');setDateRange({from:'',through:''});setFilterDraft({query:'',from:'',through:''});setPage(0);};
  const applyRegisterFilters=()=>{if(invalidFilter)return;setQuery(filterDraft.query);setDateRange({from:filterDraft.from,through:filterDraft.through});setPage(0);if(filterDetailsRef.current)filterDetailsRef.current.open=false;};
  const openDetail=(row,index)=>{detailOpener.current=`authoritative-register-line-${row.ledger_line_id}-${index}`;detailScrollY.current=Number(environment?.scrollY)||0;detailTableX.current=Number(registerTableRef.current?.scrollLeft)||0;setDetail(row);};
  const closeDetail=()=>{setDetail(null);environment?.setTimeout?.(()=>{registerTableRef.current?.scrollTo?.({left:detailTableX.current,behavior:'auto'});environment?.document?.getElementById?.(detailOpener.current)?.focus?.();environment?.scrollTo?.({top:detailScrollY.current,behavior:'auto'});},0);};
  if(detail)return <AuthoritativeLineageDrill config={config} fetcher={fetcher} initial={{kind:'GL',row:detail,context:{entityId:config.entityId,periodId:config.periodId,journalEntryId:detail.journal_entry_id,journalLineId:detail.journal_line_id,ledgerLineId:detail.ledger_line_id}}} onExit={closeDetail}/>;
  return <AuthoritativeAccountRegisterView eyebrow="ACCOUNTING REGISTER" title="Account Register" subtitle="Posted activity for one account and period.">
    <div className="qbo-report-back authoritative-register-back"><button type="button" className="btn btn-sm btn-ghost" onClick={onBack}>Back to chart of accounts</button></div>
    <div className="authoritative-register-scope" aria-label="Account register scope"><span><i>Account</i><b>{accountName}</b><small>{accountCode}</small></span><span><i>Company / period</i><b>{authoritativeCoaScopeText(state.scope||config,config)}</b></span><span><i>Currency</i><b>{currencies.length?currencies.join(', '):'Not available'}</b></span><span><i>Posted entries</i><b>{state.phase==='READY'?state.rows.length:'—'}</b></span></div>
    <details className="authoritative-return-context authoritative-register-return"><summary>Chart of accounts filters retained</summary><span>{restoreText||'All accounts'}</span></details>
    <div className="authoritative-filter-bar authoritative-register-filter authoritative-ledger-toolbar"><details ref={filterDetailsRef} className="authoritative-list-more-filters authoritative-register-filter-disclosure" onToggle={event=>{if(event.currentTarget.open)setFilterDraft({query,from:dateRange.from,through:dateRange.through});}}><summary aria-label={query||dateFilterCount?`Filter, ${Number(Boolean(query))+dateFilterCount} active filters`:undefined}>Filter</summary><div className="authoritative-register-filter-panel"><label><span>Find</span><input maxLength={160} value={filterDraft.query} onChange={event=>setFilterDraft(current=>({...current,query:event.target.value}))} placeholder="Journal, member, memo, or amount"/></label><label><span>From</span><input type="date" min={periodStart||undefined} max={periodEnd||undefined} value={filterDraft.from} onChange={event=>setFilterDraft(current=>({...current,from:event.target.value}))}/></label><label><span>To</span><input type="date" min={periodStart||undefined} max={periodEnd||undefined} value={filterDraft.through} onChange={event=>setFilterDraft(current=>({...current,through:event.target.value}))}/></label><div className="authoritative-list-more-filter-actions">{invalidDateRange&&<span className="muted sm" role="alert">From must be on or before To.</span>}{dateOutOfScope&&<span className="muted sm" role="alert">Dates must stay within the selected period.</span>}<button type="button" className="btn btn-sm btn-ghost" onClick={()=>setFilterDraft({query:'',from:'',through:''})}>Reset</button><button type="button" className="btn btn-sm" disabled={invalidFilter} onClick={applyRegisterFilters}>Apply</button><button type="button" className="btn btn-sm btn-ghost" onClick={()=>{if(filterDetailsRef.current)filterDetailsRef.current.open=false;}}>Close</button></div></div></details><PageSize label="Rows per page" value={pageSize} onChange={size=>{setPageSize(size);setPage(0);}}/><span className="result-count" aria-live="polite"><b>{state.phase==='READY'?rows.length:'—'}</b> entries</span>{(query||dateFilterCount>0)&&<button type="button" className="btn btn-sm btn-ghost" onClick={resetRegisterFilters}>Clear filters</button>}<button type="button" className="btn btn-sm" disabled={state.phase==='LOADING'} onClick={load}>{state.phase==='LOADING'?'Loading…':'Refresh'}</button></div>
    {state.phase==='LOADING'&&<StateBlock tone="loading">Loading account activity…</StateBlock>}
    <ErrorBlock state={state} onRetry={load}/>
    {state.phase==='READY'&&!rows.length&&<StateBlock tone="empty" title={state.rows.length?'No entries match this filter':'No posted entries found'}>{state.rows.length?'Change or clear the filter.':'No posted entries were returned for this account and period. This does not describe activity outside the selected period.'}</StateBlock>}
    {state.phase==='READY'&&rows.length>0&&<><div ref={registerTableRef} className="table-wrap authoritative-register-table" tabIndex={0} aria-label="Account register; scroll horizontally to view every column"><table className="tbl"><thead><tr><th scope="col">Date</th><th scope="col">Journal</th><th scope="col">Member</th><th scope="col">Description</th><th scope="col">Currency</th><th scope="col" className="ta-r">Debit</th><th scope="col" className="ta-r">Credit</th><th scope="col" className="ta-r">Opening</th><th scope="col" className="ta-r">Running balance</th><th scope="col">Source documents</th><th scope="col">Details</th></tr></thead><tbody>{visibleRows.map((row,index)=><tr key={row.ledger_line_id}><td>{row.journal_date}</td><td><code>{row.journal_number}</code></td><td>{dash(row.member_ref)}</td><td>{dash(row.description)}</td><td>{row.currency}</td><td className="ta-r">{fixedMoney(row.debit_amount)}</td><td className="ta-r">{fixedMoney(row.credit_amount)}</td><td className="ta-r">{fixedMoney(row.opening_balance)}</td><td className="ta-r">{fixedMoney(row.running_balance)}</td><td>{row.source_document_ids.length?row.source_document_ids.map(id=><code key={id}>{id}</code>):'None'}</td><td><button id={`authoritative-register-line-${row.ledger_line_id}-${index}`} type="button" className="btn btn-sm" onClick={()=>openDetail(row,index)}>View details</button></td></tr>)}</tbody></table></div><Pagination page={currentPage} pageCount={pageCount} pageSize={pageSize} total={rows.length} onChange={setPage} label="Account register pages" itemLabel="entries"/></>}
  </AuthoritativeAccountRegisterView>;
}

export function AuthoritativeChartOfAccountsWorkspace({config,fetcher=globalThis.fetch,environment=globalThis}){
  const [state,setState]=useState({phase:'LOADING',rows:[],error:null});
  const [query,setQuery]=useState('');const [status,setStatus]=useState('ALL');const [currency,setCurrency]=useState('ALL');const [page,setPage]=useState(0);const [pageSize,setPageSize]=useState(200);const [selection,setSelection]=useState(null);const openerRef=useRef(null);const tableRef=useRef(null);
  const load=async()=>{setState(current=>({...current,phase:'LOADING',error:null}));const result=await refreshAuthoritativeChartOfAccounts({config,fetcher});setState(result.ok?{phase:'READY',rows:result.rows,scope:result.scope,error:null}:{phase:'ERROR',rows:[],scope:null,error:result});};
  useEffect(()=>{void load();},[config,fetcher]);
  const currencies=useMemo(()=>[...new Set(state.rows.map(row=>row.currency).filter(Boolean))].sort(),[state.rows]);
  const rows=useMemo(()=>state.rows.filter(row=>{const matchesQuery=`${row.account_code} ${row.account_name}`.toLowerCase().includes(query.trim().toLowerCase());const matchesStatus=status==='ALL'||(status==='ACTIVE'?row.active:!row.active);const matchesCurrency=currency==='ALL'||row.currency===currency;return matchesQuery&&matchesStatus&&matchesCurrency;}),[state.rows,query,status,currency]);
  const pageCount=Math.ceil(rows.length/pageSize);const currentPage=Math.min(page,Math.max(pageCount-1,0));const visibleRows=pageRows(rows,currentPage,pageSize);
  const resetFilters=()=>{setQuery('');setStatus('ALL');setCurrency('ALL');setPage(0);};
  const returnContext=()=>({entityId:config.entityId,periodId:config.periodId,entityLabel:config.scopePresentation?.entityLabel,periodLabel:config.scopePresentation?.periodLabel,query,status,currency,page:currentPage,pageSize,scrollY:Number(environment?.scrollY)||0,tableX:Number(tableRef.current?.scrollLeft)||0});
  const openAccountList=()=>{openerRef.current='authoritative-coa-run-report';setSelection({kind:'ACCOUNT_LIST',page:0,returnContext:returnContext()});};
  const openAccountView=(kind,row,index)=>{openerRef.current=`authoritative-coa-${kind.toLowerCase()}-${row.account_code}-${row.currency||'none'}-${index}`;setSelection({kind,accountCode:row.account_code,accountName:row.account_name,returnContext:{entityId:config.entityId,periodId:config.periodId,query,status,currency,page:currentPage,pageSize,scrollY:Number(environment?.scrollY)||0,tableX:Number(tableRef.current?.scrollLeft)||0}});};
  const closeAccountView=()=>{const context=selection?.returnContext;setSelection(null);restoreAuthoritativeCoaReturnContext(environment,config,context,{getTable:()=>tableRef.current,focusId:openerRef.current});};
  if(selection?.kind==='ACCOUNT_LIST')return <AuthoritativeAccountListReport state={state} returnContext={selection.returnContext} page={selection.page||0} onPageChange={page=>setSelection(current=>current?.kind==='ACCOUNT_LIST'?{...current,page}:current)} onRefresh={load} backLabel="Back to chart of accounts" onBack={closeAccountView}/>;
  if(selection?.kind==='REPORT')return <AuthoritativeGeneralLedgerWorkspace config={config} fetcher={fetcher} environment={environment} initialAccountCode={selection.accountCode} workspaceTitle="Account QuickReport" workspaceSubtitle={`Posted activity for ${selection.accountName}.`} backLabel="Back to chart of accounts" onBack={closeAccountView}/>;
  if(selection)return <Register config={config} fetcher={fetcher} environment={environment} selection={selection} onBack={closeAccountView}/>;
  return <AuthoritativeChartOfAccountsView eyebrow="ACCOUNTING" title="Chart of accounts" subtitle="Review accounts and posted balances." actions={<button id="authoritative-coa-run-report" type="button" className="btn btn-sm" disabled={state.phase==='LOADING'} onClick={openAccountList}>Run report</button>}>
    <div className="authoritative-filter-bar authoritative-coa-filter authoritative-ledger-toolbar" aria-label="Chart of Accounts filters"><label className="authoritative-coa-query-filter"><span>Search</span><input value={query} onChange={event=>{setQuery(event.target.value);setPage(0);}} placeholder="Filter by name or number"/></label><label className="authoritative-coa-status-filter"><span>Status</span><select value={status} onChange={event=>{setStatus(event.target.value);setPage(0);}}><option value="ALL">All statuses</option><option value="ACTIVE">Active</option><option value="INACTIVE">Inactive</option></select></label><label className="authoritative-coa-currency-filter"><span>Currency</span><select value={currency} onChange={event=>{setCurrency(event.target.value);setPage(0);}}><option value="ALL">All currencies</option>{currencies.map(value=><option key={value} value={value}>{value}</option>)}</select></label><PageSize label="Rows per page" value={pageSize} sizes={COA_PAGE_SIZES} onChange={size=>{setPageSize(size);setPage(0);}}/><span className="result-count" aria-live="polite"><b>{state.phase==='READY'?rows.length:'—'}</b> shown</span>{(query||status!=='ALL'||currency!=='ALL')&&<button type="button" className="btn btn-sm btn-ghost authoritative-coa-clear" onClick={resetFilters}>Clear filters</button>}<button type="button" className="btn btn-sm" disabled={state.phase==='LOADING'} onClick={load}>{state.phase==='LOADING'?'Loading…':'Refresh'}</button></div>
    {evidenceScope(state.scope||{entityId:config.entityId,periodId:config.periodId},config)}
    {state.phase==='LOADING'&&<StateBlock tone="loading">Loading accounts and posted balances…</StateBlock>}
    <ErrorBlock state={state} onRetry={load}/>
    {state.phase==='READY'&&!rows.length&&<StateBlock tone="empty" title={state.rows.length?'No accounts match these filters':'No accounts returned'}>{state.rows.length?'Change or clear the filters.':'No accounts were returned for this company and period.'}</StateBlock>}
    {state.phase==='READY'&&rows.length>0&&<><div ref={tableRef} className="table-wrap authoritative-coa-table" tabIndex={0} aria-label="Chart of Accounts"><table className="tbl"><thead><tr><th scope="col">Account</th><th scope="col">Name</th><th scope="col">Member rule</th><th scope="col">Status</th><th scope="col">Currency</th><th scope="col" className="ta-r">Opening</th><th scope="col" className="ta-r">Period debit</th><th scope="col" className="ta-r">Period credit</th><th scope="col" className="ta-r">Ending</th><th scope="col" className="ta-r">Posted lines</th><th scope="col">Action</th></tr></thead><tbody>{visibleRows.map((row,index)=><tr key={`${row.account_code}:${row.currency||'none'}:${index}`}><td data-label="Account"><code>{row.account_code}</code></td><td data-label="Name">{row.account_name}</td><td data-label="Member rule">{row.requires_member?row.required_member_type||'Required':'None'}</td><td data-label="Status"><span className={`authoritative-status ${row.active?'is-active':'is-inactive'}`}>{row.active?'Active':'Inactive'}</span></td><td data-label="Currency">{row.currency||'Not available'}</td><td data-label="Opening" className="ta-r">{row.opening_balance===null?'—':fixedMoney(row.opening_balance)}</td><td data-label="Period debit" className="ta-r">{row.period_debit===null?'—':fixedMoney(row.period_debit)}</td><td data-label="Period credit" className="ta-r">{row.period_credit===null?'—':fixedMoney(row.period_credit)}</td><td data-label="Ending" className="ta-r">{row.ending_balance===null?'—':fixedMoney(row.ending_balance)}</td><td data-label="Posted lines" className="ta-r">{row.posted_ledger_line_count}</td><td data-label="Action"><div className="authoritative-coa-row-actions" role="group" aria-label={`Account views for ${row.account_name}`}><button id={`authoritative-coa-register-${row.account_code}-${row.currency||'none'}-${index}`} type="button" className="btn btn-sm" onClick={()=>openAccountView('REGISTER',row,index)}>View register</button><details className="authoritative-coa-action-menu"><summary aria-label={`More account actions for ${row.account_name}`}><span className="sr-only">More account actions</span></summary><button id={`authoritative-coa-report-${row.account_code}-${row.currency||'none'}-${index}`} type="button" className="btn btn-sm btn-ghost" onClick={()=>openAccountView('REPORT',row,index)}>Run report</button></details></div></td></tr>)}</tbody></table></div><Pagination page={currentPage} pageCount={pageCount} pageSize={pageSize} total={rows.length} onChange={setPage} label="Chart of Accounts pages" itemLabel="accounts"/></>}
  </AuthoritativeChartOfAccountsView>;
}
