import React,{useEffect,useState} from 'react';
import {activateAuthoritativeWbsReadAccess,refreshAuthoritativeWbsH1ImportInventory,refreshAuthoritativeWbsH1AccountingSettingsProposal,readAuthoritativeWbsH1AccountingSettingsDecision,decideAuthoritativeWbsH1AccountingSettings,refreshAuthoritativeWbsH1PayableAccountingProposal,createAuthoritativeWbsH1PayableReclassDraft,readAuthoritativeJournalEntryDetail} from './accounting-api.js';
import {StateBlock} from './ui.jsx';
import {AuthoritativeWorkspaceView,AuthoritativeWorkspaceHeader} from './authoritative-workbench-view.jsx';
import {AuthoritativeLineageDrill} from './authoritative-lineage-drill.jsx';
import {DEFAULT_AUTHORITATIVE_LIST_VIEW,createAuthoritativeReturnContext,restoreAuthoritativeReturnContext} from './authoritative-list-context.js';

const PAGE_SIZE=50;
const label=value=>value===null?'Not available':value;
const mappingLabel=value=>({MAPPING_MISSING:'Mapping missing',MAPPING_READY_FOR_REVIEW:'Ready for mapping review',MAPPING_AMBIGUOUS:'Mapping ambiguous',FORMAL_MAPPING_POSTED:'Formally mapped and posted'}[value]||value);
const importLabel=value=>value==='CONTROLLED_TEST_POSTED'?'Controlled test posted':'Imported source only';
const proposalException=value=>({SETTINGS_NOT_APPROVED:'Settings approval required',COST_CODE_MISSING:'Cost code missing',PROJECT_MISSING:'Project missing',VENDOR_MISSING:'Payee missing',DEBIT_MAPPING_MISSING:'Debit mapping missing',DEBIT_MAPPING_AMBIGUOUS:'Debit mapping ambiguous',CREDIT_MAPPING_MISSING:'Credit mapping missing',CREDIT_MAPPING_AMBIGUOUS:'Credit mapping ambiguous',DEBIT_ACCOUNT_NOT_READY:'Debit account not ready',CREDIT_ACCOUNT_NOT_READY:'Credit account not ready',DEBIT_MEMBER_POLICY_UNSUPPORTED:'Debit member policy unsupported',CREDIT_MEMBER_POLICY_UNSUPPORTED:'Credit member policy unsupported',VENDOR_MEMBER_NOT_READY:'Payee member not ready',DEBIT_DIMENSION_UNSUPPORTED:'Debit dimension unsupported',CREDIT_DIMENSION_UNSUPPORTED:'Credit dimension unsupported'}[value]||value);

const companyScopes=scopes=>{
  const companies=new Map();
  for(const scope of Array.isArray(scopes)?scopes:[]){
    if(!scope?.entity_id||!scope?.period_id||companies.has(scope.entity_id))continue;
    companies.set(scope.entity_id,{entityId:scope.entity_id,periodId:scope.period_id,entityName:scope.entity_name,entityCode:scope.entity_code});
  }
  return [...companies.values()].sort((left,right)=>String(left.entityName||left.entityCode).localeCompare(String(right.entityName||right.entityCode)));
};

export function AuthoritativeWbsH1ImportWorkspace({config,scopes=[],fetcher=globalThis.fetch,environment=globalThis,onOpenJournalWorkflow}){
  const [offset,setOffset]=useState(0);
  const [state,setState]=useState({phase:'LOADING',data:null,error:null});
  const [settings,setSettings]=useState({phase:'LOADING',data:null,error:null});
  const [decision,setDecision]=useState({phase:'IDLE',data:null,error:null});
  const [decisionReason,setDecisionReason]=useState('');
  const [proposalOffset,setProposalOffset]=useState(0);
  const [proposals,setProposals]=useState({phase:'LOADING',data:null,error:null});
  const [draftReason,setDraftReason]=useState('');
  const [drafts,setDrafts]=useState({});
  const [draftDetail,setDraftDetail]=useState(null);
  const [companyPopulation,setCompanyPopulation]=useState({phase:'LOADING',rows:[]});
  const [access,setAccess]=useState({phase:'IDLE',version:0,error:null});
  const load=async nextOffset=>{
    setState(current=>({...current,phase:'LOADING',error:null}));
    const result=await refreshAuthoritativeWbsH1ImportInventory({config,limit:PAGE_SIZE,offset:nextOffset,fetcher});
    setState(current=>result.ok?{phase:'READY',data:result.data,error:null}:{phase:'BLOCKED',data:current.data,error:result});
  };
  const loadProposals=async nextOffset=>{setProposals(current=>({...current,phase:'LOADING',error:null}));const result=await refreshAuthoritativeWbsH1PayableAccountingProposal({config,limit:PAGE_SIZE,offset:nextOffset,fetcher});setProposals(current=>result.ok?{phase:'READY',data:result.data,error:null}:{phase:'BLOCKED',data:current.data,error:result});};
  const loadSettings=async()=>{setSettings(current=>({...current,phase:'LOADING',error:null}));setDecision({phase:'LOADING',data:null,error:null});const result=await refreshAuthoritativeWbsH1AccountingSettingsProposal({config,fetcher});setSettings(result.ok?{phase:'READY',data:result.data,error:null}:{phase:'BLOCKED',data:null,error:result});if(!result.ok){setDecision({phase:'IDLE',data:null,error:null});return;}const existing=await readAuthoritativeWbsH1AccountingSettingsDecision({config,proposalHash:result.data.proposal_hash,fetcher});setDecision(existing.ok?{phase:'READY',data:existing.data,error:null}:{phase:'BLOCKED',data:null,error:existing});};
  const decide=async outcome=>{const proposal=settings.data;if(!proposal)return;setDecision(current=>({...current,phase:'SAVING',error:null}));const key=`wbs-h1-settings-${globalThis.crypto?.randomUUID?.()||Date.now()}`;const result=await decideAuthoritativeWbsH1AccountingSettings({config,proposalHash:proposal.proposal_hash,outcome,reason:decisionReason,idempotencyKey:key,fetcher});setDecision(result.ok?{phase:'READY',data:result.data,error:null}:{phase:'BLOCKED',data:null,error:result});if(result.ok){setDecisionReason('');setProposalOffset(0);void loadProposals(0);}};
  const closeDraftDetail=()=>{const context=draftDetail?.returnContext;setDraftDetail(null);restoreAuthoritativeReturnContext(environment,config,context,{getTable:()=>environment?.document?.querySelector?.('.authoritative-wbs-h1-proposal-table')});};
  const openDraftDetail=async(receipt,proposal,focusId,tableX=0)=>{
    const base=createAuthoritativeReturnContext({config,view:{...DEFAULT_AUTHORITATIVE_LIST_VIEW,page:Math.floor(proposalOffset/PAGE_SIZE)+1,pageSize:PAGE_SIZE},focusId,scrollY:Number(environment?.scrollY)||0,tableX});
    if(!base)return;
    const returnContext=Object.freeze({...base,sourceRecordHash:proposal.source_record_hash,journalId:receipt.journal_entry_id});
    setDraftDetail({phase:'LOADING',receipt,returnContext,error:null});
    const result=await readAuthoritativeJournalEntryDetail({config,journalEntryId:receipt.journal_entry_id,fetcher});
    setDraftDetail(result.ok?{phase:'READY',receipt,journal:result.journal,returnContext,error:null}:{phase:'BLOCKED',receipt,returnContext,error:result});
  };
  const createDraft=async(proposal,focusId,tableX)=>{setDrafts(current=>({...current,[proposal.source_record_hash]:{phase:'SAVING'}}));const key=`wbs-h1-payable-draft-${globalThis.crypto?.randomUUID?.()||Date.now()}`;const result=await createAuthoritativeWbsH1PayableReclassDraft({config,proposal,reason:draftReason,idempotencyKey:key,fetcher});setDrafts(current=>({...current,[proposal.source_record_hash]:result.ok?{phase:'READY',data:result.data}:{phase:'BLOCKED',error:result}}));if(result.ok)await openDraftDetail(result.data,proposal,focusId,tableX);};
  const activateWbsRead=async()=>{setAccess(current=>({...current,phase:'SAVING',error:null}));const key=`wbs-read-access-${globalThis.crypto?.randomUUID?.()||Date.now()}`;const result=await activateAuthoritativeWbsReadAccess({config,idempotencyKey:key,fetcher});setAccess(current=>result.ok?{phase:'READY',version:current.version+1,error:null}:{...current,phase:'BLOCKED',error:result});};
  useEffect(()=>{setOffset(0);setProposalOffset(0);void load(0);void loadSettings();void loadProposals(0);},[config.entityId,config.periodId,access.version]);
  useEffect(()=>{let active=true;const companies=companyScopes(scopes);if(companies.length===0){setCompanyPopulation({phase:'BLOCKED',rows:[]});return()=>{active=false;};}setCompanyPopulation({phase:'LOADING',rows:[]});void(async()=>{const rows=[];for(let index=0;index<companies.length;index+=6){const batch=companies.slice(index,index+6);const results=await Promise.all(batch.map(async company=>{const scopedConfig={...config,entityId:company.entityId,periodId:company.periodId};const result=await refreshAuthoritativeWbsH1ImportInventory({config:scopedConfig,limit:1,offset:0,fetcher});return result.ok?{...company,status:'READY',inventory:result.data}:{...company,status:'BLOCKED',error:result};}));rows.push(...results);if(active)setCompanyPopulation({phase:index+6>=companies.length?'READY':'LOADING',rows:[...rows]});}})();return()=>{active=false;};},[config.baseUrl,config.getAccessToken,fetcher,scopes,access.version]);
  const data=state.data,total=data?.totals.source_record_count||0,page=Math.floor(offset/PAGE_SIZE)+1,pageCount=Math.max(1,Math.ceil(total/PAGE_SIZE));
  const wbsReadRequired=state.error?.code==='WBS_READ_ACCESS_REQUIRED'||companyPopulation.rows.some(row=>row.error?.code==='WBS_READ_ACCESS_REQUIRED');
  const move=next=>{setOffset(next);void load(next);};
  if(draftDetail?.phase==='READY')return <AuthoritativeLineageDrill config={config} fetcher={fetcher} initial={{kind:'JOURNAL',journal:draftDetail.journal,context:{entityId:config.entityId,periodId:config.periodId,journalId:draftDetail.journal.journal_entry_id,journalRevision:draftDetail.journal.revision,journalCurrency:draftDetail.journal.currency}}} onExit={closeDraftDetail}/>;
  if(draftDetail)return <section className="full-bleed qbo-transaction-report authoritative-evidence-page" aria-label="Created WBS Draft Journal"><div className="qbo-report-back"><button type="button" className="btn btn-sm btn-ghost" onClick={closeDraftDetail}>Back to WBS Integration Hub</button><span>Draft Journal {draftDetail.receipt.journal_entry_id}</span></div><StateBlock tone={draftDetail.phase==='LOADING'?'loading':'blocked'} title={draftDetail.phase==='LOADING'?'Loading created Draft Journal':'Created Draft Journal unavailable'}>{draftDetail.phase==='LOADING'?'Re-reading the exact company, period, Journal, lines, and source relationship.':draftDetail.error?.message||'The Draft was created, but its exact Journal detail could not be read. Return and refresh before continuing.'}</StateBlock></section>;
  return <AuthoritativeWorkspaceView area="WBS Data Import" className="stack authoritative-wbs-h1-import-workspace">
    <AuthoritativeWorkspaceHeader eyebrow="WBS DATA IMPORT" title="2026 H1 business data" description="Real WBS business rows are shown under the selected company before formal accounting mapping." status="READ ONLY"/>
    {wbsReadRequired&&<StateBlock tone="blocked" title="WBS read access required"><div className="stack"><span>Enable the additional read-only permission needed to show this company's WBS source and mapping evidence. This does not allow importing, approving or posting.</span><div><button type="button" className="btn btn-primary" onClick={()=>void activateWbsRead()} disabled={access.phase==='SAVING'}>{access.phase==='SAVING'?'Enabling…':'Enable WBS read access'}</button></div>{access.phase==='BLOCKED'&&<span>{access.error?.message}</span>}</div></StateBlock>}
    <section className="report-workbench" aria-label="All authorized WBS companies">
      <div className="report-workbench-head"><div><b>All companies</b><div className="page-subtitle">January–June source, mapping and formal-posting progress for every company available to this signed-in user.</div></div><span className="badge badge-muted">AUTHORIZED SCOPE</span></div>
      {companyPopulation.phase==='LOADING'&&companyPopulation.rows.length===0&&<StateBlock tone="loading" title="Loading company population">Reading each authorized WBS company from the accounting API.</StateBlock>}
      {companyPopulation.phase==='BLOCKED'&&companyPopulation.rows.length===0&&<StateBlock tone="blocked" title="Company population unavailable">No authorized company scopes were returned. Missing companies are not treated as zero.</StateBlock>}
      {companyPopulation.rows.length>0&&<div className="table-wrap" role="region" tabIndex={0} aria-label="All authorized WBS company H1 progress"><table className="tbl"><thead><tr><th>Company</th><th>H1 source rows</th><th>Mapping ready</th><th>Mapping exceptions</th><th>Formal postings</th><th>Status</th></tr></thead><tbody>{companyPopulation.rows.map(row=>{const totals=row.inventory?.totals,exceptions=totals?totals.mapping_missing_count+totals.mapping_ambiguous_count:null;return <tr key={row.entityId}><td><b>{row.entityName||row.entityCode}</b><div className="page-subtitle">{row.inventory?.company_code||row.entityCode}</div></td><td>{totals?.source_record_count??'Unavailable'}</td><td>{totals?.mapping_ready_count??'Unavailable'}</td><td>{exceptions??'Unavailable'}</td><td>{totals?.formal_mapping_posted_count??'Unavailable'}</td><td>{row.status==='BLOCKED'?<span className="badge badge-muted" title={row.error?.message}>READ FAILED</span>:totals.source_record_count>0&&totals.formal_mapping_posted_count===totals.source_record_count?<span className="badge badge-muted">FORMALLY POSTED</span>:exceptions>0?<span className="badge badge-muted">NEEDS MAPPING</span>:<span className="badge badge-muted">IN PROGRESS</span>}</td></tr>;})}</tbody></table></div>}
      {companyPopulation.phase==='LOADING'&&companyPopulation.rows.length>0&&<div className="page-subtitle">Loading remaining authorized companies…</div>}
      {companyPopulation.rows.some(row=>row.status==='BLOCKED')&&<StateBlock tone="blocked" title="Some companies could not be read">The failed company scopes remain visible as unavailable and are not counted as empty.</StateBlock>}
    </section>
    {state.phase==='LOADING'&&!data&&<StateBlock tone="loading" title="Loading WBS business data">Reading the selected company's January–June import inventory.</StateBlock>}
    {state.phase==='BLOCKED'&&!data&&<StateBlock tone="blocked" title={state.error?.code||'WBS_H1_IMPORT_INVENTORY_BLOCKED'}>{state.error?.message}</StateBlock>}
    {data&&<>
      {state.phase==='BLOCKED'&&<StateBlock tone="blocked" title={state.error?.code||'Refresh failed'}>{state.error?.message} The previously loaded inventory remains below.</StateBlock>}
      <div className="qbo-toolgrid" aria-label="WBS H1 import totals">
        <span><i>Company</i><b>{data.company_code}</b></span><span><i>Imported rows</i><b>{data.totals.source_record_count}</b></span><span><i>Source amount</i><b>{data.currency} {data.totals.source_amount}</b></span><span><i>Formal postings</i><b>{data.totals.formal_mapping_posted_count}</b></span>
      </div>
      <StateBlock tone={data.totals.mapping_missing_count||data.totals.mapping_ambiguous_count?'blocked':'empty'} title={data.totals.source_record_count?'Imported business data is available':'No H1 business data found'}>
        {data.totals.source_record_count?`${data.totals.controlled_test_posted_count} rows have controlled test postings; ${data.totals.mapping_ready_count} are ready for mapping review; ${data.totals.mapping_missing_count} have no matching WBS mapping. Imported source rows are not formal ledger entries.`:'No January–June WBS Payables have been staged for this company.'}
      </StateBlock>
      <section className="report-workbench" aria-label="WBS exact account Settings">
        <div className="report-workbench-head"><div><b>WBS account Settings</b><div className="page-subtitle">Exact Payable debit rules for {data.company_code} and {config.scopePresentation?.periodLabel||'the selected period'}.</div></div><button type="button" className="btn" onClick={loadSettings} disabled={settings.phase==='LOADING'}>{settings.phase==='LOADING'?'Refreshing…':'Refresh'}</button></div>
        {settings.phase==='LOADING'&&!settings.data&&<StateBlock tone="loading" title="Loading WBS account Settings">Reading the selected company's exact account rules.</StateBlock>}
        {settings.phase==='BLOCKED'&&<StateBlock tone="blocked" title={settings.error?.code||'WBS_SETTINGS_BLOCKED'}>{settings.error?.message}</StateBlock>}
        {settings.data&&<><div className="qbo-toolgrid" aria-label="WBS account Settings totals"><span><i>Source rules</i><b>{settings.data.source_setting_count}</b></span><span><i>Ready to review</i><b>{settings.data.ready_rule_count}</b></span><span><i>Blocked defaults</i><b>{settings.data.blocked_rule_count}</b></span><span><i>Exceptions</i><b>{settings.data.exception_count}</b></span></div>{settings.data.rules.length===0?<StateBlock tone="empty" title="No WBS account Settings found">This company has no staged Payable debit rules covering the selected period.</StateBlock>:<div className="table-wrap" role="region" tabIndex={0} aria-label="WBS exact account Settings"><table className="tbl"><thead><tr><th>WBS rule</th><th>Cost code</th><th>Account</th><th>Required dimension</th><th>Decision</th></tr></thead><tbody>{settings.data.rules.map(rule=><tr key={rule.rule_id}><td title={rule.source_setting_hash}>{rule.wbs_setting_id}</td><td>{rule.detail||'Default'}</td><td>{rule.account_code===null?'Not assigned':`${rule.account_code} · ${rule.account_name}`}</td><td>{rule.supplementary||'None'}</td><td>{rule.decision==='READY_FOR_HUMAN_REVIEW'?'Ready for review':rule.decision==='BLOCKED_DEFAULT'?'Blocked default':rule.decision==='MAPPING_AMBIGUOUS'?'Mapping ambiguous':rule.decision==='ACCOUNT_NOT_READY'?'Account not ready':'Mapping missing'}</td></tr>)}</tbody></table></div>}<div className="page-subtitle">Proposal {settings.data.proposal_hash.slice(0,18)}… · A Controller decision approves Settings only; it never creates or posts a Journal.</div>
          {decision.phase==='BLOCKED'&&<StateBlock tone="blocked" title={decision.error?.code||'SETTINGS_DECISION_BLOCKED'}>{decision.error?.message}</StateBlock>}
          {decision.data?<StateBlock tone="empty" title={`Controller ${decision.data.outcome==='APPROVED'?'approved':'rejected'} these Settings`}>{decision.data.outcome==='APPROVED'?`${decision.data.approved_rule_count} exact WBS rules are approved for this period.`:'The proposal remains unavailable for accounting use.'} Decision {decision.data.decision_hash.slice(0,18)}… No Draft or posting action was created.</StateBlock>:<div className="stack" aria-label="Controller Settings decision"><label>Review reason<textarea value={decisionReason} onChange={event=>setDecisionReason(event.target.value)} minLength={8} maxLength={2000} rows={3} placeholder="Explain why these exact WBS account rules should be approved or rejected."/></label><div className="row"><button type="button" className="btn btn-primary" disabled={decision.phase==='SAVING'||decisionReason.trim().length<8||settings.data.status!=='READY_FOR_HUMAN_REVIEW'||settings.data.ready_rule_count<1} onClick={()=>void decide('APPROVED')}>Approve Settings</button><button type="button" className="btn" disabled={decision.phase==='SAVING'||decisionReason.trim().length<8} onClick={()=>void decide('REJECTED')}>Reject</button><span className="badge badge-muted">SETTINGS ONLY</span></div></div>}
        </>}
      </section>
      <section className="report-workbench" aria-label="WBS Payable accounting proposals">
        <div className="report-workbench-head"><div><b>Payable accounting proposals</b><div className="page-subtitle">WBS business facts matched to exact debit and credit Settings. Suggestions remain read-only until a separate human accounting workflow is opened.</div></div><button type="button" className="btn" onClick={()=>loadProposals(proposalOffset)} disabled={proposals.phase==='LOADING'}>{proposals.phase==='LOADING'?'Refreshing…':'Refresh'}</button></div>
        {proposals.phase==='LOADING'&&!proposals.data&&<StateBlock tone="loading" title="Preparing accounting proposals">Matching the selected company and period to approved WBS Settings.</StateBlock>}
        {proposals.phase==='BLOCKED'&&!proposals.data&&<StateBlock tone="blocked" title={proposals.error?.code||'WBS_PAYABLE_PROPOSALS_BLOCKED'}>{proposals.error?.message}</StateBlock>}
        {proposals.data&&<>{proposals.phase==='BLOCKED'&&<StateBlock tone="blocked" title={proposals.error?.code||'Refresh failed'}>{proposals.error?.message} The previously loaded proposal page remains below.</StateBlock>}
          <label>Draft reason<textarea value={draftReason} onChange={event=>setDraftReason(event.target.value)} minLength={8} maxLength={2000} rows={2} placeholder="Explain why this approved WBS mapping should become a Draft."/></label>
          <div className="qbo-toolgrid" aria-label="WBS Payable proposal totals"><span><i>Source rows</i><b>{proposals.data.source_record_count}</b></span><span><i>Ready to review</i><b>{proposals.data.ready_count}</b></span><span><i>Exceptions</i><b>{proposals.data.exception_count}</b></span><span><i>Settings</i><b>{proposals.data.settings_outcome==='APPROVED'?'Approved':proposals.data.settings_outcome==='REJECTED'?'Rejected':'Not decided'}</b></span></div>
          {proposals.data.rows.length===0?<StateBlock tone="empty" title="No Payable proposals on this page">Choose another period or return to the previous page.</StateBlock>:<div className="table-wrap authoritative-wbs-h1-proposal-table" role="region" tabIndex={0} aria-label="WBS Payable proposal and exception queue"><table className="tbl"><thead><tr><th>Date</th><th>Source amount</th><th>Project / cost code</th><th>Suggested entry</th><th>Status / action</th></tr></thead><tbody>{proposals.data.rows.map(row=>{const draft=drafts[row.source_record_hash],focusId=`wbs-h1-draft-${row.source_record_hash.slice(-16)}`;return <tr key={row.source_record_hash}><td>{row.accounting_date}</td><td>{proposals.data.currency} {row.amount}</td><td>{label(row.project_code)} / {label(row.cost_code)}</td><td>{row.proposed_lines.length===0?'Not available':row.proposed_lines.map(line=><div key={line.line_number}>{line.side==='DEBIT'?'Dr':'Cr'} {line.account_code} · {line.account_name} · {proposals.data.currency} {line.amount}</div>)}</td><td>{draft?.phase==='READY'?<><span className="badge badge-muted">DRAFT CREATED</span><div className="page-subtitle">Journal {draft.data.journal_entry_id}</div><div className="row-acts"><button id={focusId} type="button" className="btn btn-sm" onClick={event=>void openDraftDetail(draft.data,row,focusId,Number(event.currentTarget.closest('.table-wrap')?.scrollLeft)||0)}>View Draft</button>{onOpenJournalWorkflow&&<button type="button" className="btn btn-sm btn-primary" onClick={()=>void onOpenJournalWorkflow(draft.data)}>Continue in Journal entries</button>}</div></>:row.status==='READY_FOR_CONTROLLER_REVIEW'?<><span className="badge badge-muted">READY TO REVIEW</span><div><button id={focusId} type="button" className="btn btn-primary" disabled={draft?.phase==='SAVING'||draftReason.trim().length<8} onClick={event=>void createDraft(row,focusId,Number(event.currentTarget.closest('.table-wrap')?.scrollLeft)||0)}>{draft?.phase==='SAVING'?'Creating…':'Create Draft'}</button></div>{draft?.phase==='BLOCKED'?<div className="page-subtitle">{draft.error.code}: {draft.error.message}</div>:<div className="page-subtitle">Human Draft only · no Submit, Review, Approve or Post</div>}</>:<><span className="badge badge-muted">EXCEPTION</span><div>{row.exception_codes.map(proposalException).join(' · ')}</div></>}</td></tr>;})}</tbody></table></div>}
          <div className="pagination"><button type="button" className="btn" disabled={proposalOffset===0||proposals.phase==='LOADING'} onClick={()=>{const next=Math.max(0,proposalOffset-PAGE_SIZE);setProposalOffset(next);void loadProposals(next);}}>Previous</button><span>Rows {proposals.data.source_record_count===0?0:proposalOffset+1}–{Math.min(proposalOffset+proposals.data.rows.length,proposals.data.source_record_count)} of {proposals.data.source_record_count}</span><button type="button" className="btn" disabled={proposalOffset+PAGE_SIZE>=proposals.data.source_record_count||proposals.phase==='LOADING'} onClick={()=>{const next=proposalOffset+PAGE_SIZE;setProposalOffset(next);void loadProposals(next);}}>Next</button></div>
          <div className="page-subtitle">Queue {proposals.data.proposal_hash.slice(0,18)}… · Creating a Draft is a separate human action. Submit, Review, Approve and Post remain separate.</div>
        </>}
      </section>
      <section className="report-workbench" aria-label="Monthly WBS import summary">
        <div className="report-workbench-head"><div><b>January–June population</b><div className="page-subtitle">The counts and amounts come from retained company-scoped WBS source facts.</div></div><button type="button" className="btn" onClick={()=>load(offset)} disabled={state.phase==='LOADING'}>{state.phase==='LOADING'?'Refreshing…':'Refresh'}</button></div>
        <div className="table-wrap" role="region" tabIndex={0} aria-label="Monthly WBS import summary"><table className="tbl"><thead><tr><th>Period</th><th>Rows</th><th>Source amount</th><th>Test posted</th><th>Mapping ready</th><th>Mapping missing</th><th>Formal posted</th></tr></thead><tbody>{data.months.map(month=><tr key={month.period_code}><td>{month.period_code}</td><td>{month.source_record_count}</td><td>{data.currency} {month.source_amount}</td><td>{month.controlled_test_posted_count}</td><td>{month.mapping_ready_count}</td><td>{month.mapping_missing_count+month.mapping_ambiguous_count}</td><td>{month.formal_mapping_posted_count}</td></tr>)}</tbody></table></div>
      </section>
      <section className="report-workbench" aria-label="Imported WBS business rows">
        <div className="report-workbench-head"><div><b>Imported business rows</b><div className="page-subtitle">Page {page} of {pageCount}. Source hashes are immutable REFS evidence identities.</div></div><span className="badge badge-muted">NO ACCOUNTING ACTION</span></div>
        {data.rows.length===0?<StateBlock tone="empty" title="No rows on this page">Return to the previous page or import the company's source population.</StateBlock>:<div className="table-wrap" role="region" tabIndex={0} aria-label="Imported WBS business rows"><table className="tbl"><thead><tr><th>Date</th><th>Amount</th><th>Project</th><th>Cost code</th><th>Payee reference</th><th>Import state</th><th>Mapping state</th><th>Source evidence</th></tr></thead><tbody>{data.rows.map(row=><tr key={row.source_record_hash}><td>{row.accounting_date}</td><td>{data.currency} {row.amount}</td><td>{label(row.project_code)}</td><td>{label(row.cost_code)}</td><td>{label(row.vendor_no)}</td><td>{importLabel(row.import_state)}</td><td>{mappingLabel(row.mapping_state)}</td><td title={row.source_record_hash}>{row.source_record_hash.slice(0,18)}…</td></tr>)}</tbody></table></div>}
        <div className="pagination"><button type="button" className="btn" disabled={offset===0||state.phase==='LOADING'} onClick={()=>move(Math.max(0,offset-PAGE_SIZE))}>Previous</button><span>Rows {total===0?0:offset+1}–{Math.min(offset+data.rows.length,total)} of {total}</span><button type="button" className="btn" disabled={offset+PAGE_SIZE>=total||state.phase==='LOADING'} onClick={()=>move(offset+PAGE_SIZE)}>Next</button></div>
      </section>
    </>}
  </AuthoritativeWorkspaceView>;
}
