import React,{useEffect,useMemo,useState} from 'react';
import {proposeAuthoritativeAiInvoiceCapitalization,refreshAuthoritativeAiInvoiceCapitalizationEvidence,refreshAuthoritativeAiInvoiceCapitalizationProposals} from './accounting-api.js';
import {StateBlock} from './ui.jsx';

const initial={evidenceId:'',treatment:'CWIP',assetAccountCode:'',liabilityAccountCode:'',assetClass:'',allocationBasis:'SOURCE_DIMENSIONED',projectRef:'',propertyRef:'',placedInServiceDate:'',usefulLifeMonths:'',reason:''};
export function AuthoritativeCapitalizationPanel({config,fetcher=globalThis.fetch}){
  const [state,setState]=useState({phase:'LOADING',evidence:[],proposals:[],error:null}),[form,setForm]=useState(initial),[submit,setSubmit]=useState({phase:'IDLE',message:''});
  const load=async()=>{setState(current=>({...current,phase:'LOADING',error:null}));const [evidence,proposals]=await Promise.all([refreshAuthoritativeAiInvoiceCapitalizationEvidence({config,fetcher}),refreshAuthoritativeAiInvoiceCapitalizationProposals({config,fetcher})]);setState(evidence.ok&&proposals.ok?{phase:'READY',evidence:evidence.rows,proposals:proposals.rows,error:null}:{phase:'BLOCKED',evidence:[],proposals:[],error:evidence.ok?proposals:evidence});};
  useEffect(()=>{void load();},[config?.entityId,config?.periodId]);
  const used=useMemo(()=>new Set(state.proposals.map(row=>row.classification_evidence_id)),[state.proposals]),available=state.evidence.filter(row=>!used.has(row.classification_evidence_id)),selected=available.find(row=>row.classification_evidence_id===form.evidenceId)||null;
  const change=event=>setForm(current=>({...current,[event.target.name]:event.target.value}));
  const propose=async event=>{event.preventDefault();if(!selected)return;const fixed=form.treatment==='FIXED_ASSET',dimensioned=form.allocationBasis==='SOURCE_DIMENSIONED';setSubmit({phase:'SAVING',message:''});const result=await proposeAuthoritativeAiInvoiceCapitalization({config,evidence:selected,capitalizationTreatment:form.treatment,assetAccountCode:form.assetAccountCode.trim(),liabilityAccountCode:form.liabilityAccountCode.trim(),assetClass:form.assetClass.trim(),memberTrace:{project_ref:dimensioned?(form.projectRef.trim()||null):null,property_ref:dimensioned?(form.propertyRef.trim()||null):null,allocation_basis:form.allocationBasis},placedInServiceDate:fixed?form.placedInServiceDate:null,usefulLifeMonths:fixed?Number(form.usefulLifeMonths):null,reason:form.reason,idempotencyKey:`ai-invoice-capitalization:${globalThis.crypto?.randomUUID?.()||Date.now()}`,fetcher});if(!result.ok){setSubmit({phase:'ERROR',message:`${result.code}: ${result.message}`});return;}setSubmit({phase:'SAVED',message:'The policy-bound capitalization proposal was retained. No Draft or posting action occurred.'});setForm(initial);await load();};
  return <section className="card" aria-label="Invoice capitalization proposals"><div className="card-head"><div><h2>Invoice capitalization review</h2><p className="muted sm">Policy-qualified construction and equipment invoices can be retained as CWIP or fixed-asset proposals. A human supplies accounts, class, dimensions, and placed-in-service evidence.</p></div><span className="badge badge-warning">PROPOSAL ONLY</span></div>
    {state.phase==='BLOCKED'?<StateBlock tone="blocked" title={state.error?.code||'CAPITALIZATION_READ_BLOCKED'}>{state.error?.message} No browser or demonstration evidence is substituted.</StateBlock>:null}
    {state.phase==='READY'?<><form className="form-grid" onSubmit={propose}><label>Retained policy decision<select name="evidenceId" value={form.evidenceId} onChange={change} required><option value="">Select source-bound evidence</option>{available.map(row=><option key={row.classification_evidence_id} value={row.classification_evidence_id}>{row.source_document_id} - {(row.confidence*100).toFixed(0)}%</option>)}</select></label><label>Treatment<select name="treatment" value={form.treatment} onChange={change}><option value="CWIP">Construction in progress</option><option value="FIXED_ASSET">Fixed asset</option></select></label><label>Asset account<input name="assetAccountCode" value={form.assetAccountCode} onChange={change} required/></label><label>Offset liability account<input name="liabilityAccountCode" value={form.liabilityAccountCode} onChange={change} required/></label><label>Asset class<input name="assetClass" value={form.assetClass} onChange={change} required/></label><label>Allocation basis<select name="allocationBasis" value={form.allocationBasis} onChange={change}><option value="SOURCE_DIMENSIONED">Source dimensioned</option><option value="ENTITY_ONLY">Entity only</option></select></label>{form.allocationBasis==='SOURCE_DIMENSIONED'?<><label>Project reference<input name="projectRef" value={form.projectRef} onChange={change} required={form.treatment==='CWIP'}/></label><label>Property reference<input name="propertyRef" value={form.propertyRef} onChange={change}/></label></>:null}{form.treatment==='FIXED_ASSET'?<><label>Placed in service<input type="date" name="placedInServiceDate" value={form.placedInServiceDate} onChange={change} required/></label><label>Useful life (months)<input type="number" min="1" max="600" name="usefulLifeMonths" value={form.usefulLifeMonths} onChange={change} required/></label></>:null}<label className="form-span">Controller rationale<textarea name="reason" minLength={8} maxLength={2000} value={form.reason} onChange={change} required/></label><div className="form-span"><button className="btn btn-primary" disabled={!selected||submit.phase==='SAVING'}>{submit.phase==='SAVING'?'Retaining proposal...':'Retain capitalization proposal'}</button> <span className="muted sm">No Draft, review, approval, or posting authority.</span></div></form>{submit.message?<StateBlock tone={submit.phase==='ERROR'?'blocked':'success'} title={submit.phase==='ERROR'?'Proposal blocked':'Proposal retained'}>{submit.message}</StateBlock>:null}
      {state.proposals.length===0?<StateBlock tone="empty" title="No retained capitalization proposals">No source-bound capitalization proposal has been retained for this entity.</StateBlock>:<div className="table-wrap" role="region" tabIndex={0}><table className="tbl"><thead><tr><th>Source</th><th>Treatment</th><th>Amount</th><th>Accounts / asset</th><th>Policy evidence</th><th>Authority</th></tr></thead><tbody>{state.proposals.map(row=><tr key={row.ai_invoice_capitalization_proposal_id}><td><b>{row.source_document_id}</b><div className="muted sm">Line {row.source_document_line_id}</div></td><td>{row.capitalization_treatment}</td><td>{row.currency} {row.amount}</td><td>Dr {row.asset_account_code}<br/>Cr {row.liability_account_code}<div className="muted sm">{row.asset_class}</div></td><td><details><summary>Policy and source hashes</summary><div className="mono sm">{row.policy_snapshot_id}<br/>{row.policy_snapshot_hash}<br/>{row.source_payload_hash}<br/>{row.source_line_hash}</div></details></td><td><span className="badge badge-muted">PROPOSED</span><div className="muted sm">NO DRAFT OR POST</div></td></tr>)}</tbody></table></div>}</>:null}
  </section>;
}
