import React,{useCallback,useEffect,useMemo,useState}from'react';
import{refreshAuthoritativeReportMappings}from'./accounting-api.js';
import{StateBlock}from'./ui.jsx';
const shortHash=value=>`${value.slice(0,15)}…${value.slice(-8)}`;
const statement=value=>value==='BS'?'Balance Sheet':'Income Statement';

export function AuthoritativeReportMappingsWorkspace({config,fetcher=globalThis.fetch}){
 const[state,setState]=useState({phase:'LOADING',data:null,error:null});const[query,setQuery]=useState('');const load=useCallback(async()=>{setState({phase:'LOADING',data:null,error:null});const result=await refreshAuthoritativeReportMappings({config,fetcher});setState(result.ok?{phase:'READY',data:result.data,error:null}:{phase:'ERROR',data:null,error:result});},[config,fetcher]);useEffect(()=>{load();},[load]);const data=state.data;
 const rows=useMemo(()=>{const needle=query.trim().toLowerCase();return !needle||!data?data?.mappings||[]:data.mappings.filter(row=>[row.account_code,row.account_role,row.account_class,row.account_type,row.statement,row.report_row_code,row.cash_flow_class,...row.dimension_requirements].some(value=>String(value).toLowerCase().includes(needle)));},[data,query]);
 return <section className="workspace-card" aria-labelledby="report-mappings-title"><header className="workspace-title-row"><div><p className="eyebrow">APPROVED MAPPING EVIDENCE</p><h2 id="report-mappings-title">Mapping Center</h2><p>Review the complete approved account-to-report mapping catalog for this company and period.</p></div><button type="button" onClick={load} disabled={state.phase==='LOADING'}>Refresh</button></header>
 {state.phase==='LOADING'&&<StateBlock tone="loading">Reading approved report mappings...</StateBlock>}{state.error&&<StateBlock tone="danger">{state.error.code}: {state.error.message}</StateBlock>}
 {data&&<><div className="summary-grid"><article><span>Period</span><strong>{data.scope.period_code}</strong><small>{data.scope.period_status} · {data.scope.currency}</small></article><article><span>Approved mappings</span><strong>{data.population.total_count}</strong><small>Complete immutable population</small></article><article><span>Mapping snapshot</span><strong>Version {data.approval.report_mapping_version}</strong><small>{data.approval.approved_by} · {data.approval.approved_at}</small></article><article><span>Population hash</span><strong className="mono sm">{shortHash(data.population.population_hash)}</strong><small>Bound to snapshot {shortHash(data.approval.report_mapping_hash)}</small></article></div>
 <label className="field"><span>Find approved mappings</span><input type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Account, role, statement, report row, or cash-flow class"/></label><p className="muted sm">Showing {rows.length} of {data.population.total_count} complete approved mappings.</p>
 <div className="table-wrap" tabIndex="0" role="region" aria-label="Approved account-to-report mappings; scroll horizontally to view every column"><table><thead><tr><th>Account</th><th>Role / class</th><th>Statement / report row</th><th>Normal balance</th><th>Cash flow</th><th>Dimensions</th><th>Effective</th><th>Evidence hash</th></tr></thead><tbody>{rows.map(row=><tr key={`${row.account_code}:${row.account_role}`}><td><strong>{row.account_code}</strong><br/><span className="muted sm">{row.account_type}</span></td><td>{row.account_role}<br/><span className="muted sm">{row.account_class}{row.contra?' · Contra':''}</span></td><td>{statement(row.statement)}<br/><span className="mono sm">{row.report_row_code}</span></td><td>{row.normal_balance}</td><td>{row.cash_flow_class}</td><td>{row.dimension_requirements.length?row.dimension_requirements.join(', '):'None'}</td><td>{row.effective_from} to {row.effective_to||'Open-ended'}</td><td className="mono sm" title={row.mapping_hash}>{shortHash(row.mapping_hash)}</td></tr>)}</tbody></table></div>{rows.length===0&&<StateBlock tone="empty">No approved mappings match this local filter. The authoritative population remains unchanged.</StateBlock>}<p className="muted sm">Read only. This catalog cannot create, edit, approve, deactivate, import, automatically apply, or post a mapping. Vendor, source-field, project, property, cost-code and mapping-exception catalogs remain separate unavailable read models.</p></>}
 </section>;
}
