import React,{useCallback,useEffect,useState}from'react';
import{closeAuthoritativePeriod,periodCloseCommandIdempotencyKey,periodReopenCommandIdempotencyKey,refreshAuthoritativePeriodCloseHistory,refreshAuthoritativePeriodCloseReadiness,refreshAuthoritativePeriodReopenHistory,reopenAuthoritativePeriod}from'./accounting-api.js';
import{StateBlock}from'./ui.jsx';

const label={APPROVED_CLOSE_POLICY_UNAVAILABLE:'Approved close policy unavailable',UNPOSTED_JOURNALS:'Unposted journals remain',ADMITTED_SOURCE_REVIEW_OPEN:'Admitted-source review remains open',APPROVED_STATEMENT_SNAPSHOT_MISSING:'Approved financial statement snapshot missing',APPROVED_STATEMENT_SNAPSHOT_STALE:'Approved financial statement snapshot is stale',PERIOD_NOT_OPEN:'Period is not open'};
export function AuthoritativePeriodCloseWorkspace({config,fetcher=globalThis.fetch,currentActorAccess=null}){
 const[state,setState]=useState({phase:'LOADING',data:null,error:null,receipt:null}),[history,setHistory]=useState({phase:'LOADING',items:[],cursor:null,error:null}),[reopenHistory,setReopenHistory]=useState({phase:'LOADING',items:[],cursor:null,error:null}),[reason,setReason]=useState(''),[confirmed,setConfirmed]=useState(false),[reopenReason,setReopenReason]=useState(''),[reopenConfirmed,setReopenConfirmed]=useState(false);
 const load=useCallback(async()=>{setState(s=>({...s,phase:'LOADING',error:null}));const result=await refreshAuthoritativePeriodCloseReadiness({config,fetcher});setState(s=>result.ok?{...s,phase:'READY',data:result.data,error:null}:{...s,phase:'ERROR',error:result});},[config,fetcher]);useEffect(()=>{load();},[load]);
 const loadHistory=useCallback(async({append=false,cursor=null}={})=>{setHistory(s=>({...s,phase:'LOADING',error:null}));const result=await refreshAuthoritativePeriodCloseHistory({config,fetcher,limit:25,cursor});setHistory(s=>result.ok?{phase:'READY',items:append?[...s.items,...result.data.items]:result.data.items,cursor:result.data.next_cursor,error:null}:{...s,phase:'ERROR',error:result});},[config,fetcher]);useEffect(()=>{loadHistory();},[loadHistory]);
 const loadReopenHistory=useCallback(async({append=false,cursor=null}={})=>{setReopenHistory(s=>({...s,phase:'LOADING',error:null}));const result=await refreshAuthoritativePeriodReopenHistory({config,fetcher,limit:25,cursor});setReopenHistory(s=>result.ok?{phase:'READY',items:append?[...s.items,...result.data.items]:result.data.items,cursor:result.data.next_cursor,error:null}:{...s,phase:'ERROR',error:result});},[config,fetcher]);useEffect(()=>{loadReopenHistory();},[loadReopenHistory]);
 const permissions=Array.isArray(currentActorAccess?.permissions)?currentActorAccess.permissions:[],permission=permissions.includes('GL.PERIOD.CLOSE'),reopenPermission=permissions.includes('GL.PERIOD.REOPEN'),latestClose=history.items[0]||null,canClose=state.data?.ready===true&&permission&&confirmed&&reason.trim().length>=8&&reason===reason.trim()&&state.phase==='READY',canReopen=state.data?.period_status==='CLOSED'&&latestClose?.version===state.data.period_version&&reopenPermission&&reopenConfirmed&&reopenReason.trim().length>=8&&reopenReason===reopenReason.trim()&&state.phase==='READY';
 const close=async()=>{if(!canClose)return;setState(s=>({...s,phase:'CLOSING',error:null}));const key=await periodCloseCommandIdempotencyKey({config,readiness:state.data,reason});if(!key){setState(s=>({...s,phase:'ERROR',error:{code:'PERIOD_CLOSE_COMMAND_IDENTITY_UNAVAILABLE',message:'The browser could not create a stable close command identity.'}}));return;}const result=await closeAuthoritativePeriod({config,readiness:state.data,reason,idempotencyKey:key,fetcher});if(!result.ok){setState(s=>({...s,phase:'ERROR',error:result}));return;}setState(s=>({...s,phase:'CLOSED',receipt:result.data,error:null}));await Promise.all([load(),loadHistory(),loadReopenHistory()]);};
 const reopen=async()=>{if(!canReopen)return;setState(s=>({...s,phase:'REOPENING',error:null}));const key=await periodReopenCommandIdempotencyKey({config,readiness:state.data,closeEvidence:latestClose,reason:reopenReason});if(!key){setState(s=>({...s,phase:'ERROR',error:{code:'PERIOD_REOPEN_COMMAND_IDENTITY_UNAVAILABLE',message:'The browser could not create a stable reopen command identity.'}}));return;}const result=await reopenAuthoritativePeriod({config,readiness:state.data,closeEvidence:latestClose,reason:reopenReason,idempotencyKey:key,fetcher});if(!result.ok){setState(s=>({...s,phase:'ERROR',error:result}));return;}setState(s=>({...s,phase:'REOPENED',receipt:result.data,error:null}));await Promise.all([load(),loadHistory(),loadReopenHistory()]);};
 return <section className="workspace-card" aria-labelledby="period-close-title"><header className="workspace-title-row"><div><p className="eyebrow">AUTHORITATIVE CLOSE</p><h2 id="period-close-title">Month-End Close</h2><p>Close only after current policy, source, journal, ledger, and independently approved statement evidence all agree.</p></div><button type="button" onClick={load} disabled={state.phase==='LOADING'||state.phase==='CLOSING'}>Refresh readiness</button></header>
 {state.phase==='LOADING'&&<StateBlock tone="loading">Recomputing period-close readiness...</StateBlock>}{state.error&&<StateBlock tone="danger">{state.error.code}: {state.error.message}</StateBlock>}
 {state.data&&<><dl className="evidence-grid"><div><dt>Period</dt><dd>{state.data.period_code}</dd></div><div><dt>Status / version</dt><dd>{state.data.period_status} / {state.data.period_version}</dd></div><div><dt>Unposted journals</dt><dd>{state.data.unposted_journal_count}</dd></div><div><dt>Open source blockers</dt><dd>{state.data.admitted_source_blocker_count}</dd></div><div><dt>Readiness hash</dt><dd><code>{state.data.readiness_hash}</code></dd></div></dl>{state.data.blockers.length?<div><h3>Close blockers</h3><ul>{state.data.blockers.map(item=><li key={item.code}>{label[item.code]||item.code} ({item.count})</li>)}</ul></div>:<StateBlock tone="success">All authoritative close gates are complete.</StateBlock>}
 <fieldset disabled={state.phase==='CLOSING'||state.phase==='CLOSED'||!state.data.ready||!permission}><legend>Controller close confirmation</legend><label>Reason<textarea value={reason} onChange={event=>setReason(event.target.value)} minLength={8} maxLength={2000}/></label><label><input type="checkbox" checked={confirmed} onChange={event=>setConfirmed(event.target.checked)}/> I verified this exact readiness hash and understand reopening requires a different, independently authorized actor.</label><button type="button" onClick={close} disabled={!canClose}>Close period</button></fieldset>{!permission&&<p className="muted">GL.PERIOD.CLOSE permission is required.</p>}
 {state.data.period_status==='CLOSED'&&<fieldset disabled={state.phase==='REOPENING'||!reopenPermission||latestClose?.version!==state.data.period_version}><legend>Independent period reopen</legend><p>Reopening preserves the original close receipt and returns this period to OPEN. It does not create or post a journal.</p><label>Reopen reason<textarea value={reopenReason} onChange={event=>setReopenReason(event.target.value)} minLength={8} maxLength={2000}/></label><label><input type="checkbox" checked={reopenConfirmed} onChange={event=>setReopenConfirmed(event.target.checked)}/> I verified the latest retained close receipt and am not the actor who closed this period.</label><button type="button" onClick={reopen} disabled={!canReopen}>Reopen period</button></fieldset>}{state.data.period_status==='CLOSED'&&!reopenPermission&&<p className="muted">GL.PERIOD.REOPEN permission is required for an independent reopen.</p>}</>}
 {state.receipt?.schema_version==='PERIOD_CLOSE_RECEIPT_V2'&&<StateBlock tone="success">Period closed by {state.receipt.closed_by}. Receipt version {state.receipt.version}; readiness {state.receipt.readiness_hash}.</StateBlock>}{state.receipt?.schema_version==='PERIOD_REOPEN_RECEIPT_V1'&&<StateBlock tone="success">Period reopened by {state.receipt.reopened_by}. Receipt version {state.receipt.version}; prior close evidence {state.receipt.prior_close_audit_event_id}.</StateBlock>}
 <section aria-labelledby="period-close-history-title"><div className="workspace-title-row"><div><h3 id="period-close-history-title">Close history</h3><p>Immutable close evidence verified against its audit and outbox records. Reasons and command references are shown only as hashes.</p></div><button type="button" onClick={()=>loadHistory()} disabled={history.phase==='LOADING'}>Refresh history</button></div>
 {history.phase==='LOADING'&&history.items.length===0&&<StateBlock tone="loading">Reading retained close receipts...</StateBlock>}{history.error&&<StateBlock tone="danger">{history.error.code}: {history.error.message}</StateBlock>}
 {history.phase!=='LOADING'&&history.items.length===0&&!history.error&&<StateBlock>No retained close receipts for this period.</StateBlock>}
 {history.items.length>0&&<div className="table-scroll" tabIndex="0" aria-label="Period close history"><table><thead><tr><th>Recorded</th><th>Version</th><th>Closed by</th><th>Readiness</th><th>Statement snapshot</th><th>Ledger evidence</th><th>Delivery</th></tr></thead><tbody>{history.items.map(item=><tr key={item.audit_event_id}><td>{item.recorded_at}</td><td>{item.version}</td><td>{item.closed_by}</td><td><code>{item.readiness_hash}</code></td><td><code>{item.financial_statement_snapshot_hash}</code></td><td><code>{item.ledger_evidence_hash}</code></td><td>{item.delivery.status} ({item.delivery.attempt_count})</td></tr>)}</tbody></table></div>}
 {history.cursor&&<button type="button" onClick={()=>loadHistory({append:true,cursor:history.cursor})} disabled={history.phase==='LOADING'}>Load more close history</button>}
 <p className="muted">Close receipts remain immutable. Reopen is a separate CAS- and SoD-bound command; this table provides no Draft, review, approval, or posting action.</p></section>
 <section aria-labelledby="period-reopen-history-title"><div className="workspace-title-row"><div><h3 id="period-reopen-history-title">Reopen history</h3><p>Each retained reopen is verified against its exact prior close and both audit/outbox chains. Reasons and command references are retained only as hashes.</p></div><button type="button" onClick={()=>loadReopenHistory()} disabled={reopenHistory.phase==='LOADING'}>Refresh reopen history</button></div>
 {reopenHistory.phase==='LOADING'&&reopenHistory.items.length===0&&<StateBlock tone="loading">Reading retained reopen receipts...</StateBlock>}{reopenHistory.error&&<StateBlock tone="danger">{reopenHistory.error.code}: {reopenHistory.error.message}</StateBlock>}
 {reopenHistory.phase!=='LOADING'&&reopenHistory.items.length===0&&!reopenHistory.error&&<StateBlock>No retained reopen receipts for this period.</StateBlock>}
 {reopenHistory.items.length>0&&<div className="table-scroll" tabIndex="0" aria-label="Period reopen history"><table><thead><tr><th>Recorded</th><th>Version</th><th>Reopened by</th><th>Prior close</th><th>Prior closer</th><th>Prior readiness</th><th>Delivery</th></tr></thead><tbody>{reopenHistory.items.map(item=><tr key={item.audit_event_id}><td>{item.recorded_at}</td><td>{item.version}</td><td>{item.reopened_by}</td><td><code>{item.prior_close_audit_event_id}</code><br/>{item.prior_closed_at}</td><td>{item.prior_closed_by}</td><td><code>{item.prior_readiness_hash}</code></td><td>{item.delivery.status} ({item.delivery.attempt_count})</td></tr>)}</tbody></table></div>}
 {reopenHistory.cursor&&<button type="button" onClick={()=>loadReopenHistory({append:true,cursor:reopenHistory.cursor})} disabled={reopenHistory.phase==='LOADING'}>Load more reopen history</button>}
 <p className="muted">This readback is evidence only. It cannot close, reopen, create a Draft, review, approve, or post.</p></section></section>;
}
