import React,{useEffect,useMemo,useState} from 'react';
import {refreshAuthoritativeBudgetVsActual,refreshAuthoritativeCashFlowClassification,refreshAuthoritativeConsolidation,refreshAuthoritativeConstructionLoanRollforward,refreshAuthoritativeCwipRollforward,refreshAuthoritativeDimensionProfitability,refreshAuthoritativeFinancialStatementPeriodComparison,refreshAuthoritativeFinancialStatements,refreshAuthoritativeIntercompanyReconciliation,refreshAuthoritativePrepaidRollforward} from './accounting-api.js';
import {StateBlock} from './ui.jsx';
import {DEFAULT_AUTHORITATIVE_LIST_VIEW,createAuthoritativeReturnContext,restoreAuthoritativeReturnContext} from './authoritative-list-context.js';

const REPORTS=[
  ['TRIAL_BALANCE','Trial Balance'],
  ['BALANCE_SHEET','Balance Sheet'],
  ['INCOME_STATEMENT','Income Statement'],
  ['CASH_FLOW','Cash movement evidence'],
];
const DIMENSION_TYPES=Object.freeze([['PROPERTY','Property P&L'],['PROJECT','Project P&L'],['UNIT','Unit profitability']]);
const fixed4=value=>{const match=/^(-?)([0-9]+)\.([0-9]{4})$/.exec(String(value??'0.0000'));if(!match)return 0n;return BigInt(`${match[1]}${match[2]}${match[3]}`);};
const fixed4String=value=>{const negative=value<0n,absolute=negative?-value:value,digits=absolute.toString().padStart(5,'0');return `${negative?'-':''}${digits.slice(0,-4)}.${digits.slice(-4)}`;};
const add=(...values)=>fixed4String(values.reduce((sum,value)=>sum+fixed4(value),0n));
const subtract=(left,right)=>fixed4String(fixed4(left)-fixed4(right));
const money=value=>{const units=fixed4(value),negative=units<0n,absolute=negative?-units:units,cents=(absolute+50n)/100n,whole=(cents/100n).toString().replace(/\B(?=(\d{3})+(?!\d))/g,','),fraction=(cents%100n).toString().padStart(2,'0');return `${negative?'-':''}$${whole}.${fraction}`;};
const sumRows=(rows,sections=null)=>fixed4String(rows.reduce((sum,row)=>sections&&!sections.includes(row.statement_section)?sum:sum+fixed4(row.display_balance),0n));
const sumCashFlowRows=(rows,sections=null)=>fixed4String(rows.reduce((sum,row)=>sections&&!sections.includes(row.classification)?sum:sum+fixed4(row.cash_effect),0n));

export const FinancialStatementSummary=({report,rows})=>{
  if(report==='BALANCE_SHEET'){
    const assets=sumRows(rows,['ASSETS']),liabilities=sumRows(rows,['LIABILITIES']),equity=sumRows(rows,['EQUITY','CURRENT_EARNINGS']),right=add(liabilities,equity),difference=subtract(assets,right);
    return <div className="qbo-toolgrid" aria-label="Balance Sheet equation"><span><i>Assets</i><b>{money(assets)}</b></span><span><i>Liabilities</i><b>{money(liabilities)}</b></span><span><i>Equity and current earnings</i><b>{money(equity)}</b></span><span><i>Assets - liabilities - equity</i><b>{money(difference)}</b></span></div>;
  }
  if(report==='INCOME_STATEMENT'){
    const revenue=sumRows(rows,['REVENUE']),expense=sumRows(rows,['EXPENSES']);
    return <div className="qbo-toolgrid" aria-label="Income Statement equation"><span><i>Revenue</i><b>{money(revenue)}</b></span><span><i>Expenses</i><b>{money(expense)}</b></span><span><i>Net income</i><b>{money(subtract(revenue,expense))}</b></span></div>;
  }
  if(report==='CASH_FLOW')return <div className="qbo-toolgrid" aria-label="Direct cash movement evidence"><span><i>Direct cash-account movement</i><b>{money(sumRows(rows))}</b></span><span><i>Classification boundary</i><b>Not classified as operating, investing, or financing</b></span></div>;
  return <div className="qbo-toolgrid" aria-label="Trial Balance control"><span><i>Net debit balance</i><b>{money(sumRows(rows))}</b></span></div>;
};

const EvidenceIds=({label,ids=[]})=><div><b>{label}</b>{ids.length?<ul className="evidence-id-list">{ids.map(id=><li key={id}><code>{id}</code></li>)}</ul>:<p className="muted sm">No retained identifier.</p>}</div>;

const CashFlowDetail=({row,returnContext,onBack})=><section className="full-bleed qbo-transaction-report" aria-label="Cash flow classification evidence">
  <div className="qbo-report-back"><button type="button" className="btn btn-sm btn-ghost" onClick={onBack}>Back to statement of cash flows</button><span>Entity {returnContext?.entityId} · Period {returnContext?.periodId}</span></div>
  <div className="card-head"><div><h2>{row.classification==='BLOCKED'?'Blocked cash-flow classification':`${row.classification} cash flow`}</h2><p className="muted sm">Cash {row.cash_account_code} · Counterpart {row.counterpart_account_code}</p></div><span className={row.mapping_status==='CLASSIFIED'?'badge badge-muted':'badge badge-danger'}>{row.mapping_status}</span></div>
  <div className="qbo-toolgrid"><span><i>Cash effect</i><b>{money(row.cash_effect)}</b></span><span><i>Mapping snapshot</i><b>{row.mapping_snapshot_id||'Not admitted'}</b></span><span><i>Mapping version</i><b>{row.mapping_version||'Not admitted'}</b></span></div>
  <p className="muted sm">Classification basis: {row.classification_basis}.{row.mapping_snapshot_hash&&` Immutable mapping hash: ${row.mapping_snapshot_hash}.`}</p>
  <div className="detail-grid"><EvidenceIds label="Journal entries" ids={row.journal_entry_ids}/><EvidenceIds label="Journal lines" ids={row.journal_line_ids}/><EvidenceIds label="Ledger lines" ids={row.ledger_line_ids}/><EvidenceIds label="Source documents" ids={row.source_document_ids}/></div>
</section>;

const IntercompanyDetail=({row,returnContext,onBack})=><section className="full-bleed qbo-transaction-report" aria-label="Intercompany reconciliation evidence">
  <div className="qbo-report-back"><button type="button" className="btn btn-sm btn-ghost" onClick={onBack}>Back to intercompany reconciliation</button><span>Entity {returnContext?.entityId} | Period {returnContext?.periodId}</span></div>
  <div className="card-head"><div><h2>{row.account_code} ↔ {row.counterparty_account_code}</h2><p className="muted sm">Exact bidirectional intercompany mapping and POSTED-ledger evidence only.</p></div><span className={row.mapping_status==='MAPPED_INTERCOMPANY_PAIR'?'badge badge-muted':'badge badge-danger'}>{row.mapping_status}</span></div>
  <div className="qbo-toolgrid"><span><i>Current entity</i><b>{row.current_closing_balance===null?'Blocked':money(row.current_closing_balance)}</b></span><span><i>Counterparty</i><b>{row.counterparty_closing_balance===null?'Blocked':money(row.counterparty_closing_balance)}</b></span><span><i>Difference</i><b>{row.difference_amount===null?'Blocked':money(row.difference_amount)}</b></span><span><i>Result</i><b>{row.in_balance?'Tied':'Review required'}</b></span></div>
  <p className="muted sm">{row.classification_basis}. No elimination or adjustment is created by this report.</p>
  <div className="detail-grid"><EvidenceIds label="Current journal entries" ids={row.journal_entry_ids}/><EvidenceIds label="Current sources" ids={row.source_document_ids}/><EvidenceIds label="Counterparty journal entries" ids={row.counterparty_journal_entry_ids}/><EvidenceIds label="Counterparty sources" ids={row.counterparty_source_document_ids}/></div>
</section>;

const BudgetActualDetail=({row,returnContext,onBack})=><section className="full-bleed qbo-transaction-report" aria-label="Budget versus actual evidence">
  <div className="qbo-report-back"><button type="button" className="btn btn-sm btn-ghost" onClick={onBack}>Back to budget versus actual</button><span>Entity {returnContext?.entityId} | Period {returnContext?.periodId}</span></div>
  <div className="card-head"><div><h2>{row.account_code} - {row.account_name}</h2><p className="muted sm">Approved immutable budget snapshot compared only with same-period POSTED ledger evidence.</p></div><span className={row.report_status==='APPROVED_BUDGET_VS_ACTUAL'?'badge badge-muted':'badge badge-danger'}>{row.report_status}</span></div>
  <div className="qbo-toolgrid"><span><i>Budget</i><b>{row.budget_amount===null?'Blocked':money(row.budget_amount)}</b></span><span><i>Actual</i><b>{row.actual_amount===null?'Blocked':money(row.actual_amount)}</b></span><span><i>Variance</i><b>{row.variance_amount===null?'Blocked':money(row.variance_amount)}</b></span><span><i>Comparison side</i><b>{row.comparison_side}</b></span></div>
  <p className="muted sm">{row.classification_basis}. Snapshot <code>{row.budget_snapshot_id}</code> v{row.budget_version}; receipt {row.budget_receipt_hash}; source {row.budget_source_ref} v{row.budget_source_version}. This read cannot create or revise a budget, journal, mapping, or adjustment.</p>
  <div className="detail-grid"><EvidenceIds label="Journal entries" ids={row.journal_entry_ids}/><EvidenceIds label="Journal lines" ids={row.journal_line_ids}/><EvidenceIds label="Ledger lines" ids={row.ledger_line_ids}/><EvidenceIds label="Source documents" ids={row.source_document_ids}/></div>
</section>;

const ConsolidationDetail=({row,returnContext,onBack})=><section className="full-bleed qbo-transaction-report" aria-label="Consolidation evidence">
  <div className="qbo-report-back"><button type="button" className="btn btn-sm btn-ghost" onClick={onBack}>Back to consolidation</button><span>Entity {returnContext?.entityId} | Period {returnContext?.periodId}</span></div>
  <div className="card-head"><div><h2>{row.presentation_account_code} - {row.presentation_side}</h2><p className="muted sm">Immutable member/account mapping, approved elimination evidence, and POSTED ledger only.</p></div><span className={row.report_status==='APPROVED_CONSOLIDATION_SNAPSHOT_AND_POSTED_LEDGER_EXACT'?'badge badge-muted':'badge badge-danger'}>{row.report_status}</span></div>
  <div className="qbo-toolgrid"><span><i>Member actual</i><b>{row.member_actual_amount===null?'Blocked':money(row.member_actual_amount)}</b></span><span><i>Approved elimination</i><b>{row.elimination_amount===null?'Blocked':money(row.elimination_amount)}</b></span><span><i>Consolidated</i><b>{row.consolidated_amount===null?'Blocked':money(row.consolidated_amount)}</b></span><span><i>Members with evidence</i><b>{row.evidence_member_count}/{row.member_count}</b></span></div>
  <p className="muted sm">{row.classification_basis}. Snapshot <code>{row.consolidation_snapshot_id}</code> v{row.consolidation_version}; receipt {row.consolidation_receipt_hash}. This report creates no elimination journal or adjustment.</p>
  <div className="detail-grid"><EvidenceIds label="Member entities" ids={row.member_entity_ids}/><EvidenceIds label="Journal entries" ids={row.journal_entry_ids}/><EvidenceIds label="Ledger lines" ids={row.ledger_line_ids}/><EvidenceIds label="Source documents" ids={row.source_document_ids}/></div>
</section>;

const ReportDetail=({row,returnContext,onBack})=><section className="full-bleed qbo-transaction-report" aria-label="Financial statement account evidence">
  <div className="qbo-report-back"><button type="button" className="btn btn-sm btn-ghost" onClick={onBack}>Back to financial statement</button><span>Entity {returnContext?.entityId} · Period {returnContext?.periodId} · {returnContext?.report}</span></div>
  <div className="card-head"><div><h2>{row.account_code} - {row.account_name}</h2><p className="muted sm">{row.statement_type} / {row.statement_section}</p></div><span className="badge badge-muted">POSTED EVIDENCE</span></div>
  <div className="qbo-toolgrid">
    {row.opening_debit!==undefined&&<><span><i>Opening debits</i><b>{money(row.opening_debit)}</b></span><span><i>Opening credits</i><b>{money(row.opening_credit)}</b></span></>}
    <span><i>Period debits</i><b>{money(row.period_debit)}</b></span><span><i>Period credits</i><b>{money(row.period_credit)}</b></span>
    <span><i>Statement balance</i><b>{money(row.display_balance)}</b></span>
  </div>
  <p className="muted sm">Classification basis: {row.classification_basis}. Period {row.period_code}, {row.period_start} through {row.period_end}.{row.dimension_type&&` Exact ${row.dimension_type.toLowerCase()} ${row.dimension_ref}.`}</p>
  <div className="detail-grid">
    <EvidenceIds label="Journal entries" ids={row.journal_entry_ids}/><EvidenceIds label="Journal lines" ids={row.journal_line_ids}/>
    <EvidenceIds label="Ledger lines" ids={row.ledger_line_ids}/><EvidenceIds label="Source documents" ids={row.source_document_ids}/>
  </div>
</section>;

export function AuthoritativeReportsWorkspace({config,fetcher=globalThis.fetch,environment=globalThis}){
  const [report,setReport]=useState('TRIAL_BALANCE');
  const [selected,setSelected]=useState(null);
  const [state,setState]=useState({phase:'LOADING',rows:[],error:null});
  const [dimensionType,setDimensionType]=useState('PROPERTY');
  const [dimensionRef,setDimensionRef]=useState('');
  const [dimensionState,setDimensionState]=useState({phase:'IDLE',rows:[],error:null,scope:null});
  const [cashFlowState,setCashFlowState]=useState({phase:'IDLE',rows:[],error:null,scope:null,complete:false});
  const [cwipState,setCwipState]=useState({phase:'IDLE',rows:[],error:null,scope:null,complete:false});
  const [constructionLoanState,setConstructionLoanState]=useState({phase:'IDLE',rows:[],error:null,scope:null,complete:false});
  const [prepaidState,setPrepaidState]=useState({phase:'IDLE',rows:[],error:null,scope:null,complete:false});
  const [counterpartyEntityId,setCounterpartyEntityId]=useState('');
  const [counterpartyPeriodId,setCounterpartyPeriodId]=useState('');
  const [intercompanyState,setIntercompanyState]=useState({phase:'IDLE',rows:[],error:null,scope:null,complete:false});
  const [budgetState,setBudgetState]=useState({phase:'IDLE',rows:[],error:null,scope:null,complete:false});
  const [consolidationGroupRef,setConsolidationGroupRef]=useState('');
  const [consolidationState,setConsolidationState]=useState({phase:'IDLE',rows:[],error:null,scope:null,complete:false});
  const [priorPeriodId,setPriorPeriodId]=useState('');
  const [comparisonState,setComparisonState]=useState({phase:'IDLE',rows:[],error:null,scope:null});
  const load=async()=>{setState(current=>({...current,phase:'LOADING',error:null}));const result=await refreshAuthoritativeFinancialStatements({config,fetcher});setState(result.ok?{phase:'READY',rows:result.rows,error:null}:{phase:'ERROR',rows:[],error:result});};
  const loadDimension=async()=>{setDimensionState({phase:'LOADING',rows:[],error:null,scope:null});const result=await refreshAuthoritativeDimensionProfitability({config,dimensionType,dimensionRef,fetcher});setDimensionState(result.ok?{phase:'READY',rows:result.rows,error:null,scope:result.scope}:{phase:'ERROR',rows:[],error:result,scope:null});};
  const loadCashFlow=async()=>{setCashFlowState({phase:'LOADING',rows:[],error:null,scope:null,complete:false});const result=await refreshAuthoritativeCashFlowClassification({config,fetcher});setCashFlowState(result.ok?{phase:'READY',rows:result.rows,error:null,scope:result.scope,complete:result.complete}:{phase:'ERROR',rows:[],error:result,scope:null,complete:false});};
  const loadCwip=async()=>{setCwipState({phase:'LOADING',rows:[],error:null,scope:null,complete:false});const result=await refreshAuthoritativeCwipRollforward({config,fetcher});setCwipState(result.ok?{phase:'READY',rows:result.rows,error:null,scope:result.scope,complete:result.complete}:{phase:'ERROR',rows:[],error:result,scope:null,complete:false});};
  const loadConstructionLoan=async()=>{setConstructionLoanState({phase:'LOADING',rows:[],error:null,scope:null,complete:false});const result=await refreshAuthoritativeConstructionLoanRollforward({config,fetcher});setConstructionLoanState(result.ok?{phase:'READY',rows:result.rows,error:null,scope:result.scope,complete:result.complete}:{phase:'ERROR',rows:[],error:result,scope:null,complete:false});};
  const loadPrepaid=async()=>{setPrepaidState({phase:'LOADING',rows:[],error:null,scope:null,complete:false});const result=await refreshAuthoritativePrepaidRollforward({config,fetcher});setPrepaidState(result.ok?{phase:'READY',rows:result.rows,error:null,scope:result.scope,complete:result.complete}:{phase:'ERROR',rows:[],error:result,scope:null,complete:false});};
  const loadIntercompany=async()=>{setIntercompanyState({phase:'LOADING',rows:[],error:null,scope:null,complete:false});const result=await refreshAuthoritativeIntercompanyReconciliation({config,counterpartyEntityId,counterpartyPeriodId,fetcher});setIntercompanyState(result.ok?{phase:'READY',rows:result.rows,error:null,scope:result.scope,complete:result.complete}:{phase:'ERROR',rows:[],error:result,scope:null,complete:false});};
  const loadBudget=async()=>{setBudgetState({phase:'LOADING',rows:[],error:null,scope:null,complete:false});const result=await refreshAuthoritativeBudgetVsActual({config,fetcher});setBudgetState(result.ok?{phase:'READY',rows:result.rows,error:null,scope:result.scope,complete:result.complete}:{phase:'ERROR',rows:[],error:result,scope:null,complete:false});};
  const loadConsolidation=async()=>{setConsolidationState({phase:'LOADING',rows:[],error:null,scope:null,complete:false});const result=await refreshAuthoritativeConsolidation({config,groupRef:consolidationGroupRef,fetcher});setConsolidationState(result.ok?{phase:'READY',rows:result.rows,error:null,scope:result.scope,complete:result.complete}:{phase:'ERROR',rows:[],error:result,scope:null,complete:false});};
  const loadComparison=async()=>{setComparisonState({phase:'LOADING',rows:[],error:null,scope:null});const result=await refreshAuthoritativeFinancialStatementPeriodComparison({config,priorPeriodId,fetcher});setComparisonState(result.ok?{phase:'READY',rows:result.rows,error:null,scope:result.scope}:{phase:'ERROR',rows:[],error:result,scope:null});};
  useEffect(()=>{load();},[config?.entityId,config?.periodId]);
  const rows=useMemo(()=>state.rows.filter(row=>row.statement_type===report),[state.rows,report]);
  const openEvidence=(row,focusId)=>{
    const base=createAuthoritativeReturnContext({config,view:DEFAULT_AUTHORITATIVE_LIST_VIEW,focusId,scrollY:Number(environment?.scrollY)||0});
    if(base)setSelected({row,returnContext:{...base,report}});
  };
  const closeEvidence=()=>{
    const context=selected?.returnContext;
    if(REPORTS.some(([key])=>key===context?.report))setReport(context.report);
    setSelected(null);
    restoreAuthoritativeReturnContext(environment,config,context);
  };
  if(selected)return selected.kind==='CASH_FLOW_CLASSIFICATION'?<CashFlowDetail row={selected.row} returnContext={selected.returnContext} onBack={closeEvidence}/>:selected.kind==='INTERCOMPANY_RECONCILIATION'?<IntercompanyDetail row={selected.row} returnContext={selected.returnContext} onBack={closeEvidence}/>:selected.kind==='BUDGET_VS_ACTUAL'?<BudgetActualDetail row={selected.row} returnContext={selected.returnContext} onBack={closeEvidence}/>:selected.kind==='CONSOLIDATION'?<ConsolidationDetail row={selected.row} returnContext={selected.returnContext} onBack={closeEvidence}/>:<ReportDetail row={selected.row} returnContext={selected.returnContext} onBack={closeEvidence}/>;
  return <div className="stack"><div><h1>Financial statements</h1><p className="page-subtitle">OIDC-authenticated, entity-and-period-scoped POSTED ledger evidence. Browser seed data and local storage are not used.</p></div>
    <div className="tabs" role="tablist" aria-label="Financial statements">{REPORTS.map(([key,label])=><button type="button" role="tab" aria-selected={report===key} className={report===key?'tab active':'tab'} key={key} onClick={()=>{setReport(key);setSelected(null);}}>{label}</button>)}</div>
    <p className="muted sm">Entity {config.entityId} | Period {config.periodId} | Read only</p>
    {state.phase==='LOADING'&&<StateBlock tone="loading">Loading authoritative financial statements...</StateBlock>}
    {state.phase==='ERROR'&&<StateBlock tone="error" title={state.error?.code} actions={<button type="button" className="btn btn-sm" onClick={load}>Retry read</button>}><p>{state.error?.message}</p></StateBlock>}
    {state.phase==='READY'&&<section className="card" aria-label={`${REPORTS.find(item=>item[0]===report)?.[1]} rows`}>
      <div className="card-head"><div><h2>{REPORTS.find(item=>item[0]===report)?.[1]}</h2><p className="muted sm">{rows.length} accounts in retained evidence.</p></div><span className="badge badge-muted">READ ONLY</span></div>
      {!!rows.length&&<FinancialStatementSummary report={report} rows={rows}/>}
      {report==='CASH_FLOW'&&<p className="muted sm">This view is direct cash-account movement evidence only. It is not a statement of cash flows and does not infer operating, investing, or financing activities.</p>}
      {!rows.length?<StateBlock tone="empty" title="No POSTED ledger evidence returned">No POSTED ledger evidence was returned for this statement and period.</StateBlock>:<div className="table-wrap"><table className="tbl"><thead><tr><th>Section</th><th>Account</th><th>Period debit</th><th>Period credit</th><th>Balance</th><th>Evidence</th></tr></thead><tbody>{rows.map(row=>{const focusId=`authoritative-report-${row.statement_type}-${row.account_code}`;return <tr key={`${row.statement_type}:${row.account_code}`}><td>{row.statement_section}</td><td><b>{row.account_code}</b><div className="muted sm">{row.account_name}</div></td><td className="num">{money(row.period_debit)}</td><td className="num">{money(row.period_credit)}</td><td className="num">{money(row.display_balance)}</td><td><button id={focusId} type="button" className="btn btn-sm" onClick={()=>openEvidence(row,focusId)}>Open evidence</button></td></tr>;})}</tbody></table></div>}
    </section>}
    <section className="card" aria-label="Statement of cash flows evidence">
      <div className="card-head"><div><h2>Statement of cash flows</h2><p className="muted sm">Operating, investing, and financing classification requires an exact approved immutable mapping for every POSTED bank-cash journal counterpart.</p></div><span className="badge badge-muted">READ ONLY</span></div>
      <div className="qbo-filter-grid"><button type="button" className="btn" onClick={loadCashFlow}>Load mapped cash-flow evidence</button></div>
      <p className="muted sm">No source label, account description, or account-code prefix is used to infer a classification. A missing, ambiguous, invalid, or multi-cash mapping stays BLOCKED and prevents statement totals from being asserted.</p>
      {cashFlowState.phase==='LOADING'&&<StateBlock tone="loading">Loading mapping-backed POSTED cash-flow evidence...</StateBlock>}
      {cashFlowState.phase==='ERROR'&&<StateBlock tone="error" title={cashFlowState.error?.code}><p>{cashFlowState.error?.message}</p></StateBlock>}
      {cashFlowState.phase==='READY'&&!cashFlowState.rows.length&&<StateBlock tone="empty" title="No POSTED bank-cash evidence returned">This scoped empty result is not evidence of zero operating, investing, or financing cash flow.</StateBlock>}
      {cashFlowState.phase==='READY'&&!!cashFlowState.rows.length&&!cashFlowState.complete&&<StateBlock tone="error" title="BLOCKED_CASH_FLOW_CLASSIFICATION">At least one POSTED cash movement has no single valid mapping. REFS will not calculate operating, investing, or financing totals from this incomplete classification set.</StateBlock>}
      {cashFlowState.phase==='READY'&&cashFlowState.complete&&<div className="qbo-toolgrid" aria-label="Statement of cash flows totals"><span><i>Operating</i><b>{money(sumCashFlowRows(cashFlowState.rows,['OPERATING']))}</b></span><span><i>Investing</i><b>{money(sumCashFlowRows(cashFlowState.rows,['INVESTING']))}</b></span><span><i>Financing</i><b>{money(sumCashFlowRows(cashFlowState.rows,['FINANCING']))}</b></span><span><i>Net change in cash</i><b>{money(sumCashFlowRows(cashFlowState.rows))}</b></span></div>}
      {cashFlowState.phase==='READY'&&!!cashFlowState.rows.length&&<div className="table-wrap"><table className="tbl"><thead><tr><th>Classification</th><th>Cash / counterpart</th><th>Cash effect</th><th>Mapping</th><th>Evidence</th></tr></thead><tbody>{cashFlowState.rows.map(row=>{const focusId=`authoritative-cash-flow-${row.journal_entry_ids[0]}-${row.counterpart_account_code}`;return <tr key={`${row.journal_entry_ids[0]}:${row.cash_account_code}:${row.counterpart_account_code}`}><td><b>{row.classification}</b><div className="muted sm">{row.mapping_status}</div></td><td><b>{row.cash_account_code}</b><div className="muted sm">{row.counterpart_account_code}</div></td><td className="num">{money(row.cash_effect)}</td><td>{row.mapping_snapshot_id?<><code>{row.mapping_snapshot_id}</code><div className="muted sm">v{row.mapping_version}</div></>:'Not admitted'}</td><td><button id={focusId} type="button" className="btn btn-sm" onClick={()=>{const base=createAuthoritativeReturnContext({config,view:DEFAULT_AUTHORITATIVE_LIST_VIEW,focusId,scrollY:Number(environment?.scrollY)||0});if(base)setSelected({kind:'CASH_FLOW_CLASSIFICATION',row,returnContext:{...base,report}});}}>Open evidence</button></td></tr>;})}</tbody></table></div>}
    </section>
    <section className="card" aria-label="Prior-period comparison evidence">
      <div className="card-head"><div><h2>Prior-period comparison</h2><p className="muted sm">Compares current POSTED statement evidence with one explicit, earlier entity-scoped period. Absence on either side is never converted to zero.</p></div><span className="badge badge-muted">READ ONLY</span></div>
      <div className="qbo-filter-grid"><label>Prior period ID<input value={priorPeriodId} maxLength="36" onChange={event=>{setPriorPeriodId(event.target.value.trim());setComparisonState({phase:'IDLE',rows:[],error:null,scope:null});}} placeholder="UUID of an earlier period"/></label><button type="button" className="btn" disabled={!priorPeriodId||priorPeriodId===config.periodId} onClick={loadComparison}>Load comparison evidence</button></div>
      <p className="muted sm">The API rejects overlapping or same-period comparisons. A row marked missing requires retained POSTED evidence before it can support a comparison conclusion.</p>
      {comparisonState.phase==='LOADING'&&<StateBlock tone="loading">Loading two-period POSTED statement evidence...</StateBlock>}
      {comparisonState.phase==='ERROR'&&<StateBlock tone="error" title={comparisonState.error?.code}><p>{comparisonState.error?.message}</p></StateBlock>}
      {comparisonState.phase==='READY'&&!comparisonState.rows.length&&<StateBlock tone="empty" title="No comparable POSTED evidence returned">This scoped empty result is not evidence of no period-over-period change.</StateBlock>}
      {comparisonState.phase==='READY'&&!!comparisonState.rows.length&&<div className="table-wrap"><table className="tbl"><thead><tr><th>Statement / account</th><th>Current period</th><th>Prior period</th><th>Evidence status</th></tr></thead><tbody>{comparisonState.rows.map(row=><tr key={`${row.statement_type}:${row.account_code}`}><td><b>{row.account_code}</b><div className="muted sm">{row.statement_type} / {row.statement_section}</div></td><td className="num">{row.current_display_balance===null?'Evidence missing':money(row.current_display_balance)}</td><td className="num">{row.prior_display_balance===null?'Evidence missing':money(row.prior_display_balance)}</td><td><span className={row.comparison_status==='COMPARABLE_POSTED_EVIDENCE'?'badge badge-muted':'badge badge-danger'}>{row.comparison_status}</span></td></tr>)}</tbody></table></div>}
    </section>
    <section className="card" aria-label="CWIP rollforward evidence">
      <div className="card-head"><div><h2>CWIP rollforward</h2><p className="muted sm">Exact approved CWIP-account mappings plus POSTED ledger evidence. Debit and credit movement stay in ledger form; REFS does not infer capitalization, transfers, or write-offs.</p></div><span className="badge badge-muted">READ ONLY</span></div>
      <div className="qbo-filter-grid"><button type="button" className="btn" onClick={loadCwip}>Load CWIP rollforward evidence</button></div>
      <p className="muted sm">An account enters this view only through one immutable mapping snapshot with classification CWIP. An empty or blocked result is not evidence of zero CWIP, zero construction activity, or a completed capitalization review.</p>
      {cwipState.phase==='LOADING'&&<StateBlock tone="loading">Loading mapping-backed CWIP ledger evidence...</StateBlock>}
      {cwipState.phase==='ERROR'&&<StateBlock tone="error" title={cwipState.error?.code}><p>{cwipState.error?.message}</p></StateBlock>}
      {cwipState.phase==='READY'&&!cwipState.rows.length&&<StateBlock tone="empty" title="No admitted CWIP ledger evidence returned">No immutable CWIP account mapping with retained POSTED ledger evidence was returned for this period. This scoped empty result is not zero CWIP.</StateBlock>}
      {cwipState.phase==='READY'&&!!cwipState.rows.length&&!cwipState.complete&&<StateBlock tone="error" title="BLOCKED_CWIP_MAPPING">At least one CWIP account mapping is missing, ambiguous, or invalid. REFS will not assert a complete CWIP rollforward.</StateBlock>}
      {cwipState.phase==='READY'&&!!cwipState.rows.length&&<div className="table-wrap"><table className="tbl"><thead><tr><th>Account</th><th>Opening</th><th>Period debit</th><th>Period credit</th><th>Closing</th><th>Mapping</th></tr></thead><tbody>{cwipState.rows.map(row=><tr key={row.account_code}><td><b>{row.account_code}</b><div className="muted sm">{row.account_name}</div><div className="muted sm">{row.mapping_status}</div></td><td className="num">{row.opening_balance===null?'Blocked':money(row.opening_balance)}</td><td className="num">{row.period_debit===null?'Blocked':money(row.period_debit)}</td><td className="num">{row.period_credit===null?'Blocked':money(row.period_credit)}</td><td className="num">{row.closing_balance===null?'Blocked':money(row.closing_balance)}</td><td>{row.mapping_snapshot_id?<><code>{row.mapping_snapshot_id}</code><div className="muted sm">v{row.mapping_version}</div></>:'Not admitted'}</td></tr>)}</tbody></table></div>}
    </section>
    <section className="card" aria-label="Construction loan rollforward evidence">
      <div className="card-head"><div><h2>Construction loan rollforward</h2><p className="muted sm">Exact approved construction-loan account mappings plus POSTED ledger evidence. Credit is shown as a draw and debit as a repayment; this view never infers lender, commitment, interest capitalization, or construction activity from account labels or source text.</p></div><span className="badge badge-muted">READ ONLY</span></div>
      <div className="qbo-filter-grid"><button type="button" className="btn" onClick={loadConstructionLoan}>Load construction-loan evidence</button></div>
      <p className="muted sm">An account enters this view only through one immutable mapping snapshot with classification CONSTRUCTION_LOAN. An empty or blocked result is not evidence of zero debt, zero draws, zero repayments, or a completed lender reconciliation.</p>
      {constructionLoanState.phase==='LOADING'&&<StateBlock tone="loading">Loading mapping-backed construction-loan ledger evidence...</StateBlock>}
      {constructionLoanState.phase==='ERROR'&&<StateBlock tone="error" title={constructionLoanState.error?.code}><p>{constructionLoanState.error?.message}</p></StateBlock>}
      {constructionLoanState.phase==='READY'&&!constructionLoanState.rows.length&&<StateBlock tone="empty" title="No admitted construction-loan ledger evidence returned">No immutable construction-loan account mapping with retained POSTED ledger evidence was returned for this period. This scoped empty result is not zero construction debt.</StateBlock>}
      {constructionLoanState.phase==='READY'&&!!constructionLoanState.rows.length&&!constructionLoanState.complete&&<StateBlock tone="error" title="BLOCKED_CONSTRUCTION_LOAN_MAPPING">At least one construction-loan account mapping is missing, ambiguous, or invalid. REFS will not assert a complete construction-loan rollforward.</StateBlock>}
      {constructionLoanState.phase==='READY'&&!!constructionLoanState.rows.length&&<div className="table-wrap"><table className="tbl"><thead><tr><th>Account</th><th>Opening</th><th>Period draws</th><th>Period repayments</th><th>Closing</th><th>Mapping</th></tr></thead><tbody>{constructionLoanState.rows.map(row=><tr key={row.account_code}><td><b>{row.account_code}</b><div className="muted sm">{row.account_name}</div><div className="muted sm">{row.mapping_status}</div></td><td className="num">{row.opening_balance===null?'Blocked':money(row.opening_balance)}</td><td className="num">{row.period_draws===null?'Blocked':money(row.period_draws)}</td><td className="num">{row.period_repayments===null?'Blocked':money(row.period_repayments)}</td><td className="num">{row.closing_balance===null?'Blocked':money(row.closing_balance)}</td><td>{row.mapping_snapshot_id?<><code>{row.mapping_snapshot_id}</code><div className="muted sm">v{row.mapping_version}</div></>:'Not admitted'}</td></tr>)}</tbody></table></div>}
    </section>
    <section className="card" aria-label="Prepaid rollforward evidence">
      <div className="card-head"><div><h2>Prepaid rollforward</h2><p className="muted sm">Exact approved prepaid-account mappings plus POSTED ledger evidence. Debit is shown as an addition and credit as amortization; this view never infers insurance coverage, policy period, useful life, or amortization schedule from an account label or source text.</p></div><span className="badge badge-muted">READ ONLY</span></div>
      <div className="qbo-filter-grid"><button type="button" className="btn" onClick={loadPrepaid}>Load prepaid evidence</button></div>
      <p className="muted sm">An account enters this view only through one immutable mapping snapshot with classification PREPAID. An empty or blocked result is not evidence of zero prepaid assets, zero amortization, or a complete insurance review.</p>
      {prepaidState.phase==='LOADING'&&<StateBlock tone="loading">Loading mapping-backed prepaid ledger evidence...</StateBlock>}
      {prepaidState.phase==='ERROR'&&<StateBlock tone="error" title={prepaidState.error?.code}><p>{prepaidState.error?.message}</p></StateBlock>}
      {prepaidState.phase==='READY'&&!prepaidState.rows.length&&<StateBlock tone="empty" title="No admitted prepaid ledger evidence returned">No immutable prepaid account mapping with retained POSTED ledger evidence was returned for this period. This scoped empty result is not zero prepaid assets.</StateBlock>}
      {prepaidState.phase==='READY'&&!!prepaidState.rows.length&&!prepaidState.complete&&<StateBlock tone="error" title="BLOCKED_PREPAID_MAPPING">At least one prepaid account mapping is missing, ambiguous, or invalid. REFS will not assert a complete prepaid rollforward.</StateBlock>}
      {prepaidState.phase==='READY'&&!!prepaidState.rows.length&&<div className="table-wrap"><table className="tbl"><thead><tr><th>Account</th><th>Opening</th><th>Period additions</th><th>Period amortization</th><th>Closing</th><th>Mapping</th></tr></thead><tbody>{prepaidState.rows.map(row=><tr key={row.account_code}><td><b>{row.account_code}</b><div className="muted sm">{row.account_name}</div><div className="muted sm">{row.mapping_status}</div></td><td className="num">{row.opening_balance===null?'Blocked':money(row.opening_balance)}</td><td className="num">{row.period_additions===null?'Blocked':money(row.period_additions)}</td><td className="num">{row.period_amortization===null?'Blocked':money(row.period_amortization)}</td><td className="num">{row.closing_balance===null?'Blocked':money(row.closing_balance)}</td><td>{row.mapping_snapshot_id?<><code>{row.mapping_snapshot_id}</code><div className="muted sm">v{row.mapping_version}</div></>:'Not admitted'}</td></tr>)}</tbody></table></div>}
    </section>
    <section className="card" aria-label="Intercompany reconciliation evidence">
      <div className="card-head"><div><h2>Intercompany reconciliation</h2><p className="muted sm">Two distinct entity scopes, exactly aligned periods, bidirectional approved mappings, and POSTED-ledger evidence are required.</p></div><span className="badge badge-muted">READ ONLY</span></div>
      <div className="qbo-filter-grid"><label>Counterparty entity ID<input value={counterpartyEntityId} maxLength="36" onChange={event=>{setCounterpartyEntityId(event.target.value.trim());setIntercompanyState({phase:'IDLE',rows:[],error:null,scope:null,complete:false});}} placeholder="UUID of the counterparty entity"/></label><label>Counterparty period ID<input value={counterpartyPeriodId} maxLength="36" onChange={event=>{setCounterpartyPeriodId(event.target.value.trim());setIntercompanyState({phase:'IDLE',rows:[],error:null,scope:null,complete:false});}} placeholder="UUID with the same period dates"/></label><button type="button" className="btn" disabled={!counterpartyEntityId||!counterpartyPeriodId||counterpartyEntityId===config.entityId} onClick={loadIntercompany}>Load reconciliation evidence</button></div>
      <p className="muted sm">A shared account code, memo, vendor, or amount is never enough. The API separately verifies report authority for the counterparty entity and rejects unaligned period boundaries. No elimination or adjustment is created by this report.</p>
      {intercompanyState.phase==='LOADING'&&<StateBlock tone="loading">Loading bidirectional intercompany POSTED evidence...</StateBlock>}
      {intercompanyState.phase==='ERROR'&&<StateBlock tone="error" title={intercompanyState.error?.code}><p>{intercompanyState.error?.message}</p></StateBlock>}
      {intercompanyState.phase==='READY'&&!intercompanyState.rows.length&&<StateBlock tone="empty" title="No admitted intercompany evidence returned">This scoped empty result is not evidence of no intercompany balance, no elimination requirement, or a completed consolidation review.</StateBlock>}
      {intercompanyState.phase==='READY'&&!!intercompanyState.rows.length&&!intercompanyState.complete&&<StateBlock tone="error" title="BLOCKED_INTERCOMPANY_EVIDENCE">At least one account pair lacks an exact bidirectional mapping or retained POSTED evidence. REFS will not assert an intercompany conclusion.</StateBlock>}
      {intercompanyState.phase==='READY'&&!!intercompanyState.rows.length&&<div className="table-wrap"><table className="tbl"><thead><tr><th>Account pair</th><th className="ta-r">Current</th><th className="ta-r">Counterparty</th><th className="ta-r">Difference</th><th>Result</th><th>Evidence</th></tr></thead><tbody>{intercompanyState.rows.map(row=>{const focusId=`authoritative-intercompany-${row.account_code}-${row.counterparty_account_code}`;return <tr key={`${row.account_code}:${row.counterparty_account_code}`}><td><b>{row.account_code}</b><div className="muted sm">↔ {row.counterparty_account_code}</div><div className="muted sm">{row.mapping_status}</div></td><td className="num">{row.current_closing_balance===null?'Blocked':money(row.current_closing_balance)}</td><td className="num">{row.counterparty_closing_balance===null?'Blocked':money(row.counterparty_closing_balance)}</td><td className="num">{row.difference_amount===null?'Blocked':money(row.difference_amount)}</td><td><span className={row.in_balance?'badge badge-ok':'badge badge-warn'}>{row.in_balance?'Tied':'Review required'}</span></td><td><button id={focusId} type="button" className="btn btn-sm" onClick={()=>{const base=createAuthoritativeReturnContext({config,view:DEFAULT_AUTHORITATIVE_LIST_VIEW,focusId,scrollY:Number(environment?.scrollY)||0});if(base)setSelected({kind:'INTERCOMPANY_RECONCILIATION',row,returnContext:{...base,report}});}}>Open evidence</button></td></tr>;})}</tbody></table></div>}
    </section>
    <section className="card" aria-label="Budget versus actual evidence">
      <div className="card-head"><div><h2>Budget versus actual</h2><p className="muted sm">Latest approved immutable budget snapshot versus same-entity, same-period, same-currency POSTED ledger evidence.</p></div><span className="badge badge-muted">READ ONLY</span></div>
      <div className="qbo-filter-grid"><button type="button" className="btn" onClick={loadBudget}>Load budget evidence</button></div>
      <p className="muted sm">A comparison side is declared by the approved budget line; REFS never infers it from an account name, code, prior actual, WBS status, or a browser fixture. Missing snapshot, account, currency, or POSTED evidence remains BLOCKED and is never converted to zero.</p>
      {budgetState.phase==='LOADING'&&<StateBlock tone="loading">Loading immutable budget and POSTED actual evidence...</StateBlock>}
      {budgetState.phase==='ERROR'&&<StateBlock tone="error" title={budgetState.error?.code}><p>{budgetState.error?.message}</p></StateBlock>}
      {budgetState.phase==='READY'&&!budgetState.rows.length&&<StateBlock tone="empty" title="No approved budget snapshot returned">No approved immutable budget snapshot was returned for this entity and period. This scoped empty result is not zero budget or zero actual.</StateBlock>}
      {budgetState.phase==='READY'&&!!budgetState.rows.length&&!budgetState.complete&&<StateBlock tone="error" title="BLOCKED_BUDGET_ACTUAL_EVIDENCE">At least one budget line lacks an active account, same-currency POSTED actual, or complete immutable budget evidence. REFS will not calculate a budget conclusion for that line.</StateBlock>}
      {budgetState.phase==='READY'&&!!budgetState.rows.length&&<div className="table-wrap"><table className="tbl"><thead><tr><th>Account</th><th>Side</th><th className="ta-r">Budget</th><th className="ta-r">Actual</th><th className="ta-r">Variance</th><th>Snapshot</th><th>Evidence</th></tr></thead><tbody>{budgetState.rows.map(row=>{const focusId=`authoritative-budget-${row.account_code}`;return <tr key={row.account_code}><td><b>{row.account_code}</b><div className="muted sm">{row.account_name}</div><div className="muted sm">{row.report_status}</div></td><td>{row.comparison_side}</td><td className="num">{row.budget_amount===null?'Blocked':money(row.budget_amount)}</td><td className="num">{row.actual_amount===null?'Blocked':money(row.actual_amount)}</td><td className="num">{row.variance_amount===null?'Blocked':money(row.variance_amount)}</td><td><code>{row.budget_snapshot_id}</code><div className="muted sm">v{row.budget_version}</div></td><td><button id={focusId} type="button" className="btn btn-sm" onClick={()=>{const base=createAuthoritativeReturnContext({config,view:DEFAULT_AUTHORITATIVE_LIST_VIEW,focusId,scrollY:Number(environment?.scrollY)||0});if(base)setSelected({kind:'BUDGET_VS_ACTUAL',row,returnContext:{...base,report}});}}>Open evidence</button></td></tr>;})}</tbody></table></div>}
    </section>
    <section className="card" aria-label="Consolidation evidence">
      <div className="card-head"><div><h2>Consolidation and elimination evidence</h2><p className="muted sm">An approved immutable consolidation snapshot must explicitly name every member, account presentation mapping, and elimination evidence.</p></div><span className="badge badge-muted">READ ONLY</span></div>
      <div className="qbo-filter-grid"><label>Consolidation group<input value={consolidationGroupRef} maxLength="160" onChange={event=>{setConsolidationGroupRef(event.target.value);setConsolidationState({phase:'IDLE',rows:[],error:null,scope:null,complete:false});}} placeholder="Canonical approved group reference"/></label><button type="button" className="btn" disabled={!consolidationGroupRef.trim()} onClick={loadConsolidation}>Load consolidation evidence</button></div>
      <p className="muted sm">REFS never assumes that matching account codes, amounts, or entity names form a consolidation. Missing member scope, aligned period/currency, posted ledger, mapping, or elimination evidence is BLOCKED. This view cannot create an elimination journal.</p>
      {consolidationState.phase==='LOADING'&&<StateBlock tone="loading">Loading immutable consolidation and POSTED ledger evidence...</StateBlock>}
      {consolidationState.phase==='ERROR'&&<StateBlock tone="error" title={consolidationState.error?.code}><p>{consolidationState.error?.message}</p></StateBlock>}
      {consolidationState.phase==='READY'&&!consolidationState.rows.length&&<StateBlock tone="empty" title="No approved consolidation snapshot returned">No approved immutable consolidation snapshot was returned for this reporting entity, period, and group. This scoped empty result is not evidence of zero eliminations or a completed consolidation.</StateBlock>}
      {consolidationState.phase==='READY'&&!!consolidationState.rows.length&&!consolidationState.complete&&<StateBlock tone="error" title="BLOCKED_CONSOLIDATION_EVIDENCE">At least one presented account lacks member scope, aligned period/currency, POSTED ledger, or approved elimination evidence. REFS will not calculate a consolidation conclusion.</StateBlock>}
      {consolidationState.phase==='READY'&&!!consolidationState.rows.length&&<div className="table-wrap"><table className="tbl"><thead><tr><th>Presentation account</th><th>Members</th><th className="ta-r">Member actual</th><th className="ta-r">Elimination</th><th className="ta-r">Consolidated</th><th>Evidence</th></tr></thead><tbody>{consolidationState.rows.map(row=>{const focusId=`authoritative-consolidation-${row.presentation_account_code}-${row.presentation_side}`;return <tr key={`${row.presentation_account_code}:${row.presentation_side}`}><td><b>{row.presentation_account_code}</b><div className="muted sm">{row.presentation_side}</div><div className="muted sm">{row.report_status}</div></td><td>{row.evidence_member_count}/{row.member_count}</td><td className="num">{row.member_actual_amount===null?'Blocked':money(row.member_actual_amount)}</td><td className="num">{row.elimination_amount===null?'Blocked':money(row.elimination_amount)}</td><td className="num">{row.consolidated_amount===null?'Blocked':money(row.consolidated_amount)}</td><td><button id={focusId} type="button" className="btn btn-sm" onClick={()=>{const base=createAuthoritativeReturnContext({config,view:DEFAULT_AUTHORITATIVE_LIST_VIEW,focusId,scrollY:Number(environment?.scrollY)||0});if(base)setSelected({kind:'CONSOLIDATION',row,returnContext:{...base,report}});}}>Open evidence</button></td></tr>;})}</tbody></table></div>}
    </section>
    <section className="card" aria-label="Dimension profitability evidence">
      <div className="card-head"><div><h2>Dimension profitability</h2><p className="muted sm">Property, Project, and Unit P&amp;L use only exact dimensions retained on POSTED ledger lines.</p></div><span className="badge badge-muted">READ ONLY</span></div>
      <div className="qbo-filter-grid"><label>Dimension type<select value={dimensionType} onChange={event=>{setDimensionType(event.target.value);setDimensionState({phase:'IDLE',rows:[],error:null,scope:null});}}>{DIMENSION_TYPES.map(([key,label])=><option key={key} value={key}>{label}</option>)}</select></label><label>Exact reference<input value={dimensionRef} maxLength="160" onChange={event=>setDimensionRef(event.target.value)} placeholder="e.g. PROPERTY-01"/></label><button type="button" className="btn" disabled={!dimensionRef.trim()} onClick={loadDimension}>Load profitability evidence</button></div>
      <p className="muted sm">A blank result is not zero profitability: it means no retained POSTED ledger line carries this exact dimension for the selected period. The report never infers a dimension from a memo, bank account, or source header.</p>
      {dimensionState.phase==='LOADING'&&<StateBlock tone="loading">Loading exact-dimension POSTED ledger evidence...</StateBlock>}
      {dimensionState.phase==='ERROR'&&<StateBlock tone="error" title={dimensionState.error?.code}><p>{dimensionState.error?.message}</p></StateBlock>}
      {dimensionState.phase==='READY'&&!dimensionState.rows.length&&<StateBlock tone="empty" title="No exact-dimension POSTED ledger evidence returned">This scoped empty result is not evidence of zero property, project, or unit profitability.</StateBlock>}
      {dimensionState.phase==='READY'&&!!dimensionState.rows.length&&<div className="table-wrap"><table className="tbl"><thead><tr><th>Section</th><th>Account</th><th>Period debit</th><th>Period credit</th><th>Balance</th><th>Evidence</th></tr></thead><tbody>{dimensionState.rows.map(row=>{const focusId=`authoritative-dimension-${row.dimension_type}-${row.dimension_ref}-${row.account_code}`;return <tr key={`${row.dimension_type}:${row.dimension_ref}:${row.statement_section}:${row.account_code}`}><td>{row.statement_section}</td><td><b>{row.account_code}</b><div className="muted sm">{row.account_name}</div></td><td className="num">{money(row.period_debit)}</td><td className="num">{money(row.period_credit)}</td><td className="num">{money(row.display_balance)}</td><td><button id={focusId} type="button" className="btn btn-sm" onClick={()=>openEvidence(row,focusId)}>Open evidence</button></td></tr>;})}</tbody></table></div>}
    </section>
  </div>;
}
