import React,{useCallback,useEffect,useMemo,useState}from'react';
import{refreshAuthoritativeMappingCatalogs}from'./accounting-api.js';
import{StateBlock}from'./ui.jsx';
const shortHash=value=>`${value.slice(0,15)}…${value.slice(-8)}`;
const statement=value=>value==='BS'?'Balance Sheet':'Income Statement';
const present=value=>value??'—';

export function AuthoritativeReportMappingsWorkspace({config,fetcher=globalThis.fetch}){
 const[state,setState]=useState({phase:'LOADING',data:null,error:null});const[query,setQuery]=useState('');const load=useCallback(async()=>{setState({phase:'LOADING',data:null,error:null});const result=await refreshAuthoritativeMappingCatalogs({config,fetcher});setState(result.ok?{phase:'READY',data:result.data,error:null}:{phase:'ERROR',data:null,error:result});},[config,fetcher]);useEffect(()=>{load();},[load]);const data=state.data;
 const reportRows=useMemo(()=>{const needle=query.trim().toLowerCase();return !needle||!data?data?.report.mappings||[]:data.report.mappings.filter(row=>[row.account_code,row.account_role,row.account_class,row.account_type,row.statement,row.report_row_code,row.cash_flow_class,...row.dimension_requirements].some(value=>String(value).toLowerCase().includes(needle)));},[data,query]);
 const dimensionRows=useMemo(()=>{const needle=query.trim().toLowerCase();return !needle||!data?data?.dimensions.mappings||[]:data.dimensions.mappings.filter(row=>[row.rule_id,row.scope_level,row.project_ref,row.property_ref,row.cost_code_ref,row.member_ref,row.capitalization_treatment,row.cwip_account_role,row.status].some(value=>String(value??'').toLowerCase().includes(needle)));},[data,query]);
 return <section className="workspace-card" aria-labelledby="report-mappings-title"><header className="workspace-title-row"><div><p className="eyebrow">APPROVED MAPPING EVIDENCE</p><h2 id="report-mappings-title">Mapping Center</h2><p>Review complete approved account-to-report and project, property, and cost-code mapping catalogs for this company and period.</p></div><button type="button" onClick={load} disabled={state.phase==='LOADING'}>Refresh</button></header>
 {state.phase==='LOADING'&&<StateBlock tone="loading">Reading approved mapping catalogs...</StateBlock>}{state.error&&<StateBlock tone="danger">{state.error.code}: {state.error.message}</StateBlock>}
 {data&&<><div className="summary-grid"><article><span>Period</span><strong>{data.report.scope.period_code}</strong><small>{data.report.scope.period_status} · {data.report.scope.currency}</small></article><article><span>Report mappings</span><strong>{data.report.population.total_count}</strong><small>Complete immutable population</small></article><article><span>Dimension mappings</span><strong>{data.dimensions.population.total_count}</strong><small>Complete immutable population</small></article><article><span>Approved snapshots</span><strong>Versions {data.report.approval.report_mapping_version} / {data.dimensions.approval.dimension_mapping_version}</strong><small>{data.report.approval.approved_by} · {data.report.approval.approved_at}</small></article></div>
 <label className="field"><span>Find approved mappings</span><input type="search" value={query} onChange={event=>setQuery(event.target.value)} placeholder="Account, report row, project, property, cost code, or rule"/></label>
 <h3>Account-to-report mappings</h3><p className="muted sm">Showing {reportRows.length} of {data.report.population.total_count} complete approved report mappings. Population hash: <span className="mono" title={data.report.population.population_hash}>{shortHash(data.report.population.population_hash)}</span></p>
 <div className="table-wrap" tabIndex="0" role="region" aria-label="Approved account-to-report mappings; scroll horizontally to view every column"><table><thead><tr><th>Account</th><th>Role / class</th><th>Statement / report row</th><th>Normal balance</th><th>Cash flow</th><th>Dimensions</th><th>Effective</th><th>Evidence hash</th></tr></thead><tbody>{reportRows.map(row=><tr key={`${row.account_code}:${row.account_role}`}><td><strong>{row.account_code}</strong><br/><span className="muted sm">{row.account_type}</span></td><td>{row.account_role}<br/><span className="muted sm">{row.account_class}{row.contra?' · Contra':''}</span></td><td>{statement(row.statement)}<br/><span className="mono sm">{row.report_row_code}</span></td><td>{row.normal_balance}</td><td>{row.cash_flow_class}</td><td>{row.dimension_requirements.length?row.dimension_requirements.join(', '):'None'}</td><td>{row.effective_from} to {row.effective_to||'Open-ended'}</td><td className="mono sm" title={row.mapping_hash}>{shortHash(row.mapping_hash)}</td></tr>)}</tbody></table></div>{reportRows.length===0&&<StateBlock tone="empty">No approved report mappings match this local filter. The authoritative population remains unchanged.</StateBlock>}
 <h3>Project, property, and cost-code mappings</h3><p className="muted sm">Showing {dimensionRows.length} of {data.dimensions.population.total_count} complete approved dimension mappings. Population hash: <span className="mono" title={data.dimensions.population.population_hash}>{shortHash(data.dimensions.population.population_hash)}</span></p>
 <div className="table-wrap" tabIndex="0" role="region" aria-label="Approved project, property, and cost-code mappings; scroll horizontally to view every column"><table><thead><tr><th>Rule / scope</th><th>Project</th><th>Property</th><th>Cost code / member</th><th>Treatment</th><th>Requirements</th><th>Status / effective</th><th>Evidence hash</th></tr></thead><tbody>{dimensionRows.map(row=><tr key={row.rule_id}><td><strong>{row.rule_id}</strong><br/><span className="muted sm">{row.scope_level}</span></td><td>{present(row.project_ref)}</td><td>{present(row.property_ref)}</td><td>{present(row.cost_code_ref)}<br/><span className="muted sm">Member: {present(row.member_ref)}</span></td><td>{row.capitalization_treatment}<br/><span className="muted sm">CWIP role: {row.cwip_account_role}</span></td><td>Ownership: {row.ownership_requirement}<br/><span className="muted sm">Member: {row.member_requirement}</span></td><td>{row.status} · {row.effective_for_period?'In period':'Outside period'}<br/><span className="muted sm">{row.effective_from} to {row.effective_to||'Open-ended'}</span></td><td className="mono sm" title={row.mapping_hash}>{shortHash(row.mapping_hash)}</td></tr>)}</tbody></table></div>{dimensionRows.length===0&&<StateBlock tone="empty">No approved dimension mappings match this local filter. The authoritative population remains unchanged.</StateBlock>}
 <p className="muted sm">Read only. These catalogs cannot create, edit, approve, deactivate, import, automatically apply, or post a mapping. Vendor, source-field, mapping-exception, and mapping-history catalogs remain separate unavailable read models.</p></>}
 </section>;
}
