import React from 'react';
import { nextAuthoritativeWorkflowAction } from './authoritative-workflow.js';
import { StateBlock } from './ui.jsx';
import {
  authoritativeEvidenceKey,
  filterAuthoritativeRows,
  normalizeAuthoritativeListView,
  paginateAuthoritativeRows,
} from './authoritative-list-context.js';

const money=(value,currency)=>new Intl.NumberFormat('en-US',{style:'currency',currency:/^[A-Z]{3}$/.test(currency||'')?currency:'USD'}).format(Number(value)||0);
const date=/^\d{4}-\d{2}-\d{2}$/;
const amount=/^(?:0|[1-9]\d{0,15})(?:\.\d{1,4})?$/;
const account=/^[A-Za-z0-9._-]{1,64}$/;
export const validateAuthoritativeDocumentDraft=values=>{
  const kind=['AP_BILL','AR_INVOICE'].includes(values?.kind)?values.kind:null;
  const documentNumber=String(values?.documentNumber||'').trim(),counterpartyRef=String(values?.counterpartyRef||'').trim(),counterpartyName=String(values?.counterpartyName||'').trim(),currency=String(values?.currency||'').trim().toUpperCase(),accountingDate=String(values?.accountingDate||'').trim(),dueDate=String(values?.dueDate||'').trim(),value=String(values?.amount||'').trim(),offsetAccountCode=String(values?.offsetAccountCode||'').trim(),description=String(values?.description||'').trim();
  if(!kind||!documentNumber||documentNumber.length>128||!counterpartyRef||counterpartyRef.length>128||!counterpartyName||counterpartyName.length>255||!/^[A-Z]{3}$/.test(currency)||!date.test(accountingDate)||!amount.test(value)||Number(value)<=0||!account.test(offsetAccountCode)||description.length>2000||(dueDate&&!date.test(dueDate)))return {ok:false,code:'AUTHORITATIVE_DOCUMENT_INVALID',message:'Complete the Draft fields with valid dates, a positive four-decimal amount, and an account code.'};
  return {ok:true,kind,document:{documentNumber,counterpartyRef,counterpartyName,currency,accountingDate,dueDate:dueDate||null,amount:value,offsetAccountCode,description:description||null}};
};
export function AuthoritativeDocumentTable({title,documents=[],kind,onOpen}) {
  const bill=kind==='AP',number=bill?'bill_no':'inv_no',counterparty=bill?'vendor_name':'customer_name',dateKey=bill?'bill_date':'inv_date';
  return <section aria-label={title}><div className="card-head"><div><h2>{title}</h2><p className="muted sm">Authoritative API rows only. Open a row to inspect its retained evidence.</p></div></div>{documents.length?<div className="table-wrap"><table className="tbl"><thead><tr><th>{bill?'Bill':'Invoice'}</th><th>{bill?'Vendor':'Customer'}</th><th>Date</th><th>Due date</th><th className="ta-r">Amount</th><th className="ta-r">Open balance</th><th>Status</th><th>Evidence</th></tr></thead><tbody>{documents.map(row=>{
    const key=authoritativeEvidenceKey('document',row)||row.journal_entry_id||row[bill?'bill_id':'inv_id']||row[number];
    const focusId=authoritativeEvidenceKey('document',row)?`authoritative-document-${row.business_document_id}`:undefined;
    return <tr key={key}><td>{row[number]}</td><td>{row[counterparty]}</td><td>{row[dateKey]}</td><td>{row.due_date||'Not retained'}</td><td className="ta-r">{money(row.amount,row.currency)}</td><td className="ta-r">{money(row.open_balance,row.currency)}</td><td>{row.status}</td><td><button id={focusId} type="button" className="btn btn-sm btn-ghost" onClick={()=>onOpen?.(row,focusId)}>Open evidence</button></td></tr>;
  })}</tbody></table></div>:<StateBlock tone="empty" title={`No authoritative ${bill?'bills':'invoices'} in this scope`}>This scoped empty result is not evidence of a zero balance.</StateBlock>}</section>;
}

export function AuthoritativeDocumentDetail({document,kind,entityId,onBack}){const bill=kind==='AP',number=bill?'bill_no':'inv_no',counterparty=bill?'vendor_name':'customer_name',dateKey=bill?'bill_date':'inv_date',title=bill?'Bill evidence':'Invoice evidence';return <section className="full-bleed qbo-transaction-report" aria-label={title}><div className="qbo-report-back"><button type="button" onClick={onBack}>Back to {bill?'AP bills':'AR invoices'}</button><span>Entity {entityId} · authoritative list revision {document.revision}</span></div><div className="gl-drill-head"><div><div className="gl-drill-crumb">{bill?'Payables':'Receivables'} / read-only evidence</div><h1>{document[number]}</h1><div className="gl-drill-account">{document[counterparty]} · {document[dateKey]}</div></div><span className="badge badge-muted">{document.status}</span></div><p className="report-drill-hint">This page shows only fields retained by the authenticated AP/AR list read model. It cannot create, edit, approve, pay, allocate, post, print, export, or synchronize a document.</p><div className="table-wrap"><table className="tbl" aria-label={`${title} fields`}><tbody><tr><th>Entity</th><td>{entityId}</td><th>{bill?'Vendor':'Customer'}</th><td>{document[counterparty]}</td></tr><tr><th>{bill?'Bill':'Invoice'} date</th><td>{document[dateKey]}</td><th>Due date</th><td>{document.due_date||'Not retained'}</td></tr><tr><th>Currency</th><td>{document.currency}</td><th>Status</th><td>{document.status}</td></tr><tr><th>Original amount</th><td>{money(document.amount,document.currency)}</td><th>Open balance</th><td>{money(document.open_balance,document.currency)}</td></tr><tr><th>Offset account</th><td>{document.account_code||'Not retained'}</td><th>Posted journal</th><td>{document.je_number||'Not retained'}</td></tr><tr><th>Period ID</th><td>{document.period_id||'Not retained'}</td><th>Description</th><td>{document.description||'Not retained'}</td></tr></tbody></table></div></section>;}

export function AuthoritativeAdjustmentSummary({title,adjustments=[],onOpen}) {
  return <section aria-label={title}><div className="card-head"><div><h2>{title}</h2><p className="muted sm">Authoritative adjustment rows only. Open a row to inspect its retained evidence.</p></div></div>{adjustments.length?<div className="table-wrap"><table className="tbl"><thead><tr><th>Adjustment</th><th>Date</th><th>Reason</th><th className="ta-r">Amount</th><th>Status</th><th>Evidence</th></tr></thead><tbody>{adjustments.map(row=>{
    const focusId=authoritativeEvidenceKey('adjustment',row)?`authoritative-adjustment-${row.business_adjustment_id}`:undefined;
    return <tr key={row.business_adjustment_id}><td>{row.adjustment_kind}</td><td>{row.accounting_date}</td><td>{row.reason||'Not retained'}</td><td className="ta-r">{money(row.amount,row.currency)}</td><td>{row.status}</td><td><button id={focusId} type="button" className="btn btn-sm btn-ghost" onClick={()=>onOpen?.(row,focusId)}>Open evidence</button></td></tr>;
  })}</tbody></table></div>:<StateBlock tone="empty" title="No authoritative adjustments in this scope">This scoped empty result is not evidence of a zero balance.</StateBlock>}</section>;
}

export function AuthoritativeAdjustmentDetail({adjustment,side,entityId,onBack}){const label=side==='AP'?'AP adjustment evidence':'AR adjustment evidence';return <section className="full-bleed qbo-transaction-report" aria-label={label}><div className="qbo-report-back"><button type="button" onClick={onBack}>Back to {side==='AP'?'AP adjustments':'AR adjustments'}</button><span>Entity {entityId} · authoritative adjustment revision {adjustment.version}</span></div><div className="gl-drill-head"><div><div className="gl-drill-crumb">{side==='AP'?'Payables':'Receivables'} / read-only adjustment evidence</div><h1>{adjustment.adjustment_kind}</h1><div className="gl-drill-account">{adjustment.accounting_date} · {adjustment.business_adjustment_id}</div></div><span className="badge badge-muted">{adjustment.status}</span></div><p className="report-drill-hint">This page contains only fields returned by the authenticated adjustment read model. It cannot create, edit, apply, refund, approve, post, reverse, print, export, or synchronize an adjustment.</p><div className="table-wrap"><table className="tbl" aria-label={`${label} fields`}><tbody><tr><th>Entity</th><td>{entityId}</td><th>Period ID</th><td>{adjustment.period_id}</td></tr><tr><th>Currency</th><td>{adjustment.currency}</td><th>Amount</th><td>{money(adjustment.amount,adjustment.currency)}</td></tr><tr><th>Status</th><td>{adjustment.status}</td><th>Revision</th><td>{adjustment.version}</td></tr><tr><th>Document ID</th><td>{adjustment.business_document_id||'Not retained'}</td><th>Source adjustment</th><td>{adjustment.source_adjustment_id||'Not retained'}</td></tr><tr><th>Journal entry</th><td>{adjustment.journal_entry_id||'Not retained'}</td><th>Journal status</th><td>{adjustment.journal_status||'Not retained'}</td></tr><tr><th>Created at</th><td>{adjustment.created_at}</td><th>Reason</th><td>{adjustment.reason||'Not retained'}</td></tr></tbody></table></div></section>;}

export function AuthoritativeDocumentWorkspace({kind,documents=[],adjustments=[],view,onViewChange,onOpenDocument,onOpenAdjustment}) {
  const bill=kind==='AP';
  const state=normalizeAuthoritativeListView(view);
  const dateField=bill?'bill_date':'inv_date';
  const filteredDocuments=filterAuthoritativeRows(documents,state,dateField);
  const page=paginateAuthoritativeRows(filteredDocuments,state);
  const filteredAdjustments=filterAuthoritativeRows(adjustments,state,'accounting_date');
  const statuses=[...new Set([...documents,...adjustments].map(row=>row?.status).filter(Boolean))].sort();
  const change=patch=>onViewChange?.({...state,...patch,page:patch.page??1});
  return <div className="authoritative-document-workspace">
    <div className="filter-bar authoritative-list-filters" role="search" aria-label={`${bill?'Payables':'Receivables'} presentation filters`}>
      <label>Search <input value={state.query} onChange={event=>change({query:event.target.value})} placeholder={bill?'Bill or vendor':'Invoice or customer'}/></label>
      <label>Status <select value={state.status} onChange={event=>change({status:event.target.value})}><option value="ALL">All statuses</option>{statuses.map(status=><option key={status} value={status}>{status}</option>)}</select></label>
      <label>From <input type="date" value={state.from} onChange={event=>change({from:event.target.value})}/></label>
      <label>Through <input type="date" value={state.through} onChange={event=>change({through:event.target.value})}/></label>
      <span className="result-count" aria-live="polite">{page.total} {bill?'bills':'invoices'} · {filteredAdjustments.length} adjustments</span>
    </div>
    {page.total?<AuthoritativeDocumentTable title={bill?'AP bills':'AR invoices'} documents={page.rows} kind={kind} onOpen={onOpenDocument}/>:<StateBlock tone="empty" title={documents.length?`No ${bill?'bills':'invoices'} match these presentation filters`:`No authoritative ${bill?'bills':'invoices'} in this scope`}>{documents.length?'Change a presentation filter to see retained list facts. A local no-match is not evidence of zero balance.':'This scoped empty result is not evidence of a zero balance.'}</StateBlock>}
    {page.pageCount>1&&<nav className="pagination" aria-label={`${bill?'AP bills':'AR invoices'} pages`}><button type="button" disabled={page.page===1} onClick={()=>change({page:page.page-1})}>Previous</button><span>Page {page.page} of {page.pageCount}</span><button type="button" disabled={page.page===page.pageCount} onClick={()=>change({page:page.page+1})}>Next</button></nav>}
    {filteredAdjustments.length?<AuthoritativeAdjustmentSummary title={bill?'AP adjustments':'AR adjustments'} adjustments={filteredAdjustments} onOpen={onOpenAdjustment}/>:<StateBlock tone="empty" title={adjustments.length?'No adjustments match these presentation filters':'No authoritative adjustments in this scope'}>{adjustments.length?'Change a presentation filter to see retained adjustment facts. A local no-match is not evidence of zero balance.':'This scoped empty result is not evidence of a zero balance.'}</StateBlock>}
  </div>;
}
export function AuthoritativeWorkflowTable({title,documents=[],kind,onWorkflow,workingJournalIds=new Set()}){const bill=kind==='AP';return <section aria-label={title}><h2>{title}</h2>{documents.map(row=>{const action=nextAuthoritativeWorkflowAction(row.journal_status);return <div key={row.journal_entry_id}>{row[bill?'bill_no':'inv_no']} {action?<button disabled={workingJournalIds.has(row.journal_entry_id)} onClick={()=>onWorkflow(row,action)}>{action}</button>:row.journal_status}</div>;})}</section>;}
export function AuthoritativeWorkflowAdjustmentTable({title,adjustments=[],onWorkflow,workingJournalIds=new Set()}){return <section aria-label={title}><h2>{title}</h2>{adjustments.map(row=>{const action=nextAuthoritativeWorkflowAction(row.journal_status);return <div key={row.business_adjustment_id}>{row.adjustment_kind} {action?<button disabled={workingJournalIds.has(row.journal_entry_id)} onClick={()=>onWorkflow(row,action)}>{action}</button>:row.journal_status}</div>;})}</section>;}
export function AuthoritativeCreditApplicationForm({kind,credits=[],documents=[]}){const label=kind==='AR_CREDIT_MEMO'?'Credit memo':'Vendor credit';return <section aria-label={`Apply ${label}`}><h2>Apply {label}</h2><select>{credits.filter(x=>x.status==='POSTED').map(x=><option key={x.business_adjustment_id}>{x.business_adjustment_id}</option>)}</select><select>{documents.map(x=><option key={x.business_document_id}>{x.inv_no||x.bill_no}</option>)}</select></section>;}
export function AuthoritativeRefundForm({credits=[]}){return <section aria-label="Create refund Draft"><h2>Create refund Draft</h2><label>Credit memo<select>{credits.filter(x=>x.status==='POSTED').map(x=><option key={x.business_adjustment_id}>{x.business_adjustment_id}</option>)}</select></label></section>;}
export function AuthoritativeDraftForm(){return <section aria-label="Create Draft only"><h2>Create Draft only</h2><p>Drafts are sent to the authoritative API and require review and approval before any separate posting command.</p></section>;}
export function AuthoritativeRuntimeLock(){return <main className="login-shell"><section className="login-card" role="alert"><h1>Authoritative API required</h1><p>The deployed REFS client is locked until its HTTPS accounting API and OIDC token provider are configured.</p></section></main>;}
