import React,{useEffect,useMemo,useState} from 'react';
import {proposeAuthoritativeAiInvoiceExpense,refreshAuthoritativeAiInvoiceExpenseEvidence,refreshAuthoritativeAiInvoiceExpenseProposals} from './accounting-api.js';
import {StateBlock} from './ui.jsx';

const initial={evidenceId:'',expenseAccountCode:'',liabilityAccountCode:'',allocationBasis:'SOURCE_DIMENSIONED',projectRef:'',propertyRef:'',reason:''};
export function AuthoritativeExpensePanel({config,fetcher=globalThis.fetch}){
  const [state,setState]=useState({phase:'LOADING',evidence:[],proposals:[],error:null}),[form,setForm]=useState(initial),[submit,setSubmit]=useState({phase:'IDLE',message:''});
  const load=async()=>{const [evidence,proposals]=await Promise.all([refreshAuthoritativeAiInvoiceExpenseEvidence({config,fetcher}),refreshAuthoritativeAiInvoiceExpenseProposals({config,fetcher})]);setState(evidence.ok&&proposals.ok?{phase:'READY',evidence:evidence.rows,proposals:proposals.rows,error:null}:{phase:'BLOCKED',evidence:[],proposals:[],error:evidence.ok?proposals:evidence});};
  useEffect(()=>{void load();},[config?.entityId,config?.periodId]);
  const used=useMemo(()=>new Set(state.proposals.map(row=>row.classification_evidence_id)),[state.proposals]),available=state.evidence.filter(row=>!used.has(row.classification_evidence_id)),selected=available.find(row=>row.classification_evidence_id===form.evidenceId)||null,change=event=>setForm(current=>({...current,[event.target.name]:event.target.value}));
  const propose=async event=>{event.preventDefault();if(!selected)return;const dimensioned=form.allocationBasis==='SOURCE_DIMENSIONED';setSubmit({phase:'SAVING',message:''});const result=await proposeAuthoritativeAiInvoiceExpense({config,evidence:selected,expenseAccountCode:form.expenseAccountCode.trim(),liabilityAccountCode:form.liabilityAccountCode.trim(),memberTrace:{project_ref:dimensioned?(form.projectRef.trim()||null):null,property_ref:dimensioned?(form.propertyRef.trim()||null):null,allocation_basis:form.allocationBasis},reason:form.reason,idempotencyKey:`ai-invoice-expense:${globalThis.crypto?.randomUUID?.()||Date.now()}`,fetcher});if(!result.ok){setSubmit({phase:'ERROR',message:`${result.code}: ${result.message}`});return;}setSubmit({phase:'SAVED',message:'The policy-backed expense proposal was retained. No Draft or posting action occurred.'});setForm(initial);await load();};
  return <section className="card" aria-label="Invoice expense proposals"><div className="card-head"><div><h2>Invoice expense review</h2><p className="muted sm">Retained invoice evidence classified as expense under the approved capitalization policy. A human confirms accounts and source dimensions before retaining a balanced proposal.</p></div><span className="badge badge-muted">PROPOSAL ONLY</span></div>
    {state.phase==='BLOCKED'?<StateBlock tone="blocked" title={state.error?.code||'EXPENSE_READ_BLOCKED'}>{state.error?.message} No cached or demonstration evidence is substituted.</StateBlock>:null}
    {state.phase==='READY'?<><form className="form-grid" onSubmit={propose}><label>Retained expense decision<select name="evidenceId" value={form.evidenceId} onChange={change} required><option value="">Select source-bound evidence</option>{available.map(row=><option key={row.classification_evidence_id} value={row.classification_evidence_id}>{row.source_document_id} - {(row.confidence*100).toFixed(0)}%</option>)}</select></label><label>Expense account<input name="expenseAccountCode" value={form.expenseAccountCode} onChange={change} required/></label><label>Offset liability account<input name="liabilityAccountCode" value={form.liabilityAccountCode} onChange={change} required/></label><label>Allocation basis<select name="allocationBasis" value={form.allocationBasis} onChange={change}><option value="SOURCE_DIMENSIONED">Source dimensioned</option><option value="ENTITY_ONLY">Entity only</option></select></label>{form.allocationBasis==='SOURCE_DIMENSIONED'?<><label>Project reference<input name="projectRef" value={form.projectRef} onChange={change}/></label><label>Property reference<input name="propertyRef" value={form.propertyRef} onChange={change}/></label></>:null}<label className="form-span">Controller rationale<textarea name="reason" minLength={8} maxLength={2000} value={form.reason} onChange={change} required/></label><div className="form-span"><button className="btn btn-primary" disabled={!selected||submit.phase==='SAVING'}>{submit.phase==='SAVING'?'Retaining proposal...':'Retain expense proposal'}</button> <span className="muted sm">No Draft, review, approval, or posting authority.</span></div></form>{submit.message?<StateBlock tone={submit.phase==='ERROR'?'blocked':'success'} title={submit.phase==='ERROR'?'Proposal blocked':'Proposal retained'}>{submit.message}</StateBlock>:null}
      {state.proposals.length===0?<StateBlock tone="empty" title="No retained expense proposals">No source-bound expense proposal has been retained for this entity.</StateBlock>:<div className="table-wrap" role="region" tabIndex={0}><table className="tbl"><thead><tr><th>Source</th><th>Balanced treatment</th><th>Amount</th><th>Reason / confidence</th><th>Evidence</th><th>Authority</th></tr></thead><tbody>{state.proposals.map(row=><tr key={row.ai_invoice_expense_proposal_id}><td><b>{row.source_document_id}</b><div className="muted sm">Line {row.source_document_line_id}</div></td><td>Dr {row.expense_account_code}<br/>Cr {row.liability_account_code}</td><td>{row.currency} {row.amount}</td><td>{row.proposal_reason}<div className="muted sm">{(row.confidence*100).toFixed(0)}% / {row.rule_id}</div></td><td><details><summary>Policy and source hashes</summary><div className="mono sm">{row.policy_snapshot_id}<br/>{row.policy_snapshot_hash}<br/>{row.source_payload_hash}<br/>{row.source_line_hash}</div></details></td><td><span className="badge badge-muted">PROPOSED</span><div className="muted sm">NO DRAFT OR POST</div></td></tr>)}</tbody></table></div>}</>:null}
  </section>;
}
