import React,{useEffect,useRef,useState} from 'react';
import {readBillPaymentRegister,readBillPaymentJournal} from './bill-payment-register.js';
import {AuthoritativeLineageDrill} from './authoritative-lineage-drill.jsx';
import {AuthoritativeWorkspaceHeader,AuthoritativeWorkspaceView} from './authoritative-workbench-view.jsx';
import {StateBlock} from './ui.jsx';

const empty={phase:'LOADING',data:null,error:null};
export function AuthoritativeBillPaymentsWorkspace({config,access=null,fetcher=globalThis.fetch,onBack=()=>{},workspaceTitle='Bill Payments',workspaceDescription='Review persisted vendor payments for the selected company and accounting period.',backLabel='Back to bills'}){
  const [state,setState]=useState(empty),[cursors,setCursors]=useState([null]),[refresh,setRefresh]=useState(0),[detail,setDetail]=useState(null),[busy,setBusy]=useState(false),[detailError,setDetailError]=useState(null);
  const buttons=useRef(new Map()),returnId=useRef(null),wasDetail=useRef(false);
  const cursor=cursors.at(-1);
  useEffect(()=>{let active=true;setState(empty);void readBillPaymentRegister({config,afterId:cursor,fetcher}).then(result=>{if(active)setState(result.ok?{phase:'READY',data:result.data,error:null}:{phase:'ERROR',data:null,error:result.message});});return()=>{active=false;};},[config?.baseUrl,config?.entityId,config?.periodId,cursor,refresh,fetcher]);
  useEffect(()=>{if(wasDetail.current&&!detail)buttons.current.get(returnId.current)?.focus();wasDetail.current=!!detail;},[detail]);
  const openJournal=async row=>{if(busy)return;setBusy(true);setDetailError(null);returnId.current=row.payment_occurrence_id;try{const result=await readBillPaymentJournal({config,row,fetcher});if(result.ok)setDetail(result.journal);else setDetailError(result.message);}finally{setBusy(false);}};
  if(detail)return <AuthoritativeLineageDrill config={config} fetcher={fetcher} initial={{kind:'JOURNAL',journal:detail,context:{entityId:config.entityId,periodId:config.periodId,journalId:detail.journal_entry_id,journalRevision:detail.revision,journalCurrency:detail.currency}}} onExit={()=>setDetail(null)}/>;
  const canReadJournal=access?.entity_id===config?.entityId&&access?.session_refresh_required===false&&access?.permissions?.includes('GL.JE.VIEW');
  return <AuthoritativeWorkspaceView className="authoritative-bill-payments-workspace">
    <AuthoritativeWorkspaceHeader eyebrow="Expenses" title={workspaceTitle} description={workspaceDescription} status="Read-only register"/>
    <div className="filter-bar"><button type="button" className="btn" onClick={onBack}>{backLabel}</button><span>{config?.scopePresentation?.entityLabel||'Selected company'} · {config?.scopePresentation?.periodLabel||'Selected period'}</span><button type="button" className="btn" disabled={state.phase==='LOADING'} onClick={()=>{setCursors([null]);setRefresh(value=>value+1);}}>Refresh</button></div>
    {state.phase==='LOADING'?<StateBlock tone="loading" title={`Loading ${workspaceTitle}`}>Reading retained payment, Bill, Journal, ledger, bank-match, and audit references.</StateBlock>:null}
    {state.phase==='ERROR'?<StateBlock tone="error" title={`Could not load ${workspaceTitle}`}>{state.error}<button type="button" className="btn" onClick={()=>setRefresh(value=>value+1)}>Try again</button></StateBlock>:null}
    {detailError?<p role="alert">{detailError}</p>:null}
    {state.phase==='READY'?<><div className="table-wrap" role="region" tabIndex={0} aria-label="Bill Payment register; scroll horizontally to view all fields"><table className="tbl"><thead><tr><th>Payment reference</th><th>Date</th><th>Vendor</th><th>Bill</th><th>Amount</th><th>Bank account</th><th>Bank</th><th>Status</th><th>Journal</th><th>Bank match</th></tr></thead><tbody>{state.data.rows.map(row=><tr key={row.payment_occurrence_id}><td title={`Payment ID: ${row.payment_occurrence_id}`}>{row.journal_number||row.payment_occurrence_id}</td><td>{row.accounting_date}</td><td title={`Vendor: ${row.vendor_ref}`}>{row.vendor_name}</td><td title={`Bill ID: ${row.business_document_id}`}>{row.bill_number}</td><td>{row.amount} {row.currency}</td><td>{row.cash_account_code}</td><td>{row.bank_member_ref}</td><td>{row.payment_status.replaceAll('_',' ')}</td><td>{row.journal_entry_id?<button type="button" className="btn btn-sm btn-ghost" disabled={busy||!canReadJournal} ref={element=>{if(element)buttons.current.set(row.payment_occurrence_id,element);else buttons.current.delete(row.payment_occurrence_id);}} onClick={()=>openJournal(row)}>View {row.journal_status.replaceAll('_',' ')}</button>:'Unavailable'}</td><td>{row.bank_match_id?<span title={`Journal line ${row.journal_line_id}; ledger line ${row.ledger_line_id}`}>Matched · {row.bank_match_id}</span>:'Not matched'}</td></tr>)}</tbody></table></div>
      {!state.data.rows.length?<StateBlock tone="empty" title="No Bill Payments on this page">No retained AP payment occurrence was returned for this company and period.</StateBlock>:null}
      <div className="filter-bar" aria-label="Bill Payment pages"><button type="button" className="btn" disabled={cursors.length===1} onClick={()=>setCursors(value=>value.slice(0,-1))}>Previous</button><span>Page {cursors.length} · {state.data.rows.length} payments</span><button type="button" className="btn" disabled={!state.data.next_id} onClick={()=>setCursors(value=>[...value,state.data.next_id])}>Next</button></div>
      <details><summary>Exact evidence references</summary><p>Each row retains the payment occurrence, Bill, payment reference, bank-controlled Journal line, active bank match, ledger line, and lifecycle audit IDs that exist in PostgreSQL. Missing links remain visibly unavailable.</p>{state.data.rows.map(row=><dl className="fixed-assets-detail-grid" key={row.payment_occurrence_id}>{[['Payment ID',row.payment_occurrence_id],['Bill ID',row.business_document_id],['Source document',row.source_document_id||'—'],['Journal ID',row.journal_entry_id||'—'],['Payment reference',row.journal_number||'—'],['Cash account',row.cash_account_code||'—'],['Bank member',row.bank_member_ref||'—'],['Journal line ID',row.journal_line_id||'—'],['Ledger line ID',row.ledger_line_id||'—'],['Draft audit event',row.draft_audit_event_id||'—'],['Posted audit event',row.posted_audit_event_id||'—']].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>)}</details>
    </>:null}
  </AuthoritativeWorkspaceView>;
}
