import React,{useEffect,useState} from 'react';
import {refreshAuthoritativeAiAmortizationCoverageEvidence,refreshAuthoritativeAiAmortizationSchedules} from './accounting-api.js';
import {AuthoritativeWorkspaceHeader,AuthoritativeWorkspaceView} from './authoritative-workbench-view.jsx';
import {StateBlock} from './ui.jsx';

const idle={phase:'LOADING',rows:[],error:null};
const money=(value,currency)=>{const number=Number(value);return Number.isFinite(number)?new Intl.NumberFormat('en-US',{style:'currency',currency}).format(number):String(value||'');};

export function AuthoritativeAmortizationWorkspace({config,fetcher=globalThis.fetch}){
  const [coverage,setCoverage]=useState(idle),[schedules,setSchedules]=useState(idle);
  const load=async()=>{setCoverage(current=>({...current,phase:'LOADING',error:null}));setSchedules(current=>({...current,phase:'LOADING',error:null}));const [evidence,plans]=await Promise.all([refreshAuthoritativeAiAmortizationCoverageEvidence({config,fetcher}),refreshAuthoritativeAiAmortizationSchedules({config,fetcher})]);setCoverage(evidence.ok?{phase:'READY',rows:evidence.rows,error:null}:{phase:'BLOCKED',rows:[],error:evidence});setSchedules(plans.ok?{phase:'READY',rows:plans.rows,error:null}:{phase:'BLOCKED',rows:[],error:plans});};
  useEffect(()=>{void load();},[config?.entityId]);
  const loading=coverage.phase==='LOADING'||schedules.phase==='LOADING';
  return <AuthoritativeWorkspaceView area="Amortization Center">
    <AuthoritativeWorkspaceHeader eyebrow="AUTHORITATIVE - AI ACCOUNTING" title="Amortization Center" description="Server-retained prepaid coverage evidence and deterministic monthly schedules. Every proposed schedule remains a human-controlled accounting proposal." status="REVIEW REQUIRED"/>
    <section className="report-workbench" aria-label="Authoritative amortization evidence">
      <div className="report-workbench-head"><div><b>Prepaid coverage and amortization plans</b><div className="page-subtitle">This workspace reads only authoritative evidence for the configured entity. It never computes schedules in the browser or substitutes demonstration data.</div></div><button type="button" className="btn" disabled={loading} onClick={load}>{loading?'Refreshing evidence...':'Refresh evidence'}</button></div>
      <div className="report-shelf" aria-label="Amortization authority boundary"><span className="report-shelf-chip report-shelf-chip-on">RETAINED SOURCE EVIDENCE</span><span className="report-shelf-chip">WHOLE-MONTH COVERAGE</span><span className="report-shelf-chip">HUMAN DRAFT REQUIRED</span><span className="report-shelf-chip">NO AUTO POST</span></div>
      {coverage.phase==='LOADING'&&<StateBlock tone="loading" title="Loading authoritative prepaid coverage evidence">Reading retained source documents for the configured entity.</StateBlock>}
      {coverage.phase==='BLOCKED'&&<StateBlock tone="blocked" title={coverage.error?.code||'AI_AMORTIZATION_COVERAGE_EVIDENCE_BLOCKED'}>{coverage.error?.message} No browser-stored, substitute, or demonstration evidence is shown.</StateBlock>}
      {coverage.phase==='READY'&&coverage.rows.length===0&&<StateBlock tone="empty" title="No retained prepaid coverage evidence">No authoritative whole-month coverage evidence was returned. This does not prove that no prepaid or insurance obligation exists.</StateBlock>}
      {coverage.phase==='READY'&&coverage.rows.length>0&&<section className="card" aria-label="Retained prepaid coverage evidence"><div className="card-head"><div><h2>Coverage evidence</h2><p className="muted sm">Coverage dates, immutable source hash, and extraction method are retained before a proposal can exist.</p></div><span className="badge badge-muted">EVIDENCE ONLY</span></div><div className="table-wrap" role="region" tabIndex={0} aria-label="Prepaid coverage evidence; scroll horizontally to view every column"><table className="tbl"><thead><tr><th>Coverage period</th><th>Source document</th><th>Evidence method</th><th>Audit trace</th><th>Authority</th></tr></thead><tbody>{coverage.rows.map(row=><tr key={row.ai_amortization_coverage_evidence_id}><td><b>{row.coverage_start}</b><div className="muted sm">to {row.coverage_end}</div></td><td>{row.source_document_id}<div className="muted sm">v{row.source_document_version}</div></td><td>{row.extraction_method.replaceAll('_',' ')}</td><td><details><summary>Immutable hashes</summary><div className="muted sm">Source: {row.source_payload_hash}<br/>Evidence: {row.evidence_hash}<br/>Coverage: {row.coverage_hash}</div></details></td><td><span className="badge badge-muted">NO DRAFT OR POST</span></td></tr>)}</tbody></table></div></section>}
      {schedules.phase==='LOADING'&&<StateBlock tone="loading" title="Loading authoritative amortization plans">Reading server-proposed schedules and their monthly lines.</StateBlock>}
      {schedules.phase==='BLOCKED'&&<StateBlock tone="blocked" title={schedules.error?.code||'AI_AMORTIZATION_SCHEDULE_BLOCKED'}>{schedules.error?.message} No browser-stored, substitute, or demonstration schedule is shown.</StateBlock>}
      {schedules.phase==='READY'&&schedules.rows.length===0&&<StateBlock tone="empty" title="No proposed amortization schedules">No human-controlled amortization proposal was returned for this entity. Coverage evidence alone never creates a journal.</StateBlock>}
      {schedules.phase==='READY'&&schedules.rows.length>0&&<section className="card" aria-label="Proposed amortization schedules"><div className="card-head"><div><h2>Proposed monthly schedules</h2><p className="muted sm">A proposal needs separate human decision and standard Draft workflow; it cannot review, approve, or post itself.</p></div><span className="badge badge-warning">HUMAN DRAFT REQUIRED</span></div><div className="table-wrap" role="region" tabIndex={0} aria-label="Proposed amortization schedules; scroll horizontally to view every column"><table className="tbl"><thead><tr><th>Coverage</th><th>Amount and accounts</th><th>Member trace</th><th>Monthly schedule</th><th>Authority</th></tr></thead><tbody>{schedules.rows.map(row=><tr key={row.ai_amortization_schedule_id}><td><b>{row.coverage_start}</b><div className="muted sm">to {row.coverage_end} / {row.rule_id}</div></td><td><b>{money(row.original_amount,row.currency)}</b><div className="muted sm">{row.prepaid_account_code} to {row.expense_account_code}</div></td><td>{row.member_trace.allocation_basis}<div className="muted sm">Project: {row.member_trace.project_ref||'ENTITY ONLY'}<br/>Property: {row.member_trace.property_ref||'ENTITY ONLY'}</div></td><td><details><summary>{row.schedule_lines.length} proposed monthly lines</summary><ul className="muted sm">{row.schedule_lines.map(line=><li key={line.line_no}>{line.amortization_month}: {money(line.amount,row.currency)}</li>)}</ul></details></td><td><span className="badge badge-muted">NO REVIEW OR POST</span><div className="muted sm">Separate human Draft only</div></td></tr>)}</tbody></table></div></section>}
    </section>
  </AuthoritativeWorkspaceView>;
}
