import React,{useCallback,useEffect,useRef,useState} from 'react';
import {refreshAuthoritativeAiPropertyRentRevenueReviews} from './accounting-api.js';
import {AuthoritativeWorkspaceHeader,AuthoritativeWorkspaceView} from './authoritative-workbench-view.jsx';
import {StateBlock} from './ui.jsx';

const initial={phase:'LOADING',rows:[],error:null};
const pretty=value=>value?.replaceAll('_',' ')||'—';
const money=(value,currency)=>`${currency} ${value}`;
const sumMoney4=rows=>{let total=0n;for(const row of rows){const match=/^(-?)([0-9]+)(?:\.([0-9]{1,4}))?$/.exec(row.variance_amount);if(!match)continue;const amount=BigInt(match[2])*10000n+BigInt((match[3]||'').padEnd(4,'0'));total+=match[1]? -amount:amount;}const sign=total<0n?'-':'',magnitude=total<0n?-total:total;return `${sign}${magnitude/10000n}.${String(magnitude%10000n).padStart(4,'0')}`;};
const shortHash=value=>value?`${value.slice(0,22)}…`:'—';

export function AuthoritativeRevenueRecognitionWorkspace({config,fetcher=globalThis.fetch}){
  const[state,setState]=useState(initial),[detail,setDetail]=useState(null),[reload,setReload]=useState(0),back=useRef(null);
  const load=useCallback(async()=>refreshAuthoritativeAiPropertyRentRevenueReviews({config,limit:500,fetcher}),[config?.baseUrl,config?.entityId,config?.periodId,fetcher]);
  useEffect(()=>{let active=true;setState(initial);setDetail(null);void load().then(result=>{if(active)setState(result.ok?{phase:'READY',rows:result.rows,error:null}:{phase:'ERROR',rows:[],error:`${result.code}: ${result.message}`});});return()=>{active=false;};},[load,reload]);
  if(detail)return <AuthoritativeWorkspaceView area="Revenue recognition" className="authoritative-revenue-recognition-detail"><AuthoritativeWorkspaceHeader eyebrow="Accounting operations" title={detail.property_ref||'Entity-level rent'} description="Immutable Property Rent revenue and period-cutoff exception evidence." status={pretty(detail.review_status)}/><div className="page-actions"><button type="button" className="btn btn-ghost" onClick={()=>{setDetail(null);queueMicrotask(()=>back.current?.focus());}}>Back to Revenue recognition</button></div><div className="authoritative-kpi-grid"><article><span>Expected rent</span><strong>{money(detail.expected_rent_amount,detail.currency)}</strong></article><article><span>Posted revenue</span><strong>{money(detail.posted_revenue_amount,detail.currency)}</strong></article><article><span>Variance</span><strong>{money(detail.variance_amount,detail.currency)}</strong></article><article><span>Risk</span><strong>{detail.risk_level}</strong></article></div><div className="table-wrap" role="region" tabIndex={0} aria-label="Revenue recognition exception evidence"><table className="tbl"><tbody><tr><th>Recognition date</th><td>{detail.accounting_date}</td></tr><tr><th>Property / unit</th><td>{detail.property_ref||'Entity-level'}<small>{detail.unit_ref||'No unit retained'}</small></td></tr><tr><th>Lease / tenant</th><td>{detail.lease_ref||'No lease retained'}<small>{detail.tenant_ref||'No tenant retained'}</small></td></tr><tr><th>Control finding</th><td>{detail.reason}<small>{detail.suggested_action}</small></td></tr><tr><th>Source document</th><td>{detail.source_document_id}<small>source version {detail.source_version}</small></td></tr><tr><th>Posted Journal</th><td>{detail.journal_entry_id||'No Posted Journal retained for this period'}</td></tr><tr><th>Source hashes</th><td>{detail.receipt_hash}<small>{detail.source_evidence_hash}</small></td></tr><tr><th>Approved mapping</th><td>{detail.mapping_snapshot_id}<small>{detail.mapping_snapshot_hash}</small></td></tr><tr><th>Rule</th><td>{detail.rule_id}<small>Observed {new Date(detail.created_at).toLocaleString()}</small></td></tr></tbody></table></div><StateBlock>Accounting actions are disabled. Resolve the source, mapping, or Journal evidence in its authorized workspace.</StateBlock></AuthoritativeWorkspaceView>;
  const totalVariance=sumMoney4(state.rows),currency=state.rows.length&&new Set(state.rows.map(row=>row.currency)).size===1?state.rows[0].currency:null;
  return <AuthoritativeWorkspaceView area="Revenue recognition" className="authoritative-revenue-recognition-workspace"><AuthoritativeWorkspaceHeader eyebrow="Accounting operations" title="Revenue recognition" description="Review period-scoped Property Rent revenue against approved mappings and source-linked Posted ledger evidence." status="Read-only exception review"/>{state.phase==='LOADING'?<StateBlock tone="loading">Loading Revenue recognition controls...</StateBlock>:state.phase==='ERROR'?<StateBlock tone="danger" title="Revenue recognition evidence is unavailable">{state.error}<div className="page-actions"><button type="button" className="btn btn-ghost" onClick={()=>setReload(value=>value+1)}>Retry read</button></div></StateBlock>:state.rows.length===0?<StateBlock>No Property Rent revenue or cutoff exceptions were returned for this company and period. This result does not assert that the source population is complete.</StateBlock>:<><div className="authoritative-kpi-grid"><article><span>Exceptions</span><strong>{state.rows.length}</strong></article><article><span>Posted mismatches</span><strong>{state.rows.filter(row=>row.review_status==='POSTED_REVENUE_MISMATCH').length}</strong></article><article><span>Cutoff reviews</span><strong>{state.rows.filter(row=>row.review_status==='UNPOSTED_RENT_CUTOFF_REVIEW').length}</strong></article><article><span>Net variance</span><strong>{currency?money(totalVariance,currency):'Multiple currencies'}</strong></article></div><div className="table-wrap" role="region" tabIndex={0} aria-label="Revenue recognition exceptions"><table className="tbl"><thead><tr><th>Property / recognition date</th><th>Expected rent</th><th>Posted revenue</th><th>Variance</th><th>Status</th><th>Evidence</th></tr></thead><tbody>{state.rows.map(row=><tr key={row.wbs_property_rent_source_admission_id}><td><button type="button" className="link-button" onClick={event=>{back.current=event.currentTarget;setDetail(row);}}>{row.property_ref||'Entity-level rent'}</button><small>{row.accounting_date} · {row.unit_ref||'No unit retained'}</small></td><td>{money(row.expected_rent_amount,row.currency)}</td><td>{money(row.posted_revenue_amount,row.currency)}</td><td>{money(row.variance_amount,row.currency)}</td><td>{pretty(row.review_status)}</td><td>{row.journal_entry_id?'Posted Journal linked':'Cutoff review'}<small>{shortHash(row.source_evidence_hash)}</small></td></tr>)}</tbody></table></div></>}</AuthoritativeWorkspaceView>;
}
