// REFS seed data (demo). All figures are illustrative prototype data, not actuals.

export const COA = [
  ['110100','Petty Cash','ASSET','DEBIT'],
  ['111000','Operating Cash','ASSET','DEBIT'],
  ['112000','Escrow Cash','ASSET','DEBIT'],
  ['112001','Escrow - Other Reserves','ASSET','DEBIT'],
  ['112002','Escrow - Real Estate Tax Reserve','ASSET','DEBIT'],
  ['112003','Escrow - Insurance Reserve','ASSET','DEBIT'],
  ['112004','Escrow - Capital Expenditure Reserves','ASSET','DEBIT'],
  ['113000','Reserve Fund Cash','ASSET','DEBIT'],
  ['114001','Charles Schwab Investment Account','ASSET','DEBIT'],
  ['115000','Cash Clearing','ASSET','DEBIT'],
  ['123700','A/R Management Fees','ASSET','DEBIT'],
  ['123830','A/R Employee Receivable','ASSET','DEBIT'],
  ['125000','Due from Related Party','ASSET','DEBIT'],
  ['125001','A/R - Other','ASSET','DEBIT'],
  ['125002','Accrued Receivable Income','ASSET','DEBIT'],
  ['140100','Prepaid Insurance','ASSET','DEBIT'],
  ['140300','Prepaid HOA','ASSET','DEBIT'],
  ['140400','Prepaid Property Tax','ASSET','DEBIT'],
  ['140600','Prepaid Other','ASSET','DEBIT'],
  ['158001','Investment in Subsidiary','ASSET','DEBIT'],
  ['159002','Notes Receivable','ASSET','DEBIT'],
  ['159022','Interest Receivable','ASSET','DEBIT'],
  ['161000','Inventory - Land','ASSET','DEBIT'],
  ['161201','Loan Closing Costs','ASSET','DEBIT'],
  ['162000','Land Improvements','ASSET','DEBIT'],
  ['163000','Inventory - Buildings','ASSET','DEBIT'],
  ['164100','CWIP - Land','ASSET','DEBIT'],
  ['164400','CWIP - Land Improvements','ASSET','DEBIT'],
  ['165901','FA - Investment Homes','ASSET','DEBIT'],
  ['185000','Deposit - Earnest Money','ASSET','DEBIT'],
  ['185100','Deposit - Construction Loan','ASSET','DEBIT'],
  ['220200','Accounts Payable (WBS)','LIABILITY','CREDIT'],
  ['220300','A/P Accrual','LIABILITY','CREDIT'],
  ['220450','A/P Accrual - Insurance','LIABILITY','CREDIT'],
  ['220451','A/P Accrual - Interest','LIABILITY','CREDIT'],
  ['225000','Security Deposit (WBS)','LIABILITY','CREDIT'],
  ['227303','Note Payable','LIABILITY','CREDIT'],
  ['260200','Mortgage Loan - Short Term','LIABILITY','CREDIT'],
  ['270200','Mortgage Loan - Long Term','LIABILITY','CREDIT'],
  ['270700','Other Long Term Loan','LIABILITY','CREDIT'],
  ['270800','Loan Costs','LIABILITY','CREDIT'],
  ['291000','Due to/from','LIABILITY','CREDIT'],
  ['370300','Current Year Surplus (Deficit)','EQUITY','CREDIT'],
  ['372000','Retained Earnings (WBS)','EQUITY','CREDIT'],
  ['380101','Paid in Capital - Common','EQUITY','CREDIT'],
  ['380104','Additional Paid in Capital','EQUITY','CREDIT'],
  ['380499','Owner Contribution','EQUITY','CREDIT'],
  ['420500','Gross Potential Rent','REVENUE','CREDIT'],
  ['421500','Loss/Gain to Lease','REVENUE','CREDIT'],
  ['421803','Rental Income (WBS)','REVENUE','CREDIT'],
  ['431000','Less: Vacancy','REVENUE','CREDIT'],
  ['432000','Less: Concessions','REVENUE','CREDIT'],
  ['442310','MUD Reimbursement','REVENUE','CREDIT'],
  ['449200','Interest Income (WBS)','REVENUE','CREDIT'],
  ['460300','Pet Rent','REVENUE','CREDIT'],
  ['460400','Application Fees','REVENUE','CREDIT'],
  ['480000','Late Fee (WBS)','REVENUE','CREDIT'],
  ['490100','Sales Proceeds','REVENUE','CREDIT'],
  ['490600','Outsourcing Service Income','REVENUE','CREDIT'],
  ['491800','Sales of Product Income','REVENUE','CREDIT'],
  ['510000','Cost of Goods Sold','EXPENSE','DEBIT'],
  ['510100','Sales Commission','EXPENSE','DEBIT'],
  ['608000','Landscape Contract','EXPENSE','DEBIT'],
  ['612500','R&M - HVAC Repairs','EXPENSE','DEBIT'],
  ['612900','R&M - Miscellaneous Repairs','EXPENSE','DEBIT'],
  ['613900','R&M - Roof','EXPENSE','DEBIT'],
  ['623000','Turn - Painting','EXPENSE','DEBIT'],
  ['625000','Contract - Pest Control','EXPENSE','DEBIT'],
  ['632000','Property Insurance','EXPENSE','DEBIT'],
  ['635000','Property Tax (WBS)','EXPENSE','DEBIT'],
  ['641200','Elec - Resident Units','EXPENSE','DEBIT'],
  ['643000','Water and Sewer','EXPENSE','DEBIT'],
  ['651000','Bank Fees (WBS)','EXPENSE','DEBIT'],
  ['681000','HOA Fees','EXPENSE','DEBIT'],
  ['682000','Management Fees','EXPENSE','DEBIT'],
  ['700100','Professional & Legal Fees','EXPENSE','DEBIT'],
  ['700405','Travel','EXPENSE','DEBIT'],
  ['700600','Salaries & Wages','EXPENSE','DEBIT'],
  ['220204','Tax Payable','LIABILITY','CREDIT'],
  ['700800','Payroll Fees','EXPENSE','DEBIT'],
  ['704600','Employee Recruiting','EXPENSE','DEBIT'],
  ['632015','Insurance - Workers Comp','EXPENSE','DEBIT'],
  ['700150','Consulting Fees','EXPENSE','DEBIT'],
  ['701600','Google Ads','EXPENSE','DEBIT'],
  ['705000','Software (Expense)','EXPENSE','DEBIT'],
  ['780120','CAP - Carpet/Vinyl/Tile','EXPENSE','DEBIT'],
  ['792000','Asset Management Fees','EXPENSE','DEBIT'],
  ['795000','Interest Expense (WBS)','EXPENSE','DEBIT'],
  ['291001','Due to/from Affiliates (WBS)','LIABILITY','CREDIT'],
  ['705001','Research & Development Service (WBS)','EXPENSE','DEBIT'],
  ['705002','Outsourcing Service (WBS)','EXPENSE','DEBIT'],
  ['111000','Cash - Operating','ASSET','DEBIT'],
  ['112000','Restricted Cash - Escrow','ASSET','DEBIT'],
  ['113000','Restricted Cash - Reserve','ASSET','DEBIT'],
  ['120200','AR - Tenant','ASSET','DEBIT'],
  ['164200','Construction in Progress (CIP)','ASSET','DEBIT'],
  ['164500','Capitalized Interest','ASSET','DEBIT'],
  ['161000','Land','ASSET','DEBIT'],
  ['163000','Building','ASSET','DEBIT'],
  ['220200','Accounts Payable','LIABILITY','CREDIT'],
  ['220410','Interest Payable','LIABILITY','CREDIT'],
  ['225000','Security Deposit Liability','LIABILITY','CREDIT'],
  ['270100','Construction Loan Payable','LIABILITY','CREDIT'],
  ['380104','Members Equity - Contribution','EQUITY','CREDIT'],
  ['421803','Rental Income - Base Rent','REVENUE','CREDIT'],
  ['482300','Other Income','REVENUE','CREDIT'],
  ['795000','Interest Expense','EXPENSE','DEBIT'],
  ['682000','Property Management Fee','EXPENSE','DEBIT'],
  ['612900','Repair & Maintenance','EXPENSE','DEBIT'],
  ['641600','Utilities','EXPENSE','DEBIT'],
  ['795000','Insurance Expense','EXPENSE','DEBIT'],
  ['142000','Suspense','ASSET','DEBIT'],
].map(([code,name,type,nb])=>({account_code:code,account_name:name,account_type:type,normal_balance:nb})).filter((a,i,arr)=>arr.findIndex(x=>x.account_code===a.account_code)===i);

export const ENTITIES = [
  {entity_id:1, entity_code:'WBGR', entity_name:'Wan Bridge Group LLC', entity_type:'ProjectCo'},
  {entity_id:2, entity_code:'WBLD', entity_name:'Wan Bridge Land LLC', entity_type:'LandCo'},
  {entity_id:3, entity_code:'WBDE', entity_name:'Wan Bridge Development LLC', entity_type:'ProjectCo'},
  {entity_id:4, entity_code:'WBHO', entity_name:'WB Home LLC', entity_type:'ProjectCo'},
  {entity_id:5, entity_code:'WBCR', entity_name:'WB Conroe LLC', entity_type:'ProjectCo'},
  {entity_id:6, entity_code:'WBGE', entity_name:'WB Georgetown LLC', entity_type:'ProjectCo'},
  {entity_id:7, entity_code:'WBBM', entity_name:'WB Balmoral LLC', entity_type:'ProjectCo'},
  {entity_id:8, entity_code:'WBWH', entity_name:'WB Waxahachie Home Building LLC', entity_type:'Vertical'},
  {entity_id:9, entity_code:'WBDH', entity_name:'WB Denton Home Building LLC', entity_type:'Vertical'},
  {entity_id:10, entity_code:'WBEE', entity_name:'WBWT West End Estates LLC', entity_type:'ProjectCo'},
  {entity_id:11, entity_code:'WBPL', entity_name:'WB Pradera Oaks Land 1 LLC', entity_type:'LandCo'},
  {entity_id:12, entity_code:'WBRO', entity_name:'WB Red Oaks Home Building LLC', entity_type:'Vertical'},
  {entity_id:13, entity_code:'WBIB', entity_name:'WB Ivy District Home Building LLC', entity_type:'Vertical'},
  {entity_id:14, entity_code:'WBCW', entity_name:'WB Crowley Home Building LLC', entity_type:'Vertical'},
  {entity_id:15, entity_code:'WBAI', entity_name:'AIWB INC', entity_type:'Corporate'},
  {entity_id:16, entity_code:'WBTD', entity_name:'TF Portfolio Delaware LLC', entity_type:'ProjectCo'},
  {entity_id:17, entity_code:'WBTS', entity_name:'WAN BRIDGE TEXAS SERVICE LLC', entity_type:'ProjectCo'},
  {entity_id:18, entity_code:'WBL8', entity_name:'WB Lago Mar POD 8 Land LLC', entity_type:'LandCo'},
  {entity_id:19, entity_code:'WBSC', entity_name:'WBWT Sandy Cove LLC', entity_type:'ProjectCo'},
  {entity_id:20, entity_code:'WBSV', entity_name:'WBWT Sandy Cove II LLC', entity_type:'ProjectCo'},
  {entity_id:21, entity_code:'WBTP', entity_name:'Tilegend Partners LLC', entity_type:'ProjectCo'},
  {entity_id:22, entity_code:'WBC3', entity_name:'WB Churchill III LLC', entity_type:'ProjectCo'},
  {entity_id:23, entity_code:'WBFP', entity_name:'WB TF Portfolio Locust LLC', entity_type:'ProjectCo'},
  {entity_id:24, entity_code:'WBC4', entity_name:'WB Conroe 40 LP', entity_type:'Fund'},
  {entity_id:25, entity_code:'WBS5', entity_name:'WB Investment Sub Fund IV LP', entity_type:'Fund'},
  {entity_id:26, entity_code:'WBS1', entity_name:'WB San Marcos 1 Home Building LLC', entity_type:'Vertical'},
  {entity_id:27, entity_code:'WBP8', entity_name:'WB POD 8 Home Building LLC', entity_type:'Vertical'},
  {entity_id:28, entity_code:'WBGA', entity_name:'WB Galveston LLC', entity_type:'ProjectCo'},
  {entity_id:29, entity_code:'WBLO', entity_name:'WB Longhorn LLC', entity_type:'ProjectCo'},
  {entity_id:30, entity_code:'WBB7', entity_name:'WBWT Balmoral Section 27 LLC', entity_type:'ProjectCo'},
  {entity_id:31, entity_code:'WBTO', entity_name:'WB TF Portfolio LLC', entity_type:'ProjectCo'},
  {entity_id:32, entity_code:'FDF4', entity_name:'WB Investment Fund IV LLC', entity_type:'Fund'},
  {entity_id:33, entity_code:'WBPM', entity_name:'WBPT Management LLC', entity_type:'ServiceCo'},
  {entity_id:34, entity_code:'WBCA', entity_name:'Wan Pacific Capital Management LLC', entity_type:'ServiceCo'},
  {entity_id:35, entity_code:'WBOF', entity_name:'WB Opportunity Fund III LP', entity_type:'Fund'},
  {entity_id:36, entity_code:'TPAU', entity_name:'WBWT Audra I LLC', entity_type:'ProjectCo'},
  {entity_id:37, entity_code:'WBIN', entity_name:'Wan Bridge Investment LLC', entity_type:'ProjectCo'},
  {entity_id:38, entity_code:'WBT2', entity_name:'TF Texas 002 LLC', entity_type:'ProjectCo'},
  {entity_id:39, entity_code:'WBC5', entity_name:'WB CH I LLC', entity_type:'ProjectCo'},
  {entity_id:40, entity_code:'WBIV', entity_name:'WB Ivy District LLC', entity_type:'ProjectCo'},
  {entity_id:41, entity_code:'WBIF', entity_name:'Wan Bridge Sub Fund LP', entity_type:'Fund'},
  {entity_id:42, entity_code:'WBPH', entity_name:'WB Pradera Oaks 2 and 3 Holding LLC', entity_type:'ProjectCo'},
  {entity_id:43, entity_code:'FDF2', entity_name:'WB Investment Fund II LP', entity_type:'Fund'},
  {entity_id:44, entity_code:'WBP2', entity_name:'WB Pradera Oaks 200 LP', entity_type:'Fund'},
  {entity_id:45, entity_code:'WBC6', entity_name:'WB CH II LLC', entity_type:'ProjectCo'},
  {entity_id:46, entity_code:'WBO2', entity_name:'WB Opportunity Fund II LP', entity_type:'Fund'},
  {entity_id:47, entity_code:'WBWL', entity_name:'WB Waxahachie Land LLC', entity_type:'LandCo'},
  {entity_id:48, entity_code:'WBVI', entity_name:'WB Investment Texas VI INC', entity_type:'Corporate'},
  {entity_id:49, entity_code:'WBLL', entity_name:'WB Lago Vista Land LLC', entity_type:'LandCo'},
  {entity_id:50, entity_code:'WBSO', entity_name:'WB Sage One Inc', entity_type:'Corporate'},
  {entity_id:51, entity_code:'WBBT', entity_name:'Wan BT Fund Management LLC', entity_type:'Fund'},
  {entity_id:52, entity_code:'WBD2', entity_name:'WB Denton Phase II LP', entity_type:'Fund'},
  {entity_id:53, entity_code:'WBPW', entity_name:'WB Parkway Eldridge Home Building LLC', entity_type:'Vertical'},
  {entity_id:54, entity_code:'WBSM', entity_name:'WB San Marcos SH123 Land LLC', entity_type:'LandCo'},
  {entity_id:55, entity_code:'WBR2', entity_name:'WBWT Rayzor Ranch II LLC', entity_type:'ProjectCo'},
  {entity_id:56, entity_code:'WBIL', entity_name:'Wan Bridge Investment Fund LP', entity_type:'Fund'},
  {entity_id:57, entity_code:'WBS3', entity_name:'WB Sage Investment Three Inc', entity_type:'Corporate'},
  {entity_id:58, entity_code:'WBJL', entity_name:'WB Joshua Land LLC', entity_type:'LandCo'},
  {entity_id:59, entity_code:'WBDP', entity_name:'WB Denton Land LP', entity_type:'Fund'},
  {entity_id:60, entity_code:'WBFU', entity_name:'Wan Bridge Foundation', entity_type:'ProjectCo'},
  {entity_id:61, entity_code:'WBCH', entity_name:'WB Churchill II LLC', entity_type:'ProjectCo'},
  {entity_id:62, entity_code:'WBFL', entity_name:'WB Forney Land LLC', entity_type:'LandCo'},
  {entity_id:63, entity_code:'WBWK', entity_name:'WB W Klein Land LLC', entity_type:'LandCo'},
  {entity_id:64, entity_code:'WBWA', entity_name:'WB West Alvin Land LLC', entity_type:'LandCo'},
  {entity_id:65, entity_code:'WBWR', entity_name:'WBWT Rayzor Ranch LLC', entity_type:'ProjectCo'},
  {entity_id:66, entity_code:'WBCM', entity_name:'Wan Pacific II Capital Management LLC', entity_type:'ServiceCo'},
  {entity_id:67, entity_code:'FD2B', entity_name:'Wan Bridge Fund 2B DE LLC', entity_type:'Fund'},
  {entity_id:68, entity_code:'WBA2', entity_name:'WBWT Audra II LLC', entity_type:'ProjectCo'},
  {entity_id:69, entity_code:'WBL2', entity_name:'WB Lago Mar Pod 12 LLC', entity_type:'ProjectCo'},
  {entity_id:70, entity_code:'WBMC', entity_name:'WBWT Mason Creek LLC', entity_type:'ProjectCo'},
  {entity_id:71, entity_code:'WBT1', entity_name:'TF Texas 001 LLC', entity_type:'ProjectCo'},
  {entity_id:72, entity_code:'WBO6', entity_name:'WB Opportunity Sub Fund 6 LP', entity_type:'Fund'},
  {entity_id:73, entity_code:'FDFO', entity_name:'WB Magnolia LLC', entity_type:'ProjectCo'},
  {entity_id:74, entity_code:'WBSE', entity_name:'WB Seagoville Land LLC', entity_type:'LandCo'},
  {entity_id:75, entity_code:'WBWI', entity_name:'WBWT Investment LLC', entity_type:'ProjectCo'},
  {entity_id:76, entity_code:'WBF4', entity_name:'WB Investment Fund IV LP', entity_type:'Fund'},
  {entity_id:77, entity_code:'WBNF', entity_name:'Nanafu Texas Investment Inc', entity_type:'Corporate'},
  {entity_id:78, entity_code:'WBLF', entity_name:'WBWT LS Fronterra LLC', entity_type:'ProjectCo'},
  {entity_id:79, entity_code:'WBST', entity_name:'WB Sage Two INC', entity_type:'Corporate'},
  {entity_id:80, entity_code:'WBS2', entity_name:'WB Sage Investment Two Inc', entity_type:'Corporate'},
  {entity_id:81, entity_code:'WBIT', entity_name:'WB Investment Fund IV Holding LLC', entity_type:'Fund'},
  {entity_id:82, entity_code:'WB2P', entity_name:'WB Conroe 2P DE LLC', entity_type:'ProjectCo'},
  {entity_id:83, entity_code:'WB16', entity_name:'WB Red Oak 116B DE LLC', entity_type:'ProjectCo'},
  {entity_id:84, entity_code:'WBCL', entity_name:'WB Crowley Land LLC', entity_type:'LandCo'},
  {entity_id:85, entity_code:'WBPR', entity_name:'WB Pearland LLC', entity_type:'ProjectCo'},
  {entity_id:86, entity_code:'WB27', entity_name:'WB Balmoral 27 LLC', entity_type:'ProjectCo'},
  {entity_id:87, entity_code:'WBPP', entity_name:'WB Primera Red Oaks LP', entity_type:'Fund'},
  {entity_id:88, entity_code:'WBWD', entity_name:'W Land Development Management LLC', entity_type:'LandCo'},
  {entity_id:89, entity_code:'WBVC', entity_name:'WB VCH I LLC', entity_type:'ProjectCo'},
  {entity_id:90, entity_code:'WBRT', entity_name:'WB Red Oak Phase II LLC', entity_type:'ProjectCo'},
  {entity_id:91, entity_code:'WBB5', entity_name:'WB Bastrop 5 Home Building LLC', entity_type:'Vertical'},
  {entity_id:92, entity_code:'WBHM', entity_name:'WB HMH Lago Mar Pod 12 LLC', entity_type:'ProjectCo'},
  {entity_id:93, entity_code:'WBP1', entity_name:'WB PC Phase I Home Building LLC', entity_type:'Vertical'},
  {entity_id:94, entity_code:'WBB1', entity_name:'WB Bastrop 1 Home Building LLC', entity_type:'Vertical'},
  {entity_id:95, entity_code:'WBPU', entity_name:'WB Plum Creek Home Building LLC', entity_type:'Vertical'},
  {entity_id:96, entity_code:'WBB8', entity_name:'WBWT Balmoral Section 28 LLC', entity_type:'ProjectCo'},
  {entity_id:97, entity_code:'WBSA', entity_name:'WB Sage Investment One INC', entity_type:'Corporate'},
  {entity_id:98, entity_code:'WBBN', entity_name:'WB Brooklyn Village LLC', entity_type:'ProjectCo'},
  {entity_id:99, entity_code:'WBOV', entity_name:'WB Opportunity Fund V LP', entity_type:'Fund'},
  {entity_id:100, entity_code:'FDCM', entity_name:'WB Cayman LP', entity_type:'Fund'},
  {entity_id:101, entity_code:'WBAE', entity_name:'WBWT Aurora Square Estates LLC', entity_type:'ProjectCo'},
  {entity_id:102, entity_code:'WBF1', entity_name:'Wan Bridge Fund 115 DE LLC', entity_type:'Fund'},
  {entity_id:103, entity_code:'FD1B', entity_name:'Wan Bridge Fund 1B DE LLC', entity_type:'Fund'},
  {entity_id:104, entity_code:'WBPS', entity_name:'WB Magnolia 1774 LLC', entity_type:'ProjectCo'},
  {entity_id:105, entity_code:'WBP6', entity_name:'WB Pradera Oaks 6 LP', entity_type:'Fund'},
  {entity_id:106, entity_code:'WBTC', entity_name:'WB Texas Consulting LLC', entity_type:'ServiceCo'},
  {entity_id:107, entity_code:'WBCP', entity_name:'WB CONROE PH 2 LLC', entity_type:'ProjectCo'},
  {entity_id:108, entity_code:'WBCV', entity_name:'WB Sandy Cove at Lago Mar Home Building LLC', entity_type:'Vertical'},
  {entity_id:109, entity_code:'WBCY', entity_name:'WB Opportunity Fund VI Cayman L.P.', entity_type:'Fund'},
  {entity_id:110, entity_code:'WB13', entity_name:'WB BV 139 Delaware LLC', entity_type:'ProjectCo'},
  {entity_id:111, entity_code:'WBPI', entity_name:'WB PC Phase I LLC', entity_type:'ProjectCo'},
  {entity_id:112, entity_code:'FDF6', entity_name:'WB Opportunity fund 6 LP', entity_type:'Fund'},
  {entity_id:113, entity_code:'WB2B', entity_name:'WB Conroe 2B DE LLC', entity_type:'ProjectCo'},
  {entity_id:114, entity_code:'WBPA', entity_name:'Wan Pacific Real Estate Development LLC', entity_type:'ProjectCo'},
  {entity_id:115, entity_code:'WBP4', entity_name:'WB Pradera Oaks 4 and 5 LP', entity_type:'Fund'},
  {entity_id:116, entity_code:'WBYF', entity_name:'Yanfu Management LLC', entity_type:'ServiceCo'},
  {entity_id:117, entity_code:'WBBL', entity_name:'WB Bastrop Land LLC', entity_type:'LandCo'},
  {entity_id:118, entity_code:'WBRL', entity_name:'WB Red Oaks Land LLC', entity_type:'LandCo'},
  {entity_id:119, entity_code:'WBON', entity_name:'WB Opportunity II Holding LLC', entity_type:'ProjectCo'},
];

export const PERIODS = [
  {period_id:1, entity_id:2, period_code:'2026-06', status:'CLOSED'},
  {period_id:2, entity_id:2, period_code:'2026-07', status:'OPEN'},
  {period_id:3, entity_id:4, period_code:'2026-07', status:'OPEN'},
];

export const PROJECTS = [
  {project_id:1, project_code:'PRJ-001', project_name:'Cedar Ridge Phase I', entity_id:2, project_status:'ACTIVE', construction_status:'UNDER_CONSTRUCTION'},
  {project_id:2, project_code:'PRJ-002', project_name:'Maple Court', entity_id:4, project_status:'ACTIVE', construction_status:'IN_SERVICE'},
];

export const PROPERTIES = [
  {property_id:1, property_code:'P0012', property_name:'Cedar Ridge Bldg A', entity_id:2, project_id:1, property_status:'UNDER_DEVELOPMENT', operation_status:null},
  {property_id:2, property_code:'P0020', property_name:'Maple Court', entity_id:4, project_id:2, property_status:'IN_SERVICE', operation_status:'STABILIZED'},
];

export const LOANS = [
  {loan_id:1, loan_code:'L-2025-014', loan_type:'CONSTRUCTION', entity_id:2, project_id:1, lender_name:'First National Bank',
   commitment_amount:12000000, original_principal:12000000, current_principal:4250000,
   interest_rate:0.0825, maturity_date:'2027-12-31', borrowing_base:8500000},
  {loan_id:2, loan_code:'M-2024-003', loan_type:'MORTGAGE', entity_id:4, project_id:2, lender_name:'Pacific Mortgage',
   commitment_amount:6000000, original_principal:6000000, current_principal:5720000,
   interest_rate:0.0615, maturity_date:'2034-05-01', borrowing_base:6000000},
];

export const BANK_ACCOUNTS = [
  {bank_account_id:1, bank_account_code:'BA-001', entity_id:2, bank_name:'First National Bank', account_type:'OPERATING', gl_account_code:'111000', cash_scope:'Operating'},
  {bank_account_id:2, bank_account_code:'BA-003', entity_id:4, bank_name:'Pacific Bank', account_type:'OPERATING', gl_account_code:'111000', cash_scope:'Operating'},
  {bank_account_id:3, bank_account_code:'BA-ESC', entity_id:2, bank_name:'First National Bank', account_type:'ESCROW', gl_account_code:'111000', cash_scope:'Escrow'},
];

export const VENDORS = [
  {vendor_id:1, vendor_code:'V-100', vendor_name:'Summit General Contractors', is_1099:false, is_related_party:false},
  {vendor_id:2, vendor_code:'V-101', vendor_name:'BluePeak Utilities', is_1099:false, is_related_party:false},
  {vendor_id:3, vendor_code:'V-102', vendor_name:'WanBridge Property Mgmt (RP)', is_1099:false, is_related_party:true},
];

export const CUSTOMERS = [
  {customer_id:1, customer_code:'C-200', customer_name:'Tenant - Unit A-203', customer_type:'TENANT', is_related_party:false},
  {customer_id:2, customer_code:'C-201', customer_name:'WanBridge OpCo (Owner)', customer_type:'OWNER', is_related_party:true},
];

// PM Charge Code -> Owner GL mapping (versioned)
export const MAPPINGS = [
  {mapping_id:1, mapping_type:'PM', source_code:'RENT', owner_gl_account_code:'421803', rev_exp_flag:'REVENUE', cash_accrual_flag:'ACCRUAL', is_current:true},
  {mapping_id:2, mapping_type:'PM', source_code:'LATE_FEE', owner_gl_account_code:'482300', rev_exp_flag:'REVENUE', cash_accrual_flag:'CASH', is_current:true},
  {mapping_id:3, mapping_type:'PM', source_code:'SEC_DEPOSIT', owner_gl_account_code:'225000', rev_exp_flag:'LIABILITY', cash_accrual_flag:'CASH', is_current:true},
  {mapping_id:4, mapping_type:'PM', source_code:'UTILITIES', owner_gl_account_code:'641600', rev_exp_flag:'EXPENSE', cash_accrual_flag:'ACCRUAL', is_current:true},
  {mapping_id:5, mapping_type:'PM', source_code:'MGMT_FEE', owner_gl_account_code:'682000', rev_exp_flag:'EXPENSE', cash_accrual_flag:'ACCRUAL', is_current:true},
  // NOTE: 'PET_FEE' intentionally UNMAPPED to demonstrate GL_MAPPING_MISSING exception
];

export const USERS = [
  {user_id:'ricky', name:'Ricky (Controller)', role_code:'CONTROLLER'},
  {user_id:'sam', name:'Sam (Staff Accountant)', role_code:'STAFF_ACCT'},
  {user_id:'pat', name:'Pat (Project Accountant)', role_code:'PROJECT_ACCT'},
  {user_id:'lee', name:'Lee (Auditor)', role_code:'AUDITOR'},
];
