import { useState } from 'react';
import { Btn, Money, Field } from './ui.jsx';
import { money } from './engine.js';
import { ENTITIES } from './data.js';
import { buildUnitTransferPair } from './unit-transfer-pairing.js';

const EVIDENCE=['Deed / Title','WBS transfer record','Accounting memo','A-B agreement','Cutoff settlement','Cost export','Loan draw package','Lender consent','Tax / legal memo'];
export function UnitTransfer({ctx}) {
 const {jes,actions,toast,can}=ctx; const [fromId,setFromId]=useState(5);const [toId,setToId]=useState(9);const [unit,setUnit]=useState('');const [price,setPrice]=useState('');const [ev,setEv]=useState({});const [result,setResult]=useState(null);
 const unitsOf=eid=>{const m={};jes.filter(j=>j.posting_status==='POSTED'&&j.entity_id===eid).forEach(j=>j.lines.forEach(l=>{if(l.unit_code&&['164100','164200','164400','164500'].includes(l.account_code))m[l.unit_code]=(m[l.unit_code]||0)+(l.debit_amount||0)-(l.credit_amount||0);}));return m;}; const A=ENTITIES.find(e=>e.entity_id===+fromId),B=ENTITIES.find(e=>e.entity_id===+toId),unitsA=unitsOf(+fromId),carrying=unit?+(unitsA[unit]||0).toFixed(2):0,p=+price||carrying,gain=+(p-carrying).toFixed(2),evDone=EVIDENCE.filter(e=>ev[e]).length,missing=EVIDENCE.filter(e=>!ev[e]);
 // Both journals are built before either is created. A pair that would not
 // mirror is never posted as a half transfer.
 const doTransfer=()=>{if(evDone<4){toast(`Evidence is incomplete (${evDone}/9). Select Deed, WBS, Memo, and Agreement at minimum.`,'bad');return;}const built=buildUnitTransferPair({from:A,to:B,unit,carrying,price});if(!built.ok){toast(built.message,'bad');return;}actions.newJEFromRule(built.out);actions.newJEFromRule(built.in);setResult({pair:built.pair_id,carrying:built.carrying,p:built.price,gain:built.gain,missing});toast(`Paired draft journals created: ${built.pair_id}. They enter the approval workflow.`);};
 return <div className="full-bleed"><h2 className="page-h">Unit Transfer Accounting</h2><div className="filter-bar"><Field label="From"><select value={fromId} onChange={e=>{setFromId(e.target.value);setUnit('');}}>{ENTITIES.filter(e=>['Vertical','ProjectCo','LandCo'].includes(e.entity_type)).map(e=><option key={e.entity_id} value={e.entity_id}>{e.entity_code} {e.entity_name}</option>)}</select></Field><Field label="To"><select value={toId} onChange={e=>setToId(e.target.value)}>{ENTITIES.filter(e=>e.entity_id!==+fromId).map(e=><option key={e.entity_id} value={e.entity_id}>{e.entity_code} {e.entity_name}</option>)}</select></Field><Field label="Unit"><select value={unit} onChange={e=>setUnit(e.target.value)}><option value="">Select</option>{Object.keys(unitsA).map(u=><option key={u}>{u}</option>)}</select></Field><Field label="Transfer Price"><input type="number" value={price} placeholder={carrying||''} onChange={e=>setPrice(e.target.value)}/></Field></div><section className="qbo-card"><h4>Cost bridge and paired-journal preview</h4><p>A carrying cost: {money(carrying)}. Transfer price: {money(p)}. Gain or loss: {money(gain)}.</p><p className="muted sm">Entity A records Due from B, releases the unit at its carrying cost and recognises its gain or loss. Entity B records Due to A and capitalises the unit at the price it paid. Due from and Due to are equal, in the same period, on the symmetric account pair, so the balance eliminates on consolidation. The intercompany margin stays in B's inventory on B's own books and is removed at group level by the consolidation, never by an entry in either company's ledger. Both entries require normal approval.</p></section><section className="qbo-card"><h4>Evidence checklist ({evDone}/9)</h4>{EVIDENCE.map(e=><label key={e} style={{display:'flex',gap:8,margin:'3px 0'}}><input type="checkbox" checked={!!ev[e]} onChange={x=>setEv(s=>({...s,[e]:x.target.checked}))}/>{e}</label>)}</section><Btn variant="primary" onClick={doTransfer} disabled={!can('GL.JE.CREATE')} title={can('GL.JE.CREATE') ? 'Create the paired Draft journal entries' : 'Your role does not hold GL.JE.CREATE'}>Create paired draft journals</Btn>{evDone<9&&<span className="muted sm" style={{marginLeft:12}}>Evidence missing: {missing.slice(0,3).join(', ')}{missing.length>3?` and ${missing.length-3} more`:''}</span>}{result&&<section className="src-card" style={{marginTop:14}}><b>Pair {result.pair}</b><p>Cost bridge: {money(result.carrying)} to {money(result.p)}. Gain or loss: {money(result.gain)}. Missing evidence: {result.missing.length}.</p></section>}</div>;
}
