import { useState } from 'react';
import { Btn, Money, Field } from './ui.jsx';
import { money } from './engine.js';
import { ENTITIES } from './data.js';

const EVIDENCE=['Deed / Title','WBS transfer record','Accounting memo','A-B agreement','Cutoff settlement','Cost export','Loan draw package','Lender consent','Tax / legal memo'];
export function UnitTransfer({ctx}) {
 const {jes,actions,toast,can}=ctx; const [fromId,setFromId]=useState(5);const [toId,setToId]=useState(9);const [unit,setUnit]=useState('');const [price,setPrice]=useState('');const [ev,setEv]=useState({});const [result,setResult]=useState(null);
 const unitsOf=eid=>{const m={};jes.filter(j=>j.posting_status==='POSTED'&&j.entity_id===eid).forEach(j=>j.lines.forEach(l=>{if(l.unit_code&&['164100','164200','164400','164500'].includes(l.account_code))m[l.unit_code]=(m[l.unit_code]||0)+(l.debit_amount||0)-(l.credit_amount||0);}));return m;}; const A=ENTITIES.find(e=>e.entity_id===+fromId),B=ENTITIES.find(e=>e.entity_id===+toId),unitsA=unitsOf(+fromId),carrying=unit?+(unitsA[unit]||0).toFixed(2):0,p=+price||carrying,gain=+(p-carrying).toFixed(2),evDone=EVIDENCE.filter(e=>ev[e]).length,missing=EVIDENCE.filter(e=>!ev[e]);
 const doTransfer=()=>{if(!unit){toast('Select a unit first.','bad');return;}if(carrying<=0){toast('The selected unit has no carrying cost.','bad');return;}if(evDone<4){toast(`Evidence is incomplete (${evDone}/9). Select Deed, WBS, Memo, and Agreement at minimum.`,'bad');return;}const pair='UT-'+Date.now().toString().slice(-6);const aLines=[{account_code:'125000',debit_amount:p,credit_amount:0,member:B.entity_name,description:'Due from_'+B.entity_name,unit_code:unit},{account_code:'164400',debit_amount:0,credit_amount:carrying,unit_code:unit}];if(gain>0.005)aLines.push({account_code:'787001',debit_amount:0,credit_amount:gain,description:'Gain on transfer',unit_code:unit});if(gain<-0.005)aLines.push({account_code:'787001',debit_amount:-gain,credit_amount:0,description:'Loss on transfer',unit_code:unit});actions.newJEFromRule({entity_id:A.entity_id,source_system:'INTERNAL',payee:B.entity_name,je_type:'AUTO',rule_code:'R-UT-OUT-01',description:`Unit Transfer OUT ${unit} to ${B.entity_code} [${pair}]`,lines:aLines});actions.newJEFromRule({entity_id:B.entity_id,source_system:'INTERNAL',payee:A.entity_name,je_type:'AUTO',rule_code:'R-UT-IN-01',description:`Unit Transfer IN ${unit} from ${A.entity_code} [${pair}]`,lines:[{account_code:'164400',debit_amount:p,credit_amount:0,unit_code:unit},{account_code:'291000',debit_amount:0,credit_amount:p,member:A.entity_name,description:'Due to/from_'+A.entity_name,unit_code:unit}]});setResult({pair,carrying,p,gain,missing});toast(`Paired draft journals created: ${pair}. They enter the approval workflow.`);};
 return <div className="full-bleed"><h2 className="page-h">Unit Transfer Accounting</h2><div className="filter-bar"><Field label="From"><select value={fromId} onChange={e=>{setFromId(e.target.value);setUnit('');}}>{ENTITIES.filter(e=>['Vertical','ProjectCo','LandCo'].includes(e.entity_type)).map(e=><option key={e.entity_id} value={e.entity_id}>{e.entity_code} {e.entity_name}</option>)}</select></Field><Field label="To"><select value={toId} onChange={e=>setToId(e.target.value)}>{ENTITIES.filter(e=>e.entity_id!==+fromId).map(e=><option key={e.entity_id} value={e.entity_id}>{e.entity_code} {e.entity_name}</option>)}</select></Field><Field label="Unit"><select value={unit} onChange={e=>setUnit(e.target.value)}><option value="">Select</option>{Object.keys(unitsA).map(u=><option key={u}>{u}</option>)}</select></Field><Field label="Transfer Price"><input type="number" value={price} placeholder={carrying||''} onChange={e=>setPrice(e.target.value)}/></Field></div><section className="qbo-card"><h4>Cost bridge and paired-journal preview</h4><p>A carrying cost: {money(carrying)}. Transfer price: {money(p)}. Gain or loss: {money(gain)}.</p><p className="muted sm">Entity A records Due from B and removes CWIP. Entity B records opening CWIP and Due to A. Both entries require normal approval.</p></section><section className="qbo-card"><h4>Evidence checklist ({evDone}/9)</h4>{EVIDENCE.map(e=><label key={e} style={{display:'flex',gap:8,margin:'3px 0'}}><input type="checkbox" checked={!!ev[e]} onChange={x=>setEv(s=>({...s,[e]:x.target.checked}))}/>{e}</label>)}</section><Btn variant="primary" onClick={doTransfer} disabled={!can('GL.JE.CREATE')}>Create paired draft journals</Btn>{evDone<9&&<span className="muted sm" style={{marginLeft:12}}>Evidence missing: {missing.slice(0,3).join(', ')}{missing.length>3?` and ${missing.length-3} more`:''}</span>}{result&&<section className="src-card" style={{marginTop:14}}><b>Pair {result.pair}</b><p>Cost bridge: {money(result.carrying)} to {money(result.p)}. Gain or loss: {money(result.gain)}. Missing evidence: {result.missing.length}.</p></section>}</div>;
}
