import { useState } from 'react';
import { KPI, Btn, Badge, Money, Table, Tabs } from './ui.jsx';
import { money } from './engine.js';
import { aiJudge } from './ai.js';
import { ENTITIES } from './data.js';
import { repo } from './repo.js';

const SEED_STAGING = [
 {id:'STG-001',category:'Bank Transaction',source_system:'BANK',source_id:'BANKTXN-Z-4471',entity_id:4,date:'2026-07-30',amount:1250,direction:'CREDIT',description:'ACH UNKNOWN TENANT',payee:'',cost_code:'',status:'',mapping:'MISSING',stage:'Pending Mapping'},
 {id:'STG-002',category:'Construction Loan',detail:'Draw',source_system:'WBS_CL',source_id:'DRAW-2026-0801',entity_id:5,date:'2026-08-01',amount:250000,description:'Draw Request 8 - Cedar Ridge',payee:'First National Bank',cost_code:'',status:'UNDER_CONSTRUCTION',mapping:'OK',stage:'Pending Coding'},
 {id:'STG-003',category:'FAST Cost',source_system:'FAST',source_id:'FAST-88412',entity_id:5,date:'2026-07-29',amount:18400,description:'Framing labor - Lot 103 Block B',payee:'Summit General Contractors',cost_code:'2HD220',status:'UNDER_CONSTRUCTION',mapping:'OK',stage:'Pending Coding'},
 {id:'STG-004',category:'FAST Cost',source_system:'FAST',source_id:'FAST-88413',entity_id:5,date:'2026-07-29',amount:6200,description:'Punch-out - Lot 101 Block A (completed unit)',payee:'Summit General Contractors',cost_code:'2HD850',status:'COMPLETED',mapping:'OK',stage:'Pending Coding'},
 {id:'STG-005',category:'Faster PO',source_system:'FASTER_PO',source_id:'FPO-2026-3321',entity_id:15,date:'2026-07-28',amount:4300,description:'Marketing services Q3',payee:'Wan Bridge Land LLC',cost_code:'24E060',status:'',mapping:'OK',stage:'Pending Review'},
 {id:'STG-006',category:'Property Operation',source_system:'PM',source_id:'YARDI-5585',entity_id:11,date:'2026-07-31',amount:120,description:'PET_FEE - Unit C-050',payee:'',cost_code:'',status:'',mapping:'MISSING',stage:'Pending Mapping'},
];
export function StagingCenter({ctx}) {
 const {actions,toast,entity}=ctx; const [rows,setRows]=useState(()=>repo.load('staging',SEED_STAGING)); const [tab,setTab]=useState('All'); const [aiRow,setAiRow]=useState(null);
 const save=r=>{setRows(r);repo.save('staging',r);}; const enOf=id=>ENTITIES.find(e=>e.entity_id===id)||ENTITIES[0];
 const judge=r=>aiJudge({category:r.category,detail:r.detail||r.description,direction:r.direction,amount:r.amount,description:r.description,payee:r.payee,cost_code:r.cost_code,status:r.status},enOf(r.entity_id));
 const stages=['All','Pending Mapping','Pending Coding','Pending Review','Ready to Post','Posted','Exception','AI Decision Log']; const list=rows.filter(r=>(tab==='All'||r.stage===tab)&&(!entity||r.entity_id===entity)); const tone=s=>({'Pending Mapping':'bad','Pending Coding':'warn','Pending Review':'warn','Ready to Post':'ok','Posted':'muted','Exception':'bad'}[s]||'muted');
 const advance=r=>{if(r.stage==='Pending Mapping'){toast('GL mapping is missing. Configure it in Mapping Center.','bad');actions.ensureException({exception_type:'GL_MAPPING_MISSING',severity:'HIGH',object_type:'STAGING',object_ref:r.source_id,entity_id:r.entity_id,owner:'PROPERTY_ACCT',root_cause:'No matching controlled setting'});return;}const j=judge(r);if(r.stage==='Pending Coding'){save(rows.map(x=>x.id===r.id?{...x,stage:'Pending Review',ai:j}:x));toast(`AI recommendation: Dr ${j.suggested.dr} / Cr ${j.suggested.cr}`);return;}if(r.stage==='Pending Review'){save(rows.map(x=>x.id===r.id?{...x,stage:'Ready to Post',ai:j}:x));toast('Human review approved. Ready to create a draft journal.');return;}if(r.stage==='Ready to Post'){const id=actions.newJEFromRule({entity_id:r.entity_id,source_system:r.source_system,payee:r.payee||null,description:`${r.description} [${r.source_id}]`,rule_code:j.rule_used,je_type:'AUTO',lines:[{account_code:j.suggested.dr,debit_amount:r.amount,credit_amount:0,member:j.suggested.dr.startsWith('291')?r.payee:undefined,cost_code:r.cost_code||undefined},{account_code:j.suggested.cr,debit_amount:0,credit_amount:r.amount,member:j.suggested.cr.startsWith('291')?(r.payee||'Wan Bridge Development LLC'):undefined}]});save(rows.map(x=>x.id===r.id?{...x,stage:'Posted',je_id:id}:x));toast(`Draft journal created. Source: ${r.source_id}`);}};
 const labels={'Pending Mapping':'Map accounts','Pending Coding':'AI recommendation','Pending Review':'Approve review','Ready to Post':'Create draft journal','Posted':'Posted','Exception':'Resolve'};
 return <div className="full-bleed"><h2 className="page-h">Accounting Staging Center</h2><div className="filter-bar"><span className="muted sm">Source - Classification - Company Setting - AI recommendation - Human Review - Draft Journal - Approval - General Ledger. Steps cannot be skipped.</span></div><div className="kpi-row"><KPI label="Pending mapping" value={rows.filter(r=>r.stage==='Pending Mapping').length} tone="bad"/><KPI label="Pending coding or review" value={rows.filter(r=>/Coding|Review/.test(r.stage)).length} tone="warn"/><KPI label="Ready for draft" value={rows.filter(r=>r.stage==='Ready to Post').length} tone="ok"/><KPI label="Posted" value={rows.filter(r=>r.stage==='Posted').length}/></div><Tabs tabs={stages} active={tab} onChange={setTab}/>{tab==='AI Decision Log'?<Table exportName="ai-decision-log" rows={repo.load('ai_log',[])} empty="No AI decision records." cols={[{h:'Time',k:'ts'},{h:'Model',k:'model'},{h:'Prompt version',k:'prompt_version'},{h:'Input',render:r=><span className="muted sm">{r.input_summary} - {r.input_digest}</span>},{h:'Entity',k:'entity'},{h:'Suggested',render:r=>r.suggested?`Dr ${r.suggested.dr} / Cr ${r.suggested.cr}`:'None'},{h:'Human decision',render:r=>r.human_decision||'Recommendation pending review'}]}/>:<Table rowKey="id" pageSize={20} exportName="staging" onRow={r=>setAiRow(r)} rows={list} empty="No source data is waiting in this stage." cols={[{h:'Source ID',k:'source_id'},{h:'Category',render:r=><Badge tone="muted">{r.category}</Badge>},{h:'Entity',render:r=>enOf(r.entity_id).entity_code},{h:'Date',k:'date'},{h:'Description',k:'description'},{h:'Cost code',render:r=>r.cost_code||'None'},{h:'Amount',num:true,render:r=><Money v={r.amount}/>},{h:'Mapping',render:r=><Badge tone={r.mapping==='OK'?'ok':'bad'}>{r.mapping}</Badge>},{h:'Stage',render:r=><Badge tone={tone(r.stage)}>{r.stage}</Badge>},{h:'Action',render:r=>r.stage==='Posted'?<span className="muted sm">Journal created</span>:<Btn size="sm" variant={r.stage==='Ready to Post'?'primary':'default'} onClick={e=>{e.stopPropagation();advance(r);}}>{labels[r.stage]}</Btn>}]}/>} {aiRow&&(()=>{const j=judge(aiRow);return <section className="src-card" style={{marginTop:14}}><div className="src-grid"><span><i>Suggested journal</i><b>Dr {j.suggested.dr} {j.suggested.dr_name} - Cr {j.suggested.cr} {j.suggested.cr_name}</b></span><span><i>Confidence</i><b>{(j.confidence*100).toFixed(0)}%</b></span><span><i>Rule</i><b>{j.rule_used}</b></span><span><i>Risk</i><b>{j.risk}</b></span><span><i>Human review</i><b>{j.need_human?'Required':'Not required'}</b></span><span><i>Amount</i><b>{money(aiRow.amount)}</b></span></div><p className="muted sm">Reason: {j.reason} - Evidence: {j.evidence.slice(0,70)} - AI only recommends; a human must approve a draft journal.</p></section>})()}</div>;
}
