import test from 'node:test';import assert from 'node:assert/strict';import {generateKeyPairSync} from 'node:crypto';import {createAccountingHttpServer} from '../api/accounting-http.mjs';import {accountingServerConfig} from '../runtime/start-accounting-server.mjs';import {createProductionAccountingServer} from '../runtime/accounting-server.mjs';
const {publicKey}=generateKeyPairSync('ed25519');const publicKeyPem=publicKey.export({type:'spki',format:'pem'}),wbsSnapshotPublicKeys=JSON.stringify({'it-wbs-2026-08':publicKeyPem}),wbsProviderSignedTrust=JSON.stringify({issuer:'wbs-provider',key_id:'it-wbs-2026-08',public_key:publicKeyPem});
const readyPool={query:async sql=>String(sql).includes('to_regprocedure')?{rowCount:1,rows:[{ready:true}]}:{rowCount:1}};
const base={NODE_ENV:'production',RENDER_GIT_COMMIT:'abcdef1234567890abcdef1234567890abcdef12',DATABASE_URL:'postgresql://runtime_user:RuntimeLongSecret99@db.example:5432/refs?sslmode=require',MIGRATION_DATABASE_URL:'postgresql://migration_user:MigrationLongSecret99@db.example:5432/refs?sslmode=require',CONTEXT_ISSUER_DATABASE_URL:'postgresql://issuer_user:IssuerLongSecret99@db.example:5432/refs?sslmode=require',GRANT_SYNC_DATABASE_URL:'postgresql://grant_user:GrantLongSecret99@db.example:5432/refs?sslmode=require',OIDC_ISSUER:'https://iam.example',OIDC_AUDIENCE:'refs-accounting',OIDC_JWKS_URI:'https://iam.example/.well-known/jwks.json',REFS_HTTP_ALLOWED_ORIGINS:'https://app.example',REFS_ATTACHMENT_MODE:'REQUIRED',REFS_WBS_INGEST_MODE:'REQUIRED',REFS_WBS_EVIDENCE_RETENTION_DAYS:'365',S3_ENDPOINT:'https://s3.example',S3_BUCKET:'refs',S3_REGION:'us-east-1',S3_ACCESS_KEY_ID:'key',S3_SECRET_ACCESS_KEY:'secret',VIRUS_SCANNER_ENDPOINT:'https://scan.example',VIRUS_SCANNER_TOKEN:'token',VIRUS_SCANNER_CA_PEM:'-----BEGIN CERTIFICATE-----\nTEST\n-----END CERTIFICATE-----',VIRUS_SCANNER_SERVER_NAME:'scanner.internal',ATTACHMENT_SCANNER_ACTOR_ID:'scanner-service',WBS_SNAPSHOT_ED25519_PUBLIC_KEYS:wbsSnapshotPublicKeys,WBS_PROVIDER_SIGNED_TRUST:wbsProviderSignedTrust,WBS_PROVIDER_SIGNED_SERVICE_ACTOR_ID:'oidc|wbs-provider-admission-service'};
test('production startup requires OIDC, attachment dependencies, signed WBS trust and isolated TLS database identities',()=>{const config=accountingServerConfig(base);assert.equal(config.port,8080);assert.equal(config.runtimePoolMax,4);assert.equal(config.issuerPoolMax,2);assert.equal(config.database.requirePostgres,true);assert.equal(config.controlledDemoEnabled,false);assert.throws(()=>accountingServerConfig({...base,REFS_CONTROLLED_DEMO_MODE:'ENABLED'}),/permanently disabled/);assert.deepEqual(Object.keys(config.wbsSnapshotPublicKeys),['it-wbs-2026-08']);assert.equal(config.wbsProviderSignedTrust.issuer,'wbs-provider');for(const key of ['OIDC_ISSUER','OIDC_AUDIENCE','OIDC_JWKS_URI'])assert.throws(()=>accountingServerConfig({...base,[key]:''}),/OIDC_/);for(const key of ['S3_ENDPOINT','S3_BUCKET','S3_REGION','S3_ACCESS_KEY_ID','S3_SECRET_ACCESS_KEY','VIRUS_SCANNER_ENDPOINT','VIRUS_SCANNER_TOKEN','VIRUS_SCANNER_SERVER_NAME','ATTACHMENT_SCANNER_ACTOR_ID','WBS_SNAPSHOT_ED25519_PUBLIC_KEYS','WBS_PROVIDER_SIGNED_TRUST','WBS_PROVIDER_SIGNED_SERVICE_ACTOR_ID'])assert.throws(()=>accountingServerConfig({...base,[key]:''}),new RegExp(key));assert.throws(()=>accountingServerConfig({...base,VIRUS_SCANNER_CA_PEM:''}),/VIRUS_SCANNER_CA_PEM or VIRUS_SCANNER_CA_FILE/);assert.throws(()=>accountingServerConfig({...base,VIRUS_SCANNER_CA_PEM:'invalid'}),/must contain a PEM certificate/);assert.equal(accountingServerConfig({...base,VIRUS_SCANNER_CA_PEM:undefined,VIRUS_SCANNER_CA_FILE:'/run/secrets/scanner-ca.pem'}).scanner.caFile,'/run/secrets/scanner-ca.pem');assert.throws(()=>accountingServerConfig({...base,WBS_SNAPSHOT_ED25519_PUBLIC_KEYS:'not-json'}),/must be JSON/);assert.throws(()=>accountingServerConfig({...base,WBS_PROVIDER_SIGNED_TRUST:'not-json'}),/must be JSON/);});
test('production startup rejects unsafe port, body limit and pool budgets',()=>{assert.throws(()=>accountingServerConfig({...base,PORT:'0'}),/PORT/);assert.throws(()=>accountingServerConfig({...base,REFS_HTTP_MAX_BODY_BYTES:'999'}),/MAX_BODY/);assert.throws(()=>accountingServerConfig({...base,REFS_PG_RUNTIME_POOL_MAX:'0'}),/RUNTIME_POOL/);assert.throws(()=>accountingServerConfig({...base,REFS_PG_ISSUER_POOL_MAX:'11'}),/ISSUER_POOL/);const tuned=accountingServerConfig({...base,REFS_PG_RUNTIME_POOL_MAX:'3',REFS_PG_ISSUER_POOL_MAX:'1'});assert.equal(tuned.runtimePoolMax,3);assert.equal(tuned.issuerPoolMax,1);});
test('production startup refuses an API deployment without an explicit browser origin',()=>{assert.throws(()=>accountingServerConfig({...base,REFS_HTTP_ALLOWED_ORIGINS:''}),/REFS_HTTP_ALLOWED_ORIGINS/);});
test('production startup refuses an unversioned, shortened or malformed API release',()=>{for(const value of ['',undefined,'release-1','abcdef','1234567abcdef'])assert.throws(()=>accountingServerConfig({...base,RENDER_GIT_COMMIT:value,GITHUB_SHA:undefined}),/RENDER_GIT_COMMIT or GITHUB_SHA/);const githubSha='1234567890abcdef1234567890abcdef12345678';assert.equal(accountingServerConfig({...base,RENDER_GIT_COMMIT:undefined,GITHUB_SHA:githubSha}).releaseSha,githubSha);});
test('production CORS allowlist accepts only explicit HTTPS origins',()=>{assert.deepEqual(accountingServerConfig({...base,REFS_HTTP_ALLOWED_ORIGINS:'https://app.example,https://staging.example'}).allowedOrigins,['https://app.example','https://staging.example']);for(const origin of ['*','http://app.example','https://app.example/path','not-an-origin'])assert.throws(()=>accountingServerConfig({...base,REFS_HTTP_ALLOWED_ORIGINS:origin}),/REFS_HTTP_ALLOWED_ORIGINS/);});
test('Stage 1 can explicitly disable later integrations without weakening core PostgreSQL and OIDC requirements',()=>{
  const stage1={...base,REFS_ATTACHMENT_MODE:'DISABLED',REFS_WBS_INGEST_MODE:'DISABLED'};
  for(const key of ['S3_ENDPOINT','S3_BUCKET','S3_REGION','S3_ACCESS_KEY_ID','S3_SECRET_ACCESS_KEY','VIRUS_SCANNER_ENDPOINT','VIRUS_SCANNER_TOKEN','VIRUS_SCANNER_CA_PEM','VIRUS_SCANNER_CA_FILE','VIRUS_SCANNER_SERVER_NAME','ATTACHMENT_SCANNER_ACTOR_ID','WBS_SNAPSHOT_ED25519_PUBLIC_KEYS','WBS_PROVIDER_SIGNED_TRUST','WBS_PROVIDER_SIGNED_SERVICE_ACTOR_ID','REFS_WBS_EVIDENCE_RETENTION_DAYS'])delete stage1[key];
  const config=accountingServerConfig(stage1);assert.equal(config.attachmentMode,'DISABLED');assert.equal(config.wbsIngestMode,'DISABLED');assert.equal(config.s3,null);assert.equal(config.scanner,null);assert.equal(config.wbsSnapshotPublicKeys,null);
  for(const key of ['DATABASE_URL','CONTEXT_ISSUER_DATABASE_URL','OIDC_ISSUER','OIDC_AUDIENCE','OIDC_JWKS_URI'])assert.throws(()=>accountingServerConfig({...stage1,[key]:''}));
  for(const [key,value] of [['REFS_ATTACHMENT_MODE','OPTIONAL'],['REFS_WBS_INGEST_MODE','AUTO']])assert.throws(()=>accountingServerConfig({...stage1,[key]:value}),/REQUIRED or DISABLED/);
});
test('internal-test startup is explicit, fixed-identity only, and rejects external integrations',()=>{
  const internal={...base,NODE_ENV:'test',REFS_DEPLOYMENT_ENV:'internal-test',REFS_INTERNAL_TEST_MODE:'ENABLED',REFS_INTERNAL_TEST_TENANT_ID:'11111111-1111-4111-8111-111111111111',REFS_INTERNAL_TEST_ACTOR_ID:'internal-test-operator',REFS_ATTACHMENT_MODE:'DISABLED',REFS_WBS_INGEST_MODE:'DISABLED'};
  for(const key of ['OIDC_ISSUER','OIDC_AUDIENCE','OIDC_JWKS_URI','S3_ENDPOINT','S3_BUCKET','S3_REGION','S3_ACCESS_KEY_ID','S3_SECRET_ACCESS_KEY','VIRUS_SCANNER_ENDPOINT','VIRUS_SCANNER_TOKEN','VIRUS_SCANNER_CA_PEM','VIRUS_SCANNER_SERVER_NAME','ATTACHMENT_SCANNER_ACTOR_ID','WBS_SNAPSHOT_ED25519_PUBLIC_KEYS','WBS_PROVIDER_SIGNED_TRUST','WBS_PROVIDER_SIGNED_SERVICE_ACTOR_ID'])delete internal[key];
  const config=accountingServerConfig(internal);assert.deepEqual(config.internalTest,{tenantId:internal.REFS_INTERNAL_TEST_TENANT_ID,actorId:internal.REFS_INTERNAL_TEST_ACTOR_ID,allowWbsLivePilot:false});
  const livePilot=accountingServerConfig({...internal,REFS_WBS_LIVE_PILOT_MODE:'ENABLED',WBS_CF_ACCESS_CLIENT_ID:'id',WBS_CF_ACCESS_CLIENT_SECRET:'secret',WBS_REFS_AUTH:'auth'});assert.equal(livePilot.internalTest.allowWbsLivePilot,true);assert.equal(livePilot.wbsLivePilotMode,'ENABLED');assert.deepEqual(livePilot.wbsLivePilotCredentials,{'CF-Access-Client-Id':'id','CF-Access-Client-Secret':'secret','X-REFS-Auth':'auth'});
  assert.throws(()=>accountingServerConfig({...internal,REFS_HTTP_ALLOWED_ORIGINS:''}),/requires exactly one HTTPS REFS_HTTP_ALLOWED_ORIGINS/);assert.throws(()=>accountingServerConfig({...internal,REFS_HTTP_ALLOWED_ORIGINS:'https:\/\/internal.example,https:\/\/other.example'}),/requires exactly one HTTPS REFS_HTTP_ALLOWED_ORIGINS/);
  for(const change of [{REFS_DEPLOYMENT_ENV:'staging'},{REFS_INTERNAL_TEST_MODE:'AUTO'},{REFS_INTERNAL_TEST_TENANT_ID:''},{REFS_INTERNAL_TEST_ACTOR_ID:''},{REFS_ATTACHMENT_MODE:'REQUIRED'},{REFS_WBS_INGEST_MODE:'REQUIRED'},{REFS_AI_MODE:'ENABLED',LITELLM_BASE_URL:'https://gateway.example',LITELLM_API_KEY:'key'}])assert.throws(()=>accountingServerConfig({...internal,...change}),/REFS_INTERNAL_TEST_MODE|REFS_INTERNAL_TEST_TENANT_ID/);
  assert.equal(accountingServerConfig({...base,REFS_INTERNAL_TEST_MODE:'DISABLED'}).internalTest,null);
});test('unsigned WBS live pilot is disabled by default and requires server-side credentials when enabled',()=>{
  const disabled=accountingServerConfig({...base,REFS_WBS_LIVE_PILOT_MODE:undefined});assert.equal(disabled.wbsLivePilotMode,'DISABLED');assert.equal(disabled.wbsLivePilotCredentials,null);
  const enabled={...base,REFS_WBS_LIVE_PILOT_MODE:'ENABLED',WBS_CF_ACCESS_CLIENT_ID:'client-id',WBS_CF_ACCESS_CLIENT_SECRET:'client-secret',WBS_REFS_AUTH:'refs-auth'};
  const config=accountingServerConfig(enabled);assert.equal(config.wbsLivePilotMode,'ENABLED');assert.deepEqual(config.wbsLivePilotCredentials,{'CF-Access-Client-Id':'client-id','CF-Access-Client-Secret':'client-secret','X-REFS-Auth':'refs-auth'});
  for(const key of ['WBS_CF_ACCESS_CLIENT_ID','WBS_CF_ACCESS_CLIENT_SECRET','WBS_REFS_AUTH'])assert.throws(()=>accountingServerConfig({...enabled,[key]:''}),new RegExp(key));
  assert.throws(()=>accountingServerConfig({...base,REFS_WBS_LIVE_PILOT_MODE:'AUTO'}),/ENABLED or DISABLED/);
});
test('WBS test import is disabled by default and can run only in staging with eleven distinct internal actors',()=>{
  assert.equal(accountingServerConfig(base).wbsTestImportMode,'DISABLED');assert.equal(accountingServerConfig(base).wbsTestImport,null);
  const enabled={...base,REFS_DEPLOYMENT_ENV:'staging',REFS_WBS_LIVE_PILOT_MODE:'ENABLED',WBS_CF_ACCESS_CLIENT_ID:'client-id',WBS_CF_ACCESS_CLIENT_SECRET:'client-secret',WBS_REFS_AUTH:'refs-auth',REFS_WBS_TEST_IMPORT_MODE:'ENABLED',REFS_WBS_TEST_IMPORT_TENANT_ID:'6fb25daf-0799-4805-bede-be54230da33c',REFS_WBS_TEST_IMPORT_ENTITY_ID:'ca8d23c7-0ea6-4860-8e3e-caf9a3e22ce3',REFS_WBS_TEST_IMPORT_COMPANY_CODE:'WBPA',REFS_WBS_TEST_IMPORT_IMPORTER_ACTOR_ID:'test-importer',REFS_WBS_TEST_IMPORT_RECONCILIATION_STARTER_ACTOR_ID:'test-starter',REFS_WBS_TEST_IMPORT_MAKER_ACTOR_ID:'test-maker',REFS_WBS_TEST_IMPORT_PAYMENT_MAKER_ACTOR_ID:'test-payment-maker',REFS_WBS_TEST_IMPORT_MATCH_MAKER_ACTOR_ID:'test-match-maker',REFS_WBS_TEST_IMPORT_SUBMITTER_ACTOR_ID:'test-submitter',REFS_WBS_TEST_IMPORT_REVIEWER_ACTOR_ID:'test-reviewer',REFS_WBS_TEST_IMPORT_APPROVER_ACTOR_ID:'test-approver',REFS_WBS_TEST_IMPORT_POSTER_ACTOR_ID:'test-poster',REFS_WBS_TEST_IMPORT_CLEARER_ACTOR_ID:'test-clearer',REFS_WBS_TEST_IMPORT_REOPENER_ACTOR_ID:'test-reopener'};
  const config=accountingServerConfig(enabled);assert.equal(config.wbsTestImportMode,'ENABLED');assert.deepEqual(config.wbsTestImport,{tenantId:enabled.REFS_WBS_TEST_IMPORT_TENANT_ID,entityId:enabled.REFS_WBS_TEST_IMPORT_ENTITY_ID,companyCode:'WBPA',actors:{importer:'test-importer',reconciliationStarter:'test-starter',maker:'test-maker',paymentMaker:'test-payment-maker',matchMaker:'test-match-maker',submitter:'test-submitter',reviewer:'test-reviewer',approver:'test-approver',poster:'test-poster',clearer:'test-clearer',reopener:'test-reopener'}});
  assert.throws(()=>accountingServerConfig({...enabled,REFS_DEPLOYMENT_ENV:'production'}),/only in staging/);assert.throws(()=>accountingServerConfig({...enabled,REFS_WBS_LIVE_PILOT_MODE:'DISABLED'}),/requires REFS_WBS_LIVE_PILOT_MODE/);assert.throws(()=>accountingServerConfig({...enabled,REFS_WBS_TEST_IMPORT_REVIEWER_ACTOR_ID:'test-maker'}),/canonical and distinct/);assert.throws(()=>accountingServerConfig({...enabled,REFS_WBS_TEST_IMPORT_MODE:'AUTO'}),/ENABLED or DISABLED/);
  const renderFallback={...enabled,RENDER:'true'};
  for(const key of ['REFS_WBS_TEST_IMPORT_RECONCILIATION_STARTER_ACTOR_ID','REFS_WBS_TEST_IMPORT_PAYMENT_MAKER_ACTOR_ID','REFS_WBS_TEST_IMPORT_MATCH_MAKER_ACTOR_ID','REFS_WBS_TEST_IMPORT_CLEARER_ACTOR_ID','REFS_WBS_TEST_IMPORT_REOPENER_ACTOR_ID'])delete renderFallback[key];
  const renderConfig=accountingServerConfig(renderFallback);
  assert.deepEqual({reconciliationStarter:renderConfig.wbsTestImport.actors.reconciliationStarter,paymentMaker:renderConfig.wbsTestImport.actors.paymentMaker,matchMaker:renderConfig.wbsTestImport.actors.matchMaker,clearer:renderConfig.wbsTestImport.actors.clearer,reopener:renderConfig.wbsTestImport.actors.reopener},{reconciliationStarter:'wbs-test-reconciliation-starter',paymentMaker:'wbs-test-payment-maker',matchMaker:'wbs-test-match-maker',clearer:'wbs-test-clearer',reopener:'wbs-test-reopener'});
  assert.throws(()=>accountingServerConfig({...renderFallback,RENDER:'false'}),/RECONCILIATION_STARTER_ACTOR_ID is required/);
  assert.throws(()=>accountingServerConfig({...renderFallback,REFS_WBS_TEST_IMPORT_ENTITY_ID:'10e95b7f-d74f-43c7-ab56-e92efdc62226'}),/RECONCILIATION_STARTER_ACTOR_ID is required/);
  assert.throws(()=>accountingServerConfig({...renderFallback,REFS_WBS_TEST_IMPORT_IMPORTER_ACTOR_ID:''}),/IMPORTER_ACTOR_ID is required/);
});
test('LiteLLM gateway is disabled by default and requires server-only HTTPS configuration when enabled',()=>{
  assert.equal(accountingServerConfig(base).aiMode,'DISABLED');const enabled=accountingServerConfig({...base,REFS_AI_MODE:'ENABLED',LITELLM_BASE_URL:'https://igateway.wbm3.com',LITELLM_API_KEY:'sk-virtual-key-12345',LITELLM_MODEL:'gpt-4.1-mini'});assert.equal(enabled.aiMode,'ENABLED');assert.equal(typeof enabled.aiGateway.analyzeJson,'function');for(const key of ['LITELLM_BASE_URL','LITELLM_API_KEY'])assert.throws(()=>accountingServerConfig({...base,REFS_AI_MODE:'ENABLED',[key]:''}),/LITELLM_/);assert.throws(()=>accountingServerConfig({...base,REFS_AI_MODE:'AUTO'}),/REFS_AI_MODE/);assert.throws(()=>accountingServerConfig({...base,REFS_AI_MODE:'ENABLED',LITELLM_BASE_URL:'http://gateway.example',LITELLM_API_KEY:'sk-virtual-key-12345'}),/LITELLM_BASE_URL/);
});
test('internal-test HTTP boundary blocks every write method before kernel access',async()=>{
  let kernelUsed=false;const server=createAccountingHttpServer({internalTest:{tenantId:'11111111-1111-4111-8111-111111111111',actorId:'internal-test-operator'},authenticate:async()=>({trusted:true,internalTest:true,tenantId:'11111111-1111-4111-8111-111111111111',actorId:'internal-test-operator'}),kernelFactory:async()=>{kernelUsed=true;return {postJournal:async()=>({})};}});
  await new Promise((resolve,reject)=>server.listen(0,'127.0.0.1',error=>error?reject(error):resolve()));try{const endpoint=`http://127.0.0.1:${server.address().port}/api/v1/entities/22222222-2222-4222-8222-222222222222/journal-entries/33333333-3333-4333-8333-333333333333/post`;for(const method of ['POST','PUT','PATCH','DELETE','TRACE']){const response=await fetch(endpoint,{method,headers:{'content-type':'application/json','idempotency-key':`internal-${method.toLowerCase()}-block-0001`,'if-match':'"0"'},body:JSON.stringify({periodId:'44444444-4444-4444-8444-444444444444'})});assert.equal(response.status,403,method);assert.equal((await response.json()).code,'INTERNAL_TEST_READ_ONLY',method);}assert.equal(kernelUsed,false);}finally{await new Promise(resolve=>server.close(resolve));}
});test('production readiness fails closed when attachment storage or scanner is unavailable',async()=>{const pool=readyPool;const build=(storageOk,scannerOk)=>createProductionAccountingServer({runtimePool:pool,issuerPool:pool,authenticator:{authenticate:async()=>({})},attachmentStorage:{probe:async()=>{if(!storageOk)throw new Error('storage offline');return true;}},virusScanner:{probe:async()=>{if(!scannerOk)throw new Error('scanner offline');return true;}},scannerServiceActorId:'scanner',wbsSnapshotVerifier:()=>true});for(const [storageOk,scannerOk,status] of [[true,true,200],[false,true,503],[true,false,503]]){const server=build(storageOk,scannerOk);await new Promise((resolve,reject)=>server.listen(0,'127.0.0.1',error=>error?reject(error):resolve()));try{const port=server.address().port,response=await fetch(`http://127.0.0.1:${port}/health/ready`);assert.equal(response.status,status);assert.equal((await response.json()).ok,status===200);}finally{await new Promise(resolve=>server.close(resolve));}}});
test('signed Final-1 readiness requires immutable versioned Object Lock storage',async()=>{const pool=readyPool;const build=ok=>createProductionAccountingServer({runtimePool:pool,issuerPool:pool,authenticator:{authenticate:async()=>({})},wbsImmutableEvidenceStorage:{retentionDays:365,probeImmutable:async()=>{if(!ok)throw new Error('object lock offline');},putImmutableVersion:async()=>{}},wbsProviderSignedTrust:{public_key:'PEM'},wbsProviderSignedServiceActorId:'provider-service'});for(const [ok,status] of [[true,200],[false,503]]){const server=build(ok);await new Promise((resolve,reject)=>server.listen(0,'127.0.0.1',error=>error?reject(error):resolve()));try{const response=await fetch(`http://127.0.0.1:${server.address().port}/health/ready`);assert.equal(response.status,status);assert.equal((await response.json()).ok,status===200);}finally{await new Promise(resolve=>server.close(resolve));}}});
test('Stage 1 readiness depends only on the two database identities when integrations are disabled',async()=>{const pool=readyPool;const server=createProductionAccountingServer({runtimePool:pool,issuerPool:pool,authenticator:{authenticate:async()=>({trusted:true,tenantId:'tenant',actorId:'actor'})}});await new Promise((resolve,reject)=>server.listen(0,'127.0.0.1',error=>error?reject(error):resolve()));try{const response=await fetch(`http://127.0.0.1:${server.address().port}/health/ready`);assert.equal(response.status,200);assert.equal((await response.json()).ok,true);}finally{await new Promise(resolve=>server.close(resolve));}});
test('all production modes fail readiness closed unless Controller mapping database functions are installed',async()=>{let schemaReady=true;const pool={query:async sql=>({rowCount:1,rows:String(sql).includes('to_regprocedure')?[{ready:schemaReady}]:[]})};const server=createProductionAccountingServer({runtimePool:pool,issuerPool:pool,authenticator:{authenticate:async()=>({trusted:true,tenantId:'tenant',actorId:'actor'})}});await new Promise((resolve,reject)=>server.listen(0,'127.0.0.1',error=>error?reject(error):resolve()));try{assert.equal((await fetch(`http://127.0.0.1:${server.address().port}/health/ready`)).status,200);schemaReady=false;assert.equal((await fetch(`http://127.0.0.1:${server.address().port}/health/ready`)).status,503);}finally{await new Promise(resolve=>server.close(resolve));}});
test('production readiness requires both period-scoped AP and AR control readers',async()=>{const readinessSql=[];const pool={query:async sql=>{if(String(sql).includes('to_regprocedure')){readinessSql.push(String(sql));return {rowCount:1,rows:[{ready:true}]};}return {rowCount:1,rows:[{ready:true}]};}};const server=createProductionAccountingServer({runtimePool:pool,issuerPool:pool,authenticator:{authenticate:async()=>({trusted:true,tenantId:'tenant',actorId:'actor'})}});await new Promise((resolve,reject)=>server.listen(0,'127.0.0.1',error=>error?reject(error):resolve()));try{assert.equal((await fetch(`http://127.0.0.1:${server.address().port}/health/ready`)).status,200);const controllerSql=readinessSql.find(sql=>sql.includes('refs_ap_control_total'));assert.ok(controllerSql);assert.match(controllerSql,/refs_ap_control_total\(uuid,uuid,uuid\)/);assert.match(controllerSql,/refs_ar_control_total\(uuid,uuid,uuid\)/);}finally{await new Promise(resolve=>server.close(resolve));}});
test('production readiness requires the atomic Final-1 signed-control successor functions',async()=>{const readinessSql=[];const pool={query:async sql=>{if(String(sql).includes('to_regprocedure')){readinessSql.push(String(sql));return {rowCount:1,rows:[{ready:true}]};}return {rowCount:1,rows:[{ready:true}]};}};const server=createProductionAccountingServer({runtimePool:pool,issuerPool:pool,authenticator:{authenticate:async()=>({trusted:true,tenantId:'tenant',actorId:'actor'})}});await new Promise((resolve,reject)=>server.listen(0,'127.0.0.1',error=>error?reject(error):resolve()));try{assert.equal((await fetch(`http://127.0.0.1:${server.address().port}/health/ready`)).status,200);const controllerSql=readinessSql.find(sql=>sql.includes('refs_record_wbs_final1_signed_control_total'));assert.ok(controllerSql);for(const name of ['refs_record_wbs_final1_signed_control_total','refs_retain_wbs_final1_business_evidence','refs_retain_wbs_final1_source_evidence_with_signed_controls'])assert.match(controllerSql,new RegExp(`${name}\\(`));}finally{await new Promise(resolve=>server.close(resolve));}});
test('accounting settings readiness fails closed until migration 374 functions and refs_app grants are present',async()=>{let workflowReady=true;const readinessSql=[];const pool={query:async sql=>{const statement=String(sql);if(statement.includes('to_regprocedure'))readinessSql.push(statement);const isWorkflow=statement.includes('refs_read_accounting_settings_workflow_evidence');return {rowCount:1,rows:[{ready:isWorkflow?workflowReady:true}]};}};const server=createProductionAccountingServer({runtimePool:pool,issuerPool:pool,authenticator:{authenticate:async()=>({trusted:true,tenantId:'tenant',actorId:'actor'})}});await new Promise((resolve,reject)=>server.listen(0,'127.0.0.1',error=>error?reject(error):resolve()));try{assert.equal((await fetch(`http://127.0.0.1:${server.address().port}/health/ready`)).status,200);const workflowSql=readinessSql.find(sql=>sql.includes('refs_read_accounting_settings_workflow_evidence'));assert.ok(workflowSql);for(const required of ['public.accounting_settings_workflow','public.accounting_settings_workflow_history','refs_read_accounting_settings_workflow','refs_read_accounting_settings_workflow_evidence','refs_read_accounting_settings_workflow_options','refs_read_accounting_settings_workflow_register','refs_accounting_settings_create_hash','refs_accounting_settings_transition_hash','refs_create_accounting_settings_workflow','refs_transition_accounting_settings_workflow','refs_read_wbs_ai_approved_entity_period_settings','refs_read_authoritative_setting_history','has_function_privilege'])assert.match(workflowSql,new RegExp(required));assert.equal([...workflowSql.matchAll(/has_function_privilege\('refs_app'/g)].length,10);assert.doesNotMatch(workflowSql,/has_function_privilege\(current_user/);workflowReady=false;assert.equal((await fetch(`http://127.0.0.1:${server.address().port}/health/ready`)).status,503);}finally{await new Promise(resolve=>server.close(resolve));}});

test('recent accounting workflows fail readiness closed until migrations 386 through 391 functions and refs_app grants are present',async()=>{let recentReady=true;const readinessSql=[];const pool={query:async sql=>{const statement=String(sql);if(statement.includes('refs_read_import_export_history'))readinessSql.push(statement);const isRecent=statement.includes('refs_read_import_export_history');return {rowCount:1,rows:[{ready:isRecent?recentReady:true}]};}};const server=createProductionAccountingServer({runtimePool:pool,issuerPool:pool,authenticator:{authenticate:async()=>({trusted:true,tenantId:'tenant',actorId:'actor'})}});await new Promise((resolve,reject)=>server.listen(0,'127.0.0.1',error=>error?reject(error):resolve()));try{assert.equal((await fetch(`http://127.0.0.1:${server.address().port}/health/ready`)).status,200);const sql=readinessSql.at(-1);assert.ok(sql);for(const required of ['public.report_saved_view','public.webhook_subscription','public.forecast_workflow','public.import_export_history_job','public.recurring_schedule','public.recurring_schedule_run','refs_read_report_saved_views','refs_create_report_saved_view','refs_update_report_saved_view','refs_read_webhook_subscription','refs_create_webhook_subscription','refs_transition_webhook_subscription','refs_read_webhook_delivery_history','refs_read_forecast_workflow','refs_create_forecast_workflow','refs_transition_forecast_workflow','refs_read_import_export_history','refs_record_posted_ledger_export_history','refs_read_recurring_schedule','refs_create_recurring_schedule','refs_transition_recurring_schedule','refs_run_due_recurring_schedules','refs_read_custom_report','refs_parse_source_document','has_function_privilege'])assert.match(sql,new RegExp(required));assert.equal([...sql.matchAll(/has_function_privilege\('refs_app'/g)].length,18);recentReady=false;assert.equal((await fetch(`http://127.0.0.1:${server.address().port}/health/ready`)).status,503);}finally{await new Promise(resolve=>server.close(resolve));}});
test('enabled WBS test import readiness requires receipt, human start, and separate Post/Clear functions',async()=>{const readinessSql=[];const pool={query:async sql=>{if(String(sql).includes('to_regprocedure'))readinessSql.push(String(sql));return {rowCount:1,rows:[{ready:true}]};}};const wbsTestImport={tenantId:'6fb25daf-0799-4805-bede-be54230da33c',entityId:'ca8d23c7-0ea6-4860-8e3e-caf9a3e22ce3',companyCode:'WBPA',actors:{importer:'wbs-test-importer',reconciliationStarter:'wbs-test-starter',maker:'wbs-test-maker',paymentMaker:'wbs-test-payment-maker',matchMaker:'wbs-test-match-maker',submitter:'wbs-test-submitter',reviewer:'wbs-test-reviewer',approver:'wbs-test-approver',poster:'wbs-test-poster',clearer:'wbs-test-clearer',reopener:'wbs-test-reopener'}};const server=createProductionAccountingServer({runtimePool:pool,issuerPool:pool,authenticator:{authenticate:async()=>({trusted:true,tenantId:wbsTestImport.tenantId,actorId:'actor'})},wbsLivePilotClient:{readObservation:async()=>null},wbsTestImport});await new Promise((resolve,reject)=>server.listen(0,'127.0.0.1',error=>error?reject(error):resolve()));try{assert.equal((await fetch(`http://127.0.0.1:${server.address().port}/health/ready`)).status,200);const importSql=readinessSql.find(sql=>sql.includes('refs_begin_wbs_test_bank_staged_import'));assert.ok(importSql);for(const name of ['refs_create_wbs_test_payable_draft_hash','refs_create_wbs_test_payable_draft','refs_begin_wbs_test_bank_staged_import','refs_append_wbs_test_bank_staged_chunk','refs_finalize_wbs_test_bank_import_receipt','refs_start_wbs_test_bank_reconciliation','refs_wbs_test_bank_adjustment_post_batch','refs_wbs_test_bank_adjustment_clear_batch','refs_list_reconciliation_adjustment_evidence'])assert.match(importSql,new RegExp(`${name}\\(`));}finally{await new Promise(resolve=>server.close(resolve));}});
