import assert from'node:assert/strict';import test from'node:test';
import{validAccountingSettingsWorkflow,validAccountingSettingsWorkflowEvidence,validAccountingSettingsWorkflowOptions,validAccountingSettingsWorkflowRegister,validAccountingSettingsCreateReceipt,validAccountingSettingsTransitionReceipt}from'../runtime/accounting-settings-workflow-contract.mjs';
import{accountingSettingsOptions,accountingSettingsWorkflow,accountingSettingsWorkflowEvidence,accountingSettingsWorkflowEvidenceWithHistoricalAndFutureRules,id}from'./helpers/accounting-settings-workflow-fixture.mjs';
test('settings workflow contract accepts only the exact five-decision lifecycle prefix',()=>{for(const status of ['DRAFT','SUBMITTED','REVIEWED','APPROVED','ACTIVE','SUPERSEDED'])assert.equal(validAccountingSettingsWorkflow(accountingSettingsWorkflow(status)),true);for(const mutate of[row=>row.history[1].to_status='REVIEWED',row=>row.history[0].reason=null,row=>row.submitted_by='maker',row=>row.submitted_at='2026-09-09T00:00:00Z',row=>row.canonical_parent_snapshot.company_code='unsafe company',row=>row.canonical_parent_snapshot.period_end='2026-02-30',row=>row.canonical_parent_snapshot.coa.setting_snapshot_id=id(999)]){const row=accountingSettingsWorkflow('SUBMITTED');mutate(row);assert.equal(validAccountingSettingsWorkflow(row),false);}});
test('GET forbids idempotent and command receipts require it',()=>{const getter=accountingSettingsWorkflow(),command=accountingSettingsWorkflow('DRAFT',{command:true});assert.equal(validAccountingSettingsWorkflow({...getter,idempotent:false}),false);assert.equal(validAccountingSettingsCreateReceipt(getter),false);assert.equal(validAccountingSettingsCreateReceipt(command),true);assert.equal(validAccountingSettingsTransitionReceipt({...accountingSettingsWorkflow('SUBMITTED'),idempotent:false},{action:'SUBMIT',expectedRevision:0}),true);assert.equal(validAccountingSettingsTransitionReceipt(accountingSettingsWorkflow('SUBMITTED'),{action:'SUBMIT',expectedRevision:0}),false);});
test('options recompute exact missing families, unique approved ids and OPEN action readiness',()=>{const options=accountingSettingsOptions();assert.equal(validAccountingSettingsWorkflowOptions(options),true);const missing=structuredClone(options);missing.prerequisites[2].approved_options=[];assert.equal(validAccountingSettingsWorkflowOptions(missing),false);missing.blockers.missing_approved_families=[missing.prerequisites[2].family];missing.action_flags.can_create_draft=false;assert.equal(validAccountingSettingsWorkflowOptions(missing),true);const duplicate=structuredClone(options);duplicate.prerequisites[1].approved_options[0].setting_snapshot_id=duplicate.prerequisites[0].approved_options[0].setting_snapshot_id;assert.equal(validAccountingSettingsWorkflowOptions(duplicate),false);const closed=structuredClone(options);closed.blockers.period_status='CLOSED';assert.equal(validAccountingSettingsWorkflowOptions(closed),false);closed.action_flags.can_create_draft=false;assert.equal(validAccountingSettingsWorkflowOptions(closed),true);});
test('workflow actions fail closed when retained child evidence is no longer current',()=>{const stale=accountingSettingsWorkflow('DRAFT');stale.source_current=false;assert.equal(stale.action_flags.can_submit,true);assert.equal(validAccountingSettingsWorkflow(stale),false);stale.action_flags.can_submit=false;assert.equal(validAccountingSettingsWorkflow(stale),true);});
test('history chain and command receipts bind exact evidence while ignoring object key order',()=>{const draft=accountingSettingsWorkflow('DRAFT'),receipt=accountingSettingsWorkflow('DRAFT',{command:true}),reordered=Object.fromEntries(Object.entries(draft.child_setting_snapshot_ids).reverse()),reason=draft.history[0].reason;assert.equal(validAccountingSettingsCreateReceipt(receipt,{tenantId:draft.tenant_id,entityId:draft.entity_id,periodId:draft.period_id,expectedChildSettingSnapshotIds:reordered,expectedReason:reason,expectedActor:'maker'}),true);reordered.coa=id(999);assert.equal(validAccountingSettingsCreateReceipt(receipt,{expectedChildSettingSnapshotIds:reordered}),false);const submitted=accountingSettingsWorkflow('SUBMITTED',{command:true});assert.equal(validAccountingSettingsTransitionReceipt(submitted,{tenantId:draft.tenant_id,entityId:draft.entity_id,workflowId:draft.accounting_settings_workflow_id,action:'SUBMIT',expectedRevision:0,priorWorkflow:draft,expectedReason:reason}),true);const rewritten=structuredClone(submitted);rewritten.history[0].reason='Rewrite retained accounting settings history evidence.';assert.equal(validAccountingSettingsTransitionReceipt(rewritten,{tenantId:draft.tenant_id,entityId:draft.entity_id,workflowId:draft.accounting_settings_workflow_id,action:'SUBMIT',expectedRevision:0,priorWorkflow:draft,expectedReason:reason}),false);const changed=structuredClone(submitted);changed.canonical_parent_hash=hashForTest();assert.equal(validAccountingSettingsTransitionReceipt(changed,{tenantId:draft.tenant_id,entityId:draft.entity_id,workflowId:draft.accounting_settings_workflow_id,action:'SUBMIT',expectedRevision:0,priorWorkflow:draft,expectedReason:reason}),false);});
test('options and register stay bounded, unique and deterministically ordered',()=>{const options=accountingSettingsOptions(),extra=structuredClone(options.prerequisites[0].approved_options[0]);extra.setting_snapshot_id=id(999);options.prerequisites[0].approved_options.push(extra);assert.equal(validAccountingSettingsWorkflowOptions(options),false);const newer=accountingSettingsWorkflow('DRAFT'),older=accountingSettingsWorkflow('DRAFT');newer.accounting_settings_workflow_id=id(60);newer.created_at='2026-09-02T00:00:00Z';newer.history[0].created_at=newer.created_at;older.accounting_settings_workflow_id=id(50);older.created_at='2026-09-01T00:00:00Z';older.history[0].created_at=older.created_at;const register={schema_version:'ACCOUNTING_SETTINGS_WORKFLOW_REGISTER_V1',tenant_id:newer.tenant_id,entity_id:newer.entity_id,rows:[newer,older],limit:2,boundary:'PARENT_SNAPSHOT_ACTIVATION_ONLY'};assert.equal(validAccountingSettingsWorkflowRegister(register,{tenantId:newer.tenant_id,entityId:newer.entity_id,limit:2}),true);assert.equal(validAccountingSettingsWorkflowRegister({...register,rows:[older,newer]},{tenantId:newer.tenant_id,entityId:newer.entity_id,limit:2}),false);assert.equal(validAccountingSettingsWorkflowRegister({...register,rows:[newer,newer]},{tenantId:newer.tenant_id,entityId:newer.entity_id,limit:2}),false);assert.equal(validAccountingSettingsWorkflowRegister({...register,limit:1},{tenantId:newer.tenant_id,entityId:newer.entity_id,limit:1}),false);});
test('workflow evidence binds every complete policy body to the canonical parent and exact scope',()=>{const evidence=accountingSettingsWorkflowEvidence(),scope={tenantId:evidence.tenant_id,entityId:evidence.entity_id,workflowId:evidence.workflow_id,periodId:evidence.period_id};assert.equal(validAccountingSettingsWorkflowEvidence(evidence,scope),true);for(const mutate of[value=>value.tenant_id=id(9),value=>value.period_id=id(9),value=>value.selected_child_snapshots.pop(),value=>value.selected_child_snapshots.reverse(),value=>value.selected_child_snapshots[1].setting_snapshot_id=value.selected_child_snapshots[0].setting_snapshot_id,value=>value.selected_child_snapshots[0].snapshot_hash=hashForTest(),value=>value.selected_child_snapshots[0].snapshot.settings.authorization='Bearer forbidden-secret-token']){const forged=structuredClone(evidence);mutate(forged);assert.equal(validAccountingSettingsWorkflowEvidence(forged,scope),false);}});
test('workflow evidence validates every retained settings family and their cross-family bindings',()=>{const evidence=accountingSettingsWorkflowEvidence(),scope={tenantId:evidence.tenant_id,entityId:evidence.entity_id,workflowId:evidence.workflow_id,periodId:evidence.period_id},settings=(value,key)=>value.selected_child_snapshots.find(row=>row.key===key).snapshot.settings;const invalidByFamily=[
 ['coa',value=>settings(value,'coa').accounts.pop()],
 ['vendor_treatment',value=>settings(value,'vendor_treatment').unexpected=true],
 ['project_property_cost_code',value=>settings(value,'project_property_cost_code').default_capitalization_treatment='CWIP'],
 ['period_close_policy',value=>settings(value,'period_close_policy').period_status='CLOSED'],
 ['tax',value=>settings(value,'tax').expense_account_role='UNKNOWN'],
 ['intercompany',value=>{const policy=settings(value,'intercompany');policy.enabled=true;policy.clearing_account_role='INTERCOMPANY_CLEARING';}],
 ['materiality',value=>settings(value,'materiality').currency='EUR'],
 ['approval_thresholds',value=>settings(value,'approval_thresholds').approval_levels[0].reviewer_role='AP_PREPARER'],
 ['report_mapping',value=>settings(value,'report_mapping').account_mappings[0].statement='UNKNOWN'],
 ['loan_capitalization_policy',value=>settings(value,'loan_capitalization_policy').qualifying_combinations[0].asset_ref='asset-1']
 ];for(const [family,mutate] of invalidByFamily){const forged=structuredClone(evidence);mutate(forged);assert.equal(validAccountingSettingsWorkflowEvidence(forged,scope),false,family);}
 const reportDrift=structuredClone(evidence);settings(reportDrift,'report_mapping').account_mappings[0].account_code='999999';assert.equal(validAccountingSettingsWorkflowEvidence(reportDrift,scope),false,'report mapping must bind the active COA');
 const dimensionDrift=structuredClone(evidence);settings(dimensionDrift,'loan_capitalization_policy').qualifying_combinations[0].project_ref='unapproved-project';assert.equal(validAccountingSettingsWorkflowEvidence(dimensionDrift,scope),false,'loan policy must bind an approved CWIP dimension');
 const duplicateSod=structuredClone(evidence);settings(duplicateSod,'approval_thresholds').approval_levels[0].sod_constraints.push('APPROVER_NE_POSTER');assert.equal(validAccountingSettingsWorkflowEvidence(duplicateSod,scope),false,'SoD constraints must be exact and unique');
 const invalidHistoricalMapping=structuredClone(evidence),mappings=settings(invalidHistoricalMapping,'report_mapping').account_mappings;mappings.push({...mappings[0],statement:'IS',effective_from:'2026-01-01',effective_to:'2026-09-30'});assert.equal(validAccountingSettingsWorkflowEvidence(invalidHistoricalMapping,scope),false,'historical report mappings retain role semantics');
 for(const mutate of[value=>settings(value,'tax').allocation_precision=0.0001,value=>settings(value,'tax').tax_codes[0].rate=0,value=>settings(value,'loan_capitalization_policy').materiality_amount=100]){const numericMoney=structuredClone(evidence);mutate(numericMoney);assert.equal(validAccountingSettingsWorkflowEvidence(numericMoney,scope),false,'MONEY4 evidence must retain its exact string representation');}
});
test('intercompany clearing report semantics follow the approved COA classification',()=>{const evidence=accountingSettingsWorkflowEvidence(),scope={tenantId:evidence.tenant_id,entityId:evidence.entity_id,workflowId:evidence.workflow_id,periodId:evidence.period_id},settings=(value,key)=>value.selected_child_snapshots.find(row=>row.key===key).snapshot.settings,clearing=value=>settings(value,'coa').accounts.find(account=>account.role==='INTERCOMPANY_CLEARING'),mapping=value=>settings(value,'report_mapping').account_mappings.find(row=>row.account_role==='INTERCOMPANY_CLEARING');assert.equal(clearing(evidence).account_class,'ASSET');assert.equal(mapping(evidence).normal_balance,'DEBIT');assert.equal(validAccountingSettingsWorkflowEvidence(evidence,scope),true,'ASSET clearing uses a BS debit mapping');const liability=structuredClone(evidence);clearing(liability).account_class='LIABILITY';mapping(liability).normal_balance='CREDIT';assert.equal(validAccountingSettingsWorkflowEvidence(liability,scope),true,'LIABILITY clearing uses a BS credit mapping');const wrongAsset=structuredClone(evidence);mapping(wrongAsset).normal_balance='CREDIT';assert.equal(validAccountingSettingsWorkflowEvidence(wrongAsset,scope),false,'ASSET clearing cannot use a credit mapping');const wrongLiability=structuredClone(liability);mapping(wrongLiability).normal_balance='DEBIT';assert.equal(validAccountingSettingsWorkflowEvidence(wrongLiability,scope),false,'LIABILITY clearing cannot use a debit mapping');});
test('workflow evidence rejects non-string or empty dimension requirements',()=>{const evidence=accountingSettingsWorkflowEvidence(),scope={tenantId:evidence.tenant_id,entityId:evidence.entity_id,workflowId:evidence.workflow_id,periodId:evidence.period_id},settings=(value,key)=>value.selected_child_snapshots.find(row=>row.key===key).snapshot.settings;const coa=structuredClone(evidence);settings(coa,'coa').accounts[0].dimension_requirements=[{dimension:'project'}];assert.equal(validAccountingSettingsWorkflowEvidence(coa,scope),false,'COA dimension requirements must be non-empty strings');const intercompany=structuredClone(evidence),policy=settings(intercompany,'intercompany');policy.enabled=true;policy.clearing_account_role='INTERCOMPANY_CLEARING';policy.entities=[{company_code:'COUNTERPARTY',counterparty_entity_id:id(90),counterparty_approval_id:id(91),counterparty_approval_hash:hashForTest(),currency:'USD',dimension_requirements:[''],due_to_account_role:'INTERCOMPANY_DUE_TO',due_from_account_role:'INTERCOMPANY_DUE_FROM',elimination_account_role:'INTERCOMPANY_ELIMINATION',effective_from:'2026-01-01',effective_to:null}];assert.equal(validAccountingSettingsWorkflowEvidence(intercompany,scope),false,'intercompany dimension requirements must be non-empty strings');});
test('workflow evidence accepts SQL-valid historical and future nested rules while retaining current-period gates',()=>{const evidence=accountingSettingsWorkflowEvidenceWithHistoricalAndFutureRules(),scope={tenantId:evidence.tenant_id,entityId:evidence.entity_id,workflowId:evidence.workflow_id,periodId:evidence.period_id};assert.equal(validAccountingSettingsWorkflowEvidence(evidence,scope),true);const expiredClassification=structuredClone(evidence),thresholds=expiredClassification.selected_child_snapshots.find(row=>row.key==='approval_thresholds').snapshot.settings.classification_thresholds;thresholds[0].effective_to='2026-09-30';assert.equal(validAccountingSettingsWorkflowEvidence(expiredClassification,scope),false);const taxGap=structuredClone(evidence);taxGap.selected_child_snapshots.find(row=>row.key==='tax').snapshot.settings.coverage_end='2026-09-30';assert.equal(validAccountingSettingsWorkflowEvidence(taxGap,scope),false);});
function hashForTest(){return `sha256:${'f'.repeat(64)}`;}
