import test from 'node:test';import assert from 'node:assert/strict';import {generateKeyPairSync} from 'node:crypto';import {accountingServerConfig} from '../runtime/start-accounting-server.mjs';import {createProductionAccountingServer} from '../runtime/accounting-server.mjs';
const {publicKey}=generateKeyPairSync('ed25519');const publicKeyPem=publicKey.export({type:'spki',format:'pem'}),wbsSnapshotPublicKeys=JSON.stringify({'it-wbs-2026-08':publicKeyPem}),wbsProviderSignedTrust=JSON.stringify({issuer:'wbs-provider',key_id:'it-wbs-2026-08',public_key:publicKeyPem});
const base={NODE_ENV:'production',DATABASE_URL:'postgresql://runtime_user:RuntimeLongSecret99@db.example:5432/refs?sslmode=require',MIGRATION_DATABASE_URL:'postgresql://migration_user:MigrationLongSecret99@db.example:5432/refs?sslmode=require',CONTEXT_ISSUER_DATABASE_URL:'postgresql://issuer_user:IssuerLongSecret99@db.example:5432/refs?sslmode=require',GRANT_SYNC_DATABASE_URL:'postgresql://grant_user:GrantLongSecret99@db.example:5432/refs?sslmode=require',OIDC_ISSUER:'https://iam.example',OIDC_AUDIENCE:'refs-accounting',OIDC_JWKS_URI:'https://iam.example/.well-known/jwks.json',REFS_HTTP_ALLOWED_ORIGINS:'https://app.example',REFS_ATTACHMENT_MODE:'REQUIRED',REFS_WBS_INGEST_MODE:'REQUIRED',S3_ENDPOINT:'https://s3.example',S3_BUCKET:'refs',S3_REGION:'us-east-1',S3_ACCESS_KEY_ID:'key',S3_SECRET_ACCESS_KEY:'secret',VIRUS_SCANNER_ENDPOINT:'https://scan.example',VIRUS_SCANNER_TOKEN:'token',VIRUS_SCANNER_CA_FILE:'/run/secrets/scanner-ca.pem',VIRUS_SCANNER_SERVER_NAME:'scanner.internal',ATTACHMENT_SCANNER_ACTOR_ID:'scanner-service',WBS_SNAPSHOT_ED25519_PUBLIC_KEYS:wbsSnapshotPublicKeys,WBS_PROVIDER_SIGNED_TRUST:wbsProviderSignedTrust,WBS_PROVIDER_SIGNED_SERVICE_ACTOR_ID:'oidc|wbs-provider-admission-service'};
test('production startup requires OIDC, attachment dependencies, WBS signature keyring and isolated TLS database identities',()=>{const config=accountingServerConfig(base);assert.equal(config.port,8080);assert.equal(config.runtimePoolMax,4);assert.equal(config.issuerPoolMax,2);assert.equal(config.database.requirePostgres,true);assert.deepEqual(Object.keys(config.wbsSnapshotPublicKeys),['it-wbs-2026-08']);assert.equal(config.wbsProviderSignedTrust.issuer,'wbs-provider');for(const key of ['OIDC_ISSUER','OIDC_AUDIENCE','OIDC_JWKS_URI'])assert.throws(()=>accountingServerConfig({...base,[key]:''}),/OIDC_/);for(const key of ['S3_ENDPOINT','S3_BUCKET','S3_REGION','S3_ACCESS_KEY_ID','S3_SECRET_ACCESS_KEY','VIRUS_SCANNER_ENDPOINT','VIRUS_SCANNER_TOKEN','VIRUS_SCANNER_CA_FILE','VIRUS_SCANNER_SERVER_NAME','ATTACHMENT_SCANNER_ACTOR_ID','WBS_SNAPSHOT_ED25519_PUBLIC_KEYS','WBS_PROVIDER_SIGNED_TRUST','WBS_PROVIDER_SIGNED_SERVICE_ACTOR_ID'])assert.throws(()=>accountingServerConfig({...base,[key]:''}),new RegExp(key));assert.throws(()=>accountingServerConfig({...base,WBS_SNAPSHOT_ED25519_PUBLIC_KEYS:'not-json'}),/must be JSON/);assert.throws(()=>accountingServerConfig({...base,WBS_PROVIDER_SIGNED_TRUST:'not-json'}),/must be JSON/);});
test('production startup rejects unsafe port, body limit and pool budgets',()=>{assert.throws(()=>accountingServerConfig({...base,PORT:'0'}),/PORT/);assert.throws(()=>accountingServerConfig({...base,REFS_HTTP_MAX_BODY_BYTES:'999'}),/MAX_BODY/);assert.throws(()=>accountingServerConfig({...base,REFS_PG_RUNTIME_POOL_MAX:'0'}),/RUNTIME_POOL/);assert.throws(()=>accountingServerConfig({...base,REFS_PG_ISSUER_POOL_MAX:'11'}),/ISSUER_POOL/);const tuned=accountingServerConfig({...base,REFS_PG_RUNTIME_POOL_MAX:'3',REFS_PG_ISSUER_POOL_MAX:'1'});assert.equal(tuned.runtimePoolMax,3);assert.equal(tuned.issuerPoolMax,1);});
test('production startup refuses an API deployment without an explicit browser origin',()=>{assert.throws(()=>accountingServerConfig({...base,REFS_HTTP_ALLOWED_ORIGINS:''}),/REFS_HTTP_ALLOWED_ORIGINS/);});
test('production CORS allowlist accepts only explicit HTTPS origins',()=>{assert.deepEqual(accountingServerConfig({...base,REFS_HTTP_ALLOWED_ORIGINS:'https://app.example,https://staging.example'}).allowedOrigins,['https://app.example','https://staging.example']);for(const origin of ['*','http://app.example','https://app.example/path','not-an-origin'])assert.throws(()=>accountingServerConfig({...base,REFS_HTTP_ALLOWED_ORIGINS:origin}),/REFS_HTTP_ALLOWED_ORIGINS/);});
test('Stage 1 can explicitly disable later integrations without weakening core PostgreSQL and OIDC requirements',()=>{
  const stage1={...base,REFS_ATTACHMENT_MODE:'DISABLED',REFS_WBS_INGEST_MODE:'DISABLED'};
  for(const key of ['S3_ENDPOINT','S3_BUCKET','S3_REGION','S3_ACCESS_KEY_ID','S3_SECRET_ACCESS_KEY','VIRUS_SCANNER_ENDPOINT','VIRUS_SCANNER_TOKEN','VIRUS_SCANNER_CA_FILE','VIRUS_SCANNER_SERVER_NAME','ATTACHMENT_SCANNER_ACTOR_ID','WBS_SNAPSHOT_ED25519_PUBLIC_KEYS','WBS_PROVIDER_SIGNED_TRUST','WBS_PROVIDER_SIGNED_SERVICE_ACTOR_ID'])delete stage1[key];
  const config=accountingServerConfig(stage1);assert.equal(config.attachmentMode,'DISABLED');assert.equal(config.wbsIngestMode,'DISABLED');assert.equal(config.s3,null);assert.equal(config.scanner,null);assert.equal(config.wbsSnapshotPublicKeys,null);
  for(const key of ['DATABASE_URL','CONTEXT_ISSUER_DATABASE_URL','OIDC_ISSUER','OIDC_AUDIENCE','OIDC_JWKS_URI'])assert.throws(()=>accountingServerConfig({...stage1,[key]:''}));
  for(const [key,value] of [['REFS_ATTACHMENT_MODE','OPTIONAL'],['REFS_WBS_INGEST_MODE','AUTO']])assert.throws(()=>accountingServerConfig({...stage1,[key]:value}),/REQUIRED or DISABLED/);
});
test('unsigned WBS live pilot is disabled by default and requires server-side credentials when enabled',()=>{
  const disabled=accountingServerConfig({...base,REFS_WBS_LIVE_PILOT_MODE:undefined});assert.equal(disabled.wbsLivePilotMode,'DISABLED');assert.equal(disabled.wbsLivePilotCredentials,null);
  const enabled={...base,REFS_WBS_LIVE_PILOT_MODE:'ENABLED',WBS_CF_ACCESS_CLIENT_ID:'client-id',WBS_CF_ACCESS_CLIENT_SECRET:'client-secret',WBS_REFS_AUTH:'refs-auth'};
  const config=accountingServerConfig(enabled);assert.equal(config.wbsLivePilotMode,'ENABLED');assert.deepEqual(config.wbsLivePilotCredentials,{'CF-Access-Client-Id':'client-id','CF-Access-Client-Secret':'client-secret','X-REFS-Auth':'refs-auth'});
  for(const key of ['WBS_CF_ACCESS_CLIENT_ID','WBS_CF_ACCESS_CLIENT_SECRET','WBS_REFS_AUTH'])assert.throws(()=>accountingServerConfig({...enabled,[key]:''}),new RegExp(key));
  assert.throws(()=>accountingServerConfig({...base,REFS_WBS_LIVE_PILOT_MODE:'AUTO'}),/ENABLED or DISABLED/);
});
test('production readiness fails closed when attachment storage or scanner is unavailable',async()=>{const pool={query:async()=>({rowCount:1})};const build=(storageOk,scannerOk)=>createProductionAccountingServer({runtimePool:pool,issuerPool:pool,authenticator:{authenticate:async()=>({})},attachmentStorage:{probe:async()=>{if(!storageOk)throw new Error('storage offline');}},virusScanner:{probe:async()=>{if(!scannerOk)throw new Error('scanner offline');}},scannerServiceActorId:'scanner',wbsSnapshotVerifier:()=>true});for(const [storageOk,scannerOk,status] of [[true,true,200],[false,true,503],[true,false,503]]){const server=build(storageOk,scannerOk);await new Promise((resolve,reject)=>server.listen(0,'127.0.0.1',error=>error?reject(error):resolve()));try{const port=server.address().port,response=await fetch(`http://127.0.0.1:${port}/health/ready`);assert.equal(response.status,status);assert.equal((await response.json()).ok,status===200);}finally{await new Promise(resolve=>server.close(resolve));}}});
test('Stage 1 readiness depends only on the two database identities when integrations are disabled',async()=>{const pool={query:async()=>({rowCount:1})};const server=createProductionAccountingServer({runtimePool:pool,issuerPool:pool,authenticator:{authenticate:async()=>({trusted:true,tenantId:'tenant',actorId:'actor'})}});await new Promise((resolve,reject)=>server.listen(0,'127.0.0.1',error=>error?reject(error):resolve()));try{const response=await fetch(`http://127.0.0.1:${server.address().port}/health/ready`);assert.equal(response.status,200);assert.equal((await response.json()).ok,true);}finally{await new Promise(resolve=>server.close(resolve));}});
