import test from 'node:test';
import assert from 'node:assert/strict';
import {buildAiAccountingDecisionPacketFullV1} from '../runtime/ai-accounting-decision-packet-full-contract.mjs';
import {hashAiAccountingEvidence,reviewAiAccountingPostedOutcomeFullV1} from '../runtime/ai-accounting-posted-outcome-full-contract.mjs';

const id=n=>`${String(n).padStart(8,'0')}-0000-4000-8000-${String(n).padStart(12,'0')}`;
const hash=n=>`sha256:${String(n).repeat(64).slice(0,64)}`;
const scope={tenantId:id(1),entityId:id(2),accountingPeriodId:id(3)};
const source={schema_version:'AI_ACCOUNTING_SOURCE_V1',tenant_id:scope.tenantId,entity_id:scope.entityId,company_code:'WBPA',accounting_period_id:scope.accountingPeriodId,accounting_period_start:'2026-07-01',accounting_period_end:'2026-07-31',business_date:'2026-07-15',accounting_date:'2026-07-15',cash_direction:'NON_CASH',currency:'USD',amount:'100.0000',source_document_id:id(4),source_document_line_id:id(5),source_payload_hash:hash(1),source_line_hash:hash(2),source_type:'INVOICE',project_ref:null,property_ref:null,vendor_ref:'VENDOR-7',member_ref:null,cost_code_ref:null,completeness_status:'COMPLETE',duplicate_status:'NONE',admission_status:'ADMITTED',exception_codes:[],source_detail:{execution_evidence:{account_master:[{account_code:'211000',active:true,required_member_type:null,requires_member:false},{account_code:'610000',active:true,required_member_type:null,requires_member:false},{account_code:'620000',active:true,required_member_type:null,requires_member:false}],attachments:[{attachment_id:id(6),content_hash:hash(6),finalization_status:'VERIFIED_CLEAN',scan_status:'CLEAN',storage_version:'version-6'}]},invoice_date:'2026-07-15',invoice_number:'INV-7',service_period_end:'2026-07-31',service_period_start:'2026-07-01'}};
const settings={id:id(29),hash:hash(29)};
const traces=['ACCOUNT','CLASSIFICATION','MATERIALITY','APPROVAL','PERIOD_CLOSE','REPORT'].map((policy_type,index)=>({policy_type,snapshot_id:id(30+index),version:1,snapshot_hash:hash(3+index),rule_id:`${policy_type}_RULE_V1`,approval_status:'APPROVED',tenant_id:scope.tenantId,entity_id:scope.entityId,company_code:'WBPA',accounting_period_id:scope.accountingPeriodId,settings_snapshot_id:settings.id,settings_snapshot_hash:settings.hash}));
const approvalTrace=traces.find(trace=>trace.policy_type==='APPROVAL');
const workflowPolicy={approval_status:'APPROVED',tenant_id:scope.tenantId,entity_id:scope.entityId,company_code:'WBPA',period_id:scope.accountingPeriodId,settings_snapshot_id:settings.id,settings_snapshot_hash:settings.hash,policy_id:approvalTrace.snapshot_id,policy_hash:approvalTrace.snapshot_hash,stages:{DRAFT:{role:'AP_PREPARER',permission:'GL.JE.CREATE'},SUBMIT:{role:'AP_PREPARER',permission:'GL.JE.SUBMIT'},REVIEW:{role:'AP_REVIEWER',permission:'GL.JE.REVIEW'},APPROVE:{role:'CONTROLLER',permission:'GL.JE.APPROVE'},POST:{role:'GL_POSTER',permission:'GL.JE.POST'}}};
const line=(line_number,side,account_code,amount='100.0000')=>({line_number,side,account_code,account_class:side==='DEBIT'?'EXPENSE':'LIABILITY',account_type:side==='DEBIT'?'OPERATING_EXPENSE':'ACCOUNTS_PAYABLE',amount,currency:'USD',project_ref:null,property_ref:null,member_ref:null,cost_code_ref:null,dimension_requirements:[],source_document_id:id(4),source_document_line_id:id(5),source_line_hash:hash(2)});
const delta={statement:'INCOME_STATEMENT',cash_flow_classification:'NONE',accounting_period_id:scope.accountingPeriodId,account_code:'610000',account_class:'EXPENSE',direction:'INCREASE',amount:'100.0000',currency:'USD',project_ref:null,property_ref:null,member_ref:null,cost_code_ref:null,source_document_line_id:id(5)};
const liabilityDelta={...delta,statement:'BALANCE_SHEET',account_code:'211000',account_class:'LIABILITY',direction:'INCREASE'};
const approvedAccountPolicies=[['610000','EXPENSE','OPERATING_EXPENSE'],['620000','EXPENSE','OPERATING_EXPENSE'],['211000','LIABILITY','ACCOUNTS_PAYABLE']].map(([account_code,account_class,account_type])=>({account_code,account_class,account_type,normal_balance:account_class==='EXPENSE'?'DEBIT':'CREDIT',contra:false,report_statement:account_class==='EXPENSE'?'INCOME_STATEMENT':'BALANCE_SHEET',cash_flow_classification:'NONE',required_dimensions:[],optional_dimensions:[],effective_from:'2026-01-01',effective_to:null,settings_snapshot_id:settings.id,settings_snapshot_hash:settings.hash}));
const packet=buildAiAccountingDecisionPacketFullV1({...scope,source,classification:'EXPENSE',ruleId:'EXPENSE_POLICY_V1',reason:'Approved current-period expense.',confidence:.94,risk:{risk_level:'MEDIUM',policy_rule_id:'RISK_POLICY_V1',materiality_threshold:'50.0000',approval_threshold:'500.0000',confidence_floor:.9,threshold_comparison:'AT_OR_ABOVE_MATERIALITY'},requiredHumanFields:['controller_conclusion'],policyTraces:traces,workflowPolicy,approvedAccountPolicies,proposedJournal:{status:'SUGGESTED_ONLY',balanced:true,reversal_policy:'NONE',lines:[line(1,'DEBIT','610000'),line(2,'CREDIT','211000')]},expectedReportDeltas:[delta,liabilityDelta]});
const actual=(sourceLine,index)=>({...sourceLine,journal_line_id:id(50+index),ledger_line_id:id(60+index)});
const postedLines=packet.proposed_journal.lines.map(actual);
const draftDecisionHash=hashAiAccountingEvidence(packet),draftIdempotency=`draft:${scope.tenantId}:${scope.entityId}:${id(42)}:${draftDecisionHash}`;
const draftEvent=(kind,event_id)=>{const payload={action:`${kind}_DRAFT_CREATE`,actor_id:'maker',actual_revision:1,company_code:'WBPA',decision_packet_hash:draftDecisionHash,entity_id:scope.entityId,expected_revision:0,idempotency_key:draftIdempotency,journal_entry_id:id(42),period_id:scope.accountingPeriodId,tenant_id:scope.tenantId};return {event_id,event_hash:hashAiAccountingEvidence(payload),payload};};
const draftGrantPayload={actor_id:'maker',actor_type:'HUMAN',company_code:'WBPA',entity_id:scope.entityId,permission:'GL.JE.CREATE',period_id:scope.accountingPeriodId,role:'AP_PREPARER',status:'APPROVED',tenant_id:scope.tenantId};
const receiptPayload={decision_packet_id:id(40),decision_packet_hash:draftDecisionHash,journal_entry_id:id(42),source_document_id:id(4),source_document_line_id:id(5),created_by:'maker',created_at:'2026-08-20T10:00:00Z',actor_type:'HUMAN',role:'AP_PREPARER',permission:'GL.JE.CREATE',actor_grant:{grant_id:id(119),grant_hash:hashAiAccountingEvidence(draftGrantPayload),payload:draftGrantPayload},expected_revision:0,actual_revision:1,if_match:'revision:0',idempotency_key:draftIdempotency,audit_event:draftEvent('AUDIT',id(78)),outbox_event:draftEvent('OUTBOX',id(79))};
const receipt={decision_packet_id:id(40),decision_packet_hash:hashAiAccountingEvidence(packet),draft_receipt_id:id(41),draft_receipt_hash:hashAiAccountingEvidence(receiptPayload),draft_receipt_payload:receiptPayload,journal_entry_id:id(42),source_document_id:id(4),source_document_line_id:id(5)};
const journal=lines=>({status:'POSTED',journal_entry_id:id(42),journal_number:'JE-2026-0001',entity_id:scope.entityId,company_code:'WBPA',accounting_period_id:scope.accountingPeriodId,prepared_by:'maker',reviewed_by:'reviewer',approved_by:'approver',posted_by:'poster',lines});
const workflow=()=>{let previous=receipt.draft_receipt_hash;return ['SUBMIT','REVIEW','APPROVE','POST'].map((action,index)=>{const actor_id=['maker','reviewer','approver','poster'][index],{role,permission}=workflowPolicy.stages[action],idempotency_key=`workflow:${action}:${scope.tenantId}:${scope.entityId}:${id(42)}:${receipt.decision_packet_hash}`,grantPayload={actor_id,actor_type:'HUMAN',company_code:'WBPA',entity_id:scope.entityId,permission,period_id:scope.accountingPeriodId,role,status:'APPROVED',tenant_id:scope.tenantId},actor_grant={grant_id:id(120+index),grant_hash:hashAiAccountingEvidence(grantPayload),payload:grantPayload},event=(kind,offset)=>{const payload={action:`${kind}_${action}`,actor_id,actual_revision:index+2,company_code:'WBPA',entity_id:scope.entityId,expected_revision:index+1,idempotency_key,journal_entry_id:id(42),period_id:scope.accountingPeriodId,previous_receipt_hash:previous,tenant_id:scope.tenantId};return {event_id:id(offset+index),event_hash:hashAiAccountingEvidence(payload),payload};};const payload={action,actor_id,actor_type:'HUMAN',role,permission,actor_grant,at:`2026-08-20T1${index+1}:00:00Z`,expected_revision:index+1,actual_revision:index+2,if_match:`revision:${index+1}`,idempotency_key,audit_event:event('AUDIT',80),outbox_event:event('OUTBOX',90),decision_packet_hash:receipt.decision_packet_hash,draft_receipt_hash:receipt.draft_receipt_hash,journal_entry_id:id(42),previous_receipt_hash:previous};const item={receipt_id:id(100+index),receipt_hash:hashAiAccountingEvidence(payload),payload};previous=item.receipt_hash;return item;});};
const tb=lines=>{const payload={status:'POSTED_LEDGER_ONLY',snapshot_id:id(70),entity_id:scope.entityId,accounting_period_id:scope.accountingPeriodId,journal_entry_id:id(42),ledger_line_ids:lines.map(row=>row.ledger_line_id),deltas:lines.map(row=>({side:row.side,account_code:row.account_code,account_class:row.account_class,amount:row.amount,currency:row.currency,project_ref:row.project_ref,property_ref:row.property_ref,member_ref:row.member_ref,cost_code_ref:row.cost_code_ref}))};return {...payload,snapshot_hash:hashAiAccountingEvidence(payload)};};
const report=(lines,deltas=[delta,liabilityDelta])=>{const payload={status:'POSTED_LEDGER_ONLY',report_snapshot_id:id(71),trial_balance_snapshot_id:id(70),entity_id:scope.entityId,accounting_period_id:scope.accountingPeriodId,journal_entry_ids:[id(42)],ledger_line_ids:lines.map(row=>row.ledger_line_id),source_document_ids:[id(4)],deltas};return {...payload,report_snapshot_hash:hashAiAccountingEvidence(payload)};};
const review=args=>reviewAiAccountingPostedOutcomeFullV1({workflowReceipts:workflow(),...args});

test('proves exact decision to Draft receipt to Posted JE to ledger/TB to report lineage',()=>{
  const result=review({packet,decisionToDraftReceipt:receipt,postedJournal:journal(postedLines),trialBalanceSnapshot:tb(postedLines),reportSnapshot:report(postedLines)});
  assert.equal(result.status,'CONSISTENT');assert.equal(result.journal_exact,true);assert.equal(result.trial_balance_exact,true);assert.equal(result.report_exact,true);assert.equal(result.unexpected_effect_count,0);assert.deepEqual(result.action_flags,{can_create_draft:false,can_review:false,can_approve:false,can_post:false});
});

test('unexpected or reversed report effects fail as internally inconsistent rather than allowing variance',()=>{
  const extra={...delta,statement:'BALANCE_SHEET',account_code:'999999',account_class:'ASSET'};
  assert.throws(()=>review({packet,decisionToDraftReceipt:receipt,postedJournal:journal(postedLines),trialBalanceSnapshot:tb(postedLines),reportSnapshot:report(postedLines,[delta,liabilityDelta,extra])}),error=>error.code==='AI_ACCOUNTING_OUTCOME_REPORT_INVALID');
  const reversed={...delta,direction:'DECREASE'};
  assert.throws(()=>review({packet,decisionToDraftReceipt:receipt,postedJournal:journal(postedLines),trialBalanceSnapshot:tb(postedLines),reportSnapshot:report(postedLines,[reversed,liabilityDelta])}),error=>error.code==='AI_ACCOUNTING_OUTCOME_REPORT_INVALID');
});

test('rejects unbalanced GL, TB drift, missing receipt lineage, or failed SoD',()=>{
  const unbalanced=[postedLines[0],{...postedLines[1],amount:'99.0000'}];
  assert.throws(()=>review({packet,decisionToDraftReceipt:receipt,postedJournal:journal(unbalanced),trialBalanceSnapshot:tb(unbalanced),reportSnapshot:report(unbalanced)}),error=>error.code==='AI_ACCOUNTING_OUTCOME_POSTED_JOURNAL_INVALID');
  assert.throws(()=>review({packet,decisionToDraftReceipt:receipt,postedJournal:journal(postedLines),trialBalanceSnapshot:{...tb(postedLines),deltas:[]},reportSnapshot:report(postedLines)}),error=>error.code==='AI_ACCOUNTING_OUTCOME_TRIAL_BALANCE_INVALID');
  assert.throws(()=>review({packet,decisionToDraftReceipt:{...receipt,draft_receipt_hash:hash(7)},postedJournal:journal(postedLines),trialBalanceSnapshot:tb(postedLines),reportSnapshot:report(postedLines)}),error=>error.code==='AI_ACCOUNTING_OUTCOME_TRACE_INVALID');
  const sod={...journal(postedLines),posted_by:'approver'};
  assert.throws(()=>review({packet,decisionToDraftReceipt:receipt,postedJournal:sod,trialBalanceSnapshot:tb(postedLines),reportSnapshot:report(postedLines)}),error=>error.code==='AI_ACCOUNTING_OUTCOME_POSTED_JOURNAL_INVALID');
  assert.throws(()=>reviewAiAccountingPostedOutcomeFullV1({packet,decisionToDraftReceipt:receipt,workflowReceipts:[],postedJournal:journal(postedLines),trialBalanceSnapshot:tb(postedLines),reportSnapshot:report(postedLines)}),error=>error.code==='AI_ACCOUNTING_OUTCOME_WORKFLOW_TRACE_INVALID');
  assert.throws(()=>review({packet,decisionToDraftReceipt:receipt,postedJournal:journal(postedLines),trialBalanceSnapshot:{...tb(postedLines),snapshot_hash:hash(99)},reportSnapshot:report(postedLines)}),error=>error.code==='AI_ACCOUNTING_OUTCOME_TRIAL_BALANCE_INVALID');
  assert.throws(()=>review({packet,decisionToDraftReceipt:receipt,postedJournal:journal(postedLines),trialBalanceSnapshot:tb(postedLines),reportSnapshot:{...report(postedLines),report_snapshot_hash:hash(98)}}),error=>error.code==='AI_ACCOUNTING_OUTCOME_REPORT_INVALID');
  const sourceDrift=[{...postedLines[0],source_document_id:id(999)},postedLines[1]];
  assert.throws(()=>review({packet,decisionToDraftReceipt:receipt,postedJournal:journal(sourceDrift),trialBalanceSnapshot:tb(sourceDrift),reportSnapshot:report(sourceDrift)}),error=>error.code==='AI_ACCOUNTING_OUTCOME_POSTED_JOURNAL_INVALID');
  const malformed=[{...postedLines[0],account_class:'NOT_AN_ACCOUNT_CLASS'},postedLines[1]];
  assert.throws(()=>review({packet,decisionToDraftReceipt:receipt,postedJournal:journal(malformed),trialBalanceSnapshot:tb(malformed),reportSnapshot:report(malformed)}),error=>error.code==='AI_ACCOUNTING_OUTCOME_POSTED_JOURNAL_INVALID');
  const aiWorkflow=workflow(),aiPayload={...aiWorkflow[0].payload,actor_type:'AI'};aiWorkflow[0]={...aiWorkflow[0],payload:aiPayload,receipt_hash:hashAiAccountingEvidence(aiPayload)};
  assert.throws(()=>reviewAiAccountingPostedOutcomeFullV1({packet,decisionToDraftReceipt:receipt,workflowReceipts:aiWorkflow,postedJournal:journal(postedLines),trialBalanceSnapshot:tb(postedLines),reportSnapshot:report(postedLines)}),error=>error.code==='AI_ACCOUNTING_OUTCOME_WORKFLOW_TRACE_INVALID');
  const eventWorkflow=workflow(),badEvent={...eventWorkflow[0].payload.audit_event,event_hash:hash(97)},eventPayload={...eventWorkflow[0].payload,audit_event:badEvent};eventWorkflow[0]={...eventWorkflow[0],payload:eventPayload,receipt_hash:hashAiAccountingEvidence(eventPayload)};
  assert.throws(()=>reviewAiAccountingPostedOutcomeFullV1({packet,decisionToDraftReceipt:receipt,workflowReceipts:eventWorkflow,postedJournal:journal(postedLines),trialBalanceSnapshot:tb(postedLines),reportSnapshot:report(postedLines)}),error=>error.code==='AI_ACCOUNTING_OUTCOME_WORKFLOW_TRACE_INVALID');
});

test('rejects caller-asserted Draft and workflow roles, permissions, grant hashes, or grant scope',()=>{
  const withDraftPayload=mutate=>{const draft_receipt_payload=mutate(structuredClone(receipt.draft_receipt_payload));return {...receipt,draft_receipt_payload,draft_receipt_hash:hashAiAccountingEvidence(draft_receipt_payload)};};
  for(const bad of [
    withDraftPayload(payload=>({...payload,role:'PREPARER'})),
    withDraftPayload(payload=>({...payload,actor_grant:{...payload.actor_grant,grant_hash:hash(96)}})),
    withDraftPayload(payload=>{const grantPayload={...payload.actor_grant.payload,entity_id:id(99)};return {...payload,actor_grant:{...payload.actor_grant,payload:grantPayload,grant_hash:hashAiAccountingEvidence(grantPayload)}};})
  ])assert.throws(()=>review({packet,decisionToDraftReceipt:bad,postedJournal:journal(postedLines),trialBalanceSnapshot:tb(postedLines),reportSnapshot:report(postedLines)}),error=>error.code==='AI_ACCOUNTING_OUTCOME_TRACE_INVALID');
  const variants=[
    payload=>({...payload,role:'REVIEWER'}),
    payload=>({...payload,permission:'JOURNAL.SUBMIT'}),
    payload=>({...payload,actor_grant:{...payload.actor_grant,grant_hash:hash(95)}}),
    payload=>{const grantPayload={...payload.actor_grant.payload,tenant_id:id(98)};return {...payload,actor_grant:{...payload.actor_grant,payload:grantPayload,grant_hash:hashAiAccountingEvidence(grantPayload)}};}
  ];
  for(const mutate of variants){const receipts=workflow(),payload=mutate(structuredClone(receipts[0].payload));receipts[0]={...receipts[0],payload,receipt_hash:hashAiAccountingEvidence(payload)};assert.throws(()=>reviewAiAccountingPostedOutcomeFullV1({packet,decisionToDraftReceipt:receipt,workflowReceipts:receipts,postedJournal:journal(postedLines),trialBalanceSnapshot:tb(postedLines),reportSnapshot:report(postedLines)}),error=>error.code==='AI_ACCOUNTING_OUTCOME_WORKFLOW_TRACE_INVALID');}
});

test('rejects impossible or non-canonical Draft and workflow timestamps',()=>{
  const withDraftTime=created_at=>{const draft_receipt_payload={...structuredClone(receipt.draft_receipt_payload),created_at};return {...receipt,draft_receipt_payload,draft_receipt_hash:hashAiAccountingEvidence(draft_receipt_payload)};};
  for(const created_at of ['2026-02-30T10:00:00Z','2026-08-20T10:00:00+00:00'])assert.throws(()=>review({packet,decisionToDraftReceipt:withDraftTime(created_at),postedJournal:journal(postedLines),trialBalanceSnapshot:tb(postedLines),reportSnapshot:report(postedLines)}),error=>error.code==='AI_ACCOUNTING_OUTCOME_TRACE_INVALID');
  for(const at of ['2026-02-30T11:00:00Z','2026-08-20T11:00:00+00:00']){const receipts=workflow(),payload={...receipts[0].payload,at};receipts[0]={...receipts[0],payload,receipt_hash:hashAiAccountingEvidence(payload)};assert.throws(()=>reviewAiAccountingPostedOutcomeFullV1({packet,decisionToDraftReceipt:receipt,workflowReceipts:receipts,postedJournal:journal(postedLines),trialBalanceSnapshot:tb(postedLines),reportSnapshot:report(postedLines)}),error=>error.code==='AI_ACCOUNTING_OUTCOME_WORKFLOW_TRACE_INVALID');}
});

test('keeps a changed approved account as MISMATCH until a formal variance workflow exists',()=>{
  const changed=[{...postedLines[0],account_code:'620000'},postedLines[1]],actualReport=[{...delta,account_code:'620000'},liabilityDelta];
  const expectedLines=packet.proposed_journal.lines,actualLines=changed.map(({journal_line_id,ledger_line_id,...row})=>row);
  const event=(kind,event_id)=>{const eventPayload={actor_id:'controller-variance',decision_packet_hash:hashAiAccountingEvidence(packet),entity_id:scope.entityId,journal_entry_id:id(42),permission:`${kind}_AI_ACCOUNTING_VARIANCE_AUTHORIZE`,tenant_id:scope.tenantId};return {event_id,event_hash:hashAiAccountingEvidence(eventPayload),payload:eventPayload};};
  const payload={status:'HUMAN_AUTHORIZED',permission:'AI.ACCOUNTING.VARIANCE.AUTHORIZE',authorized_by:'controller-variance',authorized_at:'2026-08-20T12:00:00Z',reason:'Controller approved a documented account reclassification.',decision_packet_hash:hashAiAccountingEvidence(packet),expected_journal_hash:hashAiAccountingEvidence(expectedLines),actual_journal_hash:hashAiAccountingEvidence(actualLines),expected_report_hash:hashAiAccountingEvidence(packet.expected_report_deltas),actual_report_hash:hashAiAccountingEvidence(actualReport),expected_journal_revision:7,actual_journal_revision:8,audit_event:event('AUDIT',id(110)),outbox_event:event('OUTBOX',id(111))};
  const variance={variance_receipt_id:id(112),variance_receipt_hash:hashAiAccountingEvidence(payload),payload};
  const result=review({packet,decisionToDraftReceipt:receipt,postedJournal:journal(changed),trialBalanceSnapshot:tb(changed),reportSnapshot:report(changed,actualReport),humanAuthorizedVariance:variance});
  assert.equal(result.status,'MISMATCH');assert.equal(result.journal_exact,false);assert.equal(result.report_exact,false);assert.equal(result.variance_authorized,false);
  const forged={...variance,payload:{...payload,permission:'AI.ANALYSIS.EXPLAIN'}};
  assert.equal(review({packet,decisionToDraftReceipt:receipt,postedJournal:journal(changed),trialBalanceSnapshot:tb(changed),reportSnapshot:report(changed,actualReport),humanAuthorizedVariance:forged}).status,'MISMATCH');
});
