import test from 'node:test';
import assert from 'node:assert/strict';
import {createAiAnalysisExplanationService,AiAnalysisExplanationError} from '../runtime/ai-analysis-explanation-service.mjs';

const summary=[{category:'DUPLICATE_PAYABLE',total_findings:'2',high_findings:'2',medium_findings:'0',low_findings:'0',latest_materialized_at:'2026-08-15T00:00:00Z'}];
const findingId='11111111-1111-4111-8111-111111111111';
const evidence=[{category:'DUPLICATE_PAYABLE',row:{ai_duplicate_payable_finding_id:findingId,risk_level:'HIGH',confidence:'1.0000',rule_id:'DUPLICATE_PAYABLE_EXACT',reason:'Two payable sources have the same supplier, invoice number, currency, and gross amount.',suggested_action:'Compare source evidence before any Draft or payment activity.',source_document_id:'source-1',candidate_source_document_id:'source-2',source_payload_hash:'sha256:'+'1'.repeat(64),candidate_payload_hash:'sha256:'+'2'.repeat(64),source_document_version:'2',candidate_document_version:'3',created_at:'2026-08-15T00:00:00Z'}}];
const modelOutput={traceId:'trace',providerRequestId:'chatcmpl-1',model:'gpt-4.1-mini',elapsedMs:10,result:{headline:'Two duplicate payable findings need review.',risk_level:'HIGH',narrative:'Retained duplicate-payable evidence needs controller review before any payment or Draft activity.',controller_actions:[{category:'DUPLICATE_PAYABLE',finding_ids:[findingId],action:'Compare source evidence and assign a controller.'}]}};
const audit=({state='STARTED',response}={})=>({beginAiAccountingAnalysisExplanation:async input=>({requestHash:'sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',result:state==='REPLAY'?{state,response}:{state}}),completeAiAccountingAnalysisExplanation:async input=>input.output,abandonAiAccountingAnalysisExplanation:async()=>{}});

test('AI analysis explanation sends only retained aggregate and redacted source-traceable finding facts, persists one audit receipt, and cannot grant accounting actions',async()=>{
  let input,begin,complete;const repository={...audit(),beginAiAccountingAnalysisExplanation:async value=>(begin=value,{requestHash:'sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',result:{state:'STARTED'}}),completeAiAccountingAnalysisExplanation:async value=>(complete=value,value.output)};const service=createAiAnalysisExplanationService({summaryReader:async scope=>(assert.deepEqual(scope,{tenantId:'tenant',entityId:'entity'}),summary),evidenceReader:async scope=>(assert.deepEqual(scope,{tenantId:'tenant',entityId:'entity'}),evidence),auditRepository:repository,gateway:{analyzeJson:async value=>(input=value,modelOutput)}});
  const output=await service.explain({tenantId:'tenant',entityId:'entity',actorId:'oidc|controller',traceId:'trace'});assert.equal(input.facts.findings[0].high_findings,2);assert.deepEqual(input.facts.retained_evidence[0].source_refs,['source-1','source-2']);assert.deepEqual(input.facts.retained_evidence[0].evidence_hashes,['sha256:'+'1'.repeat(64),'sha256:'+'2'.repeat(64)]);assert.equal(input.facts.retained_evidence[0].raw_payload,undefined);assert.match(input.systemInstruction,/Do not infer/i);assert.deepEqual(begin.summary,[{...summary[0],total_findings:2,high_findings:2,medium_findings:0,low_findings:0}]);assert.equal(begin.evidence.length,1);assert.equal(begin.evidence[0].finding_id,findingId);assert.deepEqual(complete.output.result.controller_actions[0].finding_ids,[findingId]);assert.equal(complete.output.result.can_post,false);assert.equal(output.result.can_create_draft,false);assert.equal(output.providerRequestId,'chatcmpl-1');
});
test('AI analysis explanation replays a durable receipt without another model request',async()=>{
  let calls=0;const replay={...modelOutput,result:{...modelOutput.result,can_create_draft:false,can_review:false,can_approve:false,can_post:false}};const service=createAiAnalysisExplanationService({summaryReader:async()=>summary,evidenceReader:async()=>evidence,auditRepository:audit({state:'REPLAY',response:replay}),gateway:{analyzeJson:async()=>{calls++;throw new Error('must not call');}}});assert.deepEqual(await service.explain({tenantId:'t',entityId:'e',actorId:'a',traceId:'replay-01'}),replay);assert.equal(calls,0);
});
test('AI analysis explanation fails closed for absent durable audit, malformed summary, in-progress receipt, or action-enabled model output',async()=>{
  assert.throws(()=>createAiAnalysisExplanationService({summaryReader:async()=>[],gateway:{analyzeJson:async()=>({})}}),AiAnalysisExplanationError);const invalid=createAiAnalysisExplanationService({summaryReader:async()=>[{...summary[0],high_findings:'1'}],evidenceReader:async()=>evidence,auditRepository:audit(),gateway:{analyzeJson:async()=>({})}});await assert.rejects(()=>invalid.explain({tenantId:'t',entityId:'e',actorId:'a',traceId:'invalid-1'}),error=>error.code==='AI_ANALYSIS_SUMMARY_INVALID');const invalidEvidence=createAiAnalysisExplanationService({summaryReader:async()=>summary,evidenceReader:async()=>[{category:'DUPLICATE_PAYABLE',row:{token:'do-not-send'}}],auditRepository:audit(),gateway:{analyzeJson:async()=>({})}});await assert.rejects(()=>invalidEvidence.explain({tenantId:'t',entityId:'e',actorId:'a',traceId:'invalid-evidence'}),error=>error.code==='AI_ANALYSIS_EVIDENCE_INVALID');const running=createAiAnalysisExplanationService({summaryReader:async()=>summary,evidenceReader:async()=>evidence,auditRepository:audit({state:'IN_PROGRESS'}),gateway:{analyzeJson:async()=>({})}});await assert.rejects(()=>running.explain({tenantId:'t',entityId:'e',actorId:'a',traceId:'running-1'}),error=>error.code==='AI_ANALYSIS_IN_PROGRESS');const untraceable=createAiAnalysisExplanationService({summaryReader:async()=>summary,evidenceReader:async()=>evidence,auditRepository:audit(),gateway:{analyzeJson:async()=>({result:{...modelOutput.result,controller_actions:[{category:'DUPLICATE_PAYABLE',finding_ids:['22222222-2222-4222-8222-222222222222'],action:'Unsupported citation.'}]}})}});await assert.rejects(()=>untraceable.explain({tenantId:'t',entityId:'e',actorId:'a',traceId:'bad-citation'}),error=>error.code==='AI_ANALYSIS_RESPONSE_INVALID');const unsafe=createAiAnalysisExplanationService({summaryReader:async()=>summary,evidenceReader:async()=>evidence,auditRepository:audit(),gateway:{analyzeJson:async()=>({result:{headline:'x',risk_level:'HIGH',narrative:'x',controller_actions:[],can_post:true}})}});await assert.rejects(()=>unsafe.explain({tenantId:'t',entityId:'e',actorId:'a',traceId:'unsafe-1'}),error=>error.code==='AI_ANALYSIS_RESPONSE_INVALID');
});
