import assert from 'node:assert/strict';import test from 'node:test';import {createAccountingApi} from '../api/accounting-http.mjs';
const id=n=>`${String(n).padStart(8,'0')}-0000-4000-8000-${String(n).padStart(12,'0')}`,tenantId=id(1),entityId=id(2),hash='sha256:'+'a'.repeat(64);
const row={tenant_id:tenantId,entity_id:entityId,business_document_id:id(3),source_document_id:id(4),source_payload_hash:hash,posted_journal_entry_id:id(5),movement_kind:'AP_BILL',document_number:'INV-100',vendor_ref:'V-1',vendor_name:'Vendor One',currency:'USD',aging_date:'2026-04-01',open_amount:'500.0000'};
const policy={setting_snapshot_id:id(6),setting_snapshot_hash:hash,policy_version:1,stale_days:90,minimum_open_amount:'100.0000'};
const apiFor=kernel=>createAccountingApi({authenticate:async()=>({trusted:true,tenantId,actorId:'oidc|controller'}),kernelFactory:async()=>kernel});
test('HTTP AP aging risk reads authoritative policy and source, is no-store, accountable, and action-free',async()=>{const calls=[],response=await apiFor({getAiApAgingRiskSource:async scope=>(calls.push(scope),[row]),getAiApAgingRiskPolicy:async scope=>(calls.push(scope),policy)})({method:'GET',url:`/api/v1/entities/${entityId}/ai/reports/ap-aging-risk?asOf=2026-08-01&limit=25`,headers:{},body:null});assert.equal(response.status,200,JSON.stringify(response.body));assert.equal(response.headers['cache-control'],'no-store');assert.deepEqual(calls,[{tenantId,entityId,asOfDate:'2026-08-01'},{tenantId,entityId,asOfDate:'2026-08-01'}]);assert.equal(response.body.data.finding_count,1);assert.equal(response.body.data.findings[0].finding_type,'STALE_PAYABLE');assert.equal(response.body.data.findings[0].confidence,0.95);assert.equal(response.body.data.findings[0].owner_role,'AP_CONTROLLER_REVIEW');assert.equal(response.body.data.findings[0].due_basis,'BEFORE_AP_CLOSE');assert.deepEqual(response.body.data.action_flags,{can_create_draft:false,can_review:false,can_approve:false,can_post:false});});
test('HTTP AP aging risk rejects command semantics, unknown query, body, and missing policy',async()=>{const kernel={getAiApAgingRiskSource:async()=>[row],getAiApAgingRiskPolicy:async()=>policy},api=apiFor(kernel);for(const request of [{headers:{'if-match':'x'},body:null,url:`/api/v1/entities/${entityId}/ai/reports/ap-aging-risk?asOf=2026-08-01`},{headers:{},body:null,url:`/api/v1/entities/${entityId}/ai/reports/ap-aging-risk?asOf=2026-08-01&extra=true`},{headers:{},body:{},url:`/api/v1/entities/${entityId}/ai/reports/ap-aging-risk?asOf=2026-08-01`}])assert.equal((await api({method:'GET',...request})).status,400);assert.equal((await apiFor({...kernel,getAiApAgingRiskPolicy:async()=>null})({method:'GET',url:`/api/v1/entities/${entityId}/ai/reports/ap-aging-risk?asOf=2026-08-01`,headers:{},body:null})).status,409);});
test('HTTP AP aging risk returns no-store 503 instead of a silently truncated batch',async()=>{const second={...row,business_document_id:id(10),posted_journal_entry_id:id(11),document_number:'INV-101'},response=await apiFor({getAiApAgingRiskSource:async()=>[row,second],getAiApAgingRiskPolicy:async()=>policy})({method:'GET',url:`/api/v1/entities/${entityId}/ai/reports/ap-aging-risk?asOf=2026-08-01&limit=1`,headers:{},body:null});assert.equal(response.status,503);assert.equal(response.headers['cache-control'],'no-store');assert.equal(response.body.code,'AI_AP_AGING_FINDING_POPULATION_INCOMPLETE');});
test('HTTP AP aging risk rejects credential-shaped values inside allowed source and policy fields',async()=>{const credential=['Be','arer ','ap-aging-secret'].join('');for(const kernel of [{getAiApAgingRiskSource:async()=>[{...row,vendor_name:credential}],getAiApAgingRiskPolicy:async()=>policy},{getAiApAgingRiskSource:async()=>[row],getAiApAgingRiskPolicy:async()=>({...policy,setting_snapshot_hash:credential})}]){const response=await apiFor(kernel)({method:'GET',url:`/api/v1/entities/${entityId}/ai/reports/ap-aging-risk?asOf=2026-08-01`,headers:{},body:null});assert.equal(response.status,502);assert.equal(response.headers['cache-control'],'no-store');assert.equal(response.body.code,'AI_AP_AGING_RISK_RESPONSE_INVALID');}});
