import test from 'node:test';
import assert from 'node:assert/strict';
import {createAiAnalysisExplanationService,AiAnalysisExplanationError} from '../runtime/ai-analysis-explanation-service.mjs';

const summary=[{category:'DUPLICATE_PAYABLE',total_findings:'2',high_findings:'2',medium_findings:'0',low_findings:'0',latest_materialized_at:'2026-08-15T00:00:00Z'}];
const findingId='11111111-1111-4111-8111-111111111111';
const evidence=[{category:'DUPLICATE_PAYABLE',row:{ai_duplicate_payable_finding_id:findingId,risk_level:'HIGH',confidence:'1.0000',rule_id:'DUPLICATE_PAYABLE_EXACT',reason:'Two payable sources have the same supplier, invoice number, currency, and gross amount.',suggested_action:'Compare source evidence before any Draft or payment activity.',source_document_id:'source-1',candidate_source_document_id:'source-2',source_payload_hash:'sha256:'+'1'.repeat(64),candidate_payload_hash:'sha256:'+'2'.repeat(64),source_document_version:'2',candidate_document_version:'3',created_at:'2026-08-15T00:00:00Z'}}];
const modelOutput={traceId:'trace',providerRequestId:'chatcmpl-1',model:'gpt-4.1-mini',elapsedMs:10,result:{headline:'Two duplicate payable findings need review.',risk_level:'HIGH',narrative:'Retained duplicate-payable evidence needs controller review before any payment or Draft activity.',controller_actions:[{category:'DUPLICATE_PAYABLE',finding_ids:[findingId],action:'Compare source evidence and assign a controller.'}]}};
const audit=({state='STARTED',response}={})=>({beginAiAccountingAnalysisExplanation:async input=>({requestHash:'sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',result:state==='REPLAY'?{state,response}:{state}}),completeAiAccountingAnalysisExplanation:async input=>input.output,abandonAiAccountingAnalysisExplanation:async()=>{}});

test('AI analysis explanation sends only retained aggregate and redacted source-traceable finding facts, persists one audit receipt, and cannot grant accounting actions',async()=>{
  let input,begin,complete;const repository={...audit(),beginAiAccountingAnalysisExplanation:async value=>(begin=value,{requestHash:'sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',result:{state:'STARTED'}}),completeAiAccountingAnalysisExplanation:async value=>(complete=value,value.output)};const service=createAiAnalysisExplanationService({summaryReader:async scope=>(assert.deepEqual(scope,{tenantId:'tenant',entityId:'entity'}),summary),evidenceReader:async scope=>(assert.deepEqual(scope,{tenantId:'tenant',entityId:'entity'}),evidence),auditRepository:repository,gateway:{analyzeJson:async value=>(input=value,modelOutput)}});
  const output=await service.explain({tenantId:'tenant',entityId:'entity',actorId:'oidc|controller',traceId:'trace'});assert.equal(input.facts.findings[0].high_findings,2);assert.deepEqual(input.facts.retained_evidence[0].source_refs,['source-1','source-2']);assert.deepEqual(input.facts.retained_evidence[0].evidence_hashes,['sha256:'+'1'.repeat(64),'sha256:'+'2'.repeat(64)]);assert.equal(input.facts.retained_evidence[0].raw_payload,undefined);assert.match(input.systemInstruction,/Do not infer/i);assert.deepEqual(begin.summary,[{...summary[0],total_findings:2,high_findings:2,medium_findings:0,low_findings:0}]);assert.equal(begin.evidence.length,1);assert.equal(begin.evidence[0].finding_id,findingId);assert.deepEqual(complete.output.result.controller_actions[0].finding_ids,[findingId]);assert.equal(complete.output.result.can_post,false);assert.equal(output.result.can_create_draft,false);assert.equal(output.providerRequestId,'chatcmpl-1');
});
test('AI analysis accepts a retained duplicate bank-payment pair without exposing payment authority',async()=>{
  const bankId='22222222-2222-4222-8222-222222222222',bankSummary=[{category:'BANK_DUPLICATE_PAYMENT',total_findings:'1',high_findings:'0',medium_findings:'1',low_findings:'0',latest_materialized_at:'2026-08-19T00:00:00Z'}],bankEvidence=[{category:'BANK_DUPLICATE_PAYMENT',row:{ai_bank_duplicate_payment_finding_id:bankId,risk_level:'MEDIUM',confidence:'0.9',rule_id:'AI_BANK_SAME_DAY_SAME_AMOUNT_PAYMENT_V1',reason:'Two admitted bank payments share the exact account, date, currency, and amount.',suggested_action:'Compare invoice, approval, bank memo, and reversal evidence.',source_document_id:'33333333-3333-4333-8333-333333333333',candidate_source_document_id:'44444444-4444-4444-8444-444444444444',external_bank_line_id:'BANK-1',source_payload_hash:'sha256:'+'3'.repeat(64),candidate_payload_hash:'sha256:'+'4'.repeat(64),match_key_hash:'sha256:'+'5'.repeat(64),created_at:'2026-08-19T00:00:00Z'}}],bankOutput={...modelOutput,result:{headline:'Duplicate bank-payment evidence needs review.',risk_level:'MEDIUM',narrative:'The retained payment pair requires Controller review.',controller_actions:[{category:'BANK_DUPLICATE_PAYMENT',finding_ids:[bankId],action:'Compare both signed payment sources.'}]}};
  let facts;const service=createAiAnalysisExplanationService({summaryReader:async()=>bankSummary,evidenceReader:async()=>bankEvidence,auditRepository:audit(),gateway:{analyzeJson:async input=>(facts=input.facts,bankOutput)}});const output=await service.explain({tenantId:'tenant',entityId:'entity',actorId:'oidc|controller',traceId:'bank-duplicate-01'});assert.equal(facts.retained_evidence[0].finding_id,bankId);assert.equal(facts.retained_evidence[0].category,'BANK_DUPLICATE_PAYMENT');assert.equal(output.result.can_create_draft,false);assert.equal(output.result.can_post,false);
});
test('AI analysis accepts vendor variance and manual-JE risk as redacted source-bound evidence',async()=>{
  const vendorId='55555555-5555-4555-8555-555555555555',journalId='66666666-6666-4666-8666-666666666666';const anomalySummary=[{category:'VENDOR_INVOICE_AMOUNT_SPIKE',total_findings:'1',high_findings:'1',medium_findings:'0',low_findings:'0',latest_materialized_at:'2026-08-19T00:00:00Z'},{category:'MANUAL_JOURNAL_RISK',total_findings:'1',high_findings:'1',medium_findings:'0',low_findings:'0',latest_materialized_at:'2026-08-19T00:00:00Z'}];const anomalyEvidence=[{category:'VENDOR_INVOICE_AMOUNT_SPIKE',row:{ai_vendor_invoice_amount_anomaly_finding_id:vendorId,risk_level:'HIGH',confidence:'0.9',rule_id:'AI_VENDOR_HISTORICAL_AMOUNT_SPIKE_V1',reason:'Current invoice is five times the retained historical median.',suggested_action:'Review invoice, contract, quantity, rate, duplicate status, and coding.',source_document_id:'77777777-7777-4777-8777-777777777777',source_document_line_id:'88888888-8888-4888-8888-888888888888',source_payload_hash:'sha256:'+'6'.repeat(64),source_line_hash:'sha256:'+'7'.repeat(64),created_at:'2026-08-19T00:00:00Z'}},{category:'MANUAL_JOURNAL_RISK',row:{ai_manual_journal_risk_finding_id:journalId,risk_level:'HIGH',confidence:'0.95',rule_id:'AI_MANUAL_JOURNAL_RISK',reason:'Large round-dollar manual Journal lacks source support.',suggested_action:'Require independent Controller review before further workflow.',journal_entry_id:'99999999-9999-4999-8999-999999999999',finding_hash:'sha256:'+'8'.repeat(64),created_at:'2026-08-19T00:00:00Z'}}];const anomalyOutput={...modelOutput,result:{headline:'Two accounting anomalies require review.',risk_level:'HIGH',narrative:'Retained variance and manual Journal evidence require human conclusions.',controller_actions:[{category:'VENDOR_INVOICE_AMOUNT_SPIKE',finding_ids:[vendorId],action:'Review the vendor amount variance.'},{category:'MANUAL_JOURNAL_RISK',finding_ids:[journalId],action:'Review the manual Journal support.'}]}};let facts;const service=createAiAnalysisExplanationService({summaryReader:async()=>anomalySummary,evidenceReader:async()=>anomalyEvidence,auditRepository:audit(),gateway:{analyzeJson:async input=>(facts=input.facts,anomalyOutput)}});const output=await service.explain({tenantId:'tenant',entityId:'entity',actorId:'oidc|controller',traceId:'full-anomaly-01'});assert.deepEqual(facts.retained_evidence.map(item=>item.category),['VENDOR_INVOICE_AMOUNT_SPIKE','MANUAL_JOURNAL_RISK']);assert.deepEqual(facts.retained_evidence[1].source_refs,['99999999-9999-4999-8999-999999999999']);assert.deepEqual(facts.retained_evidence[1].evidence_hashes,['sha256:'+'8'.repeat(64)]);assert.equal(output.result.can_post,false);
});
test('AI analysis explanation redacts credential-like text before model and durable audit receipt boundaries',async()=>{
  let input,begin;const secret='sk-live-EXAMPLECREDENTIAL';const unsafeEvidence=[{category:'DUPLICATE_PAYABLE',row:{...evidence[0].row,reason:`Provider note token=${secret} must never leave the retained evidence boundary.`,suggested_action:`Use Authorization: Bearer ${secret} only for local investigation.`}}];
  const repository={...audit(),beginAiAccountingAnalysisExplanation:async value=>(begin=value,{requestHash:'sha256:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa',result:{state:'STARTED'}})};
  const service=createAiAnalysisExplanationService({summaryReader:async()=>summary,evidenceReader:async()=>unsafeEvidence,auditRepository:repository,gateway:{analyzeJson:async value=>(input=value,modelOutput)}});
  await service.explain({tenantId:'tenant',entityId:'entity',actorId:'oidc|controller',traceId:'redaction-01'});
  assert.doesNotMatch(JSON.stringify(input.facts),new RegExp(secret));assert.doesNotMatch(JSON.stringify(begin.evidence),new RegExp(secret));assert.match(input.facts.retained_evidence[0].reason,/token=\[REDACTED\]/);assert.match(input.facts.retained_evidence[0].suggested_action,/Authorization=\[REDACTED\]/);
});
test('AI analysis explanation redacts credential-like model output before it becomes a durable report',async()=>{
  let completed;const secret='sk-live-MODELREPLYSECRET';const unsafeOutput={...modelOutput,result:{...modelOutput.result,headline:`Controller memo token=${secret}`,narrative:`Do not retain Authorization: Bearer ${secret}.`,controller_actions:[{...modelOutput.result.controller_actions[0],action:`Review secret=${secret} only in the original secured evidence.`}]}};
  const repository={...audit(),completeAiAccountingAnalysisExplanation:async value=>(completed=value.output,value.output)};
  const service=createAiAnalysisExplanationService({summaryReader:async()=>summary,evidenceReader:async()=>evidence,auditRepository:repository,gateway:{analyzeJson:async()=>unsafeOutput}});
  const output=await service.explain({tenantId:'tenant',entityId:'entity',actorId:'oidc|controller',traceId:'redaction-output-01'});
  assert.doesNotMatch(JSON.stringify(completed),new RegExp(secret));assert.doesNotMatch(JSON.stringify(output),new RegExp(secret));assert.match(output.result.headline,/token=\[REDACTED\]/);assert.match(output.result.narrative,/Authorization=\[REDACTED\]/);assert.match(output.result.controller_actions[0].action,/secret=\[REDACTED\]/);
});
test('AI analysis explanation replays a durable receipt without another model request',async()=>{
  let calls=0;const replay={...modelOutput,result:{...modelOutput.result,can_create_draft:false,can_review:false,can_approve:false,can_post:false}};const service=createAiAnalysisExplanationService({summaryReader:async()=>summary,evidenceReader:async()=>evidence,auditRepository:audit({state:'REPLAY',response:replay}),gateway:{analyzeJson:async()=>{calls++;throw new Error('must not call');}}});assert.deepEqual(await service.explain({tenantId:'t',entityId:'e',actorId:'a',traceId:'replay-01'}),replay);assert.equal(calls,0);
});
test('AI analysis explanation does not reserve an audit receipt or call a model when retained evidence is empty',async()=>{
  let beginCalls=0,gatewayCalls=0;
  const service=createAiAnalysisExplanationService({summaryReader:async()=>[],evidenceReader:async()=>[],auditRepository:{...audit(),beginAiAccountingAnalysisExplanation:async()=>{beginCalls++;throw new Error('must not reserve');}},gateway:{analyzeJson:async()=>{gatewayCalls++;throw new Error('must not call');}}});
  await assert.rejects(()=>service.explain({tenantId:'t',entityId:'e',actorId:'a',traceId:'empty-evidence-01'}),error=>error.code==='AI_ANALYSIS_EVIDENCE_EMPTY');
  assert.equal(beginCalls,0);assert.equal(gatewayCalls,0);
});
test('AI analysis explanation fails closed for absent durable audit, malformed summary, in-progress receipt, or action-enabled model output',async()=>{
  assert.throws(()=>createAiAnalysisExplanationService({summaryReader:async()=>[],gateway:{analyzeJson:async()=>({})}}),AiAnalysisExplanationError);const invalid=createAiAnalysisExplanationService({summaryReader:async()=>[{...summary[0],high_findings:'1'}],evidenceReader:async()=>evidence,auditRepository:audit(),gateway:{analyzeJson:async()=>({})}});await assert.rejects(()=>invalid.explain({tenantId:'t',entityId:'e',actorId:'a',traceId:'invalid-1'}),error=>error.code==='AI_ANALYSIS_SUMMARY_INVALID');const invalidEvidence=createAiAnalysisExplanationService({summaryReader:async()=>summary,evidenceReader:async()=>[{category:'DUPLICATE_PAYABLE',row:{token:'do-not-send'}}],auditRepository:audit(),gateway:{analyzeJson:async()=>({})}});await assert.rejects(()=>invalidEvidence.explain({tenantId:'t',entityId:'e',actorId:'a',traceId:'invalid-evidence'}),error=>error.code==='AI_ANALYSIS_EVIDENCE_INVALID');const running=createAiAnalysisExplanationService({summaryReader:async()=>summary,evidenceReader:async()=>evidence,auditRepository:audit({state:'IN_PROGRESS'}),gateway:{analyzeJson:async()=>({})}});await assert.rejects(()=>running.explain({tenantId:'t',entityId:'e',actorId:'a',traceId:'running-1'}),error=>error.code==='AI_ANALYSIS_IN_PROGRESS');const untraceable=createAiAnalysisExplanationService({summaryReader:async()=>summary,evidenceReader:async()=>evidence,auditRepository:audit(),gateway:{analyzeJson:async()=>({result:{...modelOutput.result,controller_actions:[{category:'DUPLICATE_PAYABLE',finding_ids:['22222222-2222-4222-8222-222222222222'],action:'Unsupported citation.'}]}})}});await assert.rejects(()=>untraceable.explain({tenantId:'t',entityId:'e',actorId:'a',traceId:'bad-citation'}),error=>error.code==='AI_ANALYSIS_RESPONSE_INVALID');const unsafe=createAiAnalysisExplanationService({summaryReader:async()=>summary,evidenceReader:async()=>evidence,auditRepository:audit(),gateway:{analyzeJson:async()=>({result:{headline:'x',risk_level:'HIGH',narrative:'x',controller_actions:[],can_post:true}})}});await assert.rejects(()=>unsafe.explain({tenantId:'t',entityId:'e',actorId:'a',traceId:'unsafe-1'}),error=>error.code==='AI_ANALYSIS_RESPONSE_INVALID');
});
