import assert from 'node:assert/strict';
import test from 'node:test';
import {detectUnusualBankPayments} from '../runtime/ai-bank-unusual-payment.mjs';
const id=n=>`${String(n).padStart(8,'0')}-1111-4111-8111-111111111111`;
const hash=n=>`sha256:${String(n).padStart(64,'a').slice(-64)}`;
const period=id(2);
const policy={schema_version:'AI_BANK_UNUSUAL_PAYMENT_POLICY_V1',setting_snapshot_id:id(3),setting_snapshot_hash:hash('b'),policy_version:1,minimum_absolute_payment:'1000.0000',weekend_days:[0,6],holiday_dates:['2026-07-04']};
const row=(overrides={})=>({bank_source_id:id(10),source_document_id:id(11),source_document_line_id:id(12),source_payload_hash:hash('c'),source_line_hash:hash('d'),entity_id:id(1),accounting_period_id:period,bank_account_ref:'111000-CASH',external_bank_line_id:'BANK-LINE-1',transaction_date:'2026-07-04',currency:'USD',amount:'-5000.0000',counterparty_name:'Example Vendor',bank_memo:'Emergency service payment',source_admission_status:'ADMITTED',signature_verified:true,...overrides});

test('flags a material weekend and approved-holiday payment with immutable source and no accounting authority',()=>{const result=detectUnusualBankPayments([row()],{currentAccountingPeriodId:period,policy});assert.equal(result.finding_count,1);const finding=result.findings[0];assert.deepEqual(finding.rule_ids,['BANK_PAYMENT_WEEKEND_DATE','BANK_PAYMENT_APPROVED_HOLIDAY_DATE']);assert.equal(finding.risk_level,'HIGH');assert.equal(finding.source_trace.source_document_line_id,id(12));assert.equal(finding.policy_evidence.setting_snapshot_hash,policy.setting_snapshot_hash);assert.deepEqual(finding.action_flags,{can_create_draft:false,can_review:false,can_approve:false,can_post:false});});
test('does not flag ordinary business-day, immaterial, incoming, or other-period activity',()=>{const ordinary=row({transaction_date:'2026-07-06'}),small=row({bank_source_id:id(20),external_bank_line_id:'BANK-LINE-2',amount:'-999.0000'}),other=row({bank_source_id:id(21),external_bank_line_id:'BANK-LINE-3',accounting_period_id:id(9)});assert.equal(detectUnusualBankPayments([ordinary,small,other],{currentAccountingPeriodId:period,policy}).finding_count,0);assert.throws(()=>detectUnusualBankPayments([row({amount:'5000.0000'})],{currentAccountingPeriodId:period,policy}),error=>error.code==='AI_BANK_UNUSUAL_PAYMENT_SOURCE_INVALID');});
test('uses only the approved calendar and keeps weekend-only or holiday-only findings review-only',()=>{const weekend=row({transaction_date:'2026-07-05'}),holiday=row({bank_source_id:id(20),external_bank_line_id:'BANK-LINE-2',transaction_date:'2026-07-03'}),holidayPolicy={...policy,holiday_dates:['2026-07-03']};const result=detectUnusualBankPayments([weekend,holiday],{currentAccountingPeriodId:period,policy:holidayPolicy});assert.equal(result.finding_count,2);assert.deepEqual(result.findings.map(item=>item.rule_ids),[['BANK_PAYMENT_WEEKEND_DATE'],['BANK_PAYMENT_APPROVED_HOLIDAY_DATE']]);assert.ok(result.findings.every(item=>item.risk_level==='MEDIUM'&&Object.values(item.action_flags).every(value=>value===false)));});
test('fails closed on unsigned evidence, malformed hashes, duplicate policy dates, or missing policy',()=>{assert.throws(()=>detectUnusualBankPayments([row({signature_verified:false})],{currentAccountingPeriodId:period,policy}),error=>error.code==='AI_BANK_UNUSUAL_PAYMENT_SOURCE_INVALID');assert.throws(()=>detectUnusualBankPayments([row({source_line_hash:'sha256:no'})],{currentAccountingPeriodId:period,policy}),error=>error.code==='AI_BANK_UNUSUAL_PAYMENT_SOURCE_INVALID');assert.throws(()=>detectUnusualBankPayments([],{currentAccountingPeriodId:period,policy:{...policy,holiday_dates:['2026-07-04','2026-07-04']}}),error=>error.code==='AI_BANK_UNUSUAL_PAYMENT_POLICY_REQUIRED');assert.throws(()=>detectUnusualBankPayments([],{currentAccountingPeriodId:period}),error=>error.code==='AI_BANK_UNUSUAL_PAYMENT_POLICY_REQUIRED');});
