import assert from 'node:assert/strict';
import fs from 'node:fs';
import test from 'node:test';
const up=fs.readFileSync(new URL('../db/migrations/220_ai_bank_unusual_payment_review.sql',import.meta.url),'utf8');
const down=fs.readFileSync(new URL('../db/migrations/down/220_ai_bank_unusual_payment_review.sql',import.meta.url),'utf8');
const repository=fs.readFileSync(new URL('../runtime/kernel-repository.mjs',import.meta.url),'utf8');
test('migration 212 exposes only admitted signed bank lines with immutable line hashes',()=>{for(const token of ['refs_read_ai_bank_unusual_payment_sources','refs_assert_ai_analysis_scope','source_document_line_id','source_payload_hash','source_line_hash','AI_BANK_PAYMENT_SOURCE_LINE_V1',"receipt.signature_verified=true","receipt.admission_status='ADMITTED'",'bank.amount<0'])assert.match(up,new RegExp(token.replace(/[.*+?^${}()|[\]\\]/g,'\\$&'),'i'));assert.match(up,/JOIN source_document_line line[\s\S]*line\.source_document_line_id=bank\.source_line_id/i);});
test('policy is approved, hash-bound, period-effective, bounded, and fail closed',()=>{for(const token of ['AI_BANK_UNUSUAL_PAYMENT_POLICY','AI_BANK_UNUSUAL_PAYMENT_POLICY_SNAPSHOT_V1','AI_BANK_UNUSUAL_PAYMENT_REVIEW_V1','refs_jsonb_hash','setting_snapshot_hash','weekend_days','holiday_dates','minimum_absolute_payment','policy scope is ambiguous','malformed or hash-invalid'])assert.match(up,new RegExp(token,'i'));assert.match(up,/status='APPROVED'/);});
test('repository methods are read-only and rollback removes only migration 212 functions',()=>{assert.match(repository,/async listAiBankUnusualPaymentSources[\s\S]*refs_read_ai_bank_unusual_payment_sources/);assert.match(repository,/async getAiBankUnusualPaymentPolicy[\s\S]*refs_read_ai_bank_unusual_payment_policy/);const section=repository.slice(repository.indexOf('async listAiBankUnusualPaymentSources'),repository.indexOf('async materializeAiBankDuplicatePayments'));assert.doesNotMatch(section,/INSERT|UPDATE|DELETE|materialize/i);assert.match(down,/DROP FUNCTION IF EXISTS refs_read_ai_bank_unusual_payment_sources/);assert.match(down,/DROP FUNCTION IF EXISTS refs_read_ai_bank_unusual_payment_policy/);});
