import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {createAccountingApi} from '../api/accounting-http.mjs';import {detectBankGlBalanceReconciliationReviews} from '../runtime/ai-bank-gl-balance-reconciliation.mjs';
const entity=randomUUID(),period=randomUUID(),hash=`sha256:${'a'.repeat(64)}`;
const row=(change={})=>({evidence_status:'SIGNED_STATEMENT_AND_POSTED_GL',period_id:period,reconciliation_id:randomUUID(),wbs_bank_statement_receipt_id:randomUUID(),bank_account_ref:'BANK-OPERATING-1',statement_start_date:'2026-01-01',statement_ending_date:'2026-01-31',currency:'USD',statement_opening_balance:'1000.0000',statement_ending_balance:'1500.0000',book_ending_balance:'1000.0000',difference:'500.0000',statement_payload_hash:hash,admission_hash:hash,signature_algorithm:'Ed25519',signature_verified:true,admission_status:'ADMITTED',reconciliation_status:'IN_REVIEW',reconciliation_version:2,journal_entry_ids:[randomUUID()],journal_line_ids:[randomUUID()],ledger_line_ids:[randomUUID()],...change});
test('flags signed statement versus Posted GL difference with accountable no-action evidence',()=>{const result=detectBankGlBalanceReconciliationReviews([row()],{entityId:entity,accountingPeriodId:period});assert.equal(result.finding_count,1);assert.equal(result.findings[0].risk_level,'HIGH');assert.equal(result.findings[0].confidence,0.99);assert.equal(result.findings[0].owner_role,'CONTROLLER_REVIEW');assert.equal(result.findings[0].due_basis,'BEFORE_BANK_RECONCILIATION_CLOSE');assert.deepEqual(result.action_flags,{can_create_draft:false,can_review:false,can_approve:false,can_post:false});assert.match(result.findings[0].reason,/differs from source-bound Posted GL/);});
test('does not flag an exact signed-off reconciliation',()=>{assert.equal(detectBankGlBalanceReconciliationReviews([row({book_ending_balance:'1500.0000',difference:'0.0000',reconciliation_status:'RECONCILED'})],{entityId:entity,accountingPeriodId:period}).finding_count,0);});
test('keeps a zero-difference unfinished reconciliation in human review',()=>{const result=detectBankGlBalanceReconciliationReviews([row({book_ending_balance:'1500.0000',difference:'0.0000',reconciliation_status:'DRAFT'})],{entityId:entity,accountingPeriodId:period});assert.equal(result.finding_count,1);assert.equal(result.findings[0].risk_level,'MEDIUM');});
test('fails closed for unsigned, unscoped, impossible-date, extra-field, inconsistent, or lineage-free evidence',()=>{for(const changed of [{signature_verified:false},{statement_payload_hash:null},{period_id:randomUUID()},{evidence_status:'UNBOUND'},{statement_start_date:'2026-02-30'},{statement_start_date:'2026-02-01',statement_ending_date:'2026-01-31'},{authorization:'Bearer secret'},{journal_entry_ids:[]},{journal_line_ids:[]},{ledger_line_ids:[]}])assert.throws(()=>detectBankGlBalanceReconciliationReviews([row(changed)],{entityId:entity,accountingPeriodId:period}),error=>error.code==='AI_BANK_GL_RECONCILIATION_EVIDENCE_INVALID');assert.throws(()=>detectBankGlBalanceReconciliationReviews([row({difference:'499.0000'})],{entityId:entity,accountingPeriodId:period}),error=>error.code==='AI_BANK_GL_RECONCILIATION_DIFFERENCE_INVALID');});
test('rejects duplicate reconciliation, bank-account, or signed-receipt populations',()=>{const a=row();for(const duplicate of [{...a},{...row(),bank_account_ref:a.bank_account_ref},{...row(),wbs_bank_statement_receipt_id:a.wbs_bank_statement_receipt_id}])assert.throws(()=>detectBankGlBalanceReconciliationReviews([a,duplicate],{entityId:entity,accountingPeriodId:period}),error=>error.code==='AI_BANK_GL_RECONCILIATION_DUPLICATE');});
test('fails closed and returns no-store 503 instead of hiding additional bank reconciliation findings',async()=>{const rows=[row(),row({bank_account_ref:'BANK-OPERATING-2'})];assert.throws(()=>detectBankGlBalanceReconciliationReviews(rows,{entityId:entity,accountingPeriodId:period,limit:1}),error=>error.code==='AI_BANK_GL_RECONCILIATION_FINDING_POPULATION_INCOMPLETE');const tenantId=randomUUID(),api=createAccountingApi({authenticate:async()=>({trusted:true,tenantId,actorId:'controller'}),kernelFactory:async()=>({getAiBankGlBalanceReconciliation:async()=>rows})}),response=await api({method:'GET',url:`/api/v1/entities/${entity}/ai/bank/gl-balance-reconciliation?periodId=${period}&limit=1`,headers:{},body:null});assert.equal(response.status,503);assert.equal(response.headers['cache-control'],'no-store');});
