import assert from 'node:assert/strict';
import test from 'node:test';
import {detectBalanceSheetAccountAgingReviews} from '../runtime/ai-balance-sheet-account-aging-review.mjs';
const id=n=>`${String(n).padStart(8,'0')}-0000-4000-8000-${String(n).padStart(12,'0')}`,hash=c=>`sha256:${c.repeat(64)}`;
const entity=id(1),period=id(2),policy={setting_snapshot_id:id(3),setting_snapshot_hash:hash('a'),policy_version:1,dormant_days:90,minimum_absolute_balance:'1000.0000'};
const row=(overrides={})=>({tenant_id:id(4),entity_id:entity,accounting_period_id:period,period_end:'2026-06-30',account_class:'ASSET',account_code:'151000',account_name:'Other receivable',currency:'USD',ending_balance:'25000.0000',last_activity_date:'2025-12-31',journal_entry_ids:[id(5)],journal_line_ids:[id(6)],ledger_line_ids:[id(7)],source_document_ids:[id(8)],...overrides});
test('flags a material dormant balance-sheet account with exact Posted lineage and no actions',()=>{const result=detectBalanceSheetAccountAgingReviews([row()],{entityId:entity,accountingPeriodId:period,policy}),finding=result.findings[0];assert.equal(result.finding_count,1);assert.equal(finding.risk_level,'HIGH');assert.equal(finding.age_days,181);assert.equal(finding.source_document_ids[0],id(8));assert.deepEqual(finding.action_flags,{can_create_draft:false,can_review:false,can_approve:false,can_post:false});});
test('does not flag recent, zero, or immaterial balances',()=>{const result=detectBalanceSheetAccountAgingReviews([row({last_activity_date:'2026-06-01'}),row({account_code:'152000',ending_balance:'0.0000'}),row({account_code:'153000',ending_balance:'999.0000'})],{entityId:entity,accountingPeriodId:period,policy});assert.equal(result.finding_count,0);});
test('fails closed for wrong scope, malformed lineage, unsafe policy, or future activity',()=>{for(const changed of [{entity_id:id(99)},{ledger_line_ids:[]},{source_document_ids:[id(8),id(8)]},{last_activity_date:'2026-07-01'}])assert.throws(()=>detectBalanceSheetAccountAgingReviews([row(changed)],{entityId:entity,accountingPeriodId:period,policy}),error=>error.code==='AI_BALANCE_SHEET_AGING_EVIDENCE_INVALID');assert.throws(()=>detectBalanceSheetAccountAgingReviews([row()],{entityId:entity,accountingPeriodId:period,policy:{...policy,dormant_days:1}}),error=>error.code==='AI_BALANCE_SHEET_AGING_SCOPE_INVALID');});
