import assert from 'node:assert/strict';
import test from 'node:test';
import {readFile} from 'node:fs/promises';
import {createAccountingApi} from '../api/accounting-http.mjs';

const tenantId='11111111-1111-4111-8111-111111111111',entityId='22222222-2222-4222-8222-222222222222',documentId='33333333-3333-4333-8333-333333333333',lineId='44444444-4444-4444-8444-444444444444',evidenceId='55555555-5555-4555-8555-555555555555',proposalId='66666666-6666-4666-8666-666666666666',periodId='77777777-7777-4777-8777-777777777777',hash='sha256:'+'a'.repeat(64);
const row={ai_construction_loan_entry_proposal_id:proposalId,tenant_id:tenantId,entity_id:entityId,ai_construction_loan_classification_evidence_id:evidenceId,classification_hash:hash,source_document_id:documentId,source_document_line_id:lineId,source_payload_hash:hash,source_document_version:'2',source_line_hash:hash,accounting_period_id:periodId,journal_date:new Date('2026-07-15T00:00:00Z'),loan_ref:'LOAN-001',classification:'LOAN_DRAW',treatment_decision:'LOAN_DRAW_CASH',debit_account_code:'111000',credit_account_code:'230000',currency:'USD',amount:'250000.0000',member_trace:{project_ref:'PROJECT-1',property_ref:'PROPERTY-1',allocation_basis:'SOURCE_DIMENSIONED'},rule_id:'AI_CONSTRUCTION_LOAN_DRAW_V1',confidence:'0.9900',proposal_reason:'Controller selected cash against loan payable from retained evidence.',proposal_hash:hash,status:'PROPOSED',created_by:'controller',created_at:new Date('2026-08-19T12:00:00Z')};
const receipt={schema_version:'AI_CONSTRUCTION_LOAN_ENTRY_PROPOSAL_V1',...row,classification_evidence_id:evidenceId,source_document_version:2,journal_date:'2026-07-15',confidence:0.99,amount:250000,can_create_draft:false,can_review:false,can_approve:false,can_post:false,idempotent:false};delete receipt.tenant_id;delete receipt.entity_id;delete receipt.ai_construction_loan_classification_evidence_id;delete receipt.proposal_reason;delete receipt.proposal_hash;delete receipt.created_by;delete receipt.created_at;
const apiFor=kernel=>createAccountingApi({authenticate:async()=>({trusted:true,tenantId,actorId:'controller'}),kernelFactory:async()=>kernel});

test('loan entry proposal GET is closed no-store balanced evidence',async()=>{const response=await apiFor({listAiConstructionLoanEntryProposals:async()=>[row]})({method:'GET',url:`/api/v1/entities/${entityId}/ai/construction-loan/entry-proposals?limit=25`});assert.equal(response.status,200);assert.equal(response.headers['cache-control'],'no-store');assert.deepEqual({debit:response.body.data[0].debit_account_code,credit:response.body.data[0].credit_account_code,amount:response.body.data[0].amount},{debit:'111000',credit:'230000',amount:'250000.0000'});for(const field of ['tenant_id','entity_id','created_by'])assert.equal(field in response.body.data[0],false);for(const flag of ['can_create_draft','can_review','can_approve','can_post'])assert.equal(response.body.data[0][flag],false);});
test('loan entry proposal POST accepts exact classification, accounts, period, dimensions and stable identity',async()=>{const calls=[],response=await apiFor({proposeAiConstructionLoanEntry:async input=>(calls.push(input),receipt)})({method:'POST',url:`/api/v1/entities/${entityId}/ai/construction-loan/entry-proposals`,headers:{'idempotency-key':'loan-entry-proposal-001'},body:{classificationEvidenceId:evidenceId,classificationHash:hash,accountingPeriodId:periodId,treatmentDecision:'LOAN_DRAW_CASH',debitAccountCode:'111000',creditAccountCode:'230000',memberTrace:{project_ref:'PROJECT-1',property_ref:'PROPERTY-1',allocation_basis:'SOURCE_DIMENSIONED'},reason:'Controller selected cash against loan payable from retained evidence.'}});assert.equal(response.status,201,JSON.stringify(response.body));assert.equal(calls[0].classificationEvidenceId,evidenceId);assert.equal(calls[0].idempotencyKey,'loan-entry-proposal-001');assert.equal(response.body.data.can_post,false);});
test('loan entry proposal rejects authority injection and OpenAPI freezes no-action schemas',async()=>{const bad=await apiFor({proposeAiConstructionLoanEntry:async()=>receipt})({method:'POST',url:`/api/v1/entities/${entityId}/ai/construction-loan/entry-proposals`,headers:{'idempotency-key':'loan-entry-proposal-002'},body:{classificationEvidenceId:evidenceId,classificationHash:hash,accountingPeriodId:periodId,treatmentDecision:'LOAN_DRAW_CASH',debitAccountCode:'111000',creditAccountCode:'230000',memberTrace:{project_ref:null,property_ref:null,allocation_basis:'ENTITY_ONLY'},reason:'Controller retained the supported accounting treatment.',canPost:true}});assert.equal(bad.status,400);const contract=JSON.parse(await readFile(new URL('../api/openapi-accounting.json',import.meta.url),'utf8')),path=contract.paths['/entities/{entityId}/ai/construction-loan/entry-proposals'];assert.equal(path.get.operationId,'listAiConstructionLoanEntryProposals');assert.equal(path.post.operationId,'proposeAiConstructionLoanEntry');for(const schema of ['AiConstructionLoanEntryProposalRequest','AiConstructionLoanEntryProposal'])assert.equal(contract.components.schemas[schema].additionalProperties,false);for(const flag of ['can_create_draft','can_review','can_approve','can_post'])assert.equal(contract.components.schemas.AiConstructionLoanEntryProposal.properties[flag].const,false);});
