import test from 'node:test';
import assert from 'node:assert/strict';
import {applyAiCapitalizationPolicy,validateAiCapitalizationPolicyEvidence} from '../runtime/ai-capitalization-policy.mjs';

const hash=`sha256:${'a'.repeat(64)}`;
const policy=overrides=>({schema_version:'AI_CAPITALIZATION_POLICY_EVIDENCE_V1',setting_snapshot_id:'11111111-1111-4111-8111-111111111111',setting_snapshot_hash:hash,policy_version:3,rule_id:'AI_CAPITALIZATION_POLICY_V1',currency:'USD',capitalization_threshold:'5000.0000',eligible_cost_classes:['EQUIPMENT','HARD_COST','INTEREST','SOFT_COST'],charge_code_classification:{'BUILD-HARD':'HARD_COST','OFFICE-SUPPLY':'OPERATING_EXPENSE'},project_status_by_ref:{'PROJECT-A':'UNDER_CONSTRUCTION','PROJECT-DONE':'COMPLETED'},useful_life_months_by_cost_class:{EQUIPMENT:60,HARD_COST:360,SOFT_COST:360},post_completion_treatment:'EXPENSE_OR_RECLASS_REVIEW',...overrides});

test('validates a closed versioned approved capitalization policy projection',()=>{assert(validateAiCapitalizationPolicyEvidence(policy()));for(const unsafe of [{...policy(),secret:'forbidden'},policy({setting_snapshot_hash:'weak'}),policy({eligible_cost_classes:['HARD_COST','HARD_COST']}),policy({project_status_by_ref:{'PROJECT-A':'GUESSED'}})])assert.equal(validateAiCapitalizationPolicyEvidence(unsafe),null);});
test('capitalizes only policy-mapped threshold-qualified construction cost',()=>{const result=applyAiCapitalizationPolicy({policy:policy(),amount:'12500.0000',currency:'USD',chargeCode:'BUILD-HARD',projectRef:'PROJECT-A'});assert.equal(result.status,'CAPITALIZATION_REVIEW');assert.equal(result.cost_class,'HARD_COST');assert.equal(result.threshold_met,true);assert.equal(result.policy_evidence.setting_snapshot_hash,hash);});
test('expenses below-threshold or explicit operating cost with policy evidence',()=>{assert.equal(applyAiCapitalizationPolicy({policy:policy(),amount:'4999.9999',currency:'USD',chargeCode:'BUILD-HARD',projectRef:'PROJECT-A'}).status,'EXPENSE_BY_POLICY');assert.equal(applyAiCapitalizationPolicy({policy:policy(),amount:'9000.0000',currency:'USD',chargeCode:'OFFICE-SUPPLY',projectRef:null}).status,'EXPENSE_BY_POLICY');});
test('fails closed for missing policy mapping project lifecycle and post-completion cost',()=>{assert.equal(applyAiCapitalizationPolicy({policy:null,amount:'9000.0000',currency:'USD',chargeCode:'BUILD-HARD',projectRef:'PROJECT-A'}).status,'POLICY_BLOCKED');assert.equal(applyAiCapitalizationPolicy({policy:policy(),amount:'9000.0000',currency:'USD',chargeCode:'UNKNOWN',projectRef:'PROJECT-A'}).status,'POLICY_BLOCKED');assert.equal(applyAiCapitalizationPolicy({policy:policy(),amount:'9000.0000',currency:'USD',chargeCode:'BUILD-HARD',projectRef:'PROJECT-UNKNOWN'}).status,'POLICY_BLOCKED');assert.equal(applyAiCapitalizationPolicy({policy:policy(),amount:'9000.0000',currency:'USD',chargeCode:'BUILD-HARD',projectRef:'PROJECT-DONE'}).status,'POST_COMPLETION_REVIEW');});
