import assert from 'node:assert/strict';import test from 'node:test';import {createAccountingApi} from '../api/accounting-http.mjs';
const id=n=>`${String(n).padStart(8,'0')}-0000-4000-8000-${String(n).padStart(12,'0')}`;
const tenantId=id(1),entityId=id(2),counterpartyEntityId=id(3),periodId=id(4),counterpartyPeriodId=id(5),hash=c=>`sha256:${c.repeat(64)}`;
const row={period_id:periodId,counterparty_period_id:counterpartyPeriodId,period_code:'2026-07',period_start:'2026-07-01',period_end:'2026-07-31',account_code:'130000',account_name:'Due from affiliate',counterparty_account_code:'220000',counterparty_account_name:'Due to affiliate',mapping_status:'MAPPED_INTERCOMPANY_PAIR',classification_basis:'APPROVED_BIDIRECTIONAL_INTERCOMPANY_MAPPING_SNAPSHOTS_EXACT',current_closing_balance:'500.0000',counterparty_closing_balance:'-100.0000',difference_amount:'400.0000',in_balance:false,mapping_snapshot_id:id(6),mapping_version:'1',mapping_snapshot_hash:hash('a'),counterparty_mapping_snapshot_id:id(7),counterparty_mapping_version:'1',counterparty_mapping_snapshot_hash:hash('b'),journal_entry_ids:[id(8)],journal_line_ids:[id(9)],ledger_line_ids:[id(10)],source_document_ids:[id(11)],counterparty_journal_entry_ids:[id(12)],counterparty_journal_line_ids:[id(13)],counterparty_ledger_line_ids:[id(14)],counterparty_source_document_ids:[id(15)]};
const apiFor=kernel=>createAccountingApi({authenticate:async()=>({trusted:true,tenantId,actorId:'oidc|controller'}),kernelFactory:async()=>kernel});
const url=`/api/v1/entities/${entityId}/ai/reports/intercompany-close-review?periodId=${periodId}&counterpartyEntityId=${counterpartyEntityId}&counterpartyPeriodId=${counterpartyPeriodId}&limit=25`;
test('HTTP intercompany close review composes the existing authoritative two-entity report into no-action AI review evidence',async()=>{const calls=[],response=await apiFor({getIntercompanyReconciliation:async scope=>(calls.push(scope),[row])})({method:'GET',url,headers:{},body:null});assert.equal(response.status,200,JSON.stringify(response.body));assert.equal(response.headers['cache-control'],'no-store');assert.deepEqual(calls,[{tenantId,entityId,periodId,counterpartyEntityId,counterpartyPeriodId}]);assert.equal(response.body.data.finding_count,1);assert.equal(response.body.data.findings[0].difference_amount,'400.0000');assert.deepEqual(response.body.data.action_flags,{can_create_draft:false,can_review:false,can_approve:false,can_post:false});});
test('HTTP intercompany close review rejects command semantics, bodies, unknown query, same entity, and unavailable evidence',async()=>{const kernel={getIntercompanyReconciliation:async()=>[row]},api=apiFor(kernel);for(const request of [{headers:{'idempotency-key':'forbidden'},body:null,url},{headers:{},body:{},url},{headers:{},body:null,url:`${url}&extra=true`},{headers:{},body:null,url:url.replace(`counterpartyEntityId=${counterpartyEntityId}`,`counterpartyEntityId=${entityId}`)}])assert.equal((await api({method:'GET',...request})).status,400);assert.equal((await apiFor({})({method:'GET',url,headers:{},body:null})).status,503);});
test('HTTP intercompany close review returns no-store 503 instead of truncated evidence',async()=>{const second={...row,account_code:'130001',account_name:'Other due from affiliate',counterparty_account_code:'220001',counterparty_account_name:'Other due to affiliate'},response=await apiFor({getIntercompanyReconciliation:async()=>[row,second]})({method:'GET',url:url.replace('limit=25','limit=1'),headers:{},body:null});assert.equal(response.status,503);assert.equal(response.headers['cache-control'],'no-store');assert.equal(response.body.code,'AI_INTERCOMPANY_FINDING_POPULATION_INCOMPLETE');});
