import assert from 'node:assert/strict';
import test from 'node:test';
import {readFile} from 'node:fs/promises';
import {createAccountingApi} from '../api/accounting-http.mjs';

const tenantId='11111111-1111-4111-8111-111111111111',entityId='22222222-2222-4222-8222-222222222222',periodId='33333333-3333-4333-8333-333333333333',evidenceId='44444444-4444-4444-8444-444444444444',documentId='55555555-5555-4555-8555-555555555555',lineId='66666666-6666-4666-8666-666666666666',proposalId='77777777-7777-4777-8777-777777777777',hash='sha256:'+'a'.repeat(64);
const rawEvidence={ai_invoice_accounting_classification_evidence_id:evidenceId,tenant_id:tenantId,entity_id:entityId,accounting_period_id:periodId,source_document_id:documentId,source_document_line_id:lineId,source_payload_hash:hash,source_line_hash:hash,classifier_version:'AI_INVOICE_ACCOUNTING_CLASSIFICATION_V2',classification:'ACCRUAL_REVIEW',reason:'Prior service requires review.',confidence:'0.9200',required_human_fields:['account_mapping'],rule_id:'AI_PRIOR_SERVICE_ACCRUAL_REVIEW_V1',policy_snapshot_id:null,policy_snapshot_hash:null,policy_evidence:null,classification_hash:hash,status:'REVIEW_REQUIRED',created_by:'secret-actor',created_at:new Date('2026-08-19T10:00:00Z')};
const rawProposal={ai_invoice_accrual_proposal_id:proposalId,tenant_id:tenantId,entity_id:entityId,ai_invoice_accounting_classification_evidence_id:evidenceId,classification_hash:hash,source_document_id:documentId,source_document_line_id:lineId,source_payload_hash:hash,source_line_hash:hash,accounting_period_id:periodId,expense_account_code:'6100',liability_account_code:'2100',currency:'USD',amount:'125.0000',member_trace:{project_ref:null,property_ref:null,allocation_basis:'ENTITY_ONLY'},reversal_decision:'NO_AUTOMATIC_REVERSAL',reversal_date:null,rule_id:'AI_PRIOR_SERVICE_ACCRUAL_REVIEW_V1',confidence:'0.9200',proposal_reason:'Controller verified the service basis.',proposal_hash:hash,status:'PROPOSED',created_by:'secret-actor',created_at:new Date('2026-08-19T10:01:00Z')};
const apiFor=kernel=>createAccountingApi({authenticate:async()=>({trusted:true,tenantId,actorId:'controller'}),kernelFactory:async()=>kernel});

test('invoice accrual reads are no-store, scoped, closed, and redact internal identity',async()=>{const calls=[],api=apiFor({listAiInvoiceAccountingClassificationEvidence:async input=>(calls.push(input),[rawEvidence,{...rawEvidence,ai_invoice_accounting_classification_evidence_id:proposalId,classification:'EXPENSE'}]),listAiInvoiceAccrualProposals:async input=>(calls.push(input),[rawProposal])});const evidence=await api({method:'GET',url:`/api/v1/entities/${entityId}/ai/invoice-accrual/evidence?periodId=${periodId}&limit=25`}),proposals=await api({method:'GET',url:`/api/v1/entities/${entityId}/ai/invoice-accrual/proposals?limit=20`});assert.equal(evidence.status,200);assert.equal(proposals.status,200);assert.equal(evidence.headers['cache-control'],'no-store');assert.equal(evidence.body.data.length,1);assert.equal(proposals.body.data[0].can_post,false);assert.equal('tenant_id' in evidence.body.data[0],false);assert.equal('created_by' in proposals.body.data[0],false);assert.deepEqual(calls,[{tenantId,entityId,accountingPeriodId:periodId,limit:25},{tenantId,entityId,limit:20}]);assert.equal((await api({method:'GET',url:`/api/v1/entities/${entityId}/ai/invoice-accrual/proposals`,headers:{'if-match':'"1"'}})).body.code,'READ_COMMAND_HEADERS_FORBIDDEN');});

test('invoice accrual POST retains proposal evidence without journal authority',async()=>{const calls=[],result={schema_version:'AI_INVOICE_ACCRUAL_PROPOSAL_V1',ai_invoice_accrual_proposal_id:proposalId,classification_evidence_id:evidenceId,classification_hash:hash,source_document_id:documentId,source_document_line_id:lineId,source_payload_hash:hash,source_line_hash:hash,accounting_period_id:periodId,expense_account_code:'6100',liability_account_code:'2100',currency:'USD',amount:125,member_trace:{project_ref:null,property_ref:null,allocation_basis:'ENTITY_ONLY'},reversal_decision:'NO_AUTOMATIC_REVERSAL',reversal_date:null,rule_id:'AI_PRIOR_SERVICE_ACCRUAL_REVIEW_V1',confidence:0.92,status:'PROPOSED',can_create_draft:false,can_review:false,can_approve:false,can_post:false,idempotent:false},api=apiFor({proposeAiInvoiceAccrual:async input=>(calls.push(input),result)});const response=await api({method:'POST',url:`/api/v1/entities/${entityId}/ai/invoice-accrual/proposals`,headers:{'idempotency-key':'invoice-accrual-001'},body:{classificationEvidenceId:evidenceId,classificationHash:hash,accountingPeriodId:periodId,expenseAccountCode:'6100',liabilityAccountCode:'2100',memberTrace:{project_ref:null,property_ref:null,allocation_basis:'ENTITY_ONLY'},reversalDecision:'NO_AUTOMATIC_REVERSAL',reversalDate:null,reason:'Controller verified the service basis.'}});assert.equal(response.status,201);assert.equal(response.headers['cache-control'],'no-store');assert.equal(response.body.data.can_create_draft,false);assert.equal(calls[0].idempotencyKey,'invoice-accrual-001');assert.equal((await api({method:'POST',url:`/api/v1/entities/${entityId}/ai/invoice-accrual/proposals`,headers:{'idempotency-key':'invoice-accrual-002'},body:{classificationEvidenceId:evidenceId,classificationHash:hash,accountingPeriodId:periodId,expenseAccountCode:'6100',liabilityAccountCode:'2100',memberTrace:{project_ref:null,property_ref:null,allocation_basis:'ENTITY_ONLY'},reversalDecision:'REVERSE_NEXT_OPEN_PERIOD',reversalDate:null,reason:'Controller verified the service basis.'}})).body.code,'INVALID_REVERSAL_DECISION');});

test('OpenAPI publishes closed invoice accrual evidence and proposal contracts',async()=>{const contract=JSON.parse(await readFile(new URL('../api/openapi-accounting.json',import.meta.url),'utf8')),evidence=contract.paths['/entities/{entityId}/ai/invoice-accrual/evidence'].get,proposal=contract.paths['/entities/{entityId}/ai/invoice-accrual/proposals'];assert.equal(evidence.operationId,'listAiInvoiceAccrualEvidence');assert.equal(proposal.post.operationId,'proposeAiInvoiceAccrual');for(const name of ['AiInvoiceAccrualEvidence','AiInvoiceAccrualProposalRequest','AiInvoiceAccrualProposal'])assert.equal(contract.components.schemas[name].additionalProperties,false);for(const flag of ['can_create_draft','can_review','can_approve','can_post'])assert.equal(contract.components.schemas.AiInvoiceAccrualProposal.properties[flag].const,false);});
