import assert from 'node:assert/strict';
import test from 'node:test';
import {readFile} from 'node:fs/promises';
import {PostgresAccountingKernel} from '../runtime/kernel-repository.mjs';
const read=path=>readFile(new URL(path,import.meta.url),'utf8');

test('capitalization proposal requires exact approved-policy classification evidence',async()=>{const up=await read('../db/migrations/189_ai_invoice_capitalization_proposal.sql');for(const token of ['CREATE TABLE ai_invoice_capitalization_proposal',"evidence.classification<>'CAPITALIZATION_REVIEW'","evidence.rule_id<>'AI_CAPITALIZATION_POLICY_V1'",'evidence.policy_snapshot_id IS NULL','source.payload_hash<>evidence.source_payload_hash','CWIP capitalization requires an exact source project reference'])assert.ok(up.includes(token),`missing ${token}`);assert.match(up,/capitalization_treatment IN \('CWIP','FIXED_ASSET'\)/);assert.match(up,/asset_account_code<>liability_account_code/);});

test('CWIP and fixed asset treatments have mutually exclusive evidence requirements',async()=>{const up=await read('../db/migrations/189_ai_invoice_capitalization_proposal.sql');assert.match(up,/capitalization_treatment='CWIP' AND placed_in_service_date IS NULL AND useful_life_months IS NULL/);assert.match(up,/capitalization_treatment='FIXED_ASSET' AND placed_in_service_date IS NOT NULL AND useful_life_months IS NOT NULL/);assert.match(up,/useful_life_months BETWEEN 1 AND 600/);});

test('capitalization proposal is actor-idempotent, append-only, audited and has zero journal authority',async()=>{const up=await read('../db/migrations/189_ai_invoice_capitalization_proposal.sql');for(const token of ['AI_INVOICE_CAPITALIZATION_PROPOSAL_V1','AI_INVOICE_CAPITALIZATION_PROPOSED','idem.actor_id IS DISTINCT FROM actor','reject_mutation','INSERT INTO audit_event','INSERT INTO outbox_event',"'can_create_draft',false","'can_review',false","'can_approve',false","'can_post',false"])assert.ok(up.includes(token),`missing ${token}`);assert.doesNotMatch(up,/INSERT INTO (staging_item|journal_entry|journal_line|ledger_line)/i);});

test('reader is scoped and rollback refuses to erase retained evidence',async()=>{const up=await read('../db/migrations/189_ai_invoice_capitalization_proposal.sql'),down=await read('../db/migrations/down/189_ai_invoice_capitalization_proposal.sql');assert.match(up,/refs_assert_scope\(p_tenant,p_entity,'AI\.CAPITALIZATION\.VIEW'\)/);assert.match(down,/IF EXISTS\(SELECT 1 FROM ai_invoice_capitalization_proposal\)/);assert.match(down,/ERRCODE='55006'/);});

test('repository computes canonical hash before proposal and exposes scoped reader',async()=>{const calls=[],kernel=new PostgresAccountingKernel({},{sessionProvider:async()=>({})});kernel.inSession=async work=>work({query:async(sql,args)=>{calls.push({sql,args});return {rowCount:1,rows:[sql.includes('_hash(')?{request_hash:`sha256:${'a'.repeat(64)}`} : sql.includes('refs_propose_')?{result:{status:'PROPOSED'}}:{ai_invoice_capitalization_proposal_id:'proposal'}]};}});const input={tenantId:'tenant',entityId:'entity',classificationEvidenceId:'evidence',classificationHash:`sha256:${'b'.repeat(64)}`,accountingPeriodId:'period',capitalizationTreatment:'CWIP',assetAccountCode:'150100',liabilityAccountCode:'211000',assetClass:'CONSTRUCTION_IN_PROGRESS',memberTrace:{project_ref:'PROJECT-1',property_ref:null,allocation_basis:'SOURCE_DIMENSIONED'},placedInServiceDate:null,usefulLifeMonths:null,reason:'Controller confirmed capitalization under approved policy.',idempotencyKey:'idem'};assert.deepEqual(await kernel.proposeAiInvoiceCapitalization(input),{status:'PROPOSED'});assert.deepEqual(await kernel.listAiInvoiceCapitalizationProposals({tenantId:'tenant',entityId:'entity',limit:25}),[{ai_invoice_capitalization_proposal_id:'proposal'}]);assert.match(calls[0].sql,/refs_propose_ai_invoice_capitalization_hash/);assert.match(calls[1].sql,/refs_propose_ai_invoice_capitalization/);assert.match(calls[2].sql,/refs_read_ai_invoice_capitalization_proposals/);assert.equal(calls[1].args.at(-2),'idem');});
