import assert from 'node:assert/strict';
import test from 'node:test';
import {readFile} from 'node:fs/promises';
import {createAccountingApi} from '../api/accounting-http.mjs';

const tenantId='11111111-1111-4111-8111-111111111111',entityId='22222222-2222-4222-8222-222222222222',periodId='33333333-3333-4333-8333-333333333333',evidenceId='44444444-4444-4444-8444-444444444444',documentId='55555555-5555-4555-8555-555555555555',lineId='66666666-6666-4666-8666-666666666666',proposalId='77777777-7777-4777-8777-777777777777',policyId='88888888-8888-4888-8888-888888888888',hash='sha256:'+'a'.repeat(64);
const evidence={ai_invoice_accounting_classification_evidence_id:evidenceId,tenant_id:tenantId,entity_id:entityId,accounting_period_id:periodId,source_document_id:documentId,source_document_line_id:lineId,source_payload_hash:hash,source_line_hash:hash,classifier_version:'AI_INVOICE_ACCOUNTING_CLASSIFICATION_V2',classification:'CAPITALIZATION_REVIEW',reason:'Approved policy requires construction cost review.',confidence:'0.9900',required_human_fields:['capital_account'],rule_id:'AI_CAPITALIZATION_POLICY_V1',policy_snapshot_id:policyId,policy_snapshot_hash:hash,classification_hash:hash,status:'REVIEW_REQUIRED',created_by:'internal-actor',created_at:new Date('2026-08-19T10:00:00Z')};
const proposal={ai_invoice_capitalization_proposal_id:proposalId,tenant_id:tenantId,entity_id:entityId,ai_invoice_accounting_classification_evidence_id:evidenceId,classification_hash:hash,source_document_id:documentId,source_document_line_id:lineId,source_payload_hash:hash,source_line_hash:hash,accounting_period_id:periodId,capitalization_treatment:'CWIP',asset_account_code:'150100',liability_account_code:'291001',asset_class:'CONSTRUCTION_IN_PROGRESS',currency:'USD',amount:'25000.0000',member_trace:{project_ref:'PROJECT-1',property_ref:'PROPERTY-1',allocation_basis:'SOURCE_DIMENSIONED'},placed_in_service_date:null,useful_life_months:null,rule_id:'AI_CAPITALIZATION_POLICY_V1',policy_snapshot_id:policyId,policy_snapshot_hash:hash,confidence:'0.9900',proposal_reason:'Controller verified policy eligibility.',proposal_hash:hash,status:'PROPOSED',created_by:'internal-actor',created_at:new Date('2026-08-19T10:01:00Z')};
const apiFor=kernel=>createAccountingApi({authenticate:async()=>({trusted:true,tenantId,actorId:'controller'}),kernelFactory:async()=>kernel});

test('capitalization evidence and proposals are closed no-store projections',async()=>{const calls=[],api=apiFor({listAiInvoiceAccountingClassificationEvidence:async input=>(calls.push(input),[evidence,{...evidence,ai_invoice_accounting_classification_evidence_id:proposalId,classification:'EXPENSE'}]),listAiInvoiceCapitalizationProposals:async input=>(calls.push(input),[proposal])});const evidenceResponse=await api({method:'GET',url:`/api/v1/entities/${entityId}/ai/invoice-capitalization/evidence?periodId=${periodId}&limit=25`}),proposalResponse=await api({method:'GET',url:`/api/v1/entities/${entityId}/ai/invoice-capitalization/proposals?limit=20`});assert.equal(evidenceResponse.status,200);assert.equal(proposalResponse.status,200);assert.equal(evidenceResponse.headers['cache-control'],'no-store');assert.equal(evidenceResponse.body.data.length,1);assert.equal(proposalResponse.body.data[0].can_post,false);assert.equal('tenant_id' in evidenceResponse.body.data[0],false);assert.equal('created_by' in proposalResponse.body.data[0],false);assert.deepEqual(calls,[{tenantId,entityId,accountingPeriodId:periodId,limit:25},{tenantId,entityId,limit:20}]);});

test('capitalization POST retains policy-bound evidence and cannot create a journal action',async()=>{const calls=[],result={schema_version:'AI_INVOICE_CAPITALIZATION_PROPOSAL_V1',...proposal,classification_evidence_id:evidenceId,amount:25000,confidence:0.99,created_at:undefined,proposal_reason:undefined,proposal_hash:undefined,created_by:undefined,tenant_id:undefined,entity_id:undefined,ai_invoice_accounting_classification_evidence_id:undefined,idempotent:false,can_create_draft:false,can_review:false,can_approve:false,can_post:false};for(const key of Object.keys(result))if(result[key]===undefined)delete result[key];const api=apiFor({proposeAiInvoiceCapitalization:async input=>(calls.push(input),result)}),body={classificationEvidenceId:evidenceId,classificationHash:hash,accountingPeriodId:periodId,capitalizationTreatment:'CWIP',assetAccountCode:'150100',liabilityAccountCode:'291001',assetClass:'CONSTRUCTION_IN_PROGRESS',memberTrace:{project_ref:'PROJECT-1',property_ref:'PROPERTY-1',allocation_basis:'SOURCE_DIMENSIONED'},placedInServiceDate:null,usefulLifeMonths:null,reason:'Controller verified policy eligibility.'};const response=await api({method:'POST',url:`/api/v1/entities/${entityId}/ai/invoice-capitalization/proposals`,headers:{'idempotency-key':'invoice-capitalization-001'},body});assert.equal(response.status,201);assert.equal(response.body.data.can_create_draft,false);assert.equal(calls[0].idempotencyKey,'invoice-capitalization-001');const invalid=await api({method:'POST',url:`/api/v1/entities/${entityId}/ai/invoice-capitalization/proposals`,headers:{'idempotency-key':'invoice-capitalization-002'},body:{...body,capitalizationTreatment:'FIXED_ASSET'}});assert.equal(invalid.body.code,'INVALID_CAPITALIZATION_TREATMENT');});

test('OpenAPI publishes closed capitalization evidence and proposal schemas',async()=>{const contract=JSON.parse(await readFile(new URL('../api/openapi-accounting.json',import.meta.url),'utf8')),evidencePath=contract.paths['/entities/{entityId}/ai/invoice-capitalization/evidence'],proposalPath=contract.paths['/entities/{entityId}/ai/invoice-capitalization/proposals'];assert.equal(evidencePath.get.operationId,'listAiInvoiceCapitalizationEvidence');assert.equal(proposalPath.post.operationId,'proposeAiInvoiceCapitalization');for(const name of ['AiInvoiceCapitalizationEvidence','AiInvoiceCapitalizationProposalRequest','AiInvoiceCapitalizationProposal'])assert.equal(contract.components.schemas[name].additionalProperties,false);for(const flag of ['can_create_draft','can_review','can_approve','can_post'])assert.equal(contract.components.schemas.AiInvoiceCapitalizationProposal.properties[flag].const,false);});
