import assert from 'node:assert/strict';import test from 'node:test';import {readFileSync} from 'node:fs';import {createAccountingApi} from '../api/accounting-http.mjs';
const id=n=>`${String(n).padStart(8,'0')}-0000-4000-8000-${String(n).padStart(12,'0')}`,hash=n=>`sha256:${String(n%10).repeat(64)}`,tenantId=id(1),entityId=id(2),periodId=id(3),actions={can_create_draft:false,can_review:false,can_approve:false,can_post:false};
const trace={business_document_id:id(10),document_number:'INV-10',source_document_id:id(11),source_payload_hash:hash(1),posted_journal_entry_id:id(12),posted_journal_line_id:id(13),posted_line_hash:hash(2)};
const finding={schema_version:'AI_VENDOR_ACCOUNT_CODING_DRIFT_FINDING_V1',finding_type:'VENDOR_ACCOUNT_CODING_DRIFT',risk_level:'HIGH',rule_id:'AI_VENDOR_POSTED_ACCOUNT_HISTORY_DRIFT_V1',entity_id:entityId,accounting_period_id:periodId,vendor_ref:'V-1',vendor_name:'Vendor',current_account_code:'150100',current_account_name:'CWIP',baseline_account_code:'610100',baseline_account_name:'Repairs',history_period_count:3,history_evidence_count:3,baseline_evidence_count:3,baseline_dominance_basis_points:10000,current_source_trace:trace,history_posted_line_hashes:[hash(3),hash(4),hash(5)],reason:'Posted coding changed.',suggested_action:'Review evidence.',confidence:0.99,owner_role:'CONTROLLER_REVIEW',due_basis:'BEFORE_PERIOD_CLOSE',required_human_fields:['invoice_substance','contract_or_coverage_period','project_property_coding','capitalization_policy','approved_account_mapping','coding_conclusion','resolution_reason'],action_flags:actions};
const data={schema_version:'AI_VENDOR_ACCOUNT_CODING_DRIFT_BATCH_V1',current_accounting_period_id:periodId,scanned_posted_line_count:4,finding_count:1,findings:[finding],action_flags:actions},path=`/api/v1/entities/${entityId}/ai/vendor-account-coding-drifts?periodId=${periodId}&limit=2000`;
const make=value=>createAccountingApi({authenticate:async()=>({trusted:true,tenantId,actorId:'controller'}),kernelFactory:async()=>({}),aiVendorAccountCodingDriftServiceFactory:async()=>({analyze:async input=>{assert.equal(input.entityId,entityId);assert.equal(input.accountingPeriodId,periodId);return value;}})});
test('GET returns only closed source-bound Posted account coding drift evidence',async()=>{const response=await make(data)({method:'GET',url:path,headers:{},body:null});assert.equal(response.status,200);assert.equal(response.headers['cache-control'],'no-store');assert.deepEqual(response.body.data,data);});
test('GET rejects unsafe authority, extra output, command headers, and bodies',async()=>{for(const changed of [{...data,secret:'x'},{...data,action_flags:{...actions,can_post:true}},{...data,findings:[{...finding,current_source_trace:{...trace,token:'secret'}}]}])assert.equal((await make(changed)({method:'GET',url:path,headers:{},body:null})).status,502);assert.equal((await make(data)({method:'GET',url:path,headers:{'if-match':'"1"'},body:null})).status,400);assert.equal((await make(data)({method:'GET',url:path,headers:{},body:{}})).status,400);});
test('OpenAPI closes the account-coding route and trace',()=>{const contract=JSON.parse(readFileSync(new URL('../api/openapi-accounting.json',import.meta.url),'utf8')),operation=contract.paths['/entities/{entityId}/ai/vendor-account-coding-drifts'].get,findingSchema=contract.components.schemas.AiVendorAccountCodingDriftFinding;assert.equal(operation.operationId,'analyzeVendorAccountCodingDrifts');assert.equal(operation.responses['200'].headers['Cache-Control'].schema.const,'no-store');assert.equal(findingSchema.additionalProperties,false);assert.equal(findingSchema.properties.current_source_trace.$ref,'#/components/schemas/AiVendorAccountCodingTrace');assert.equal(findingSchema.properties.action_flags.$ref,'#/components/schemas/AiInvoiceNoAccountingActions');});
