import assert from 'node:assert/strict';
import test from 'node:test';
import {detectVendorInvoiceAmountDropAnomalies} from '../runtime/ai-vendor-invoice-amount-drop-anomaly.mjs';
const id=n=>`${String(n).padStart(8,'0')}-0000-4000-8000-${String(n).padStart(12,'0')}`,hash=c=>`sha256:${c.repeat(64)}`;
const policy={schema_version:'AI_VENDOR_INVOICE_AMOUNT_DROP_POLICY_V1',setting_snapshot_id:id(90),setting_snapshot_hash:hash('f'),policy_version:1,minimum_history_periods:3,drop_ratio_threshold_basis_points:5000,minimum_absolute_drop:'100.0000'};
const row=(n,period,amount,overrides={})=>({source_document_id:id(n),source_document_line_id:id(n+20),source_payload_hash:hash(String(n%10)),source_line_hash:hash(String((n+1)%10)),entity_id:id(1),accounting_period_id:id(period),vendor_ref:'VENDOR-MAINTENANCE',vendor_name:'Maintenance Vendor',currency:'USD',amount,invoice_date:`2026-0${Math.min(period,9)}-01`,project_ref:'PROJECT-1',property_ref:'PROPERTY-1',cost_category_ref:'REPAIRS',source_admission_status:'ADMITTED',signature_verified:true,...overrides});

test('flags a current invoice that falls to twenty percent of its retained historical median',()=>{const result=detectVendorInvoiceAmountDropAnomalies([row(2,2,'500.0000'),row(3,3,'500.0000'),row(4,4,'500.0000'),row(5,5,'100.0000')],{policy,currentAccountingPeriodId:id(5)}),finding=result.findings[0];assert.equal(result.finding_count,1);assert.equal(finding.risk_level,'HIGH');assert.equal(finding.current_amount,'100.0000');assert.equal(finding.baseline_median_amount,'500.0000');assert.equal(finding.absolute_drop,'400.0000');assert.equal(finding.retained_ratio_basis_points,2000);assert.deepEqual(finding.required_human_fields,['amount_drop_explanation','source_completeness','accrual_required','account_mapping','member_trace','reversing_entry_decision']);assert.deepEqual(finding.action_flags,{can_create_draft:false,can_review:false,can_approve:false,can_post:false});});
test('does not compare across accounting contexts or flag normal and immaterial variance',()=>{const history=[row(2,2,'500.0000'),row(3,3,'500.0000'),row(4,4,'500.0000')];for(const changed of [{entity_id:id(8)},{vendor_ref:'OTHER'},{currency:'CAD'},{project_ref:'OTHER'},{property_ref:'OTHER'},{cost_category_ref:'UTILITIES'}])assert.equal(detectVendorInvoiceAmountDropAnomalies([...history,row(5,5,'100.0000',changed)],{policy,currentAccountingPeriodId:id(5)}).finding_count,0);assert.equal(detectVendorInvoiceAmountDropAnomalies([...history,row(5,5,'450.0000')],{policy,currentAccountingPeriodId:id(5)}).finding_count,0);});
test('requires three distinct historical periods and exact approved policy',()=>{assert.equal(detectVendorInvoiceAmountDropAnomalies([row(2,2,'500.0000'),row(3,3,'500.0000'),row(5,5,'100.0000')],{policy,currentAccountingPeriodId:id(5)}).finding_count,0);assert.throws(()=>detectVendorInvoiceAmountDropAnomalies([row(2,2,'500.0000')],{policy:{...policy,extra:'unsafe'},currentAccountingPeriodId:id(5)}),error=>error.code==='AI_VENDOR_AMOUNT_DROP_POLICY_REQUIRED');});
test('fails closed for unsigned, unadmitted, malformed, or oversized evidence',()=>{for(const changed of [{signature_verified:false},{source_admission_status:'STAGING'},{source_line_hash:'bad'},{amount:'100'}])assert.throws(()=>detectVendorInvoiceAmountDropAnomalies([row(2,2,'500.0000',changed)],{policy,currentAccountingPeriodId:id(5)}),error=>error.code==='AI_VENDOR_AMOUNT_DROP_SOURCE_INVALID');assert.throws(()=>detectVendorInvoiceAmountDropAnomalies(Array.from({length:501},(_,index)=>row(index+2,2,'500.0000')),{policy,currentAccountingPeriodId:id(5)}),error=>error.code==='AI_VENDOR_AMOUNT_DROP_SCOPE_INVALID');});
test('fails closed when duplicate retained lines could skew the historical median',()=>{const original=row(2,2,'500.0000');for(const duplicate of [{...row(3,3,'500.0000'),source_document_line_id:original.source_document_line_id},{...row(3,3,'500.0000'),source_line_hash:original.source_line_hash}])assert.throws(()=>detectVendorInvoiceAmountDropAnomalies([original,duplicate],{policy,currentAccountingPeriodId:id(5)}),error=>error.code==='AI_VENDOR_AMOUNT_DROP_SOURCE_DUPLICATE');});
test('rejects credential-shaped values embedded in otherwise valid amount-drop evidence',()=>{const opaque=['pk','dropcredential123'].join('-');assert.throws(()=>detectVendorInvoiceAmountDropAnomalies([row(2,2,'500.0000',{cost_category_ref:`cost ${opaque}`})],{policy,currentAccountingPeriodId:id(5)}),error=>error.code==='AI_VENDOR_AMOUNT_DROP_SOURCE_INVALID');});
