import assert from 'node:assert/strict';
import test from 'node:test';
import {detectVendorInvoiceAmountAnomalies} from '../runtime/ai-vendor-invoice-amount-anomaly.mjs';
const id=n=>`${String(n).padStart(8,'0')}-0000-4000-8000-${String(n).padStart(12,'0')}`;
const hash=c=>`sha256:${c.repeat(64)}`;
const policy={schema_version:'AI_VENDOR_INVOICE_AMOUNT_ANOMALY_POLICY_V1',setting_snapshot_id:id(90),setting_snapshot_hash:hash('f'),policy_version:1,minimum_history_periods:3,ratio_threshold_basis_points:20000,minimum_absolute_delta:'100.0000'};
const row=(n,period,amount,overrides={})=>({source_document_id:id(n),source_document_line_id:id(n+20),source_payload_hash:hash(String(n%10)),source_line_hash:hash(String((n+1)%10)),entity_id:id(1),accounting_period_id:id(period),vendor_ref:'VENDOR-INSURANCE',vendor_name:'Insurance Vendor',currency:'USD',amount,invoice_date:`2026-0${Math.min(period,9)}-01`,project_ref:null,property_ref:null,cost_category_ref:'INSURANCE',source_admission_status:'ADMITTED',signature_verified:true,...overrides});

test('finds a five-times vendor invoice spike from retained prior-period evidence with no accounting authority',()=>{
  const result=detectVendorInvoiceAmountAnomalies([row(2,2,'100.0000'),row(3,3,'100.0000'),row(4,4,'100.0000'),row(5,5,'500.0000')],{policy,currentAccountingPeriodId:id(5)}),finding=result.findings[0];
  assert.equal(result.finding_count,1);assert.equal(finding.risk_level,'HIGH');assert.equal(finding.current_amount,'500.0000');assert.equal(finding.baseline_median_amount,'100.0000');assert.equal(finding.absolute_delta,'400.0000');assert.equal(finding.ratio_basis_points,50000);assert.equal(finding.history_period_count,3);assert.equal(finding.history_source_line_hashes.length,3);assert.equal(finding.policy_evidence.setting_snapshot_hash,hash('f'));assert.deepEqual(finding.action_flags,{can_create_draft:false,can_review:false,can_approve:false,can_post:false});
});
test('does not compare across entity, vendor, currency, project, property, or cost category',()=>{const history=[row(2,2,'100.0000'),row(3,3,'100.0000'),row(4,4,'100.0000')];for(const changed of [{entity_id:id(8)},{vendor_ref:'OTHER'},{currency:'CAD'},{project_ref:'P-1'},{property_ref:'PROPERTY-1'},{cost_category_ref:'REPAIRS'}])assert.equal(detectVendorInvoiceAmountAnomalies([...history,row(5,5,'500.0000',changed)],{policy,currentAccountingPeriodId:id(5)}).finding_count,0);});
test('requires distinct history periods and ignores immaterial or downward changes',()=>{assert.equal(detectVendorInvoiceAmountAnomalies([row(2,2,'100.0000'),row(3,3,'100.0000'),row(5,5,'500.0000')],{policy,currentAccountingPeriodId:id(5)}).finding_count,0);assert.equal(detectVendorInvoiceAmountAnomalies([row(2,2,'100.0000'),row(3,3,'100.0000'),row(4,4,'100.0000'),row(5,5,'180.0000')],{policy,currentAccountingPeriodId:id(5)}).finding_count,0);assert.equal(detectVendorInvoiceAmountAnomalies([row(2,2,'500.0000'),row(3,3,'500.0000'),row(4,4,'500.0000'),row(5,5,'100.0000')],{policy,currentAccountingPeriodId:id(5)}).finding_count,0);});
test('fails closed for unsigned, unadmitted, malformed, oversized, or policy-free analysis',()=>{for(const changed of [{signature_verified:false},{source_admission_status:'STAGING'},{source_line_hash:'bad'},{amount:'500'}])assert.throws(()=>detectVendorInvoiceAmountAnomalies([row(2,2,'100.0000',changed)],{policy,currentAccountingPeriodId:id(5)}),error=>error.code==='AI_VENDOR_ANOMALY_SOURCE_INVALID');assert.throws(()=>detectVendorInvoiceAmountAnomalies([row(2,2,'100.0000')],{currentAccountingPeriodId:id(5)}),error=>error.code==='AI_VENDOR_ANOMALY_POLICY_REQUIRED');assert.throws(()=>detectVendorInvoiceAmountAnomalies(Array.from({length:501},(_,index)=>row(index+2,2,'100.0000')),{policy,currentAccountingPeriodId:id(5)}),error=>error.code==='AI_VENDOR_ANOMALY_SCOPE_INVALID');});
test('fails closed when the same retained invoice line or line hash is supplied twice',()=>{const original=row(2,2,'100.0000');assert.throws(()=>detectVendorInvoiceAmountAnomalies([original,{...original}],{policy,currentAccountingPeriodId:id(5)}),error=>error.code==='AI_VENDOR_ANOMALY_SOURCE_DUPLICATE');assert.throws(()=>detectVendorInvoiceAmountAnomalies([original,row(3,3,'100.0000',{source_line_hash:original.source_line_hash})],{policy,currentAccountingPeriodId:id(5)}),error=>error.code==='AI_VENDOR_ANOMALY_SOURCE_DUPLICATE');});
test('rejects impossible calendar dates, secret-bearing evidence, and non-closed policy objects',()=>{const opaque=['sk','vendorcredential123'].join('-');for(const changed of [{invoice_date:'2026-02-30'},{vendor_name:`Vendor ${opaque}`},{cost_category_ref:'authorization=Bearer abcdefghijklmnop'}])assert.throws(()=>detectVendorInvoiceAmountAnomalies([row(2,2,'100.0000',changed)],{policy,currentAccountingPeriodId:id(5)}),error=>error.code==='AI_VENDOR_ANOMALY_SOURCE_INVALID');assert.throws(()=>detectVendorInvoiceAmountAnomalies([],{policy:{...policy,internal_note:opaque},currentAccountingPeriodId:id(5)}),error=>error.code==='AI_VENDOR_ANOMALY_POLICY_REQUIRED');});
