import assert from 'node:assert/strict';
import test from 'node:test';
import {detectVendorInvoiceFrequencyAnomalies} from '../runtime/ai-vendor-invoice-frequency-anomaly.mjs';
const id=n=>`${String(n).padStart(8,'0')}-0000-4000-8000-${String(n).padStart(12,'0')}`;
const hash=n=>`sha256:${String(n%10).repeat(64)}`;
const policy={schema_version:'AI_VENDOR_INVOICE_FREQUENCY_ANOMALY_POLICY_V1',setting_snapshot_id:id(90),setting_snapshot_hash:hash(9),policy_version:1,minimum_history_periods:3,frequency_ratio_threshold_basis_points:30000,minimum_excess_invoice_count:2};
const row=(n,period,overrides={})=>({source_document_id:id(n),source_document_line_id:id(n+100),source_payload_hash:hash(n),source_line_hash:hash(n+1),entity_id:id(1),accounting_period_id:id(period),vendor_ref:'VENDOR-1',vendor_name:'Monthly Services',currency:'USD',amount:'100.0000',invoice_date:`2026-0${period}-01`,project_ref:null,property_ref:null,cost_category_ref:'SERVICES',source_admission_status:'ADMITTED',signature_verified:true,...overrides});

test('finds a one-to-five monthly vendor frequency spike with exact source set and zero accounting authority',()=>{const rows=[row(1,1),row(2,2),row(3,3),row(4,4),row(5,4),row(6,4),row(7,4),row(8,4)],result=detectVendorInvoiceFrequencyAnomalies(rows,{policy,currentAccountingPeriodId:id(4)}),finding=result.findings[0];assert.equal(result.finding_count,1);assert.equal(finding.current_invoice_count,5);assert.equal(finding.baseline_median_invoice_count,1);assert.equal(finding.excess_invoice_count,4);assert.equal(finding.frequency_ratio_basis_points,50000);assert.equal(finding.current_total_amount,'500.0000');assert.equal(finding.current_source_trace.length,5);assert.equal(new Set(finding.current_source_trace.map(trace=>trace.source_document_line_id)).size,5);assert.equal(new Set(finding.current_source_trace.map(trace=>trace.source_line_hash)).size,5);assert.deepEqual(finding.action_flags,{can_create_draft:false,can_review:false,can_approve:false,can_post:false});});
test('does not mix entity, vendor, currency, project, property, or cost category histories',()=>{const baseline=[row(1,1),row(2,2),row(3,3)];for(const changed of [{entity_id:id(8)},{vendor_ref:'OTHER'},{currency:'CAD'},{project_ref:'P-1'},{property_ref:'PROPERTY-1'},{cost_category_ref:'REPAIRS'}])assert.equal(detectVendorInvoiceFrequencyAnomalies([...baseline,...[4,5,6,7,8].map(n=>row(n,4,changed))],{policy,currentAccountingPeriodId:id(4)}).finding_count,0);});
test('requires distinct history periods and exact approved thresholds',()=>{assert.equal(detectVendorInvoiceFrequencyAnomalies([row(1,1),row(2,2),...[3,4,5,6,7].map(n=>row(n,4))],{policy,currentAccountingPeriodId:id(4)}).finding_count,0);assert.equal(detectVendorInvoiceFrequencyAnomalies([row(1,1),row(2,2),row(3,3),row(4,4),row(5,4)],{policy,currentAccountingPeriodId:id(4)}).finding_count,0);for(const invalid of [undefined,{...policy,authorization:'secret'},{...policy,minimum_history_periods:2}])assert.throws(()=>detectVendorInvoiceFrequencyAnomalies([row(1,1)],{policy:invalid,currentAccountingPeriodId:id(4)}),error=>error.code==='AI_VENDOR_FREQUENCY_POLICY_REQUIRED');});
test('fails closed before analysis for unsigned, unadmitted, malformed, or oversized evidence',()=>{for(const changed of [{signature_verified:false},{source_admission_status:'STAGING'},{source_line_hash:'bad'},{amount:'100'}])assert.throws(()=>detectVendorInvoiceFrequencyAnomalies([row(1,1,changed)],{policy,currentAccountingPeriodId:id(4)}),error=>error.code==='AI_VENDOR_FREQUENCY_SOURCE_INVALID');assert.throws(()=>detectVendorInvoiceFrequencyAnomalies(Array.from({length:501},(_,index)=>row(index+1,1)),{policy,currentAccountingPeriodId:id(4)}),error=>error.code==='AI_VENDOR_FREQUENCY_SCOPE_INVALID');});
