import assert from 'node:assert/strict';import test from 'node:test';import {readFile} from 'node:fs/promises';
const up=await readFile(new URL('../db/migrations/200_ai_vendor_invoice_near_duplicate_finding.sql',import.meta.url),'utf8'),down=await readFile(new URL('../db/migrations/down/200_ai_vendor_invoice_near_duplicate_finding.sql',import.meta.url),'utf8');
test('near-duplicate finding and both exact signed sources are append-only',()=>{for(const token of ['CREATE TABLE ai_vendor_invoice_near_duplicate_finding','CREATE TABLE ai_vendor_invoice_near_duplicate_source','source_ordinal smallint NOT NULL CHECK','ENABLE ROW LEVEL SECURITY','append_only','wbs_final1_retained_source_row','domain=\'PAYABLES\'','source_document_line_id','raw_row_hash','source_payload_hash','trace_count<>2','two distinct exact source lines'])assert.match(up,new RegExp(token));assert.match(up,/source_ordinal IN\(1,2\)/);});
test('database independently reproduces source identity, values, periods, thresholds, and risk',()=>{
  for(const token of ['source_document_line','source.document_no IS DISTINCT FROM trace','source.currency IS DISTINCT FROM item','source_line.amount IS DISTINCT FROM','signed_invoice_date','source_line.party_ref IS DISTINCT FROM','source_line.project_ref IS DISTINCT FROM','source_line.property_ref IS DISTINCT FROM','regexp_replace(upper(first_trace','computed_amount_variance','computed_variance_bps','computed_date_gap','maximum_absolute_amount_variance','maximum_amount_variance_basis_points','maximum_date_gap_days','comparison was not reproducible under approved policy'])assert.ok(up.includes(token),`missing independent database check: ${token}`);
  assert.match(up,/source_document_id'!~'\^\[0-9a-f\]\{8\}/);assert.match(up,/accounting periods do not exactly match both sources/);assert.match(up,/risk_level' IS DISTINCT FROM CASE WHEN computed_amount_variance=0 THEN 'HIGH' ELSE 'MEDIUM' END/);
});
test('near-duplicate materialization is actor-idempotent and atomically emits one audit/outbox pair with zero accounting actions',()=>{for(const token of ['refs_ai_vendor_invoice_near_duplicate_batch_hash','idempotency_receipt','actor_id IS DISTINCT FROM actor','FOR UPDATE','refs_read_ai_vendor_invoice_near_duplicate_policy','audit_event','outbox_event','HUMAN_DECISION_REQUIRED',"'can_create_draft',false","'can_review',false","'can_approve',false","'can_post',false"])assert.match(up,new RegExp(token));assert.doesNotMatch(up,/INSERT INTO journal_entry|INSERT INTO journal_entry_line|INSERT INTO staging_item|refs_post_journal|UPDATE journal_entry/i);});
test('near-duplicate rollback refuses to erase retained evidence',()=>{assert.match(down,/Cannot remove retained vendor near-duplicate findings/);assert.match(down,/DROP TABLE ai_vendor_invoice_near_duplicate_source/);assert.match(down,/DROP TABLE ai_vendor_invoice_near_duplicate_finding/);});
