import assert from 'node:assert/strict';
import test from 'node:test';
import {createAiVendorInvoiceNearDuplicateService} from '../runtime/ai-vendor-invoice-near-duplicate-service.mjs';
const id=n=>`${String(n).padStart(8,'0')}-0000-4000-8000-${String(n).padStart(12,'0')}`;
const hash=n=>`sha256:${String(n%10).repeat(64)}`;
const documents=[1,2,3].map(n=>({source_document_id:id(n),source_system:'WBS'}));
const policy={schema_version:'AI_VENDOR_INVOICE_NEAR_DUPLICATE_POLICY_V1',setting_snapshot_id:id(90),setting_snapshot_hash:hash(9),policy_version:1,maximum_date_gap_days:7,maximum_amount_variance_basis_points:100,maximum_absolute_amount_variance:'5.0000'};
const serviceFor=({materializeWriter=null,verified=true}={})=>createAiVendorInvoiceNearDuplicateService({sourceReader:async()=>documents,policyReader:async()=>policy,detailReader:async({sourceDocumentId})=>{const n=Number(sourceDocumentId.slice(0,8));return [{source_document_id:sourceDocumentId,payload_hash:hash(n),currency:'USD',lines:[{source_document_line_id:id(n+100),amount:n===2?'502.0000':'500.0000',party_ref:'VENDOR-1',project_ref:null,property_ref:'PROPERTY-1',provider_trace:{trace_version:'WBS_PROVIDER_SOURCE_TRACE_V1',domain:'PAYABLES',disposition:'RETAINED',invoice_no:n===1?'INV-1001':n===2?'INV1001':null,invoice_date:n===2?'2026-07-17':'2026-07-15'}}]}];},evidenceReader:async({sourceDocumentId})=>{const n=Number(sourceDocumentId.slice(0,8));return {signature_verified:verified,admission_status:verified?'ADMITTED':'REJECTED',accounting_period_id:id(7),source_row_hash:hash(n+1)};},materializeWriter});

test('builds near-duplicate evidence from retained signed source while skipping explicit null invoice identity',async()=>{const result=await serviceFor().analyze({tenantId:id(80),entityId:id(1),currentAccountingPeriodId:id(7)});assert.equal(result.current_accounting_period_id,id(7));assert.equal(result.scanned_line_count,2);assert.equal(result.finding_count,1);assert.deepEqual(result.action_flags,{can_create_draft:false,can_review:false,can_approve:false,can_post:false});assert.equal(result.findings[0].source_trace.length,2);});
test('unsigned and rejected sources never reach near-duplicate analysis',async()=>{const result=await serviceFor({verified:false}).analyze({tenantId:id(80),entityId:id(1),currentAccountingPeriodId:id(7)});assert.equal(result.scanned_line_count,0);assert.equal(result.finding_count,0);});
test('materialization delegates one recomputed action-free batch under stable idempotency',async()=>{let written;const receipt={schema_version:'AI_VENDOR_INVOICE_NEAR_DUPLICATE_RUN_RECEIPT_V1',can_create_draft:false,can_review:false,can_approve:false,can_post:false};const result=await serviceFor({materializeWriter:async input=>(written=input,receipt)}).analyzeAndMaterialize({tenantId:id(80),entityId:id(1),currentAccountingPeriodId:id(7),idempotencyKey:'near-duplicate-001'});assert.equal(result,receipt);assert.equal(written.accountingPeriodId,id(7));assert.equal(written.batch.finding_count,1);assert.equal(written.idempotencyKey,'near-duplicate-001');});
test('service fails closed when a server reader returns credential-bearing source evidence',async()=>{const opaque=['pk','duplicatecredential123'].join('-'),service=createAiVendorInvoiceNearDuplicateService({sourceReader:async()=>[{source_document_id:id(1),source_system:'WBS',description:opaque}],policyReader:async()=>policy,detailReader:async()=>[],evidenceReader:async()=>null});await assert.rejects(()=>service.analyze({tenantId:id(80),entityId:id(1),currentAccountingPeriodId:id(7)}),error=>error.code==='AI_VENDOR_NEAR_DUPLICATE_SOURCE_INVALID');});
