import assert from 'node:assert/strict';
import test from 'node:test';
import {createAiVendorInvoiceAnomalyService} from '../runtime/ai-vendor-invoice-anomaly-service.mjs';
const id=n=>`${String(n).padStart(8,'0')}-0000-4000-8000-${String(n).padStart(12,'0')}`;
const hash=c=>`sha256:${c.repeat(64)}`;
const documents=[2,3,4,5].map(n=>({source_document_id:id(n),source_system:'WBS'}));
const policy={schema_version:'AI_VENDOR_INVOICE_AMOUNT_ANOMALY_POLICY_V1',setting_snapshot_id:id(90),setting_snapshot_hash:hash('f'),policy_version:1,minimum_history_periods:3,ratio_threshold_basis_points:20000,minimum_absolute_delta:'100.0000'};
test('builds a five-times spike only from admitted retained source evidence and performs no write or model call',async()=>{
  let detailReads=0,evidenceReads=0;
  const service=createAiVendorInvoiceAnomalyService({sourceReader:async()=>documents,policyReader:async()=>policy,detailReader:async({sourceDocumentId})=>{detailReads++;const n=Number(sourceDocumentId.slice(0,8));return [{source_document_id:sourceDocumentId,payload_hash:hash(String(n)),currency:'USD',lines:[{source_document_line_id:id(n+20),amount:n===5?'500.0000':'100.0000',party_ref:'VENDOR-1',project_ref:null,property_ref:null,provider_trace:{trace_version:'WBS_PROVIDER_SOURCE_TRACE_V1',domain:'PAYABLES',disposition:'RETAINED',invoice_date:`2026-0${n}-01`,accrual:{charge_code:'INSURANCE'}}}]}];},evidenceReader:async({sourceDocumentId})=>{evidenceReads++;const n=Number(sourceDocumentId.slice(0,8));return {signature_verified:true,admission_status:'ADMITTED',accounting_period_id:id(n),source_row_hash:hash(String((n+1)%10))};}});
  const result=await service.analyze({tenantId:id(80),entityId:id(1),currentAccountingPeriodId:id(5)});
  assert.equal(result.finding_count,1);assert.equal(result.findings[0].ratio_basis_points,50000);assert.equal(detailReads,4);assert.equal(evidenceReads,4);assert.deepEqual(result.action_flags,{can_create_draft:false,can_review:false,can_approve:false,can_post:false});
});
test('ignores unsigned or unadmitted documents before deterministic analysis',async()=>{const service=createAiVendorInvoiceAnomalyService({sourceReader:async()=>documents,policyReader:async()=>policy,detailReader:async({sourceDocumentId})=>[{source_document_id:sourceDocumentId,payload_hash:hash('a'),currency:'USD',lines:[]}],evidenceReader:async()=>({signature_verified:false,admission_status:'REJECTED',accounting_period_id:id(2),source_row_hash:hash('b')})});const result=await service.analyze({tenantId:id(80),entityId:id(1),currentAccountingPeriodId:id(5)});assert.equal(result.scanned_line_count,0);assert.equal(result.finding_count,0);});
test('materializes the recomputed batch through one idempotent writer without accounting authority',async()=>{let written;const receipt={schema_version:'AI_VENDOR_INVOICE_AMOUNT_ANOMALY_RUN_RECEIPT_V1',can_create_draft:false,can_review:false,can_approve:false,can_post:false};const service=createAiVendorInvoiceAnomalyService({sourceReader:async()=>[],policyReader:async()=>policy,detailReader:async()=>[],evidenceReader:async()=>null,materializeWriter:async input=>(written=input,receipt)});const result=await service.analyzeAndMaterialize({tenantId:id(80),entityId:id(1),currentAccountingPeriodId:id(5),idempotencyKey:'vendor-anomaly-run-001'});assert.equal(result,receipt);assert.equal(written.accountingPeriodId,id(5));assert.equal(written.batch.finding_count,0);assert.equal(written.idempotencyKey,'vendor-anomaly-run-001');});
