import assert from 'node:assert/strict';import test from 'node:test';import {createAiVendorMonthlySpendAnomalyService} from '../runtime/ai-vendor-monthly-spend-anomaly-service.mjs';
const id=n=>`${String(n).padStart(8,'0')}-0000-4000-8000-${String(n).padStart(12,'0')}`,hash=n=>`sha256:${Number(n).toString(16).padStart(64,'0')}`,tenantId=id(1),entityId=id(2),current=id(9),periodIds=[id(3),id(4),id(5),current],actions={can_create_draft:false,can_review:false,can_approve:false,can_post:false};
const policy={schema_version:'AI_VENDOR_INVOICE_AMOUNT_ANOMALY_POLICY_V1',setting_snapshot_id:id(90),setting_snapshot_hash:hash(9),policy_version:1,minimum_history_periods:3,ratio_threshold_basis_points:30000,minimum_absolute_delta:'200.0000'};
const row=(n,period,amount)=>({source_document_id:id(n),source_document_line_id:id(n+100),source_payload_hash:hash(n),source_line_hash:hash(n+1),entity_id:entityId,accounting_period_id:period,vendor_ref:'V-1',vendor_name:'V-1',currency:'USD',amount:`${amount}.0000`,invoice_date:'2026-08-01',project_ref:null,property_ref:null,cost_category_ref:'REPAIRS',retained_outcome:'STAGING_REVIEW_REQUIRED',exception_codes:[],source_admission_status:'ADMITTED',signature_verified:true});
const population=rows=>({schema_version:'AI_VENDOR_MONTHLY_SPEND_SOURCE_POPULATION_V1',current_accounting_period_id:current,selected_period_ids:periodIds,selected_periods:periodIds.map((period_id,index)=>({period_id,period_code:`2026-0${index+5}`,period_start:`2026-0${index+5}-01`,period_end:`2026-0${index+5}-28`})),history_period_count:3,population_line_count:rows.length,population_complete:true,admission_proofs:[{admission_id:id(200),snapshot_id:id(201),request_hash:hash(200),package_hash:hash(201),package_raw_hash:hash(202),control_totals_hash:hash(203),row_count:rows.length}],approved_policy:policy,rows,action_flags:actions});
const fixtures=()=>[row(10,id(3),100),row(20,id(4),100),row(30,id(5),100),row(40,current,125),row(50,current,125),row(60,current,125),row(70,current,125)];

test('service detects split monthly spend from one server-derived complete population read',async()=>{let calls=0;const service=createAiVendorMonthlySpendAnomalyService({populationReader:async()=>{calls++;return population(fixtures());}}),result=await service.analyze({tenantId,entityId,currentAccountingPeriodId:current});assert.equal(calls,1);assert.equal(result.finding_count,1);assert.equal(result.findings[0].current_month_total,'500.0000');assert.equal(result.findings[0].current_source_trace.length,4);assert.deepEqual(result.action_flags,actions);});
test('explicit null invoice date is counted but cannot poison otherwise complete history',async()=>{const rows=[...fixtures(),{...row(80,current,999),invoice_date:null,retained_outcome:'EXCEPTION_REVIEW_REQUIRED',exception_codes:['WBS_PAYABLE_INVOICE_DATE_MISSING']}],service=createAiVendorMonthlySpendAnomalyService({populationReader:async()=>population(rows)}),result=await service.analyze({tenantId,entityId,currentAccountingPeriodId:current});assert.equal(result.excluded_incomplete_line_count,1);assert.equal(result.scanned_line_count,7);assert.equal(result.finding_count,1);assert.equal(result.findings[0].current_month_total,'500.0000');});
test('malformed retained evidence cannot hide behind an explicit null invoice date',async()=>{const malformed={...row(80,current,999),invoice_date:null,vendor_ref:undefined,retained_outcome:'EXCEPTION_REVIEW_REQUIRED',exception_codes:['WBS_PAYABLE_INVOICE_DATE_MISSING']},service=createAiVendorMonthlySpendAnomalyService({populationReader:async()=>population([malformed])});await assert.rejects(()=>service.analyze({tenantId,entityId,currentAccountingPeriodId:current}),error=>error.code==='AI_VENDOR_MONTHLY_SPEND_SOURCE_INVALID');});
test('service rejects drifted population metadata, impossible periods, action authority, and unsafe extra fields',async()=>{const invalidDate=population([]);invalidDate.selected_periods[0]={...invalidDate.selected_periods[0],period_end:'2026-02-30'};const duplicatePeriod=population([]);duplicatePeriod.selected_periods[1]={...duplicatePeriod.selected_periods[1],period_id:duplicatePeriod.selected_periods[0].period_id};for(const changed of [{...population([]),population_complete:false},{...population([]),selected_period_ids:[current]},invalidDate,duplicatePeriod,{...population([]),action_flags:{...actions,can_post:true}},{...population([]),token:'secret'}]){const service=createAiVendorMonthlySpendAnomalyService({populationReader:async()=>changed});await assert.rejects(()=>service.analyze({tenantId,entityId,currentAccountingPeriodId:current}),error=>error.code==='AI_VENDOR_MONTHLY_SPEND_POPULATION_INVALID');}});
test('database population failure is propagated after exactly one read and no N+1 boundary exists',async()=>{let calls=0;const service=createAiVendorMonthlySpendAnomalyService({populationReader:async()=>{calls++;throw Object.assign(new Error('complete population exceeds bound'),{code:'54000'});}});await assert.rejects(()=>service.analyze({tenantId,entityId,currentAccountingPeriodId:current}),error=>error.code==='54000');assert.equal(calls,1);});
