import test,{after,before} from 'node:test';import assert from 'node:assert/strict';import {createHash,randomUUID} from 'node:crypto';import {createConnection} from 'node:net';import {request as httpsRequest} from 'node:https';
import {S3AttachmentStorage,HttpVirusScanner,AttachmentEvidenceService} from '../runtime/attachment-storage.mjs';import {runtimeConfig} from '../runtime/config.mjs';import {createPool} from '../runtime/db.mjs';import {PostgresAccountingKernel} from '../runtime/kernel-repository.mjs';import {PostgresContextIssuer} from '../runtime/context-issuer.mjs';

const endpoint=process.env.REFS_MINIO_ENDPOINT,clamavPort=Number(process.env.REFS_CLAMAV_PORT),scannerEndpoint=process.env.REFS_SCANNER_ENDPOINT,scannerToken=process.env.REFS_SCANNER_TOKEN;
if(!endpoint||!clamavPort||!scannerEndpoint||!scannerToken)throw new Error('Container attachment test environment is required');
const hash=bytes=>`sha256:${createHash('sha256').update(bytes).digest('hex')}`;
const insecureTlsFetch=(input,init={})=>new Promise((resolve,reject)=>{const url=new URL(input),req=httpsRequest(url,{method:init.method||'GET',headers:init.headers,rejectUnauthorized:false},res=>{const chunks=[];res.on('data',chunk=>chunks.push(chunk));res.on('end',()=>resolve(new Response(Buffer.concat(chunks),{status:res.statusCode,headers:res.headers})));});req.on('error',reject);if(init.signal){const abort=()=>req.destroy(init.signal.reason||new Error('aborted'));if(init.signal.aborted)return abort();init.signal.addEventListener('abort',abort,{once:true});}if(init.body)req.write(init.body);req.end();});
const storage=new S3AttachmentStorage({endpoint,bucket:'refs-evidence',region:'us-east-1',accessKeyId:process.env.MINIO_ROOT_USER,secretAccessKey:process.env.MINIO_ROOT_PASSWORD,allowInsecureLoopbackForTests:true});
const scanner=new HttpVirusScanner({endpoint:scannerEndpoint,bearerToken:scannerToken,fetcher:insecureTlsFetch,retryBaseMs:10});
let adminPool,runtimePool,issuerPool;const config=runtimeConfig();
before(async()=>{adminPool=await createPool({databaseUrl:config.migrationDatabaseUrl,applicationName:'refs-attachment-gate-admin'});runtimePool=await createPool({databaseUrl:config.databaseUrl,applicationName:'refs-attachment-gate-runtime'});issuerPool=await createPool({databaseUrl:config.contextIssuerDatabaseUrl,applicationName:'refs-attachment-gate-issuer'});});
after(async()=>{if(adminPool)await adminPool.query('TRUNCATE tenant CASCADE').catch(()=>{});await Promise.allSettled([adminPool?.end(),runtimePool?.end(),issuerPool?.end()]);});

function clam(command){return new Promise((resolve,reject)=>{const socket=createConnection({host:'127.0.0.1',port:clamavPort}),chunks=[];socket.setTimeout(30000);socket.on('connect',()=>command(socket));socket.on('data',chunk=>chunks.push(chunk));socket.on('end',()=>resolve(Buffer.concat(chunks).toString().replaceAll('\0','').trim()));socket.on('timeout',()=>socket.destroy(new Error('ClamAV timeout')));socket.on('error',reject);});}
const ping=()=>clam(socket=>socket.end('zPING\0'));
const scan=bytes=>clam(socket=>{socket.write('zINSTREAM\0');const size=Buffer.alloc(4);size.writeUInt32BE(bytes.length);socket.write(size);socket.write(bytes);socket.end(Buffer.alloc(4));});

test('real MinIO preserves immutable versions and production SigV4 metadata',async()=>{
  const first=Buffer.from('X5O!P%@AP[4\\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*'),firstHash=hash(first),reservation=await storage.reserveUpload({tenantId:'00000000-0000-4000-8000-000000000001',entityId:'00000000-0000-4000-8000-000000000002',mediaType:'application/pdf',contentHash:firstHash});
  let response=await fetch(reservation.uploadUrl,{method:'PUT',headers:reservation.requiredHeaders,body:first});assert.equal(response.ok,true);
  const observedV1=await storage.inspect(reservation.storageRef);assert.equal(observedV1.contentHash,firstHash);assert.ok(observedV1.storageVersion);
  const second=Buffer.from('refs changed attachment v2'),secondHash=hash(second),key=storage.parseRef(reservation.storageRef),secondUrl=storage.presignPut(key,{mediaType:'application/pdf',contentHash:secondHash});
  response=await fetch(secondUrl,{method:'PUT',headers:{'content-type':'application/pdf','x-amz-meta-sha256':secondHash},body:second});assert.equal(response.ok,true);
  const observedV2=await storage.inspect(reservation.storageRef);assert.notEqual(observedV2.storageVersion,observedV1.storageVersion);assert.equal(observedV2.contentHash,secondHash);
  const retained=await storage.inspect(reservation.storageRef,{versionId:observedV1.storageVersion});assert.equal(retained.storageVersion,observedV1.storageVersion);assert.equal(retained.contentHash,firstHash);
  assert.match(await scan(Buffer.from(await storage.readVersion(reservation.storageRef,observedV1.storageVersion))),/FOUND$/);
  assert.match(await scan(Buffer.from(await storage.readVersion(reservation.storageRef,observedV2.storageVersion))),/OK$/);
  assert.equal((await scanner.scan({storageRef:reservation.storageRef,storageVersion:observedV1.storageVersion})).clean,false);assert.equal((await scanner.scan({storageRef:reservation.storageRef,storageVersion:observedV2.storageVersion})).clean,true);
  await assert.rejects(scanner.scan({storageRef:reservation.storageRef,storageVersion:'missing-version'}),/503/);
  const unauthorized=new HttpVirusScanner({endpoint:scannerEndpoint,bearerToken:'wrong-token',fetcher:insecureTlsFetch});await assert.rejects(unauthorized.scan({storageRef:reservation.storageRef,storageVersion:observedV2.storageVersion}),/401/);
});

test('reserve upload finalize scan and PostgreSQL audit use exact object versions',async()=>{await adminPool.query('TRUNCATE tenant CASCADE');const tenantId=randomUUID(),entityId=randomUUID(),uploader='attachment-gate-uploader',scannerActor='attachment-gate-scanner';await adminPool.query("INSERT INTO tenant(tenant_id,tenant_code,name) VALUES($1,$2,'Attachment gate')",[tenantId,`T${tenantId.replaceAll('-','').slice(0,8)}`.toUpperCase()]);await adminPool.query("INSERT INTO entity(entity_id,tenant_id,entity_code,source_system,source_entity_id,name,base_currency) VALUES($1,$2,$3,'TEST',$3,'Attachment entity','USD')",[entityId,tenantId,`E${entityId.replaceAll('-','').slice(0,8)}`.toUpperCase()]);await adminPool.query("INSERT INTO runtime_actor_grant(tenant_id,actor_id,entity_id,permission) VALUES($1,$2,$3,'ATTACHMENT.CREATE'),($1,$4,$3,'ATTACHMENT.FINALIZE')",[tenantId,uploader,entityId,scannerActor]);const kernel=actor=>new PostgresAccountingKernel(runtimePool,{sessionProvider:async()=>new PostgresContextIssuer(issuerPool,{principalProvider:async()=>({trusted:true,actorId:actor})}).issue({tenantId})});const service=new AttachmentEvidenceService({storage,scanner,uploaderKernelFactory:async()=>kernel(uploader),scannerKernelFactory:async()=>kernel(scannerActor)});
  const exercise=async(bytes,key)=>{const args={tenantId,entityId,name:`${key}.pdf`,mediaType:'application/pdf',sizeBytes:bytes.length,contentHash:hash(bytes),idempotencyKey:`reserve-${key}`},reserved=await service.reserve({trusted:true,actorId:uploader},args),upload=await fetch(reserved.upload_url,{method:'PUT',headers:reserved.required_headers,body:bytes});assert.equal(upload.ok,true);return service.finalize({trusted:true,actorId:uploader},{tenantId,entityId,attachmentId:reserved.attachment_id,idempotencyKey:`finalize-${key}`});};
  const clean=await exercise(Buffer.from('ordinary independently-scanned accounting evidence'),'clean');assert.equal(clean.status,'VERIFIED_CLEAN');const infected=await exercise(Buffer.from('X5O!P%@AP[4\\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*'),'eicar');assert.equal(infected.status,'REJECTED');const events=(await adminPool.query("SELECT actor_id,event_type FROM audit_event WHERE object_id IN ($1,$2) AND event_type IN ('ATTACHMENT_RESERVED','ATTACHMENT_FINALIZE_REQUESTED','ATTACHMENT_FINALIZED') ORDER BY object_id,event_type",[clean.attachment_id,infected.attachment_id])).rows;assert.equal(events.length,6);assert.equal(events.filter(row=>row.event_type==='ATTACHMENT_FINALIZED'&&row.actor_id===scannerActor).length,2);
});

test('real ClamAV accepts clean bytes and detects the EICAR test signature',async()=>{
  assert.equal(await ping(),'PONG');assert.match(await scan(Buffer.from('ordinary accounting evidence')),/OK$/);
  const eicar=Buffer.from('X5O!P%@AP[4\\PZX54(P^)7CC)7}$EICAR-STANDARD-ANTIVIRUS-TEST-FILE!$H+H*');assert.match(await scan(eicar),/FOUND$/);
});
