import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';
import {S3AttachmentStorage,HttpVirusScanner,AttachmentEvidenceService} from '../runtime/attachment-storage.mjs';
const tenantId=randomUUID(),entityId=randomUUID(),contentHash=`sha256:${'a'.repeat(64)}`,clock=()=>new Date('2026-08-02T12:00:00Z');
const config={endpoint:'https://s3.example.com',bucket:'refs-evidence',region:'us-east-1',accessKeyId:'AKIAEXAMPLE',secretAccessKey:'secret-example',clock};

test('S3 reservation creates a scoped SigV4 PUT with signed content metadata',async()=>{const storage=new S3AttachmentStorage({...config,fetcher:async()=>new Response(null,{status:204})});const result=await storage.reserveUpload({tenantId,entityId,mediaType:'application/pdf',contentHash});const url=new URL(result.uploadUrl);assert.match(result.storageRef,new RegExp(`^s3://refs-evidence/refs-attachments/${tenantId}/${entityId}/`));assert.equal(url.searchParams.get('X-Amz-Algorithm'),'AWS4-HMAC-SHA256');assert.equal(url.searchParams.get('X-Amz-SignedHeaders'),'content-type;host;x-amz-meta-sha256');assert.match(url.searchParams.get('X-Amz-Signature'),/^[0-9a-f]{64}$/);assert.match(result.storageVersion,/^pending:/);});
test('S3 HEAD returns authoritative metadata and requires a versioned object',async()=>{const storage=new S3AttachmentStorage({...config,fetcher:async(_url,init)=>{assert.equal(init.method,'HEAD');assert.match(init.headers.authorization,/AWS4-HMAC-SHA256/);return new Response(null,{status:200,headers:{'content-length':'42','content-type':'application/pdf','x-amz-meta-sha256':contentHash,'x-amz-version-id':'version-7'}});}});const reserved=await storage.reserveUpload({tenantId,entityId,mediaType:'application/pdf',contentHash});assert.deepEqual(await storage.inspect(reserved.storageRef),{sizeBytes:42,mediaType:'application/pdf',contentHash,storageVersion:'version-7'});});
test('S3 configuration and object scope fail closed',async()=>{assert.throws(()=>new S3AttachmentStorage({...config,endpoint:'http://s3.example.com'}),/HTTPS/);const storage=new S3AttachmentStorage({...config,fetcher:async()=>new Response(null,{status:200})});await assert.rejects(storage.inspect('s3://other/escape'),/outside configured bucket/);});
test('scanner requires HTTPS and validates its response',async()=>{assert.throws(()=>new HttpVirusScanner({endpoint:'http://scan.example',bearerToken:'x'}),/HTTPS/);const scanner=new HttpVirusScanner({endpoint:'https://scan.example',bearerToken:'secret',fetcher:async(_url,init)=>{assert.equal(init.headers.authorization,'Bearer secret');return new Response(JSON.stringify({clean:true,scan_ref:'clamav:1'}),{status:200,headers:{'content-type':'application/json'}});}});assert.deepEqual(await scanner.scan({storageRef:'s3://b/k',storageVersion:'v1'}),{clean:true,scanRef:'clamav:1'});});
test('attachment service compensates orphan reservations and finalizes only observed/scanned metadata',async()=>{let deleted=false,finalArgs;const storage={reserveUpload:async()=>({storageRef:'s3://b/k',storageVersion:'pending:1',uploadUrl:'https://upload',requiredHeaders:{},expiresAt:'later'}),deleteReservation:async()=>{deleted=true;},inspect:async()=>({sizeBytes:9,mediaType:'application/pdf',contentHash,storageVersion:'v9'})};const scanner={scan:async()=>({clean:true,scanRef:'scan:9'})};const failing=new AttachmentEvidenceService({storage,scanner,uploaderKernelFactory:async()=>({reserveAttachment:async()=>{throw new Error('db');}}),scannerKernelFactory:async()=>({})});await assert.rejects(failing.reserve({},{}),/db/);assert.equal(deleted,true);const service=new AttachmentEvidenceService({storage,scanner,uploaderKernelFactory:async()=>({}),scannerKernelFactory:async()=>({finalizeAttachment:async args=>{finalArgs=args;return {status:'VERIFIED_CLEAN'};}})});assert.equal((await service.finalize({}, {tenantId,entityId,attachmentId:randomUUID(),storageRef:'s3://b/k',idempotencyKey:'final-1'})).status,'VERIFIED_CLEAN');assert.equal(finalArgs.storageVersion,'v9');assert.equal(finalArgs.scanRef,'scan:9');});
