import test from 'node:test';import assert from 'node:assert/strict';
import {AttachmentCleanupWorker} from '../runtime/attachment-cleanup-worker.mjs';
import {attachmentCleanupConfig} from '../runtime/start-attachment-cleanup-worker.mjs';

const principal={trusted:true,actorId:'cleanup-service',roleCode:'SERVICE'};const scope={tenantId:'t1',entityId:'e1'};
test('production composition requires a dedicated actor and explicit entity scopes',()=>{const base={ATTACHMENT_CLEANUP_ACTOR_ID:'cleanup-service',ATTACHMENT_CLEANUP_SCOPES:JSON.stringify([scope]),S3_ENDPOINT:'https://s3.example.com',S3_BUCKET:'refs',S3_REGION:'us-east-1',S3_ACCESS_KEY_ID:'key',S3_SECRET_ACCESS_KEY:'secret'};assert.equal(attachmentCleanupConfig(base).actorId,'cleanup-service');assert.throws(()=>attachmentCleanupConfig({...base,ATTACHMENT_CLEANUP_ACTOR_ID:''}),/required/);assert.throws(()=>attachmentCleanupConfig({...base,ATTACHMENT_CLEANUP_SCOPES:'[]'}),/tenantId\/entityId/);});
test('worker starts, publishes health and stops gracefully',async()=>{let release;const sleeper=()=>new Promise(resolve=>{release=resolve;});const service={runOnce:async()=>[{status:'CLEANED'}]};const worker=new AttachmentCleanupWorker({service,principal,scopes:[scope],intervalMs:10,sleeper});worker.start();for(let i=0;i<20&&worker.metrics.cycles===0;i++)await new Promise(resolve=>setTimeout(resolve,1));assert.equal(worker.health().ok,true);assert.equal(worker.metrics.cleaned,1);release();await worker.stop();assert.equal(worker.health().running,false);});
test('two workers atomically consume a shared queue without duplicates',async()=>{const queue=new Map([['a',false],['b',false],['c',false]]),seen=[];const service={runOnce:async(_principal,args)=>{const picked=[];for(const [id,claimed] of queue){if(!claimed&&picked.length<args.limit){queue.set(id,true);picked.push({status:'CLEANED',id});seen.push(id);}}return picked;}};const one=new AttachmentCleanupWorker({service,principal,scopes:[scope],batchSize:2}),two=new AttachmentCleanupWorker({service,principal:{...principal,actorId:'cleanup-service-2'},scopes:[scope],batchSize:2});await Promise.all([one.runCycle(),two.runCycle()]);assert.deepEqual([...new Set(seen)].sort(),['a','b','c']);assert.equal(seen.length,3);});
test('worker backs off after failure and later recovers',async()=>{let calls=0;const delays=[];const service={runOnce:async()=>{calls++;if(calls===1)throw new Error('temporary');return [];}};const worker=new AttachmentCleanupWorker({service,principal,scopes:[scope],intervalMs:10,maxBackoffMs:40,sleeper:async ms=>{delays.push(ms);if(delays.length===2)worker.abort.abort();}});worker.start();await worker.loopPromise;assert.deepEqual(delays,[20,10]);assert.equal(worker.metrics.cycleErrors,1);assert.equal(worker.metrics.cycles,1);});
