import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {readFile} from 'node:fs/promises';
import {MIGRATION_MANIFEST} from '../runtime/migration-manifest.mjs';
const digest=value=>createHash('sha256').update(value).digest('hex');
test('migration is manifest-bound, reversible, scoped, keyset-paged, and read-only',async()=>{const name='361_bill_payment_register_read.sql',entry=MIGRATION_MANIFEST.find(row=>row.name===name),up=await readFile(new URL('../db/migrations/'+name,import.meta.url),'utf8'),down=await readFile(new URL('../db/migrations/down/'+name,import.meta.url),'utf8');assert.equal(entry.up,digest(up));assert.equal(entry.down,digest(down));assert.match(up,/refs_assert_scope\(p_tenant,p_entity,'AP\.VIEW'\)/);assert.match(up,/period_id=p_period/);assert.match(up,/\(po\.created_at,po\.payment_occurrence_id\)</);assert.match(up,/object_type='PAYMENT_OCCURRENCE'/);assert.match(up,/AP_PAYMENT_DRAFT_CREATED/);assert.match(up,/AP_PAYMENT_POSTED/);assert.match(up,/'can_initiate_payment',false/);assert.doesNotMatch(up,/\b(?:INSERT|UPDATE|DELETE)\s+(?:INTO\s+|FROM\s+)?(?:payment_occurrence|business_document|journal_entry|journal_line|ledger_line|bank_match|audit_event)\b/i);assert.match(down,/DROP FUNCTION refs_read_bill_payment_register/);});
test('bank identity migration is manifest-bound, reversible, and reads only the controlled cash line',async()=>{const name='362_bill_payment_register_bank_identity.sql',entry=MIGRATION_MANIFEST.find(row=>row.name===name),up=await readFile(new URL('../db/migrations/'+name,import.meta.url),'utf8'),down=await readFile(new URL('../db/migrations/down/'+name,import.meta.url),'utf8');assert.equal(entry.up,digest(up));assert.equal(entry.down,digest(down));assert.match(up,/BILL_PAYMENT_REGISTER_V2/);assert.match(up,/jl\.line_no=2/);assert.match(up,/jl\.debit_amount=0 AND jl\.credit_amount=po\.amount/);assert.match(up,/'cash_account_code',cash_line\.cash_account_code/);assert.match(up,/'bank_member_ref',cash_line\.bank_member_ref/);assert.doesNotMatch(up,/\b(?:INSERT|UPDATE|DELETE)\s+(?:INTO\s+|FROM\s+)?(?:payment_occurrence|business_document|journal_entry|journal_line|ledger_line|bank_match|audit_event)\b/i);assert.match(down,/BILL_PAYMENT_REGISTER_V1/);assert.doesNotMatch(down,/cash_account_code/);});
test('OpenAPI publishes the exact read-only Bill Payment contract',async()=>{const document=JSON.parse(await readFile(new URL('../api/openapi-accounting.json',import.meta.url),'utf8')),operation=document.paths['/entities/{entityId}/ap/bill-payments']?.get;assert.equal(operation.operationId,'readBillPaymentRegister');assert.match(operation.description,/Requires AP\.VIEW/);assert.match(operation.description,/Read-only/);const envelope=operation.responses['200'].content['application/json'].schema,body=envelope.properties.data;assert.equal(envelope.additionalProperties,false);assert.equal(body.properties.schema_version.const,'BILL_PAYMENT_REGISTER_V2');assert.equal(body.properties.action_flags.properties.can_initiate_payment.const,false);assert.equal(body.properties.action_flags.properties.can_approve.const,false);assert.equal(body.properties.action_flags.properties.can_void.const,false);assert.equal(body.properties.action_flags.properties.can_release.const,false);assert.equal(body.properties.rows.items.additionalProperties,false);for(const field of ['cash_account_code','bank_member_ref','payment_occurrence_id','business_document_id','journal_entry_id','journal_line_id','ledger_line_id','bank_match_id','draft_audit_event_id','posted_audit_event_id'])assert.ok(body.properties.rows.items.required.includes(field));});
