import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtemp,writeFile,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {createHash} from 'node:crypto';
import {verifyFixedAssetAcquisitionBrowserReceipt} from '../runtime/fixed-asset-acquisition-browser-receipt.mjs';

test('acquisition browser receipt binds the release, real HTTP write, cross-period read, identity and report result',async()=>{
 const dir=await mkdtemp(join(tmpdir(),'refs-asset-acquisition-receipt-')),sha='a'.repeat(40),screenshots=[],uiPeriod='11111111-1111-4111-8111-111111111111',period='22222222-2222-4222-8222-222222222222',journal='33333333-3333-4333-8333-333333333333',source='44444444-4444-4444-8444-444444444444';
 try{
  for(const [name,width,height] of [['draft-desktop.png',1280,900],['draft-mobile.png',390,844],['lineage-desktop.png',1280,900]]){const bytes=Buffer.alloc(24);Buffer.from('89504e470d0a1a0a','hex').copy(bytes);bytes.writeUInt32BE(width,16);bytes.writeUInt32BE(height,20);await writeFile(join(dir,name),bytes);screenshots.push({name,viewport:{width,height},sha256:createHash('sha256').update(bytes).digest('hex')});}
  const business={journal_entry_id:journal,period_id:period,status:'POSTED',ledger_line_count:2,source_document_id:source,gl_lines:[{ledger_line_id:'55555555-5555-4555-8555-555555555555',account_code:'150100',debit_amount:'25000.0000',credit_amount:'0.0000',source_document_ids:[source]},{ledger_line_id:'66666666-6666-4666-8666-666666666666',account_code:'291001',debit_amount:'0.0000',credit_amount:'25000.0000',source_document_ids:[source]}],trial_balance:[{account_code:'150100',period_debit:'25000.0000',period_credit:'0.0000',display_balance:'25000.0000',source_document_ids:[source]},{account_code:'291001',period_debit:'0.0000',period_credit:'25000.0000',display_balance:'-25000.0000',source_document_ids:[source]}],asset_status:'ACTIVE',posted_cost_balance:'25000.0000',maker_later_workflow_denied:true,identity_denials:[401,401],acquisition_posting_count:1};
  const result={kind:'OWNED_POSTGRES_ACQUISITION_BROWSER_E2E',passed:true,sha,worktreeClean:true,browserBundleSha256:'b'.repeat(64),playwrightModule:'owned-playwright',chromiumVersion:'owned-chromium',scope:'Owned test; not production OIDC.',ui_period_id:uiPeriod,journal_period_id:period,actor_access:{permissions:['GL.JE.VIEW','FIXED_ASSET.REGISTER.VIEW','GL.JE.CREATE'],session_refresh_required:false},reader_access:{permissions:['GL.REPORT.VIEW','FIXED_ASSET.REGISTER.VIEW','GL.JE.VIEW'],session_refresh_required:false},reads:[{method:'GET',status:200,path:'/access/self',identity:'MAKER'},{method:'GET',status:200,path:'/fixed-assets/register?',identity:'MAKER'},{method:'GET',status:200,path:'/fixed-assets/register/id?',identity:'MAKER'},{method:'GET',status:200,path:'/acquisition-options',identity:'MAKER'},{method:'GET',status:200,path:'/journal-entries/id',identity:'MAKER'},{method:'GET',status:200,path:'/source-documents/id',identity:'READER'},{method:'GET',status:200,path:'/general-ledger/entries?',identity:'READER'},{method:'GET',status:200,path:'/financial-statements?',identity:'READER'}],writes:[{method:'POST',status:201,path:'/acquisitions',identity:'MAKER'}],checks:['real-register-list-and-detail','real-options-and-source-date','single-real-post-under-double-click','cross-period-fresh-journal-read','mobile-no-horizontal-overflow','draft-refresh-resumes-same-journal-without-post','posted-refresh-shows-cost-and-activity','late-real-source-response-ignored-after-period-switch','opened-real-source-drill-closes-on-period-switch','real-source-journal-gl-report-lineage','lineage-no-horizontal-overflow'],errors:[],http_errors:[],screenshots,business};
  const save=value=>writeFile(join(dir,'result.json'),JSON.stringify(value));await save(result);await verifyFixedAssetAcquisitionBrowserReceipt(dir,sha);
  for(const patch of [{sha:'c'.repeat(40)},{worktreeClean:false},{ui_period_id:period},{writes:[]},{reads:[]},{checks:[]},{actor_access:{permissions:['GL.JE.POST'],session_refresh_required:false}},{reader_access:{permissions:['GL.JE.POST'],session_refresh_required:false}}]){await save({...result,...patch});await assert.rejects(verifyFixedAssetAcquisitionBrowserReceipt(dir,sha));}
  const mutations=[value=>{delete value.business.source_document_id;},value=>{value.business.gl_lines[0].debit_amount='1.0000';},value=>{value.business.gl_lines[0].source_document_ids=[];},value=>{value.business.trial_balance[1].period_credit='1.0000';},value=>{value.business.trial_balance[1].source_document_ids=[];},value=>{value.business.asset_status='REGISTERED';},value=>{value.business.posted_cost_balance='0.0000';},value=>{value.business.maker_later_workflow_denied=false;},value=>{value.business.identity_denials=[401];},value=>{value.business.acquisition_posting_count=0;}];
  for(const mutate of mutations){const changed=structuredClone(result);mutate(changed);await save(changed);await assert.rejects(verifyFixedAssetAcquisitionBrowserReceipt(dir,sha));}
 }finally{await rm(dir,{recursive:true,force:true});}
});
