import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {createAccountingApi} from '../api/accounting-http.mjs';
import {validFixedAssetDisposalOptions} from '../api/fixed-asset-disposal-options-contract.mjs';

const tenantId=randomUUID(),entityId=randomUUID(),assetId=randomUUID(),periodId=randomUUID(),sourceId=randomUUID(),hash='sha256:'+'a'.repeat(64);
const snapshot={schema_version:'FIXED_ASSET_DISPOSAL_SNAPSHOT_V1',tenant_id:tenantId,entity_id:entityId,asset_id:assetId,asset_tag:'BLDG-1',asset_status:'ACTIVE',register_evidence_hash:hash,currency:'USD',member_trace:{project_ref:'P-1',property_ref:null,allocation_basis:'SOURCE_DIMENSIONED'},placed_in_service_date:'2026-01-01',period:{period_id:periodId,period_code:'2026-07',starts_on:'2026-07-01',ends_on:'2026-07-31',status:'OPEN'},disposal_date:'2026-07-25',cost_basis:'25000.0000',posted_cost_balance:'25000.0000',accumulated_depreciation:'2000.0000',impairment_reversals:[],accumulated_impairment:'0.0000',carrying_value:'23000.0000',asset_account_code:'150100',accumulated_depreciation_account_code:'159100',acquisition_posted:true,disposal_recorded:false,later_asset_movement:false,impairment_date_conflict:false,impairment_evidence_valid:true,readiness_status:'READY'};
const options={schema_version:'FIXED_ASSET_DISPOSAL_OPTIONS_V1',tenant_id:tenantId,entity_id:entityId,asset_id:assetId,options_hash:hash,snapshot,sources:[{source_document_id:sourceId,source_document_version:1,source_payload_hash:hash,source_module:'bankFeed',document_type:'BANK_TRANSACTION',document_no:'SALE-1',business_date:'2026-07-25',accounting_date:'2026-07-25',gross_amount:'24000.0000',status:'READY_FOR_DRAFT'}],proceeds_accounts:[{account_code:'111000',account_name:'Bank',required_member_type:'BANK'}],members:[{member_ref:'BANK-1',member_type:'BANK',display_name:'Operating bank'}],gain_loss_accounts:[{account_code:'780100',account_name:'Asset disposal gain or loss'}],pending_journals:[],more_pending_journals:false,readiness_status:'READY',requires_command_validation:true};
const receipt={schema_version:'FIXED_ASSET_DISPOSAL_DRAFT_V1',binding_id:randomUUID(),journal_entry_id:randomUUID(),asset_id:assetId,period_id:periodId,source_document_id:sourceId,source_document_version:1,source_payload_hash:hash,source_link_id:randomUUID(),register_evidence_hash:hash,options_hash:hash,proceeds:'24000.0000',accumulated_depreciation:'2000.0000',accumulated_impairment:'0.0000',carrying_value:'23000.0000',gain_or_loss:'1000.0000',status:'DRAFT',revision:1,idempotent:false};
const readRequest={method:'GET',url:`/api/v1/entities/${entityId}/fixed-assets/register/${assetId}/disposal-options?periodId=${periodId}&disposalDate=2026-07-25`};
const writeRequest={method:'POST',url:`/api/v1/entities/${entityId}/fixed-assets/register/${assetId}/disposals`,headers:{'Idempotency-Key':'fixed-asset-disposal-http-1'},body:{periodId,journalNumber:'DISP-1',disposalDate:'2026-07-25',sourceDocumentId:sourceId,expectedSourceVersion:1,expectedSourceHash:hash,proceedsAccountCode:'111000',proceedsMemberRef:'BANK-1',gainLossAccountCode:'780100',expectedOptionsHash:hash,reason:'Record the evidence-bound asset disposal draft.'}};

test('disposal options read binds authenticated scope and exact date',async()=>{let seen;const api=createAccountingApi({authenticate:async()=>({trusted:true,tenantId,actorId:'maker'}),kernelFactory:async()=>({readFixedAssetDisposalOptions:async args=>(seen=args,options)})});const response=await api(readRequest);assert.equal(response.status,200,JSON.stringify(response.body));assert.deepEqual(seen,{tenantId,entityId,assetId,periodId,disposalDate:'2026-07-25'});for(const request of [{...readRequest,url:readRequest.url+'&extra=1'},{...readRequest,headers:{'Idempotency-Key':'forbidden'}},{...readRequest,body:{}}])assert.equal((await api(request)).status,400);});

test('disposal command passes selections but no amount actor or tenant',async()=>{let seen;const api=createAccountingApi({authenticate:async()=>({trusted:true,tenantId,actorId:'maker'}),kernelFactory:async()=>({createFixedAssetDisposal:async args=>(seen=args,receipt)})});const response=await api(writeRequest);assert.equal(response.status,201,JSON.stringify(response.body));assert.deepEqual(seen,{tenantId,entityId,assetId,periodId,journalNumber:'DISP-1',disposalDate:'2026-07-25',sourceDocumentId:sourceId,expectedSourceVersion:1,expectedSourceHash:hash,proceedsAccountCode:'111000',proceedsMemberRef:'BANK-1',gainLossAccountCode:'780100',expectedOptionsHash:hash,reason:'Record the evidence-bound asset disposal draft.',idempotencyKey:'fixed-asset-disposal-http-1'});assert.equal(Object.hasOwn(writeRequest.body,'proceeds'),false);});

test('disposal command rejects injected accounting values and malformed selections before persistence',async()=>{let calls=0;const api=createAccountingApi({authenticate:async()=>({trusted:true,tenantId,actorId:'maker'}),kernelFactory:async()=>({createFixedAssetDisposal:async()=>{calls++;return receipt;}})});for(const patch of [{proceeds:'1.0000'},{actorId:'other'},{tenantId:randomUUID()},{expectedSourceVersion:0},{expectedSourceHash:'bad'},{expectedOptionsHash:'bad'},{proceedsAccountCode:null},{proceedsMemberRef:null},{proceedsMemberRef:'bad\nref'},{gainLossAccountCode:'bad account'},{disposalDate:'2026-02-30'}]){const response=await api({...writeRequest,body:{...writeRequest.body,...patch}});assert.equal(response.status,400,JSON.stringify({patch,response:response.body}));}assert.equal(calls,0);});

test('disposal command maps stale evidence and rejects malformed successful receipts',async()=>{for(const message of ['Disposal options changed','Disposal source changed or is unavailable']){const api=createAccountingApi({authenticate:async()=>({trusted:true,tenantId,actorId:'maker'}),kernelFactory:async()=>({createFixedAssetDisposal:async()=>{throw Object.assign(new Error(message),{code:'40001'});}})});const response=await api(writeRequest);assert.equal(response.status,412);assert.equal(response.body.code,'PRECONDITION_FAILED');}for(const patch of [{revision:0},{status:'POSTED'},{asset_id:randomUUID()},{source_document_id:randomUUID()},{gain_or_loss:'bad'}]){const api=createAccountingApi({authenticate:async()=>({trusted:true,tenantId,actorId:'maker'}),kernelFactory:async()=>({createFixedAssetDisposal:async()=>({...receipt,...patch})})});assert.equal((await api(writeRequest)).status,502,JSON.stringify(patch));}});

test('disposal readiness permits zero proceeds and requires a compatible account-member pair for positive proceeds',()=>{const scope={tenantId,entityId,assetId,periodId,disposalDate:'2026-07-25'},noCompatible={...options,members:[{member_ref:'CUSTOMER-1',member_type:'CUSTOMER',display_name:'Buyer'}],readiness_status:'BLOCKED_PROCEEDS_ACCOUNT_UNAVAILABLE'};assert.equal(validFixedAssetDisposalOptions(noCompatible,scope),true);assert.equal(validFixedAssetDisposalOptions({...noCompatible,readiness_status:'READY'},scope),false);const zero={...noCompatible,sources:[{...options.sources[0],gross_amount:'0.0000'}],readiness_status:'READY'};assert.equal(validFixedAssetDisposalOptions(zero,scope),true);assert.equal(validFixedAssetDisposalOptions({...zero,readiness_status:'BLOCKED_PROCEEDS_ACCOUNT_UNAVAILABLE'},scope),false);});
