import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {createAccountingApi} from '../api/accounting-http.mjs';
const tenantId=randomUUID(),entityId=randomUUID(),assetId=randomUUID(),periodId=randomUUID(),hash='sha256:'+'a'.repeat(64);
const body={periodId,journalNumber:'DEP-2026-07-001',journalDate:'2026-07-31',expectedRegisterEvidenceHash:hash,expectedScheduleHash:hash,reason:'Record reviewed monthly depreciation'};
const receipt={schema_version:'FIXED_ASSET_DEPRECIATION_DRAFT_V1',journal_entry_id:randomUUID(),status:'DRAFT',revision:0,idempotent:false,binding_id:randomUUID(),asset_id:assetId,period_id:periodId,expected_amount:'200.0000',register_evidence_hash:hash,schedule_snapshot_hash:hash,source_document_id:randomUUID(),source_document_version:1,source_payload_hash:hash,source_link_id:randomUUID(),acquisition_binding_id:randomUUID(),acquisition_journal_entry_id:randomUUID()};
const request={method:'POST',url:`/api/v1/entities/${entityId}/fixed-assets/register/${assetId}/depreciations`,headers:{'idempotency-key':'asset-depreciation-http-001'},body};
const setup=(action=async()=>receipt)=>{const calls=[];return {calls,api:createAccountingApi({authenticate:async()=>({trusted:true,tenantId,actorId:'maker'}),kernelFactory:async principal=>({createFixedAssetDepreciation:async args=>{calls.push({principal,args});return action(args);}})})};};
test('depreciation HTTP passes only authenticated scope and retained hashes to the native Draft command',async()=>{
 const {api,calls}=setup(async()=>({...receipt,idempotent:calls.length>1}));const first=await api({...request,url:request.url.replace(assetId,assetId.toUpperCase())}),replay=await api(request);
 assert.equal(first.status,201);assert.equal(replay.status,200);assert.equal(first.headers.etag,'"0"');assert.deepEqual(calls[0].args,{...body,tenantId,entityId,assetId,idempotencyKey:request.headers['idempotency-key']});assert.equal(calls[0].principal.actorId,'maker');assert.equal(replay.body.data.journal_entry_id,first.body.data.journal_entry_id);
});
test('depreciation HTTP rejects injected amounts, authority, malformed hashes, dates and headers before persistence',async()=>{
 const {api,calls}=setup();const invalid=[...['tenantId','entityId','actorId','requestHash','lines','amount','attachmentIds'].map(key=>({...body,[key]:'injected'})),{...body,journalDate:'2026-02-30'},{...body,journalNumber:' padded '},{...body,reason:'short'},{...body,expectedScheduleHash:'fake'},{...body,expectedRegisterEvidenceHash:'fake'}];
 for(const value of invalid)assert.equal((await api({...request,body:value})).status,400,JSON.stringify(value));assert.equal((await api({...request,headers:{}})).status,400);assert.equal((await api({...request,headers:{...request.headers,'if-match':'"1"'}})).status,400);assert.equal(calls.length,0);
});
test('depreciation HTTP maps stale evidence and unsupported post-impairment policy without retries',async()=>{
 for(const [code,message,status,responseCode] of [['40001','Depreciation schedule changed',412,'PRECONDITION_FAILED'],['40001','Acquisition source changed before depreciation',412,'PRECONDITION_FAILED'],['0A000','Post-impairment depreciation policy is required',409,'FIXED_ASSET_POST_IMPAIRMENT_POLICY_REQUIRED']]){const {api}=setup(async()=>{throw Object.assign(new Error(message),{code});});const response=await api(request);assert.equal(response.status,status);assert.equal(response.body.code,responseCode);assert.equal(response.headers['retry-after'],undefined);}
});
test('depreciation HTTP rejects malformed successful receipts',async()=>{for(const value of [null,{...receipt,asset_id:randomUUID()},{...receipt,period_id:randomUUID()},{...receipt,status:'POSTED'},{...receipt,expected_amount:'0.0000'},{...receipt,schedule_snapshot_hash:'fake'},{...receipt,register_evidence_hash:'sha256:'+'b'.repeat(64)}])assert.equal((await setup(async()=>value).api(request)).status,502);});
