import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {readFile} from 'node:fs/promises';import {movementFixture} from './fixtures/fixed-asset-movement.mjs';import {validFixedAssetMovements,FIXED_ASSET_MOVEMENTS_SCHEMA} from '../api/fixed-asset-register-contract.mjs';
test('movement contract preserves missing source status and rejects corrupted evidence families',()=>{
 const fixture=movementFixture(),context={tenantId:fixture.tenant_id,entityId:fixture.entity_id,assetId:fixture.fixed_asset_register_evidence_id,asOfDate:fixture.as_of_date,limit:50};assert.equal(validFixedAssetMovements(fixture,context),true);
 for(const patch of [{tenant_id:randomUUID()},{fixed_asset_register_evidence_id:randomUUID()},{as_of_date:'2026-08-01'},{dimensions:{}},{journal_date:'2026-08-01'},{journal_status:'DRAFT'},{debit_amount:'25000.00'},{credit_amount:'1.0000'},{journal_total_credit:'25001.0000'},{journal_ledger_line_count:1},{ledger_lineage_status:'EXACT',ledger_source_link_id:null},{ledger_source_link_count:2},{source_binding_status:'EXACT_DISPOSAL_SOURCE'},{source_document_id:randomUUID()},{posting_audit_event_count:0},{posting_audit_event_count:2},{posting_audit_event_id:null},{valuation_source_document_id:randomUUID()},{assessment_lineage_status:'EXACT_RETAINED_ASSESSMENT'},{extra:'bad'}])assert.equal(validFixedAssetMovements({...fixture,rows:[{...fixture.rows[0],...patch}]},context),false,JSON.stringify(patch));
 for(const field of Object.keys(fixture.rows[0])){const candidate=structuredClone(fixture);delete candidate.rows[0][field];assert.equal(validFixedAssetMovements(candidate,context),false,field);}
 assert.equal(validFixedAssetMovements({...fixture,rows:[fixture.rows[0],fixture.rows[0]]},context),false);
 const bound={...fixture.rows[0],source_binding_status:'EXACT_DISPOSAL_SOURCE',source_document_id:randomUUID(),source_payload_hash:'sha256:'+'a'.repeat(64),source_document_version:1,source_link_id:randomUUID(),disposal_binding_id:randomUUID()};assert.equal(validFixedAssetMovements({...fixture,rows:[bound]},context),true);
 for(const field of ['source_document_id','source_payload_hash','source_document_version','source_link_id','disposal_binding_id'])assert.equal(validFixedAssetMovements({...fixture,rows:[{...bound,[field]:null}]},context),false,field);
});
test('acquisition source requires a complete exclusive binding and rejects old response versions',()=>{
 const fixture=movementFixture(),context={tenantId:fixture.tenant_id,entityId:fixture.entity_id,assetId:fixture.fixed_asset_register_evidence_id,asOfDate:fixture.as_of_date,limit:50};
 const bound={...fixture.rows[0],source_binding_status:'EXACT_ACQUISITION_SOURCE',source_document_id:randomUUID(),source_payload_hash:'sha256:'+'a'.repeat(64),source_document_version:1,source_link_id:randomUUID(),acquisition_binding_id:randomUUID()};
 assert.equal(validFixedAssetMovements({...fixture,rows:[bound]},context),true);
 for(const key of ['source_document_id','source_payload_hash','source_document_version','source_link_id','acquisition_binding_id'])assert.equal(validFixedAssetMovements({...fixture,rows:[{...bound,[key]:null}]},context),false,key);
 for(const patch of [{disposal_binding_id:randomUUID()},{source_binding_status:'BLOCKED_MISSING_EXACT_SOURCE_BINDING'},{source_binding_status:'EXACT_DISPOSAL_SOURCE'}])assert.equal(validFixedAssetMovements({...fixture,rows:[{...bound,...patch}]},context),false);
 assert.equal(validFixedAssetMovements({...fixture,schema_version:'FIXED_ASSET_MOVEMENTS_V2'},context),false);
});
test('depreciation source requires exact posting, policy and schedule lineage',()=>{
 const fixture=movementFixture(),row=fixture.rows[0],context={tenantId:fixture.tenant_id,entityId:fixture.entity_id,assetId:fixture.fixed_asset_register_evidence_id,asOfDate:fixture.as_of_date,limit:50};
 const bound={...row,source_binding_status:'EXACT_DEPRECIATION_SOURCE',source_document_id:randomUUID(),source_payload_hash:'sha256:'+'a'.repeat(64),source_document_version:1,source_link_id:randomUUID(),depreciation_binding_id:randomUUID(),depreciation_period_id:row.accounting_period_id,depreciation_register_evidence_hash:'sha256:'+'b'.repeat(64),depreciation_schedule_snapshot_hash:'sha256:'+'c'.repeat(64),depreciation_policy_snapshot_id:randomUUID(),depreciation_policy_snapshot_hash:'sha256:'+'d'.repeat(64),depreciation_expected_amount:'25000.0000'};
 assert.equal(validFixedAssetMovements({...fixture,rows:[bound]},context),true);
 for(const key of ['source_document_id','source_payload_hash','source_document_version','source_link_id','depreciation_binding_id','depreciation_period_id','depreciation_register_evidence_hash','depreciation_schedule_snapshot_hash','depreciation_policy_snapshot_id','depreciation_policy_snapshot_hash','depreciation_expected_amount'])assert.equal(validFixedAssetMovements({...fixture,rows:[{...bound,[key]:null}]},context),false,key);
 for(const patch of [{depreciation_period_id:randomUUID()},{depreciation_expected_amount:'1.0000'},{acquisition_binding_id:randomUUID()},{disposal_binding_id:randomUUID()},{source_binding_status:'EXACT_ACQUISITION_SOURCE'}])assert.equal(validFixedAssetMovements({...fixture,rows:[{...bound,...patch}]},context),false,JSON.stringify(patch));
});
test('movement OpenAPI is the exact closed runtime schema',async()=>{const spec=JSON.parse(await readFile(new URL('../api/openapi-accounting.json',import.meta.url),'utf8'));assert.deepEqual(spec.components.schemas.FixedAssetMovements,FIXED_ASSET_MOVEMENTS_SCHEMA);assert.equal(spec.paths['/entities/{entityId}/fixed-assets/register/{assetId}/movements'].get.responses['200'].content['application/json'].schema.additionalProperties,false);});
