import test from 'node:test';
import assert from 'node:assert/strict';
import {randomUUID} from 'node:crypto';
import {createAccountingApi} from '../api/accounting-http.mjs';

const hash=seed=>'sha256:'+seed.repeat(64).slice(0,64);
function receipt({assetId,assessmentId,periodId,idempotent=false}={}){return {schema_version:'FIXED_ASSET_POST_IMPAIRMENT_DEPRECIATION_POLICY_V1',policy_id:randomUUID(),fixed_asset_register_evidence_id:assetId,impairment_assessment_evidence_id:assessmentId,impairment_assessment_hash:hash('a'),impairment_journal_entry_id:randomUUID(),impairment_posting_snapshot_hash:hash('b'),effective_period_id:periodId,effective_from:'2026-08-01',convention:'NEXT_PERIOD_FULL_MONTH',remaining_useful_life_months:110,posted_cost_balance:'25000.0000',prior_accumulated_depreciation:'2000.0000',posted_accumulated_impairment:'5000.0000',revised_carrying_value:'18000.0000',salvage_value:'1000.0000',revised_depreciable_basis:'17000.0000',regular_period_amount:'154.5455',final_period_amount:'154.5405',policy_evidence_hash:hash('c'),status:'INDEPENDENTLY_REVIEWED',can_create_draft:false,can_review:false,can_approve:false,can_post:false,idempotent};}

test('post-impairment depreciation policy review derives trusted scope and returns closed no-action evidence',async()=>{
 const tenantId=randomUUID(),entityId=randomUUID(),assetId=randomUUID(),assessmentId=randomUUID(),periodId=randomUUID(),seen=[];
 const api=createAccountingApi({authenticate:async()=>({trusted:true,tenantId,actorId:'policy-reviewer'}),kernelFactory:async()=>({reviewFixedAssetPostImpairmentPolicy:async args=>{seen.push(args);return receipt({assetId,assessmentId,periodId});}})});
 const response=await api({method:'POST',url:'/api/v1/entities/'+entityId+'/ai/fixed-assets/post-impairment-depreciation-policy-reviews',headers:{'Idempotency-Key':'review-policy-1'},body:{fixedAssetRegisterEvidenceId:assetId,impairmentAssessmentEvidenceId:assessmentId,effectivePeriodId:periodId,remainingUsefulLifeMonths:110,convention:'NEXT_PERIOD_FULL_MONTH',reason:'Independently review the revised remaining depreciation schedule.'}});
 assert.equal(response.status,201);assert.equal(response.headers['cache-control'],'no-store');assert.equal(response.body.data.can_post,false);assert.deepEqual(seen[0],{tenantId,entityId,fixedAssetRegisterEvidenceId:assetId,impairmentAssessmentEvidenceId:assessmentId,effectivePeriodId:periodId,remainingUsefulLifeMonths:110,convention:'NEXT_PERIOD_FULL_MONTH',reason:'Independently review the revised remaining depreciation schedule.',idempotencyKey:'review-policy-1'});
});

test('post-impairment policy HTTP rejects command drift and malformed backend evidence',async()=>{
 const tenantId=randomUUID(),entityId=randomUUID(),assetId=randomUUID(),assessmentId=randomUUID(),periodId=randomUUID();let result=receipt({assetId,assessmentId,periodId});
 const api=createAccountingApi({authenticate:async()=>({trusted:true,tenantId,actorId:'policy-reviewer'}),kernelFactory:async()=>({reviewFixedAssetPostImpairmentPolicy:async()=>result})}),url='/api/v1/entities/'+entityId+'/ai/fixed-assets/post-impairment-depreciation-policy-reviews',body={fixedAssetRegisterEvidenceId:assetId,impairmentAssessmentEvidenceId:assessmentId,effectivePeriodId:periodId,remainingUsefulLifeMonths:110,convention:'NEXT_PERIOD_FULL_MONTH',reason:'Independently review the revised remaining depreciation schedule.'};
 for(const request of [{method:'POST',url,body},{method:'POST',url,headers:{'Idempotency-Key':'policy-review-x','If-Match':'"0"'},body},{method:'POST',url:url+'?actor=other',headers:{'Idempotency-Key':'policy-review-x'},body},{method:'POST',url,headers:{'Idempotency-Key':'policy-review-x'},body:{...body,remainingUsefulLifeMonths:0}},{method:'POST',url,headers:{'Idempotency-Key':'policy-review-x'},body:{...body,convention:'SAME_PERIOD'}}])assert.equal((await api(request)).status,400);
 result={...result,fixed_asset_register_evidence_id:randomUUID()};assert.equal((await api({method:'POST',url,headers:{'Idempotency-Key':'policy-review-x'},body})).status,500);
 for(const mutation of [{regular_period_amount:'-1.0000'},{revised_carrying_value:'18000.0001'},{revised_depreciable_basis:'17000.0001'},{final_period_amount:'154.5406'},{posted_cost_balance:'25000.0001'},{prior_accumulated_depreciation:'1999.9999'},{posted_accumulated_impairment:'4999.9999'},{salvage_value:'1000.0001'}]){result={...receipt({assetId,assessmentId,periodId}),...mutation};assert.equal((await api({method:'POST',url,headers:{'Idempotency-Key':'policy-review-mutation-'+Object.keys(mutation)[0]},body})).status,500,Object.keys(mutation)[0]);}
 const unavailable=createAccountingApi({authenticate:async()=>({trusted:true,tenantId,actorId:'policy-reviewer'}),kernelFactory:async()=>({})});assert.equal((await unavailable({method:'POST',url,headers:{'Idempotency-Key':'policy-review-z'},body})).status,503);
});
