import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {readFile} from 'node:fs/promises';import {movementFixture} from './fixtures/fixed-asset-movement.mjs';import {validFixedAssetMovements,FIXED_ASSET_MOVEMENTS_SCHEMA} from '../api/fixed-asset-register-contract.mjs';
test('movement contract preserves missing source status and rejects corrupted evidence families',()=>{
 const fixture=movementFixture(),context={tenantId:fixture.tenant_id,entityId:fixture.entity_id,assetId:fixture.fixed_asset_register_evidence_id,asOfDate:fixture.as_of_date,limit:50};assert.equal(validFixedAssetMovements(fixture,context),true);
 for(const patch of [{tenant_id:randomUUID()},{fixed_asset_register_evidence_id:randomUUID()},{as_of_date:'2026-08-01'},{dimensions:{}},{journal_date:'2026-08-01'},{journal_status:'DRAFT'},{debit_amount:'25000.00'},{credit_amount:'1.0000'},{journal_total_credit:'25001.0000'},{journal_ledger_line_count:1},{ledger_lineage_status:'EXACT',ledger_source_link_id:null},{ledger_source_link_count:2},{source_binding_status:'EXACT_DISPOSAL_SOURCE'},{source_document_id:randomUUID()},{posting_audit_event_count:0},{posting_audit_event_count:2},{posting_audit_event_id:null},{valuation_source_document_id:randomUUID()},{assessment_lineage_status:'EXACT_RETAINED_ASSESSMENT'},{extra:'bad'}])assert.equal(validFixedAssetMovements({...fixture,rows:[{...fixture.rows[0],...patch}]},context),false,JSON.stringify(patch));
 for(const field of Object.keys(fixture.rows[0])){const candidate=structuredClone(fixture);delete candidate.rows[0][field];assert.equal(validFixedAssetMovements(candidate,context),false,field);}
 assert.equal(validFixedAssetMovements({...fixture,rows:[fixture.rows[0],fixture.rows[0]]},context),false);
 const bound={...fixture.rows[0],source_binding_status:'EXACT_DISPOSAL_SOURCE',source_document_id:randomUUID(),source_payload_hash:'sha256:'+'a'.repeat(64),source_document_version:1,source_link_id:randomUUID(),disposal_binding_id:randomUUID()};assert.equal(validFixedAssetMovements({...fixture,rows:[bound]},context),true);
 for(const field of ['source_document_id','source_payload_hash','source_document_version','source_link_id','disposal_binding_id'])assert.equal(validFixedAssetMovements({...fixture,rows:[{...bound,[field]:null}]},context),false,field);
});
test('movement OpenAPI is the exact closed runtime schema',async()=>{const spec=JSON.parse(await readFile(new URL('../api/openapi-accounting.json',import.meta.url),'utf8'));assert.deepEqual(spec.components.schemas.FixedAssetMovements,FIXED_ASSET_MOVEMENTS_SCHEMA);assert.equal(spec.paths['/entities/{entityId}/fixed-assets/register/{assetId}/movements'].get.responses['200'].content['application/json'].schema.additionalProperties,false);});
