import test from 'node:test';import assert from 'node:assert/strict';import {createAccountingApi} from '../api/accounting-http.mjs';import {validIntegrationTransactionRegister,validIntegrationTransactionRow} from '../runtime/integration-transaction-register.mjs';
const id=n=>`${n.repeat(8)}-${n.repeat(4)}-4${n.repeat(3)}-8${n.repeat(3)}-${n.repeat(12)}`,tenantId=id('1'),entityId=id('2'),rawEventId=id('3'),batchId=id('4'),receiptId=id('5');
const actions={can_setup_connector:false,can_sync_provider:false,can_import:false,can_map:false,can_create_draft:false,can_post:false,can_call_external_action:false};
const row={raw_event_id:rawEventId,connector_code:'WBS_API',connection_revision:'2',source_system:'WBS',source_module:'payable',source_entity_id:'WBPA',source_record_id:'PAY-1',source_version:'v1',event_type:'UPSERT',transaction_status:'STAGED',is_current:true,occurred_at:'2026-09-11T01:00:00Z',received_at:'2026-09-11T01:01:00Z',payload_hash:'sha256:'+'a'.repeat(64),payload_ref:'object://wbs/pay-1',correlation_id:'read-1',import_batch_id:batchId,import_batch_revision:'0',import_status:'SUCCEEDED',request_hash:'sha256:'+'b'.repeat(64),receipt_id:receiptId,receipt_hash:'sha256:'+'a'.repeat(64),outcome_kind:'STAGING',source_document_ids:[id('6')],staging_item_ids:[id('7')],audit_event_ids:[id('8')],action_flags:actions};
const connection={connector_code:'WBS_API',source_module:'payable',source_entity_id:'WBPA',connection_revision:'2',connection_status:'SUCCEEDED',latest_import_batch_id:batchId,latest_request_hash:'sha256:'+'b'.repeat(64),last_read_at:'2026-09-11T01:02:00Z',last_success_at:'2026-09-11T01:03:00Z',transaction_count:1};
const page={schema_version:'INTEGRATION_TRANSACTION_REGISTER_V1',entity_id:entityId,connector_code:null,source_module:null,transaction_status:'ALL',after_id:null,limit:25,read_at:'2026-09-11T01:04:00Z',connections:[connection],rows:[row],next_id:null,action_flags:actions};
const apiFor=kernel=>createAccountingApi({authenticate:async()=>({trusted:true,tenantId,actorId:'reader'}),kernelFactory:async()=>kernel});
test('Integration transaction list/detail are bounded, exact, company scoped, no-store and action-free',async()=>{let listArgs,detailArgs;const api=apiFor({readIntegrationTransactionRegister:async args=>(listArgs=args,page),readIntegrationTransactionDetail:async args=>(detailArgs=args,row)}),list=await api({method:'GET',url:`/api/v1/entities/${entityId}/integration-transactions?status=ALL&limit=25`,headers:{},body:null});assert.equal(list.status,200);assert.equal(list.headers['cache-control'],'no-store');assert.deepEqual(listArgs,{tenantId,entityId,connectorCode:null,sourceModule:null,status:'ALL',afterId:null,limit:25});assert.equal(validIntegrationTransactionRegister(list.body.data,{entityId}),true);const detail=await api({method:'GET',url:`/api/v1/entities/${entityId}/integration-transactions/${rawEventId}`,headers:{},body:null});assert.equal(detail.status,200);assert.deepEqual(detailArgs,{tenantId,entityId,rawEventId});assert.equal(validIntegrationTransactionRow(detail.body.data,{rawEventId}),true);});
test('Integration transactions reject cursor, scope, hash, action and command drift',async()=>{for(const changed of [{entity_id:id('9')},{rows:[{...row,payload_hash:'bad'}]},{rows:[{...row,provider_payload:{secret:true}}]},{action_flags:{...actions,can_import:true}},{next_id:id('9')}])assert.equal(validIntegrationTransactionRegister({...page,...changed},{entityId}),false);const api=apiFor({readIntegrationTransactionRegister:async()=>page,readIntegrationTransactionDetail:async()=>row});for(const request of [{method:'POST',url:`/api/v1/entities/${entityId}/integration-transactions`,headers:{},body:null},{method:'GET',url:`/api/v1/entities/${entityId}/integration-transactions?status=ALL&extra=1`,headers:{},body:null},{method:'GET',url:`/api/v1/entities/${entityId}/integration-transactions/${rawEventId}`,headers:{'if-match':'"1"'},body:null}])assert.notEqual((await api(request)).status,200);});
