import test from 'node:test';
import assert from 'node:assert/strict';
import {readFile} from 'node:fs/promises';
import {MIGRATION_MANIFEST} from '../runtime/migration-manifest.mjs';
import {verifyOutboxDispatchReleaseConfig} from '../runtime/verify-outbox-dispatch-release-config.mjs';

const file=name=>new URL(`../db/migrations/${name}`,import.meta.url);
const tenantId='11111111-1111-4111-8111-111111111111',entityId='22222222-2222-4222-8222-222222222222';

test('migration 299 atomically filters entities and binds exact grant revisions before claim',async()=>{const name='299_outbox_dispatch_entity_revision_claim.sql',up=await readFile(file(name),'utf8'),down=await readFile(file(`down/${name}`),'utf8');assert.match(up,/CREATE FUNCTION refs_claim_outbox_v3/);assert.match(up,/p_entity_ids uuid\[\]/);assert.match(up,/p_expected_grant_versions bigint\[\]/);assert.match(up,/FOR SHARE OF grant_set/);assert.match(up,/refs_read_current_actor_access/);assert.match(up,/permissions IS DISTINCT FROM ARRAY\['OUTBOX\.DISPATCH'\]/);assert.match(up,/authority_class='SERVICE'/);assert.match(up,/o\.entity_id=ANY\(p_entity_ids\)/);assert.ok(up.indexOf('FOR SHARE OF grant_set')<up.indexOf('FOR UPDATE SKIP LOCKED'));assert.match(up,/REVOKE EXECUTE ON FUNCTION refs_claim_outbox_v2.* FROM refs_app/);assert.match(up,/GRANT EXECUTE ON FUNCTION refs_claim_outbox_v3.* TO refs_app/);assert.match(down,/DROP FUNCTION refs_claim_outbox_v3/);assert.match(down,/GRANT EXECUTE ON FUNCTION refs_claim_outbox_v2/);assert.ok(MIGRATION_MANIFEST.some(row=>row.name===name));});

test('production repository has no tenant-wide claim path',async()=>{const source=await readFile(new URL('../runtime/kernel-repository.mjs',import.meta.url),'utf8');assert.match(source,/async claimOutboxV3/);assert.match(source,/refs_claim_outbox_v3/);assert.doesNotMatch(source,/async claimOutboxV2/);});

test('release preflight rejects the legacy tenant-only secret and emits aggregate evidence only',()=>{const base={OUTBOX_DISPATCH_ACTOR_ID:'outbox-service',OUTBOX_DISPATCH_SCOPES:JSON.stringify([{tenantId,entityId}]),OUTBOX_PUBLISH_URL:'https://events.example.test/v1/refs',OUTBOX_PUBLISH_TOKEN:'publisher-token-0001'};assert.throws(()=>verifyOutboxDispatchReleaseConfig({...base,OUTBOX_DISPATCH_SCOPES:JSON.stringify([{tenantId}])}),/tenantId and entityId/);const receipt=verifyOutboxDispatchReleaseConfig(base),serialized=JSON.stringify(receipt);assert.deepEqual(receipt,{schema_version:'OUTBOX_DISPATCH_RELEASE_CONFIG_V1',ready:true,scope_count:1,tenant_count:1});assert.equal(serialized.includes(tenantId),false);assert.equal(serialized.includes(entityId),false);assert.equal(serialized.includes(base.OUTBOX_PUBLISH_TOKEN),false);});

test('Render workers run the release preflight and use process supervision instead of an unsupported public health path',async()=>{for(const blueprint of ['../../render.yaml','../../render.integrations.yaml']){const source=await readFile(new URL(blueprint,import.meta.url),'utf8'),worker=source.slice(source.indexOf('name: refs-outbox-dispatch'),source.indexOf('\n  - type:',source.indexOf('name: refs-outbox-dispatch')+1));assert.match(worker,/preDeployCommand: npm run preflight:outbox-dispatch-release/);assert.match(worker,/OUTBOX_DISPATCH_HEALTH_FRESHNESS_MS/);assert.match(worker,/OUTBOX_DISPATCH_MAX_CONSECUTIVE_ERRORS/);assert.doesNotMatch(worker,/healthCheckPath/);}const runbook=await readFile(new URL('../OUTBOX-DISPATCH-RELEASE-RUNBOOK.md',import.meta.url),'utf8');assert.match(runbook,/legacy tenant-only/);assert.match(runbook,/Never infer “all entities”/);assert.match(runbook,/do not update live grants with direct SQL/);assert.match(runbook,/exits nonzero/);});
