import test from 'node:test';
import assert from 'node:assert/strict';
import {productionAiAccountingE2eConfig,runProductionAiAccountingE2e} from '../runtime/run-production-ai-accounting-e2e.mjs';

const uuid=n=>`${String(n).padStart(8,'0')}-0000-4000-8000-000000000001`;
const hash=c=>`sha256:${c.repeat(64)}`;
const roles=['producer','maker','submitter','reviewer','approver','poster','snapshotPreparer','snapshotApprover','outcomeReviewer','readback'];
const read=['AP.VIEW','AR.VIEW','BANK.VIEW','GL.JE.VIEW','GL.REPORT.VIEW','WBS.AUTOREC.VIEW'];
const permissions={producer:[...read,'AI.ANALYSIS.EXPLAIN','AI.AMORTIZATION.VIEW','AI.ACCOUNTING.SETTINGS.VIEW'],maker:[...read,'GL.JE.CREATE'],submitter:[...read,'GL.JE.SUBMIT'],reviewer:[...read,'GL.JE.REVIEW'],approver:[...read,'GL.JE.APPROVE'],poster:[...read,'GL.JE.POST'],snapshotPreparer:[...read,'GL.REPORT.SNAPSHOT.PREPARE'],snapshotApprover:[...read,'GL.REPORT.SNAPSHOT.APPROVE'],outcomeReviewer:[...read,'AI.ANALYSIS.EXPLAIN','AI.AMORTIZATION.VIEW','AI.ACCOUNTING.SETTINGS.VIEW'],readback:['GL.JE.VIEW','GL.REPORT.VIEW','WBS.AUTOREC.VIEW']};
const scenario={apiOrigin:'https://api.example',webOrigin:'https://web.example',tenantId:uuid(1),entityId:uuid(2),periodId:uuid(3),sourceDocumentId:uuid(4),admissionId:uuid(5),sourcePayloadHash:hash('a'),sourceLineHash:hash('b'),sourceRowHash:hash('e'),admissionHash:hash('f'),runKey:'approved-prod-e2e-001',reason:'Human verified the exact retained signed source and approved settings.',actors:Object.fromEntries(roles.map((role,index)=>[role,`actor-${index+1}`]))};
const environment={REFS_STAGING_API_BASE_URL:'https://api.example',REFS_STAGING_WEB_ORIGIN:'https://web.example',REFS_RELEASE_SHA:'c'.repeat(40),...Object.fromEntries(roles.map((role,index)=>[`REFS_PRODUCTION_AI_E2E_${role.replace(/[A-Z]/g,c=>`_${c}`).toUpperCase()}_TOKEN`,`signed.actor.token.${index+1}.opaque`]))};
const writeEnvironment={...environment,REFS_PRODUCTION_AI_E2E_WRITE_MODE:'ENABLED',REFS_PRODUCTION_AI_E2E_WRITE_CONFIRMATION:'I_UNDERSTAND_THIS_CREATES_AND_POSTS_ACCOUNTING'};
const response=(body,status=200,cache='no-store')=>({status,headers:new Headers({'cache-control':cache}),json:async()=>body,text:async()=>typeof body==='string'?body:JSON.stringify(body)});
const tokenName=role=>`REFS_PRODUCTION_AI_E2E_${role.replace(/[A-Z]/g,c=>`_${c}`).toUpperCase()}_TOKEN`;

function preflightFetcher({sha='c'.repeat(40),cache='no-store',scopeEntity=scenario.entityId,overlap=false,bundleDrift=null}={}){
  const byToken=new Map(roles.map(role=>[environment[tokenName(role)],role]));
  return async(url,options)=>{
    if(url.endsWith('/health/live'))return response({ok:true,status:'live',release:sha},200,cache);
    if(url.endsWith('/health/ready'))return response({ok:true,status:'ready',release:sha},200,cache);
    if(url.endsWith('/refs-build.js'))return response(`window.__BUILD=${JSON.stringify({sha,channel:'AUTHORITATIVE',authoritative:true})};`,200,cache);
    const role=byToken.get(options.headers.authorization.slice(7));
    if(url.endsWith('/access/self')){const extra=bundleDrift?.role===role?[bundleDrift.permission]:[];return response({ok:true,data:{tenant_id:scenario.tenantId,entity_id:scopeEntity,actor_id:scenario.actors[role],grant_set_version:1,permissions:[...permissions[role],...(overlap&&role==='maker'?['GL.JE.REVIEW']:[]),...(bundleDrift?.target!=='configured'?extra:[])],configured_permissions:[...permissions[role],...(bundleDrift?.target!=='effective'?extra:[])],session_refresh_required:false}},200,cache);}
    if(url.includes('/scope?'))return response({ok:true,data:{entity_id:scenario.entityId,period_id:scenario.periodId,period_status:'OPEN'}},200,cache);
    if(url.includes('/accounting-settings?')||url.includes('/approval-controls?'))return response({ok:true,data:{entity_id:scenario.entityId,accounting_period_id:scenario.periodId}},200,cache);
    if(url.includes('/wbs/provider-signed/evidence/'))return response({ok:true,data:{tenant_id:scenario.tenantId,entity_id:scenario.entityId,accounting_period_id:scenario.periodId,source_document_id:scenario.sourceDocumentId,admission_id:scenario.admissionId,source_row_hash:scenario.sourceRowHash,admission_hash:scenario.admissionHash,provider_mode:'SIGNED_OBJECT_LOCK',signature_verified:true,admission_status:'ADMITTED'}},200,cache);
    if(url.includes('/ai/accounting-decisions?'))return response({ok:true,data:{packets:[{entity_id:scenario.entityId,accounting_period_id:scenario.periodId,status:'READY_FOR_HUMAN_REVIEW',source:{source_document_id:scenario.sourceDocumentId,source_payload_hash:scenario.sourcePayloadHash,source_line_hash:scenario.sourceLineHash},proposed_journal:{status:'SUGGESTED_ONLY',balanced:true},action_flags:{can_create_draft:false,can_post:false}}]}},200,cache);
    throw new Error(`unexpected ${options.method} ${url}`);
  };
}

function happyPathFetcher(){
  const preflight=preflightFetcher(),decisionId=uuid(9001),journalId=uuid(9002),proposalId=uuid(9003),snapshotId=uuid(9004),outcomeId=uuid(9005),decisionHash=hash('d'),acceptanceHash=hash('e'),outcomeHash=hash('9');
  const saved=new Map(),effects=new Map();let queueState='AWAITING_HUMAN_DECISION',journalStatus='DRAFT',journalRevision=0,outcome=null;
  const effect=key=>effects.set(key,(effects.get(key)||0)+1);
  const queueSnapshotHash=()=>hash('0123456789abcdef'[['AWAITING_HUMAN_DECISION','ACCEPTED_READY_FOR_DRAFT','DRAFT_CREATED','PENDING_REVIEW','PENDING_APPROVAL','APPROVED','POSTED'].indexOf(queueState)]);
  const ledgerSnapshotHash=hash('8');
  const queueRows=()=>[...Array.from({length:200},(_,index)=>({ai_accounting_decision_id:uuid(1000+index),decision_hash:hash('1'),workflow_state:'REJECTED',packet:{entity_id:scenario.entityId,accounting_period_id:scenario.periodId}})),{ai_accounting_decision_id:decisionId,decision_hash:decisionHash,workflow_state:queueState,packet:{entity_id:scenario.entityId,accounting_period_id:scenario.periodId}}];
  const ledgerRows=()=>[...Array.from({length:200},(_,index)=>({ledger_line_id:uuid(2000+index),journal_entry_id:uuid(3000+index),total_count:202})),{ledger_line_id:uuid(9101),journal_entry_id:journalId,source_document_ids:[scenario.sourceDocumentId],total_count:202},{ledger_line_id:uuid(9102),journal_entry_id:journalId,source_document_ids:[scenario.sourceDocumentId],total_count:202}];
  const fetcher=async(url,options)=>{
    if(options.method==='GET'&&(url.endsWith('/health/live')||url.endsWith('/health/ready')||url.endsWith('/refs-build.js')||url.endsWith('/access/self')||url.includes('/scope?')||url.includes('/accounting-settings?')||url.includes('/approval-controls?')||url.includes('/wbs/provider-signed/evidence/')||url.includes('/ai/accounting-decisions?')))return preflight(url,options);
    if(options.method==='POST'){
      const key=options.headers['idempotency-key'];if(saved.has(key))return response({ok:true,data:{...saved.get(key),idempotent:true}});
      let data;
      if(url.endsWith('/ai/accounting-decision-runs'))data={receipts:[{source_document_id:scenario.sourceDocumentId,packet_status:'READY_FOR_HUMAN_REVIEW',decision_hash:decisionHash,ai_accounting_decision_id:decisionId}]};
      else if(url.endsWith('/human-decisions')){queueState='ACCEPTED_READY_FOR_DRAFT';data={decision_hash:decisionHash,evidence_hash:acceptanceHash};}
      else if(url.endsWith('/drafts')){queueState='DRAFT_CREATED';data={journal_entry_id:journalId};}
      else if(url.endsWith('/transitions/submit')){assert.equal(options.headers.authorization,`Bearer ${environment[tokenName('submitter')]}`);assert.equal(journalStatus,'DRAFT');journalStatus='PENDING_REVIEW';journalRevision=1;queueState='PENDING_REVIEW';data={journal_entry_id:journalId,status:journalStatus,revision:journalRevision};}
      else if(url.endsWith('/transitions/review')){assert.equal(journalStatus,'PENDING_REVIEW');journalStatus='PENDING_APPROVAL';journalRevision=2;queueState='PENDING_APPROVAL';data={journal_entry_id:journalId,status:journalStatus,revision:journalRevision};}
      else if(url.endsWith('/transitions/approve')){assert.equal(journalStatus,'PENDING_APPROVAL');journalStatus='APPROVED';journalRevision=3;queueState='APPROVED';data={journal_entry_id:journalId,status:journalStatus,revision:journalRevision};}
      else if(url.endsWith('/post')){assert.equal(journalStatus,'APPROVED');journalStatus='POSTED';journalRevision=4;queueState='POSTED';data={journal_entry_id:journalId,status:journalStatus,revision:journalRevision};}
      else if(url.endsWith('/financial-statement-snapshot-proposals'))data={financial_statement_snapshot_proposal_id:proposalId};
      else if(url.endsWith(`/financial-statement-snapshot-proposals/${proposalId}/approve`))data={financial_statement_snapshot_id:snapshotId};
      else if(url.endsWith('/posted-outcome-reviews')){outcome={ai_accounting_posted_outcome_review_id:outcomeId,review_hash:outcomeHash,review_revision:0,reviewed_by:scenario.actors.outcomeReviewer,status:'CONSISTENT'};data=outcome;}
      else throw new Error(`unexpected POST ${url}`);
      effect(key);saved.set(key,data);return response({ok:true,data},201);
    }
    if(url.includes('/accounting-decision-queue?')){const parsed=new URL(url),offset=Number(parsed.searchParams.get('offset')),snapshotToken=queueSnapshotHash(),rows=queueRows().slice(offset,offset+200);if(offset>0)assert.equal(parsed.searchParams.get('snapshotToken'),snapshotToken);return response({ok:true,data:{schema_version:'AI_ACCOUNTING_DECISION_QUEUE_SNAPSHOT_V1',limit:200,offset,total_count:201,read_count:rows.length,population_complete:offset+rows.length>=201,population_hash:snapshotToken,snapshot_token:snapshotToken,rows}});}
    if(url.includes(`/journal-entries/${journalId}?`))return response({ok:true,data:{journal_entry_id:journalId,entity_id:scenario.entityId,period_id:scenario.periodId,status:journalStatus,revision:journalRevision}});
    if(url.includes(`/financial-statement-snapshot-proposals/${proposalId}?periodId=${scenario.periodId}`))return response({ok:true,data:{financial_statement_snapshot_proposal_id:proposalId,period_id:scenario.periodId}});
    if(url.includes('/financial-statement-snapshot?'))return response({ok:true,data:{financial_statement_snapshot_id:snapshotId,period_id:scenario.periodId}});
    if(url.includes('/posted-outcome-reviews?'))return response({ok:true,data:{rows:outcome?[outcome]:[]}});
    if(url.includes('/general-ledger/snapshot-entries?')){const parsed=new URL(url),offset=Number(parsed.searchParams.get('offset')),rows=ledgerRows().slice(offset,offset+200);if(offset>0)assert.equal(parsed.searchParams.get('snapshotToken'),ledgerSnapshotHash);return response({ok:true,data:{schema_version:'GENERAL_LEDGER_SNAPSHOT_PAGE_V1',limit:200,offset,total_count:202,read_count:rows.length,population_complete:offset+rows.length>=202,population_hash:ledgerSnapshotHash,snapshot_token:ledgerSnapshotHash,rows}});}
    if(url.includes('/reports/financial-statements?'))return response({ok:true,data:[{journal_entry_ids:[journalId],source_document_ids:[scenario.sourceDocumentId]}]});
    throw new Error(`unexpected ${options.method} ${url}`);
  };
  return {fetcher,effects,ids:{decisionId,journalId,snapshotId,outcomeId}};
}

test('default execution is a GET-only preflight with zero writes',async()=>{const calls=[],fetcher=preflightFetcher(),result=await runProductionAiAccountingE2e({config:productionAiAccountingE2eConfig(environment,scenario),fetcher:async(url,options)=>{calls.push({url,options});return fetcher(url,options);}});assert.equal(result.mode,'PREFLIGHT_ONLY');assert.equal(result.write_enabled,false);assert.ok(calls.length>10);assert.ok(calls.every(call=>call.options.method==='GET'));assert.ok(calls.every(call=>!('idempotency-key' in call.options.headers)));});
test('one write switch alone still performs zero writes',async()=>{const calls=[],fetcher=preflightFetcher(),config=productionAiAccountingE2eConfig({...environment,REFS_PRODUCTION_AI_E2E_WRITE_MODE:'ENABLED'},scenario);await runProductionAiAccountingE2e({config,fetcher:async(url,options)=>{calls.push(options.method);return fetcher(url,options);}});assert.ok(calls.every(method=>method==='GET'));});
test('duplicate tokens are rejected before network access',()=>{assert.throws(()=>productionAiAccountingE2eConfig({...environment,REFS_PRODUCTION_AI_E2E_MAKER_TOKEN:environment.REFS_PRODUCTION_AI_E2E_PRODUCER_TOKEN},scenario),error=>error.code==='TOKEN_DUPLICATE');});
test('duplicate actor identities are rejected before network access',()=>{assert.throws(()=>productionAiAccountingE2eConfig(environment,{...scenario,actors:{...scenario.actors,maker:scenario.actors.producer}}),error=>error.code==='ROLE_OVERLAP');});
test('maker and submitter are distinct exact-authority actors',async()=>{const result=await runProductionAiAccountingE2e({config:productionAiAccountingE2eConfig(environment,scenario),fetcher:preflightFetcher()});assert.deepEqual(result.accesses.maker.permissions,permissions.maker);assert.deepEqual(result.accesses.submitter.permissions,permissions.submitter);assert.equal(result.accesses.maker.permissions.includes('GL.JE.SUBMIT'),false);assert.equal(result.accesses.submitter.permissions.includes('GL.JE.CREATE'),false);});
test('closed scenario schema rejects a missing, overlapping, or extra submitter',()=>{assert.throws(()=>productionAiAccountingE2eConfig(environment,{...scenario,actors:Object.fromEntries(Object.entries(scenario.actors).filter(([role])=>role!=='submitter'))}),error=>error.code==='SCENARIO_INVALID');assert.throws(()=>productionAiAccountingE2eConfig(environment,{...scenario,actors:{...scenario.actors,submitter:scenario.actors.maker}}),error=>error.code==='ROLE_OVERLAP');assert.throws(()=>productionAiAccountingE2eConfig(environment,{...scenario,actors:{...scenario.actors,legacyMaker:'actor-extra'}}),error=>error.code==='SCENARIO_INVALID');assert.throws(()=>productionAiAccountingE2eConfig(environment,{...scenario,callerPolicy:'wide'}),error=>error.code==='SCENARIO_INVALID');});
test('approved API and Web origins are bound before any token can reach the network',()=>{assert.throws(()=>productionAiAccountingE2eConfig({...environment,REFS_STAGING_API_BASE_URL:'https://attacker.example'},scenario),error=>error.code==='ORIGIN_DRIFT');assert.throws(()=>productionAiAccountingE2eConfig(environment,{...scenario,webOrigin:'https://other.example'}),error=>error.code==='ORIGIN_DRIFT');});
test('release drift fails before authenticated business reads',async()=>{let calls=0;await assert.rejects(()=>runProductionAiAccountingE2e({config:productionAiAccountingE2eConfig(environment,scenario),fetcher:async(...args)=>(calls++,preflightFetcher({sha:'d'.repeat(40)})(...args))}),error=>error.code==='RELEASE_DRIFT');assert.equal(calls,3);});
test('cached response fails closed',async()=>{await assert.rejects(()=>runProductionAiAccountingE2e({config:productionAiAccountingE2eConfig(environment,scenario),fetcher:preflightFetcher({cache:'public,max-age=60'})}),error=>error.code==='CACHE_UNSAFE');});
test('cross-scope actor access fails closed before source read',async()=>{await assert.rejects(()=>runProductionAiAccountingE2e({config:productionAiAccountingE2eConfig(environment,scenario),fetcher:preflightFetcher({scopeEntity:uuid(99)})}),error=>error.code==='SCOPE_DRIFT');});
test('conflicting workflow authority fails closed',async()=>{await assert.rejects(()=>runProductionAiAccountingE2e({config:productionAiAccountingE2eConfig(environment,scenario),fetcher:preflightFetcher({overlap:true})}),error=>error.code==='ROLE_OVERLAP');});
test('same-stage, service, configured-only, and effective-only drift fail the exact frozen bundle before writes',async()=>{for(const bundleDrift of [{role:'maker',permission:'AP.BILL.CREATE'},{role:'maker',permission:'OUTBOX.DISPATCH'},{role:'submitter',permission:'AUDIT.VIEW',target:'configured'},{role:'submitter',permission:'AUDIT.VIEW',target:'effective'}]){const calls=[];await assert.rejects(()=>runProductionAiAccountingE2e({config:productionAiAccountingE2eConfig(writeEnvironment,scenario),fetcher:async(url,options)=>{calls.push(options.method);return preflightFetcher({bundleDrift})(url,options);}}),error=>error.code==='ROLE_BUNDLE_MISMATCH');assert.equal(calls.includes('POST'),false);}});
test('a forged writeEnabled config cannot reach the network',async()=>{let calls=0;const safe=productionAiAccountingE2eConfig(environment,scenario),forged=Object.freeze({...safe,writeEnabled:true});await assert.rejects(()=>runProductionAiAccountingE2e({config:forged,fetcher:async()=>{calls++;throw new Error('must not call');}}),error=>error.code==='WRITE_INTERLOCK_REQUIRED');assert.equal(calls,0);});
test('journal revision drift stops before Submit or any later write',async()=>{const mock=happyPathFetcher(),config=productionAiAccountingE2eConfig(writeEnvironment,scenario);let tampered=false;await assert.rejects(()=>runProductionAiAccountingE2e({config,fetcher:async(url,options)=>{if(!tampered&&options.method==='GET'&&url.includes(`/journal-entries/${mock.ids.journalId}?`)){tampered=true;return response({ok:true,data:{journal_entry_id:mock.ids.journalId,entity_id:scenario.entityId,period_id:scenario.periodId,status:'DRAFT',revision:9}});}return mock.fetcher(url,options);}}),error=>error.code==='REVISION_DRIFT');assert.equal(mock.effects.size,3);assert.equal([...mock.effects.keys()].some(key=>key.endsWith(':submit')),false);});
test('same-total queue replacement between pages fails closed on the population hash',async()=>{const mock=happyPathFetcher(),config=productionAiAccountingE2eConfig(writeEnvironment,scenario);let replaced=false;await assert.rejects(()=>runProductionAiAccountingE2e({config,fetcher:async(url,options)=>{if(!replaced&&options.method==='GET'&&url.includes('/accounting-decision-queue?')&&new URL(url).searchParams.get('offset')==='200'){replaced=true;const body=await (await mock.fetcher(url,options)).json();return response({ok:true,data:{...body.data,population_hash:hash('f'),snapshot_token:hash('f')}});}return mock.fetcher(url,options);}}),error=>error.code==='POPULATION_DRIFT');assert.equal(replaced,true);assert.equal(mock.effects.size,1);});
test('same-total GL replacement between pages fails closed on the population hash',async()=>{const mock=happyPathFetcher(),config=productionAiAccountingE2eConfig(writeEnvironment,scenario);let replaced=false;await assert.rejects(()=>runProductionAiAccountingE2e({config,fetcher:async(url,options)=>{if(!replaced&&options.method==='GET'&&url.includes('/general-ledger/snapshot-entries?')&&new URL(url).searchParams.get('offset')==='200'){replaced=true;const body=await (await mock.fetcher(url,options)).json();return response({ok:true,data:{...body.data,population_hash:hash('f'),snapshot_token:hash('f')}});}return mock.fetcher(url,options);}}),error=>error.code==='POPULATION_DRIFT');assert.equal(replaced,true);assert.equal(mock.effects.size,10);});
test('full happy path uses exact states, complete queue/GL pages, and safely resumes by replay',async()=>{const mock=happyPathFetcher(),config=productionAiAccountingE2eConfig(writeEnvironment,scenario),first=await runProductionAiAccountingE2e({config,fetcher:mock.fetcher});assert.equal(first.mode,'AUTHORIZED_ACCOUNTING_WRITES_COMPLETED');assert.deepEqual({decision:first.decision_id,journal:first.journal_entry_id,snapshot:first.financial_statement_snapshot_id,outcome:first.posted_outcome_review_id},{decision:mock.ids.decisionId,journal:mock.ids.journalId,snapshot:mock.ids.snapshotId,outcome:mock.ids.outcomeId});assert.equal(mock.effects.size,10);assert.ok([...mock.effects.values()].every(count=>count===1));const second=await runProductionAiAccountingE2e({config,fetcher:mock.fetcher});assert.equal(second.journal_entry_id,first.journal_entry_id);assert.equal(second.posted_outcome_review_id,first.posted_outcome_review_id);assert.ok([...mock.effects.values()].every(count=>count===1),'resume must replay receipts without repeating effects');});
for(const enabledOnRead of [2,3])test(`an accessor enabling on read ${enabledOnRead} remains GET-only with one write-switch observation`,async()=>{
  const safe=productionAiAccountingE2eConfig(environment,scenario),mock=happyPathFetcher();
  let reads=0,writes=0;
  const forged=Object.create(null);
  for(const key of Object.keys(safe))if(key!=='writeEnabled')Object.defineProperty(forged,key,{value:safe[key],enumerable:true});
  Object.defineProperty(forged,'writeEnabled',{enumerable:true,get(){reads++;return reads>=enabledOnRead;}});
  const result=await runProductionAiAccountingE2e({config:forged,fetcher:async(url,options)=>{
    if(options?.method==='POST')writes++;
    return mock.fetcher(url,options);
  }});
  assert.equal(result.mode,'PREFLIGHT_ONLY');
  assert.equal(result.write_enabled,false);
  assert.equal(reads,1);
  assert.equal(writes,0);
  assert.equal(mock.effects.size,0);
});
