import test from 'node:test';
import assert from 'node:assert/strict';
import {productionAiAccountingE2eConfig,runProductionAiAccountingE2e} from '../runtime/run-production-ai-accounting-e2e.mjs';

const uuid=n=>`${String(n).padStart(8,'0')}-0000-4000-8000-000000000001`;
const roles=['producer','maker','submitter','reviewer','approver','poster','snapshotPreparer','snapshotApprover','outcomeReviewer','readback'];
const permissions={producer:['AI.ANALYSIS.EXPLAIN','AI.ACCOUNTING.SETTINGS.VIEW'],maker:['GL.JE.CREATE'],submitter:['GL.JE.SUBMIT'],reviewer:['GL.JE.REVIEW'],approver:['GL.JE.APPROVE'],poster:['GL.JE.POST'],snapshotPreparer:['GL.REPORT.SNAPSHOT.PREPARE','GL.REPORT.VIEW'],snapshotApprover:['GL.REPORT.SNAPSHOT.APPROVE'],outcomeReviewer:['AI.ANALYSIS.EXPLAIN'],readback:['GL.JE.VIEW','GL.REPORT.VIEW','WBS.AUTOREC.VIEW']};
const scenario={tenantId:uuid(1),entityId:uuid(2),periodId:uuid(3),sourceDocumentId:uuid(4),admissionId:uuid(5),sourcePayloadHash:'sha256:'+'a'.repeat(64),sourceLineHash:'sha256:'+'b'.repeat(64),sourceRowHash:'sha256:'+'e'.repeat(64),admissionHash:'sha256:'+'f'.repeat(64),runKey:'approved-prod-e2e-001',reason:'Human verified the exact retained signed source and approved settings.',actors:Object.fromEntries(roles.map((role,index)=>[role,`actor-${index+1}`]))};
const environment={REFS_STAGING_API_BASE_URL:'https://api.example',REFS_STAGING_WEB_ORIGIN:'https://web.example',REFS_RELEASE_SHA:'c'.repeat(40),...Object.fromEntries(roles.map((role,index)=>[`REFS_PRODUCTION_AI_E2E_${role.replace(/[A-Z]/g,c=>`_${c}`).toUpperCase()}_TOKEN`,`signed.actor.token.${index+1}.opaque`]))};
const response=(body,status=200,cache='no-store')=>({status,headers:new Headers({'cache-control':cache}),json:async()=>body,text:async()=>typeof body==='string'?body:JSON.stringify(body)});
function preflightFetcher({sha='c'.repeat(40),cache='no-store',scopeEntity=scenario.entityId,overlap=false}={}){const byToken=new Map(roles.map((role,index)=>[environment[`REFS_PRODUCTION_AI_E2E_${role.replace(/[A-Z]/g,c=>`_${c}`).toUpperCase()}_TOKEN`],role]));return async(url,options)=>{if(url.endsWith('/health/live'))return response({ok:true,status:'live',release:sha},200,cache);if(url.endsWith('/health/ready'))return response({ok:true,status:'ready',release:sha},200,cache);if(url.endsWith('/refs-build.js'))return response(`window.__BUILD=${JSON.stringify({sha,channel:'AUTHORITATIVE',authoritative:true})};`,200,cache);const role=byToken.get(options.headers.authorization.slice(7));if(url.endsWith('/access/self'))return response({ok:true,data:{tenant_id:scenario.tenantId,entity_id:scopeEntity,actor_id:scenario.actors[role],grant_set_version:1,permissions:[...permissions[role],...(overlap&&role==='submitter'?['GL.JE.REVIEW']:[])],configured_permissions:permissions[role],session_refresh_required:false}},200,cache);if(url.includes('/scope?'))return response({ok:true,data:{entity_id:scenario.entityId,period_id:scenario.periodId,period_status:'OPEN'}},200,cache);if(url.includes('/accounting-settings?')||url.includes('/approval-controls?'))return response({ok:true,data:{entity_id:scenario.entityId,accounting_period_id:scenario.periodId}},200,cache);if(url.includes('/wbs/provider-signed/evidence/'))return response({ok:true,data:{tenant_id:scenario.tenantId,entity_id:scenario.entityId,accounting_period_id:scenario.periodId,source_document_id:scenario.sourceDocumentId,admission_id:scenario.admissionId,source_row_hash:scenario.sourceRowHash,admission_hash:scenario.admissionHash,provider_mode:'SIGNED_OBJECT_LOCK',signature_verified:true,admission_status:'ADMITTED'}},200,cache);if(url.includes('/ai/accounting-decisions?'))return response({ok:true,data:{packets:[{entity_id:scenario.entityId,accounting_period_id:scenario.periodId,status:'READY_FOR_HUMAN_REVIEW',source:{source_document_id:scenario.sourceDocumentId,source_payload_hash:scenario.sourcePayloadHash,source_line_hash:scenario.sourceLineHash},proposed_journal:{status:'SUGGESTED_ONLY',balanced:true},action_flags:{can_create_draft:false,can_post:false}}]}},200,cache);throw new Error(`unexpected ${options.method} ${url}`);};}

test('default execution is a GET-only preflight with zero writes',async()=>{const calls=[],fetcher=preflightFetcher(),result=await runProductionAiAccountingE2e({config:productionAiAccountingE2eConfig(environment,scenario),fetcher:async(url,options)=>{calls.push({url,options});return fetcher(url,options);}});assert.equal(result.mode,'PREFLIGHT_ONLY');assert.equal(result.write_enabled,false);assert.ok(calls.length>10);assert.ok(calls.every(call=>call.options.method==='GET'));assert.ok(calls.every(call=>!('idempotency-key' in call.options.headers)));});
test('one write switch alone still performs zero writes',async()=>{const calls=[],fetcher=preflightFetcher(),config=productionAiAccountingE2eConfig({...environment,REFS_PRODUCTION_AI_E2E_WRITE_MODE:'ENABLED'},scenario);await runProductionAiAccountingE2e({config,fetcher:async(url,options)=>{calls.push(options.method);return fetcher(url,options);}});assert.ok(calls.every(method=>method==='GET'));});
test('duplicate tokens are rejected before network access',()=>{assert.throws(()=>productionAiAccountingE2eConfig({...environment,REFS_PRODUCTION_AI_E2E_MAKER_TOKEN:environment.REFS_PRODUCTION_AI_E2E_PRODUCER_TOKEN},scenario),error=>error.code==='TOKEN_DUPLICATE');});
test('duplicate actor identities are rejected before network access',()=>{assert.throws(()=>productionAiAccountingE2eConfig(environment,{...scenario,actors:{...scenario.actors,maker:scenario.actors.producer}}),error=>error.code==='ROLE_OVERLAP');});
test('release drift fails before authenticated business reads',async()=>{let calls=0;await assert.rejects(()=>runProductionAiAccountingE2e({config:productionAiAccountingE2eConfig(environment,scenario),fetcher:async(...args)=>(calls++,preflightFetcher({sha:'d'.repeat(40)})(...args))}),error=>error.code==='RELEASE_DRIFT');assert.equal(calls,3);});
test('cached response fails closed',async()=>{await assert.rejects(()=>runProductionAiAccountingE2e({config:productionAiAccountingE2eConfig(environment,scenario),fetcher:preflightFetcher({cache:'public,max-age=60'})}),error=>error.code==='CACHE_UNSAFE');});
test('cross-scope actor access fails closed before source read',async()=>{await assert.rejects(()=>runProductionAiAccountingE2e({config:productionAiAccountingE2eConfig(environment,scenario),fetcher:preflightFetcher({scopeEntity:uuid(99)})}),error=>error.code==='SCOPE_DRIFT');});
test('conflicting workflow authority fails closed',async()=>{await assert.rejects(()=>runProductionAiAccountingE2e({config:productionAiAccountingE2eConfig(environment,scenario),fetcher:preflightFetcher({overlap:true})}),error=>error.code==='ROLE_OVERLAP');});
test('revision drift stops before the next accounting write',async()=>{const calls=[],baseFetcher=preflightFetcher(),journalId=uuid(20),decisionId=uuid(21);const env={...environment,REFS_PRODUCTION_AI_E2E_WRITE_MODE:'ENABLED',REFS_PRODUCTION_AI_E2E_WRITE_CONFIRMATION:'I_UNDERSTAND_THIS_CREATES_AND_POSTS_ACCOUNTING'};const fetcher=async(url,options)=>{calls.push({url,method:options.method});if(options.method==='GET'&&!url.includes('/accounting-decision-queue')&&!url.includes(`/journal-entries/${journalId}`))return baseFetcher(url,options);if(options.method==='POST'&&url.endsWith('/accounting-decision-runs'))return response({ok:true,data:{receipts:[{source_document_id:scenario.sourceDocumentId,packet_status:'READY_FOR_HUMAN_REVIEW',decision_hash:'sha256:'+'d'.repeat(64),ai_accounting_decision_id:decisionId}] }},201);if(options.method==='GET'&&url.includes('/accounting-decision-queue')){const state=calls.some(c=>c.url.endsWith('/human-decisions'))?'ACCEPTED_READY_FOR_DRAFT':'AWAITING_HUMAN_DECISION';return response({ok:true,data:{rows:[{ai_accounting_decision_id:decisionId,workflow_state:state,entity_id:scenario.entityId,period_id:scenario.periodId}]}});}if(options.method==='POST'&&url.endsWith('/human-decisions'))return response({ok:true,data:{decision_hash:'sha256:'+'d'.repeat(64),evidence_hash:'sha256:'+'e'.repeat(64)}},201);if(options.method==='POST'&&url.endsWith('/drafts'))return response({ok:true,data:{journal_entry_id:journalId}},201);if(options.method==='GET'&&url.includes(`/journal-entries/${journalId}`))return response({ok:true,data:{journal_entry_id:journalId,entity_id:scenario.entityId,period_id:scenario.periodId,status:'DRAFT',revision:9}});throw new Error(`unexpected ${options.method} ${url}`);};await assert.rejects(()=>runProductionAiAccountingE2e({config:productionAiAccountingE2eConfig(env,scenario),fetcher}),error=>error.code==='REVISION_DRIFT');assert.equal(calls.filter(call=>call.method==='POST').length,3);assert.equal(calls.some(call=>call.url.includes('/transitions/')),false);assert.equal(calls.some(call=>call.url.endsWith('/post')),false);assert.equal(calls.some(call=>call.url.includes('snapshot-proposals')),false);assert.equal(calls.some(call=>call.url.includes('posted-outcome-reviews')),false);});
