import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {ReceiptFileService} from '../runtime/receipt-file.mjs';
import {createAccountingApi} from '../api/accounting-http.mjs';
const id=n=>`${n.repeat(8)}-${n.repeat(4)}-4${n.repeat(3)}-8${n.repeat(3)}-${n.repeat(12)}`;
const tenantId=id('1'),entityId=id('2'),receiptId=id('3'),principal={trusted:true,tenantId,actorId:'reader'};
const bytes=Buffer.from('owned fixture bytes'),contentHash='sha256:'+createHash('sha256').update(bytes).digest('hex');
const row={receipt_id:receiptId,receipt_created_by:'binder',receipt_created_at:'2026-06-01T00:00:00Z',attachment_id:id('4'),attachment_name:'invoice.pdf',media_type:'application/pdf',size_bytes:String(bytes.length),content_hash:contentHash,storage_ref:'s3://owned-fixture/invoice',storage_version:'version1',uploaded_by:'uploader',uploaded_at:'2026-06-01T00:00:00Z',verified_at:'2026-06-01T00:01:00Z',finalized_at:'2026-06-01T00:02:00Z',scan_status:'CLEAN',finalization_status:'VERIFIED_CLEAN',source_document_id:id('5'),source_document_revision:1,source_payload_hash:'sha256:'+'b'.repeat(64),staging_item_id:null,staging_revision:null,review_status:'FOR_REVIEW',reviewed_by:null,reviewed_at:null,extracted_facts:{source_system:'OWNED',source_module:'fixture',source_record_id:'record1',source_version:'version1',document_type:'PAYABLE',document_no:'B1',business_date:'2026-06-01',accounting_date:'2026-06-01',currency:'USD',gross_amount:'1.0000',line_count:1,party_refs:[],project_refs:[],property_refs:[],unit_refs:[],loan_refs:[],cost_code_refs:[]},action_flags:{can_upload:false,can_run_ocr:false,can_review:false,can_add_to_books:false,can_export:false,can_customize:false,can_promote_payment:false}};
function fixture({changed={},payload=bytes,metadata=payload.length,denied=false}={}){const calls=[];const service=new ReceiptFileService({kernelFactory:async p=>{assert.equal(p,principal);return{readReceiptDetail:async scope=>{calls.push(['kernel',scope]);if(denied)throw Object.assign(new Error('denied'),{code:'AUTHORIZATION_DENIED'});return{...row,...changed};}};},storage:{openVersion:async(ref,version)=>{calls.push(['storage',ref,version]);return{sizeBytes:metadata,stream:new ReadableStream({start(controller){controller.enqueue(new Uint8Array(payload));controller.close();}})};}}});return{service,calls};}
test('receipt download authorizes exact identities before storage and verifies bytes/hash',async()=>{const {service,calls}=fixture();const result=await service.read(principal,{entityId,receiptId,storageRef:'s3://attacker/ignored'});assert.deepEqual(calls,[['kernel',{tenantId,entityId,receiptId}],['storage',row.storage_ref,'version1']]);assert.deepEqual(result.content,bytes);assert.equal(result.contentHash,contentHash);assert.equal(result.receiptId,receiptId);});
test('permission denial never reads storage',async()=>{const {service,calls}=fixture({denied:true});await assert.rejects(service.read(principal,{entityId,receiptId}),{code:'AUTHORIZATION_DENIED'});assert.equal(calls.length,1);});
test('untrusted or missing principals never reach kernel or storage',async()=>{const {service,calls}=fixture();for(const p of [null,{...principal,trusted:false}])await assert.rejects(service.read(p,{entityId,receiptId}),{code:'AUTHORIZATION_DENIED'});assert.equal(calls.length,0);});
test('test objects, pending versions, unclean and oversized receipts never read storage',async()=>{for(const changed of [{storage_ref:'object://refs-test-only/fixture'},{storage_version:'test-only:1'},{storage_version:'pending:1'},{scan_status:'INFECTED'},{size_bytes:String(25*1024*1024+1)},{receipt_id:id('9')}]){const {service,calls}=fixture({changed});await assert.rejects(service.read(principal,{entityId,receiptId}));assert.equal(calls.length,1);}});
test('metadata mismatch, short, oversized and equal-length tampered bodies fail closed',async()=>{for(const opts of [{metadata:1},{payload:bytes.subarray(1),metadata:bytes.length},{payload:Buffer.concat([bytes,Buffer.from('x')]),metadata:bytes.length},{payload:Buffer.alloc(bytes.length),metadata:bytes.length}]){const {service}=fixture(opts);await assert.rejects(service.read(principal,{entityId,receiptId}),{code:'RECEIPT_FILE_IDENTITY_MISMATCH'});}});
test('download filename strips response-header and path delimiters',async()=>{const {service}=fixture({changed:{attachment_name:'a\r\n"/\\b.pdf'}});assert.equal((await service.read(principal,{entityId,receiptId})).filename,'a_____b.pdf');});
const fileUrl=`/api/v1/entities/${entityId}/receipts/${receiptId}/file`;
function apiFor(opts={}){const {service,calls}=fixture(opts);return{calls,api:createAccountingApi({authenticate:async()=>principal,kernelFactory:async()=>({}),attachmentServiceFactory:async()=>({readReceiptFile:(p,args)=>service.read(p,args)})})};}
test('receipt file HTTP GET downloads verified inert bytes and exact identity headers',async()=>{const {api}=apiFor();const result=await api({method:'GET',url:fileUrl});assert.equal(result.status,200);assert.deepEqual(result.rawBody,bytes);assert.equal(result.headers['cache-control'],'no-store');assert.equal(result.headers['x-content-type-options'],'nosniff');assert.equal(result.headers['content-type'],'application/octet-stream');assert.equal(result.headers['x-receipt-content-hash'],contentHash);assert.equal(result.headers['x-receipt-id'],receiptId);assert.equal(result.headers['x-receipt-object-version'],'version1');assert.match(result.headers['content-disposition'],/attachment;/);});
test('receipt file HTTP rejects arbitrary queries, bodies and command headers before storage',async()=>{for(const changed of [{url:fileUrl+'?storageRef=s3://attacker/x'},{body:{}},{headers:{'idempotency-key':'forbidden'}},{headers:{'if-match':'"1"'}}]){const {api,calls}=apiFor();assert.equal((await api({method:'GET',url:fileUrl,...changed})).status,400);assert.equal(calls.length,0);}});
test('receipt file HTTP denied identity, missing object and unavailable provider fail closed',async()=>{const denied=apiFor({denied:true});assert.equal((await denied.api({method:'GET',url:fileUrl})).status,403);assert.equal(denied.calls.length,1);const testObject=apiFor({changed:{storage_ref:'object://refs-test-only/x'}});assert.equal((await testObject.api({method:'GET',url:fileUrl})).status,503);assert.equal(testObject.calls.length,1);const api=createAccountingApi({authenticate:async()=>principal,kernelFactory:async()=>({})});assert.equal((await api({method:'GET',url:fileUrl})).status,503);});
