import assert from 'node:assert/strict';
import test from 'node:test';
import {readFile} from 'node:fs/promises';
import {createHash} from 'node:crypto';
import {MIGRATION_MANIFEST} from '../runtime/migration-manifest.mjs';
import {validRecurringScheduleCreate,validRecurringSchedule,validRecurringScheduleRunBatch} from '../runtime/recurring-scheduler-contract.mjs';
const id=n=>`${String(n).padStart(8,'0')}-1111-4111-8111-${String(n).padStart(12,'0')}`;
const line=(lineNo,debitAmount,creditAmount)=>({lineNo,accountCode:lineNo===1?'600000':'200000',debitAmount,creditAmount,memberRef:null,description:'Monthly recurring entry',dimensions:{}});
const create={name:'Monthly rent',journalPrefix:'RENT',currency:'USD',frequency:'MONTHLY',nextDueOn:'2026-09-30',endsOn:null,lines:[line(1,'100.0000','0.0000'),line(2,'0.0000','100.0000')],reason:'Recurring schedule contract'};
const schedule={schema_version:'RECURRING_SCHEDULE_V1',recurring_schedule_id:id(1),tenant_id:id(2),entity_id:id(3),name:create.name,journal_prefix:create.journalPrefix,currency:create.currency,frequency:create.frequency,next_due_on:create.nextDueOn,ends_on:create.endsOn,status:'DRAFT',revision:'0',lines:create.lines,created_by:'maker',created_at:'2026-09-13T00:00:00.000Z',submitted_by:null,submitted_at:null,approved_by:null,approved_at:null,last_run_at:null,history:[{action:'CREATE',actor_id:'maker',created_at:'2026-09-13T00:00:00.000Z',event_hash:'sha256:'+'a'.repeat(64),from_status:null,reason:create.reason,revision:'0',to_status:'DRAFT'}],action_flags:{can_approve:false,can_pause:false,can_post:false,can_resume:false,can_run_due:false,can_submit:true},idempotent:true};
test('recurring scheduler DTOs preserve balanced Draft and fail closed on unsafe transitions',async()=>{assert.equal(validRecurringScheduleCreate(create),true);assert.equal(validRecurringScheduleCreate({...create,lines:[create.lines[0]]}),false);assert.equal(validRecurringSchedule(schedule,{tenantId:id(2),entityId:id(3),command:true}),true);assert.equal(validRecurringSchedule({...schedule,lines:[{...schedule.lines[0],lineNo:2},schedule.lines[1]]},{tenantId:id(2),entityId:id(3),command:true}),false);const batch={schema_version:'RECURRING_SCHEDULE_RUN_BATCH_V1',tenant_id:id(2),entity_id:id(3),as_of_date:'2026-09-30',attempted_count:'0',draft_created_count:'0',failed_count:'0',runs:[],idempotent:false,action_flags:{can_post:false}};assert.equal(validRecurringScheduleRunBatch(batch,{tenantId:id(2),entityId:id(3),asOfDate:'2026-09-30'}),true);});
test('390 migration is manifest-bound and scheduler writes only Draft journal entries',async()=>{const up=await readFile(new URL('../db/migrations/390_recurring_scheduler_authoritative.sql',import.meta.url),'utf8'),down=await readFile(new URL('../db/migrations/down/390_recurring_scheduler_authoritative.sql',import.meta.url),'utf8');for(const token of ['recurring_schedule','recurring_schedule_history','recurring_schedule_run','RECURRING.SCHEDULE.APPROVE','ENABLE ROW LEVEL SECURITY','refs_create_recurring_schedule','refs_transition_recurring_schedule','refs_run_due_recurring_schedules','status=\'DRAFT\'','audit_event','outbox_event','pg_advisory_xact_lock'])assert.match(up,new RegExp(token));assert.doesNotMatch(up,/status,'POSTED'|refs_post_journal|INSERT INTO ledger_line/i);assert.match(down,/rollback denied while authoritative evidence exists/);});
test('398 recurring scheduler integrity migration is manifest-bound, tenant/entity exact, and returns retry attempts',async()=>{const name='398_recurring_scheduler_integrity_fix.sql',up=await readFile(new URL(`../db/migrations/${name}`,import.meta.url),'utf8'),down=await readFile(new URL(`../db/migrations/down/${name}`,import.meta.url),'utf8'),entry=MIGRATION_MANIFEST.find(item=>item.name===name),digest=value=>createHash('sha256').update(value.replace(/\r\n/g,'\n')).digest('hex');assert.equal(entry?.up,digest(up));assert.equal(entry?.down,digest(down));for(const token of ['recurring_schedule_tenant_entity_fkey','recurring_schedule_exception_tenant_entity_fkey','recurring_schedule_exception_tenant_entity_run_fkey','FOREIGN KEY(tenant_id,entity_id,recurring_schedule_run_id)','RETURNING recurring_schedule_run_id,attempt_count INTO run_id,run_attempt','RETURNING attempt_count INTO run_attempt',"'attempt_count',run_attempt::text"])assert.ok(up.includes(token),`missing ${token}`);assert.doesNotMatch(up,/refs_post_journal|INSERT INTO ledger_line|UPDATE ledger_line/i);assert.match(down,/DROP CONSTRAINT IF EXISTS recurring_schedule_exception_tenant_entity_run_fkey/);});

test('412 migration allows recurring schedule read support only for its exact lifecycle authorities',async()=>{const name='412_recurring_scheduler_read_authority_fix.sql',up=await readFile(new URL(`../db/migrations/${name}`,import.meta.url),'utf8'),down=await readFile(new URL(`../db/migrations/down/${name}`,import.meta.url),'utf8'),entry=MIGRATION_MANIFEST.find(item=>item.name===name),digest=value=>createHash('sha256').update(value.replace(/\r\n/g,'\n')).digest('hex');assert.equal(entry?.up,digest(up));assert.equal(entry?.down,digest(down));assert.match(up,/RECURRING\.SCHEDULE\.VIEW/);assert.match(up,/authority_class IN\('DRAFT','SUBMIT','APPROVE','REVIEW','SCHEDULE'\)/);assert.doesNotMatch(up,/RECURRING\.SCHEDULE\.VIEW[^\n]*POST/);assert.match(down,/retained grant evidence/);assert.match(down,/ERRCODE='55006'/);});
test('413 migration preserves numeric line numbers and fixes only recurring money validation',async()=>{const name='413_recurring_scheduler_line_validation_fix.sql',up=await readFile(new URL(`../db/migrations/${name}`,import.meta.url),'utf8'),down=await readFile(new URL(`../db/migrations/down/${name}`,import.meta.url),'utf8'),entry=MIGRATION_MANIFEST.find(item=>item.name===name),digest=value=>createHash('sha256').update(value.replace(/\r\n/g,'\n')).digest('hex');assert.equal(entry?.up,digest(up));assert.equal(entry?.down,digest(down));assert.match(up,/CREATE OR REPLACE FUNCTION refs_validate_recurring_schedule_lines/);assert.match(up,/\[0-9\]\{4\}/);assert.match(up,/x->>'lineNo'/);assert.doesNotMatch(up,/refs_post_journal|INSERT INTO ledger_line/i);assert.match(down,/Cannot restore defective recurring line validation/);assert.match(down,/ERRCODE='55006'/);});
test('414 migration applies the same finite additive-authority rule when issuing a runtime context',async()=>{const name='414_runtime_context_additive_authority_fix.sql',up=await readFile(new URL(`../db/migrations/${name}`,import.meta.url),'utf8'),down=await readFile(new URL(`../db/migrations/down/${name}`,import.meta.url),'utf8'),entry=MIGRATION_MANIFEST.find(item=>item.name===name),digest=value=>createHash('sha256').update(value.replace(/\r\n/g,'\n')).digest('hex');assert.equal(entry?.up,digest(up));assert.equal(entry?.down,digest(down));assert.match(up,/CREATE OR REPLACE FUNCTION refs_guard_runtime_context_sod/);assert.match(up,/runtime_human_additive_permission_authority support/);assert.match(up,/anchor\.authority_class=g\.authority_class/);assert.match(up,/CASE WHEN EXISTS\(SELECT 1 FROM runtime_human_additive_permission_authority support/);assert.match(up,/anchor\.valid_until>statement_timestamp\(\)/);assert.match(down,/active contexts/);assert.match(down,/ERRCODE='55006'/);});
test('415 migration keeps lifecycle execution least-privilege while retaining view authorization for reads',async()=>{const name='415_recurring_scheduler_lifecycle_least_privilege.sql',up=await readFile(new URL(`../db/migrations/${name}`,import.meta.url),'utf8'),down=await readFile(new URL(`../db/migrations/down/${name}`,import.meta.url),'utf8'),entry=MIGRATION_MANIFEST.find(item=>item.name===name),digest=value=>createHash('sha256').update(value.replace(/\r\n/g,'\n')).digest('hex');assert.equal(entry?.up,digest(up));assert.equal(entry?.down,digest(down));assert.match(up,/CREATE OR REPLACE FUNCTION refs_transition_recurring_schedule/);assert.match(up,/CREATE OR REPLACE FUNCTION refs_run_due_recurring_schedules/);assert.doesNotMatch(up,/PERFORM refs_assert_scope\(p_tenant,p_entity,'RECURRING\.SCHEDULE\.VIEW'\)/);assert.match(up,/RECURRING\.SCHEDULE\.SUBMIT/);assert.match(up,/RECURRING\.SCHEDULE\.RUN/);assert.match(down,/retained schedules/);assert.match(down,/ERRCODE='55006'/);});
test('416 migration separates command receipts from view-gated reads',async()=>{const name='416_recurring_scheduler_command_payload_authority_fix.sql',up=await readFile(new URL(`../db/migrations/${name}`,import.meta.url),'utf8'),down=await readFile(new URL(`../db/migrations/down/${name}`,import.meta.url),'utf8'),entry=MIGRATION_MANIFEST.find(item=>item.name===name),digest=value=>createHash('sha256').update(value.replace(/\r\n/g,'\n')).digest('hex');assert.equal(entry?.up,digest(up));assert.equal(entry?.down,digest(down));assert.match(up,/CREATE OR REPLACE FUNCTION refs_recurring_schedule_command_payload/);assert.doesNotMatch(up,/command_payload[\s\S]*?PERFORM refs_assert_scope\(p_tenant,p_entity,'RECURRING\.SCHEDULE\.VIEW'/);assert.match(up,/refs_create_recurring_schedule[\s\S]*?refs_recurring_schedule_command_payload/);assert.match(up,/refs_transition_recurring_schedule[\s\S]*?refs_recurring_schedule_command_payload/);assert.match(down,/retained schedules/);assert.match(down,/ERRCODE='55006'/);});