import assert from 'node:assert/strict';import test from 'node:test';import {randomUUID} from 'node:crypto';import {createAccountingApi} from '../api/accounting-http.mjs';
const tenantId=randomUUID(),entityId=randomUUID(),periodId=randomUUID(),viewId=randomUUID();
const base={schema_version:'REPORT_SAVED_VIEW_V1',saved_view_id:viewId,tenant_id:tenantId,entity_id:entityId,owner_actor_id:'owner',name:'August financial review',report_type:'FINANCIAL_STATEMENTS',period_id:periodId,filters:{statement:'BALANCE_SHEET'},visibility:'PRIVATE',revision:'0',created_at:'2026-09-13T00:00:00.000Z',updated_at:'2026-09-13T00:00:00.000Z',idempotent:false};
const input={name:base.name,reportType:'FINANCIAL_STATEMENTS',periodId,filters:base.filters,visibility:'PRIVATE',reason:'Retain controller reporting filters for monthly review.'};
const dimensionInput={name:'Project P&L',reportType:'DIMENSION_PNL',periodId,filters:{dimensionType:'PROJECT',dimensionRef:'P-001'},visibility:'ENTITY_SHARED',reason:'Share this exact project reporting selection with reviewers.'};
test('saved report view routes preserve closed DTO, cursor, no-store, create and CAS update',async()=>{
 const calls=[];const kernel={readReportSavedViews:async args=>(calls.push(['list',args]),{schema_version:'REPORT_SAVED_VIEW_PAGE_V1',entity_id:entityId,limit:args.limit,after_updated_at:args.afterUpdatedAt,after_id:args.afterId,next_cursor:{updated_at:base.updated_at,saved_view_id:viewId},rows:[base]}),readReportSavedView:async args=>(calls.push(['read',args]),base),createReportSavedView:async args=>(calls.push(['create',args]),args.reportType==='DIMENSION_PNL'?{...base,name:args.name,report_type:'DIMENSION_PNL',filters:args.filters,visibility:args.visibility}:{...base}),updateReportSavedView:async args=>(calls.push(['update',args]),{...base,revision:'1',name:'Updated view',idempotent:false})};
 const api=createAccountingApi({authenticate:async()=>({trusted:true,tenantId,actorId:'owner'}),kernelFactory:async()=>kernel});const path=`/api/v1/entities/${entityId}/report-saved-views`;
 let response=await api({method:'GET',url:`${path}?limit=1`,body:null,headers:{}});assert.equal(response.status,200);assert.equal(response.headers['cache-control'],'no-store');assert.deepEqual(calls[0][1],{tenantId,entityId,limit:1,afterUpdatedAt:null,afterId:null});
 response=await api({method:'POST',url:path,body:input,headers:{'idempotency-key':'saved-view-create-001'}});assert.equal(response.status,201);assert.equal(calls[1][0],'create');assert.equal(calls[1][1].tenantId,tenantId);
 response=await api({method:'POST',url:path,body:dimensionInput,headers:{'idempotency-key':'saved-view-create-003'}});assert.equal(response.status,201);assert.equal(calls[2][0],'create');assert.equal(calls[2][1].reportType,'DIMENSION_PNL');assert.equal(calls[2][1].visibility,'ENTITY_SHARED');
 response=await api({method:'POST',url:`${path}/${viewId}`,body:input,headers:{'idempotency-key':'saved-view-update-001','if-match':'"0"'}});assert.equal(response.status,200);assert.equal(response.headers.etag,'"1"');assert.equal(calls[3][1].expectedRevision,0);
 for(const request of [{method:'GET',url:`${path}?afterUpdatedAt=2026-09-13T00:00:00.000Z`,body:null,headers:{}},{method:'POST',url:path,body:{...input,ownerActorId:'other'},headers:{'idempotency-key':'saved-view-create-002'}},{method:'POST',url:path,body:{...dimensionInput,filters:{dimensionType:'PROJECT'}},headers:{'idempotency-key':'saved-view-create-004'}},{method:'POST',url:`${path}/${viewId}`,body:input,headers:{'idempotency-key':'saved-view-update-002'}}])assert.equal((await api(request)).status,request.method==='GET'||request.url===path?400:428);
});
