import test from 'node:test';
import assert from 'node:assert/strict';
import {createHash} from 'node:crypto';
import {stage3SignedEvidenceAuthoritativeE2eConfig,verifyStage3SignedEvidenceAuthoritativeE2e} from '../runtime/verify-stage3-signed-evidence-authoritative-e2e.mjs';

const roles=['BANK_EXCEPTION','COST_CWIP','INSURANCE_PREPAID','PROPERTY_RENT','G11_PAYABLE','G11_BANK','REPORT_BALANCE_SHEET','REPORT_INCOME_STATEMENT','REPORT_CASH_FLOW'];
const sha='a'.repeat(40),hash=letter=>`sha256:${letter.repeat(64)}`,uuid=index=>`${String(index).padStart(8,'0')}-1111-4111-8111-${String(index).padStart(12,'0')}`;
const tenantId=uuid(9),entityId=uuid(1),periodId=uuid(2);
const knownControlTotals=()=>({row_count:1,currency_totals:[{currency:'USD',row_count:1,amount_total:'10.0000'}]});
const knownControlTotalsHash='sha256:faa6c295db3c0d8e097f0f897b7da3102ae098551023cc9e55bba1ebd14011e1';
const canonical=value=>Array.isArray(value)?value.map(canonical):value&&typeof value==='object'?Object.fromEntries(Object.keys(value).sort().map(key=>[key,canonical(value[key])])):value;
const digest=value=>`sha256:${createHash('sha256').update(JSON.stringify(canonical(value))).digest('hex')}`;
const businessScenarios=()=>{const source=index=>uuid(100+index),result=index=>uuid(500+index),base={tenantId,entityId,periodId};return {bankException:{...base,sourceDocumentId:source(0),findingId:result(0)},costCwip:{...base,sourceDocumentId:source(1),journalEntryId:result(1)},insurancePrepaid:{...base,sourceDocumentId:source(2),journalEntryId:result(2)},propertyRent:{...base,sourceDocumentId:source(3),journalEntryId:result(3)},g11:{...base,payableIncurSourceDocumentId:source(4),autocSourceDocumentId:source(5),payableIncurJournalEntryId:result(4),autocJournalEntryId:result(5)},reporting:{balanceSheet:{...base,sourceDocumentId:source(6),financialStatementSnapshotId:result(6)},incomeStatement:{...base,sourceDocumentId:source(7),financialStatementSnapshotId:result(7)},cashFlow:{...base,sourceDocumentId:source(8),financialStatementSnapshotId:result(8)}}};};
const businessFor=(business,role)=>role==='BANK_EXCEPTION'?business.bankException:role==='COST_CWIP'?business.costCwip:role==='INSURANCE_PREPAID'?business.insurancePrepaid:role==='PROPERTY_RENT'?business.propertyRent:role.startsWith('G11_')?business.g11:business.reporting[role==='REPORT_BALANCE_SHEET'?'balanceSheet':role==='REPORT_INCOME_STATEMENT'?'incomeStatement':'cashFlow'];
const resultFor=(business,role)=>role==='BANK_EXCEPTION'?business.findingId:role==='G11_PAYABLE'?business.payableIncurJournalEntryId:role==='G11_BANK'?business.autocJournalEntryId:role.startsWith('REPORT_')?business.financialStatementSnapshotId:business.journalEntryId;
const binding=(role,index,business)=>({role,entityId,sourceDocumentId:uuid(100+index),rawEventId:uuid(200+index),sourceRecordId:`record-${index}`,sourceVersion:`version-${index}`,sourceRowHash:hash('1'),admissionId:uuid(300+index),admissionHash:hash('2'),snapshotId:uuid(400+index),issuer:'refs-mcp.wbm3.com',keyId:'wbs-final1-2026',receiptHash:hash('3'),receiptVersionId:`receipt-v${index}`,requestRawHash:hash('4'),requestVersionId:`request-v${index}`,responseRawHash:hash('5'),responseVersionId:`response-v${index}`,packageRawHash:hash('6'),packageHash:hash('7'),packageVersionId:`package-v${index}`,businessResultId:resultFor(businessFor(business,role),role),businessResultHash:digest(businessFor(business,role)),controlTotals:knownControlTotals(),controlTotalsHash:knownControlTotalsHash});
const scenarioAndBusiness=()=>{const business=businessScenarios();return {scenario:{tenantId,entityId,periodId,bindings:roles.map((role,index)=>binding(role,index,business))},business};};
const environment={REFS_RELEASE_SHA:sha,REFS_STAGING_API_BASE_URL:'https://api.example.test',REFS_STAGING_WEB_ORIGIN:'https://web.example.test',REFS_STAGE3_SIGNED_EVIDENCE_E2E_READ_ACCESS_TOKEN:'stage3-read-token-value'};
const config=()=>{const {scenario,business}=scenarioAndBusiness();return stage3SignedEvidenceAuthoritativeE2eConfig(environment,scenario,business);};
const response=(status,body,cache='no-store',contentType='application/json')=>({status,headers:new Headers({'cache-control':cache,'content-type':contentType}),json:async()=>body,text:async()=>String(body)});
const dto=row=>({evidence_version:'WBS_PROVIDER_SIGNED_SOURCE_EVIDENCE_V1',provider_mode:'SIGNED_OBJECT_LOCK',admission_status:'ADMITTED',signature_verified:true,tenant_id:tenantId,entity_id:row.entityId,accounting_period_id:periodId,source_document_id:row.sourceDocumentId,raw_event_id:row.rawEventId,source_record_id:row.sourceRecordId,source_version:row.sourceVersion,source_row_hash:row.sourceRowHash,admission_id:row.admissionId,admission_hash:row.admissionHash,snapshot_id:row.snapshotId,issuer:row.issuer,key_id:row.keyId,algorithm:'Ed25519',control_totals:knownControlTotals(),control_totals_hash:knownControlTotalsHash,action_flags:{can_propose_amortization:false,can_review:false,can_create_draft:false,can_approve:false,can_post:false},artifacts:{receipt:{sha256:row.receiptHash,version_id:row.receiptVersionId},request:{sha256:row.requestRawHash,version_id:row.requestVersionId},response:{sha256:row.responseRawHash,version_id:row.responseVersionId},package:{sha256:row.packageRawHash,canonical_package_hash:row.packageHash,version_id:row.packageVersionId}}});
const fetcherFor=(configuration,mutate=()=>{},calls=[])=>async(url,options)=>{calls.push({url,options});if(url.endsWith('/health/live'))return response(200,{ok:true,status:'live',release:sha});if(url.endsWith('/health/ready'))return response(200,{ok:true,status:'ready',release:sha});if(url.endsWith('/refs-build.js'))return response(200,`window.__BUILD = ${JSON.stringify({channel:'AUTHORITATIVE',authoritative:true,sha})};`);const row=configuration.bindings.find(item=>url.endsWith(`/source-documents/${item.sourceDocumentId}`));assert.ok(row);const data=dto(row);mutate(data,row);return response(200,{ok:true,data});};

test('Stage3 accepts the provider faa6 known vector unchanged through authoritative GET DTO',async()=>{const c=config(),calls=[],result=await verifyStage3SignedEvidenceAuthoritativeE2e({config:c,fetcher:fetcherFor(c,()=>{},calls)});assert.equal(result.ok,true);assert.equal(result.bindings.length,9);assert.ok(result.bindings.every(row=>row.controlTotalsHash===knownControlTotalsHash));assert.equal(calls.length,12);for(const {options} of calls){assert.equal(options.method,'GET');assert.equal(options.body,undefined);assert.equal(Object.keys(options.headers).some(key=>key.toLowerCase()==='idempotency-key'),false);}});

test('Stage3 rejects legacy per_currency and gross_amount control shapes',async()=>{for(const legacy of [data=>{data.control_totals={row_count:1,per_currency:[{currency:'USD',row_count:1,amount_total:'10.0000'}]};},data=>{data.control_totals={row_count:1,currency_totals:[{currency:'USD',row_count:1,gross_amount:'10.0000'}]};}]){const c=config();await assert.rejects(()=>verifyStage3SignedEvidenceAuthoritativeE2e({config:c,fetcher:fetcherFor(c,(data,row)=>{if(row.role==='BANK_EXCEPTION')legacy(data);})}),/not the closed V1 schema/);}});

test('Stage3 rejects a correct control object paired with the wrong hash',async()=>{const c=config();await assert.rejects(()=>verifyStage3SignedEvidenceAuthoritativeE2e({config:c,fetcher:fetcherFor(c,(data,row)=>{if(row.role==='COST_CWIP')data.control_totals_hash=hash('f');})}),/control totals hash is not canonical/);});

test('Stage3 rejects control totals beyond the frozen 500-row bound',()=>{for(const mutate of [totals=>{totals.row_count=501;totals.currency_totals[0].row_count=501;},totals=>{totals.currency_totals=Array.from({length:501},(_,index)=>({currency:String.fromCharCode(65+Math.floor(index/676),65+Math.floor(index/26)%26,65+index%26),row_count:1,amount_total:'0.0000'}));totals.row_count=501;}]){const pair=scenarioAndBusiness(),totals=pair.scenario.bindings[0].controlTotals;mutate(totals);pair.scenario.bindings[0].controlTotalsHash=digest(totals);assert.throws(()=>stage3SignedEvidenceAuthoritativeE2eConfig(environment,pair.scenario,pair.business),/(row_count|currency_totals) is invalid/);}});

test('Stage3 rejects unsigned evidence, writable action flags and cacheable reads',async()=>{for(const mutation of [(data,row)=>{if(row.role==='INSURANCE_PREPAID')data.provider_mode='UNSIGNED_GET_ONLY';},(data,row)=>{if(row.role==='PROPERTY_RENT')data.action_flags.can_post=true;}]){const c=config();await assert.rejects(()=>verifyStage3SignedEvidenceAuthoritativeE2e({config:c,fetcher:fetcherFor(c,mutation)}),/(not formally admitted signed evidence|can_post must remain false)/);}const c=config(),normal=fetcherFor(c);await assert.rejects(()=>verifyStage3SignedEvidenceAuthoritativeE2e({config:c,fetcher:async(url,options)=>{const answer=await normal(url,options);if(url.includes('/source-documents/'))answer.headers=new Headers({'cache-control':'public','content-type':'application/json'});return answer;}}),/must be no-store/);});

test('Stage3 rejects legacy or hash-drifted frozen scenario contracts before network access',()=>{for(const mutate of [binding=>{binding.controlTotals={row_count:1,per_currency:[{currency:'USD',gross_amount:'10.0000'}]};},binding=>{binding.controlTotalsHash=hash('f');}]){const pair=scenarioAndBusiness();mutate(pair.scenario.bindings[0]);assert.throws(()=>stage3SignedEvidenceAuthoritativeE2eConfig(environment,pair.scenario,pair.business),/(not the closed V1 schema|control totals hash is not canonical)/);}});
