import test from 'node:test';
import assert from 'node:assert/strict';
import {stage3CostCwipAuthoritativeE2eConfig,verifyStage3CostCwipAuthoritativeE2e} from '../runtime/verify-stage3-cost-cwip-authoritative-e2e.mjs';

const id=value=>`${value}`.padStart(8,'0')+'-0000-4000-8000-000000000001';
const scenario={entityId:id(1),periodId:id(2),sourceDocumentId:id(3),journalEntryId:id(4),cwipJournalLineId:id(5),offsetJournalLineId:id(6),cwipLedgerLineId:id(7),offsetLedgerLineId:id(8),cwipAccountCode:'164100',offsetAccountCode:'610000',expectedAmount:'125.5000'};
const environment={REFS_STAGING_API_BASE_URL:'https://api.staging.example',REFS_STAGING_WEB_ORIGIN:'https://web.staging.example',REFS_RELEASE_SHA:'a'.repeat(40),REFS_STAGE3_COST_CWIP_E2E_READ_ACCESS_TOKEN:'header.payload.signature'};
const response=body=>({status:200,headers:new Headers({'cache-control':'no-store'}),json:async()=>body,text:async()=>typeof body==='string'?body:JSON.stringify(body)});
const ok=data=>response({ok:true,data});
const release=(status,sha='a'.repeat(40))=>response({ok:true,status,release:sha});
const leg=(account,journalLine,ledgerLine,debit,credit)=>({account_code:account,journal_entry_id:scenario.journalEntryId,journal_line_id:journalLine,ledger_line_id:ledgerLine,source_document_ids:[scenario.sourceDocumentId],debit_amount:debit,credit_amount:credit});
const cwip=leg('164100',scenario.cwipJournalLineId,scenario.cwipLedgerLineId,'125.5000','0.0000'),offset=leg('610000',scenario.offsetJournalLineId,scenario.offsetLedgerLineId,'0.0000','125.5000');
const statement=(statement_type,row)=>({...row,statement_type,journal_entry_ids:[scenario.journalEntryId],journal_line_ids:[row.journal_line_id],ledger_line_ids:[row.ledger_line_id],opening_debit:'0.0000',opening_credit:'0.0000',period_debit:row.debit_amount,period_credit:row.credit_amount,ending_debit:row.debit_amount,ending_credit:row.credit_amount,display_balance:'125.5000'});
const evidence={source:[{source_document_id:scenario.sourceDocumentId,source_system:'WBS',source_module:'cost_general_ledger',document_type:'WBS_COST_CWIP',gross_amount:'125.5000',posted_journal_entry_ids:[scenario.journalEntryId]}],journal:{journal_entry_id:scenario.journalEntryId,period_id:scenario.periodId,status:'POSTED',lines:[cwip,offset]},cwip:[cwip],offset:[offset],statements:[statement('TRIAL_BALANCE',cwip),statement('BALANCE_SHEET',cwip),statement('TRIAL_BALANCE',offset),statement('INCOME_STATEMENT',offset)]};
const fetcher=(calls,changes={})=>async(url,options)=>{calls.push({url,options});if(url.endsWith('/health/live'))return release('live',changes.live);if(url.endsWith('/health/ready'))return release('ready',changes.ready);if(url.endsWith('/refs-build.js'))return {status:200,headers:new Headers({'cache-control':'no-store'}),text:async()=>`window.__BUILD=${JSON.stringify({sha:changes.web||'a'.repeat(40),channel:'AUTHORITATIVE',authoritative:true})};`};if(url.includes('/source-documents/'))return ok(changes.source||evidence.source);if(url.includes('/journal-entries/'))return ok(changes.journal||evidence.journal);if(url.includes('accountCode=164100'))return ok(changes.cwip||evidence.cwip);if(url.includes('accountCode=610000'))return ok(changes.offset||evidence.offset);return ok(changes.statements||evidence.statements);};

test('Stage 3 Cost-to-CWIP config rejects non-text money and abbreviated release SHA',()=>{assert.throws(()=>stage3CostCwipAuthoritativeE2eConfig(environment,{...scenario,expectedAmount:125.5}),/fixed four-decimal text/);assert.throws(()=>stage3CostCwipAuthoritativeE2eConfig({...environment,REFS_RELEASE_SHA:'aaaaaaa'},scenario),/full 40-character/);});

test('Stage 3 Cost-to-CWIP verifier reads exact source, POSTED JE, GL legs and TB/reports without writes',async()=>{const calls=[],result=await verifyStage3CostCwipAuthoritativeE2e({config:stage3CostCwipAuthoritativeE2eConfig(environment,scenario),fetcher:fetcher(calls)});assert.equal(result.ok,true);assert.equal(calls.length,8);assert.ok(calls.every(call=>call.options.method==='GET'));assert.ok(calls.filter(call=>call.url.includes('/api/v1/')).every(call=>call.options.headers.authorization==='Bearer header.payload.signature'));assert.ok(calls.every(call=>call.options.body===undefined));});

test('Stage 3 Cost-to-CWIP verifier rejects mismatched release before accounting reads',async()=>{const calls=[];await assert.rejects(()=>verifyStage3CostCwipAuthoritativeE2e({config:stage3CostCwipAuthoritativeE2eConfig(environment,scenario),fetcher:fetcher(calls,{web:'b'.repeat(40)})}),/release/);assert.equal(calls.length,3);});

test('Stage 3 Cost-to-CWIP verifier fails closed on wrong source type, GL amount or report amount/lineage',async()=>{for(const [changes,pattern] of [[{source:[{...evidence.source[0],document_type:'WBS_PAYABLE'}]},/WBS_COST_CWIP/],[{offset:[{...offset,credit_amount:'125.50'}]},/offset leg/],[{statements:evidence.statements.map(row=>row.statement_type==='BALANCE_SHEET'?{...row,period_debit:'125.4999'}:row)},/financial report is missing the exact CWIP lineage/],[{statements:evidence.statements.filter(row=>!(row.statement_type==='INCOME_STATEMENT'&&row.account_code==='610000'))},/financial report is missing the exact offset lineage/]]){await assert.rejects(()=>verifyStage3CostCwipAuthoritativeE2e({config:stage3CostCwipAuthoritativeE2eConfig(environment,scenario),fetcher:fetcher([],changes)}),pattern);}});
