import test from 'node:test';
import assert from 'node:assert/strict';
import {generateKeyPairSync,sign} from 'node:crypto';
import {canonicalRequestHash} from '../runtime/request-hash.mjs';
import {buildWbsMcpReadonlySnapshot} from '../runtime/wbs-mcp-inbound-lineage.mjs';
import {createWbsSnapshotSignatureVerifier} from '../runtime/wbs-snapshot-signature.mjs';
import {createWbsAdmittedPayableIngestion,WbsAdmittedPayableIngestionError} from '../runtime/wbs-admitted-payable-ingestion.mjs';

const tenantId='11111111-1111-4111-8111-111111111111',entityId='22222222-2222-4222-8222-222222222222';
const pair=generateKeyPairSync('ed25519'),keyId='wbs-admitted-payable-test';
const publicKeys={[keyId]:pair.publicKey.export({type:'spki',format:'pem'})};
const contentRows=[{ap_guid:'33333333-3333-4333-8333-333333333333',ap_type:'AUTOC',company_code:'COMPANY-A',currency:'USD',amount:'125.5000',incurred_date:'2026-08-10',posting_date:'2026-08-11',vendor_no:'VENDOR-1'}];
const envelope=rows=>({contract_version:'WBS-REFS-MCP-V1',tool:'list_payables',environment:'production',captured_at:'2026-08-11T02:00:00.000Z',source:{system:'WBS'},scope:{company:'COMPANY-A',currency:'USD',snapshot_token:'provider-snapshot-payable-1'},record_count:rows.length,content_sha256:canonicalRequestHash(rows).slice(7),cursor_next:null,etl_notice:'Snapshot comparison required',rows});
const conventions=source=>[{scope:{company_key:'COMPANY-A',currency:'USD'},receipt:{hash:`sha256:${source.content_sha256}`,ref:'object://wbs/payable/direction',version:'1',verification_id:'verify-payable-1',key_id:keyId,algorithm:'Ed25519',verified_on:'2026-08-11T02:00:00.000Z'},rule_id:'WBS-PAYABLE-DIRECTION-1',version:'1',ap_type:'AUTOC',direction:'DEBIT'}];
function signedSnapshot(rows=contentRows){const source=envelope(rows);const unsigned=buildWbsMcpReadonlySnapshot({envelopes:[source],snapshotId:'44444444-4444-4444-8444-444444444444',dictionaryVersion:'WBS-MCP-V1',environment:'PRODUCTION',delivery:{mode:'SIGNED_SNAPSHOT_PACKAGE',snapshot_token:'provider-snapshot-payable-1',extract_started_at:'2026-08-11T01:59:00.000Z',extract_completed_at:'2026-08-11T02:00:00.000Z',consistency:'COMPLETE',read_consistency:'SNAPSHOT_ISOLATION',pagination:'PRIMARY_KEY_SEEK'},detachedSignature:{key_id:keyId,algorithm:'Ed25519',value:'placeholder'},payableDirectionConventions:conventions(source)});return {...unsigned,detached_signature:{...unsigned.detached_signature,value:sign(null,Buffer.from(unsigned.package_hash),pair.privateKey).toString('base64')}};}
function resign(snapshot,mutate){const next=structuredClone(snapshot);mutate(next);next.views[0].content_hash=canonicalRequestHash(next.views[0].rows);const {package_hash,detached_signature,...manifest}=next;void package_hash;next.package_hash=canonicalRequestHash(manifest);next.detached_signature={...detached_signature,value:sign(null,Buffer.from(next.package_hash),pair.privateKey).toString('base64')};return next;}
function harness(){const calls=[];const kernel={async recordWbsSnapshot(request){calls.push(['receipt',request]);return {import_batch_id:'55555555-5555-4555-8555-555555555555',idempotent:false,can_create_draft:false,can_post:false};},async persistWbsInboundRows(request){calls.push(['rows',request]);return {receipt_id:'66666666-6666-4666-8666-666666666666',row_count:request.rows.length,idempotent:false,can_create_draft:false,can_post:false};}};return {calls,service:createWbsAdmittedPayableIngestion({kernel,signatureVerifier:createWbsSnapshotSignatureVerifier({publicKeys})})};}

test('signed production Payable composes immutable receipt through Raw, MONEY4 Normalized and Staging with zero action authority',async()=>{const {calls,service}=harness(),snapshot=signedSnapshot();const result=await service.ingest({tenantId,entityId,snapshot,idempotencyKey:'wbs-payable-admission-0001'});assert.deepEqual(calls.map(([kind])=>kind),['receipt','rows']);const row=calls[1][1].rows[0];assert.deepEqual({raw:row.raw.amount,normalized:row.normalized.amount,money4:row.normalized.amount_money4,company:row.normalized.company_key,currency:row.normalized.currency,outcome:row.outcome_kind},{raw:'-125.5000',normalized:-125.5,money4:'-125.5000',company:'COMPANY-A',currency:'USD',outcome:'STAGING'});assert.deepEqual({status:result.status,normalized:result.normalized_count,staging:result.staging_count,exceptions:result.exception_count,draft:result.can_create_draft,approve:result.can_approve,post:result.can_post},{status:'PERSISTED_PAYABLE_STAGING_REVIEW_REQUIRED',normalized:1,staging:1,exceptions:0,draft:false,approve:false,post:false});});

test('admitted Payable replay is idempotent and changed evidence under the same key is rejected',async()=>{const {calls,service}=harness(),snapshot=signedSnapshot();const first=await service.ingest({tenantId,entityId,snapshot,idempotencyKey:'wbs-payable-admission-replay'}),replay=await service.ingest({tenantId,entityId,snapshot,idempotencyKey:'wbs-payable-admission-replay'});assert.equal(first.idempotent,false);assert.equal(replay.idempotent,true);assert.equal(calls.length,2);const changed=resign(snapshot,value=>{value.views[0].rows[0].description='different signed evidence';});await assert.rejects(()=>service.ingest({tenantId,entityId,snapshot:changed,idempotencyKey:'wbs-payable-admission-replay'}),error=>error instanceof WbsAdmittedPayableIngestionError&&error.code==='WBS_PAYABLE_ADMISSION_IDEMPOTENCY_CONFLICT');});

test('unsigned pilot, cross-currency, non-Payable, and bad signature never reach persistence',async()=>{const cases=[];cases.push([{...signedSnapshot(),status:'NOT_ADMITTED',signature_verified:false,can_persist:false},'WBS_PAYABLE_ADMISSION_UNSIGNED_PILOT_FORBIDDEN']);const crossCurrency=resign(signedSnapshot(),value=>{value.views[0].rows[0].currency='CAD';value.views[0].rows.push({...value.views[0].rows[0],apGuId:'77777777-7777-4777-8777-777777777777',currency:'USD'});value.views[0].row_count=2;value.views[0].last_primary_key='77777777-7777-4777-8777-777777777777';});cases.push([crossCurrency,'WBS_PAYABLE_ADMISSION_CURRENCY_INVALID']);const nonPayable=resign(signedSnapshot(),value=>{value.views[0].name='BGDATA.bank_transaction';value.views[0].rows[0]={bankTransactionId:'BANK-1',bank_account_ref:'111000',currency:'USD',amount:'1.0000',transaction_date:'2026-08-10',posting_date:'2026-08-11'};value.views[0].row_count=1;value.views[0].first_primary_key='BANK-1';value.views[0].last_primary_key='BANK-1';});cases.push([nonPayable,'WBS_PAYABLE_ADMISSION_SCOPE_INVALID']);cases.push([{...signedSnapshot(),detached_signature:{key_id:keyId,algorithm:'Ed25519',value:'invalid'}},'WBS_PAYABLE_ADMISSION_SIGNATURE_INVALID']);for(const [snapshot,code] of cases){const {calls,service}=harness();await assert.rejects(()=>service.ingest({tenantId,entityId,snapshot,idempotencyKey:`wbs-payable-${code}`}),error=>error.code===code);assert.equal(calls.length,0);}});

test('signed malformed Payable retains immutable Raw and becomes Exception instead of a Draft candidate',async()=>{const snapshot=resign(signedSnapshot(),value=>{value.views[0].rows[0].amount='125.50000';});const {calls,service}=harness(),result=await service.ingest({tenantId,entityId,snapshot,idempotencyKey:'wbs-payable-exception-0001'});const row=calls[1][1].rows[0];assert.equal(row.raw.amount,'125.50000');assert.equal(row.normalized.amount,null);assert.equal(row.normalized.amount_money4,null);assert.equal(row.outcome_kind,'EXCEPTION');assert.equal(result.exception_count,1);assert.equal(result.can_create_draft,false);});
