import test from 'node:test';import assert from 'node:assert/strict';import {randomUUID} from 'node:crypto';import {createAccountingApi} from '../api/accounting-http.mjs';
const tenantId=randomUUID(),entityId=randomUUID(),subscriptionId=randomUUID(),outboxEventId=randomUUID(),deliveryId=randomUUID(),fingerprint='sha256:'+'a'.repeat(64);
const row={schema_version:'WEBHOOK_SUBSCRIPTION_V1',subscription_id:subscriptionId,tenant_id:tenantId,entity_id:entityId,subscription_name:'Accounting events',endpoint_host:'hooks.example.com',endpoint_path:'/refs/v1/events',event_types:['ACCOUNTING.JOURNAL.POSTED'],signing_key_fingerprint:fingerprint,status:'DRAFT',revision:'0',created_by:'maker',created_at:'2026-09-13T00:00:00.000Z',submitted_by:null,submitted_at:null,approved_by:null,approved_at:null,suspended_by:null,suspended_at:null,idempotent:false};
const history={schema_version:'WEBHOOK_DELIVERY_HISTORY_V1',subscription_id:subscriptionId,limit:25,rows:[{delivery_id:deliveryId,outbox_event_id:outboxEventId,event_type:'ACCOUNTING.JOURNAL.POSTED',payload_hash:fingerprint,attempt_number:1,status:'FAILED',delivered_at:'2026-09-13T01:00:00.000Z',response_status:503,response_hash:fingerprint}]};
test('webhook subscription endpoints bind scope, hide secret reference, and keep history readonly',async()=>{
 const calls=[];const api=createAccountingApi({authenticate:async()=>({trusted:true,tenantId,actorId:'maker'}),kernelFactory:async()=>({readWebhookSubscription:async args=>(calls.push(['read',args]),row),readWebhookDeliveryHistory:async args=>(calls.push(['history',args]),history),createWebhookSubscription:async args=>(calls.push(['create',args]),row),transitionWebhookSubscription:async args=>(calls.push(['transition',args]),{...row,status:'PENDING_APPROVAL',revision:'1'})})});
 let response=await api({method:'GET',url:`/api/v1/entities/${entityId}/webhook-subscriptions/${subscriptionId}`,body:null,headers:{}});assert.equal(response.status,200);assert.equal(response.headers['cache-control'],'no-store');assert.doesNotMatch(JSON.stringify(response.body),/signingKeyReference|signing_key_reference/);assert.deepEqual(calls[0],['read',{tenantId,entityId,subscriptionId}]);
 response=await api({method:'GET',url:`/api/v1/entities/${entityId}/webhook-subscriptions/${subscriptionId}/deliveries?limit=25`,body:null,headers:{}});assert.equal(response.status,200);assert.equal(response.body.data.rows.length,1);assert.doesNotMatch(JSON.stringify(response.body),/secret|token|authorization|signing_key/i);assert.equal(calls[1][1].limit,25);
 const body={subscriptionName:'Accounting events',endpointHost:'hooks.example.com',endpointPath:'/refs/v1/events',eventTypes:['ACCOUNTING.JOURNAL.POSTED'],signingKeyReference:'vault://refs/webhooks/one',signingKeyFingerprint:fingerprint,reason:'Maker requests controlled accounting event delivery.'};
 response=await api({method:'POST',url:`/api/v1/entities/${entityId}/webhook-subscriptions`,body,headers:{'idempotency-key':'webhook-create-0001'}});assert.equal(response.status,201);assert.equal(calls[2][1].eventTypes[0],'ACCOUNTING.JOURNAL.POSTED');assert.doesNotMatch(JSON.stringify(response.body),/vault/);
 response=await api({method:'POST',url:`/api/v1/entities/${entityId}/webhook-subscriptions/${subscriptionId}/transitions`,body:{action:'SUBMIT',reason:'Independent submitter sends this for review.'},headers:{'idempotency-key':'webhook-submit-0001','if-match':'"0"'}});assert.equal(response.status,200);assert.equal(calls[3][1].expectedRevision,0);
 for(const request of [{method:'GET',url:`/api/v1/entities/${entityId}/webhook-subscriptions/${subscriptionId}/deliveries`,body:null,headers:{'idempotency-key':'forbidden'}},{method:'POST',url:`/api/v1/entities/${entityId}/webhook-subscriptions`,body:{...body,eventTypes:['bad event']},headers:{'idempotency-key':'webhook-create-0001'}},{method:'POST',url:`/api/v1/entities/${entityId}/webhook-subscriptions`,body:{...body,endpointHost:'127.0.0.1'},headers:{'idempotency-key':'webhook-ip4-0001'}},{method:'POST',url:`/api/v1/entities/${entityId}/webhook-subscriptions`,body:{...body,endpointHost:'10.0.0.1'},headers:{'idempotency-key':'webhook-rfc1918-0001'}},{method:'POST',url:`/api/v1/entities/${entityId}/webhook-subscriptions`,body:{...body,endpointHost:'169.254.1.1'},headers:{'idempotency-key':'webhook-linklocal-001'}},{method:'POST',url:`/api/v1/entities/${entityId}/webhook-subscriptions`,body:{...body,endpointHost:'::1'},headers:{'idempotency-key':'webhook-ip6-0001'}},{method:'POST',url:`/api/v1/entities/${entityId}/webhook-subscriptions`,body:{...body,endpointHost:'localhost'},headers:{'idempotency-key':'webhook-localhost-01'}},{method:'POST',url:`/api/v1/entities/${entityId}/webhook-subscriptions`,body:{...body,endpointHost:'api.internal.example'},headers:{'idempotency-key':'webhook-internal-0001'}},{method:'POST',url:`/api/v1/entities/${entityId}/webhook-subscriptions`,body:{...body,endpointHost:'hooks.example.test'},headers:{'idempotency-key':'webhook-test-0001'}},{method:'POST',url:`/api/v1/entities/${entityId}/webhook-subscriptions/${subscriptionId}/deliveries`,body:{},headers:{'idempotency-key':'cannot-write'}}])assert.ok((await api(request)).status>=400);
});
