const exact=(value,keys)=>value&&typeof value==='object'&&!Array.isArray(value)&&Object.keys(value).length===keys.length&&keys.every(key=>Object.hasOwn(value,key));
const uuid=value=>typeof value==='string'&&/^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/.test(value);
const text=(value,max)=>typeof value==='string'&&value===value.trim()&&value.length>0&&value.length<=max&&!/[\u0000-\u001f\u007f]/.test(value);
const hash=value=>typeof value==='string'&&/^sha256:[0-9a-f]{64}$/.test(value);
const timestamp=value=>typeof value==='string'&&/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}\.\d{6}Z$/.test(value)&&Number.isFinite(Date.parse(value));
const vendor=value=>exact(value,['vendor_ref','vendor_name'])&&text(value.vendor_ref,128)&&text(value.vendor_name,2000);
const bankCash=value=>exact(value,['bank_member_ref','bank_name','cash_account_code','cash_account_name'])&&text(value.bank_member_ref,128)&&text(value.bank_name,2000)&&text(value.cash_account_code,64)&&text(value.cash_account_name,2000);
const expenseAccount=value=>exact(value,['expense_account_code','expense_account_name'])&&text(value.expense_account_code,64)&&text(value.expense_account_name,2000);
const attachment=value=>exact(value,['attachment_id','name','media_type','size_bytes','content_hash','verified_at'])&&uuid(value.attachment_id)&&text(value.name,512)&&text(value.media_type,255)&&/^(0|[1-9]\d{0,18})$/.test(value.size_bytes)&&hash(value.content_hash)&&timestamp(value.verified_at);

export const validNativeExpenseCreateOptions=(value,{entityId,periodId})=>exact(value,['schema_version','entity_id','period_id','vendors','bank_cash_accounts','expense_accounts','attachments'])&&value.schema_version==='NATIVE_EXPENSE_CREATE_OPTIONS_V1'&&value.entity_id===entityId&&value.period_id===periodId&&Array.isArray(value.vendors)&&Array.isArray(value.bank_cash_accounts)&&Array.isArray(value.expense_accounts)&&Array.isArray(value.attachments)&&value.attachments.length<=100&&value.vendors.every(vendor)&&value.bank_cash_accounts.every(bankCash)&&value.expense_accounts.every(expenseAccount)&&value.attachments.every(attachment)&&new Set(value.vendors.map(row=>row.vendor_ref)).size===value.vendors.length&&new Set(value.bank_cash_accounts.map(row=>row.bank_member_ref+'\u0000'+row.cash_account_code)).size===value.bank_cash_accounts.length&&new Set(value.expense_accounts.map(row=>row.expense_account_code)).size===value.expense_accounts.length&&new Set(value.attachments.map(row=>row.attachment_id)).size===value.attachments.length;
